// nortear-design-system-svelte/src/components/ui/stepper/stepper-item.svelte
<script lang="ts">
	import type { HTMLLiAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "@/lib/utils.js";
	import {
		getStepperRootContext,
		resolveStepperState,
		setStepperItemContext,
		type StepperState,
	} from "./stepper-context.js";

	/**
	 * Uma etapa.
	 *
	 * O estado é DERIVADO, não escrito à mão: a etapa compara o próprio número
	 * com o valor do fluxo e chega sozinha a concluída, atual ou ainda não
	 * alcançada. `completed` explícito existe só para o fluxo que aceita ordem
	 * fora do comum.
	 *
	 * `data-state` e `data-disabled` moram AQUI porque é deles que a folha
	 * alcança o indicador e o traço sem regra extra.
	 */

	let {
		ref = $bindable(null),
		step,
		completed = false,
		disabled = false,
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLLiAttributes, HTMLLIElement> & {
		/** Número desta etapa, contando de 1. */
		step: number;
		/** Conta como concluída mesmo estando depois da atual. */
		completed?: boolean;
		/** Indisponível: o gatilho sai da ordem de tabulação. */
		disabled?: boolean;
	} = $props();

	const root = getStepperRootContext();

	const state: StepperState = $derived(resolveStepperState(step, root.value, completed));

	setStepperItemContext({
		get step() {
			return step;
		},
		get state() {
			return state;
		},
		get disabled() {
			return disabled;
		},
	});
</script>

<li
	bind:this={ref}
	{...restProps}
	data-slot="stepper-item"
	data-step={step}
	data-state={state}
	data-completed={completed ? "" : undefined}
	data-disabled={disabled ? "" : undefined}
	class={cn("nds-stepper-item", className)}
>
	{@render children?.()}
</li>

// nortear-design-system-vue/src/components/ui/stepper/StepperItem.vue
<script setup lang="ts">
import { computed, inject, provide, type HTMLAttributes } from 'vue';
import { cn } from '@/lib/utils';
import { STEPPER_ITEM_KEY, STEPPER_KEY, type StepperState } from './stepper.context';

/**
 * Uma etapa.
 *
 * O estado é DERIVADO da comparação entre o número desta etapa e o valor atual
 * do fluxo — `completed` explícito só é necessário quando o fluxo aceita ordem
 * fora do comum, e por isso vence a comparação.
 *
 * O traço vive DENTRO do item, depois do gatilho, como a folha documenta. É
 * isso que faz `.nds-stepper-item[data-state="completed"] .nds-stepper-separator`
 * alcançá-lo sem regra extra.
 */
const props = withDefaults(defineProps<{
  /** Número desta etapa, contando de 1. */
  step: number;
  /** Conta como concluída mesmo estando depois da atual. */
  completed?: boolean;
  /** Indisponível: o gatilho sai da ordem de tabulação. */
  disabled?: boolean;
  class?: HTMLAttributes['class'];
}>(), {
  completed: false,
  disabled: false,
});

const root = inject(STEPPER_KEY, null);

const state = computed<StepperState>(() => {
  const value = root?.value.value ?? 1;
  if (props.completed || props.step < value) return 'completed';
  if (props.step === value) return 'active';
  return 'inactive';
});

provide(STEPPER_ITEM_KEY, {
  step: computed(() => props.step),
  state,
  disabled: computed(() => props.disabled),
});
</script>

<template>
  <li
    data-slot="stepper-item"
    :data-step="step"
    :data-state="state"
    :data-completed="completed ? '' : undefined"
    :data-disabled="disabled ? '' : undefined"
    :class="cn('nds-stepper-item', props.class)"
  >
    <slot :state="state" />
  </li>
</template>
