// nortear-design-system-svelte/src/components/ui/stepper/stepper-indicator.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "@/lib/utils.js";
	import CheckIcon from "@lucide/svelte/icons/check";
	import { getStepperItemContext } from "./stepper-context.js";

	/**
	 * Círculo numerado.
	 *
	 * `aria-hidden` porque o número repete a posição que a `<ol>` já anuncia —
	 * ler os dois faz o leitor de tela dizer a mesma coisa duas vezes.
	 *
	 * A marca de verificação da etapa concluída é FORMA, não matiz: sobrevive a
	 * daltonismo e a tela monocromática. Quem não a vê ouve a palavra de estado
	 * que o gatilho carrega em `.nds-sr-only`.
	 *
	 * Com conteúdo próprio o indicador vira `data-custom` e a resolução para de
	 * escrevê-lo — senão a marca apagaria o ícone que o consumidor pôs ali.
	 */

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement> = $props();

	const item = getStepperItemContext();
</script>

<span
	bind:this={ref}
	{...restProps}
	data-slot="stepper-indicator"
	data-custom={children ? "" : undefined}
	aria-hidden="true"
	class={cn("nds-stepper-indicator", className)}
>
	{#if children}
		{@render children()}
	{:else if item.state === "completed"}
		<CheckIcon class="nds-icon" aria-hidden="true" />
	{:else}
		{item.step}
	{/if}
</span>

// nortear-design-system-vue/src/components/ui/stepper/StepperIndicator.vue
<script setup lang="ts">
import { computed, inject, type HTMLAttributes } from 'vue';
import { Check } from 'lucide-vue-next';
import { cn } from '@/lib/utils';
import { STEPPER_ITEM_KEY } from './stepper.context';

/**
 * Círculo numerado.
 *
 * `aria-hidden` porque o número repete a posição que a `<ol>` já anuncia — ler
 * os dois faz o leitor de tela dizer a mesma coisa duas vezes.
 *
 * Concluída, o número dá lugar a uma marca de verificação: é FORMA, e é ela que
 * mantém o estado legível em tela monocromática e para quem não distingue as
 * cores. Conteúdo próprio entra pelo slot e substitui os dois.
 */
const props = defineProps<{
  class?: HTMLAttributes['class'];
}>();

const item = inject(STEPPER_ITEM_KEY, null);

const state = computed(() => item?.state.value ?? 'inactive');
const step = computed(() => item?.step.value ?? 1);
</script>

<template>
  <span
    data-slot="stepper-indicator"
    aria-hidden="true"
    :class="cn('nds-stepper-indicator', props.class)"
  >
    <slot>
      <Check
        v-if="state === 'completed'"
        class="nds-icon"
      />
      <template v-else>
        {{ step }}
      </template>
    </slot>
  </span>
</template>
