// nortear-design-system-vue/src/components/ui/dialog/DialogContent.vue
<script setup lang="ts">
import type { DialogContentEmits, DialogContentProps } from 'reka-ui'

import type { HTMLAttributes } from 'vue'
import { computed } from 'vue'
import { reactiveOmit } from '@vueuse/core'
import { XIcon } from 'lucide-vue-next'
import {
  DialogClose,
  DialogContent,
  DialogPortal,
  injectDialogRootContext,
  useForwardPropsEmits,
} from 'reka-ui'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import DialogOverlay from './DialogOverlay.vue'

defineOptions({
  inheritAttrs: false,
})

/**
 * `closeLabel` é o nome acessível do X do canto. Vai como texto dentro de um
 * `<span class="nds-sr-only">` e não como `aria-label`: texto real sobrevive à
 * tradução automática da página, que ignora atributo. Existe porque o rótulo
 * estava CRAVADO em pt-BR aqui dentro, e o padrão o mantém para todo call site
 * que já existia.
 */
const props = withDefaults(defineProps<DialogContentProps & { class?: HTMLAttributes['class'], showCloseButton?: boolean, closeLabel?: string }>(), {
  showCloseButton: true,
  closeLabel: 'Fechar',
})
const emits = defineEmits<DialogContentEmits>()

// `showCloseButton` e `closeLabel` são deste wrapper, não do primitivo: sem
// tirá-los daqui o `v-bind` os despeja no elemento como atributos soltos
// (`showclosebutton="true"`, `closelabel="Fechar"`), que não significam nada
// para ninguém que lê o DOM.
const delegatedProps = reactiveOmit(props, 'class', 'showCloseButton', 'closeLabel')

const forwarded = useForwardPropsEmits(delegatedProps, emits)

// O primitivo desta stack isola o resto do documento com `aria-hidden` e NÃO
// emite `aria-modal` (conferido em node_modules). O contrato de markup do
// design system promete o atributo, então quem o emite é este wrapper — lendo
// do contexto da raiz para que um diálogo não-modal não o receba.
const rootContext = injectDialogRootContext()
const ariaModal = computed(() => (rootContext.modal.value ? 'true' : undefined))
</script>

<template>
  <DialogPortal>
    <DialogOverlay />
    <DialogContent
      data-slot="dialog-content"
      v-bind="{ 'aria-modal': ariaModal, 'aria-label': $attrs['aria-labelledby'] ? undefined : 'Dialog', ...$attrs, ...forwarded }"
      :class="cn('nds-dialog-content', props.class)"
    >
      <slot />

      <DialogClose
        v-if="showCloseButton"
        data-slot="dialog-close"
        as-child
      >
        <Button
          variant="ghost"
          class="nds-dialog-close-position"
          size="icon-sm"
        >
          <XIcon />
          <span class="nds-sr-only">{{ closeLabel }}</span>
        </Button>
      </DialogClose>
    </DialogContent>
  </DialogPortal>
</template>

// nortear-design-system-svelte/src/components/ui/dialog/dialog-content.svelte
<script lang="ts">
	import { Dialog as DialogPrimitive } from "bits-ui";
	import DialogPortal from "./dialog-portal.svelte";
	import type { Snippet } from "svelte";
	// Import direto do arquivo, e não `import * as Dialog from "./index.js"`:
	// pelo namespace o overlay entrava como `Dialog.Overlay` e nenhuma varredura
	// por nome enxergava o uso — a peça parecia exportada e nunca renderizada.
	import DialogOverlay from "./dialog-overlay.svelte";
	import { cn, type WithoutChildrenOrChild } from "@/lib/utils.js";
	import type { ComponentProps } from "svelte";
	import { Button } from "@/components/ui/button/index.js";
	import XIcon from '@lucide/svelte/icons/x';

	let {
		ref = $bindable(null),
		class: className,
		portalProps,
		children,
		showCloseButton = true,
		closeLabel = "Fechar",
		onClosePress,
		...restProps
	}: WithoutChildrenOrChild<DialogPrimitive.ContentProps> & {
		portalProps?: WithoutChildrenOrChild<ComponentProps<typeof DialogPortal>>;
		children: Snippet;
		showCloseButton?: boolean;
		/**
		 * Avisa que o X do canto foi acionado — é o `close-press` que o bits-ui
		 * NÃO publica. O `onOpenChange` diz que o diálogo fechou, nunca por onde;
		 * das quatro saídas, esta é a única que mora dentro deste wrapper, então
		 * é daqui que ela tem de sair. Quem escuta traduz em `DialogCloseReason`
		 * pelo `close-reason.ts` ao lado; o primitivo não conhece analytics.
		 *
		 * Fica FORA do `restProps` de propósito: espalhado no `Content` viraria
		 * atributo inválido no elemento do painel.
		 */
		onClosePress?: () => void;
		/**
		 * Nome acessível do X do canto. Vai num `<span class="nds-sr-only">` e não
		 * num `aria-label`: é o mecanismo que o conteúdo compartilhado documenta, e
		 * texto real sobrevive à tradução automática da página, que ignora
		 * `aria-label`.
		 *
		 * A prop existe porque o rótulo estava CRAVADO em português aqui dentro:
		 * quem consome o design system noutro idioma tinha de reescrever o
		 * primitivo para trocar uma palavra. O default preserva todo call site.
		 */
		closeLabel?: string;
	} = $props();
</script>

<DialogPortal {...portalProps}>
	<!--
		Overlay e painel são IRMÃOS, sempre: é o arranjo em que o painel fica fixo
		no centro sem depender do overlay para posicionar, e o véu não rola.
	-->
	<DialogOverlay />
	<DialogPrimitive.Content
		bind:ref
		data-slot="dialog-content"
		class={cn("nds-dialog-content", className)}
		{...restProps}
	>
		{@render children?.()}
		{#if showCloseButton}
			<!--
				O `onclick` vai no `DialogPrimitive.Close`, e não no `Button`: a lib
				faz `mergeProps(restProps, closeState.props)`, que ENCADEIA os dois
				manipuladores. Escrito depois do `{...props}` no botão, ele venceria
				o handler que fecha o diálogo — é o mesmo padrão que o Cancelar do
				rodapé desta família já encadeia à mão.
			-->
			<DialogPrimitive.Close data-slot="dialog-close" onclick={onClosePress}>
				{#snippet child({ props })}
					<Button variant="ghost" class="nds-dialog-close-position" size="icon-sm" {...props}>
						<XIcon  />
						<span class="nds-sr-only">{closeLabel}</span>
					</Button>
				{/snippet}
			</DialogPrimitive.Close>
		{/if}
	</DialogPrimitive.Content>
</DialogPortal>
