// nortear-design-system-vue/src/components/docs/SeparatorDocs.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { useTranslation } from '@/lib/i18n';
import { useSeoEffect } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { useActiveSection } from '@/lib/use-active-section';
import { Separator } from '@/components/ui/separator';
import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.vue';
import uiTranslations from '@/i18n/ui.json';
import separatorTranslations from '@shared/content/separator/translations.json';

import DocsHeader        from '@/components/docs/shared/sections/DocsHeader.vue';
import DocsDemonstration from '@/components/docs/shared/sections/DocsDemonstration.vue';
import DocsAnatomy       from '@/components/docs/shared/sections/DocsAnatomy.vue';
import DocsWhenToUse     from '@/components/docs/shared/sections/DocsWhenToUse.vue';
import DocsDoDont        from '@/components/docs/shared/sections/DocsDoDont.vue';
import DocsImport        from '@/components/docs/shared/sections/DocsImport.vue';
import DocsVariants      from '@/components/docs/shared/sections/DocsVariants.vue';
import DocsStates        from '@/components/docs/shared/sections/DocsStates.vue';
import DocsProps         from '@/components/docs/shared/sections/DocsProps.vue';
import DocsTokens        from '@/components/docs/shared/sections/DocsTokens.vue';
import DocsAccessibility from '@/components/docs/shared/sections/DocsAccessibility.vue';
import DocsRelated       from '@/components/docs/shared/sections/DocsRelated.vue';
import DocsNotes         from '@/components/docs/shared/sections/DocsNotes.vue';
import DocsAnalytics     from '@/components/docs/shared/sections/DocsAnalytics.vue';
import DocsTestes        from '@/components/docs/shared/sections/DocsTestes.vue';
import { stripHtml, toPlainText } from '@/lib/strip-html';

// ─── i18n ─────────────────────────────────────────────────────────────────────

const { t: tNav } = useTranslation(uiTranslations);
const { t: tContent, locale } = useTranslation(separatorTranslations);

// As chaves de `accessibility.screenReader` variam por componente, então só os
// valores chegam ao container — o `t()` exige nome de chave e não serviria.
// O `title` fica de fora: ele é o cabeçalho da lista, não um item dela.
const screenReaderItems = computed(() =>
  Object.entries(
    (separatorTranslations as unknown as Record<
      string,
      { accessibility?: { screenReader?: Record<string, string> } }
    >)[locale.value]?.accessibility?.screenReader ?? {},
  )
    .filter(([key]) => key !== 'title')
    .map(([, value]) => value),
);

// ─── Helpers ──────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function localPriority(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

// ─── SEO & GEO ────────────────────────────────────────────────────────────────

useSeoEffect(computed(() => ({
  title: tContent('seo.title'),
  description: tContent('seo.description'),
  locale: locale.value as 'pt-BR' | 'en' | 'es',
  componentSlug: 'separator',
})));

// ─── Analytics — page view ────────────────────────────────────────────────────

watch(locale, (newLocale) => {
  track('docs_page_view', {
    component_name: 'separator',
    locale: newLocale,
    page_title: `${tContent('title')} · Design System`,
  });
}, { immediate: true });

// ─── Analytics — section view ─────────────────────────────────────────────────

// ─── Navigation groups ────────────────────────────────────────────────────────

const navGroups = computed(() => [
  {
    label: tNav('nav.overview'),
    sections: [
      { id: 'demonstracao', label: tNav('nav.demonstration') },
      { id: 'anatomia',     label: tNav('nav.anatomy')      },
      { id: 'quando-usar',  label: tNav('nav.usage')        },
      { id: 'do-dont',      label: tNav('nav.doDont')       },
    ],
  },
  {
    label: tNav('nav.techRef'),
    sections: [
      { id: 'importacao',   label: tNav('nav.import')   },
      { id: 'variantes',    label: tNav('nav.variants') },
      { id: 'estados',      label: tNav('nav.states')   },
      { id: 'propriedades', label: tNav('nav.props')    },
      { id: 'tokens',       label: tNav('nav.tokens')   },
    ],
  },
  {
    label: tNav('nav.context'),
    sections: [
      { id: 'acessibilidade', label: tNav('nav.accessibility') },
      { id: 'relacionados',   label: tNav('nav.related')       },
      { id: 'notas',          label: tNav('nav.notes')         },
    ],
  },
  {
    label: tNav('nav.quality'),
    sections: [
      { id: 'analytics', label: tNav('nav.analytics') },
      { id: 'testes',    label: tNav('nav.testes')    },
    ],
  },
]);

const allSectionIds = computed(() => navGroups.value.flatMap(g => g.sections.map(s => s.id)));

const { activeId: activeSection } = useActiveSection(allSectionIds, (id) => {
  track('docs_section_viewed', {
    section_id: id,
    component_name: 'separator',
    locale: locale.value,
  });
});
// ─── Code strings ─────────────────────────────────────────────────────────────

const codeImportBasic = `import { Separator } from "@/components/ui/separator";`;

const horizontalCode = `<Separator orientation="horizontal" />`;

const verticalCode = `<div class="nds-cluster nds-docs-demo-row" data-spacing="md" data-align="center">
  <span>Início</span>
  <Separator orientation="vertical" />
  <span>Docs</span>
</div>`;

const codeCustomization = `/* Override de cor para tema customizado */
.theme-custom [data-slot='separator'] {
  background-color: hsl(var(--accent) / 0.4);
}`;

/** Linhas da tabela de tokens, na ordem em que a folha compartilhada as aplica. */
const TOKEN_ROWS = ['line', 'horizontal', 'vertical', 'emphasisColor', 'emphasisThickness'] as const;

const interfaceCode = `interface SeparatorProps {
  orientation?: 'horizontal' | 'vertical'; // default: 'horizontal'
  decorative?: boolean;                    // default: true
  emphasis?: 'default' | 'strong';         // default: 'default'
  class?: string;
}`;

const anatomyStructure = computed(() => tContent('anatomy.structureCode'));

// ─── Computed data ────────────────────────────────────────────────────────────

const anatomyItems = computed(() => [
  tContent('anatomy.item1'),
  tContent('anatomy.item2'),
  tContent('anatomy.item3'),
  tContent('anatomy.item4'),
]);

const variantItems = computed(() => [
  { trackId: 'horizontal', name: tContent('variants.items.horizontal'), description: stripHtml(tContent('variants.styles.horizontal')), code: horizontalCode },
  { trackId: 'vertical', name: tContent('variants.items.vertical'),   description: stripHtml(tContent('variants.styles.vertical')),   code: verticalCode   },
]);

const stateItems = computed(() => [
  { label: tContent('states.decorative.label'), trigger: toPlainText(tContent('states.decorative.trigger')), behavior: toPlainText(tContent('states.decorative.behavior')) },
  { label: tContent('states.semantic.label'),   trigger: toPlainText(tContent('states.semantic.trigger')),   behavior: toPlainText(tContent('states.semantic.behavior')) },
]);

const propCols = computed(() => ({
  prop: tContent('props.table.prop'),
  type: tContent('props.table.type'),
  default: tContent('props.table.default'),
  required: tContent('props.table.required'),
  description: tContent('props.table.description'),
}));

const separatorPropItems = computed(() => [
  { name: 'orientation', type: tContent('props.table.orientation.type'),  defaultValue: tContent('props.table.orientation.default'),  required: tContent('props.table.orientation.required'),  description: toPlainText(tContent('props.table.orientation.description')) },
  { name: 'decorative',  type: tContent('props.table.decorative.type'),   defaultValue: tContent('props.table.decorative.default'),   required: tContent('props.table.decorative.required'),   description: toPlainText(tContent('props.table.decorative.description'))  },
  { name: 'emphasis',    type: tContent('props.table.emphasis.type'),     defaultValue: tContent('props.table.emphasis.default'),     required: tContent('props.table.emphasis.required'),     description: toPlainText(tContent('props.table.emphasis.description'))     },
  { name: 'class',       type: tContent('props.table.className.type'),    defaultValue: tContent('props.table.className.default'),    required: tContent('props.table.className.required'),    description: toPlainText(tContent('props.table.className.description'))    },
]);

// Token, seletor e aplicação saem TODOS do conteúdo compartilhado. Antes cada
// stack escrevia a primeira coluna à mão, e as cinco divergiram: uma trazia
// `--border`, outra `bg-border`, outra o próprio seletor.
const tokenRows = computed(() =>
  TOKEN_ROWS.map((k) => ({
    token: tContent(`tokens.table.${k}.token`),
    value: tContent(`tokens.table.${k}.class`),
    description: tContent(`tokens.table.${k}.part`),
  })),
);

const accessibilityItems = computed(() => [
  tContent('accessibility.items.item1'),
  tContent('accessibility.items.item2'),
  tContent('accessibility.items.item3'),
  tContent('accessibility.items.item4'),
  tContent('accessibility.items.item5'),
]);

const keyboardItems = computed(() => [
  { key: '—',   description: tContent('accessibility.keyboard.noKeyboard')  },
  { key: 'Tab', description: tContent('accessibility.keyboard.description') },
]);

const relatedItems = computed(() => [
  { name: tContent('related.items.card.name'),           description: toPlainText(tContent('related.items.card.description')),           path: '?path=/docs/components-layout-card--docs'           },
  { name: tContent('related.items.sheet.name'),          description: toPlainText(tContent('related.items.sheet.description')),          path: '?path=/docs/components-overlay-sheet--docs'          },
  { name: tContent('related.items.sidebar.name'),        description: toPlainText(tContent('related.items.sidebar.description')),        path: '?path=/docs/components-layout-sidebar--docs'        },
  { name: tContent('related.items.navigationMenu.name'), description: toPlainText(tContent('related.items.navigationMenu.description')), path: '?path=/docs/components-navigation-navigationmenu--docs' },
]);

const noteItems = computed(() => [
  { title: '', content: tContent('notes.item1') },
  { title: '', content: tContent('notes.item2') },
  { title: '', content: tContent('notes.item3') },
  { title: '', content: tContent('notes.item4') },
]);

const analyticsItems = computed(() => [
  { event: '—', trigger: toPlainText(tContent('analytics.description')), payload: '—' },
]);

const a11yCritCols = computed(() => ({
  criterion: tNav('common.criterion'),
  level: 'WCAG',
  how: tNav('common.howToVerify'),
}));

const functionalTestItems = computed(() => [
  { action: toPlainText(tContent('testes.functional.item1.action')), result: toPlainText(tContent('testes.functional.item1.result')), priority: localPriority(tContent('testes.functional.item1.priority')) },
  { action: toPlainText(tContent('testes.functional.item2.action')), result: toPlainText(tContent('testes.functional.item2.result')), priority: localPriority(tContent('testes.functional.item2.priority')) },
  { action: toPlainText(tContent('testes.functional.item3.action')), result: toPlainText(tContent('testes.functional.item3.result')), priority: localPriority(tContent('testes.functional.item3.priority')) },
  { action: toPlainText(tContent('testes.functional.item4.action')), result: toPlainText(tContent('testes.functional.item4.result')), priority: localPriority(tContent('testes.functional.item4.priority')) },
  { action: toPlainText(tContent('testes.functional.item5.action')), result: toPlainText(tContent('testes.functional.item5.result')), priority: localPriority(tContent('testes.functional.item5.priority')) },
]);

const a11yTestItems = computed(() => [
  { criterion: tContent('testes.accessibility.item1'), level: 'AA', how: tContent('testes.accessibility.item1') },
  { criterion: tContent('testes.accessibility.item2'), level: 'AA', how: tContent('testes.accessibility.item2') },
  { criterion: tContent('testes.accessibility.item3'), level: 'AA', how: tContent('testes.accessibility.item3') },
  { criterion: tContent('testes.accessibility.item4'), level: 'AA', how: tContent('testes.accessibility.item4') },
  { criterion: tContent('testes.accessibility.item5'), level: 'AA', how: tContent('testes.accessibility.item5') },
]);

const visualTestItems = computed(() => [
  { story: tContent('testes.visual.item1.story'), priority: localPriority(tContent('testes.visual.item1.priority')) },
  { story: tContent('testes.visual.item2.story'), priority: localPriority(tContent('testes.visual.item2.priority')) },
  { story: tContent('testes.visual.item3.story'), priority: localPriority(tContent('testes.visual.item3.priority')) },
  { story: tContent('testes.visual.item4.story'), priority: localPriority(tContent('testes.visual.item4.priority')) },
  { story: tContent('testes.visual.item5.story'), priority: localPriority(tContent('testes.visual.item5.priority')) },
]);
</script>

<template>
  <DocsPageLayout
    :nav-groups="navGroups"
    :active-section="activeSection"
  >
    <template #header>
      <DocsHeader
        :title="tContent('title')"
        :description="tContent('description')"
        :category="tContent('category')"
        :type="tContent('type')"
      />
    </template>

    <!-- ── Demonstração ───────────────────────────────────────────── -->
    <DocsDemonstration :title="tContent('demonstration.title')">
      <div
        class="nds-grid nds-w-full"
        data-cols="2"
        data-spacing="lg"
      >
        <div
          class="nds-stack"
          data-spacing="sm"
        >
          <div
            class="nds-stack nds-rounded-md nds-border-default nds-p-4"
            data-spacing="sm"
          >
            <div class="nds-text-body nds-font-medium">
              Header
            </div>
            <Separator orientation="horizontal" />
            <div class="nds-text-caption nds-text-muted-foreground">
              Conteúdo separado por divisor horizontal.
            </div>
          </div>
          <p class="nds-text-caption nds-text-muted-foreground">
            {{ tContent('demonstration.labels.horizontal') }}
          </p>
        </div>

        <div
          class="nds-stack"
          data-spacing="sm"
        >
          <div
            class="nds-cluster nds-docs-demo-row nds-border-default nds-rounded-md nds-px-4 nds-text-body"
            data-spacing="md"
            data-align="center"
          >
            <span>Início</span>
            <Separator orientation="vertical" />
            <span>Docs</span>
            <Separator orientation="vertical" />
            <span>Sobre</span>
          </div>
          <p class="nds-text-caption nds-text-muted-foreground">
            {{ tContent('demonstration.labels.vertical') }}
          </p>
        </div>

        <div
          class="nds-stack"
          data-spacing="sm"
        >
          <div
            class="nds-stack nds-rounded-md nds-border-default nds-p-4 nds-text-body"
            data-spacing="sm"
          >
            <div class="nds-font-medium nds-text-caption nds-uppercase nds-text-muted-foreground">
              Categoria A
            </div>
            <div>Item 1</div>
            <div>Item 2</div>
            <Separator orientation="horizontal" />
            <div class="nds-font-medium nds-text-caption nds-uppercase nds-text-muted-foreground">
              Categoria B
            </div>
            <div>Item 3</div>
            <div>Item 4</div>
          </div>
          <p class="nds-text-caption nds-text-muted-foreground">
            {{ tContent('demonstration.labels.inMenu') }}
          </p>
        </div>

        <div
          class="nds-stack"
          data-spacing="sm"
        >
          <div class="nds-rounded-md nds-border-default nds-bg-card nds-text-card-foreground">
            <div class="nds-p-4 nds-text-body nds-font-medium">
              Card title
            </div>
            <Separator orientation="horizontal" />
            <div class="nds-p-4 nds-text-body nds-text-muted-foreground">
              Conteúdo do card abaixo do separator.
            </div>
            <Separator orientation="horizontal" />
            <div class="nds-p-4 nds-text-caption nds-text-muted-foreground">
              Footer do card.
            </div>
          </div>
          <p class="nds-text-caption nds-text-muted-foreground">
            {{ tContent('demonstration.labels.inCard') }}
          </p>
        </div>
      </div>
    </DocsDemonstration>

    <!-- ── Anatomia ───────────────────────────────────────────────── -->
    <DocsAnatomy
      :title="tContent('anatomy.title')"
      :items="anatomyItems"
      :structure-code="anatomyStructure"
    />

    <!-- ── Quando Usar ────────────────────────────────────────────── -->
    <DocsWhenToUse
      :title="tContent('usage.title')"
      :guidelines="{
        title: tContent('usage.guidelines.title'),
        items: [
          tContent('usage.guidelines.item1'),
          tContent('usage.guidelines.item2'),
          tContent('usage.guidelines.item3'),
          tContent('usage.guidelines.item4'),
          tContent('usage.guidelines.item5'),
        ],
      }"
      :scenarios="{
        title: tContent('usage.scenarios.title'),
        cols: {
          scenario: tContent('usage.scenarios.cols.scenario'),
          use: tContent('usage.scenarios.cols.use'),
          alternative: tContent('usage.scenarios.cols.alternative'),
        },
        items: [
          { s: tContent('usage.scenarios.item1.s'), u: tContent('usage.scenarios.item1.u'), a: tContent('usage.scenarios.item1.a') },
          { s: tContent('usage.scenarios.item2.s'), u: tContent('usage.scenarios.item2.u'), a: tContent('usage.scenarios.item2.a') },
          { s: tContent('usage.scenarios.item3.s'), u: tContent('usage.scenarios.item3.u'), a: tContent('usage.scenarios.item3.a') },
          { s: tContent('usage.scenarios.item4.s'), u: tContent('usage.scenarios.item4.u'), a: tContent('usage.scenarios.item4.a') },
          { s: tContent('usage.scenarios.item5.s'), u: tContent('usage.scenarios.item5.u'), a: tContent('usage.scenarios.item5.a') },
        ],
      }"
      :do="{
        title: tContent('usage.do.title'),
        items: [
          tContent('usage.do.item1'),
          tContent('usage.do.item2'),
          tContent('usage.do.item3'),
          tContent('usage.do.item4'),
        ],
      }"
      :dont="{
        title: tContent('usage.dont.title'),
        items: [
          tContent('usage.dont.item1'),
          tContent('usage.dont.item2'),
          tContent('usage.dont.item3'),
          tContent('usage.dont.item4'),
        ],
      }"
    />

    <!-- ── Do & Don't ─────────────────────────────────────────────── -->
    <DocsDoDont
      :title="tContent('doDont.title')"
      :pairs="[
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: toPlainText(tContent('doDont.pair1.do')), dontCaption: toPlainText(tContent('doDont.pair1.dont')) },
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: toPlainText(tContent('doDont.pair2.do')), dontCaption: toPlainText(tContent('doDont.pair2.dont')) },
      ]"
    >
      <template #do-preview-0>
        <div
          class="nds-stack nds-w-full nds-text-body nds-border-default nds-rounded-md nds-p-4"
          data-spacing="sm"
        >
          <div class="nds-font-medium">
            Grupo A
          </div>
          <Separator orientation="horizontal" />
          <div class="nds-font-medium">
            Grupo B
          </div>
        </div>
      </template>
      <template #dont-preview-0>
        <div
          class="nds-stack nds-w-full nds-text-body nds-border-default nds-rounded-md nds-p-4"
          data-spacing="sm"
        >
          <div>Item 1</div>
          <Separator orientation="horizontal" />
          <div>Item 2</div>
          <Separator orientation="horizontal" />
          <div>Item 3</div>
        </div>
      </template>
      <template #do-preview-1>
        <div
          class="nds-cluster nds-docs-demo-row nds-w-full nds-text-body nds-border-default nds-rounded-md nds-px-4"
          data-spacing="md"
          data-align="center"
        >
          <span>Início</span>
          <Separator orientation="vertical" />
          <span>Sobre</span>
        </div>
      </template>
      <template #dont-preview-1>
        <!-- Contêiner de BLOCO: é onde o separador vertical colapsa para 0px e
             some da tela sem erro nenhum. -->
        <div class="nds-block nds-w-full nds-max-w-sm nds-text-body nds-border-default nds-rounded-md nds-p-4">
          <span>Início</span>
          <Separator orientation="vertical" />
          <span>Sobre</span>
        </div>
      </template>
    </DocsDoDont>

    <!-- ── Importação ─────────────────────────────────────────────── -->
    <DocsImport
      :title="tContent('import.title')"
      :code="codeImportBasic"
    />

    <!-- ── Variantes ──────────────────────────────────────────────── -->
    <DocsVariants
      :title="tContent('variants.title')"
      :items="variantItems"
    >
      <template #variant-preview-0>
        <div
          class="nds-stack nds-w-full nds-text-body"
          data-spacing="sm"
        >
          <div>Conteúdo acima</div>
          <Separator orientation="horizontal" />
          <div>Conteúdo abaixo</div>
        </div>
      </template>
      <template #variant-preview-1>
        <div
          class="nds-cluster nds-docs-demo-row nds-w-full nds-text-body"
          data-spacing="md"
          data-align="center"
        >
          <span>A</span>
          <Separator orientation="vertical" />
          <span>B</span>
          <Separator orientation="vertical" />
          <span>C</span>
        </div>
      </template>
    </DocsVariants>

    <!-- ── Estados ─────────────────────────────────────────────────── -->
    <DocsStates
      :title="tContent('states.title')"
      :cols="{
        state: tContent('states.cols.state'),
        trigger: toPlainText(tContent('states.cols.trigger')),
        behavior: toPlainText(tContent('states.cols.behavior')),
      }"
      :items="stateItems"
    />

    <!-- ── Propriedades ───────────────────────────────────────────── -->
    <DocsProps
      :title="tContent('props.title')"
      :tables="[
        { title: 'Separator', cols: propCols, items: separatorPropItems },
      ]"
      :interface-code="interfaceCode"
      :extensibility-title="tContent('props.extensibilityTitle')"
      :extensibility-code="tContent('props.extensibilityCode')"
    />

    <!-- ── Tokens ─────────────────────────────────────────────────── -->
    <DocsTokens
      :title="tContent('tokens.title')"
      :cols="{
        token: tContent('tokens.table.token'),
        value: tContent('tokens.table.class'),
        description: tContent('tokens.table.part'),
      }"
      :items="tokenRows"
      :customization-title="tContent('tokens.customizationTitle')"
      :customization-code="tContent('tokens.customizationCode')"
    />

    <!-- ── Acessibilidade ─────────────────────────────────────────── -->
    <DocsAccessibility
      :screen-reader-title="tNav('common.screenReader')"
      :screen-reader-items="screenReaderItems"
      :title="tContent('accessibility.title')"
      :summary="tContent('accessibility.summary')"
      :items="accessibilityItems"
      :keyboard-title="tContent('accessibility.keyboard.title')"
      :keyboard-items="keyboardItems"
    />

    <!-- ── Relacionados ───────────────────────────────────────────── -->
    <DocsRelated
      :title="tContent('related.title')"
      :items="relatedItems"
    />

    <!-- ── Notas ──────────────────────────────────────────────────── -->
    <DocsNotes
      :title="tContent('notes.title')"
      :items="noteItems"
    />

    <!-- ── Analytics ─────────────────────────────────────────────── -->
    <DocsAnalytics
      :title="tContent('analytics.title')"
      :cols="{
        event: 'Evento',
        trigger: 'Quando dispara',
        payload: 'Payload',
      }"
      :items="analyticsItems"
    />

    <!-- ── Testes ─────────────────────────────────────────────────── -->
    <DocsTestes
      :title="tContent('testes.title')"
      :functional="{
        title: tContent('testes.functional.title'),
        cols: { action: tNav('common.userAction'), result: tNav('common.expectedResult'), priority: tNav('common.priority') },
        items: functionalTestItems,
      }"
      :accessibility="{
        title: tContent('testes.accessibility.title'),
        cols: a11yCritCols,
        items: a11yTestItems,
      }"
      :visual="{
        title: tContent('testes.visual.title'),
        cols: { story: tNav('common.storyState'), priority: tNav('common.priority') },
        items: visualTestItems,
      }"
    />
  </DocsPageLayout>
</template>

// nortear-design-system-react/src/components/docs/SeparatorDocs.tsx
import { useCallback, useEffect, useMemo } from "react";
import { Separator } from "@/components/ui/separator";
import { useTranslation } from "@/lib/i18n";
import { useSeoEffect } from "@/lib/use-seo";
import { track } from "@/lib/analytics";
import { useActiveSection } from "@/lib/use-active-section";
import uiTranslations from "@/i18n/ui.json";
import separatorTranslations from "@shared/content/separator/translations.json";

import { DocsHeader }        from "@/components/docs/shared/sections/DocsHeader";
import { DocsPageLayout }    from "@/components/docs/shared/sections/DocsPageLayout";
import { DocsDemonstration } from "@/components/docs/shared/sections/DocsDemonstration";
import { DocsAnatomy }       from "@/components/docs/shared/sections/DocsAnatomy";
import { DocsWhenToUse }     from "@/components/docs/shared/sections/DocsWhenToUse";
import { DocsDoDont }        from "@/components/docs/shared/sections/DocsDoDont";
import { DocsImport }        from "@/components/docs/shared/sections/DocsImport";
import { DocsVariants }      from "@/components/docs/shared/sections/DocsVariants";
import { DocsStates }        from "@/components/docs/shared/sections/DocsStates";
import { DocsProps }         from "@/components/docs/shared/sections/DocsProps";
import { DocsTokens }        from "@/components/docs/shared/sections/DocsTokens";
import { DocsAccessibility } from "@/components/docs/shared/sections/DocsAccessibility";
import { DocsRelated }       from "@/components/docs/shared/sections/DocsRelated";
import { DocsNotes }         from "@/components/docs/shared/sections/DocsNotes";
import { DocsAnalytics }     from "@/components/docs/shared/sections/DocsAnalytics";
import { DocsTestes }        from "@/components/docs/shared/sections/DocsTestes";
import { stripHtml, toPlainText } from "@/lib/strip-html";

// ─── Helpers ─────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: "common.high",
  medium: "common.medium",
  low: "common.low",
};

/** Linhas da tabela de tokens, na ordem em que a folha compartilhada as aplica. */
const TOKEN_ROWS = ["line", "horizontal", "vertical", "emphasisColor", "emphasisThickness"] as const;

// ─── Nav ─────────────────────────────────────────────────────────────────────

const getNavGroups = (t: (key: string) => string) => [
  {
    label: t("nav.overview"),
    sections: [
      { id: "demonstracao", label: t("nav.demonstration") },
      { id: "anatomia",     label: t("nav.anatomy") },
      { id: "quando-usar",  label: t("nav.usage") },
      { id: "do-dont",      label: t("nav.doDont") },
    ],
  },
  {
    label: t("nav.techRef"),
    sections: [
      { id: "importacao",   label: t("nav.import") },
      { id: "variantes",    label: t("nav.variants") },
      { id: "estados",      label: t("nav.states") },
      { id: "propriedades", label: t("nav.props") },
      { id: "tokens",       label: t("nav.tokens") },
    ],
  },
  {
    label: t("nav.context"),
    sections: [
      { id: "acessibilidade", label: t("nav.accessibility") },
      { id: "relacionados",   label: t("nav.related") },
      { id: "notas",          label: t("nav.notes") },
    ],
  },
  {
    label: t("nav.quality"),
    sections: [
      { id: "analytics", label: t("nav.analytics") },
      { id: "testes",    label: t("nav.testes") },
    ],
  },
];

// ─── Componente principal ─────────────────────────────────────────────────────

export function SeparatorDocs() {
  const { t: tNav } = useTranslation(uiTranslations);
  const { t: tContent, locale } = useTranslation(separatorTranslations);

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria.
  // O `title` fica de fora: ele é o cabeçalho da lista, não um item dela.
  const screenReaderItems = useMemo(
    () =>
      Object.entries(
        (separatorTranslations as unknown as Record<
          string,
          { accessibility?: { screenReader?: Record<string, string> } }
        >)[locale]?.accessibility?.screenReader ?? {},
      )
        .filter(([key]) => key !== "title")
        .map(([, value]) => value),
    [locale],
  );

  const navGroups = useMemo(() => getNavGroups(tNav), [tNav]);
  const allIds = useMemo(
    () => navGroups.flatMap((g) => g.sections.map((s) => s.id)),
    [navGroups]
  );

  useSeoEffect({
    title: tContent("seo.title"),
    description: tContent("seo.description"),
    locale,
    componentSlug: "separator",
  });

  useEffect(() => {
    track("docs_page_view", {
      component_name: "separator",
      locale,
      page_title: `${tContent("title")} · Design System`,
    });
  }, [locale, tContent]);

  const handleSectionChange = useCallback(
    (id: string) => {
      track("docs_section_viewed", {
        section_id: id,
        component_name: "separator",
        locale,
      });
    },
    [locale]
  );

  const activeId = useActiveSection(allIds, handleSectionChange);

  // ─── Code strings ───────────────────────────────────────────────────────────

  const codeImport = `import { Separator } from "@/components/ui/separator";`;

  const horizontalCode = `<div className="nds-stack nds-w-xs" data-spacing="md">
  <div>Item 1</div>
  <Separator orientation="horizontal" />
  <div>Item 2</div>
</div>`;

  const verticalCode = `<div className="nds-cluster nds-docs-demo-row" data-spacing="md" data-align="center">
  <span>Item 1</span>
  <Separator orientation="vertical" />
  <span>Item 2</span>
</div>`;

  const structureCode = tContent('anatomy.structureCode');

  const interfaceCode = `interface SeparatorProps extends React.HTMLAttributes<HTMLDivElement> {
  orientation?: "horizontal" | "vertical"; // padrão: "horizontal"
  decorative?: boolean;                    // padrão: true
  emphasis?: "default" | "strong";         // padrão: "default"
  className?: string;
}`;

  // ─── Locale-aware column labels ─────────────────────────────────────────────

  const analyticsCols = {
    event: locale === "en" ? "Event" : locale === "es" ? "Evento" : "Evento",
    trigger: locale === "en" ? "Trigger" : locale === "es" ? "Disparo" : "Disparo",
    payload: "Payload",
  };

  return (
    <DocsPageLayout
      navGroups={navGroups}
      activeSection={activeId}
      componentSlug="separator"
      header={
        <DocsHeader
          title={tContent("title")}
          description={tContent("description")}
          category={tContent("category")}
          type={tContent("type")}
        />
      }
    >
      {/* ── Demonstração ──────────────────────────────────────────── */}
      <DocsDemonstration >
        <div className="nds-grid nds-w-full" data-cols="2" data-spacing="lg">
          <div className="nds-stack" data-spacing="sm">
            <p className="nds-text-caption nds-font-medium nds-text-muted-foreground">
              {tContent("demonstration.labels.horizontal")}
            </p>
            <div className="nds-stack nds-w-full nds-text-body nds-border-default nds-rounded-md nds-p-4" data-spacing="sm">
              <div>Item 1</div>
              <Separator orientation="horizontal" />
              <div>Item 2</div>
            </div>
          </div>
          <div className="nds-stack" data-spacing="sm">
            <p className="nds-text-caption nds-font-medium nds-text-muted-foreground">
              {tContent("demonstration.labels.vertical")}
            </p>
            <div className="nds-cluster nds-docs-demo-row nds-text-body nds-border-default nds-rounded-md nds-px-4" data-spacing="md" data-align="center">
              <span>Item 1</span>
              <Separator orientation="vertical" />
              <span>Item 2</span>
              <Separator orientation="vertical" />
              <span>Item 3</span>
            </div>
          </div>
        </div>
      </DocsDemonstration>

      {/* ── Anatomia ──────────────────────────────────────────────── */}
      <DocsAnatomy
        items={[
          tContent("anatomy.item1"),
          tContent("anatomy.item2"),
          tContent("anatomy.item3"),
          tContent("anatomy.item4"),
        ]}
        structureCode={structureCode}
        structureLabel={tContent("anatomy.structureLabel")}
      />

      {/* ── Quando Usar ───────────────────────────────────────────── */}
      <DocsWhenToUse
        guidelines={{
          title: tContent("usage.guidelines.title"),
          items: [
            tContent("usage.guidelines.item1"),
            tContent("usage.guidelines.item2"),
            tContent("usage.guidelines.item3"),
            tContent("usage.guidelines.item4"),
            tContent("usage.guidelines.item5"),
          ],
        }}
        scenarios={{
          title: tContent("usage.scenarios.title"),
          cols: {
            scenario: tContent("usage.scenarios.cols.scenario"),
            use: tContent("usage.scenarios.cols.use"),
            alternative: tContent("usage.scenarios.cols.alternative"),
          },
          items: [
            { s: tContent("usage.scenarios.item1.s"), u: tContent("usage.scenarios.item1.u"), a: tContent("usage.scenarios.item1.a") },
            { s: tContent("usage.scenarios.item2.s"), u: tContent("usage.scenarios.item2.u"), a: tContent("usage.scenarios.item2.a") },
            { s: tContent("usage.scenarios.item3.s"), u: tContent("usage.scenarios.item3.u"), a: tContent("usage.scenarios.item3.a") },
            { s: tContent("usage.scenarios.item4.s"), u: tContent("usage.scenarios.item4.u"), a: tContent("usage.scenarios.item4.a") },
            { s: tContent("usage.scenarios.item5.s"), u: tContent("usage.scenarios.item5.u"), a: tContent("usage.scenarios.item5.a") },
          ],
        }}
        uxWriting={{
          title: tContent("usage.uxWriting.title"),
          cols: {
            element: tContent("usage.uxWriting.table.element"),
            rules: tContent("usage.uxWriting.table.rules"),
            do: tContent("usage.uxWriting.table.correct"),
            dont: tContent("usage.uxWriting.table.avoid"),
          },
          items: [
            {
              element: tContent("usage.uxWriting.table.decorativeChoice.name"),
              rules: tContent("usage.uxWriting.table.decorativeChoice.format"),
              do: tContent("usage.uxWriting.table.decorativeChoice.good"),
              dont: tContent("usage.uxWriting.table.decorativeChoice.bad"),
            },
            {
              element: tContent("usage.uxWriting.table.vsGap.name"),
              rules: tContent("usage.uxWriting.table.vsGap.format"),
              do: tContent("usage.uxWriting.table.vsGap.good"),
              dont: tContent("usage.uxWriting.table.vsGap.bad"),
            },
            {
              element: tContent("usage.uxWriting.table.vsBorder.name"),
              rules: tContent("usage.uxWriting.table.vsBorder.format"),
              do: tContent("usage.uxWriting.table.vsBorder.good"),
              dont: tContent("usage.uxWriting.table.vsBorder.bad"),
            },
            {
              element: tContent("usage.uxWriting.table.vertical.name"),
              rules: tContent("usage.uxWriting.table.vertical.format"),
              do: tContent("usage.uxWriting.table.vertical.good"),
              dont: tContent("usage.uxWriting.table.vertical.bad"),
            },
          ],
        }}
        do={{
          title: tContent("usage.do.title"),
          items: [
            tContent("usage.do.item1"),
            tContent("usage.do.item2"),
            tContent("usage.do.item3"),
            tContent("usage.do.item4"),
          ],
        }}
        dont={{
          title: tContent("usage.dont.title"),
          items: [
            tContent("usage.dont.item1"),
            tContent("usage.dont.item2"),
            tContent("usage.dont.item3"),
            tContent("usage.dont.item4"),
          ],
        }}
      />

      {/* ── Do & Don't ────────────────────────────────────────────── */}
      <DocsDoDont
        pairs={[
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doPreview: (
              <div className="nds-stack nds-w-full nds-text-body" data-spacing="sm">
                <div className="nds-font-medium">Header do Card</div>
                <Separator orientation="horizontal" />
                <div className="nds-text-muted-foreground">Conteúdo do Card</div>
              </div>
            ),
            dontPreview: (
              <div className="nds-stack nds-w-full nds-text-body" data-spacing="lg">
                <div className="nds-font-medium">Header do Card</div>
                <div className="nds-text-muted-foreground">Conteúdo do Card</div>
              </div>
            ),
            doCaption: stripHtml(tContent("doDont.pair1.do")),
            dontCaption: stripHtml(tContent("doDont.pair1.dont")),
          },
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doPreview: (
              <div className="nds-cluster nds-docs-demo-row nds-text-body" data-spacing="md" data-align="center">
                <a href="#" className="nds-text-primary">Link 1</a>
                <Separator orientation="vertical" />
                <a href="#" className="nds-text-primary">Link 2</a>
                <Separator orientation="vertical" />
                <a href="#" className="nds-text-primary">Link 3</a>
              </div>
            ),
            dontPreview: (
              // Contêiner de BLOCO: é onde o separador vertical colapsa para 0px
              // e some da tela sem erro nenhum. Antes este exemplo usava um
              // contêiner flex, onde a linha aparece — o "não faça" mostrava o
              // caso funcionando e contradizia a própria legenda.
              <div className="nds-block nds-w-full nds-max-w-sm nds-text-body">
                <a href="#" className="nds-text-primary">Link 1</a>
                <Separator orientation="vertical" />
                <a href="#" className="nds-text-primary">Link 2</a>
              </div>
            ),
            doCaption: stripHtml(tContent("doDont.pair2.do")),
            dontCaption: stripHtml(tContent("doDont.pair2.dont")),
          },
        ]}
      />

      {/* ── Importação ────────────────────────────────────────────── */}
      <DocsImport componentSlug="separator" code={codeImport} />

      {/* ── Variantes ─────────────────────────────────────────────── */}
      <DocsVariants
        componentSlug="separator"
        items={[
          {
            trackId: "horizontal",
            name: tContent("variants.items.horizontal"),
            description: stripHtml(tContent("variants.styles.horizontal")),
            code: horizontalCode,
            preview: (
              <div className="nds-stack nds-w-xs nds-text-body" data-spacing="sm">
                <div>Seção superior</div>
                <Separator orientation="horizontal" />
                <div>Seção inferior</div>
              </div>
            ),
          },
          {
            trackId: "vertical",
            name: tContent("variants.items.vertical"),
            description: stripHtml(tContent("variants.styles.vertical")),
            code: verticalCode,
            preview: (
              <div className="nds-cluster nds-docs-demo-row nds-text-body" data-spacing="md" data-align="center">
                <span>Item 1</span>
                <Separator orientation="vertical" />
                <span>Item 2</span>
              </div>
            ),
          },
        ]}
      />

      {/* ── Estados ───────────────────────────────────────────────── */}
      <DocsStates
        cols={{
          state: tContent("states.cols.state"),
          trigger: toPlainText(tContent("states.cols.trigger")),
          behavior: toPlainText(tContent("states.cols.behavior")),
        }}
        items={[
          {
            label: tContent("states.decorative.label"),
            trigger: toPlainText(tContent("states.decorative.trigger")),
            behavior: toPlainText(tContent("states.decorative.behavior")),
          },
          {
            label: tContent("states.semantic.label"),
            trigger: toPlainText(tContent("states.semantic.trigger")),
            behavior: toPlainText(tContent("states.semantic.behavior")),
          },
        ]}
      />

      {/* ── Propriedades ──────────────────────────────────────────── */}
      <DocsProps
        tables={[
          {
            cols: {
              prop: tContent("props.table.prop"),
              type: tContent("props.table.type"),
              default: tContent("props.table.default"),
              required: tContent("props.table.required"),
              description: tContent("props.table.description"),
            },
            items: [
              {
                name: "orientation",
                type: tContent("props.table.orientation.type"),
                defaultValue: tContent("props.table.orientation.default"),
                required: tContent("props.table.orientation.required"),
                description: toPlainText(tContent("props.table.orientation.description")),
              },
              {
                name: "decorative",
                type: tContent("props.table.decorative.type"),
                defaultValue: tContent("props.table.decorative.default"),
                required: tContent("props.table.decorative.required"),
                description: toPlainText(tContent("props.table.decorative.description")),
              },
              {
                name: "emphasis",
                type: tContent("props.table.emphasis.type"),
                defaultValue: tContent("props.table.emphasis.default"),
                required: tContent("props.table.emphasis.required"),
                description: toPlainText(tContent("props.table.emphasis.description")),
              },
              {
                name: "className",
                type: tContent("props.table.className.type"),
                defaultValue: tContent("props.table.className.default"),
                required: tContent("props.table.className.required"),
                description: toPlainText(tContent("props.table.className.description")),
              },
            ],
          },
        ]}
        interfaceCode={interfaceCode}
        extensibilityTitle={tContent("props.extensibilityTitle")}
        extensibilityCode={tContent("props.extensibilityCode")}
      />

      {/* ── Tokens ────────────────────────────────────────────────── */}
      <DocsTokens
        cols={{
          token: tContent("tokens.table.token"),
          value: tContent("tokens.table.class"),
          description: tContent("tokens.table.part"),
        }}
        // Token, seletor e aplicação saem TODOS do conteúdo compartilhado. Antes
        // cada stack escrevia a primeira coluna à mão, e as cinco divergiram: uma
        // trazia `--border`, outra `bg-border`, outra o próprio seletor.
        items={TOKEN_ROWS.map((k) => ({
          token: tContent(`tokens.table.${k}.token`),
          value: tContent(`tokens.table.${k}.class`),
          description: tContent(`tokens.table.${k}.part`),
        }))}
        customizationTitle={tContent("tokens.customizationTitle")}
        customizationCode={tContent("tokens.customizationCode")}
      />

      {/* ── Acessibilidade ────────────────────────────────────────── */}
      <DocsAccessibility
        screenReaderTitle={tNav("common.screenReader")}
        screenReaderItems={screenReaderItems}
        summary={tContent("accessibility.summary")}
        items={[
          tContent("accessibility.items.item1"),
          tContent("accessibility.items.item2"),
          tContent("accessibility.items.item3"),
          tContent("accessibility.items.item4"),
          tContent("accessibility.items.item5"),
        ]}
        keyboardTitle={tContent("accessibility.keyboard.title")}
        keyboardItems={[
          { key: "—", description: tContent("accessibility.keyboard.noKeyboard") },
          { key: "Tab", description: tContent("accessibility.keyboard.description") },
        ]}
      />

      {/* ── Relacionados ──────────────────────────────────────────── */}
      <DocsRelated
        componentSlug="separator"
        items={[
          {
            name: tContent("related.items.card.name"),
            description: toPlainText(tContent("related.items.card.description")),
            path: "?path=/docs/components-layout-card--docs",
          },
          {
            name: tContent("related.items.sheet.name"),
            description: toPlainText(tContent("related.items.sheet.description")),
            path: "?path=/docs/components-overlay-sheet--docs",
          },
          {
            name: tContent("related.items.sidebar.name"),
            description: toPlainText(tContent("related.items.sidebar.description")),
            path: "?path=/docs/components-layout-sidebar--docs",
          },
          {
            name: tContent("related.items.navigationMenu.name"),
            description: toPlainText(tContent("related.items.navigationMenu.description")),
            path: "?path=/docs/components-navigation-navigationmenu--docs",
          },
        ]}
      />

      {/* ── Notas ─────────────────────────────────────────────────── */}
      <DocsNotes
        componentSlug="separator"
        items={[
          { title: "", content: tContent("notes.item1") },
          { title: "", content: tContent("notes.item2") },
          { title: "", content: tContent("notes.item3") },
          { title: "", content: tContent("notes.item4") },
        ]}
      />

      {/* ── Analytics ─────────────────────────────────────────────── */}
      <DocsAnalytics
        cols={analyticsCols}
        items={[
          {
            event: "—",
            trigger: toPlainText(tContent("analytics.description")),
            payload: "—",
          },
        ]}
      />

      {/* ── Testes ────────────────────────────────────────────────── */}
      <DocsTestes
        functional={{
          title: tContent("testes.functional.title"),
          cols: {
            action: tNav("common.userAction"),
            result: tNav("common.expectedResult"),
            priority: tNav("common.priority"),
          },
          items: [
            {
              action: tContent("testes.functional.item1.action"),
              result: tContent("testes.functional.item1.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item1.priority")] ?? "common.high"),
            },
            {
              action: tContent("testes.functional.item2.action"),
              result: tContent("testes.functional.item2.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item2.priority")] ?? "common.high"),
            },
            {
              action: tContent("testes.functional.item3.action"),
              result: tContent("testes.functional.item3.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item3.priority")] ?? "common.high"),
            },
            {
              action: tContent("testes.functional.item4.action"),
              result: tContent("testes.functional.item4.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item4.priority")] ?? "common.high"),
            },
            {
              action: tContent("testes.functional.item5.action"),
              result: tContent("testes.functional.item5.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item5.priority")] ?? "common.medium"),
            },
          ],
        }}
        accessibility={{
          title: tContent("testes.accessibility.title"),
          cols: {
            criterion: tNav("common.criterion"),
            level: "WCAG",
            how: tNav("common.howToVerify"),
          },
          items: [
            { criterion: tContent("testes.accessibility.item1"), level: "AA", how: "axe-core" },
            { criterion: tContent("testes.accessibility.item2"), level: "1.4.11", how: "Contrast checker" },
            { criterion: tContent("testes.accessibility.item3"), level: "AA", how: "DevTools a11y tree" },
            { criterion: tContent("testes.accessibility.item4"), level: "1.3.1", how: "DevTools a11y tree" },
            { criterion: tContent("testes.accessibility.item5"), level: "2.1.1", how: "Tab keyboard" },
          ],
        }}
        visual={{
          title: tContent("testes.visual.title"),
          cols: {
            story: tNav("common.storyState"),
            priority: tNav("common.priority"),
          },
          items: [
            { story: tContent("testes.visual.item1.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item1.priority")] ?? "common.high") },
            { story: tContent("testes.visual.item2.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item2.priority")] ?? "common.high") },
            { story: tContent("testes.visual.item3.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item3.priority")] ?? "common.high") },
            { story: tContent("testes.visual.item4.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item4.priority")] ?? "common.medium") },
            { story: tContent("testes.visual.item5.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item5.priority")] ?? "common.medium") },
          ],
        }}
      />
    </DocsPageLayout>
  );
}

export default SeparatorDocs;
