// nortear-design-system-svelte/src/components/ui/input-group/input-group-textarea.svelte
<script lang="ts">
	import { cn } from "@/lib/utils.js";
	import { Textarea } from "@/components/ui/textarea/index.js";
	import type { ComponentProps } from "svelte";

	let {
		ref = $bindable(null),
		value = $bindable(),
		class: className,
		...props
	}: ComponentProps<typeof Textarea> = $props();
</script>

<Textarea
	bind:ref
	data-slot="input-group-control"
	class={cn("nds-input-group-control", className)}
	bind:value
	{...props}
/>

// design-system-vue/src/components/ui/input-group/InputGroupTextarea.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'
import { Textarea } from '@/components/ui/textarea'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <Textarea
    data-slot="input-group-control"
    :class="cn(
      'nds-input-group-control',
      props.class,
    )"
  />
</template>
