// nortear-design-system-svelte/src/components/docs/EditorDocs.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { Editor } from '@/components/ui/editor';
  import { Button } from '@/components/ui/button';
  import {
    CONTENTS,
    editorLabelsFor,
    nounLabelsFor,
  } from '@/components/ui/editor/editor.fixtures';
  import {
    editorAdvancedSource,
    editorBasicSource,
  } from '@/components/ui/editor/editor.source';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import { createActiveSection } from '@/lib/use-active-section.svelte';
  import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader, DocsDemonstration, DocsAnatomy, DocsWhenToUse, DocsDoDont,
    DocsImport, DocsVariants, DocsStates, DocsProps, DocsTokens,
    DocsAccessibility, DocsRelated, DocsNotes, DocsAnalytics, DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import editorTranslations from '@shared/content/editor/translations.json';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(editorTranslations);

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'editor',
      aiSummary: t('seo.aiSummary'),
      aiEntities: t('seo.aiEntities'),
      breadcrumb: [
        { name: 'Components', item: '/components' },
        { name: t('category'), item: '/components/form' },
        { name: t('title') },
      ],
    });
    track('docs_page_view', {
      component_name: 'editor',
      locale: l,
      page_title: `${t('title')} · Design System`,
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────

  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')   },
        { id: 'variantes',    label: tNav('nav.variants') },
        { id: 'estados',      label: tNav('nav.states')   },
        { id: 'propriedades', label: tNav('nav.props')    },
        { id: 'tokens',       label: tNav('nav.tokens')   },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  const sectionIds = untrack(() => NAV_GROUPS.flatMap(g => g.sections.map(s => s.id)));
  const section = createActiveSection(sectionIds, (id) => {
    track('docs_section_viewed', { section_id: id, component_name: 'editor', locale: $locale });
  });
  $effect(() => section.attach());

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  const priorityKeyMap: Record<string, string> = {
    high: 'common.high', medium: 'common.medium', low: 'common.low',
  };
  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  /** Estados do conteúdo compartilhado, na ordem em que ele os lista. */
  const STATE_KEYS = [
    'editing', 'readOnly', 'imageSelected', 'inTable', 'fieldOpen', 'invalidValue',
  ] as const;

  /** Chaves da tabela de tokens, na ordem em que o conteúdo as declara. */
  const TOKEN_KEYS = [
    'border', 'background', 'muted', 'mutedForeground', 'foreground',
    'primary', 'accent', 'ring', 'textH1',
  ] as const;

  // ─── Rótulos da barra ────────────────────────────────────────────────────────
  //
  // Os 51 rótulos vêm do conteúdo compartilhado, no idioma da página. Antes
  // vinham de um objeto local em pt-BR — inclusive `editorField`, o nome
  // acessível da área editável: a página trocava de idioma e a interface que ela
  // demonstra continuava em português para quem ouve.

  const barLabels = $derived(editorLabelsFor($locale));

  /** Os mesmos rótulos com o SUBSTANTIVO no lugar do verbo — o par 1 do Do & Don't. */
  const nounBarLabels = $derived(nounLabelsFor($locale));

  // ─── Demonstração ────────────────────────────────────────────────────────────
  //
  // Dois EIXOS independentes, e não uma escolha de três: o conjunto (básico ou
  // avançado) e a edição ligada ou desligada são perguntas diferentes. Como
  // escolha única, "somente leitura" excluía o conjunto escolhido — não dava para
  // ver o conjunto avançado em leitura, que é justamente o estado que a seção de
  // estados descreve.
  //
  // O evento sai do PRÓPRIO botão, por `data-track`: o observer do
  // DocsPageLayout resolve por `.closest('[data-track]')`, e sem marcação no
  // controle ele subia até o container da seção e disparava um segundo
  // `docs_demo_click` com o rótulo TRADUZIDO no `element_id` — o mesmo clique
  // contado duas vezes, e a segunda partida em três valores no GA4.

  let demoPreset = $state<'basic' | 'advanced'>('advanced');
  let demoEditable = $state(true);

  const demoControls = $derived([
    {
      key: 'basic',
      label: $tStore('demonstration.labels.basic'),
      pressed: demoPreset === 'basic',
      apply: () => { demoPreset = 'basic'; },
    },
    {
      key: 'advanced',
      label: $tStore('demonstration.labels.advanced'),
      pressed: demoPreset === 'advanced',
      apply: () => { demoPreset = 'advanced'; },
    },
    {
      key: 'readOnly',
      label: $tStore('demonstration.labels.readOnly'),
      pressed: !demoEditable,
      apply: () => { demoEditable = !demoEditable; },
    },
  ]);

  // ─── Código dos exemplos ─────────────────────────────────────────────────────
  //
  // O mesmo construtor que alimenta o painel Code das stories: um lugar só para
  // o snippet do conjunto básico e o do avançado.
  const codeBasic = editorBasicSource();
  const codeAdvanced = editorAdvancedSource();

  const interfaceCode = `interface EditorProps {
  content?: string;
  editable?: boolean;
  preset?: "basic" | "advanced";
  labels: EditorLabels;
  resolveImage?: (file: File) => Promise<string | null>;
  describeImage?: (file: File | null, src: string) => Promise<string | null>;
  onchange?: (html: string) => void;
  class?: string;
}`;

  /** Conteúdo dos dois pares de boas práticas — o mesmo nos quatro previews. */
  const DO_DONT_CONTENT = '<p>Ótimo trabalho, obrigado!</p>';
</script>

<DocsPageLayout navGroups={NAV_GROUPS} activeSection={section.value} componentSlug="editor">
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
    />
  {/snippet}

  <!-- ── Demonstração ───────────────────────────────────────────── -->
  <DocsDemonstration title={$tStore('demonstration.title')} componentSlug="editor">
    <div class="nds-stack nds-w-full" data-spacing="md">
      <div class="nds-cluster" data-spacing="sm" role="group" aria-label={$tStore('demonstration.title')}>
        {#each demoControls as control (control.key)}
          <Button
            variant="outline"
            size="sm"
            aria-pressed={control.pressed}
            data-track="demo"
            data-track-id={`editor:demonstracao:${control.key}`}
            data-track-label={control.label}
            onclick={control.apply}
          >
            {control.label}
          </Button>
        {/each}
      </div>

      <Editor
        content={CONTENTS.playground}
        preset={demoPreset}
        editable={demoEditable}
        labels={barLabels}
        class="nds-w-full"
      />
    </div>
  </DocsDemonstration>

  <!-- ── Anatomia ───────────────────────────────────────────────── -->
  <DocsAnatomy
    title={$tStore('anatomy.title')}
    items={[
      $tStore('anatomy.item1'),
      $tStore('anatomy.item2'),
      $tStore('anatomy.item3'),
      $tStore('anatomy.item4'),
      $tStore('anatomy.item5'),
      $tStore('anatomy.item6'),
      $tStore('anatomy.item7'),
    ]}
    structureLabel={$tStore('anatomy.structureLabel')}
    structureCode={$tStore('anatomy.structureCode')}
    language="html"
  />

  <!-- ── Quando Usar ────────────────────────────────────────────── -->
  <DocsWhenToUse
    title={$tStore('usage.title')}
    guidelines={{
      title: $tStore('usage.guidelines.title'),
      items: [1, 2, 3, 4, 5].map((n) => $tStore(`usage.guidelines.item${n}`)),
    }}
    scenarios={{
      title: $tStore('usage.scenarios.title'),
      cols: {
        scenario: $tStore('usage.scenarios.cols.scenario'),
        use: $tStore('usage.scenarios.cols.use'),
        alternative: $tStore('usage.scenarios.cols.alternative'),
      },
      items: [1, 2, 3, 4, 5, 6].map((n) => ({
        s: $tStore(`usage.scenarios.item${n}.s`),
        u: $tStore(`usage.scenarios.item${n}.u`),
        a: $tStore(`usage.scenarios.item${n}.a`),
      })),
    }}
    do={{
      title: $tNavStore('common.do'),
      items: [
        $tStore('usage.do.item1'),
        $tStore('usage.do.item2'),
        $tStore('usage.do.item3'),
        $tStore('usage.do.item4'),
      ],
    }}
    dont={{
      title: $tNavStore('common.dont'),
      items: [
        $tStore('usage.dont.item1'),
        $tStore('usage.dont.item2'),
        $tStore('usage.dont.item3'),
        $tStore('usage.dont.item4'),
      ],
    }}
  />

  <!-- ── Do & Don't ─────────────────────────────────────────────── -->
  <DocsDoDont
    title={$tStore('doDont.title')}
    pairs={[
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair1.do'),
        dontCaption: $tStore('doDont.pair1.dont'),
        doPreview: doPair1,
        dontPreview: dontPair1,
      },
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair2.do'),
        dontCaption: $tStore('doDont.pair2.dont'),
        doPreview: doPair2,
        dontPreview: dontPair2,
      },
    ]}
  />

  <!-- Os dois editores do par 1 diferem em UM rótulo, o do botão de link:
       `labels.actions.link` ("Inserir link") de um lado, `labels.nouns.link`
       ("Link") do outro, os dois vindos do conteúdo compartilhado. É exatamente
       o que a legenda deste par contrasta, e um segundo texto diferente daria à
       comparação uma segunda variável. -->
  {#snippet doPair1()}
    <Editor content={DO_DONT_CONTENT} preset="basic" labels={barLabels} class="nds-w-full" />
  {/snippet}
  {#snippet dontPair1()}
    <Editor
      content={DO_DONT_CONTENT}
      preset="basic"
      labels={nounBarLabels}
      class="nds-w-full"
    />
  {/snippet}

  {#snippet doPair2()}
    <Editor content={DO_DONT_CONTENT} preset="basic" labels={barLabels} class="nds-w-full" />
  {/snippet}
  {#snippet dontPair2()}
    <Editor content={DO_DONT_CONTENT} preset="advanced" labels={barLabels} class="nds-w-full" />
  {/snippet}

  <!-- ── Importação ─────────────────────────────────────────────── -->
  <DocsImport
    title={$tStore('import.title')}
    description={$tStore('import.basic')}
    code={$tStore('import.basicCode')}
    secondaryDescription={$tStore('import.withStorage')}
    secondaryCode={$tStore('import.withStorageCode')}
    componentSlug="editor"
    copyLabel={$tNavStore('common.copy')}
    copiedLabel={$tNavStore('common.copied')}
  />

  <!-- ── Conjuntos ──────────────────────────────────────────────── -->
  <DocsVariants
    title={$tStore('variants.title')}
    note={$tStore('variants.note')}
    componentSlug="editor"
    copyLabel={$tNavStore('common.copy')}
    copiedLabel={$tNavStore('common.copied')}
    items={[
      {
        name: $tStore('variants.items.basic.name'),
        // A chave ESTÁVEL, e não o nome traduzido: é ela que vira `snippet_id`
        // do `docs_code_copy`, e um nome traduzido partiria o mesmo evento em
        // três valores no GA4.
        trackId: 'basic',
        description: $tStore('variants.items.basic.description'),
        code: codeBasic,
        preview: variantBasic,
      },
      {
        name: $tStore('variants.items.advanced.name'),
        trackId: 'advanced',
        description: $tStore('variants.items.advanced.description'),
        code: codeAdvanced,
        preview: variantAdvanced,
      },
    ]}
  />

  {#snippet variantBasic()}
    <Editor content={CONTENTS.basic} preset="basic" labels={barLabels} class="nds-w-full" />
  {/snippet}
  {#snippet variantAdvanced()}
    <Editor content={CONTENTS.advanced} preset="advanced" labels={barLabels} class="nds-w-full" />
  {/snippet}

  <!-- ── Estados ────────────────────────────────────────────────── -->
  <DocsStates
    title={$tStore('states.title')}
    cols={{
      state: $tStore('states.cols.state'),
      trigger: $tStore('states.cols.trigger'),
      behavior: $tStore('states.cols.behavior'),
    }}
    items={STATE_KEYS.map((key) => ({
      label: $tStore(`states.${key}.label`),
      trigger: $tStore(`states.${key}.trigger`),
      behavior: $tStore(`states.${key}.behavior`),
    }))}
  />

  <!-- ── Propriedades ───────────────────────────────────────────── -->
  <DocsProps
    title={$tStore('props.title')}
    tables={[
      {
        cols: {
          prop: $tStore('props.table.prop'),
          type: $tStore('props.table.type'),
          default: $tStore('props.table.default'),
          required: $tStore('props.table.required'),
          description: $tStore('props.table.description'),
        },
        items: [
          { name: $tStore('props.table.content.name'),       type: $tStore('props.table.content.type'),       defaultValue: $tStore('props.table.content.default'),       required: $tStore('props.table.content.required'),       description: $tStore('props.table.content.description') },
          { name: $tStore('props.table.editable.name'),      type: $tStore('props.table.editable.type'),      defaultValue: $tStore('props.table.editable.default'),      required: $tStore('props.table.editable.required'),      description: $tStore('props.table.editable.description') },
          { name: $tStore('props.table.preset.name'),        type: $tStore('props.table.preset.type'),        defaultValue: $tStore('props.table.preset.default'),        required: $tStore('props.table.preset.required'),        description: $tStore('props.table.preset.description') },
          { name: $tStore('props.table.labels.name'),        type: $tStore('props.table.labels.type'),        defaultValue: $tStore('props.table.labels.default'),        required: $tStore('props.table.labels.required'),        description: $tStore('props.table.labels.description') },
          // O nome do callback é o desta stack; a descrição é compartilhada.
          { name: 'onchange',                                type: $tStore('props.table.onChange.type'),      defaultValue: $tStore('props.table.onChange.default'),      required: $tStore('props.table.onChange.required'),      description: $tStore('props.table.onChange.description') },
          { name: $tStore('props.table.resolveImage.name'),  type: $tStore('props.table.resolveImage.type'),  defaultValue: $tStore('props.table.resolveImage.default'),  required: $tStore('props.table.resolveImage.required'),  description: $tStore('props.table.resolveImage.description') },
          { name: $tStore('props.table.describeImage.name'), type: $tStore('props.table.describeImage.type'), defaultValue: $tStore('props.table.describeImage.default'), required: $tStore('props.table.describeImage.required'), description: $tStore('props.table.describeImage.description') },
        ],
      },
    ]}
    interfaceCode={interfaceCode}
    extensibilityTitle={$tStore('props.extensibilityTitle')}
    extensibilityNotes={$tStore('props.extensibility')}
    extensibilityCode={$tStore('props.extensibilityCode')}
    copyLabel={$tNavStore('common.copy')}
    copiedLabel={$tNavStore('common.copied')}
  />

  <!-- ── Tokens ─────────────────────────────────────────────────── -->
  <DocsTokens
    title={$tStore('tokens.title')}
    cols={{
      token: $tStore('tokens.table.token'),
      value: $tStore('tokens.table.value'),
      description: $tStore('tokens.table.description'),
    }}
    items={TOKEN_KEYS.map((key) => ({
      token: $tStore(`tokens.table.${key}.token`),
      value: $tStore(`tokens.table.${key}.value`),
      description: $tStore(`tokens.table.${key}.description`),
    }))}
    customizationTitle={$tStore('tokens.customizationTitle')}
    customizationCode={$tStore('tokens.customizationCode')}
    copyLabel={$tNavStore('common.copy')}
    copiedLabel={$tNavStore('common.copied')}
  />

  <!-- ── Acessibilidade ─────────────────────────────────────────── -->
  <DocsAccessibility
    title={$tStore('accessibility.title')}
    summary={$tStore('accessibility.summary')}
    items={[
      $tStore('accessibility.item1'),
      $tStore('accessibility.item2'),
      $tStore('accessibility.item3'),
      $tStore('accessibility.item4'),
      $tStore('accessibility.item5'),
      $tStore('accessibility.item6'),
      $tStore('accessibility.item7'),
    ]}
    keyboardTitle={$tStore('accessibility.keyboardTitle')}
    keyboardItems={[
      { key: $tStore('accessibility.keyboard.tab.key'),      description: $tStore('accessibility.keyboard.tab.action')      },
      { key: $tStore('accessibility.keyboard.arrows.key'),   description: $tStore('accessibility.keyboard.arrows.action')   },
      { key: $tStore('accessibility.keyboard.homeEnd.key'),  description: $tStore('accessibility.keyboard.homeEnd.action')  },
      { key: $tStore('accessibility.keyboard.enter.key'),    description: $tStore('accessibility.keyboard.enter.action')    },
      { key: $tStore('accessibility.keyboard.escape.key'),   description: $tStore('accessibility.keyboard.escape.action')   },
    ]}
  />

  <!-- ── Relacionados ───────────────────────────────────────────── -->
  <DocsRelated
    title={$tStore('related.title')}
    componentSlug="editor"
    items={[
      { name: 'Textarea',    description: $tStore('related.textarea'),    path: '?path=/docs/primitives-form-textarea--docs'    },
      { name: 'CodeBlock',   description: $tStore('related.codeBlock'),   path: '?path=/docs/primitives-display-codeblock--docs'   },
      { name: 'ToggleGroup', description: $tStore('related.toggleGroup'), path: '?path=/docs/primitives-form-togglegroup--docs' },
      { name: 'Button',      description: $tStore('related.button'),      path: '?path=/docs/primitives-form-button--docs'      },
    ]}
  />

  <!-- ── Notas ──────────────────────────────────────────────────── -->
  <DocsNotes
    title={$tStore('notes.title')}
    componentSlug="editor"
    items={[
      { title: '', content: $tStore('notes.tip1') },
      { title: '', content: $tStore('notes.tip2') },
      { title: '', content: $tStore('notes.tip3') },
      { title: '', content: $tStore('notes.tip4') },
      { title: '', content: $tStore('notes.tip5') },
      { title: '', content: $tStore('notes.tip6') },
    ]}
  />

  <!-- ── Analytics ─────────────────────────────────────────────── -->
  <DocsAnalytics
    title={$tStore('analytics.title')}
    cols={{
      event: $tStore('analytics.table.event'),
      trigger: $tStore('analytics.table.trigger'),
      payload: $tStore('analytics.table.payload'),
    }}
    items={[
      { event: $tStore('analytics.table.pageView'),      trigger: $tStore('analytics.table.pageViewTrigger'),      payload: $tStore('analytics.table.pageViewPayload') },
      { event: $tStore('analytics.table.sectionViewed'), trigger: $tStore('analytics.table.sectionViewedTrigger'), payload: $tStore('analytics.table.sectionViewedPayload') },
      { event: $tStore('analytics.table.demoClick'),     trigger: $tStore('analytics.table.demoClickTrigger'),     payload: $tStore('analytics.table.demoClickPayload') },
    ]}
  />

  <!-- ── Testes ─────────────────────────────────────────────────── -->
  <DocsTestes
    title={$tStore('testes.title')}
    functional={{
      title: $tStore('testes.functional.title'),
      description: $tStore('testes.functional.description'),
      cols: {
        action: $tNavStore('common.userAction'),
        result: $tNavStore('common.expectedResult'),
        priority: $tNavStore('common.priority'),
      },
      items: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].map((n) => ({
        action: $tStore(`testes.functional.item${n}.action`),
        result: $tStore(`testes.functional.item${n}.result`),
        priority: localPriority($tStore(`testes.functional.item${n}.priority`), $tNavStore),
      })),
    }}
    accessibility={{
      title: $tStore('testes.accessibility.title'),
      description: $tStore('testes.accessibility.description'),
      cols: {
        criterion: $tNavStore('common.criterion'),
        level: 'WCAG',
        how: $tNavStore('common.howToVerify'),
      },
      // O critério é o RESULTADO esperado; a ação é como se verifica. Invertê-los
      // deixaria "Inspecionar a barra" na coluna de critério, que não é critério
      // nenhum.
      items: [1, 2, 3, 4, 5].map((n) => ({
        criterion: $tStore(`testes.accessibility.item${n}.result`),
        level: 'AA',
        how: $tStore(`testes.accessibility.item${n}.action`),
      })),
    }}
    visual={{
      title: $tStore('testes.visual.title'),
      description: $tStore('testes.visual.description'),
      cols: {
        story: $tNavStore('common.storyState'),
        priority: $tNavStore('common.priority'),
      },
      items: [1, 2, 3].map((n) => ({
        story: `${$tStore(`testes.visual.item${n}.action`)} — ${$tStore(`testes.visual.item${n}.result`)}`,
        priority: localPriority($tStore(`testes.visual.item${n}.priority`), $tNavStore),
      })),
    }}
  />
</DocsPageLayout>

// nortear-design-system-vue/src/components/docs/EditorDocs.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useTranslation } from '@/lib/i18n';
import { useSeoEffect } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { useActiveSection } from '@/lib/use-active-section';
import { Editor, type EditorPreset } from '@/components/ui/editor';
import { editorLabelsFor, nounLabelsFor } from '@/components/ui/editor/editor.labels';
import { Button } from '@/components/ui/button';
import {
  editorAdvancedSource,
  editorBasicSource,
} from '@/components/ui/editor/editor.source';

import DocsPageLayout    from '@/components/docs/shared/sections/DocsPageLayout.vue';
import DocsHeader        from '@/components/docs/shared/sections/DocsHeader.vue';
import DocsDemonstration from '@/components/docs/shared/sections/DocsDemonstration.vue';
import DocsAnatomy       from '@/components/docs/shared/sections/DocsAnatomy.vue';
import DocsWhenToUse     from '@/components/docs/shared/sections/DocsWhenToUse.vue';
import DocsDoDont        from '@/components/docs/shared/sections/DocsDoDont.vue';
import DocsImport        from '@/components/docs/shared/sections/DocsImport.vue';
import DocsVariants      from '@/components/docs/shared/sections/DocsVariants.vue';
import DocsStates        from '@/components/docs/shared/sections/DocsStates.vue';
import DocsProps         from '@/components/docs/shared/sections/DocsProps.vue';
import DocsTokens        from '@/components/docs/shared/sections/DocsTokens.vue';
import DocsAccessibility from '@/components/docs/shared/sections/DocsAccessibility.vue';
import DocsRelated       from '@/components/docs/shared/sections/DocsRelated.vue';
import DocsNotes         from '@/components/docs/shared/sections/DocsNotes.vue';
import DocsAnalytics     from '@/components/docs/shared/sections/DocsAnalytics.vue';
import DocsTestes        from '@/components/docs/shared/sections/DocsTestes.vue';

import uiTranslations        from '@/i18n/ui.json';
import componentTranslations from '@shared/content/editor/translations.json';
import { toPlainText } from '@/lib/strip-html';

// ─── i18n ─────────────────────────────────────────────────────────────────────
// IMPORTANTE: locale vem de useTranslation — NUNCA de useLocaleStore/Pinia
const { t: tNav } = useTranslation(uiTranslations);
const { t: tContent, locale } = useTranslation(componentTranslations, {
  // O conteúdo compartilhado descreve o callback de mudança de forma neutra de
  // API. Aqui ele tem o nome que esta stack usa — e só o NOME muda; a descrição
  // continua vindo do conteúdo.
  '*': { 'props.table.onChange.name': '@change' },
});

// ─── Rótulos das demonstrações ────────────────────────────────────────────────
//
// Os rótulos da barra vêm do CONTEÚDO COMPARTILHADO, no idioma da página.
//
// Todo botão do editor é só de ícone: o rótulo É o nome acessível, e nome
// acessível é conteúdo. Antes eram um objeto de 51 entradas escrito aqui, em
// pt-BR — a página trocava de idioma e a interface que ela demonstra, não.
// A leitura é tipada em `editor.labels.ts`: rótulo ausente reprova no
// `vue-tsc`, e não em silêncio na tela.

const baseLabels = computed(() => editorLabelsFor(locale.value));

/**
 * O lado errado do primeiro Do & Don't: o SUBSTANTIVO no lugar do verbo.
 *
 * Muda um rótulo só, o do botão de link — `labels.actions.link` ("Inserir
 * link") contra `labels.nouns.link` ("Link"), os dois vindos do conteúdo. É
 * exatamente o que a legenda do par contrasta, e um segundo texto diferente
 * daria à comparação uma segunda variável.
 */
const nounLabels = computed(() => nounLabelsFor(locale.value));

// ─── Conteúdo dos exemplos ────────────────────────────────────────────────────

const DEMO_CONTENT = '<p>Escreva aqui. A energia de repouso é <strong>E = mc²</strong>.</p>';
const BASIC_CONTENT =
  '<p>Comentário curto, com ênfase e uma lista.</p><ul><li>primeiro</li><li>segundo</li></ul>';
const ADVANCED_CONTENT =
  '<h2>Relatório</h2><p>Texto com <mark>destaque</mark> e <a href="https://exemplo.com">link</a>.</p>';
const THANKS_CONTENT = '<p>Ótimo trabalho, obrigado!</p>';

// ─── SEO & GEO ────────────────────────────────────────────────────────────────

useSeoEffect(computed(() => ({
  title: tContent('seo.title'),
  description: tContent('seo.description'),
  locale: locale.value as 'pt-BR' | 'en' | 'es',
  componentSlug: 'editor',
  aiSummary: tContent('seo.aiSummary'),
  aiEntities: tContent('seo.aiEntities'),
  breadcrumb: [
    { name: 'Components', item: '/components' },
    { name: tContent('category'), item: '/components/form' },
    { name: tContent('title') },
  ],
})));

// ─── Analytics — page view ────────────────────────────────────────────────────

watch(locale, (newLocale) => {
  track('docs_page_view', {
    component_name: 'editor',
    locale: newLocale as 'pt-BR' | 'en' | 'es',
    page_title: tContent('seo.title'),
  });
}, { immediate: true });

// ─── Demonstração ─────────────────────────────────────────────────────────────

const demoPreset = ref<EditorPreset>('advanced');
const demoReadOnly = ref(false);

/**
 * Os três controles da demonstração, cada um marcado para o observer.
 *
 * O evento sai do PRÓPRIO botão. A seção de demonstração é um container
 * auto-instrumentado (`data-track-container`), e o observer resolve por
 * `.closest('[data-track]')`: um controle sem marcação própria fazia o clique
 * subir até a seção, e o container disparava um SEGUNDO `docs_demo_click` com
 * `element_id` tirado do texto traduzido — o mesmo clique virava dois eventos
 * no GA4, e um deles partido em três idiomas. Marcado o botão, o `closest` para
 * nele: um evento, com a chave estável na terceira parte do id.
 */
const demoControls = computed(() => [
  {
    key: 'basic',
    label: tContent('demonstration.labels.basic'),
    pressed: demoPreset.value === 'basic',
    apply: () => { demoPreset.value = 'basic'; },
  },
  {
    key: 'advanced',
    label: tContent('demonstration.labels.advanced'),
    pressed: demoPreset.value === 'advanced',
    apply: () => { demoPreset.value = 'advanced'; },
  },
  {
    key: 'readOnly',
    label: tContent('demonstration.labels.readOnly'),
    pressed: demoReadOnly.value,
    apply: () => { demoReadOnly.value = !demoReadOnly.value; },
  },
]);

// ─── Navegação ────────────────────────────────────────────────────────────────

const navGroups = computed(() => [
  {
    label: tContent('nav.overview'),
    sections: [
      { id: 'demonstracao', label: tContent('nav.demonstration') },
      { id: 'anatomia',     label: tContent('nav.anatomy')       },
      { id: 'quando-usar',  label: tContent('nav.usage')         },
      { id: 'do-dont',      label: tContent('nav.doDont')        },
    ],
  },
  {
    label: tContent('nav.techRef'),
    sections: [
      { id: 'importacao',   label: tContent('nav.import')   },
      { id: 'variantes',    label: tContent('nav.variants') },
      { id: 'estados',      label: tContent('nav.states')   },
      { id: 'propriedades', label: tContent('nav.props')    },
      { id: 'tokens',       label: tContent('nav.tokens')   },
    ],
  },
  {
    label: tNav('nav.context'),
    sections: [
      { id: 'acessibilidade', label: tContent('nav.accessibility') },
      { id: 'relacionados',   label: tContent('nav.related')       },
      { id: 'notas',          label: tContent('nav.notes')         },
    ],
  },
  {
    label: tNav('nav.quality'),
    sections: [
      { id: 'analytics', label: tContent('nav.analytics') },
      { id: 'testes',    label: tContent('nav.testes')    },
    ],
  },
]);

const allSectionIds = computed(() => navGroups.value.flatMap((g) => g.sections.map((s) => s.id)));

const { activeId: activeSection } = useActiveSection(allSectionIds, (id) => {
  track('docs_section_viewed', {
    section_id: id,
    component_name: 'editor',
    locale: locale.value,
  });
});

// ─── Helpers ──────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function localPriority(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

/** Estados do conteúdo compartilhado, na ordem em que ele os declara. */
const STATE_KEYS = [
  'editing',
  'readOnly',
  'imageSelected',
  'inTable',
  'fieldOpen',
  'invalidValue',
];

/** Chaves da tabela de tokens, na ordem em que o conteúdo as declara. */
const TOKEN_KEYS = [
  'border',
  'background',
  'muted',
  'mutedForeground',
  'foreground',
  'primary',
  'accent',
  'ring',
  'textH1',
];

// ─── Código exibido ───────────────────────────────────────────────────────────

const interfaceCode = `interface EditorProps {
  content?: string;                   // HTML inicial, sanitizado antes de montar
  editable?: boolean;                 // padrão: true
  preset?: 'basic' | 'advanced';      // padrão: 'advanced'
  labels: EditorLabels;               // obrigatório
  resolveImage?: (file: File) => Promise<string | null>;
  describeImage?: (file: File | null, src: string) => Promise<string | null>;
}

// Emits
//   (e: 'change', html: string): void`;

// ─── Dados das seções ─────────────────────────────────────────────────────────

const anatomyItems = computed(() => [
  tContent('anatomy.item1'),
  tContent('anatomy.item2'),
  tContent('anatomy.item3'),
  tContent('anatomy.item4'),
  tContent('anatomy.item5'),
  tContent('anatomy.item6'),
  tContent('anatomy.item7'),
]);

const guidelineItems = computed(() =>
  [1, 2, 3, 4, 5].map((i) => tContent(`usage.guidelines.item${i}`)),
);

const scenarioItems = computed(() =>
  [1, 2, 3, 4, 5, 6].map((i) => ({
    s: tContent(`usage.scenarios.item${i}.s`),
    u: tContent(`usage.scenarios.item${i}.u`),
    a: tContent(`usage.scenarios.item${i}.a`),
  })),
);

const variantItems = computed(() => [
  {
    // Chave ESTÁVEL, não traduzida: ela vira o `snippet_id` do evento de cópia.
    name: tContent('variants.items.basic.name'),
    trackId: 'basic',
    description: tContent('variants.items.basic.description'),
    code: editorBasicSource(),
  },
  {
    name: tContent('variants.items.advanced.name'),
    trackId: 'advanced',
    description: tContent('variants.items.advanced.description'),
    code: editorAdvancedSource(),
  },
]);

const stateItems = computed(() =>
  STATE_KEYS.map((key) => ({
    label: tContent(`states.${key}.label`),
    trigger: tContent(`states.${key}.trigger`),
    behavior: toPlainText(tContent(`states.${key}.behavior`)),
  })),
);

const propItems = computed(() =>
  ['content', 'editable', 'preset', 'labels', 'onChange', 'resolveImage', 'describeImage'].map(
    (key) => ({
      name: tContent(`props.table.${key}.name`),
      type: tContent(`props.table.${key}.type`),
      defaultValue: tContent(`props.table.${key}.default`),
      required: tContent(`props.table.${key}.required`),
      description: toPlainText(tContent(`props.table.${key}.description`)),
    }),
  ),
);

const tokenRows = computed(() =>
  TOKEN_KEYS.map((key) => ({
    token: tContent(`tokens.table.${key}.token`),
    value: tContent(`tokens.table.${key}.value`),
    description: tContent(`tokens.table.${key}.description`),
  })),
);

const accessibilityItems = computed(() => [
  tContent('accessibility.item1'),
  tContent('accessibility.item2'),
  tContent('accessibility.item3'),
  tContent('accessibility.item4'),
  tContent('accessibility.item5'),
  tContent('accessibility.item6'),
  tContent('accessibility.item7'),
]);

const keyboardItems = computed(() =>
  ['tab', 'arrows', 'homeEnd', 'enter', 'escape'].map((key) => ({
    key: tContent(`accessibility.keyboard.${key}.key`),
    description: tContent(`accessibility.keyboard.${key}.action`),
  })),
);

const relatedItems = computed(() => [
  { name: 'Textarea',    description: toPlainText(tContent('related.textarea')),    path: '?path=/docs/primitives-form-textarea--docs'    },
  { name: 'CodeBlock',   description: toPlainText(tContent('related.codeBlock')),   path: '?path=/docs/primitives-display-codeblock--docs'   },
  { name: 'ToggleGroup', description: toPlainText(tContent('related.toggleGroup')), path: '?path=/docs/primitives-form-togglegroup--docs' },
  { name: 'Button',      description: toPlainText(tContent('related.button')),      path: '?path=/docs/primitives-form-button--docs'      },
]);

const noteItems = computed(() =>
  ['tip1', 'tip2', 'tip3', 'tip4', 'tip5', 'tip6'].map((key) => ({
    title: '',
    content: tContent(`notes.${key}`),
  })),
);

const analyticsItems = computed(() => [
  {
    event: tContent('analytics.table.pageView'),
    trigger: toPlainText(tContent('analytics.table.pageViewTrigger')),
    payload: tContent('analytics.table.pageViewPayload'),
  },
  {
    event: tContent('analytics.table.sectionViewed'),
    trigger: toPlainText(tContent('analytics.table.sectionViewedTrigger')),
    payload: tContent('analytics.table.sectionViewedPayload'),
  },
  {
    event: tContent('analytics.table.demoClick'),
    trigger: toPlainText(tContent('analytics.table.demoClickTrigger')),
    payload: tContent('analytics.table.demoClickPayload'),
  },
]);

const functionalTestItems = computed(() =>
  Array.from({ length: 11 }, (_value, i) => `item${i + 1}`).map((key) => ({
    action: tContent(`testes.functional.${key}.action`),
    result: tContent(`testes.functional.${key}.result`),
    priority: localPriority(tContent(`testes.functional.${key}.priority`)),
  })),
);

// O conteúdo compartilhado descreve a verificação de acessibilidade como AÇÃO e
// RESULTADO. A tabela pergunta critério, nível e como verificar: o resultado é o
// critério que precisa valer, e a ação é como se chega até ele.
const a11yTestItems = computed(() =>
  ['item1', 'item2', 'item3', 'item4', 'item5'].map((key) => ({
    criterion: tContent(`testes.accessibility.${key}.result`),
    level: 'WCAG 2.2 AA',
    how: tContent(`testes.accessibility.${key}.action`),
  })),
);

const visualTestItems = computed(() =>
  ['item1', 'item2', 'item3'].map((key) => ({
    story: `${tContent(`testes.visual.${key}.action`)} — ${tContent(`testes.visual.${key}.result`)}`,
    priority: localPriority(tContent(`testes.visual.${key}.priority`)),
  })),
);
</script>

<template>
  <DocsPageLayout
    :nav-groups="navGroups"
    :active-section="activeSection"
    component-slug="editor"
  >
    <template #header>
      <DocsHeader
        :title="tContent('title')"
        :description="tContent('description')"
        :category="tContent('category')"
        :type="tContent('type')"
      />
    </template>

    <!-- ── Demonstração ─────────────────────────────────────────────── -->
    <DocsDemonstration
      :title="tContent('demonstration.title')"
      component-slug="editor"
    >
      <div
        class="nds-stack nds-w-full"
        data-spacing="md"
      >
        <div
          class="nds-cluster"
          data-spacing="sm"
          role="group"
          :aria-label="tContent('demonstration.title')"
        >
          <!-- O observer resolve por `.closest('[data-track]')`, e a terceira
               parte do id estruturado vira `element_id`. -->
          <Button
            v-for="control in demoControls"
            :key="control.key"
            type="button"
            variant="outline"
            size="sm"
            :aria-pressed="control.pressed"
            data-track="demo"
            :data-track-id="`editor:demonstracao:${control.key}`"
            :data-track-label="control.label"
            @click="control.apply"
          >
            {{ control.label }}
          </Button>
        </div>

        <Editor
          :labels="baseLabels"
          :content="DEMO_CONTENT"
          :preset="demoPreset"
          :editable="!demoReadOnly"
        />
      </div>
    </DocsDemonstration>

    <!-- ── Anatomia ─────────────────────────────────────────────────── -->
    <DocsAnatomy
      :title="tContent('anatomy.title')"
      :items="anatomyItems"
      :structure-label="tContent('anatomy.structureLabel')"
      :structure-code="tContent('anatomy.structureCode')"
      language="html"
    />

    <!-- ── Quando Usar ──────────────────────────────────────────────── -->
    <DocsWhenToUse
      :title="tContent('usage.title')"
      :guidelines="{ title: tContent('usage.guidelines.title'), items: guidelineItems }"
      :scenarios="{
        title: tContent('usage.scenarios.title'),
        cols: {
          scenario: tContent('usage.scenarios.cols.scenario'),
          use: tContent('usage.scenarios.cols.use'),
          alternative: tContent('usage.scenarios.cols.alternative'),
        },
        items: scenarioItems,
      }"
      :do="{
        title: tNav('common.do'),
        items: [
          tContent('usage.do.item1'),
          tContent('usage.do.item2'),
          tContent('usage.do.item3'),
          tContent('usage.do.item4'),
        ],
      }"
      :dont="{
        title: tNav('common.dont'),
        items: [
          tContent('usage.dont.item1'),
          tContent('usage.dont.item2'),
          tContent('usage.dont.item3'),
          tContent('usage.dont.item4'),
        ],
      }"
    />

    <!-- ── Do & Don't ───────────────────────────────────────────────── -->
    <DocsDoDont
      :title="tContent('doDont.title')"
      :pairs="[
        {
          doLabel: tNav('common.do'),
          dontLabel: tNav('common.dont'),
          doCaption: toPlainText(tContent('doDont.pair1.do')),
          dontCaption: toPlainText(tContent('doDont.pair1.dont')),
        },
        {
          doLabel: tNav('common.do'),
          dontLabel: tNav('common.dont'),
          doCaption: toPlainText(tContent('doDont.pair2.do')),
          dontCaption: toPlainText(tContent('doDont.pair2.dont')),
        },
      ]"
    >
      <!-- Par 1: o verbo da ação contra o nome da marcação.
           MESMO conjunto e MESMO conteúdo nos dois lados: muda um rótulo só, o
           do botão de link — e é dele que a legenda fala. -->
      <template #do-preview-0>
        <Editor
          :labels="baseLabels"
          :content="THANKS_CONTENT"
          preset="basic"
        />
      </template>
      <template #dont-preview-0>
        <Editor
          :labels="nounLabels"
          :content="THANKS_CONTENT"
          preset="basic"
        />
      </template>

      <!-- Par 2: o conjunto pelo tipo de conteúdo, não pelo espaço -->
      <template #do-preview-1>
        <Editor
          :labels="baseLabels"
          :content="THANKS_CONTENT"
          preset="basic"
        />
      </template>
      <template #dont-preview-1>
        <Editor
          :labels="baseLabels"
          :content="THANKS_CONTENT"
          preset="advanced"
        />
      </template>
    </DocsDoDont>

    <!-- ── Importação ───────────────────────────────────────────────── -->
    <DocsImport
      :title="tContent('import.title')"
      :description="tContent('import.basic')"
      :code="tContent('import.basicCode')"
      :secondary-description="tContent('import.withStorage')"
      :secondary-code="tContent('import.withStorageCode')"
      component-slug="editor"
    />

    <!-- ── Variantes ────────────────────────────────────────────────── -->
    <DocsVariants
      :title="tContent('variants.title')"
      :note="tContent('variants.note')"
      :items="variantItems"
      component-slug="editor"
    >
      <template #variant-preview-0>
        <Editor
          :labels="baseLabels"
          :content="BASIC_CONTENT"
          preset="basic"
        />
      </template>
      <template #variant-preview-1>
        <Editor
          :labels="baseLabels"
          :content="ADVANCED_CONTENT"
          preset="advanced"
        />
      </template>
    </DocsVariants>

    <!-- ── Estados ──────────────────────────────────────────────────── -->
    <DocsStates
      :title="tContent('states.title')"
      :cols="{
        state: tContent('states.cols.state'),
        trigger: tContent('states.cols.trigger'),
        behavior: tContent('states.cols.behavior'),
      }"
      :items="stateItems"
    />

    <!-- ── Propriedades ─────────────────────────────────────────────── -->
    <DocsProps
      :title="tContent('props.title')"
      :tables="[
        {
          title: 'Editor',
          cols: {
            prop: tContent('props.table.prop'),
            type: tContent('props.table.type'),
            default: tContent('props.table.default'),
            required: tContent('props.table.required'),
            description: tContent('props.table.description'),
          },
          items: propItems,
        },
      ]"
      :interface-code="interfaceCode"
      :extensibility-title="tContent('props.extensibilityTitle')"
      :extensibility-notes="tContent('props.extensibility')"
      :extensibility-code="tContent('props.extensibilityCode')"
      language="ts"
    />

    <!-- ── Tokens ───────────────────────────────────────────────────── -->
    <DocsTokens
      :title="tContent('tokens.title')"
      :cols="{
        token: tContent('tokens.table.token'),
        value: tContent('tokens.table.value'),
        description: tContent('tokens.table.description'),
      }"
      :items="tokenRows"
      :customization-title="tContent('tokens.customizationTitle')"
      :customization-code="tContent('tokens.customizationCode')"
    />

    <!-- ── Acessibilidade ───────────────────────────────────────────── -->
    <DocsAccessibility
      :title="tContent('accessibility.title')"
      :summary="tContent('accessibility.summary')"
      :items="accessibilityItems"
      :keyboard-title="tContent('accessibility.keyboardTitle')"
      :keyboard-items="keyboardItems"
    />

    <!-- ── Relacionados ─────────────────────────────────────────────── -->
    <DocsRelated
      :title="tContent('related.title')"
      :items="relatedItems"
      component-slug="editor"
    />

    <!-- ── Notas ────────────────────────────────────────────────────── -->
    <DocsNotes
      :title="tContent('notes.title')"
      :items="noteItems"
      component-slug="editor"
    />

    <!-- ── Analytics ────────────────────────────────────────────────── -->
    <DocsAnalytics
      :title="tContent('analytics.title')"
      :cols="{
        event: tContent('analytics.table.event'),
        trigger: toPlainText(tContent('analytics.table.trigger')),
        payload: tContent('analytics.table.payload'),
      }"
      :items="analyticsItems"
    />

    <!-- ── Testes ───────────────────────────────────────────────────── -->
    <DocsTestes
      :title="tContent('testes.title')"
      :functional="{
        title: tContent('testes.functional.title'),
        description: tContent('testes.functional.description'),
        cols: {
          action: tNav('common.userAction'),
          result: tNav('common.expectedResult'),
          priority: tNav('common.priority'),
        },
        items: functionalTestItems,
      }"
      :accessibility="{
        title: tContent('testes.accessibility.title'),
        description: tContent('testes.accessibility.description'),
        cols: {
          criterion: tNav('common.criterion'),
          level: 'WCAG',
          how: tNav('common.howToVerify'),
        },
        items: a11yTestItems,
      }"
      :visual="{
        title: tContent('testes.visual.title'),
        description: tContent('testes.visual.description'),
        cols: {
          story: tNav('common.storyState'),
          priority: tNav('common.priority'),
        },
        items: visualTestItems,
      }"
    />
  </DocsPageLayout>
</template>
