// nortear-design-system-vue/src/components/ui/context-menu/ContextMenuShortcut.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <span
    data-slot="context-menu-shortcut"
    :class="cn('nds-dropdown-menu-shortcut', props.class)"
  >
    <slot />
  </span>
</template>

// design-system-svelte/src/components/ui/context-menu/context-menu-shortcut.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "@/lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLSpanElement>> = $props();
</script>

<span
	bind:this={ref}
	data-slot="context-menu-shortcut"
	class={cn("nds-dropdown-menu-shortcut", className)}
	{...restProps}
>
	{@render children?.()}
</span>
