// nortear-design-system-react/src/components/ui/sonner.tsx
import { useTheme } from "next-themes"
import { Toaster as Sonner, type ToasterProps } from "sonner"
import { CircleCheckIcon, InfoIcon, TriangleAlertIcon, OctagonXIcon, Loader2Icon } from "lucide-react"

/**
 * Rótulos em português — o design system é escrito em pt-BR, e os defaults da
 * lib ("Notifications", "Close toast") chegariam à tela em inglês.
 */
export const REGION_LABEL = "Notificações"
export const CLOSE_LABEL = "Fechar notificação"

/**
 * A região que desenha a fila. Vai UMA VEZ no root da aplicação.
 *
 * `containerAriaLabel` e `toastOptions` entram DEPOIS do spread de `props`
 * porque quem consome precisa poder sobrepô-los — dois Toasters na mesma tela
 * exigem nomes distintos. O `toastOptions` é mesclado, e não substituído: passar
 * só `classNames` não pode apagar o rótulo do botão de fechar.
 */
const Toaster = ({ containerAriaLabel, toastOptions, ...props }: ToasterProps) => {
  const { theme = "system" } = useTheme()

  return (
    <Sonner
      theme={theme as ToasterProps["theme"]}
      icons={{
        success: (
          <CircleCheckIcon className="nds-toast-icon" />
        ),
        info: (
          <InfoIcon className="nds-toast-icon" />
        ),
        warning: (
          <TriangleAlertIcon className="nds-toast-icon" />
        ),
        error: (
          <OctagonXIcon className="nds-toast-icon" />
        ),
        loading: (
          <Loader2Icon className="nds-toast-icon nds-toast-icon-spin" />
        ),
      }}
      style={
        {
          "--normal-bg": "var(--popover)",
          "--normal-text": "var(--popover-foreground)",
          "--normal-border": "var(--border)",
          "--border-radius": "var(--radius)",
        } as React.CSSProperties
      }
      {...props}
      containerAriaLabel={containerAriaLabel ?? REGION_LABEL}
      toastOptions={{ closeButtonAriaLabel: CLOSE_LABEL, ...toastOptions }}
    />
  )
}

export { Toaster }

// nortear-design-system-vue/src/components/ui/sonner/Sonner.vue
<script lang="ts" setup>
import type { ToasterProps } from 'vue-sonner'

import {
  CircleCheckIcon,
  InfoIcon,
  Loader2Icon,
  OctagonXIcon,
  TriangleAlertIcon,
  XIcon,
} from 'lucide-vue-next'
import { Toaster as Sonner } from 'vue-sonner'
import { computed } from 'vue'

// A folha da lib NÃO é injetada em runtime nesta stack — o pacote a expõe como
// `vue-sonner/style.css` e espera que quem consome a importe. Sem esta linha a
// região saía sem posicionamento, sem fundo e sem sombra: um `<ol>` cru no meio
// da página, e nada na tela dizia que faltava alguma coisa.
import 'vue-sonner/style.css'

/**
 * Rótulos em português — o design system é escrito em pt-BR, e os defaults da
 * lib ("Notifications", "Close toast") chegariam à tela em inglês.
 */
const REGION_LABEL = 'Notificações'
const CLOSE_LABEL = 'Fechar notificação'

const props = defineProps<ToasterProps>()

/**
 * `toastOptions` é MESCLADO, e não substituído: passar só `classNames` não pode
 * apagar o rótulo do botão de fechar.
 */
const toastOptions = computed(() => ({
  closeButtonAriaLabel: CLOSE_LABEL,
  ...(props.toastOptions ?? {}),
}))

const containerAriaLabel = computed(() => props.containerAriaLabel ?? REGION_LABEL)
</script>

<template>
  <Sonner
    :style="{
      '--normal-bg': 'var(--popover)',
      '--normal-text': 'var(--popover-foreground)',
      '--normal-border': 'var(--border)',
      '--border-radius': 'var(--radius)',
    }"
    v-bind="props"
    :container-aria-label="containerAriaLabel"
    :toast-options="toastOptions"
  >
    <template #success-icon>
      <CircleCheckIcon class="nds-toast-icon" />
    </template>
    <template #info-icon>
      <InfoIcon class="nds-toast-icon" />
    </template>
    <template #warning-icon>
      <TriangleAlertIcon class="nds-toast-icon" />
    </template>
    <template #error-icon>
      <OctagonXIcon class="nds-toast-icon" />
    </template>
    <template #loading-icon>
      <div>
        <Loader2Icon class="nds-toast-icon nds-toast-icon-spin" />
      </div>
    </template>
    <template #close-icon>
      <XIcon class="nds-toast-icon" />
    </template>
  </Sonner>
</template>
