// nortear-design-system-vue/src/components/docs/AspectRatioDocs.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { useTranslation } from '@/lib/i18n';
import { useSeoEffect } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { useActiveSection } from '@/lib/use-active-section';
import { AspectRatio } from '@/components/ui/aspect-ratio';
import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.vue';
import uiTranslations from '@/i18n/ui.json';
import aspectRatioTranslations from '@shared/content/aspect-ratio/translations.json';

import DocsHeader        from '@/components/docs/shared/sections/DocsHeader.vue';
import DocsDemonstration from '@/components/docs/shared/sections/DocsDemonstration.vue';
import DocsAnatomy       from '@/components/docs/shared/sections/DocsAnatomy.vue';
import DocsWhenToUse     from '@/components/docs/shared/sections/DocsWhenToUse.vue';
import DocsDoDont        from '@/components/docs/shared/sections/DocsDoDont.vue';
import DocsImport        from '@/components/docs/shared/sections/DocsImport.vue';
import DocsVariants      from '@/components/docs/shared/sections/DocsVariants.vue';
import DocsStates        from '@/components/docs/shared/sections/DocsStates.vue';
import DocsProps         from '@/components/docs/shared/sections/DocsProps.vue';
import DocsTokens        from '@/components/docs/shared/sections/DocsTokens.vue';
import DocsAccessibility from '@/components/docs/shared/sections/DocsAccessibility.vue';
import DocsRelated       from '@/components/docs/shared/sections/DocsRelated.vue';
import DocsNotes         from '@/components/docs/shared/sections/DocsNotes.vue';
import DocsAnalytics     from '@/components/docs/shared/sections/DocsAnalytics.vue';
import DocsTestes        from '@/components/docs/shared/sections/DocsTestes.vue';
import { stripHtml, toPlainText } from '@/lib/strip-html';

// ─── i18n ─────────────────────────────────────────────────────────────────────

const { t: tNav } = useTranslation(uiTranslations);
const { t: tContent, locale } = useTranslation(aspectRatioTranslations);

// As chaves de `accessibility.screenReader` variam por componente, então só os
// valores chegam ao container — o `t()` exige nome de chave e não serviria.
const screenReaderItems = computed(() =>
  Object.values(
    (aspectRatioTranslations as unknown as Record<
      string,
      { accessibility?: { screenReader?: Record<string, string> } }
    >)[locale.value]?.accessibility?.screenReader ?? {},
  ),
);

// ─── Helpers ──────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function localPriority(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

// ─── Media URLs (demo) ────────────────────────────────────────────────────────

const imgLandscape = 'https://images.unsplash.com/photo-1535025183041-0991a977e25b?w=800&auto=format';
const imgProduct   = 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format';
const imgAvatar    = 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format';
const imgPortrait  = 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=400&auto=format';
const imgUltraWide = 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&auto=format';

// ─── SEO & GEO ────────────────────────────────────────────────────────────────

useSeoEffect(computed(() => ({
  title: tContent('seo.title'),
  description: tContent('seo.description'),
  locale: locale.value as 'pt-BR' | 'en' | 'es',
  componentSlug: 'aspect-ratio',
})));

// ─── Analytics — page view ────────────────────────────────────────────────────

watch(locale, (newLocale) => {
  track('docs_page_view', {
    component_name: 'aspect-ratio',
    locale: newLocale,
    page_title: `${tContent('title')} · Design System`,
  });
}, { immediate: true });

// ─── Analytics — section view ─────────────────────────────────────────────────

// ─── Navigation groups ────────────────────────────────────────────────────────

const navGroups = computed(() => [
  {
    label: tNav('nav.overview'),
    sections: [
      { id: 'demonstracao', label: tNav('nav.demonstration') },
      { id: 'anatomia',     label: tNav('nav.anatomy')      },
      { id: 'quando-usar',  label: tNav('nav.usage')        },
      { id: 'do-dont',      label: tNav('nav.doDont')       },
    ],
  },
  {
    label: tNav('nav.techRef'),
    sections: [
      { id: 'importacao',   label: tNav('nav.import')   },
      { id: 'variantes',    label: tNav('nav.variants') },
      { id: 'estados',      label: tNav('nav.states')   },
      { id: 'propriedades', label: tNav('nav.props')    },
      { id: 'tokens',       label: tNav('nav.tokens')   },
    ],
  },
  {
    label: tNav('nav.context'),
    sections: [
      { id: 'acessibilidade', label: tNav('nav.accessibility') },
      { id: 'relacionados',   label: tNav('nav.related')       },
      { id: 'notas',          label: tNav('nav.notes')         },
    ],
  },
  {
    label: tNav('nav.quality'),
    sections: [
      { id: 'analytics', label: tNav('nav.analytics') },
      { id: 'testes',    label: tNav('nav.testes')    },
    ],
  },
]);

const allSectionIds = computed(() => navGroups.value.flatMap(g => g.sections.map(s => s.id)));

const { activeId: activeSection } = useActiveSection(allSectionIds, (id) => {
  track('docs_section_viewed', {
    section_id: id,
    component_name: 'aspect-ratio',
    locale: locale.value,
  });
});
// ─── Code strings ─────────────────────────────────────────────────────────────

const codeImportBasic = `import { AspectRatio } from "@/components/ui/aspect-ratio";`;

const codeSixteenNine = `<AspectRatio :ratio="16 / 9">
  <img src="/hero.jpg" alt="Paisagem" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

const codeFourThree = `<AspectRatio :ratio="4 / 3">
  <img src="/product.jpg" alt="Foto do produto" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

const codeSquare = `<AspectRatio :ratio="1">
  <img src="/avatar.jpg" alt="Foto de perfil" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

const codeThreeFour = `<AspectRatio :ratio="3 / 4">
  <img src="/cover.jpg" alt="Capa vertical" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

const codeUltraWide = `<AspectRatio :ratio="21 / 9">
  <img src="/pano.jpg" alt="Cabeçalho panorâmico" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

const codeCustomizationTokens = `<!-- Tokens no FILHO, nunca no AspectRatio -->
<AspectRatio :ratio="16 / 9">
  <img
    src="/hero.jpg"
    alt="Paisagem"
    class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%"
  />
</AspectRatio>`;

const interfaceCode = `// AspectRatio
interface AspectRatioProps {
  ratio?: number;   // largura / altura. Padrão: 1
  asChild?: boolean;
  class?: string;
}`;

const anatomyStructure = `<AspectRatio ratio={16 / 9}>          // 1. Root wrapper (padding-bottom calculado)
  <img                                 // 2. Slot (conteúdo filho)
    src="/hero.jpg"
    alt="Paisagem"
    class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%"
  />
</AspectRatio>`;

// ─── Computed data ────────────────────────────────────────────────────────────

const anatomyItems = computed(() => [
  tContent('anatomy.item1'),
  tContent('anatomy.item2'),
  tContent('anatomy.item3'),
]);

const variantItems = computed(() => [
  { name: '16 / 9', description: stripHtml(tContent('variants.items.sixteenNine')), code: codeSixteenNine },
  { name: '4 / 3',  description: stripHtml(tContent('variants.items.fourThree')),  code: codeFourThree  },
  { name: '1 / 1',  description: stripHtml(tContent('variants.items.square')),     code: codeSquare     },
  { name: '3 / 4',  description: stripHtml(tContent('variants.items.threeFour')),  code: codeThreeFour  },
  { name: '21 / 9', description: stripHtml(tContent('variants.items.ultraWide')),  code: codeUltraWide  },
]);

const stateItems = computed(() => [
  { label: tContent('states.item1.label'), trigger: toPlainText(tContent('states.item1.trigger')), behavior: toPlainText(tContent('states.item1.behavior'))},
  { label: tContent('states.item2.label'), trigger: toPlainText(tContent('states.item2.trigger')), behavior: toPlainText(tContent('states.item2.behavior'))},
  { label: tContent('states.item3.label'), trigger: toPlainText(tContent('states.item3.trigger')), behavior: toPlainText(tContent('states.item3.behavior')) },
]);

const propCols = computed(() => ({
  prop: tContent('props.table.prop'),
  type: tContent('props.table.type'),
  default: tContent('props.table.default'),
  required: tContent('props.table.required'),
  description: tContent('props.table.description'),
}));

const aspectRatioPropItems = computed(() => [
  { name: 'ratio',   type: 'number',  defaultValue: '1',     required: 'Não', description: toPlainText(tContent('props.table.ratio'))     },
  { name: 'asChild', type: 'boolean', defaultValue: 'false', required: 'Não', description: toPlainText(tContent('props.table.asChild'))   },
  { name: 'class',   type: 'string',  defaultValue: '—',     required: 'Não', description: toPlainText(tContent('props.table.className')) },
]);

const slotPropItems = computed(() => [
  { name: 'default slot', type: 'VNode', defaultValue: '—', required: 'Sim', description: toPlainText(tContent('props.table.children')) },
]);

const tokenRows = computed(() => [
  { token: '—',         value: '—',            description: tContent('tokens.table.radius')  },
  { token: '--border',  value: 'border',       description: tContent('tokens.table.border')  },
  { token: '--muted',   value: 'bg-muted',     description: tContent('tokens.table.muted')   },
]);

const accessibilityItems = computed(() => [
  tContent('accessibility.aria.item1'),
  tContent('accessibility.aria.item2'),
  tContent('accessibility.aria.item3'),
  tContent('accessibility.aria.item4'),
  tContent('accessibility.aria.item5'),
]);

const keyboardItems = computed(() => [
  { key: '—', description: tContent('accessibility.keyboard.item1') },
  { key: '—', description: tContent('accessibility.keyboard.note')  },
]);

const relatedItems = computed(() => [
  { name: 'Avatar',     description: tContent('related.avatar'),   path: '?path=/docs/ui-avatar--docs'     },
  { name: 'Card',       description: tContent('related.card'),     path: '?path=/docs/ui-card--docs'       },
  { name: 'Skeleton',   description: tContent('related.skeleton'), path: '?path=/docs/ui-skeleton--docs'   },
]);

const noteItems = computed(() => [
  { title: '', content: tContent('notes.item1') },
  { title: '', content: tContent('notes.item2') },
  { title: '', content: tContent('notes.item3') },
  { title: '', content: tContent('notes.item4') },
]);

const analyticsItems = computed(() => [
  { event: '—', trigger: toPlainText(tContent('analytics.note')), payload: '—' },
]);

const a11yCritCols = computed(() => ({
  criterion: tNav('common.criterion'),
  level: 'WCAG',
  how: tNav('common.howToVerify'),
}));

const functionalTestItems = computed(() => [
  { action: toPlainText(tContent('testes.functional.item1.action')), result: toPlainText(tContent('testes.functional.item1.result')), priority: localPriority(tContent('testes.functional.item1.priority')) },
  { action: toPlainText(tContent('testes.functional.item2.action')), result: toPlainText(tContent('testes.functional.item2.result')), priority: localPriority(tContent('testes.functional.item2.priority')) },
  { action: toPlainText(tContent('testes.functional.item3.action')), result: toPlainText(tContent('testes.functional.item3.result')), priority: localPriority(tContent('testes.functional.item3.priority')) },
  { action: toPlainText(tContent('testes.functional.item4.action')), result: toPlainText(tContent('testes.functional.item4.result')), priority: localPriority(tContent('testes.functional.item4.priority')) },
  { action: toPlainText(tContent('testes.functional.item5.action')), result: toPlainText(tContent('testes.functional.item5.result')), priority: localPriority(tContent('testes.functional.item5.priority')) },
]);

const a11yTestItems = computed(() => [
  { criterion: toPlainText(tContent('testes.accessibility.item1.criterion')), level: tContent('testes.accessibility.item1.level'), how: tContent('testes.accessibility.item1.how') },
  { criterion: toPlainText(tContent('testes.accessibility.item2.criterion')), level: tContent('testes.accessibility.item2.level'), how: tContent('testes.accessibility.item2.how') },
  { criterion: toPlainText(tContent('testes.accessibility.item3.criterion')), level: tContent('testes.accessibility.item3.level'), how: toPlainText(tContent('testes.accessibility.item3.how')) },
  { criterion: toPlainText(tContent('testes.accessibility.item4.criterion')), level: tContent('testes.accessibility.item4.level'), how: toPlainText(tContent('testes.accessibility.item4.how')) },
  { criterion: toPlainText(tContent('testes.accessibility.item5.criterion')), level: tContent('testes.accessibility.item5.level'), how: tContent('testes.accessibility.item5.how') },
]);

const visualTestItems = computed(() => [
  { story: tContent('testes.visual.item1.story'), priority: localPriority(tContent('testes.visual.item1.priority')) },
  { story: tContent('testes.visual.item2.story'), priority: localPriority(tContent('testes.visual.item2.priority')) },
  { story: tContent('testes.visual.item3.story'), priority: localPriority(tContent('testes.visual.item3.priority')) },
  { story: tContent('testes.visual.item4.story'), priority: localPriority(tContent('testes.visual.item4.priority')) },
  { story: tContent('testes.visual.item5.story'), priority: localPriority(tContent('testes.visual.item5.priority')) },
]);
</script>

<template>
  <DocsPageLayout
    :nav-groups="navGroups"
    :active-section="activeSection"
  >
    <template #header>
      <DocsHeader
        :title="tContent('title')"
        :description="tContent('description')"
        :category="tContent('category')"
        :type="tContent('type')"
      />
    </template>

    <!-- ── Demonstração ───────────────────────────────────────────── -->
    <DocsDemonstration :title="tContent('demonstration.title')">
      <div
        class="nds-grid nds-w-full"
        style="gap: var(--spacing-6)"
      >
        <div
          class="nds-stack"
          data-spacing="xs"
        >
          <AspectRatio :ratio="16 / 9">
            <img
              :src="imgLandscape"
              :alt="tContent('demonstration.labels.sixteenNine')"
              loading="lazy"
              decoding="async"
              class="nds-w-full nds-rounded-md"
              style="object-fit: cover; height: 100%"
            >
          </AspectRatio>
          <p class="nds-text-caption nds-text-muted-foreground">
            {{ tContent('demonstration.labels.sixteenNine') }}
          </p>
        </div>
        <div
          class="nds-stack"
          data-spacing="xs"
        >
          <AspectRatio :ratio="4 / 3">
            <img
              :src="imgProduct"
              :alt="tContent('demonstration.labels.fourThree')"
              loading="lazy"
              decoding="async"
              class="nds-w-full nds-rounded-md"
              style="object-fit: cover; height: 100%"
            >
          </AspectRatio>
          <p class="nds-text-caption nds-text-muted-foreground">
            {{ tContent('demonstration.labels.fourThree') }}
          </p>
        </div>
        <div
          class="nds-stack"
          data-spacing="xs"
        >
          <AspectRatio :ratio="1">
            <img
              :src="imgAvatar"
              :alt="tContent('demonstration.labels.square')"
              loading="lazy"
              decoding="async"
              class="nds-w-full nds-rounded-md"
              style="object-fit: cover; height: 100%"
            >
          </AspectRatio>
          <p class="nds-text-caption nds-text-muted-foreground">
            {{ tContent('demonstration.labels.square') }}
          </p>
        </div>
        <div
          class="nds-stack"
          data-spacing="xs"
        >
          <AspectRatio :ratio="3 / 4">
            <img
              :src="imgPortrait"
              :alt="tContent('demonstration.labels.threeFour')"
              loading="lazy"
              decoding="async"
              class="nds-w-full nds-rounded-md"
              style="object-fit: cover; height: 100%"
            >
          </AspectRatio>
          <p class="nds-text-caption nds-text-muted-foreground">
            {{ tContent('demonstration.labels.threeFour') }}
          </p>
        </div>
      </div>
    </DocsDemonstration>

    <!-- ── Anatomia ───────────────────────────────────────────────── -->
    <DocsAnatomy
      :title="tContent('anatomy.title')"
      :items="anatomyItems"
      :structure-code="anatomyStructure"
    />

    <!-- ── Quando Usar ────────────────────────────────────────────── -->
    <DocsWhenToUse
      :title="tContent('usage.title')"
      :guidelines="{
        title: tContent('usage.guidelines.title'),
        items: [
          tContent('usage.guidelines.item1'),
          tContent('usage.guidelines.item2'),
          tContent('usage.guidelines.item3'),
          tContent('usage.guidelines.item4'),
          tContent('usage.guidelines.item5'),
        ],
      }"
      :scenarios="{
        title: tContent('usage.scenarios.title'),
        cols: {
          scenario: tContent('usage.scenarios.cols.scenario'),
          use: tContent('usage.scenarios.cols.use'),
          alternative: tContent('usage.scenarios.cols.alternative'),
        },
        items: [
          { s: tContent('usage.scenarios.item1.s'), u: tContent('usage.scenarios.item1.u'), a: toPlainText(tContent('usage.scenarios.item1.a')) },
          { s: tContent('usage.scenarios.item2.s'), u: tContent('usage.scenarios.item2.u'), a: tContent('usage.scenarios.item2.a') },
          { s: tContent('usage.scenarios.item3.s'), u: tContent('usage.scenarios.item3.u'), a: tContent('usage.scenarios.item3.a') },
          { s: tContent('usage.scenarios.item4.s'), u: tContent('usage.scenarios.item4.u'), a: tContent('usage.scenarios.item4.a') },
          { s: tContent('usage.scenarios.item5.s'), u: tContent('usage.scenarios.item5.u'), a: tContent('usage.scenarios.item5.a') },
        ],
      }"
      :do="{
        title: tContent('usage.do.title'),
        items: [
          tContent('usage.do.item1'),
          tContent('usage.do.item2'),
          tContent('usage.do.item3'),
          tContent('usage.do.item4'),
        ],
      }"
      :dont="{
        title: tContent('usage.dont.title'),
        items: [
          tContent('usage.dont.item1'),
          tContent('usage.dont.item2'),
          tContent('usage.dont.item3'),
          tContent('usage.dont.item4'),
        ],
      }"
    />

    <!-- ── Do & Don't ─────────────────────────────────────────────── -->
    <DocsDoDont
      :title="tContent('doDont.title')"
      :pairs="[
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair1.do'), dontCaption: tContent('doDont.pair1.dont') },
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair2.do'), dontCaption: tContent('doDont.pair2.dont') },
      ]"
    >
      <template #do-preview-0>
        <AspectRatio
          :ratio="16 / 9"
          class="nds-w-full"
        >
          <img
            :src="imgLandscape"
            alt="Paisagem"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: cover; height: 100%"
          >
        </AspectRatio>
      </template>
      <template #dont-preview-0>
        <AspectRatio
          :ratio="16 / 9"
          class="nds-w-full nds-bg-muted"
        >
          <img
            :src="imgLandscape"
            alt="Paisagem"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: contain; height: 100%"
          >
        </AspectRatio>
      </template>
      <template #do-preview-1>
        <AspectRatio
          :ratio="4 / 3"
          class="nds-w-full"
        >
          <img
            :src="imgProduct"
            alt="Produto"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: cover; height: 100%"
          >
        </AspectRatio>
      </template>
      <template #dont-preview-1>
        <AspectRatio
          :ratio="4 / 3"
          class="nds-w-full nds-rounded-md nds-border-default"
        >
          <img
            :src="imgProduct"
            alt="Produto"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: cover; height: 100%"
          >
        </AspectRatio>
      </template>
    </DocsDoDont>

    <!-- ── Importação ─────────────────────────────────────────────── -->
    <DocsImport
      :title="tContent('import.title')"
      :code="codeImportBasic"
    />

    <!-- ── Variantes ──────────────────────────────────────────────── -->
    <DocsVariants
      :title="tContent('variants.title')"
      :items="variantItems"
    >
      <template #variant-preview-0>
        <AspectRatio
          :ratio="16 / 9"
          class="nds-w-full"
        >
          <img
            :src="imgLandscape"
            alt="Paisagem 16:9"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: cover; height: 100%"
          >
        </AspectRatio>
      </template>
      <template #variant-preview-1>
        <AspectRatio
          :ratio="4 / 3"
          class="nds-w-full"
        >
          <img
            :src="imgProduct"
            alt="Produto 4:3"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: cover; height: 100%"
          >
        </AspectRatio>
      </template>
      <template #variant-preview-2>
        <AspectRatio
          :ratio="1"
          class="nds-w-full"
        >
          <img
            :src="imgAvatar"
            alt="Avatar 1:1"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: cover; height: 100%"
          >
        </AspectRatio>
      </template>
      <template #variant-preview-3>
        <AspectRatio
          :ratio="3 / 4"
          class="nds-w-full"
        >
          <img
            :src="imgPortrait"
            alt="Retrato 3:4"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: cover; height: 100%"
          >
        </AspectRatio>
      </template>
      <template #variant-preview-4>
        <AspectRatio
          :ratio="21 / 9"
          class="nds-w-full"
        >
          <img
            :src="imgUltraWide"
            alt="Ultra-wide 21:9"
            loading="lazy"
            decoding="async"
            class="nds-w-full nds-rounded-md"
            style="object-fit: cover; height: 100%"
          >
        </AspectRatio>
      </template>
    </DocsVariants>

    <!-- ── Estados ─────────────────────────────────────────────────── -->
    <DocsStates
      :title="tContent('states.title')"
      :cols="{
        state: tContent('props.table.prop'),
        trigger: toPlainText(tContent('usage.scenarios.cols.scenario')),
        behavior: toPlainText(tContent('usage.scenarios.cols.use')),
      }"
      :items="stateItems"
    />

    <!-- ── Propriedades ───────────────────────────────────────────── -->
    <DocsProps
      :title="tContent('props.title')"
      :tables="[
        { title: 'AspectRatio', cols: propCols, items: aspectRatioPropItems },
        { title: 'Slot', cols: propCols, items: slotPropItems },
      ]"
      :interface-code="interfaceCode"
      :extensibility-title="tContent('props.extensibilityTitle')"
      :extensibility-notes="stripHtml(tContent('props.extensibility'))"
    />

    <!-- ── Tokens ─────────────────────────────────────────────────── -->
    <DocsTokens
      :title="tContent('tokens.title')"
      :cols="{
        token: 'Token',
        value: 'Classe',
        description: tContent('tokens.table.part'),
      }"
      :items="tokenRows"
      :customization-title="tContent('tokens.customizationTitle')"
      :customization-code="codeCustomizationTokens"
    />

    <!-- ── Acessibilidade ─────────────────────────────────────────── -->
    <DocsAccessibility
      :screen-reader-title="tNav('common.screenReader')"
      :screen-reader-items="screenReaderItems"
      :title="tContent('accessibility.title')"
      :summary="tContent('accessibility.summary')"
      :items="accessibilityItems"
      :keyboard-title="tContent('accessibility.keyboard.title')"
      :keyboard-items="keyboardItems"
    />

    <!-- ── Relacionados ───────────────────────────────────────────── -->
    <DocsRelated
      :title="tContent('related.title')"
      :items="relatedItems"
    />

    <!-- ── Notas ──────────────────────────────────────────────────── -->
    <DocsNotes
      :title="tContent('notes.title')"
      :items="noteItems"
    />

    <!-- ── Analytics ─────────────────────────────────────────────── -->
    <DocsAnalytics
      :title="tContent('analytics.title')"
      :cols="{
        event: tContent('analytics.table.event'),
        trigger: toPlainText(tContent('analytics.table.trigger')),
        payload: tContent('analytics.table.payload'),
      }"
      :items="analyticsItems"
    />

    <!-- ── Testes ─────────────────────────────────────────────────── -->
    <DocsTestes
      :title="tContent('testes.title')"
      :functional="{
        title: tContent('testes.functional.title'),
        cols: { action: tNav('common.userAction'), result: tNav('common.expectedResult'), priority: tNav('common.priority') },
        items: functionalTestItems,
      }"
      :accessibility="{
        title: tContent('testes.accessibility.title'),
        cols: a11yCritCols,
        items: a11yTestItems,
      }"
      :visual="{
        title: tContent('testes.visual.title'),
        cols: { story: tNav('common.storyState'), priority: tNav('common.priority') },
        items: visualTestItems,
      }"
    />
  </DocsPageLayout>
</template>

// nortear-design-system-svelte/src/components/docs/AspectRatioDocs.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { AspectRatio } from '@/components/ui/aspect-ratio';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import { createActiveSection } from '@/lib/use-active-section.svelte';
  import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader, DocsDemonstration, DocsAnatomy, DocsWhenToUse, DocsDoDont,
    DocsImport, DocsVariants, DocsStates, DocsProps, DocsTokens,
    DocsAccessibility, DocsRelated, DocsNotes, DocsAnalytics, DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import aspectRatioTranslations from '@shared/content/aspect-ratio/translations.json';
  import { stripHtml, toPlainText } from '@/lib/strip-html';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(aspectRatioTranslations);

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria.
  const screenReaderItems = $derived(
    Object.values(
      (aspectRatioTranslations as unknown as Record<
        string,
        { accessibility?: { screenReader?: Record<string, string> } }
      >)[$locale]?.accessibility?.screenReader ?? {},
    ),
  );

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'aspect-ratio',
    });
    track('docs_page_view', {
      component_name: 'aspect-ratio',
      locale: l,
      page_title: `${t('title')} · Design System`,
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────

  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')   },
        { id: 'variantes',    label: tNav('nav.variants') },
        { id: 'estados',      label: tNav('nav.states')   },
        { id: 'propriedades', label: tNav('nav.props')    },
        { id: 'tokens',       label: tNav('nav.tokens')   },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  const sectionIds = untrack(() => NAV_GROUPS.flatMap(g => g.sections.map(s => s.id)));
  const section = createActiveSection(sectionIds, (id) => {
    track('docs_section_viewed', { section_id: id, component_name: 'aspect-ratio', locale: $locale });
  });
  $effect(() => section.attach());

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  const priorityKeyMap: Record<string, string> = { high: 'common.high', medium: 'common.medium', low: 'common.low' };
  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  // ─── Image URLs ──────────────────────────────────────────────────────────────

  const IMG_LANDSCAPE = 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&auto=format&fit=crop&q=60';
  const IMG_PRODUCT = 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=900&auto=format&fit=crop&q=60';
  const IMG_AVATAR = 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=60';
  const IMG_PORTRAIT = 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&auto=format&fit=crop&q=60';
  const IMG_ULTRA = 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1600&auto=format&fit=crop&q=60';

  // ─── Anatomy ASCII ───────────────────────────────────────────────────────────

  const anatomyStructureCode = `<AspectRatio ratio={16 / 9}>
  <!-- padding-bottom: 56.25% calculado pelo primitivo -->
  <img
    src="/hero.jpg"
    alt="Paisagem"
    class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%"
  />
</AspectRatio>`;

  // ─── Code strings ────────────────────────────────────────────────────────────

  const codeImportBasic = `import { AspectRatio } from "@/components/ui/aspect-ratio";`;

  const codeImportWithImage = `import { AspectRatio } from "@/components/ui/aspect-ratio";

<AspectRatio ratio={16 / 9}>
  <img
    src="/hero.jpg"
    alt="Gráfico de vendas 2025"
    class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%"
  />
</AspectRatio>`;

  const codeSixteenNine = `<AspectRatio ratio={16 / 9}>
  <img src="/video-cover.jpg" alt="Tutorial" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

  const codeFourThree = `<AspectRatio ratio={4 / 3}>
  <img src="/product.jpg" alt="Sapato azul tamanho 42" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

  const codeSquare = `<AspectRatio ratio={1}>
  <img src="/avatar.jpg" alt="Avatar do usuário" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

  const codeThreeFour = `<AspectRatio ratio={3 / 4}>
  <img src="/cover.jpg" alt="Capa do livro" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

  const codeUltraWide = `<AspectRatio ratio={21 / 9}>
  <img src="/hero-wide.jpg" alt="Hero panorâmico" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
</AspectRatio>`;

  const interfaceCode = `interface AspectRatioProps {
  ratio?: number;
  child?: Snippet<[{ props: Record<string, unknown> }]>;
  class?: string;
  children?: Snippet;
}`;

  const codeCustomizationTokens = `/* AspectRatio herda tokens do filho — aplique no <img>, <video>, <iframe> */
<AspectRatio ratio={16 / 9}>
  <img class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" alt="..." />
</AspectRatio>`;
</script>

<DocsPageLayout navGroups={NAV_GROUPS} activeSection={section.value}>
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
    />
  {/snippet}

      <!-- ── Demonstração ───────────────────────────────────────────── -->
      <DocsDemonstration title={$tStore('demonstration.title')}>
        <div class="nds-grid nds-w-full" style="gap: var(--spacing-6)">
          <div class="nds-stack" data-spacing="xs">
            <p class="nds-text-caption nds-text-muted-foreground">{$tStore('demonstration.labels.sixteenNine')}</p>
            <AspectRatio ratio={16 / 9}>
              <img src={IMG_LANDSCAPE} alt="Paisagem ao entardecer" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
            </AspectRatio>
          </div>
          <div class="nds-stack" data-spacing="xs">
            <p class="nds-text-caption nds-text-muted-foreground">{$tStore('demonstration.labels.fourThree')}</p>
            <AspectRatio ratio={4 / 3}>
              <img src={IMG_PRODUCT} alt="Produto em destaque" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
            </AspectRatio>
          </div>
          <div class="nds-stack" data-spacing="xs">
            <p class="nds-text-caption nds-text-muted-foreground">{$tStore('demonstration.labels.square')}</p>
            <AspectRatio ratio={1}>
              <img src={IMG_AVATAR} alt="Avatar de usuário" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
            </AspectRatio>
          </div>
          <div class="nds-stack" data-spacing="xs">
            <p class="nds-text-caption nds-text-muted-foreground">{$tStore('demonstration.labels.threeFour')}</p>
            <AspectRatio ratio={3 / 4}>
              <img src={IMG_PORTRAIT} alt="Retrato vertical" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
            </AspectRatio>
          </div>
        </div>
      </DocsDemonstration>

      <!-- ── Anatomia ───────────────────────────────────────────────── -->
      <DocsAnatomy
        title={$tStore('anatomy.title')}
        items={[
          $tStore('anatomy.item1'),
          $tStore('anatomy.item2'),
          $tStore('anatomy.item3'),
        ]}
        structureCode={anatomyStructureCode}
      />

      <!-- ── Quando Usar ────────────────────────────────────────────── -->
      <DocsWhenToUse
        title={$tStore('usage.title')}
        guidelines={{
          title: $tStore('usage.guidelines.title'),
          items: [
            $tStore('usage.guidelines.item1'),
            $tStore('usage.guidelines.item2'),
            $tStore('usage.guidelines.item3'),
            $tStore('usage.guidelines.item4'),
            $tStore('usage.guidelines.item5'),
          ],
        }}
        scenarios={{
          title: $tStore('usage.scenarios.title'),
          cols: {
            scenario: $tStore('usage.scenarios.cols.scenario'),
            use: $tStore('usage.scenarios.cols.use'),
            alternative: $tStore('usage.scenarios.cols.alternative'),
          },
          items: [
            { s: $tStore('usage.scenarios.item1.s'), u: $tStore('usage.scenarios.item1.u'), a: toPlainText($tStore('usage.scenarios.item1.a')) },
            { s: $tStore('usage.scenarios.item2.s'), u: $tStore('usage.scenarios.item2.u'), a: toPlainText($tStore('usage.scenarios.item2.a')) },
            { s: $tStore('usage.scenarios.item3.s'), u: $tStore('usage.scenarios.item3.u'), a: toPlainText($tStore('usage.scenarios.item3.a')) },
            { s: $tStore('usage.scenarios.item4.s'), u: $tStore('usage.scenarios.item4.u'), a: toPlainText($tStore('usage.scenarios.item4.a')) },
            { s: $tStore('usage.scenarios.item5.s'), u: $tStore('usage.scenarios.item5.u'), a: toPlainText($tStore('usage.scenarios.item5.a')) },
          ],
        }}
        do={{
          title: $tStore('usage.do.title'),
          items: [
            $tStore('usage.do.item1'),
            $tStore('usage.do.item2'),
            $tStore('usage.do.item3'),
            $tStore('usage.do.item4'),
          ],
        }}
        dont={{
          title: $tStore('usage.dont.title'),
          items: [
            $tStore('usage.dont.item1'),
            $tStore('usage.dont.item2'),
            $tStore('usage.dont.item3'),
            $tStore('usage.dont.item4'),
          ],
        }}
      />

      <!-- ── Do & Don't ─────────────────────────────────────────────── -->
      <DocsDoDont
        title={$tStore('doDont.title')}
        pairs={[
          {
            doLabel: $tNavStore('common.do'),
            dontLabel: $tNavStore('common.dont'),
            doCaption: $tStore('doDont.pair1.do'),
            dontCaption: $tStore('doDont.pair1.dont'),
            doPreview: doPair1,
            dontPreview: dontPair1,
          },
          {
            doLabel: $tNavStore('common.do'),
            dontLabel: $tNavStore('common.dont'),
            doCaption: $tStore('doDont.pair2.do'),
            dontCaption: $tStore('doDont.pair2.dont'),
            doPreview: doPair2,
            dontPreview: dontPair2,
          },
        ]}
      />

      {#snippet doPair1()}
        <div class="nds-w-full nds-max-w-xs">
          <AspectRatio ratio={16 / 9}>
            <img src={IMG_LANDSCAPE} alt="Paisagem com object-cover" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}
      {#snippet dontPair1()}
        <div class="nds-w-full nds-max-w-xs">
          <AspectRatio ratio={16 / 9}>
            <img src={IMG_LANDSCAPE} alt="Paisagem com object-contain" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md nds-bg-muted" style="object-fit: contain; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}
      {#snippet doPair2()}
        <div class="nds-w-full nds-max-w-xs">
          <AspectRatio ratio={1}>
            <img src={IMG_AVATAR} alt="Avatar arredondado no filho" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}
      {#snippet dontPair2()}
        <div class="nds-w-full nds-max-w-xs nds-rounded-md nds-overflow-hidden">
          <AspectRatio ratio={1}>
            <img src={IMG_AVATAR} alt="Radius aplicado ao container" loading="lazy" decoding="async" class="nds-w-full" style="object-fit: cover; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}

      <!-- ── Importação ─────────────────────────────────────────────── -->
      <DocsImport
        title={$tStore('import.title')}
        code={codeImportBasic}
        secondaryCode={codeImportWithImage}
      />

      <!-- ── Variantes ──────────────────────────────────────────────── -->
      <DocsVariants
        title={$tStore('variants.title')}
        items={[
          { name: '16 / 9', description: $tStore('variants.items.sixteenNine'), code: codeSixteenNine, preview: variantSixteenNine },
          { name: '4 / 3',  description: $tStore('variants.items.fourThree'),  code: codeFourThree,   preview: variantFourThree   },
          { name: '1 / 1',  description: $tStore('variants.items.square'),     code: codeSquare,      preview: variantSquare      },
          { name: '3 / 4',  description: $tStore('variants.items.threeFour'),  code: codeThreeFour,   preview: variantThreeFour   },
          { name: '21 / 9', description: $tStore('variants.items.ultraWide'),  code: codeUltraWide,   preview: variantUltraWide   },
        ]}
      />

      {#snippet variantSixteenNine()}
        <div class="nds-w-full nds-max-w-md">
          <AspectRatio ratio={16 / 9}>
            <img src={IMG_LANDSCAPE} alt="Paisagem 16:9" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}
      {#snippet variantFourThree()}
        <div class="nds-w-full nds-max-w-md">
          <AspectRatio ratio={4 / 3}>
            <img src={IMG_PRODUCT} alt="Imagem de produto 4:3" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}
      {#snippet variantSquare()}
        <div style="width: 13rem">
          <AspectRatio ratio={1}>
            <img src={IMG_AVATAR} alt="Avatar quadrado 1:1" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}
      {#snippet variantThreeFour()}
        <div style="width: 13rem">
          <AspectRatio ratio={3 / 4}>
            <img src={IMG_PORTRAIT} alt="Retrato 3:4" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}
      {#snippet variantUltraWide()}
        <div class="nds-w-full" style="max-width: 36rem">
          <AspectRatio ratio={21 / 9}>
            <img src={IMG_ULTRA} alt="Hero ultra-wide 21:9" loading="lazy" decoding="async" class="nds-w-full nds-rounded-md" style="object-fit: cover; height: 100%" />
          </AspectRatio>
        </div>
      {/snippet}

      <!-- ── Estados ────────────────────────────────────────────────── -->
      <DocsStates
        title={$tStore('states.title')}
        cols={{
          state: $tStore('props.table.prop'),
          trigger: $tNavStore('common.userAction'),
          behavior: $tNavStore('common.expectedResult'),
        }}
        items={[
          { label: $tStore('states.item1.label'), trigger: toPlainText($tStore('states.item1.trigger')), behavior: toPlainText($tStore('states.item1.behavior'))},
          { label: $tStore('states.item2.label'), trigger: toPlainText($tStore('states.item2.trigger')), behavior: toPlainText($tStore('states.item2.behavior'))},
          { label: $tStore('states.item3.label'), trigger: toPlainText($tStore('states.item3.trigger')), behavior: toPlainText($tStore('states.item3.behavior')) },
        ]}
      />

      <!-- ── Propriedades ───────────────────────────────────────────── -->
      <DocsProps
        title={$tStore('props.title')}
        tables={[
          {
            cols: {
              prop: $tStore('props.table.prop'),
              type: $tStore('props.table.type'),
              default: $tStore('props.table.default'),
              required: $tStore('props.table.required'),
              description: $tStore('props.table.description'),
            },
            items: [
              { name: 'ratio',    type: 'number',  defaultValue: '1',       required: 'Não', description: toPlainText($tStore('props.table.ratio'))     },
              { name: 'children', type: 'Snippet', defaultValue: '—',       required: 'Sim', description: toPlainText($tStore('props.table.children'))  },
              { name: 'child',    type: 'Snippet<[{ props }]>', defaultValue: '—', required: 'Não', description: toPlainText($tStore('props.table.asChild'))   },
              { name: 'class',    type: 'string',  defaultValue: '—',       required: 'Não', description: toPlainText($tStore('props.table.className')) },
            ],
          },
        ]}
        interfaceCode={interfaceCode}
        extensibilityTitle={$tStore('props.extensibilityTitle')}
        extensibilityNotes={$tStore('props.extensibility')}
      />

      <!-- ── Tokens ─────────────────────────────────────────────────── -->
      <DocsTokens
        title={$tStore('tokens.title')}
        cols={{
          token: $tStore('tokens.table.token'),
          value: $tStore('tokens.table.class'),
          description: $tStore('tokens.table.part'),
        }}
        items={[
          { token: '--radius', value: 'rounded-md',    description: $tStore('tokens.table.radius') },
          { token: '--border', value: 'border',        description: $tStore('tokens.table.border') },
          { token: '--muted',  value: 'bg-muted',      description: $tStore('tokens.table.muted')  },
        ]}
        customizationTitle={$tStore('tokens.customizationTitle')}
        customizationCode={codeCustomizationTokens}
      />

      <!-- ── Acessibilidade ─────────────────────────────────────────── -->
      <DocsAccessibility
        screenReaderTitle={$tNavStore('common.screenReader')}
        screenReaderItems={screenReaderItems}
        title={$tStore('accessibility.title')}
        summary={$tStore('accessibility.summary')}
        items={[
          $tStore('accessibility.aria.item1'),
          $tStore('accessibility.aria.item2'),
          $tStore('accessibility.aria.item3'),
          $tStore('accessibility.aria.item4'),
          $tStore('accessibility.aria.item5'),
        ]}
        keyboardTitle={$tStore('accessibility.keyboard.title')}
        keyboardItems={[
          { key: '—', description: $tStore('accessibility.keyboard.item1') },
          { key: 'Tab', description: $tStore('accessibility.keyboard.note') },
        ]}
      />

      <!-- ── Relacionados ───────────────────────────────────────────── -->
      <DocsRelated
        title={$tStore('related.title')}
        items={[
          { name: 'Avatar',     description: $tStore('related.avatar'),   path: '?path=/docs/ui-avatar--docs'     },
          { name: 'Card',       description: $tStore('related.card'),     path: '?path=/docs/ui-card--docs'       },
          { name: 'Skeleton',   description: $tStore('related.skeleton'), path: '?path=/docs/ui-skeleton--docs'   },
          { name: 'ScrollArea', description: $tStore('related.aspectRatio'), path: '?path=/docs/ui-scrollarea--docs' },
        ]}
      />

      <!-- ── Notas ──────────────────────────────────────────────────── -->
      <DocsNotes
        title={$tStore('notes.title')}
        items={[
          { title: '', content: $tStore('notes.item1') },
          { title: '', content: $tStore('notes.item2') },
          { title: '', content: $tStore('notes.item3') },
          { title: '', content: $tStore('notes.item4') },
        ]}
      />

      <!-- ── Analytics ─────────────────────────────────────────────── -->
      <DocsAnalytics
        title={$tStore('analytics.title')}
        cols={{
          event: $tStore('analytics.table.event'),
          trigger: toPlainText($tStore('analytics.table.trigger')),
          payload: $tStore('analytics.table.payload'),
        }}
        items={[
          { event: '—', trigger: stripHtml($tStore('analytics.note')), payload: '—' },
        ]}
      />

      <!-- ── Testes ─────────────────────────────────────────────────── -->
      <DocsTestes
        title={$tStore('testes.title')}
        functional={{
          title: $tStore('testes.functional.title'),
          cols: {
            action: $tNavStore('common.userAction'),
            result: $tNavStore('common.expectedResult'),
            priority: $tNavStore('common.priority'),
          },
          items: [
            { action: toPlainText($tStore('testes.functional.item1.action')), result: toPlainText($tStore('testes.functional.item1.result')), priority: localPriority($tStore('testes.functional.item1.priority'), $tNavStore) },
            { action: toPlainText($tStore('testes.functional.item2.action')), result: toPlainText($tStore('testes.functional.item2.result')), priority: localPriority($tStore('testes.functional.item2.priority'), $tNavStore) },
            { action: toPlainText($tStore('testes.functional.item3.action')), result: toPlainText($tStore('testes.functional.item3.result')), priority: localPriority($tStore('testes.functional.item3.priority'), $tNavStore) },
            { action: toPlainText($tStore('testes.functional.item4.action')), result: toPlainText($tStore('testes.functional.item4.result')), priority: localPriority($tStore('testes.functional.item4.priority'), $tNavStore) },
            { action: toPlainText($tStore('testes.functional.item5.action')), result: toPlainText($tStore('testes.functional.item5.result')), priority: localPriority($tStore('testes.functional.item5.priority'), $tNavStore) },
          ],
        }}
        accessibility={{
          title: $tStore('testes.accessibility.title'),
          cols: {
            criterion: $tNavStore('common.criterion'),
            level: 'WCAG',
            how: $tNavStore('common.howToVerify'),
          },
          items: [
            { criterion: toPlainText($tStore('testes.accessibility.item1.criterion')), level: $tStore('testes.accessibility.item1.level'), how: $tStore('testes.accessibility.item1.how') },
            { criterion: toPlainText($tStore('testes.accessibility.item2.criterion')), level: $tStore('testes.accessibility.item2.level'), how: $tStore('testes.accessibility.item2.how') },
            { criterion: toPlainText($tStore('testes.accessibility.item3.criterion')), level: $tStore('testes.accessibility.item3.level'), how: $tStore('testes.accessibility.item3.how') },
            { criterion: toPlainText($tStore('testes.accessibility.item4.criterion')), level: $tStore('testes.accessibility.item4.level'), how: toPlainText($tStore('testes.accessibility.item4.how')) },
            { criterion: toPlainText($tStore('testes.accessibility.item5.criterion')), level: $tStore('testes.accessibility.item5.level'), how: toPlainText($tStore('testes.accessibility.item5.how')) },
          ],
        }}
        visual={{
          title: $tStore('testes.visual.title'),
          cols: {
            story: $tNavStore('common.storyState'),
            priority: $tNavStore('common.priority'),
          },
          items: [
            { story: $tStore('testes.visual.item1.story'), priority: localPriority($tStore('testes.visual.item1.priority'), $tNavStore) },
            { story: $tStore('testes.visual.item2.story'), priority: localPriority($tStore('testes.visual.item2.priority'), $tNavStore) },
            { story: $tStore('testes.visual.item3.story'), priority: localPriority($tStore('testes.visual.item3.priority'), $tNavStore) },
            { story: $tStore('testes.visual.item4.story'), priority: localPriority($tStore('testes.visual.item4.priority'), $tNavStore) },
            { story: $tStore('testes.visual.item5.story'), priority: localPriority($tStore('testes.visual.item5.priority'), $tNavStore) },
          ],
        }}
      />
</DocsPageLayout>
