// nortear-design-system-react/src/components/docs/MarkdownDocs.tsx
import { useCallback, useEffect, useMemo } from "react";
import { Markdown } from "@/components/ui/markdown";
import { useTranslation } from "@/lib/i18n";
import { useSeoEffect } from "@/lib/use-seo";
import { track } from "@/lib/analytics";
import { useActiveSection } from "@/lib/use-active-section";
import uiTranslations from "@/i18n/ui.json";
import markdownTranslations from "@shared/content/markdown/translations.json";
import { ALLOW_PRESETS } from "@shared/primitives/markdown-ast";
import {
  MARKDOWN_CODE,
  MARKDOWN_COMMENT,
  MARKDOWN_PROSE,
  MARKDOWN_TABLE,
  MARKDOWN_UNSAFE,
} from "@shared/primitives/markdown-examples";

import { DocsHeader }        from "@/components/docs/shared/sections/DocsHeader";
import { DocsPageLayout }    from "@/components/docs/shared/sections/DocsPageLayout";
import { DocsDemonstration } from "@/components/docs/shared/sections/DocsDemonstration";
import { DocsAnatomy }       from "@/components/docs/shared/sections/DocsAnatomy";
import { DocsWhenToUse }     from "@/components/docs/shared/sections/DocsWhenToUse";
import { DocsDoDont }        from "@/components/docs/shared/sections/DocsDoDont";
import { DocsImport }        from "@/components/docs/shared/sections/DocsImport";
import { DocsVariants }      from "@/components/docs/shared/sections/DocsVariants";
import { DocsStates }        from "@/components/docs/shared/sections/DocsStates";
import { DocsProps }         from "@/components/docs/shared/sections/DocsProps";
import { DocsTokens }        from "@/components/docs/shared/sections/DocsTokens";
import { DocsAccessibility } from "@/components/docs/shared/sections/DocsAccessibility";
import { DocsRelated }       from "@/components/docs/shared/sections/DocsRelated";
import { DocsNotes }         from "@/components/docs/shared/sections/DocsNotes";
import { DocsAnalytics }     from "@/components/docs/shared/sections/DocsAnalytics";
import { DocsTestes }        from "@/components/docs/shared/sections/DocsTestes";
import { toPlainText } from "@/lib/strip-html";

// ─── Helpers ─────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: "common.high",
  medium: "common.medium",
  low: "common.low",
};

// ─── Nav ─────────────────────────────────────────────────────────────────────

const getNavGroups = (t: (key: string) => string) => [
  {
    label: t("nav.overview"),
    sections: [
      { id: "demonstracao", label: t("nav.demonstration") },
      { id: "anatomia",     label: t("nav.anatomy") },
      { id: "quando-usar",  label: t("nav.usage") },
      { id: "do-dont",      label: t("nav.doDont") },
    ],
  },
  {
    label: t("nav.techRef"),
    sections: [
      { id: "importacao",   label: t("nav.import") },
      { id: "variantes",    label: t("nav.variants") },
      { id: "estados",      label: t("nav.states") },
      { id: "propriedades", label: t("nav.props") },
      { id: "tokens",       label: t("nav.tokens") },
    ],
  },
  {
    label: t("nav.context"),
    sections: [
      { id: "acessibilidade", label: t("nav.accessibility") },
      { id: "relacionados",   label: t("nav.related") },
      { id: "notas",          label: t("nav.notes") },
    ],
  },
  {
    label: t("nav.quality"),
    sections: [
      { id: "analytics", label: t("nav.analytics") },
      { id: "testes",    label: t("nav.testes") },
    ],
  },
];

// ─── Componente principal ─────────────────────────────────────────────────────

export function MarkdownDocs() {
  const { t: tNav } = useTranslation(uiTranslations);
  const { t: tContent, locale } = useTranslation(markdownTranslations);

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria.
  // O `title` fica de fora: ele é o cabeçalho da lista, não um item dela.
  const screenReaderItems = useMemo(
    () =>
      Object.entries(
        (markdownTranslations as unknown as Record<
          string,
          { accessibility?: { screenReader?: Record<string, string> } }
        >)[locale]?.accessibility?.screenReader ?? {},
      )
        .filter(([key]) => key !== "title")
        .map(([, value]) => value),
    [locale],
  );

  const navGroups = useMemo(() => getNavGroups(tNav), [tNav]);
  const allIds = useMemo(
    () => navGroups.flatMap((g) => g.sections.map((s) => s.id)),
    [navGroups],
  );

  useSeoEffect({
    title: tContent("seo.title"),
    description: tContent("seo.description"),
    locale,
    componentSlug: "markdown",
  });

  useEffect(() => {
    track("docs_page_view", {
      component_name: "markdown",
      locale,
      page_title: `${tContent("title")} · Design System`,
    });
  }, [locale, tContent]);

  const handleSectionChange = useCallback(
    (id: string) => {
      track("docs_section_viewed", {
        section_id: id,
        component_name: "markdown",
        locale,
      });
    },
    [locale],
  );

  const activeId = useActiveSection(allIds, handleSectionChange);

  const priorityLabel = (raw: string) => tNav(priorityKeyMap[raw] ?? "common.high");

  /**
   * Um exemplo rotulado: a legenda diz QUAL documento está sendo desenhado.
   *
   * Sem a legenda, quatro documentos empilhados viram um só texto comprido — e
   * o assunto da demonstração é justamente a diferença entre eles.
   */
  const example = (labelKey: string, content: string) => (
    <div className="nds-stack nds-w-full" data-spacing="xs">
      <p className="nds-text-caption nds-text-muted-foreground">{tContent(labelKey)}</p>
      <Markdown content={content} />
    </div>
  );

  return (
    <DocsPageLayout
      navGroups={navGroups}
      activeSection={activeId}
      header={
        <DocsHeader
          title={tContent("title")}
          description={tContent("description")}
          category={tContent("category")}
          type={tContent("type")}
        />
      }
    >
      {/* ── Demonstração ──────────────────────────────────────────── */}
      <DocsDemonstration componentSlug="markdown">
        <div className="nds-stack nds-w-full" data-spacing="lg">
          {example("demonstration.labels.prose", MARKDOWN_PROSE)}
          {example("demonstration.labels.code", MARKDOWN_CODE)}
          {example("demonstration.labels.table", MARKDOWN_TABLE)}
          {example("demonstration.labels.unsafe", MARKDOWN_UNSAFE)}
        </div>
      </DocsDemonstration>

      {/* ── Anatomia ──────────────────────────────────────────────── */}
      <DocsAnatomy
        items={[
          tContent("anatomy.item1"),
          tContent("anatomy.item2"),
          tContent("anatomy.item3"),
          tContent("anatomy.item4"),
          tContent("anatomy.item5"),
        ]}
        structureCode={tContent("anatomy.structureCode")}
      />

      {/* ── Quando Usar ───────────────────────────────────────────── */}
      <DocsWhenToUse
        guidelines={{
          title: tContent("usage.guidelines.title"),
          items: [1, 2, 3, 4, 5].map((i) => tContent(`usage.guidelines.item${i}`)),
        }}
        scenarios={{
          title: tContent("usage.scenarios.title"),
          cols: {
            scenario: tContent("usage.scenarios.cols.scenario"),
            use: tContent("usage.scenarios.cols.use"),
            alternative: tContent("usage.scenarios.cols.alternative"),
          },
          items: [1, 2, 3, 4, 5].map((i) => ({
            s: tContent(`usage.scenarios.item${i}.s`),
            u: tContent(`usage.scenarios.item${i}.u`),
            a: toPlainText(tContent(`usage.scenarios.item${i}.a`)),
          })),
        }}
        uxWriting={{
          title: tContent("usage.uxWriting.title"),
          cols: {
            element: tContent("usage.uxWriting.table.element"),
            rules: tContent("usage.uxWriting.table.rules"),
            do: tContent("usage.uxWriting.table.correct"),
            dont: tContent("usage.uxWriting.table.avoid"),
          },
          items: ["heading", "link", "image", "code"].map((k) => ({
            element: tContent(`usage.uxWriting.table.${k}.name`),
            rules: tContent(`usage.uxWriting.table.${k}.format`),
            do: tContent(`usage.uxWriting.table.${k}.good`),
            dont: tContent(`usage.uxWriting.table.${k}.bad`),
          })),
        }}
        do={{
          title: tContent("usage.do.title"),
          items: [1, 2, 3, 4].map((i) => tContent(`usage.do.item${i}`)),
        }}
        dont={{
          title: tContent("usage.dont.title"),
          items: [1, 2, 3, 4].map((i) => tContent(`usage.dont.item${i}`)),
        }}
      />

      {/* ── Do & Don't ────────────────────────────────────────────── */}
      <DocsDoDont
        pairs={[
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doCaption: toPlainText(tContent("doDont.pair1.do")),
            dontCaption: toPlainText(tContent("doDont.pair1.dont")),
            // O par inteiro é o MESMO texto: o que muda é o que se faz com o
            // endereço recusado. Desenhar dois textos diferentes trocaria a
            // lição por uma comparação de conteúdo.
            doPreview: (
              <Markdown content="[Leia a política de privacidade](javascript:alert(1)) antes de continuar." />
            ),
            dontPreview: <Markdown content="antes de continuar." />,
          },
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doCaption: toPlainText(tContent("doDont.pair2.do")),
            dontCaption: toPlainText(tContent("doDont.pair2.dont")),
            doPreview: <Markdown content={MARKDOWN_COMMENT} allow={ALLOW_PRESETS.comment} />,
            dontPreview: (
              <Markdown content="Concordo com o **ponto principal**." allow={ALLOW_PRESETS.comment} />
            ),
          },
        ]}
      />

      {/* ── Importação ────────────────────────────────────────────── */}
      <DocsImport componentSlug="markdown"
        description={tContent("import.basic")}
        code={tContent("import.basicCode")}
        secondaryDescription={tContent("import.withStreaming")}
        secondaryCode={tContent("import.withStreamingCode")}
      />

      {/* ── Listas brancas ────────────────────────────────────────── */}
      <DocsVariants
        note={tContent("variants.note")}
        componentSlug="markdown"
        items={[
          {
            name: "full",
            description: tContent("variants.items.full.description"),
            code: `<Markdown content={resposta} />`,
            preview: <Markdown content={MARKDOWN_COMMENT} />,
          },
          {
            name: "chat",
            description: tContent("variants.items.chat.description"),
            code: `<Markdown\n  content={resposta}\n  allow={["paragraph", "code", "blockquote", "list", "thematicBreak", "raw"]}\n/>`,
            preview: <Markdown content={MARKDOWN_COMMENT} allow={ALLOW_PRESETS.chat} />,
          },
          {
            name: "comment",
            description: tContent("variants.items.comment.description"),
            code: `<Markdown content={resposta} allow={["paragraph", "raw"]} />`,
            preview: <Markdown content={MARKDOWN_COMMENT} allow={ALLOW_PRESETS.comment} />,
          },
        ]}
      />

      {/* ── Estados ───────────────────────────────────────────────── */}
      <DocsStates
        cols={{
          state: tContent("states.cols.state"),
          trigger: tContent("states.cols.trigger"),
          behavior: tContent("states.cols.behavior"),
        }}
        items={["idle", "streaming", "refused", "empty"].map((k) => ({
          label: tContent(`states.${k}.label`),
          trigger: toPlainText(tContent(`states.${k}.trigger`)),
          behavior: toPlainText(tContent(`states.${k}.behavior`)),
        }))}
      />

      {/* ── Propriedades ──────────────────────────────────────────── */}
      <DocsProps
        tables={[
          {
            title: "Markdown",
            cols: {
              prop: tContent("props.table.prop"),
              type: tContent("props.table.type"),
              default: tContent("props.table.default"),
              required: tContent("props.table.required"),
              description: tContent("props.table.description"),
            },
            items: ["content", "streaming", "allow", "allowedProtocols", "onLinkClick", "class"].map(
              (k) => ({
                name: tContent(`props.table.${k}.name`),
                type: tContent(`props.table.${k}.type`),
                defaultValue: tContent(`props.table.${k}.default`),
                required: tContent(`props.table.${k}.required`),
                description: toPlainText(tContent(`props.table.${k}.description`)),
              }),
            ),
          },
        ]}
        interfaceCode={`interface MarkdownProps extends React.ComponentProps<"div"> {
  content: string;
  streaming?: boolean;
  allow?: readonly MdBlockKind[];
  allowedProtocols?: readonly string[];
  onLinkClick?: (url: string) => void;
}`}
        extensibilityTitle={tContent("props.extensibilityTitle")}
        extensibilityNotes={tContent("props.extensibility")}
        extensibilityCode={tContent("props.extensibilityCode")}
      />

      {/* ── Tokens ────────────────────────────────────────────────── */}
      <DocsTokens
        cols={{
          token: tContent("tokens.table.token"),
          value: tContent("tokens.table.value"),
          description: tContent("tokens.table.description"),
        }}
        items={[
          { token: "--foreground", value: ".nds-markdown",                    description: tContent("tokens.table.foreground.description") },
          { token: "--primary",    value: ".nds-markdown-link",               description: tContent("tokens.table.linkColor.description") },
          { token: "--ring",       value: ".nds-markdown-link:focus-visible", description: tContent("tokens.table.linkRing.description") },
          { token: "--primary",    value: ".nds-markdown-quote",              description: tContent("tokens.table.quoteBar.description") },
          { token: "--border",     value: ".nds-markdown-rule",               description: tContent("tokens.table.ruleLine.description") },
          { token: "--radius-md",  value: ".nds-markdown-image",              description: tContent("tokens.table.imageRadius.description") },
        ]}
        customizationTitle={tContent("tokens.customizationTitle")}
        customizationCode={tContent("tokens.customizationCode")}
        language="css"
      />

      {/* ── Acessibilidade ────────────────────────────────────────── */}
      <DocsAccessibility
        summary={tContent("accessibility.summary")}
        items={[1, 2, 3, 4, 5].map((i) => tContent(`accessibility.items.item${i}`))}
        keyboardTitle={tContent("accessibility.keyboard.title")}
        keyboardItems={[
          { key: "Tab",   description: tContent("accessibility.keyboard.tab") },
          { key: "Enter", description: tContent("accessibility.keyboard.enter") },
          { key: "↑ ↓",   description: tContent("accessibility.keyboard.arrows") },
        ]}
        screenReaderTitle={tContent("accessibility.screenReader.title")}
        screenReaderItems={screenReaderItems}
      />

      {/* ── Relacionados ──────────────────────────────────────────── */}
      <DocsRelated componentSlug="markdown"
        items={[
          { name: tContent("related.items.codeBlock.name"), description: toPlainText(tContent("related.items.codeBlock.description")), path: "?path=/docs/components-display-codeblock--docs" },
          { name: tContent("related.items.editor.name"),    description: toPlainText(tContent("related.items.editor.description")),    path: "?path=/docs/components-form-editor--docs" },
          { name: tContent("related.items.table.name"),     description: toPlainText(tContent("related.items.table.description")),     path: "?path=/docs/components-tables-table--docs" },
          { name: tContent("related.items.skeleton.name"),  description: toPlainText(tContent("related.items.skeleton.description")),  path: "?path=/docs/components-feedback-skeleton--docs" },
        ]}
      />

      {/* ── Notas ─────────────────────────────────────────────────── */}
      <DocsNotes
        componentSlug="markdown"
        items={[1, 2, 3, 4].map((i) => ({ title: "", content: tContent(`notes.item${i}`) }))}
      />

      {/* ── Analytics ─────────────────────────────────────────────── */}
      <DocsAnalytics
        cols={{
          event: tContent("analytics.table.event"),
          trigger: tContent("analytics.table.trigger"),
          payload: tContent("analytics.table.payload"),
        }}
        items={["pageView", "sectionViewed", "demoClick"].map((k) => ({
          event: tContent(`analytics.table.${k}`),
          trigger: toPlainText(tContent(`analytics.table.${k}Trigger`)),
          payload: tContent(`analytics.table.${k}Payload`),
        }))}
      />

      {/* ── Testes ────────────────────────────────────────────────── */}
      <DocsTestes
        functional={{
          title: tContent("testes.functional.title"),
          description: tContent("testes.functional.description"),
          cols: {
            action: tNav("common.userAction"),
            result: tNav("common.expectedResult"),
            priority: tNav("common.priority"),
          },
          items: [1, 2, 3, 4, 5, 6].map((i) => ({
            action: toPlainText(tContent(`testes.functional.item${i}.action`)),
            result: toPlainText(tContent(`testes.functional.item${i}.result`)),
            priority: priorityLabel(tContent(`testes.functional.item${i}.priority`)),
          })),
        }}
        accessibility={{
          title: tContent("testes.accessibility.title"),
          description: tContent("testes.accessibility.description"),
          cols: {
            criterion: tNav("common.criterion"),
            level: "WCAG",
            how: tNav("common.howToVerify"),
          },
          // A lista é PLANA: cada item é um critério, e o "como verificar" é o
          // próprio addon-a11y rodando em toda story.
          items: [1, 2, 3, 4, 5].map((i) => ({
            criterion: toPlainText(tContent(`testes.accessibility.item${i}`)),
            level: "AA",
            how: "—",
          })),
        }}
        visual={{
          title: tContent("testes.visual.title"),
          description: tContent("testes.visual.description"),
          cols: {
            story: tNav("common.storyState"),
            priority: tNav("common.priority"),
          },
          items: [1, 2, 3, 4, 5].map((i) => ({
            story: toPlainText(tContent(`testes.visual.item${i}.story`)),
            priority: priorityLabel(tContent(`testes.visual.item${i}.priority`)),
          })),
        }}
      />
    </DocsPageLayout>
  );
}

// nortear-design-system-svelte/src/components/docs/MarkdownDocs.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { Markdown } from '@/components/ui/markdown';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import { createActiveSection } from '@/lib/use-active-section.svelte';
  import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader, DocsDemonstration, DocsAnatomy, DocsWhenToUse, DocsDoDont,
    DocsImport, DocsVariants, DocsStates, DocsProps, DocsTokens,
    DocsAccessibility, DocsRelated, DocsNotes, DocsAnalytics, DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import markdownTranslations from '@shared/content/markdown/translations.json';
  import { ALLOW_PRESETS } from '@shared/primitives/markdown-ast';
  import {
    MARKDOWN_CODE,
    MARKDOWN_COMMENT,
    MARKDOWN_PROSE,
    MARKDOWN_TABLE,
    MARKDOWN_UNSAFE,
  } from '@shared/primitives/markdown-examples';
  import { toPlainText } from '@/lib/strip-html';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(markdownTranslations);

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria. O
  // `title` fica de fora: ele é o cabeçalho da lista, não um item dela.
  const screenReaderItems = $derived(
    Object.entries(
      (markdownTranslations as unknown as Record<
        string,
        { accessibility?: { screenReader?: Record<string, string> } }
      >)[$locale]?.accessibility?.screenReader ?? {},
    )
      .filter(([key]) => key !== 'title')
      .map(([, value]) => value),
  );

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'markdown',
    });
    track('docs_page_view', {
      component_name: 'markdown',
      locale: l,
      page_title: `${t('title')} · Design System`,
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────

  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')   },
        { id: 'variantes',    label: tNav('nav.variants') },
        { id: 'estados',      label: tNav('nav.states')   },
        { id: 'propriedades', label: tNav('nav.props')    },
        { id: 'tokens',       label: tNav('nav.tokens')   },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  const sectionIds = untrack(() => NAV_GROUPS.flatMap(g => g.sections.map(s => s.id)));
  const section = createActiveSection(sectionIds, (id) => {
    track('docs_section_viewed', { section_id: id, component_name: 'markdown', locale: $locale });
  });
  $effect(() => section.attach());

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  const priorityKeyMap: Record<string, string> = { high: 'common.high', medium: 'common.medium', low: 'common.low' };
  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  // ─── Exemplos ────────────────────────────────────────────────────────────────

  const EXAMPLES = [
    { key: 'prose', content: MARKDOWN_PROSE },
    { key: 'code', content: MARKDOWN_CODE },
    { key: 'table', content: MARKDOWN_TABLE },
    { key: 'unsafe', content: MARKDOWN_UNSAFE },
  ];

  /** O par do Do & Don't é o MESMO texto: o que muda é o que se faz com ele. */
  const REFUSED_LINK = '[Leia a política de privacidade](javascript:alert(1)) antes de continuar.';
  const REFUSED_LINK_DROPPED = 'antes de continuar.';
  const COMMENT_TRIMMED = 'Concordo com o **ponto principal**.';

  // ─── Code strings ────────────────────────────────────────────────────────────

  const interfaceCode = `interface MarkdownProps {
  content: string;
  streaming?: boolean;
  allow?: readonly MdBlockKind[];
  allowedProtocols?: readonly string[];
  onLinkClick?: (url: string) => void;
  class?: string;
}`;

  const codeFull = '<Markdown content={answer} />';
  const codeChat = `<Markdown
  content={answer}
  allow={["paragraph", "code", "blockquote", "list", "thematicBreak", "raw"]}
/>`;
  const codeComment = '<Markdown content={answer} allow={["paragraph", "raw"]} />';
</script>

<DocsPageLayout navGroups={NAV_GROUPS} activeSection={section.value}>
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
    />
  {/snippet}

  <!-- ── Demonstração ───────────────────────────────────────────── -->
  <DocsDemonstration componentSlug="markdown">
    <div class="nds-stack nds-w-full" data-spacing="lg">
      <!--
        A legenda diz QUAL documento está sendo desenhado. Sem ela, quatro
        documentos empilhados viram um só texto comprido — e o assunto da
        demonstração é justamente a diferença entre eles.
      -->
      {#each EXAMPLES as example (example.key)}
        <div class="nds-stack nds-w-full" data-spacing="xs">
          <p class="nds-text-caption nds-text-muted-foreground">
            {$tStore(`demonstration.labels.${example.key}`)}
          </p>
          <Markdown content={example.content} />
        </div>
      {/each}
    </div>
  </DocsDemonstration>

  <!-- ── Anatomia ───────────────────────────────────────────────── -->
  <DocsAnatomy
    items={[
      $tStore('anatomy.item1'),
      $tStore('anatomy.item2'),
      $tStore('anatomy.item3'),
      $tStore('anatomy.item4'),
      $tStore('anatomy.item5'),
    ]}
    structureCode={$tStore('anatomy.structureCode')}
  />

  <!-- ── Quando Usar ────────────────────────────────────────────── -->
  <DocsWhenToUse
    guidelines={{
      title: $tStore('usage.guidelines.title'),
      items: [1, 2, 3, 4, 5].map(i => $tStore(`usage.guidelines.item${i}`)),
    }}
    scenarios={{
      title: $tStore('usage.scenarios.title'),
      cols: {
        scenario: $tStore('usage.scenarios.cols.scenario'),
        use: $tStore('usage.scenarios.cols.use'),
        alternative: $tStore('usage.scenarios.cols.alternative'),
      },
      items: [1, 2, 3, 4, 5].map(i => ({
        s: $tStore(`usage.scenarios.item${i}.s`),
        u: $tStore(`usage.scenarios.item${i}.u`),
        a: toPlainText($tStore(`usage.scenarios.item${i}.a`)),
      })),
    }}
    uxWriting={{
      title: $tStore('usage.uxWriting.title'),
      cols: {
        element: $tStore('usage.uxWriting.table.element'),
        rules: $tStore('usage.uxWriting.table.rules'),
        do: $tStore('usage.uxWriting.table.correct'),
        dont: $tStore('usage.uxWriting.table.avoid'),
      },
      items: ['heading', 'link', 'image', 'code'].map(k => ({
        element: $tStore(`usage.uxWriting.table.${k}.name`),
        rules: $tStore(`usage.uxWriting.table.${k}.format`),
        do: $tStore(`usage.uxWriting.table.${k}.good`),
        dont: $tStore(`usage.uxWriting.table.${k}.bad`),
      })),
    }}
    do={{
      title: $tStore('usage.do.title'),
      items: [1, 2, 3, 4].map(i => $tStore(`usage.do.item${i}`)),
    }}
    dont={{
      title: $tStore('usage.dont.title'),
      items: [1, 2, 3, 4].map(i => $tStore(`usage.dont.item${i}`)),
    }}
  />

  <!-- ── Do & Don't ─────────────────────────────────────────────── -->
  <DocsDoDont
    pairs={[
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: toPlainText($tStore('doDont.pair1.do')),
        dontCaption: toPlainText($tStore('doDont.pair1.dont')),
        doPreview: doPair1,
        dontPreview: dontPair1,
      },
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: toPlainText($tStore('doDont.pair2.do')),
        dontCaption: toPlainText($tStore('doDont.pair2.dont')),
        doPreview: doPair2,
        dontPreview: dontPair2,
      },
    ]}
  />

  {#snippet doPair1()}
    <Markdown content={REFUSED_LINK} />
  {/snippet}
  {#snippet dontPair1()}
    <Markdown content={REFUSED_LINK_DROPPED} />
  {/snippet}
  {#snippet doPair2()}
    <Markdown content={MARKDOWN_COMMENT} allow={ALLOW_PRESETS.comment} />
  {/snippet}
  {#snippet dontPair2()}
    <Markdown content={COMMENT_TRIMMED} allow={ALLOW_PRESETS.comment} />
  {/snippet}

  <!-- ── Importação ─────────────────────────────────────────────── -->
  <DocsImport componentSlug="markdown"
    description={$tStore('import.basic')}
    code={$tStore('import.basicCode')}
    secondaryDescription={$tStore('import.withStreaming')}
    secondaryCode={$tStore('import.withStreamingCode')}
  />

  <!-- ── Listas brancas ─────────────────────────────────────────── -->
  <DocsVariants
    note={$tStore('variants.note')}
    componentSlug="markdown"
    items={[
      { name: 'full',    description: $tStore('variants.items.full.description'),    code: codeFull,    preview: variantFull },
      { name: 'chat',    description: $tStore('variants.items.chat.description'),    code: codeChat,    preview: variantChat },
      { name: 'comment', description: $tStore('variants.items.comment.description'), code: codeComment, preview: variantComment },
    ]}
  />

  {#snippet variantFull()}
    <Markdown content={MARKDOWN_COMMENT} />
  {/snippet}
  {#snippet variantChat()}
    <Markdown content={MARKDOWN_COMMENT} allow={ALLOW_PRESETS.chat} />
  {/snippet}
  {#snippet variantComment()}
    <Markdown content={MARKDOWN_COMMENT} allow={ALLOW_PRESETS.comment} />
  {/snippet}

  <!-- ── Estados ────────────────────────────────────────────────── -->
  <DocsStates
    cols={{
      state: $tStore('states.cols.state'),
      trigger: $tStore('states.cols.trigger'),
      behavior: $tStore('states.cols.behavior'),
    }}
    items={['idle', 'streaming', 'refused', 'empty'].map(k => ({
      label: $tStore(`states.${k}.label`),
      trigger: toPlainText($tStore(`states.${k}.trigger`)),
      behavior: toPlainText($tStore(`states.${k}.behavior`)),
    }))}
  />

  <!-- ── Propriedades ───────────────────────────────────────────── -->
  <DocsProps
    tables={[
      {
        title: 'Markdown',
        cols: {
          prop: $tStore('props.table.prop'),
          type: $tStore('props.table.type'),
          default: $tStore('props.table.default'),
          required: $tStore('props.table.required'),
          description: $tStore('props.table.description'),
        },
        items: ['content', 'streaming', 'allow', 'allowedProtocols', 'onLinkClick', 'class'].map(k => ({
          name: $tStore(`props.table.${k}.name`),
          type: $tStore(`props.table.${k}.type`),
          defaultValue: $tStore(`props.table.${k}.default`),
          required: $tStore(`props.table.${k}.required`),
          description: toPlainText($tStore(`props.table.${k}.description`)),
        })),
      },
    ]}
    interfaceCode={interfaceCode}
    extensibilityTitle={$tStore('props.extensibilityTitle')}
    extensibilityNotes={$tStore('props.extensibility')}
    extensibilityCode={$tStore('props.extensibilityCode')}
  />

  <!-- ── Tokens ─────────────────────────────────────────────────── -->
  <DocsTokens
    cols={{
      token: $tStore('tokens.table.token'),
      value: $tStore('tokens.table.value'),
      description: $tStore('tokens.table.description'),
    }}
    items={[
      { token: '--foreground', value: '.nds-markdown',                    description: $tStore('tokens.table.foreground.description') },
      { token: '--primary',    value: '.nds-markdown-link',               description: $tStore('tokens.table.linkColor.description') },
      { token: '--ring',       value: '.nds-markdown-link:focus-visible', description: $tStore('tokens.table.linkRing.description') },
      { token: '--primary',    value: '.nds-markdown-quote',              description: $tStore('tokens.table.quoteBar.description') },
      { token: '--border',     value: '.nds-markdown-rule',               description: $tStore('tokens.table.ruleLine.description') },
      { token: '--radius-md',  value: '.nds-markdown-image',              description: $tStore('tokens.table.imageRadius.description') },
    ]}
    customizationTitle={$tStore('tokens.customizationTitle')}
    customizationCode={$tStore('tokens.customizationCode')}
    language="css"
  />

  <!-- ── Acessibilidade ─────────────────────────────────────────── -->
  <DocsAccessibility
    summary={$tStore('accessibility.summary')}
    items={[1, 2, 3, 4, 5].map(i => $tStore(`accessibility.items.item${i}`))}
    keyboardTitle={$tStore('accessibility.keyboard.title')}
    keyboardItems={[
      { key: 'Tab',   description: $tStore('accessibility.keyboard.tab') },
      { key: 'Enter', description: $tStore('accessibility.keyboard.enter') },
      { key: '↑ ↓',   description: $tStore('accessibility.keyboard.arrows') },
    ]}
    screenReaderTitle={$tStore('accessibility.screenReader.title')}
    screenReaderItems={screenReaderItems}
  />

  <!-- ── Relacionados ───────────────────────────────────────────── -->
  <DocsRelated componentSlug="markdown"
    items={[
      { name: $tStore('related.items.codeBlock.name'), description: toPlainText($tStore('related.items.codeBlock.description')), path: '?path=/docs/components-display-codeblock--docs' },
      { name: $tStore('related.items.editor.name'),    description: toPlainText($tStore('related.items.editor.description')),    path: '?path=/docs/components-form-editor--docs' },
      { name: $tStore('related.items.table.name'),     description: toPlainText($tStore('related.items.table.description')),     path: '?path=/docs/components-tables-table--docs' },
      { name: $tStore('related.items.skeleton.name'),  description: toPlainText($tStore('related.items.skeleton.description')),  path: '?path=/docs/components-feedback-skeleton--docs' },
    ]}
  />

  <!-- ── Notas ──────────────────────────────────────────────────── -->
  <DocsNotes
    componentSlug="markdown"
    items={[1, 2, 3, 4].map(i => ({ title: '', content: $tStore(`notes.item${i}`) }))}
  />

  <!-- ── Analytics ──────────────────────────────────────────────── -->
  <DocsAnalytics
    cols={{
      event: $tStore('analytics.table.event'),
      trigger: $tStore('analytics.table.trigger'),
      payload: $tStore('analytics.table.payload'),
    }}
    items={['pageView', 'sectionViewed', 'demoClick'].map(k => ({
      event: $tStore(`analytics.table.${k}`),
      trigger: toPlainText($tStore(`analytics.table.${k}Trigger`)),
      payload: $tStore(`analytics.table.${k}Payload`),
    }))}
  />

  <!-- ── Testes ─────────────────────────────────────────────────── -->
  <DocsTestes
    functional={{
      title: $tStore('testes.functional.title'),
      description: $tStore('testes.functional.description'),
      cols: {
        action: $tNavStore('common.userAction'),
        result: $tNavStore('common.expectedResult'),
        priority: $tNavStore('common.priority'),
      },
      items: [1, 2, 3, 4, 5, 6].map(i => ({
        action: toPlainText($tStore(`testes.functional.item${i}.action`)),
        result: toPlainText($tStore(`testes.functional.item${i}.result`)),
        priority: localPriority($tStore(`testes.functional.item${i}.priority`), $tNavStore),
      })),
    }}
    accessibility={{
      title: $tStore('testes.accessibility.title'),
      description: $tStore('testes.accessibility.description'),
      cols: {
        criterion: $tNavStore('common.criterion'),
        level: 'WCAG',
        how: $tNavStore('common.howToVerify'),
      },
      items: [1, 2, 3, 4, 5].map(i => ({
        criterion: toPlainText($tStore(`testes.accessibility.item${i}`)),
        level: 'AA',
        how: '—',
      })),
    }}
    visual={{
      title: $tStore('testes.visual.title'),
      description: $tStore('testes.visual.description'),
      cols: {
        story: $tNavStore('common.storyState'),
        priority: $tNavStore('common.priority'),
      },
      items: [1, 2, 3, 4, 5].map(i => ({
        story: toPlainText($tStore(`testes.visual.item${i}.story`)),
        priority: localPriority($tStore(`testes.visual.item${i}.priority`), $tNavStore),
      })),
    }}
  />
</DocsPageLayout>
