// design-system-vue/src/components/docs/ScrollAreaDocs.vue
<script setup lang="ts">
import { computed, watch, ref } from 'vue';
import { useTranslation } from '@/lib/i18n';
import { useSeoEffect } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { useActiveSection } from '@/lib/use-active-section';
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area';
import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.vue';
import uiTranslations from '@/i18n/ui.json';
import scrollAreaTranslations from '@shared/content/scroll-area/translations.json';

import DocsHeader        from '@/components/docs/shared/sections/DocsHeader.vue';
import DocsDemonstration from '@/components/docs/shared/sections/DocsDemonstration.vue';
import DocsAnatomy       from '@/components/docs/shared/sections/DocsAnatomy.vue';
import DocsWhenToUse     from '@/components/docs/shared/sections/DocsWhenToUse.vue';
import DocsDoDont        from '@/components/docs/shared/sections/DocsDoDont.vue';
import DocsImport        from '@/components/docs/shared/sections/DocsImport.vue';
import DocsVariants      from '@/components/docs/shared/sections/DocsVariants.vue';
import DocsStates        from '@/components/docs/shared/sections/DocsStates.vue';
import DocsProps         from '@/components/docs/shared/sections/DocsProps.vue';
import DocsTokens        from '@/components/docs/shared/sections/DocsTokens.vue';
import DocsAccessibility from '@/components/docs/shared/sections/DocsAccessibility.vue';
import DocsRelated       from '@/components/docs/shared/sections/DocsRelated.vue';
import DocsNotes         from '@/components/docs/shared/sections/DocsNotes.vue';
import DocsAnalytics     from '@/components/docs/shared/sections/DocsAnalytics.vue';
import DocsTestes        from '@/components/docs/shared/sections/DocsTestes.vue';

// ─── i18n ─────────────────────────────────────────────────────────────────────

const { t: tNav } = useTranslation(uiTranslations);
const { t: tContent, locale } = useTranslation(scrollAreaTranslations);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '');
}

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function localPriority(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

// ─── SEO & GEO ────────────────────────────────────────────────────────────────

useSeoEffect(computed(() => ({
  title: tContent('seo.title'),
  description: tContent('seo.description'),
  locale: locale.value as 'pt-BR' | 'en' | 'es',
  componentSlug: 'scroll-area',
  aiSummary: tContent('seo.aiSummary'),
  aiEntities: tContent('seo.aiEntities'),
  aiIntent: tContent('seo.aiIntent') as 'informational' | 'navigational',
  breadcrumb: [
    { name: 'Components', item: '/components' },
    { name: tContent('category'), item: '/components/layout' },
    { name: tContent('title') },
  ],
})));

// ─── Analytics — page view ────────────────────────────────────────────────────

watch(locale, (newLocale) => {
  track('docs_page_view', {
    component_name: 'scroll-area',
    locale: newLocale as 'pt-BR' | 'en' | 'es',
    page_title: `${tContent('title')} · Design System`,
  });
}, { immediate: true });

// ─── Analytics — section view ─────────────────────────────────────────────────

// ─── Navigation groups ────────────────────────────────────────────────────────

const navGroups = computed(() => [
  {
    label: tNav('nav.overview'),
    sections: [
      { id: 'demonstracao', label: tNav('nav.demonstration') },
      { id: 'anatomia',     label: tNav('nav.anatomy')      },
      { id: 'quando-usar',  label: tNav('nav.usage')        },
      { id: 'do-dont',      label: tNav('nav.doDont')       },
    ],
  },
  {
    label: tNav('nav.techRef'),
    sections: [
      { id: 'importacao',   label: tNav('nav.import')   },
      { id: 'variantes',    label: tNav('nav.variants') },
      { id: 'estados',      label: tNav('nav.states')   },
      { id: 'propriedades', label: tNav('nav.props')    },
      { id: 'tokens',       label: tNav('nav.tokens')   },
    ],
  },
  {
    label: tNav('nav.context'),
    sections: [
      { id: 'acessibilidade', label: tNav('nav.accessibility') },
      { id: 'relacionados',   label: tNav('nav.related')       },
      { id: 'notas',          label: tNav('nav.notes')         },
    ],
  },
  {
    label: tNav('nav.quality'),
    sections: [
      { id: 'analytics', label: tNav('nav.analytics') },
      { id: 'testes',    label: tNav('nav.testes')    },
    ],
  },
]);

const allSectionIds = computed(() => navGroups.value.flatMap((g) => g.sections.map((s) => s.id)));



const { activeId: activeSection } = useActiveSection(allSectionIds, (id) => {
  track('docs_section_viewed', {
    section_id: id,
    component_name: 'scroll-area',
    locale: locale.value,
  });
});
// ─── Demo data ────────────────────────────────────────────────────────────────

const verticalTags = Array.from({ length: 30 }, (_, i) => `Tag ${i + 1}`);
const horizontalCards = Array.from({ length: 12 }, (_, i) => ({ id: i + 1, title: `Card ${i + 1}` }));
const matrixCols = Array.from({ length: 10 }, (_, i) => `C${i + 1}`);
const matrixRows = Array.from({ length: 12 }, (_, i) => `R${i + 1}`);

// ─── Code strings ─────────────────────────────────────────────────────────────

const codeImportBasic = `import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";`;

const codeVertical = `<div class="h-[300px] w-[280px] overflow-hidden rounded-md border">
  <ScrollArea class="h-full w-full">
    <div class="p-4">
      <div v-for="tag in tags" :key="tag" class="text-sm">{{ tag }}</div>
    </div>
  </ScrollArea>
</div>`;

const codeHorizontal = `<div class="w-[500px] h-[180px] overflow-hidden rounded-md border">
  <ScrollArea class="h-full w-full whitespace-nowrap">
    <div class="flex w-max gap-4 p-4">
      <figure v-for="card in cards" :key="card.id" class="shrink-0 w-[160px] rounded-md border p-4">
        {{ card.title }}
      </figure>
    </div>
    <ScrollBar orientation="horizontal" />
  </ScrollArea>
</div>`;

const codeBoth = `<div class="w-[500px] h-[280px] overflow-hidden rounded-md border">
  <ScrollArea class="h-full w-full">
    <table class="border-collapse">
      <!-- linhas/colunas que excedem o viewport -->
    </table>
    <ScrollBar orientation="horizontal" />
  </ScrollArea>
</div>`;

const codeCustomizationTokens = `/* Espessura customizada da scrollbar */
[data-slot="scroll-area-scrollbar"] {
  --scrollbar-size: 8px;
}
[data-slot="scroll-area-scrollbar"][data-orientation="vertical"] {
  width: var(--scrollbar-size);
}
[data-slot="scroll-area-scrollbar"][data-orientation="horizontal"] {
  height: var(--scrollbar-size);
}`;

const interfaceCode = `// ScrollArea — props principais (reka-ui ScrollAreaRoot)
interface ScrollAreaProps {
  type?: 'auto' | 'always' | 'scroll' | 'hover'; // default 'hover'
  scrollHideDelay?: number; // default 600
  dir?: 'ltr' | 'rtl';
  class?: string;
}

// ScrollBar
interface ScrollBarProps {
  orientation?: 'vertical' | 'horizontal'; // default 'vertical'
  class?: string;
}`;

// ─── Computed data ────────────────────────────────────────────────────────────

const anatomyItems = computed(() => [
  tContent('anatomy.item1'),
  tContent('anatomy.item2'),
  tContent('anatomy.item3'),
  tContent('anatomy.item4'),
  tContent('anatomy.item5'),
]);

const variantItems = computed(() => [
  { name: tContent('variants.items.vertical'),   description: stripHtml(tContent('variants.styles.vertical')),   code: codeVertical   },
  { name: tContent('variants.items.horizontal'), description: stripHtml(tContent('variants.styles.horizontal')), code: codeHorizontal },
  { name: tContent('variants.items.both'),       description: stripHtml(tContent('variants.styles.both')),       code: codeBoth       },
]);

const stateItems = computed(() => [
  { label: tContent('states.items.idle'),      trigger: '—',                          behavior: stripHtml(tContent('states.descriptions.idle'))      },
  { label: tContent('states.items.scrolling'), trigger: 'scroll',                     behavior: stripHtml(tContent('states.descriptions.scrolling')) },
  { label: tContent('states.items.hover'),     trigger: 'mouseover',                  behavior: stripHtml(tContent('states.descriptions.hover'))     },
  { label: tContent('states.items.focus'),     trigger: 'Tab',                        behavior: stripHtml(tContent('states.descriptions.focus'))     },
]);

const propCols = computed(() => ({
  prop: tContent('props.table.prop'),
  type: tContent('props.table.type'),
  default: tContent('props.table.default'),
  required: tContent('props.table.required'),
  description: tContent('props.table.description'),
}));

const scrollAreaPropItems = computed(() => [
  { name: 'type',            type: tContent('props.table.type_prop.type'),        defaultValue: tContent('props.table.type_prop.default'),        required: tContent('props.table.type_prop.required'),        description: stripHtml(tContent('props.table.type_prop.description'))        },
  { name: 'scrollHideDelay', type: tContent('props.table.scrollHideDelay.type'),  defaultValue: tContent('props.table.scrollHideDelay.default'),  required: tContent('props.table.scrollHideDelay.required'),  description: stripHtml(tContent('props.table.scrollHideDelay.description'))  },
  { name: 'class',           type: tContent('props.table.className.type'),        defaultValue: tContent('props.table.className.default'),        required: tContent('props.table.className.required'),        description: stripHtml(tContent('props.table.className.description'))        },
  { name: 'slot:default',    type: tContent('props.table.children.type'),         defaultValue: tContent('props.table.children.default'),         required: tContent('props.table.children.required'),         description: stripHtml(tContent('props.table.children.description'))         },
]);

const scrollBarPropItems = computed(() => [
  { name: 'orientation', type: tContent('props.table.orientation.type'), defaultValue: tContent('props.table.orientation.default'), required: tContent('props.table.orientation.required'), description: stripHtml(tContent('props.table.orientation.description')) },
  { name: 'class',       type: tContent('props.table.className.type'),   defaultValue: tContent('props.table.className.default'),   required: tContent('props.table.className.required'),   description: stripHtml(tContent('props.table.className.description'))   },
]);

const tokenRows = computed(() => [
  { token: '--border',                 value: tContent('tokens.table.border.class'),     description: tContent('tokens.table.border.part')     },
  { token: '--ring',                   value: tContent('tokens.table.ring.class'),       description: tContent('tokens.table.ring.part')       },
  { token: '--background',             value: tContent('tokens.table.background.class'), description: tContent('tokens.table.background.part') },
  { token: '--foreground',             value: tContent('tokens.table.foreground.class'), description: tContent('tokens.table.foreground.part') },
  { token: '--muted',                  value: tContent('tokens.table.muted.class'),      description: tContent('tokens.table.muted.part')      },
  { token: '--ring-offset-background', value: tContent('tokens.table.ringOffset.class'), description: tContent('tokens.table.ringOffset.part') },
]);

const accessibilityItems = computed(() => [
  tContent('accessibility.items.item1'),
  tContent('accessibility.items.item2'),
  tContent('accessibility.items.item3'),
  tContent('accessibility.items.item4'),
  tContent('accessibility.items.item5'),
  tContent('accessibility.items.item6'),
]);

const keyboardItems = computed(() => [
  { key: 'Tab',        description: tContent('accessibility.keyboard.tab')        },
  { key: 'ArrowDown',  description: tContent('accessibility.keyboard.arrowDown')  },
  { key: 'ArrowUp',    description: tContent('accessibility.keyboard.arrowUp')    },
  { key: 'ArrowRight', description: tContent('accessibility.keyboard.arrowRight') },
  { key: 'ArrowLeft',  description: tContent('accessibility.keyboard.arrowLeft')  },
  { key: 'PageDown',   description: tContent('accessibility.keyboard.pageDown')   },
  { key: 'PageUp',     description: tContent('accessibility.keyboard.pageUp')     },
  { key: 'Home',       description: tContent('accessibility.keyboard.home')       },
  { key: 'End',        description: tContent('accessibility.keyboard.end')        },
]);

const relatedItems = computed(() => [
  { name: 'Resizable', description: tContent('related.items.resizable.description'), path: '?path=/docs/ui-resizable--docs' },
  { name: 'Sheet',     description: tContent('related.items.sheet.description'),     path: '?path=/docs/ui-sheet--docs'     },
  { name: 'Dialog',    description: tContent('related.items.dialog.description'),    path: '?path=/docs/ui-dialog--docs'    },
  { name: 'Command',   description: tContent('related.items.command.description'),   path: '?path=/docs/ui-command--docs'   },
]);

const noteItems = computed(() => [
  { title: '', content: tContent('notes.item1') },
  { title: '', content: tContent('notes.item2') },
  { title: '', content: tContent('notes.item3') },
  { title: '', content: tContent('notes.item4') },
]);

const analyticsItems = computed(() => [
  { event: 'content_scroll', trigger: tContent('analytics.table.content_scroll.trigger'), payload: tContent('analytics.table.content_scroll.payload') },
]);

const a11yCritCols = computed(() => ({
  criterion: tNav('common.criterion'),
  level: 'WCAG',
  how: tNav('common.howToVerify'),
}));

const functionalTestItems = computed(() => [
  { action: tContent('testes.functional.item1.action'), result: tContent('testes.functional.item1.result'), priority: localPriority(tContent('testes.functional.item1.priority')) },
  { action: tContent('testes.functional.item2.action'), result: tContent('testes.functional.item2.result'), priority: localPriority(tContent('testes.functional.item2.priority')) },
  { action: tContent('testes.functional.item3.action'), result: tContent('testes.functional.item3.result'), priority: localPriority(tContent('testes.functional.item3.priority')) },
  { action: tContent('testes.functional.item4.action'), result: tContent('testes.functional.item4.result'), priority: localPriority(tContent('testes.functional.item4.priority')) },
]);

const a11yTestItems = computed(() => [
  { criterion: tContent('testes.accessibility.item1'), level: '4.1.2',  how: tContent('testes.accessibility.description') },
  { criterion: tContent('testes.accessibility.item2'), level: '1.4.11', how: tContent('testes.accessibility.description') },
  { criterion: tContent('testes.accessibility.item3'), level: '2.4.7',  how: tContent('testes.accessibility.description') },
  { criterion: tContent('testes.accessibility.item4'), level: '2.1.1',  how: tContent('testes.accessibility.description') },
  { criterion: tContent('testes.accessibility.item5'), level: '1.4.10', how: tContent('testes.accessibility.description') },
]);

const visualTestItems = computed(() => [
  { story: tContent('testes.visual.item1.story'), priority: localPriority(tContent('testes.visual.item1.priority')) },
  { story: tContent('testes.visual.item2.story'), priority: localPriority(tContent('testes.visual.item2.priority')) },
  { story: tContent('testes.visual.item3.story'), priority: localPriority(tContent('testes.visual.item3.priority')) },
  { story: tContent('testes.visual.item4.story'), priority: localPriority(tContent('testes.visual.item4.priority')) },
]);
</script>

<template>
  <DocsPageLayout :nav-groups="navGroups" :active-section="activeSection">
    <template #header>
      <DocsHeader
        :title="tContent('title')"
        :description="tContent('description')"
        :category="tContent('category')"
        :type="tContent('type')"
        install-note="npx shadcn-vue@latest add scroll-area"
      />
    </template>

    <!-- ── Demonstração ───────────────────────────────────────────── -->
    <DocsDemonstration :title="tContent('demonstration.title')">
      <div class="w-full space-y-4">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <div>
            <p class="mb-2 text-xs font-medium text-muted-foreground">
              {{ tContent('demonstration.labels.verticalTitle') }}
            </p>
            <div class="h-[260px] w-full overflow-hidden rounded-md border">
              <ScrollArea class="h-full w-full">
                <div class="p-4 space-y-2">
                  <div
                    v-for="tag in verticalTags"
                    :key="tag"
                    class="text-sm rounded-sm border px-2 py-1.5"
                  >
                    {{ tag }}
                  </div>
                </div>
              </ScrollArea>
            </div>
          </div>
          <div>
            <p class="mb-2 text-xs font-medium text-muted-foreground">
              {{ tContent('demonstration.labels.horizontalTitle') }}
            </p>
            <div class="h-[180px] w-full overflow-hidden rounded-md border">
              <ScrollArea class="h-full w-full whitespace-nowrap">
                <div class="flex w-max gap-3 p-4">
                  <figure
                    v-for="card in horizontalCards"
                    :key="card.id"
                    class="shrink-0 w-[140px] rounded-md border bg-muted p-3"
                  >
                    <div class="text-sm font-medium">{{ card.title }}</div>
                  </figure>
                </div>
                <ScrollBar orientation="horizontal" />
              </ScrollArea>
            </div>
          </div>
        </div>
        <div>
          <p class="mb-2 text-xs font-medium text-muted-foreground">
            {{ tContent('demonstration.labels.bothTitle') }}
          </p>
          <div class="h-[260px] w-full overflow-hidden rounded-md border">
            <ScrollArea class="h-full w-full">
              <table class="border-collapse text-sm">
                <thead>
                  <tr>
                    <th class="sticky top-0 z-10 bg-background border px-3 py-2 text-left">#</th>
                    <th
                      v-for="col in matrixCols"
                      :key="col"
                      class="sticky top-0 z-10 bg-background border px-3 py-2 text-left whitespace-nowrap"
                    >
                      {{ col }}
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="row in matrixRows" :key="row">
                    <th class="border px-3 py-2 text-left whitespace-nowrap bg-muted">{{ row }}</th>
                    <td
                      v-for="col in matrixCols"
                      :key="col"
                      class="border px-3 py-2 whitespace-nowrap"
                    >
                      {{ row }}-{{ col }}
                    </td>
                  </tr>
                </tbody>
              </table>
              <ScrollBar orientation="horizontal" />
            </ScrollArea>
          </div>
        </div>
      </div>
    </DocsDemonstration>

    <!-- ── Anatomia ───────────────────────────────────────────────── -->
    <DocsAnatomy
      :title="tContent('anatomy.title')"
      :items="anatomyItems"
      :structure-label="tContent('anatomy.structureLabel')"
      :structure-code="tContent('anatomy.structureCode')"
    />

    <!-- ── Quando Usar ────────────────────────────────────────────── -->
    <DocsWhenToUse
      :title="tContent('usage.title')"
      :guidelines="{
        title: tContent('usage.guidelines.title'),
        items: [
          tContent('usage.guidelines.item1'),
          tContent('usage.guidelines.item2'),
          tContent('usage.guidelines.item3'),
          tContent('usage.guidelines.item4'),
        ],
      }"
      :scenarios="{
        title: tContent('usage.scenarios.title'),
        cols: {
          scenario: tContent('usage.scenarios.cols.scenario'),
          use: tContent('usage.scenarios.cols.use'),
          alternative: tContent('usage.scenarios.cols.alternative'),
        },
        items: [
          { s: tContent('usage.scenarios.item1.s'), u: tContent('usage.scenarios.item1.u'), a: tContent('usage.scenarios.item1.a') },
          { s: tContent('usage.scenarios.item2.s'), u: tContent('usage.scenarios.item2.u'), a: tContent('usage.scenarios.item2.a') },
          { s: tContent('usage.scenarios.item3.s'), u: tContent('usage.scenarios.item3.u'), a: tContent('usage.scenarios.item3.a') },
          { s: tContent('usage.scenarios.item4.s'), u: tContent('usage.scenarios.item4.u'), a: tContent('usage.scenarios.item4.a') },
          { s: tContent('usage.scenarios.item5.s'), u: tContent('usage.scenarios.item5.u'), a: tContent('usage.scenarios.item5.a') },
        ],
      }"
      :ux-writing="{
        title: tContent('usage.uxWriting.title'),
        cols: {
          element: tContent('usage.uxWriting.table.element'),
          rules:   tContent('usage.uxWriting.table.rules'),
          do:      tContent('usage.uxWriting.table.correct'),
          dont:    tContent('usage.uxWriting.table.avoid'),
        },
        items: [
          { element: tContent('usage.uxWriting.table.container.name'),   rules: tContent('usage.uxWriting.table.container.format'),   do: tContent('usage.uxWriting.table.container.good'),   dont: tContent('usage.uxWriting.table.container.bad')   },
          { element: tContent('usage.uxWriting.table.scrollArea.name'),  rules: tContent('usage.uxWriting.table.scrollArea.format'),  do: tContent('usage.uxWriting.table.scrollArea.good'),  dont: tContent('usage.uxWriting.table.scrollArea.bad')  },
          { element: tContent('usage.uxWriting.table.orientation.name'), rules: tContent('usage.uxWriting.table.orientation.format'), do: tContent('usage.uxWriting.table.orientation.good'), dont: tContent('usage.uxWriting.table.orientation.bad') },
        ],
      }"
      :do="{
        title: tContent('usage.do.title'),
        items: [
          tContent('usage.do.item1'),
          tContent('usage.do.item2'),
          tContent('usage.do.item3'),
          tContent('usage.do.item4'),
        ],
      }"
      :dont="{
        title: tContent('usage.dont.title'),
        items: [
          tContent('usage.dont.item1'),
          tContent('usage.dont.item2'),
          tContent('usage.dont.item3'),
          tContent('usage.dont.item4'),
        ],
      }"
    />

    <!-- ── Do & Don't ─────────────────────────────────────────────── -->
    <DocsDoDont
      :title="tContent('doDont.title')"
      :pairs="[
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair1.do'), dontCaption: tContent('doDont.pair1.dont') },
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair2.do'), dontCaption: tContent('doDont.pair2.dont') },
      ]"
    >
      <template #do-preview-0>
        <div class="h-[180px] w-full overflow-hidden rounded-md border">
          <ScrollArea class="h-full w-full">
            <div class="p-3 space-y-1.5">
              <div v-for="i in 18" :key="i" class="text-xs rounded-sm border px-2 py-1">Item {{ i }}</div>
            </div>
          </ScrollArea>
        </div>
      </template>
      <template #dont-preview-0>
        <div class="w-full rounded-md border p-3 space-y-1.5">
          <div v-for="i in 6" :key="i" class="text-xs rounded-sm border px-2 py-1">Item {{ i }}</div>
          <p class="text-[10px] text-muted-foreground">Sem altura — conteúdo expande</p>
        </div>
      </template>
      <template #do-preview-1>
        <div class="h-[180px] w-full overflow-hidden rounded-md border">
          <ScrollArea class="h-full w-full">
            <div class="p-3 space-y-1.5">
              <div v-for="i in 14" :key="i" class="text-xs rounded-sm border px-2 py-1">Item {{ i }}</div>
            </div>
          </ScrollArea>
        </div>
      </template>
      <template #dont-preview-1>
        <div class="h-[180px] w-full overflow-hidden rounded-md border">
          <ScrollArea class="h-full w-full">
            <ScrollArea class="h-[100px] w-full">
              <div class="p-3 space-y-1.5">
                <div v-for="i in 10" :key="i" class="text-xs rounded-sm border px-2 py-1">Item {{ i }}</div>
              </div>
            </ScrollArea>
          </ScrollArea>
        </div>
      </template>
    </DocsDoDont>

    <!-- ── Importação ─────────────────────────────────────────────── -->
    <DocsImport
      :title="tContent('import.title')"
      :code="codeImportBasic"
    />

    <!-- ── Variantes ──────────────────────────────────────────────── -->
    <DocsVariants :title="tContent('variants.title')" :items="variantItems">
      <template #variant-preview-0>
        <div class="h-[200px] w-[260px] overflow-hidden rounded-md border">
          <ScrollArea class="h-full w-full">
            <div class="p-3 space-y-1.5">
              <div v-for="i in 20" :key="i" class="text-xs rounded-sm border px-2 py-1">
                {{ tContent('demonstration.labels.tag') }} {{ i }}
              </div>
            </div>
          </ScrollArea>
        </div>
      </template>
      <template #variant-preview-1>
        <div class="h-[140px] w-[420px] overflow-hidden rounded-md border">
          <ScrollArea class="h-full w-full whitespace-nowrap">
            <div class="flex w-max gap-3 p-3">
              <figure v-for="i in 10" :key="i" class="shrink-0 w-[120px] rounded-md border bg-muted p-3 text-xs">
                Card {{ i }}
              </figure>
            </div>
            <ScrollBar orientation="horizontal" />
          </ScrollArea>
        </div>
      </template>
      <template #variant-preview-2>
        <div class="h-[200px] w-[420px] overflow-hidden rounded-md border">
          <ScrollArea class="h-full w-full">
            <table class="border-collapse text-xs">
              <tbody>
                <tr v-for="r in 12" :key="r">
                  <td v-for="c in 10" :key="c" class="border px-3 py-1.5 whitespace-nowrap">
                    R{{ r }}-C{{ c }}
                  </td>
                </tr>
              </tbody>
            </table>
            <ScrollBar orientation="horizontal" />
          </ScrollArea>
        </div>
      </template>
    </DocsVariants>

    <!-- ── Estados ──────────────────────────────────────────────── -->
    <DocsStates
      :title="tContent('states.title')"
      :cols="{
        state: tContent('states.title'),
        trigger: 'Trigger',
        behavior: tContent('props.table.description'),
      }"
      :items="stateItems"
    />

    <!-- ── Propriedades ───────────────────────────────────────────── -->
    <DocsProps
      :title="tContent('props.title')"
      :tables="[
        { title: 'ScrollArea', cols: propCols, items: scrollAreaPropItems },
        { title: 'ScrollBar',  cols: propCols, items: scrollBarPropItems  },
      ]"
      :interface-code="interfaceCode"
      :extensibility-title="tContent('props.extensibilityTitle')"
      :extensibility-notes="tContent('props.extensibilityCode')"
    />

    <!-- ── Tokens ─────────────────────────────────────────────────── -->
    <DocsTokens
      :title="tContent('tokens.title')"
      :cols="{
        token: tContent('tokens.table.token'),
        value: tContent('tokens.table.class'),
        description: tContent('tokens.table.part'),
      }"
      :items="tokenRows"
      :customization-title="tContent('tokens.customizationTitle')"
      :customization-code="codeCustomizationTokens"
    />

    <!-- ── Acessibilidade ─────────────────────────────────────────── -->
    <DocsAccessibility
      :title="tContent('accessibility.title')"
      :summary="tContent('accessibility.summary')"
      :items="accessibilityItems"
      :keyboard-title="tContent('accessibility.keyboard.title')"
      :keyboard-items="keyboardItems"
    />

    <!-- ── Relacionados ───────────────────────────────────────────── -->
    <DocsRelated :title="tContent('related.title')" :items="relatedItems" />

    <!-- ── Notas ──────────────────────────────────────────────────── -->
    <DocsNotes :title="tContent('notes.title')" :items="noteItems" />

    <!-- ── Analytics ─────────────────────────────────────────────── -->
    <DocsAnalytics
      :title="tContent('analytics.title')"
      :cols="{
        event: tContent('analytics.table.event'),
        trigger: tContent('analytics.table.trigger'),
        payload: tContent('analytics.table.payload'),
      }"
      :items="analyticsItems"
    />

    <!-- ── Testes ─────────────────────────────────────────────────── -->
    <DocsTestes
      :title="tContent('testes.title')"
      :functional="{
        title: tContent('testes.functional.title'),
        cols: { action: tNav('common.userAction'), result: tNav('common.expectedResult'), priority: tNav('common.priority') },
        items: functionalTestItems,
      }"
      :accessibility="{
        title: tContent('testes.accessibility.title'),
        cols: a11yCritCols,
        items: a11yTestItems,
      }"
      :visual="{
        title: tContent('testes.visual.title'),
        cols: { story: tNav('common.storyState'), priority: tNav('common.priority') },
        items: visualTestItems,
      }"
    />
  </DocsPageLayout>
</template>

// nortear-design-system-svelte/src/components/docs/ScrollAreaDocs.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { ScrollArea } from '@/components/ui/scroll-area';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import { createActiveSection } from '@/lib/use-active-section.svelte';
  import DOMPurify from 'dompurify';
  import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader, DocsDemonstration, DocsAnatomy, DocsWhenToUse, DocsDoDont,
    DocsImport, DocsVariants, DocsStates, DocsProps, DocsTokens,
    DocsAccessibility, DocsRelated, DocsNotes, DocsAnalytics, DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import scrollAreaTranslations from '@shared/content/scroll-area/translations.json';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(scrollAreaTranslations);

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria.
  const screenReaderItems = $derived(
    Object.values(
      (scrollAreaTranslations as unknown as Record<
        string,
        { accessibility?: { screenReader?: Record<string, string> } }
      >)[$locale]?.accessibility?.screenReader ?? {},
    ),
  );

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'scroll-area',
      aiSummary: t('seo.aiSummary'),
      aiEntities: t('seo.aiEntities'),
      breadcrumb: [
        { name: 'Components', item: '/components' },
        { name: t('category'), item: '/components/layout' },
        { name: t('title') },
      ],
    });
    track('docs_page_view', {
      component_name: 'scroll-area',
      locale: l,
      page_title: `${t('title')} · Design System`,
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────


  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')   },
        { id: 'variantes',    label: tNav('nav.variants') },
        { id: 'estados',      label: tNav('nav.states')   },
        { id: 'propriedades', label: tNav('nav.props')    },
        { id: 'tokens',       label: tNav('nav.tokens')   },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  const sectionIds = untrack(() => NAV_GROUPS.flatMap(g => g.sections.map(s => s.id)));
  const section = createActiveSection(sectionIds, (id) => {
    track('docs_section_viewed', { section_id: id, component_name: 'scroll-area', locale: $locale });
  });
  $effect(() => section.attach());

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  function stripHtml(s: string) {
    return s.replace(/<[^>]*>/g, '');
  }

  const priorityKeyMap: Record<string, string> = { high: 'common.high', medium: 'common.medium', low: 'common.low' };

  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  // ─── Demo data ───────────────────────────────────────────────────────────────

  const VERTICAL_TAGS = Array.from({ length: 30 }, (_, i) => i + 1);
  const HORIZONTAL_CARDS = Array.from({ length: 10 }, (_, i) => i + 1);
  const MATRIX_ROWS = Array.from({ length: 12 }, (_, i) => i + 1);
  const MATRIX_COLS = Array.from({ length: 12 }, (_, i) => i + 1);

  // ─── Code strings ────────────────────────────────────────────────────────────

  const codeImportBasic = `import { ScrollArea } from "@/components/ui/scroll-area";`;

  const codeVertical = `<div style="height: 300px">
  <ScrollArea orientation="vertical" class="nds-w-full nds-rounded-md nds-border-default" style="height: 100%">
    <div class="nds-stack nds-p-4" data-spacing="sm">
      {#each tags as tag}
        <div class="nds-text-body">Tag {tag}</div>
      {/each}
    </div>
  </ScrollArea>
</div>`;

  const codeHorizontal = `<div style="width: 500px">
  <ScrollArea orientation="horizontal" class="nds-w-full nds-whitespace-nowrap nds-rounded-md nds-border-default" style="height: 100%">
    <div class="nds-cluster nds-p-4" data-spacing="md" style="width: max-content">
      {#each items as item}
        <Card {...item} />
      {/each}
    </div>
  </ScrollArea>
</div>`;

  const codeBoth = `<div style="height: 300px; width: 500px">
  <ScrollArea orientation="both" class="nds-w-full nds-rounded-md nds-border-default" style="height: 100%">
    <table style="width: max-content"><!-- conteúdo amplo --></table>
  </ScrollArea>
</div>`;

  const interfaceCode = `// bits-ui ScrollArea (Svelte)
import type { ScrollArea as ScrollAreaPrimitive } from "bits-ui";

interface ScrollAreaRootProps {
  type?: "auto" | "always" | "scroll" | "hover"; // default "hover"
  scrollHideDelay?: number;                      // default 600
  orientation?: "vertical" | "horizontal" | "both"; // wrapper local
  scrollbarXClasses?: string;
  scrollbarYClasses?: string;
  class?: string;
  children: Snippet;
}

// O wrapper local emite ScrollBar(s) automaticamente conforme orientation.
// Componentes internos (Viewport, Scrollbar, Thumb, Corner) são gerenciados pela lib.`;
</script>

<DocsPageLayout navGroups={NAV_GROUPS} activeSection={section.value}>
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
    />
  {/snippet}

  <!-- ── Demonstração ───────────────────────────────────────────── -->
  <DocsDemonstration title={$tStore('demonstration.title')}>
    <div class="nds-stack nds-w-full" data-spacing="xl">
      <!-- Demo 1: Vertical -->
      <div class="nds-stack" data-spacing="sm">
        <p class="nds-text-caption nds-font-medium nds-text-muted-foreground">
          {$tStore('demonstration.labels.verticalTitle')}
        </p>
        <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 300px; width: 100%; max-width: 360px;">
          <ScrollArea orientation="vertical" class="nds-w-full" style="height: 100%">
            <div class="nds-stack nds-p-4" data-spacing="sm">
              {#each VERTICAL_TAGS as n (n)}
                <div class="nds-text-body nds-border-b nds-last-border-0" style="padding-bottom: 0.5rem">
                  {$tStore('demonstration.labels.tag')} {n}
                </div>
              {/each}
            </div>
          </ScrollArea>
        </div>
      </div>

      <!-- Demo 2: Horizontal -->
      <div class="nds-stack" data-spacing="sm">
        <p class="nds-text-caption nds-font-medium nds-text-muted-foreground">
          {$tStore('demonstration.labels.horizontalTitle')}
        </p>
        <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 180px; width: 100%; max-width: 500px;">
          <ScrollArea orientation="horizontal" class="nds-w-full nds-whitespace-nowrap" style="height: 100%">
            <div class="nds-cluster nds-p-4" data-spacing="md" style="width: max-content">
              {#each HORIZONTAL_CARDS as n (n)}
                <div class="nds-cluster nds-rounded-md nds-bg-muted nds-text-body nds-shrink-0" data-align="center" data-justify="center" style="height: 120px; width: 140px">
                  Card {n}
                </div>
              {/each}
            </div>
          </ScrollArea>
        </div>
      </div>

      <!-- Demo 3: Both -->
      <div class="nds-stack" data-spacing="sm">
        <p class="nds-text-caption nds-font-medium nds-text-muted-foreground">
          {$tStore('demonstration.labels.bothTitle')}
        </p>
        <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 260px; width: 100%; max-width: 500px;">
          <ScrollArea orientation="both" class="nds-w-full" style="height: 100%">
            <table class="nds-border-collapse nds-text-caption" style="width: max-content">
              <tbody>
                {#each MATRIX_ROWS as r (r)}
                  <tr>
                    {#each MATRIX_COLS as c (c)}
                      <td class="nds-border-default nds-whitespace-nowrap" style="padding: 0.5rem 0.75rem">R{r}·C{c}</td>
                    {/each}
                  </tr>
                {/each}
              </tbody>
            </table>
          </ScrollArea>
        </div>
      </div>
    </div>
  </DocsDemonstration>

  <!-- ── Anatomia ───────────────────────────────────────────────── -->
  <DocsAnatomy
    title={$tStore('anatomy.title')}
    items={[
      $tStore('anatomy.item1'),
      $tStore('anatomy.item2'),
      $tStore('anatomy.item3'),
      $tStore('anatomy.item4'),
      $tStore('anatomy.item5'),
    ]}
    structureLabel={$tStore('anatomy.structureLabel')}
    structureCode={$tStore('anatomy.structureCode')}
  />

  <!-- ── Quando Usar ────────────────────────────────────────────── -->
  <DocsWhenToUse
    title={$tStore('usage.title')}
    guidelines={{
      title: $tStore('usage.guidelines.title'),
      items: [
        $tStore('usage.guidelines.item1'),
        $tStore('usage.guidelines.item2'),
        $tStore('usage.guidelines.item3'),
        $tStore('usage.guidelines.item4'),
      ],
    }}
    scenarios={{
      title: $tStore('usage.scenarios.title'),
      cols: {
        scenario: $tStore('usage.scenarios.cols.scenario'),
        use: $tStore('usage.scenarios.cols.use'),
        alternative: $tStore('usage.scenarios.cols.alternative'),
      },
      items: [
        { s: $tStore('usage.scenarios.item1.s'), u: $tStore('usage.scenarios.item1.u'), a: $tStore('usage.scenarios.item1.a') },
        { s: $tStore('usage.scenarios.item2.s'), u: $tStore('usage.scenarios.item2.u'), a: $tStore('usage.scenarios.item2.a') },
        { s: $tStore('usage.scenarios.item3.s'), u: $tStore('usage.scenarios.item3.u'), a: $tStore('usage.scenarios.item3.a') },
        { s: $tStore('usage.scenarios.item4.s'), u: $tStore('usage.scenarios.item4.u'), a: $tStore('usage.scenarios.item4.a') },
        { s: $tStore('usage.scenarios.item5.s'), u: $tStore('usage.scenarios.item5.u'), a: $tStore('usage.scenarios.item5.a') },
      ],
    }}
    uxWriting={{
      title: $tStore('usage.uxWriting.title'),
      cols: {
        element: $tStore('usage.uxWriting.table.element'),
        rules: $tStore('usage.uxWriting.table.rules'),
        do: $tStore('usage.uxWriting.table.correct'),
        dont: $tStore('usage.uxWriting.table.avoid'),
      },
      items: [
        { element: $tStore('usage.uxWriting.table.container.name'),  rules: stripHtml($tStore('usage.uxWriting.table.container.format')),  do: stripHtml($tStore('usage.uxWriting.table.container.good')),  dont: stripHtml($tStore('usage.uxWriting.table.container.bad')) },
        { element: $tStore('usage.uxWriting.table.scrollArea.name'), rules: stripHtml($tStore('usage.uxWriting.table.scrollArea.format')), do: stripHtml($tStore('usage.uxWriting.table.scrollArea.good')), dont: stripHtml($tStore('usage.uxWriting.table.scrollArea.bad')) },
        { element: $tStore('usage.uxWriting.table.orientation.name'),rules: $tStore('usage.uxWriting.table.orientation.format'),          do: $tStore('usage.uxWriting.table.orientation.good'),          dont: $tStore('usage.uxWriting.table.orientation.bad') },
      ],
    }}
    do={{
      title: $tStore('usage.do.title'),
      items: [
        $tStore('usage.do.item1'),
        $tStore('usage.do.item2'),
        $tStore('usage.do.item3'),
        $tStore('usage.do.item4'),
      ],
    }}
    dont={{
      title: $tStore('usage.dont.title'),
      items: [
        $tStore('usage.dont.item1'),
        $tStore('usage.dont.item2'),
        $tStore('usage.dont.item3'),
        $tStore('usage.dont.item4'),
      ],
    }}
  />

  <!-- ── Do & Don't ─────────────────────────────────────────────── -->
  <DocsDoDont
    title={$tStore('doDont.title')}
    pairs={[
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair1.do'),
        dontCaption: $tStore('doDont.pair1.dont'),
        doPreview: doPair1,
        dontPreview: dontPair1,
      },
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair2.do'),
        dontCaption: $tStore('doDont.pair2.dont'),
        doPreview: doPair2,
        dontPreview: dontPair2,
      },
    ]}
  />

  {#snippet doPair1()}
    <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 160px; width: 100%;">
      <ScrollArea orientation="vertical" class="nds-w-full" style="height: 100%">
        <div class="nds-stack nds-text-caption" data-spacing="sm" style="padding: 0.75rem">
          {#each Array.from({ length: 12 }, (_, i) => i + 1) as i (i)}
            <div>Item {i}</div>
          {/each}
        </div>
      </ScrollArea>
    </div>
  {/snippet}
  {#snippet dontPair1()}
    <div class="nds-w-full">
      <ScrollArea orientation="vertical" class="nds-w-full nds-rounded-md nds-border-default" style="height: 100%">
        <div class="nds-stack nds-text-caption" data-spacing="sm" style="padding: 0.75rem">
          {#each Array.from({ length: 5 }, (_, i) => i + 1) as i (i)}
            <div>Item {i}</div>
          {/each}
        </div>
      </ScrollArea>
    </div>
  {/snippet}
  {#snippet doPair2()}
    <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 160px; width: 100%;">
      <ScrollArea orientation="vertical" class="nds-w-full" style="height: 100%">
        <div class="nds-stack nds-text-caption" data-spacing="sm" style="padding: 0.75rem">
          {#each Array.from({ length: 14 }, (_, i) => i + 1) as i (i)}
            <div>Linha {i}</div>
          {/each}
        </div>
      </ScrollArea>
    </div>
  {/snippet}
  {#snippet dontPair2()}
    <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 160px; width: 100%;">
      <ScrollArea orientation="vertical" class="nds-w-full" style="height: 100%">
        <div style="height: 140px;">
          <ScrollArea orientation="vertical" class="nds-w-full" style="height: 100%">
            <div class="nds-stack nds-text-caption" data-spacing="sm" style="padding: 0.75rem">
              {#each Array.from({ length: 14 }, (_, i) => i + 1) as i (i)}
                <div>Linha {i}</div>
              {/each}
            </div>
          </ScrollArea>
        </div>
      </ScrollArea>
    </div>
  {/snippet}

  <!-- ── Importação ─────────────────────────────────────────────── -->
  <DocsImport title={$tStore('import.title')} code={codeImportBasic} />

  <!-- ── Variantes ──────────────────────────────────────────────── -->
  <DocsVariants
    title={$tStore('variants.title')}
    items={[
      { name: $tStore('variants.items.vertical'),   description: stripHtml($tStore('variants.styles.vertical')),   code: codeVertical,   preview: variantVertical   },
      { name: $tStore('variants.items.horizontal'), description: stripHtml($tStore('variants.styles.horizontal')), code: codeHorizontal, preview: variantHorizontal },
      { name: $tStore('variants.items.both'),       description: stripHtml($tStore('variants.styles.both')),       code: codeBoth,       preview: variantBoth       },
    ]}
  />

  {#snippet variantVertical()}
    <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 200px; width: 100%; max-width: 300px;">
      <ScrollArea orientation="vertical" class="nds-w-full" style="height: 100%">
        <div class="nds-stack nds-text-caption" data-spacing="sm" style="padding: 0.75rem">
          {#each VERTICAL_TAGS.slice(0, 20) as n (n)}
            <div class="nds-border-b nds-last-border-0" style="padding-bottom: 0.25rem">{$tStore('demonstration.labels.tag')} {n}</div>
          {/each}
        </div>
      </ScrollArea>
    </div>
  {/snippet}
  {#snippet variantHorizontal()}
    <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 140px; width: 100%; max-width: 420px;">
      <ScrollArea orientation="horizontal" class="nds-w-full nds-whitespace-nowrap" style="height: 100%">
        <div class="nds-cluster" data-spacing="sm" style="width: max-content; padding: 0.75rem">
          {#each HORIZONTAL_CARDS as n (n)}
            <div class="nds-cluster nds-rounded-md nds-bg-muted nds-text-caption nds-shrink-0" data-align="center" data-justify="center" style="height: 90px; width: 120px">
              Card {n}
            </div>
          {/each}
        </div>
      </ScrollArea>
    </div>
  {/snippet}
  {#snippet variantBoth()}
    <div class="nds-rounded-md nds-border-default nds-bg-background nds-overflow-hidden" style="height: 200px; width: 100%; max-width: 420px;">
      <ScrollArea orientation="both" class="nds-w-full" style="height: 100%">
        <table class="nds-border-collapse nds-text-caption" style="width: max-content">
          <tbody>
            {#each MATRIX_ROWS.slice(0, 10) as r (r)}
              <tr>
                {#each MATRIX_COLS.slice(0, 10) as c (c)}
                  <td class="nds-border-default nds-px-2 nds-py-1 nds-whitespace-nowrap">R{r}·C{c}</td>
                {/each}
              </tr>
            {/each}
          </tbody>
        </table>
      </ScrollArea>
    </div>
  {/snippet}

  <!-- ── Estados ────────────────────────────────────────────────── -->
  <DocsStates
    title={$tStore('states.title')}
    cols={{
      state: $tStore('states.cols.state'),
      trigger: $tStore('states.cols.trigger'),
      behavior: $tStore('states.cols.behavior'),
    }}
    items={[
      { label: $tStore('states.idle.label'),      trigger: $tStore('states.idle.trigger'),      behavior: stripHtml($tStore('states.idle.behavior')) },
      { label: $tStore('states.scrolling.label'), trigger: $tStore('states.scrolling.trigger'), behavior: stripHtml($tStore('states.scrolling.behavior')) },
      { label: $tStore('states.hover.label'),     trigger: $tStore('states.hover.trigger'),     behavior: stripHtml($tStore('states.hover.behavior')) },
      { label: $tStore('states.focus.label'),     trigger: $tStore('states.focus.trigger'),     behavior: stripHtml($tStore('states.focus.behavior')) },
    ]}
  />

  <!-- ── Propriedades ───────────────────────────────────────────── -->
  <DocsProps
    title={$tStore('props.title')}
    tables={[
      {
        cols: {
          prop: $tStore('props.table.prop'),
          type: $tStore('props.table.type'),
          default: $tStore('props.table.default'),
          required: $tStore('props.table.required'),
          description: $tStore('props.table.description'),
        },
        items: [
          { name: 'type',            type: $tStore('props.table.type_prop.type'),        defaultValue: $tStore('props.table.type_prop.default'),        required: $tStore('props.table.type_prop.required'),        description: DOMPurify.sanitize($tStore('props.table.type_prop.description'))        },
          { name: 'scrollHideDelay', type: $tStore('props.table.scrollHideDelay.type'),  defaultValue: $tStore('props.table.scrollHideDelay.default'),  required: $tStore('props.table.scrollHideDelay.required'),  description: DOMPurify.sanitize($tStore('props.table.scrollHideDelay.description'))  },
          { name: 'orientation',     type: '"vertical" | "horizontal" | "both"',         defaultValue: '"vertical"',                                    required: 'Não',                                            description: 'Direção do scroll suportada — controla quais ScrollBars o wrapper renderiza.' },
          { name: 'class',           type: $tStore('props.table.className.type'),        defaultValue: $tStore('props.table.className.default'),        required: $tStore('props.table.className.required'),        description: DOMPurify.sanitize($tStore('props.table.className.description'))        },
          { name: 'children',        type: 'Snippet',                                    defaultValue: '—',                                             required: 'Sim',                                            description: 'Conteúdo renderizado dentro do Viewport.' },
        ],
      },
    ]}
    interfaceCode={interfaceCode}
    extensibilityTitle={$tStore('props.extensibilityTitle')}
    extensibilityNotes={$tStore('props.extensibilityCode')}
  />

  <!-- ── Tokens ─────────────────────────────────────────────────── -->
  <DocsTokens
    title={$tStore('tokens.title')}
    cols={{
      token: $tStore('tokens.table.token'),
      value: $tStore('tokens.table.class'),
      description: $tStore('tokens.table.part'),
    }}
    items={[
      { token: '--border',                  value: $tStore('tokens.table.border.class'),     description: $tStore('tokens.table.border.part')     },
      { token: '--ring',                    value: $tStore('tokens.table.ring.class'),       description: $tStore('tokens.table.ring.part')       },
      { token: '--background',              value: $tStore('tokens.table.background.class'), description: $tStore('tokens.table.background.part') },
      { token: '--foreground',              value: $tStore('tokens.table.foreground.class'), description: $tStore('tokens.table.foreground.part') },
      { token: '--muted',                   value: $tStore('tokens.table.muted.class'),      description: $tStore('tokens.table.muted.part')      },
      { token: '--ring-offset-background',  value: $tStore('tokens.table.ringOffset.class'), description: $tStore('tokens.table.ringOffset.part') },
    ]}
    customizationTitle={$tStore('tokens.customizationTitle')}
    customizationCode={$tStore('tokens.customizationCode')}
  />

  <!-- ── Acessibilidade ─────────────────────────────────────────── -->
  <DocsAccessibility
    screenReaderTitle={$tNavStore('common.screenReader')}
    screenReaderItems={screenReaderItems}
    title={$tStore('accessibility.title')}
    summary={$tStore('accessibility.summary')}
    items={[
      $tStore('accessibility.items.item1'),
      $tStore('accessibility.items.item2'),
      stripHtml($tStore('accessibility.items.item3')),
      $tStore('accessibility.items.item4'),
      stripHtml($tStore('accessibility.items.item5')),
      $tStore('accessibility.items.item6'),
    ]}
    keyboardTitle={$tStore('accessibility.keyboard.title')}
    keyboardItems={[
      { key: 'Tab',       description: $tStore('accessibility.keyboard.tab')        },
      { key: 'Arrow Down',         description: $tStore('accessibility.keyboard.arrowDown')  },
      { key: 'Arrow Up',         description: $tStore('accessibility.keyboard.arrowUp')    },
      { key: 'Arrow Right',         description: $tStore('accessibility.keyboard.arrowRight') },
      { key: 'Arrow Left',         description: $tStore('accessibility.keyboard.arrowLeft')  },
      { key: 'PageDown',  description: $tStore('accessibility.keyboard.pageDown')   },
      { key: 'PageUp',    description: $tStore('accessibility.keyboard.pageUp')     },
      { key: 'Home',      description: $tStore('accessibility.keyboard.home')       },
      { key: 'End',       description: $tStore('accessibility.keyboard.end')        },
    ]}
  />

  <!-- ── Relacionados ───────────────────────────────────────────── -->
  <DocsRelated
    title={$tStore('related.title')}
    items={[
      { name: $tStore('related.items.resizable.name'), description: $tStore('related.items.resizable.description'), path: '?path=/docs/ui-resizable--docs' },
      { name: $tStore('related.items.sheet.name'),     description: $tStore('related.items.sheet.description'),     path: '?path=/docs/ui-sheet--docs'     },
      { name: $tStore('related.items.dialog.name'),    description: $tStore('related.items.dialog.description'),    path: '?path=/docs/ui-dialog--docs'    },
      { name: $tStore('related.items.command.name'),   description: $tStore('related.items.command.description'),   path: '?path=/docs/ui-command--docs'   },
    ]}
  />

  <!-- ── Notas ──────────────────────────────────────────────────── -->
  <DocsNotes
    title={$tStore('notes.title')}
    items={[
      { title: '', content: stripHtml($tStore('notes.item1')) },
      { title: '', content: stripHtml($tStore('notes.item2')) },
      { title: '', content: stripHtml($tStore('notes.item3')) },
      { title: '', content: stripHtml($tStore('notes.item4')) },
    ]}
  />

  <!-- ── Analytics ─────────────────────────────────────────────── -->
  <DocsAnalytics
    title={$tStore('analytics.title')}
    cols={{
      event: $tStore('analytics.table.event'),
      trigger: $tStore('analytics.table.trigger'),
      payload: $tStore('analytics.table.payload'),
    }}
    items={[
      { event: 'content_scroll', trigger: $tStore('analytics.table.content_scroll.trigger'), payload: $tStore('analytics.table.content_scroll.payload') },
    ]}
  />

  <!-- ── Testes ─────────────────────────────────────────────────── -->
  <DocsTestes
    title={$tStore('testes.title')}
    functional={{
      title: $tStore('testes.functional.title'),
      cols: {
        action: $tNavStore('common.userAction'),
        result: $tNavStore('common.expectedResult'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { action: $tStore('testes.functional.item1.action'), result: $tStore('testes.functional.item1.result'), priority: localPriority($tStore('testes.functional.item1.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item2.action'), result: $tStore('testes.functional.item2.result'), priority: localPriority($tStore('testes.functional.item2.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item3.action'), result: $tStore('testes.functional.item3.result'), priority: localPriority($tStore('testes.functional.item3.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item4.action'), result: $tStore('testes.functional.item4.result'), priority: localPriority($tStore('testes.functional.item4.priority'), $tNavStore) },
      ],
    }}
    accessibility={{
      title: $tStore('testes.accessibility.title'),
      cols: {
        criterion: $tNavStore('common.criterion'),
        level: 'WCAG',
        how: $tNavStore('common.howToVerify'),
      },
      items: [
        { criterion: $tStore('testes.accessibility.item1'), level: 'AA',     how: 'axe-core' },
        { criterion: $tStore('testes.accessibility.item2'), level: '1.4.11', how: 'Contrast checker' },
        { criterion: $tStore('testes.accessibility.item3'), level: '2.4.7',  how: 'Keyboard test' },
        { criterion: $tStore('testes.accessibility.item4'), level: '2.1.1',  how: 'Keyboard test' },
        { criterion: $tStore('testes.accessibility.item5'), level: '1.4.10', how: 'Manual mobile test' },
      ],
    }}
    visual={{
      title: $tStore('testes.visual.title'),
      cols: {
        story: $tNavStore('common.storyState'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { story: $tStore('testes.visual.item1.story'), priority: localPriority($tStore('testes.visual.item1.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item2.story'), priority: localPriority($tStore('testes.visual.item2.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item3.story'), priority: localPriority($tStore('testes.visual.item3.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item4.story'), priority: localPriority($tStore('testes.visual.item4.priority'), $tNavStore) },
      ],
    }}
  />
</DocsPageLayout>
