// nortear-design-system-react/src/components/docs/SkeletonDocs.tsx
import { useCallback, useEffect, useMemo } from "react";
import { Skeleton } from "@/components/ui/skeleton";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import { useTranslation } from "@/lib/i18n";
import { useSeoEffect } from "@/lib/use-seo";
import { track } from "@/lib/analytics";
import DOMPurify from 'dompurify';
import { useActiveSection } from "@/lib/use-active-section";
import uiTranslations from "@/i18n/ui.json";
import skeletonTranslations from "@shared/content/skeleton/translations.json";

import { DocsHeader }        from "@/components/docs/shared/sections/DocsHeader";
import { DocsPageLayout }    from "@/components/docs/shared/sections/DocsPageLayout";
import { DocsDemonstration } from "@/components/docs/shared/sections/DocsDemonstration";
import { DocsAnatomy }       from "@/components/docs/shared/sections/DocsAnatomy";
import { DocsWhenToUse }     from "@/components/docs/shared/sections/DocsWhenToUse";
import { DocsDoDont }        from "@/components/docs/shared/sections/DocsDoDont";
import { DocsImport }        from "@/components/docs/shared/sections/DocsImport";
import { DocsVariants }      from "@/components/docs/shared/sections/DocsVariants";
import { DocsStates }        from "@/components/docs/shared/sections/DocsStates";
import { DocsProps }         from "@/components/docs/shared/sections/DocsProps";
import { DocsTokens }        from "@/components/docs/shared/sections/DocsTokens";
import { DocsAccessibility } from "@/components/docs/shared/sections/DocsAccessibility";
import { DocsRelated }       from "@/components/docs/shared/sections/DocsRelated";
import { DocsNotes }         from "@/components/docs/shared/sections/DocsNotes";
import { DocsAnalytics }     from "@/components/docs/shared/sections/DocsAnalytics";
import { DocsTestes }        from "@/components/docs/shared/sections/DocsTestes";
import { stripHtml, toPlainText } from "@/lib/strip-html";

// ─── Helpers ─────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: "common.high",
  medium: "common.medium",
  low: "common.low",
};

// ─── Nav ─────────────────────────────────────────────────────────────────────

const getNavGroups = (t: (key: string) => string) => [
  {
    label: t("nav.overview"),
    sections: [
      { id: "demonstracao", label: t("nav.demonstration") },
      { id: "anatomia",     label: t("nav.anatomy") },
      { id: "quando-usar",  label: t("nav.usage") },
      { id: "do-dont",      label: t("nav.doDont") },
    ],
  },
  {
    label: t("nav.techRef"),
    sections: [
      { id: "importacao",   label: t("nav.import") },
      { id: "variantes",    label: t("nav.variants") },
      { id: "estados",      label: t("nav.states") },
      { id: "propriedades", label: t("nav.props") },
      { id: "tokens",       label: t("nav.tokens") },
    ],
  },
  {
    label: t("nav.context"),
    sections: [
      { id: "acessibilidade", label: t("nav.accessibility") },
      { id: "relacionados",   label: t("nav.related") },
      { id: "notas",          label: t("nav.notes") },
    ],
  },
  {
    label: t("nav.quality"),
    sections: [
      { id: "analytics", label: t("nav.analytics") },
      { id: "testes",    label: t("nav.testes") },
    ],
  },
];

// ─── Componente principal ─────────────────────────────────────────────────────

export function SkeletonDocs() {
  const { t: tNav } = useTranslation(uiTranslations);
  const { t: tContent, locale } = useTranslation(skeletonTranslations);

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria.
  const screenReaderItems = useMemo(
    () =>
      Object.values(
        (skeletonTranslations as unknown as Record<
          string,
          { accessibility?: { screenReader?: Record<string, string> } }
        >)[locale]?.accessibility?.screenReader ?? {},
      ),
    [locale],
  );

  const navGroups = useMemo(() => getNavGroups(tNav), [tNav]);
  const allIds = useMemo(
    () => navGroups.flatMap((g) => g.sections.map((s) => s.id)),
    [navGroups]
  );

  useSeoEffect({
    title: tContent("seo.title"),
    description: tContent("seo.description"),
    locale,
    componentSlug: "skeleton",
  });

  useEffect(() => {
    track("docs_page_view", {
      component_name: "skeleton",
      locale,
      page_title: `${tContent("title")} · Design System`,
    });
  }, [locale, tContent]);

  const handleSectionChange = useCallback(
    (id: string) => {
      track("docs_section_viewed", {
        section_id: id,
        component_name: "skeleton",
        locale,
      });
    },
    [locale]
  );

  const activeId = useActiveSection(allIds, handleSectionChange);

  // ─── Code strings ───────────────────────────────────────────────────────────

  const codeImport = `import { Skeleton } from "@/components/ui/skeleton";`;

  const codeRectangle = `<Skeleton data-shape="fill" className="nds-docs-skeleton-media" />`;
  const codeCircle = `<Skeleton data-shape="avatar" />`;
  const codeLine = `<Skeleton data-shape="text" data-width="3-4" />`;

  const interfaceCode = `// Skeleton — sem props próprias além de className.
// A caixa vem de atributo, e a folha de estilo continua dona das medidas.
interface SkeletonProps extends React.ComponentProps<"div"> {
  className?: string;
  "data-shape"?: "text" | "heading" | "avatar" | "fill";
  "data-width"?: "full" | "3-4" | "2-3" | "1-2" | "1-3";
  "data-size"?: "sm" | "lg";
}`;

  // ─── Locale-aware column labels ─────────────────────────────────────────────

  const analyticsCols = {
    event: locale === "en" ? "Event" : locale === "es" ? "Evento" : "Evento",
    trigger: locale === "en" ? "Trigger" : locale === "es" ? "Disparo" : "Disparo",
    payload: "Payload",
  };

  return (
    <DocsPageLayout
      navGroups={navGroups}
      activeSection={activeId}
      componentSlug="skeleton"
      header={
        <DocsHeader
          title={tContent("title")}
          description={tContent("description")}
          category={tContent("category")}
          type={tContent("type")}
        />
      }
    >
      {/* ── Demonstração ──────────────────────────────────────────── */}
      <DocsDemonstration title={tContent("demonstration.title")}>
        <div className="nds-grid nds-w-full" data-cols="2" data-spacing="lg" style={{ '--grid-min': '16rem' } as React.CSSProperties}>
          {/* Card de perfil */}
          <div className="nds-stack" data-spacing="sm">
            <p className="nds-text-caption nds-font-medium nds-text-muted-foreground">
              {DOMPurify.sanitize(tContent("demonstration.labels.card"))}
            </p>
            <div
              role="status"
              aria-busy="true"
              aria-label={DOMPurify.sanitize(tContent("demonstration.labels.card"))}
              className="nds-cluster nds-p-4 nds-border-default nds-rounded-md"
              data-spacing="md"
              data-align="center"
            >
              <Skeleton data-shape="avatar" />
              <div className="nds-stack nds-flex-1" data-spacing="sm">
                <Skeleton data-shape="text" data-width="2-3" />
                <Skeleton data-shape="text" data-width="1-2" />
              </div>
            </div>
          </div>

          {/* Lista */}
          <div className="nds-stack" data-spacing="sm">
            <p className="nds-text-caption nds-font-medium nds-text-muted-foreground">
              {DOMPurify.sanitize(tContent("demonstration.labels.list"))}
            </p>
            <div
              role="status"
              aria-busy="true"
              aria-label={DOMPurify.sanitize(tContent("demonstration.labels.list"))}
              className="nds-stack nds-p-4 nds-border-default nds-rounded-md"
              data-spacing="sm"
            >
              {Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="nds-cluster" data-spacing="sm" data-align="center">
                  <Skeleton data-shape="avatar" data-size="sm" />
                  <div className="nds-flex-1 nds-stack" data-spacing="xs">
                    <Skeleton data-shape="text" data-width="2-3" />
                    <Skeleton data-shape="text" data-width="1-3" />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Imagem em AspectRatio */}
          <div className="nds-stack" data-spacing="sm">
            <p className="nds-text-caption nds-font-medium nds-text-muted-foreground">
              {DOMPurify.sanitize(tContent("demonstration.labels.image"))}
            </p>
            <div
              role="status"
              aria-busy="true"
              aria-label={DOMPurify.sanitize(tContent("demonstration.labels.image"))}
            >
              <AspectRatio ratio={16 / 9}>
                <Skeleton data-shape="fill" />
              </AspectRatio>
            </div>
          </div>

          {/* Parágrafo */}
          <div className="nds-stack" data-spacing="sm">
            <p className="nds-text-caption nds-font-medium nds-text-muted-foreground">
              {DOMPurify.sanitize(tContent("demonstration.labels.paragraph"))}
            </p>
            <div
              role="status"
              aria-busy="true"
              aria-label={DOMPurify.sanitize(tContent("demonstration.labels.paragraph"))}
              className="nds-stack nds-p-4 nds-border-default nds-rounded-md"
              data-spacing="sm"
            >
              <Skeleton data-shape="text" data-width="full" />
              <Skeleton data-shape="text" data-width="3-4" />
              <Skeleton data-shape="text" data-width="1-2" />
            </div>
          </div>
        </div>
      </DocsDemonstration>

      {/* ── Anatomia ──────────────────────────────────────────────── */}
      <DocsAnatomy
        title={tContent("anatomy.title")}
        items={[
          tContent("anatomy.item1"),
          tContent("anatomy.item2"),
          tContent("anatomy.item3"),
        ]}
        structureLabel={tContent("anatomy.structureLabel")}
        structureCode={tContent("anatomy.structureCode")}
      />

      {/* ── Quando Usar ───────────────────────────────────────────── */}
      <DocsWhenToUse
        title={tContent("usage.title")}
        guidelines={{
          title: tContent("usage.guidelines.title"),
          items: [
            tContent("usage.guidelines.item1"),
            tContent("usage.guidelines.item2"),
            tContent("usage.guidelines.item3"),
            tContent("usage.guidelines.item4"),
            tContent("usage.guidelines.item5"),
          ],
        }}
        scenarios={{
          title: tContent("usage.scenarios.title"),
          cols: {
            scenario: tContent("usage.scenarios.cols.scenario"),
            use: tContent("usage.scenarios.cols.use"),
            alternative: tContent("usage.scenarios.cols.alternative"),
          },
          items: [
            { s: tContent("usage.scenarios.item1.s"), u: tContent("usage.scenarios.item1.u"), a: tContent("usage.scenarios.item1.a") },
            { s: tContent("usage.scenarios.item2.s"), u: tContent("usage.scenarios.item2.u"), a: tContent("usage.scenarios.item2.a") },
            { s: tContent("usage.scenarios.item3.s"), u: tContent("usage.scenarios.item3.u"), a: tContent("usage.scenarios.item3.a") },
            { s: tContent("usage.scenarios.item4.s"), u: tContent("usage.scenarios.item4.u"), a: tContent("usage.scenarios.item4.a") },
            { s: tContent("usage.scenarios.item5.s"), u: tContent("usage.scenarios.item5.u"), a: tContent("usage.scenarios.item5.a") },
          ],
        }}
        uxWriting={{
          title: tContent("usage.uxWriting.title"),
          cols: {
            element: tContent("usage.uxWriting.table.element"),
            rules: tContent("usage.uxWriting.table.rules"),
            do: tContent("usage.uxWriting.table.correct"),
            dont: tContent("usage.uxWriting.table.avoid"),
          },
          items: [
            {
              element: tContent("usage.uxWriting.table.ariaLabel.name"),
              rules: tContent("usage.uxWriting.table.ariaLabel.format"),
              do: tContent("usage.uxWriting.table.ariaLabel.good"),
              dont: tContent("usage.uxWriting.table.ariaLabel.bad"),
            },
            {
              element: tContent("usage.uxWriting.table.dimensions.name"),
              rules: tContent("usage.uxWriting.table.dimensions.format"),
              do: tContent("usage.uxWriting.table.dimensions.good"),
              dont: tContent("usage.uxWriting.table.dimensions.bad"),
            },
            {
              element: tContent("usage.uxWriting.table.shape.name"),
              rules: tContent("usage.uxWriting.table.shape.format"),
              do: tContent("usage.uxWriting.table.shape.good"),
              dont: tContent("usage.uxWriting.table.shape.bad"),
            },
            {
              element: tContent("usage.uxWriting.table.motionReduce.name"),
              rules: tContent("usage.uxWriting.table.motionReduce.format"),
              do: tContent("usage.uxWriting.table.motionReduce.good"),
              dont: tContent("usage.uxWriting.table.motionReduce.bad"),
            },
          ],
        }}
        do={{
          title: tContent("usage.do.title"),
          items: [
            tContent("usage.do.item1"),
            tContent("usage.do.item2"),
            tContent("usage.do.item3"),
            tContent("usage.do.item4"),
          ],
        }}
        dont={{
          title: tContent("usage.dont.title"),
          items: [
            tContent("usage.dont.item1"),
            tContent("usage.dont.item2"),
            tContent("usage.dont.item3"),
            tContent("usage.dont.item4"),
          ],
        }}
      />

      {/* ── Do & Don't ────────────────────────────────────────────── */}
      <DocsDoDont
        title={tContent("doDont.title")}
        pairs={[
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doPreview: (
              <div
                role="status"
                aria-busy="true"
                aria-label="Carregando texto"
                className="nds-w-full nds-stack"
                data-spacing="sm"
              >
                <Skeleton data-shape="heading" data-width="1-2" />
                <Skeleton data-shape="text" data-width="full" />
                <Skeleton data-shape="text" data-width="3-4" />
              </div>
            ),
            dontPreview: (
              <div className="nds-w-full">
                <Skeleton data-shape="text" data-width="1-3" />
              </div>
            ),
            doCaption: DOMPurify.sanitize(tContent("doDont.pair1.do")),
            dontCaption: DOMPurify.sanitize(tContent("doDont.pair1.dont")),
          },
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doPreview: (
              <div
                role="status"
                aria-busy="true"
                aria-label="Carregando avatar e texto"
                className="nds-cluster nds-w-full"
                data-spacing="sm"
                data-align="center"
              >
                <Skeleton data-shape="avatar" />
                <div className="nds-stack nds-flex-1" data-spacing="xs">
                  <Skeleton data-shape="text" data-width="1-2" />
                  <Skeleton data-shape="text" data-width="1-3" />
                </div>
              </div>
            ),
            dontPreview: (
              <div className="nds-cluster nds-w-full" data-spacing="sm" data-align="center">
                <Skeleton data-shape="avatar" />
                <div className="nds-stack nds-flex-1" data-spacing="xs">
                  <Skeleton data-shape="text" data-width="1-2" />
                  <Skeleton data-shape="text" data-width="1-3" />
                </div>
              </div>
            ),
            doCaption: DOMPurify.sanitize(tContent("doDont.pair2.do")),
            dontCaption: DOMPurify.sanitize(tContent("doDont.pair2.dont")),
          },
        ]}
      />

      {/* ── Importação ────────────────────────────────────────────── */}
      <DocsImport title={tContent("import.title")} code={codeImport} />

      {/* ── Variantes ─────────────────────────────────────────────── */}
      <DocsVariants
        title={tContent("variants.title")}
        componentSlug="skeleton"
        items={[
          {
            name: tContent("variants.items.rectangle"),
            description: stripHtml(tContent("variants.styles.rectangle")),
            code: codeRectangle,
            preview: (
              <div role="status" aria-busy="true" aria-label="Carregando bloco" className="nds-w-xs">
                <Skeleton data-shape="fill" className="nds-docs-skeleton-media" />
              </div>
            ),
          },
          {
            name: tContent("variants.items.circle"),
            description: stripHtml(tContent("variants.styles.circle")),
            code: codeCircle,
            preview: (
              <div role="status" aria-busy="true" aria-label="Carregando avatar">
                <Skeleton data-shape="avatar" />
              </div>
            ),
          },
          {
            name: tContent("variants.items.line"),
            description: stripHtml(tContent("variants.styles.line")),
            code: codeLine,
            preview: (
              <div
                role="status"
                aria-busy="true"
                aria-label="Carregando linha de texto"
                className="nds-stack nds-w-xs"
                data-spacing="xs"
              >
                <Skeleton data-shape="text" data-width="3-4" />
                <Skeleton data-shape="text" data-width="1-2" />
              </div>
            ),
          },
        ]}
      />

      {/* ── Estados ───────────────────────────────────────────────── */}
      <DocsStates
        title={tContent("states.title")}
        cols={{
          state: tContent("states.cols.state"),
          trigger: toPlainText(tContent("states.cols.trigger")),
          behavior: toPlainText(tContent("states.cols.behavior")),
        }}
        items={[
          {
            label: tContent("states.default.label"),
            trigger: toPlainText(tContent("states.default.trigger")),
            behavior: toPlainText(tContent("states.default.behavior")),
          },
          {
            label: tContent("states.motionReduced.label"),
            trigger: toPlainText(tContent("states.motionReduced.trigger")),
            behavior: toPlainText(tContent("states.motionReduced.behavior")),
          },
        ]}
      />

      {/* ── Propriedades ──────────────────────────────────────────── */}
      <DocsProps
        title={tContent("props.title")}
        tables={[
          {
            cols: {
              prop: tContent("props.table.prop"),
              type: tContent("props.table.type"),
              default: tContent("props.table.default"),
              required: tContent("props.table.required"),
              description: tContent("props.table.description"),
            },
            items: [
              {
                name: "className",
                type: tContent("props.table.className.type"),
                defaultValue: tContent("props.table.className.default"),
                required: tContent("props.table.className.required"),
                description: DOMPurify.sanitize(tContent("props.table.className.description")),
              },
              {
                name: "data-shape",
                type: tContent("props.table.dataShape.type"),
                defaultValue: tContent("props.table.dataShape.default"),
                required: tContent("props.table.dataShape.required"),
                description: DOMPurify.sanitize(tContent("props.table.dataShape.description")),
              },
              {
                name: "data-width",
                type: tContent("props.table.dataWidth.type"),
                defaultValue: tContent("props.table.dataWidth.default"),
                required: tContent("props.table.dataWidth.required"),
                description: DOMPurify.sanitize(tContent("props.table.dataWidth.description")),
              },
              {
                name: "data-size",
                type: tContent("props.table.dataSize.type"),
                defaultValue: tContent("props.table.dataSize.default"),
                required: tContent("props.table.dataSize.required"),
                description: DOMPurify.sanitize(tContent("props.table.dataSize.description")),
              },
              {
                name: "aria-hidden",
                type: tContent("props.table.ariaHidden.type"),
                defaultValue: tContent("props.table.ariaHidden.default"),
                required: tContent("props.table.ariaHidden.required"),
                description: DOMPurify.sanitize(tContent("props.table.ariaHidden.description")),
              },
              {
                name: "...rest",
                type: tContent("props.table.rest.type"),
                defaultValue: tContent("props.table.rest.default"),
                required: tContent("props.table.rest.required"),
                description: DOMPurify.sanitize(tContent("props.table.rest.description")),
              },
            ],
          },
        ]}
        interfaceCode={interfaceCode}
        extensibilityTitle={tContent("props.extensibilityTitle")}
        extensibilityNotes={tContent("props.extensibilityCode")}
      />

      {/* ── Tokens ────────────────────────────────────────────────── */}
      <DocsTokens
        title={tContent("tokens.title")}
        cols={{
          token: tContent("tokens.table.token"),
          value: tContent("tokens.table.class"),
          description: tContent("tokens.table.part"),
        }}
        items={["background", "rounded", "animation", "size", "motionReduce"].map((k) => ({
          token: tContent(`tokens.table.${k}.token`),
          value: tContent(`tokens.table.${k}.class`),
          description: tContent(`tokens.table.${k}.part`),
        }))}
        customizationTitle={tContent("tokens.customizationTitle")}
        customizationCode={tContent("tokens.customizationCode")}
      />

      {/* ── Acessibilidade ────────────────────────────────────────── */}
      <DocsAccessibility
        screenReaderTitle={tNav("common.screenReader")}
        screenReaderItems={screenReaderItems}
        title={tContent("accessibility.title")}
        summary={tContent("accessibility.summary")}
        items={[
          tContent("accessibility.items.item1"),
          tContent("accessibility.items.item2"),
          tContent("accessibility.items.item3"),
          tContent("accessibility.items.item4"),
          tContent("accessibility.items.item5"),
        ]}
        keyboardTitle={tContent("accessibility.keyboard.title")}
        keyboardItems={[
          { key: "—", description: tContent("accessibility.keyboard.noKeyboard") },
          { key: "Tab", description: tContent("accessibility.keyboard.description") },
        ]}
      />

      {/* ── Relacionados ──────────────────────────────────────────── */}
      <DocsRelated
        title={tContent("related.title")}
        componentSlug="skeleton"
        items={[
          {
            name: tContent("related.items.progress.name"),
            description: toPlainText(tContent("related.items.progress.description")),
            path: "?path=/docs/ui-progress--docs",
          },
          {
            name: tContent("related.items.aspectRatio.name"),
            description: toPlainText(tContent("related.items.aspectRatio.description")),
            path: "?path=/docs/ui-aspectratio--docs",
          },
          {
            name: tContent("related.items.card.name"),
            description: toPlainText(tContent("related.items.card.description")),
            path: "?path=/docs/ui-card--docs",
          },
        ]}
      />

      {/* ── Notas ─────────────────────────────────────────────────── */}
      <DocsNotes
        title={tContent("notes.title")}
        componentSlug="skeleton"
        items={[
          { title: "", content: tContent("notes.item1") },
          { title: "", content: tContent("notes.item2") },
          { title: "", content: tContent("notes.item3") },
          { title: "", content: tContent("notes.item4") },
          { title: "", content: tContent("notes.item5") },
        ]}
      />

      {/* ── Analytics ─────────────────────────────────────────────── */}
      <DocsAnalytics
        title={tContent("analytics.title")}
        cols={analyticsCols}
        items={[
          {
            event: "—",
            trigger: toPlainText(tContent("analytics.description")),
            payload: "—",
          },
        ]}
      />

      {/* ── Testes ────────────────────────────────────────────────── */}
      <DocsTestes
        title={tContent("testes.title")}
        functional={{
          title: tContent("testes.functional.title"),
          cols: {
            action: tNav("common.userAction"),
            result: tNav("common.expectedResult"),
            priority: tNav("common.priority"),
          },
          items: [
            {
              action: tContent("testes.functional.item1.action"),
              result: tContent("testes.functional.item1.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item1.priority")] ?? "common.high"),
            },
            {
              action: tContent("testes.functional.item2.action"),
              result: tContent("testes.functional.item2.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item2.priority")] ?? "common.high"),
            },
            {
              action: tContent("testes.functional.item3.action"),
              result: tContent("testes.functional.item3.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item3.priority")] ?? "common.high"),
            },
            {
              action: tContent("testes.functional.item4.action"),
              result: tContent("testes.functional.item4.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item4.priority")] ?? "common.high"),
            },
            {
              action: tContent("testes.functional.item5.action"),
              result: tContent("testes.functional.item5.result"),
              priority: tNav(priorityKeyMap[tContent("testes.functional.item5.priority")] ?? "common.medium"),
            },
          ],
        }}
        accessibility={{
          title: tContent("testes.accessibility.title"),
          cols: {
            criterion: tNav("common.criterion"),
            level: "WCAG",
            how: tNav("common.howToVerify"),
          },
          items: [
            { criterion: tContent("testes.accessibility.item1"), level: "AA", how: "axe-core" },
            { criterion: tContent("testes.accessibility.item2"), level: "4.1.2", how: "DevTools a11y tree" },
            { criterion: tContent("testes.accessibility.item3"), level: "4.1.2", how: "DevTools a11y tree" },
            { criterion: tContent("testes.accessibility.item4"), level: "2.3.3", how: "prefers-reduced-motion" },
            // Não é critério da WCAG: o esqueleto não transmite informação, então
            // 1.4.3 e 1.4.11 não se aplicam. O que se mede é luminância.
            { criterion: tContent("testes.accessibility.item5"), level: "—", how: "Medição de luminância" },
          ],
        }}
        visual={{
          title: tContent("testes.visual.title"),
          cols: {
            story: tNav("common.storyState"),
            priority: tNav("common.priority"),
          },
          items: [
            { story: tContent("testes.visual.item1.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item1.priority")] ?? "common.high") },
            { story: tContent("testes.visual.item2.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item2.priority")] ?? "common.high") },
            { story: tContent("testes.visual.item3.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item3.priority")] ?? "common.high") },
            { story: tContent("testes.visual.item4.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item4.priority")] ?? "common.high") },
            { story: tContent("testes.visual.item5.story"), priority: tNav(priorityKeyMap[tContent("testes.visual.item5.priority")] ?? "common.medium") },
          ],
        }}
      />
    </DocsPageLayout>
  );
}

export default SkeletonDocs;

// nortear-design-system-svelte/src/components/docs/SkeletonDocs.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { Skeleton } from '@/components/ui/skeleton';
  import { AspectRatio } from '@/components/ui/aspect-ratio';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import { createActiveSection } from '@/lib/use-active-section.svelte';
  import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader, DocsDemonstration, DocsAnatomy, DocsWhenToUse, DocsDoDont,
    DocsImport, DocsVariants, DocsStates, DocsProps, DocsTokens,
    DocsAccessibility, DocsRelated, DocsNotes, DocsAnalytics, DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import skeletonTranslations from '@shared/content/skeleton/translations.json';
  import { stripHtml, toPlainText } from '@/lib/strip-html';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(skeletonTranslations);

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria.
  const screenReaderItems = $derived(
    Object.values(
      (skeletonTranslations as unknown as Record<
        string,
        { accessibility?: { screenReader?: Record<string, string> } }
      >)[$locale]?.accessibility?.screenReader ?? {},
    ),
  );

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'skeleton',
    });
    track('docs_page_view', {
      component_name: 'skeleton',
      locale: l,
      page_title: t('title'),
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────

  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')   },
        { id: 'variantes',    label: tNav('nav.variants') },
        { id: 'estados',      label: tNav('nav.states')   },
        { id: 'propriedades', label: tNav('nav.props')    },
        { id: 'tokens',       label: tNav('nav.tokens')   },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  const sectionIds = untrack(() => NAV_GROUPS.flatMap(g => g.sections.map(s => s.id)));
  const section = createActiveSection(sectionIds, (id) => {
    track('docs_section_viewed', { section_id: id, component_name: 'skeleton', locale: $locale });
  });
  $effect(() => section.attach());

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  const priorityKeyMap: Record<string, string> = { high: 'common.high', medium: 'common.medium', low: 'common.low' };
  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  // ─── Code strings ────────────────────────────────────────────────────────────

  const codeImportBasic = `import { Skeleton } from "@/components/ui/skeleton";`;

  const codeImportUsage = `import { Skeleton } from "@/components/ui/skeleton";

<div role="status" aria-busy={isLoading} aria-label="Carregando perfil">
  <Skeleton data-shape="avatar" />
  <Skeleton data-shape="text" data-width="3-4" />
</div>`;

  const codeRectangle = `<Skeleton data-shape="fill" class="nds-docs-skeleton-media" />`;
  const codeCircle = `<Skeleton data-shape="avatar" />`;
  const codeLine = `<Skeleton data-shape="text" data-width="3-4" />`;

  // Sem props próprias além de class: a caixa vem de atributo, e a folha de
  // estilo continua dona das medidas.
  const interfaceCode = `interface SkeletonProps extends HTMLAttributes<HTMLDivElement> {
  class?: string;
  // data-shape: "text" | "heading" | "avatar" | "fill"
  // data-width: "full" | "3-4" | "2-3" | "1-2" | "1-3"
  // data-size:  "sm" | "lg"   (só na forma de avatar)
}`;
</script>

<DocsPageLayout navGroups={NAV_GROUPS} activeSection={section.value}>
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
    />
  {/snippet}

  <!-- ── Demonstração ───────────────────────────────────────────── -->
  <DocsDemonstration title={$tStore('demonstration.title')}>
    <div class="nds-grid nds-w-full" data-cols="2" data-spacing="lg" style="--grid-min: 16rem">
      <!-- Card de perfil -->
      <div class="nds-stack" data-spacing="sm">
        <p class="nds-text-caption nds-font-medium nds-text-muted-foreground">{$tStore('demonstration.labels.card')}</p>
        <div
          role="status"
          aria-busy="true"
          aria-label={$tStore('demonstration.labels.card')}
          class="nds-cluster nds-p-4 nds-border-default nds-rounded-md"
          data-spacing="md"
          data-align="center"
        >
          <Skeleton data-shape="avatar" />
          <div class="nds-stack nds-flex-1" data-spacing="sm">
            <Skeleton data-shape="text" data-width="2-3" />
            <Skeleton data-shape="text" data-width="1-2" />
          </div>
        </div>
      </div>

      <!-- Lista -->
      <div class="nds-stack" data-spacing="sm">
        <p class="nds-text-caption nds-font-medium nds-text-muted-foreground">{$tStore('demonstration.labels.list')}</p>
        <ul aria-busy="true" aria-label={$tStore('demonstration.labels.list')} class="nds-stack nds-list-none nds-p-0" data-spacing="sm">
          {#each Array.from({ length: 5 }) as _, i (i)}
            <li class="nds-cluster nds-p-2 nds-border-default nds-rounded-md" data-spacing="sm" data-align="center">
              <Skeleton data-shape="avatar" data-size="sm" />
              <div class="nds-stack nds-flex-1" data-spacing="xs">
                <Skeleton data-shape="text" data-width="2-3" />
                <Skeleton data-shape="text" data-width="1-3" />
              </div>
            </li>
          {/each}
        </ul>
      </div>

      <!-- Imagem AspectRatio -->
      <div class="nds-stack" data-spacing="sm">
        <p class="nds-text-caption nds-font-medium nds-text-muted-foreground">{$tStore('demonstration.labels.image')}</p>
        <div role="status" aria-busy="true" aria-label={$tStore('demonstration.labels.image')}>
          <AspectRatio ratio={16 / 9}>
            <Skeleton data-shape="fill" />
          </AspectRatio>
        </div>
      </div>

      <!-- Parágrafo -->
      <div class="nds-stack" data-spacing="sm">
        <p class="nds-text-caption nds-font-medium nds-text-muted-foreground">{$tStore('demonstration.labels.paragraph')}</p>
        <div role="status" aria-busy="true" aria-label={$tStore('demonstration.labels.paragraph')} class="nds-stack nds-p-4 nds-border-default nds-rounded-md" data-spacing="sm">
          <Skeleton data-shape="text" data-width="full" />
          <Skeleton data-shape="text" data-width="3-4" />
          <Skeleton data-shape="text" data-width="1-2" />
        </div>
      </div>
    </div>
  </DocsDemonstration>

  <!-- ── Anatomia ───────────────────────────────────────────────── -->
  <DocsAnatomy
    title={$tStore('anatomy.title')}
    items={[
      $tStore('anatomy.item1'),
      $tStore('anatomy.item2'),
      $tStore('anatomy.item3'),
    ]}
    structureCode={$tStore('anatomy.structureCode')}
  />

  <!-- ── Quando Usar ────────────────────────────────────────────── -->
  <DocsWhenToUse
    title={$tStore('usage.title')}
    guidelines={{
      title: $tStore('usage.guidelines.title'),
      items: [
        $tStore('usage.guidelines.item1'),
        $tStore('usage.guidelines.item2'),
        $tStore('usage.guidelines.item3'),
        $tStore('usage.guidelines.item4'),
        $tStore('usage.guidelines.item5'),
      ],
    }}
    scenarios={{
      title: $tStore('usage.scenarios.title'),
      cols: {
        scenario: $tStore('usage.scenarios.cols.scenario'),
        use: $tStore('usage.scenarios.cols.use'),
        alternative: $tStore('usage.scenarios.cols.alternative'),
      },
      items: [
        { s: $tStore('usage.scenarios.item1.s'), u: $tStore('usage.scenarios.item1.u'), a: toPlainText($tStore('usage.scenarios.item1.a')) },
        { s: $tStore('usage.scenarios.item2.s'), u: $tStore('usage.scenarios.item2.u'), a: toPlainText($tStore('usage.scenarios.item2.a')) },
        { s: $tStore('usage.scenarios.item3.s'), u: $tStore('usage.scenarios.item3.u'), a: toPlainText($tStore('usage.scenarios.item3.a')) },
        { s: $tStore('usage.scenarios.item4.s'), u: $tStore('usage.scenarios.item4.u'), a: toPlainText($tStore('usage.scenarios.item4.a')) },
        { s: $tStore('usage.scenarios.item5.s'), u: $tStore('usage.scenarios.item5.u'), a: toPlainText($tStore('usage.scenarios.item5.a')) },
      ],
    }}
    do={{
      title: $tStore('usage.do.title'),
      items: [
        $tStore('usage.do.item1'),
        $tStore('usage.do.item2'),
        $tStore('usage.do.item3'),
        $tStore('usage.do.item4'),
      ],
    }}
    dont={{
      title: $tStore('usage.dont.title'),
      items: [
        $tStore('usage.dont.item1'),
        $tStore('usage.dont.item2'),
        $tStore('usage.dont.item3'),
        $tStore('usage.dont.item4'),
      ],
    }}
  />

  <!-- ── Do & Don't ─────────────────────────────────────────────── -->
  <DocsDoDont
    title={$tStore('doDont.title')}
    pairs={[
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair1.do'),
        dontCaption: $tStore('doDont.pair1.dont'),
        doPreview: doPair1,
        dontPreview: dontPair1,
      },
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair2.do'),
        dontCaption: $tStore('doDont.pair2.dont'),
        doPreview: doPair2,
        dontPreview: dontPair2,
      },
    ]}
  />

  {#snippet doPair1()}
    <div role="status" aria-busy="true" aria-label="Carregando card" class="nds-w-full nds-max-w-xs nds-p-4 nds-border-default nds-rounded-md nds-stack" data-spacing="sm">
      <Skeleton data-shape="heading" data-width="1-2" />
      <Skeleton data-shape="text" data-width="full" />
      <Skeleton data-shape="text" data-width="3-4" />
    </div>
  {/snippet}
  {#snippet dontPair1()}
    <div role="status" aria-busy="true" aria-label="Carregando" class="nds-w-full nds-max-w-xs nds-p-4 nds-border-default nds-rounded-md">
      <Skeleton data-shape="text" data-width="1-3" />
    </div>
  {/snippet}
  {#snippet doPair2()}
    <div role="status" aria-busy="true" aria-label="Carregando avatar" class="nds-cluster nds-w-full" data-spacing="sm" data-align="center">
      <Skeleton data-shape="avatar" />
      <div class="nds-stack nds-flex-1" data-spacing="xs">
        <Skeleton data-shape="text" data-width="1-2" />
        <Skeleton data-shape="text" data-width="1-3" />
      </div>
    </div>
  {/snippet}
  {#snippet dontPair2()}
    <div class="nds-cluster nds-w-full" data-spacing="sm" data-align="center">
      <Skeleton data-shape="avatar" />
      <div class="nds-stack nds-flex-1" data-spacing="xs">
        <Skeleton data-shape="text" data-width="1-2" />
        <Skeleton data-shape="text" data-width="1-3" />
      </div>
    </div>
  {/snippet}

  <!-- ── Importação ─────────────────────────────────────────────── -->
  <DocsImport
    title={$tStore('import.title')}
    code={codeImportBasic}
    secondaryCode={codeImportUsage}
  />

  <!-- ── Variantes ──────────────────────────────────────────────── -->
  <DocsVariants
    title={$tStore('variants.title')}
    items={[
      { name: $tStore('variants.items.rectangle'), description: stripHtml($tStore('variants.styles.rectangle')), code: codeRectangle, preview: variantRectangle },
      { name: $tStore('variants.items.circle'),    description: stripHtml($tStore('variants.styles.circle')),    code: codeCircle,    preview: variantCircle    },
      { name: $tStore('variants.items.line'),      description: stripHtml($tStore('variants.styles.line')),      code: codeLine,      preview: variantLine      },
    ]}
  />

  {#snippet variantRectangle()}
    <div role="status" aria-busy="true" aria-label="Carregando bloco" class="nds-w-xs">
      <Skeleton data-shape="fill" class="nds-docs-skeleton-media" />
    </div>
  {/snippet}
  {#snippet variantCircle()}
    <div role="status" aria-busy="true" aria-label="Carregando avatar">
      <Skeleton data-shape="avatar" />
    </div>
  {/snippet}
  {#snippet variantLine()}
    <div role="status" aria-busy="true" aria-label="Carregando texto" class="nds-stack nds-w-xs" data-spacing="xs">
      <Skeleton data-shape="text" data-width="3-4" />
      <Skeleton data-shape="text" data-width="1-2" />
    </div>
  {/snippet}

  <!-- ── Estados ────────────────────────────────────────────────── -->
  <DocsStates
    title={$tStore('states.title')}
    cols={{
      state: $tStore('states.cols.state'),
      trigger: toPlainText($tStore('states.cols.trigger')),
      behavior: toPlainText($tStore('states.cols.behavior')),
    }}
    items={[
      { label: $tStore('states.default.label'),       trigger: toPlainText($tStore('states.default.trigger')),       behavior: toPlainText($tStore('states.default.behavior')) },
      { label: $tStore('states.motionReduced.label'), trigger: toPlainText($tStore('states.motionReduced.trigger')), behavior: toPlainText($tStore('states.motionReduced.behavior')) },
    ]}
  />

  <!-- ── Propriedades ───────────────────────────────────────────── -->
  <DocsProps
    title={$tStore('props.title')}
    tables={[
      {
        cols: {
          prop: $tStore('props.table.prop'),
          type: $tStore('props.table.type'),
          default: $tStore('props.table.default'),
          required: $tStore('props.table.required'),
          description: $tStore('props.table.description'),
        },
        items: [
          { name: 'class',       type: $tStore('props.table.className.type'),  defaultValue: $tStore('props.table.className.default'),  required: $tStore('props.table.className.required'),  description: $tStore('props.table.className.description')  },
          { name: 'data-shape',  type: $tStore('props.table.dataShape.type'),  defaultValue: $tStore('props.table.dataShape.default'),  required: $tStore('props.table.dataShape.required'),  description: $tStore('props.table.dataShape.description')  },
          { name: 'data-width',  type: $tStore('props.table.dataWidth.type'),  defaultValue: $tStore('props.table.dataWidth.default'),  required: $tStore('props.table.dataWidth.required'),  description: $tStore('props.table.dataWidth.description')  },
          { name: 'data-size',   type: $tStore('props.table.dataSize.type'),   defaultValue: $tStore('props.table.dataSize.default'),   required: $tStore('props.table.dataSize.required'),   description: $tStore('props.table.dataSize.description')   },
          { name: 'aria-hidden', type: $tStore('props.table.ariaHidden.type'), defaultValue: $tStore('props.table.ariaHidden.default'), required: $tStore('props.table.ariaHidden.required'), description: $tStore('props.table.ariaHidden.description') },
          { name: '...rest',     type: $tStore('props.table.rest.type'),       defaultValue: $tStore('props.table.rest.default'),       required: $tStore('props.table.rest.required'),       description: $tStore('props.table.rest.description')       },
        ],
      },
    ]}
    interfaceCode={interfaceCode}
    extensibilityTitle={$tStore('props.extensibilityTitle')}
    extensibilityNotes={$tStore('props.extensibilityCode')}
  />

  <!-- ── Tokens ─────────────────────────────────────────────────── -->
  <DocsTokens
    title={$tStore('tokens.title')}
    cols={{
      token: $tStore('tokens.table.token'),
      value: $tStore('tokens.table.class'),
      description: $tStore('tokens.table.part'),
    }}
    items={[
      { token: $tStore('tokens.table.background.token'),   value: $tStore('tokens.table.background.class'),   description: $tStore('tokens.table.background.part')   },
      { token: $tStore('tokens.table.rounded.token'),      value: $tStore('tokens.table.rounded.class'),      description: $tStore('tokens.table.rounded.part')      },
      { token: $tStore('tokens.table.animation.token'),    value: $tStore('tokens.table.animation.class'),    description: $tStore('tokens.table.animation.part')    },
      { token: $tStore('tokens.table.size.token'),         value: $tStore('tokens.table.size.class'),         description: $tStore('tokens.table.size.part')         },
      { token: $tStore('tokens.table.motionReduce.token'), value: $tStore('tokens.table.motionReduce.class'), description: $tStore('tokens.table.motionReduce.part') },
    ]}
    customizationTitle={$tStore('tokens.customizationTitle')}
    customizationCode={$tStore('tokens.customizationCode')}
  />

  <!-- ── Acessibilidade ─────────────────────────────────────────── -->
  <DocsAccessibility
    screenReaderTitle={$tNavStore('common.screenReader')}
    screenReaderItems={screenReaderItems}
    title={$tStore('accessibility.title')}
    summary={$tStore('accessibility.summary')}
    items={[
      $tStore('accessibility.items.item1'),
      $tStore('accessibility.items.item2'),
      $tStore('accessibility.items.item3'),
      $tStore('accessibility.items.item4'),
      $tStore('accessibility.items.item5'),
    ]}
    keyboardTitle={$tStore('accessibility.keyboard.title')}
    keyboardItems={[
      { key: '—', description: $tStore('accessibility.keyboard.noKeyboard') },
    ]}
  />

  <!-- ── Relacionados ───────────────────────────────────────────── -->
  <DocsRelated
    title={$tStore('related.title')}
    items={[
      { name: $tStore('related.items.progress.name'),    description: $tStore('related.items.progress.description'),    path: '?path=/docs/ui-progress--docs'    },
      { name: $tStore('related.items.aspectRatio.name'), description: $tStore('related.items.aspectRatio.description'), path: '?path=/docs/ui-aspectratio--docs' },
      { name: $tStore('related.items.card.name'),        description: $tStore('related.items.card.description'),        path: '?path=/docs/ui-card--docs'        },
    ]}
  />

  <!-- ── Notas ──────────────────────────────────────────────────── -->
  <DocsNotes
    title={$tStore('notes.title')}
    items={[
      { title: '', content: $tStore('notes.item1') },
      { title: '', content: $tStore('notes.item2') },
      { title: '', content: $tStore('notes.item3') },
      { title: '', content: $tStore('notes.item4') },
      { title: '', content: $tStore('notes.item5') },
    ]}
  />

  <!-- ── Analytics ─────────────────────────────────────────────── -->
  <DocsAnalytics
    title={$tStore('analytics.title')}
    cols={{
      event: 'Evento',
      trigger: 'Trigger',
      payload: 'Payload',
    }}
    items={[
      { event: '—', trigger: stripHtml($tStore('analytics.description')), payload: '—' },
    ]}
  />

  <!-- ── Testes ─────────────────────────────────────────────────── -->
  <DocsTestes
    title={$tStore('testes.title')}
    functional={{
      title: $tStore('testes.functional.title'),
      cols: {
        action: $tNavStore('common.userAction'),
        result: $tNavStore('common.expectedResult'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { action: toPlainText($tStore('testes.functional.item1.action')), result: toPlainText($tStore('testes.functional.item1.result')), priority: localPriority($tStore('testes.functional.item1.priority'), $tNavStore) },
        { action: toPlainText($tStore('testes.functional.item2.action')), result: toPlainText($tStore('testes.functional.item2.result')), priority: localPriority($tStore('testes.functional.item2.priority'), $tNavStore) },
        { action: toPlainText($tStore('testes.functional.item3.action')), result: toPlainText($tStore('testes.functional.item3.result')), priority: localPriority($tStore('testes.functional.item3.priority'), $tNavStore) },
        { action: toPlainText($tStore('testes.functional.item4.action')), result: toPlainText($tStore('testes.functional.item4.result')), priority: localPriority($tStore('testes.functional.item4.priority'), $tNavStore) },
        { action: toPlainText($tStore('testes.functional.item5.action')), result: toPlainText($tStore('testes.functional.item5.result')), priority: localPriority($tStore('testes.functional.item5.priority'), $tNavStore) },
      ],
    }}
    accessibility={{
      title: $tStore('testes.accessibility.title'),
      cols: {
        criterion: $tNavStore('common.criterion'),
        level: 'WCAG',
        how: $tNavStore('common.howToVerify'),
      },
      items: [
        { criterion: toPlainText($tStore('testes.accessibility.item1')), level: 'AA',    how: 'axe-core' },
        { criterion: toPlainText($tStore('testes.accessibility.item2')), level: '4.1.2', how: 'DevTools a11y tree' },
        { criterion: toPlainText($tStore('testes.accessibility.item3')), level: '4.1.2', how: 'DevTools a11y tree' },
        { criterion: toPlainText($tStore('testes.accessibility.item4')), level: '2.3.3', how: 'prefers-reduced-motion' },
        // Não é critério da WCAG: o esqueleto não transmite informação, então
        // 1.4.3 e 1.4.11 não se aplicam. O que se mede é luminância.
        { criterion: toPlainText($tStore('testes.accessibility.item5')), level: '—', how: 'Medição de luminância' },
      ],
    }}
    visual={{
      title: $tStore('testes.visual.title'),
      cols: {
        story: $tNavStore('common.storyState'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { story: $tStore('testes.visual.item1.story'), priority: localPriority($tStore('testes.visual.item1.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item2.story'), priority: localPriority($tStore('testes.visual.item2.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item3.story'), priority: localPriority($tStore('testes.visual.item3.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item4.story'), priority: localPriority($tStore('testes.visual.item4.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item5.story'), priority: localPriority($tStore('testes.visual.item5.priority'), $tNavStore) },
      ],
    }}
  />
</DocsPageLayout>
