// design-system-svelte/src/components/ui/drawer/drawer-header.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "@/lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="drawer-header"
	class={cn("nds-drawer-header", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// design-system-vue/src/components/ui/drawer/DrawerHeader.vue
<script lang="ts" setup>
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <div
    data-slot="drawer-header"
    :class="cn('nds-drawer-header', props.class)"
  >
    <slot />
  </div>
</template>
