// nortear-design-system-svelte/src/components/ui/sidebar/sidebar-menu-sub-button.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "@/lib/utils.js";
	import type { Snippet } from "svelte";
	import type { HTMLAnchorAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		children,
		child,
		class: className,
		size = "md",
		isActive = false,
		...restProps
	}: WithElementRef<HTMLAnchorAttributes> & {
		child?: Snippet<[{ props: Record<string, unknown> }]>;
		size?: "sm" | "md";
		isActive?: boolean;
	} = $props();

	const mergedProps = $derived({
		class: cn(
			"nds-sidebar-menu-sub-button",
			className
		),
		"data-slot": "sidebar-menu-sub-button",
		"data-sidebar": "menu-sub-button",
		"data-size": size,
		// "true" quando ativo e ausente quando não: é a forma que a folha
		// compartilhada casa, e a mesma que as outras implementações emitem.
		"data-active": isActive ? "true" : undefined,
		...restProps,
	});
</script>

{#if child}
	{@render child({ props: mergedProps })}
{:else}
	<a bind:this={ref} {...mergedProps}>
		{@render children?.()}
	</a>
{/if}

// nortear-design-system-vue/src/components/ui/sidebar/SidebarMenuSubButton.vue
<script setup lang="ts">
import type { PrimitiveProps } from 'reka-ui'
import type { HTMLAttributes } from 'vue'
import { Primitive } from 'reka-ui'
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<PrimitiveProps & {
  size?: 'sm' | 'md'
  isActive?: boolean
  class?: HTMLAttributes['class']
}>(), {
  as: 'a',
  size: 'md',
})
</script>

<template>
  <!--
    data-active vale "true" (e some quando inativo), nunca o atributo vazio:
    é a forma que a folha compartilhada casa e a que as demais implementações
    do design system emitem.
  -->
  <Primitive
    data-slot="sidebar-menu-sub-button"
    data-sidebar="menu-sub-button"
    :as="as"
    :as-child="asChild"
    :data-size="size"
    :data-active="isActive ? 'true' : undefined"
    :class="cn('nds-sidebar-menu-sub-button', props.class)"
  >
    <slot />
  </Primitive>
</template>
