// nortear-design-system-angular/src/components/docs/SliderDocs.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  OnDestroy,
  viewChild,
  TemplateRef,
  signal,
  ViewEncapsulation,
} from '@angular/core';
import { applySeo } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { useTranslation, getLocale } from '@/lib/i18n';
import { createActiveSectionObserver } from '@/lib/use-active-section';
import { stripHtml, toPlainText } from '@/lib/strip-html';
import { NdsSlider } from '@/components/ui/slider';
import { NdsLabel } from '@/components/ui/label';
import uiTranslations from '@/i18n/ui.json';
import sliderTranslations from '@shared/content/slider/translations.json';

import {
  NdsDocsPageLayout,
  NdsDocsHeader,
  NdsDocsDemonstration,
  NdsDocsAnatomy,
  NdsDocsWhenToUse,
  NdsDocsDoDont,
  NdsDocsImport,
  NdsDocsVariants,
  NdsDocsCompositions,
  NdsDocsStates,
  NdsDocsProps,
  NdsDocsTokens,
  NdsDocsAccessibility,
  NdsDocsRelated,
  NdsDocsNotes,
  NdsDocsAnalytics,
  NdsDocsTestes,
} from '@/components/docs/shared/sections';

const { t: tNav } = useTranslation(uiTranslations as Record<string, unknown>);

// Sobrescritas locais. Todas por motivo declarado — nenhuma por gosto.
const { t, dict } = useTranslation(sliderTranslations as Record<string, unknown>, {
  '*': {
    // Prop do primitivo: `valueChange` é o output do Radix NG.
    'props.table.onValueChange.type': 'output<number[]>',
    'props.table.onValueCommitted.type': 'output<number[]>',
  },
  'pt-BR': {
    // O conteúdo compartilhado lista as libs de cada stack pelo nome. Cada
    // documentação é lida isoladamente, então a comparação não faz sentido aqui.
    'notes.item1':
      '<strong>Lib upstream</strong>: <code>@radix-ng/primitives</code> — teclado, arraste e múltiplos thumbs vêm dela.',
    // `h-40` é classe de utilitário de uma lib que saiu do projeto.
    'notes.item4':
      '<strong>Vertical</strong> — o trilho ocupa a altura do container; sem altura definida ele usa a altura mínima da própria regra.',
    'accessibility.items.item5': 'Anel de foco visível na alça, com o token <code>--ring</code>',
  },
  en: {
    'notes.item1':
      '<strong>Upstream library</strong>: <code>@radix-ng/primitives</code> — keyboard, dragging and multiple thumbs come from it.',
    'notes.item4':
      '<strong>Vertical</strong> — the track fills the container height; with no height set it falls back to the rule’s own minimum.',
    'accessibility.items.item5': 'Visible focus ring on the thumb, using the <code>--ring</code> token',
  },
  es: {
    'notes.item1':
      '<strong>Librería upstream</strong>: <code>@radix-ng/primitives</code> — teclado, arrastre y múltiples thumbs vienen de ella.',
    'notes.item4':
      '<strong>Vertical</strong> — el riel ocupa la altura del contenedor; sin altura definida usa el mínimo de la propia regla.',
    'accessibility.items.item5': 'Anillo de foco visible en el thumb, con el token <code>--ring</code>',
  },
});

/**
 * Rótulo de navegação, com queda para o ui.json.
 *
 * Nem todo componente declara a lista de nav inteira no próprio JSON: o
 * slider não tem nav.compositions. Sem a queda, o que aparece na barra
 * lateral é a chave crua.
 */
function rotuloDeNav(chave: string): string {
  const doComponente = t(chave);
  return doComponente === chave ? tNav(chave) : doComponente;
}

const SECTION_IDS = [
  'demonstracao', 'anatomia', 'quando-usar', 'do-dont',
  'importacao', 'variantes', 'composicoes', 'estados', 'propriedades', 'tokens',
  'acessibilidade', 'relacionados', 'notas', 'analytics', 'testes',
] as const;

const NAV_GROUPS: { labelKey: string; sections: { id: string; labelKey: string }[] }[] = [
  { labelKey: 'nav.overview', sections: [
    { id: 'demonstracao', labelKey: 'nav.demonstration' },
    { id: 'anatomia',     labelKey: 'nav.anatomy'       },
    { id: 'quando-usar',  labelKey: 'nav.usage'         },
    { id: 'do-dont',      labelKey: 'nav.doDont'        },
  ]},
  { labelKey: 'nav.techRef', sections: [
    { id: 'importacao',   labelKey: 'nav.import'   },
    { id: 'variantes',    labelKey: 'nav.variants' },
    { id: 'composicoes',  labelKey: 'nav.compositions' },
    { id: 'estados',      labelKey: 'nav.states'   },
    { id: 'propriedades', labelKey: 'nav.props'    },
    { id: 'tokens',       labelKey: 'nav.tokens'   },
  ]},
  { labelKey: 'nav.context', sections: [
    { id: 'acessibilidade', labelKey: 'nav.accessibility' },
    { id: 'relacionados',   labelKey: 'nav.related'       },
    { id: 'notas',          labelKey: 'nav.notes'         },
  ]},
  { labelKey: 'nav.quality', sections: [
    { id: 'analytics', labelKey: 'nav.analytics' },
    { id: 'testes',    labelKey: 'nav.testes'    },
  ]},
];

const INTERFACE_CODE = `// <div ndsSlider> — o consumidor escreve UM elemento.
// As cinco partes internas (control, track, range, thumb, input) nascem do
// template, e a quantidade de alças vem do tamanho de \`value\`.
@Component({
  selector: 'div[ndsSlider]',
  hostDirectives: [
    { directive: RdxSliderRoot,
      inputs: ['value', 'min', 'max', 'step', 'disabled',
               'orientation', 'minStepsBetweenValues'],
      outputs: ['valueChange'] },
  ],
})
export class NdsSlider {
  readonly ariaLabel = input<string | undefined>(undefined, { alias: 'aria-label' });
  readonly thumbLabels = input<readonly string[]>([]);
}

// Uso com Reactive Forms:
// <div ndsSlider formControlName="volume" aria-label="Volume"></div>`;

// A anatomia do conteúdo compartilhado descreve `<nds-slider />`, elemento que
// não existe: aqui o seletor é de atributo, para o markup ficar idêntico ao das
// outras stacks. Mesmo precedente do Card e do Checkbox.
const ANATOMY_CODE = `<!-- valor = signal([50]) -->
<div
  ndsSlider
  [(value)]="valor"
  [min]="0"
  [max]="100"
  [step]="1"
  aria-label="Volume"
></div>

<!-- Intervalo: dois valores, duas alças, um rótulo para cada -->
<div
  ndsSlider
  [(value)]="faixa"
  [thumbLabels]="['Preço mínimo', 'Preço máximo']"
></div>`;

// O snippet compartilhado ensina `@apply`, de uma lib que saiu do projeto.
const CUSTOMIZATION_CODE = `/* Cor do preenchimento por contexto, via token */
.tema-sucesso {
  --primary: 142 71% 45%;
}

/* O tamanho da alça é medida sem texto: mora no CSS compartilhado,
   na escada de 8px — não em style inline. */
.nds-slider-thumb {
  inline-size: var(--spacing-5);
  block-size: var(--spacing-5);
}`;

@Component({
  selector: 'nds-slider-docs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [
    NdsSlider, NdsLabel,
    NdsDocsPageLayout, NdsDocsHeader, NdsDocsDemonstration, NdsDocsAnatomy,
    NdsDocsWhenToUse, NdsDocsDoDont, NdsDocsImport, NdsDocsVariants,
    NdsDocsCompositions, NdsDocsStates, NdsDocsProps, NdsDocsTokens,
    NdsDocsAccessibility, NdsDocsRelated, NdsDocsNotes, NdsDocsAnalytics,
    NdsDocsTestes,
  ],
  template: `
    <ng-template #tplDoDont1Do>
      <div class="nds-stack nds-w-full" data-spacing="sm">
        <div class="nds-cluster" data-justify="between">
          <label ndsLabel for="dd1-do">{{ t('demonstration.labels.volume') }}</label>
          <span class="nds-text-caption nds-tabular-nums" aria-live="polite">60%</span>
        </div>
        <div
          ndsSlider
          id="dd1-do"
          [value]="[60]"
          [aria-label]="t('demonstration.labels.volume')"
        ></div>
      </div>
    </ng-template>
    <ng-template #tplDoDont1Dont>
      <div class="nds-stack nds-w-full" data-spacing="sm">
        <div
          ndsSlider
          [value]="[60]"
          [aria-label]="t('demonstration.labels.volume')"
        ></div>
      </div>
    </ng-template>

    <ng-template #tplDoDont2Do>
      <div class="nds-stack nds-w-full" data-spacing="sm">
        <label ndsLabel>{{ t('demonstration.labels.brightness') }}</label>
        <div
          ndsSlider
          [value]="[40]"
          [step]="5"
          [aria-label]="t('demonstration.labels.brightness')"
        ></div>
      </div>
    </ng-template>
    <ng-template #tplDoDont2Dont>
      <div class="nds-stack nds-w-full" data-spacing="sm">
        <label ndsLabel>{{ t('demonstration.labels.brightness') }}</label>
        <div
          ndsSlider
          [value]="[40]"
          [min]="0"
          [max]="1000"
          [step]="1"
          [aria-label]="t('demonstration.labels.brightness')"
        ></div>
      </div>
    </ng-template>

    <ng-template #tplVarSingle>
      <div
        ndsSlider
        class="nds-w-full"
        [value]="[50]"
        [aria-label]="t('demonstration.labels.volume')"
      ></div>
    </ng-template>
    <ng-template #tplVarRange>
      <div
        ndsSlider
        class="nds-w-full"
        [value]="[20, 80]"
        [thumbLabels]="rotulosDaFaixa()"
      ></div>
    </ng-template>
    <ng-template #tplVarVertical>
      <div
        ndsSlider
        orientation="vertical"
        [value]="[60]"
        [aria-label]="t('demonstration.labels.vertical')"
      ></div>
    </ng-template>

    <ng-template #tplCompVolume>
      <div class="nds-stack nds-w-full" data-spacing="sm">
        <div class="nds-cluster" data-justify="between">
          <label ndsLabel for="comp-vol">{{ t('demonstration.labels.volume') }}</label>
          <span class="nds-text-caption nds-tabular-nums" aria-live="polite">70%</span>
        </div>
        <div
          ndsSlider
          id="comp-vol"
          [value]="[70]"
          [aria-label]="t('demonstration.labels.volume')"
        ></div>
      </div>
    </ng-template>
    <ng-template #tplCompPriceRange>
      <div class="nds-stack nds-w-full" data-spacing="sm">
        <label ndsLabel>{{ t('demonstration.labels.priceRange') }}</label>
        <div ndsSlider [value]="[20, 80]" [thumbLabels]="rotulosDaFaixa()"></div>
      </div>
    </ng-template>
    <ng-template #tplCompBrightness>
      <div class="nds-stack nds-w-full" data-spacing="sm">
        <label ndsLabel>{{ t('demonstration.labels.brightness') }}</label>
        <div
          ndsSlider
          [value]="[35]"
          [step]="5"
          [aria-label]="t('demonstration.labels.brightness')"
        ></div>
      </div>
    </ng-template>

    <nds-docs-page-layout
      [navGroups]="navGroups()"
      [activeSection]="activeSection()"
      componentSlug="slider"
    >
      <div docsHeader>
        <nds-docs-header
          [title]="t('title')"
          [description]="t('description')"
          [category]="t('category')"
          [type]="t('type')"
        />
      </div>

      <ng-container docsMain>
        <nds-docs-demonstration [title]="t('demonstration.title')">
          <div class="nds-stack nds-w-full" data-spacing="lg">
            <div class="nds-stack" data-spacing="sm">
              <label ndsLabel for="demo-single">{{ t('demonstration.labels.single') }}</label>
              <div
                ndsSlider
                id="demo-single"
                [value]="[50]"
                [aria-label]="t('demonstration.labels.volume')"
              ></div>
            </div>
            <div class="nds-stack" data-spacing="sm">
              <label ndsLabel>{{ t('demonstration.labels.range') }}</label>
              <div ndsSlider [value]="[20, 80]" [thumbLabels]="rotulosDaFaixa()"></div>
            </div>
            <div class="nds-stack" data-spacing="sm">
              <label ndsLabel for="demo-disabled">{{ t('states.disabled.label') }}</label>
              <div
                ndsSlider
                id="demo-disabled"
                [value]="[45]"
                [disabled]="true"
                [aria-label]="t('demonstration.labels.volume')"
              ></div>
            </div>
          </div>
        </nds-docs-demonstration>

        <nds-docs-anatomy
          [title]="t('anatomy.title')"
          [items]="anatomyItems()"
          [structureCode]="anatomyCode"
          language="html"
        />

        <nds-docs-when-to-use
          [title]="t('usage.title')"
          [guidelines]="guidelines()"
          [scenarios]="scenarios()"
          [uxWriting]="uxWriting()"
          [do]="usageDo()"
          [dont]="usageDont()"
        />

        <nds-docs-do-dont [title]="t('doDont.title')" [pairs]="doDontPairs()" />

        <nds-docs-import
          [title]="tNav('nav.import')"
          [code]="importCode"
          componentSlug="slider"
          language="ts"
        />

        <nds-docs-variants
          [title]="t('variants.title')"
          [items]="variantItems()"
          componentSlug="slider"
          id="variantes"
          language="html"
        />

        <nds-docs-compositions
          [title]="t('variants.compositionsTitle')"
          [items]="compositionItems()"
          [useWhenLabel]="tNav('common.useWhen')"
          componentSlug="slider"
        />

        <nds-docs-states
          [title]="t('states.title')"
          [cols]="statesCols()"
          [items]="stateItems()"
        />

        <nds-docs-props
          [title]="t('props.title')"
          [tables]="propTables()"
          [interfaceCode]="interfaceCode"
          [extensibilityTitle]="t('props.extensibilityTitle')"
          [extensibilityCode]="t('props.extensibilityCode')"
          language="html"
        />

        <nds-docs-tokens
          [title]="t('tokens.title')"
          [cols]="tokensCols()"
          [items]="tokenItems()"
          [customizationTitle]="t('tokens.customizationTitle')"
          [customizationCode]="customizationCode"
        />

        <nds-docs-accessibility
          [title]="t('accessibility.title')"
          [summary]="t('accessibility.summary')"
          [items]="a11yItems()"
          [keyboardTitle]="t('accessibility.keyboard.title')"
          [keyboardItems]="keyboardItems()"
          [screenReaderTitle]="t('accessibility.screenReader.title')"
          [screenReaderItems]="screenReaderItems()"
        />

        <nds-docs-related
          [title]="t('related.title')"
          [items]="relatedItems()"
          componentSlug="slider"
        />

        <nds-docs-notes [title]="t('notes.title')" [items]="noteItems()" componentSlug="slider" />

        <nds-docs-analytics
          [title]="t('analytics.title')"
          [cols]="analyticsCols()"
          [items]="analyticsItems()"
        />

        <nds-docs-testes
          [title]="t('testes.title')"
          [functional]="testesFunctional()"
          [accessibility]="testesAccessibility()"
          [visual]="testesVisual()"
        />
      </ng-container>
    </nds-docs-page-layout>
  `,
})
export class NdsSliderDocs implements AfterViewInit, OnDestroy {
  protected readonly t = t;
  protected readonly tNav = tNav;
  protected readonly interfaceCode = INTERFACE_CODE;
  protected readonly anatomyCode = ANATOMY_CODE;
  protected readonly customizationCode = CUSTOMIZATION_CODE;
  protected readonly importCode = `import { NdsSlider } from '@/components/ui/slider';`;

  protected readonly activeSection = signal<string | undefined>(undefined);

  private readonly tplDoDont1Do = viewChild.required<TemplateRef<unknown>>('tplDoDont1Do');
  private readonly tplDoDont1Dont = viewChild.required<TemplateRef<unknown>>('tplDoDont1Dont');
  private readonly tplDoDont2Do = viewChild.required<TemplateRef<unknown>>('tplDoDont2Do');
  private readonly tplDoDont2Dont = viewChild.required<TemplateRef<unknown>>('tplDoDont2Dont');
  private readonly tplVarSingle = viewChild.required<TemplateRef<unknown>>('tplVarSingle');
  private readonly tplVarRange = viewChild.required<TemplateRef<unknown>>('tplVarRange');
  private readonly tplVarVertical = viewChild.required<TemplateRef<unknown>>('tplVarVertical');
  private readonly tplCompVolume = viewChild.required<TemplateRef<unknown>>('tplCompVolume');
  private readonly tplCompPriceRange = viewChild.required<TemplateRef<unknown>>('tplCompPriceRange');
  private readonly tplCompBrightness = viewChild.required<TemplateRef<unknown>>('tplCompBrightness');

  /**
   * Um rótulo por alça. Repetir "Faixa de preço" nas duas não diz qual delas
   * está em foco — quem só ouve precisa da diferença.
   */
  protected readonly rotulosDaFaixa = computed(() => {
    dict();
    const faixa = t('demonstration.labels.priceRange');
    return [`${faixa} — ${tNav('common.min')}`, `${faixa} — ${tNav('common.max')}`];
  });

  protected readonly navGroups = computed(() => {
    dict();
    return NAV_GROUPS.map((g) => ({
      label: rotuloDeNav(g.labelKey),
      sections: g.sections.map((s) => ({ id: s.id, label: rotuloDeNav(s.labelKey) })),
    }));
  });

  protected readonly anatomyItems = computed(() => {
    const d = dict();
    return Object.keys(d)
      .filter((k) => /^anatomy\.item\d+$/.test(k))
      .sort()
      .map((k) => d[k]);
  });

  protected readonly guidelines = computed(() => {
    const d = dict();
    return {
      title: d['usage.guidelines.title'] ?? '',
      items: Object.keys(d).filter((k) => /^usage\.guidelines\.item\d+$/.test(k)).sort().map((k) => d[k]),
    };
  });

  protected readonly scenarios = computed(() => {
    const d = dict();
    return {
      title: d['usage.scenarios.title'] ?? '',
      cols: {
        scenario: d['usage.scenarios.cols.scenario'] ?? '',
        use: d['usage.scenarios.cols.use'] ?? '',
        alternative: d['usage.scenarios.cols.alternative'] ?? '',
      },
      items: itemsFromDict(d, 'usage.scenarios', ['s', 'u', 'a']),
    };
  });

  protected readonly uxWriting = computed(() => {
    dict();
    return {
      title: t('usage.uxWriting.title'),
      cols: {
        element: t('usage.uxWriting.table.element'),
        rules: t('usage.uxWriting.table.rules'),
        do: t('usage.uxWriting.table.correct'),
        dont: t('usage.uxWriting.table.avoid'),
      },
      items: ['ariaLabel', 'valueDisplay', 'range'].map((k) => ({
        element: toPlainText(t(`usage.uxWriting.table.${k}.name`)),
        rules: toPlainText(t(`usage.uxWriting.table.${k}.format`)),
        do: toPlainText(t(`usage.uxWriting.table.${k}.good`)),
        dont: toPlainText(t(`usage.uxWriting.table.${k}.bad`)),
      })),
    };
  });

  protected readonly usageDo = computed(() => {
    dict();
    return { title: t('usage.do.title'), items: [1, 2, 3, 4].map((i) => t(`usage.do.item${i}`)) };
  });

  protected readonly usageDont = computed(() => {
    dict();
    return { title: t('usage.dont.title'), items: [1, 2, 3, 4].map((i) => t(`usage.dont.item${i}`)) };
  });

  protected readonly doDontPairs = computed(() => {
    dict();
    const pares: [TemplateRef<unknown>, TemplateRef<unknown>][] = [
      [this.tplDoDont1Do(), this.tplDoDont1Dont()],
      [this.tplDoDont2Do(), this.tplDoDont2Dont()],
    ];
    return pares.map(([doTpl, dontTpl], i) => ({
      doLabel: tNav('common.do'),
      dontLabel: tNav('common.dont'),
      doCaption: toPlainText(t(`doDont.pair${i + 1}.do`)),
      dontCaption: toPlainText(t(`doDont.pair${i + 1}.dont`)),
      doPreview: doTpl,
      dontPreview: dontTpl,
    }));
  });

  protected readonly variantItems = computed(() => {
    dict();
    return [
      { name: t('variants.items.single'),   description: t('variants.styles.single'),   trackId: 'single',   preview: this.tplVarSingle()   },
      { name: t('variants.items.range'),    description: t('variants.styles.range'),    trackId: 'range',    preview: this.tplVarRange()    },
      { name: t('variants.items.vertical'), description: t('variants.styles.vertical'), trackId: 'vertical', preview: this.tplVarVertical() },
    ];
  });

  protected readonly compositionItems = computed(() => {
    dict();
    // `brightness` mora sob `variants.items` no conteúdo compartilhado, mas tem
    // a forma de composição (name/description/use) — é aqui que ele pertence.
    const mapa: { base: string; key: string; tpl: TemplateRef<unknown> }[] = [
      { base: 'variants.compositions.volume', key: 'volume',     tpl: this.tplCompVolume()     },
      { base: 'variants.compositions.form',   key: 'form',       tpl: this.tplCompPriceRange() },
      { base: 'variants.items.brightness',    key: 'brightness', tpl: this.tplCompBrightness() },
    ];
    return mapa.map(({ base, key, tpl }) => ({
      name: t(`${base}.name`),
      description: t(`${base}.description`),
      useWhen: t(`${base}.use`),
      trackId: key,
      preview: tpl,
    }));
  });

  protected readonly statesCols = computed(() => {
    dict();
    return {
      state: t('states.cols.state'),
      trigger: t('states.cols.trigger'),
      behavior: t('states.cols.behavior'),
    };
  });

  protected readonly stateItems = computed(() => {
    dict();
    return ['default', 'hover', 'focus', 'active', 'disabled'].map((k) => ({
      label: t(`states.${k}.label`),
      trigger: toPlainText(t(`states.${k}.trigger`)),
      behavior: toPlainText(t(`states.${k}.behavior`)),
    }));
  });

  protected readonly propTables = computed(() => {
    dict();
    const cols = {
      prop: t('props.table.prop'),
      type: t('props.table.type'),
      default: t('props.table.default'),
      required: t('props.table.required'),
      description: t('props.table.description'),
    };
    const nao = tNav('common.no');
    const linha = (name: string, key: string, tipo: string, padrao: string) => ({
      name,
      type: tipo,
      defaultValue: padrao,
      required: nao,
      description: toPlainText(t(`props.table.${key}.description`)),
    });
    return [
      {
        title: 'NdsSlider',
        cols,
        items: [
          linha('value', 'value', 'model<number[]>', '[min, max]'),
          linha('valueChange', 'onValueChange', 'output<number[]>', '—'),
          linha('min', 'min', 'number', '0'),
          linha('max', 'max', 'number', '100'),
          linha('step', 'step', 'number', '1'),
          linha('orientation', 'orientation', `'horizontal' | 'vertical'`, `'horizontal'`),
          linha('disabled', 'disabled', 'boolean', 'false'),
          {
            name: 'aria-label',
            type: 'string',
            defaultValue: '—',
            required: nao,
            // Não vem do conteúdo compartilhado: é uma entrada deste stack, e a
            // razão de existir é a seção de acessibilidade acima.
            description: toPlainText(t('accessibility.aria.label')),
          },
          {
            name: 'thumbLabels',
            type: 'string[]',
            defaultValue: '[]',
            required: nao,
            description: toPlainText(t('usage.uxWriting.table.range.format')),
          },
        ],
      },
    ];
  });

  protected readonly tokensCols = computed(() => {
    dict();
    return {
      token: t('tokens.table.token'),
      value: t('tokens.table.class'),
      description: t('tokens.table.part'),
    };
  });

  protected readonly tokenItems = computed(() => {
    dict();
    return ['muted', 'primary', 'ring', 'background', 'foreground', 'mutedForeground'].map((k) => ({
      token: `--${k.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())}`,
      value: toPlainText(t(`tokens.table.${k}.class`)),
      description: toPlainText(t(`tokens.table.${k}.part`)),
    }));
  });

  protected readonly a11yItems = computed(() => {
    const d = dict();
    // A seção genérica não tem faixa própria para ARIA; as duas listas dizem a
    // mesma coisa em graus diferentes de detalhe, então saem juntas.
    const itens = Object.keys(d).filter((k) => /^accessibility\.items\.item\d+$/.test(k)).sort().map((k) => d[k]);
    const aria = ['role', 'valuenow', 'valuemin', 'valuemax', 'orientation'].map((k) =>
      t(`accessibility.aria.${k}`),
    );
    return [...itens, ...aria];
  });

  protected readonly keyboardItems = computed(() => {
    dict();
    return [
      { key: 'Tab',       description: toPlainText(t('accessibility.keyboard.tab')) },
      { key: '→',         description: toPlainText(t('accessibility.keyboard.arrowRight')) },
      { key: '←',         description: toPlainText(t('accessibility.keyboard.arrowLeft')) },
      { key: '↑',         description: toPlainText(t('accessibility.keyboard.arrowUp')) },
      { key: '↓',         description: toPlainText(t('accessibility.keyboard.arrowDown')) },
      { key: 'Home',      description: toPlainText(t('accessibility.keyboard.home')) },
      { key: 'End',       description: toPlainText(t('accessibility.keyboard.end')) },
      { key: 'Page Up',   description: toPlainText(t('accessibility.keyboard.pageUp')) },
      { key: 'Page Down', description: toPlainText(t('accessibility.keyboard.pageDown')) },
    ];
  });

  protected readonly screenReaderItems = computed(() => {
    dict();
    return ['thumb', 'change', 'limits'].map((k) => t(`accessibility.screenReader.${k}`));
  });

  protected readonly relatedItems = computed(() => {
    dict();
    return [
      { key: 'input',      path: '?path=/docs/ui-input--docs'     },
      { key: 'switch',     path: '?path=/docs/ui-switch--docs'    },
      { key: 'progress',   path: '?path=/docs/ui-progress--docs'  },
      { key: 'radioGroup', path: '?path=/docs/ui-radiogroup--docs' },
    ].map(({ key, path }) => ({
      name: t(`related.items.${key}.name`),
      description: t(`related.items.${key}.description`),
      path,
    }));
  });

  protected readonly noteItems = computed(() => {
    dict();
    return [1, 2, 3, 4].map((i) => ({ title: '', content: t(`notes.item${i}`) }));
  });

  protected readonly analyticsCols = computed(() => {
    dict();
    return {
      event: t('analytics.table.event'),
      trigger: t('analytics.table.trigger'),
      payload: t('analytics.table.payload'),
    };
  });

  protected readonly analyticsItems = computed(() => {
    dict();
    return [
      {
        event: 'slider_change',
        trigger: toPlainText(t('analytics.table.slider_change.trigger')),
        payload: toPlainText(t('analytics.table.slider_change.payload')),
      },
    ];
  });

  protected readonly testesFunctional = computed(() => {
    const d = dict();
    return {
      title: t('testes.functional.title'),
      description: t('testes.functional.description'),
      cols: {
        action: tNav('common.userAction'),
        result: tNav('common.expectedResult'),
        priority: tNav('common.priority'),
      },
      items: itemsFromDict(d, 'testes.functional', ['action', 'result', 'priority']).map((r) => ({
        action: toPlainText(r.action),
        result: stripHtml(toPlainText(r.result)),
        priority: priorityLabel(r.priority),
      })),
    };
  });

  protected readonly testesAccessibility = computed(() => {
    const d = dict();
    // Aqui os itens são string solta, não a trinca criterion/level/how.
    const itens = Object.keys(d)
      .filter((k) => /^testes\.accessibility\.item\d+$/.test(k))
      .sort()
      .map((k) => ({ criterion: toPlainText(d[k]), level: '', how: '' }));
    return {
      title: t('testes.accessibility.title'),
      description: t('testes.accessibility.description'),
      cols: { criterion: tNav('common.criterion'), level: 'WCAG', how: tNav('common.howToVerify') },
      items: itens,
    };
  });

  protected readonly testesVisual = computed(() => {
    const d = dict();
    return {
      title: t('testes.visual.title'),
      description: t('testes.visual.description'),
      cols: { story: tNav('common.storyState'), priority: tNav('common.priority') },
      items: itemsFromDict(d, 'testes.visual', ['story', 'priority']).map((r) => ({
        story: toPlainText(r.story),
        priority: priorityLabel(r.priority),
      })),
    };
  });

  private observer: { disconnect: () => void } | undefined;

  constructor() {
    effect((onCleanup) => {
      dict();
      const locale = getLocale();
      const cleanup = applySeo({
        title: t('seo.title'),
        description: t('seo.description'),
        locale,
        componentSlug: 'slider',
      });
      track('docs_page_view', {
        component_name: 'slider',
        locale,
        page_title: `${t('title')} · Design System`,
      });
      onCleanup(cleanup);
    });
  }

  ngAfterViewInit(): void {
    this.observer = createActiveSectionObserver(
      [...SECTION_IDS],
      (id) => document.getElementById(id),
      (id) => this.activeSection.set(id),
      (id) =>
        track('docs_section_viewed', {
          component_name: 'slider',
          section_id: id,
          locale: getLocale(),
        }),
    );
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }
}

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function priorityLabel(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

function itemsFromDict<K extends string>(
  d: Record<string, string>,
  base: string,
  fields: readonly K[],
): Record<K, string>[] {
  const rows: Record<K, string>[] = [];
  for (let i = 1; ; i++) {
    if (d[`${base}.item${i}.${fields[0]}`] === undefined) break;
    const row = {} as Record<K, string>;
    for (const f of fields) row[f] = d[`${base}.item${i}.${f}`] ?? '';
    rows.push(row);
  }
  return rows;
}

// design-system-svelte/src/components/docs/SliderDocs.svelte
<script lang="ts">
  import { Slider } from '@/components/ui/slider';
  import { Label } from '@/components/ui/label';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader, DocsDemonstration, DocsAnatomy, DocsWhenToUse, DocsDoDont,
    DocsImport, DocsVariants, DocsStates, DocsProps, DocsTokens,
    DocsAccessibility, DocsRelated, DocsNotes, DocsAnalytics, DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import sliderTranslations from '@shared/content/slider/translations.json';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(sliderTranslations);

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'slider',
      aiSummary: t('seo.aiSummary'),
      aiEntities: t('seo.aiEntities'),
      aiIntent: (t('seo.aiIntent') as 'informational' | 'navigational') ?? 'informational',
      breadcrumb: [
        { name: 'Components', item: '/components' },
        { name: t('category'), item: '/components/form' },
        { name: t('title') },
      ],
    });
    track('docs_page_view', {
      component_name: 'slider',
      locale: l,
      page_title: `${t('title')} · Design System`,
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────

  let activeSection = $state('demonstracao');

  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')   },
        { id: 'variantes',    label: tNav('nav.variants') },
        { id: 'estados',      label: tNav('nav.states')   },
        { id: 'propriedades', label: tNav('nav.props')    },
        { id: 'tokens',       label: tNav('nav.tokens')   },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  $effect(() => {
    const ids = NAV_GROUPS.flatMap(g => g.sections.map(s => s.id));
    const observer = new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          activeSection = entry.target.id;
          track('docs_section_viewed', { section_id: entry.target.id, component_name: 'slider', locale: $locale });
          break;
        }
      }
    }, { rootMargin: '-20% 0px -70% 0px', threshold: 0 });
    for (const id of ids) {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    }
    return () => observer.disconnect();
  });

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  function stripHtml(s: string) {
    return s.replace(/<[^>]*>/g, '');
  }

  const priorityKeyMap: Record<string, string> = { high: 'common.high', medium: 'common.medium', low: 'common.low' };
  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  // ─── Demo state ──────────────────────────────────────────────────────────────

  let demoVolume = $state<number[]>([50]);
  let demoBrightness = $state<number[]>([70]);
  let demoPriceRange = $state<number[]>([100, 400]);

  // ─── Code strings ────────────────────────────────────────────────────────────

  const codeImport = `import { Slider } from "@/components/ui/slider";`;

  const codeSingle = `<script lang="ts">
  let value = $state([50]);
<\/script>

<Slider bind:value min={0} max={100} step={1} aria-label="Volume" />`;

  const codeRange = `<script lang="ts">
  let value = $state([20, 80]);
<\/script>

<Slider bind:value min={0} max={100} step={1} aria-label="Faixa de preço" />`;

  const codeVertical = `<div class="h-40 flex justify-center">
  <Slider
    bind:value
    orientation="vertical"
    min={0}
    max={100}
    aria-label="Brilho"
  />
</div>`;

  const interfaceCode = `// Slider (root, bits-ui)
interface SliderProps {
  value?: number[];        // SEMPRE array, mesmo single
  defaultValue?: number[];
  min?: number;            // 0
  max?: number;            // 100
  step?: number;           // 1
  orientation?: 'horizontal' | 'vertical';
  disabled?: boolean;
  onValueChange?: (v: number[]) => void;
  onValueCommit?: (v: number[]) => void;
  'aria-label': string;    // obrigatório
  class?: string;
}`;
</script>

<DocsPageLayout navGroups={NAV_GROUPS} {activeSection}>
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
      installNote="npx shadcn-svelte@latest add slider"
    />
  {/snippet}

  <!-- ── Demonstração ───────────────────────────────────────────── -->
  <DocsDemonstration title={$tStore('demonstration.title')}>
    {#snippet children()}
      <div class="w-full grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Single — Volume -->
        <div class="space-y-2">
          <p class="text-xs font-medium text-muted-foreground">{$tStore('demonstration.labels.single')}</p>
          <div class="p-4 border rounded-md space-y-3">
            <div class="flex items-center justify-between">
              <Label>{$tStore('demonstration.labels.volume')}</Label>
              <span class="text-sm tabular-nums" aria-live="polite">{demoVolume[0]}%</span>
            </div>
            <Slider
              bind:value={demoVolume}
              min={0}
              max={100}
              step={1}
              aria-label={$tStore('demonstration.labels.volume')}
            />
          </div>
        </div>

        <!-- Range — Preço -->
        <div class="space-y-2">
          <p class="text-xs font-medium text-muted-foreground">{$tStore('demonstration.labels.range')}</p>
          <div class="p-4 border rounded-md space-y-3">
            <div class="flex items-center justify-between">
              <Label>{$tStore('demonstration.labels.priceRange')}</Label>
              <span class="text-sm tabular-nums" aria-live="polite">
                R$ {demoPriceRange[0]} — R$ {demoPriceRange[1]}
              </span>
            </div>
            <Slider
              bind:value={demoPriceRange}
              min={0}
              max={500}
              step={10}
              aria-label={$tStore('demonstration.labels.priceRange')}
            />
          </div>
        </div>

        <!-- Vertical — Brilho -->
        <div class="space-y-2">
          <p class="text-xs font-medium text-muted-foreground">{$tStore('demonstration.labels.vertical')}</p>
          <div class="p-4 border rounded-md space-y-3">
            <div class="flex items-center justify-between w-40">
              <Label>{$tStore('demonstration.labels.brightness')}</Label>
              <span class="text-sm tabular-nums" aria-live="polite">{demoBrightness[0]}%</span>
            </div>
            <div class="h-40 flex justify-center">
              <Slider
                bind:value={demoBrightness}
                orientation="vertical"
                min={0}
                max={100}
                step={1}
                aria-label={$tStore('demonstration.labels.brightness')}
              />
            </div>
          </div>
        </div>

        <!-- Disabled -->
        <div class="space-y-2">
          <p class="text-xs font-medium text-muted-foreground">Disabled</p>
          <div class="p-4 border rounded-md space-y-3">
            <div class="flex items-center justify-between">
              <Label>{$tStore('demonstration.labels.volume')}</Label>
              <span class="text-sm tabular-nums">30%</span>
            </div>
            <Slider value={[30]} min={0} max={100} disabled aria-label={$tStore('demonstration.labels.volume')} />
          </div>
        </div>
      </div>
    {/snippet}
  </DocsDemonstration>

  <!-- ── Anatomia ───────────────────────────────────────────────── -->
  <DocsAnatomy
    title={$tStore('anatomy.title')}
    items={[
      $tStore('anatomy.item1'),
      $tStore('anatomy.item2'),
      $tStore('anatomy.item3'),
      $tStore('anatomy.item4'),
      $tStore('anatomy.item5'),
    ]}
    structureLabel={$tStore('anatomy.structureLabel')}
    structureCode={$tStore('anatomy.structureCode')}
  />

  <!-- ── Quando Usar ────────────────────────────────────────────── -->
  <DocsWhenToUse
    title={$tStore('usage.title')}
    guidelines={{
      title: $tStore('usage.guidelines.title'),
      items: [
        $tStore('usage.guidelines.item1'),
        $tStore('usage.guidelines.item2'),
        $tStore('usage.guidelines.item3'),
        $tStore('usage.guidelines.item4'),
      ],
    }}
    scenarios={{
      title: $tStore('usage.scenarios.title'),
      cols: {
        scenario: $tStore('usage.scenarios.cols.scenario'),
        use: $tStore('usage.scenarios.cols.use'),
        alternative: $tStore('usage.scenarios.cols.alternative'),
      },
      items: [
        { s: $tStore('usage.scenarios.item1.s'), u: $tStore('usage.scenarios.item1.u'), a: $tStore('usage.scenarios.item1.a') },
        { s: $tStore('usage.scenarios.item2.s'), u: $tStore('usage.scenarios.item2.u'), a: $tStore('usage.scenarios.item2.a') },
        { s: $tStore('usage.scenarios.item3.s'), u: $tStore('usage.scenarios.item3.u'), a: $tStore('usage.scenarios.item3.a') },
        { s: $tStore('usage.scenarios.item4.s'), u: $tStore('usage.scenarios.item4.u'), a: $tStore('usage.scenarios.item4.a') },
        { s: $tStore('usage.scenarios.item5.s'), u: $tStore('usage.scenarios.item5.u'), a: $tStore('usage.scenarios.item5.a') },
      ],
    }}
    uxWriting={{
      title: $tStore('usage.uxWriting.title'),
      cols: {
        element: $tStore('usage.uxWriting.table.element'),
        rules: $tStore('usage.uxWriting.table.rules'),
        do: $tStore('usage.uxWriting.table.correct'),
        dont: $tStore('usage.uxWriting.table.avoid'),
      },
      items: [
        { element: $tStore('usage.uxWriting.table.ariaLabel.name'),    rules: $tStore('usage.uxWriting.table.ariaLabel.format'),    do: $tStore('usage.uxWriting.table.ariaLabel.good'),    dont: $tStore('usage.uxWriting.table.ariaLabel.bad') },
        { element: $tStore('usage.uxWriting.table.valueDisplay.name'), rules: $tStore('usage.uxWriting.table.valueDisplay.format'), do: $tStore('usage.uxWriting.table.valueDisplay.good'), dont: $tStore('usage.uxWriting.table.valueDisplay.bad') },
        { element: $tStore('usage.uxWriting.table.range.name'),        rules: $tStore('usage.uxWriting.table.range.format'),        do: $tStore('usage.uxWriting.table.range.good'),        dont: $tStore('usage.uxWriting.table.range.bad') },
      ],
    }}
    do={{
      title: $tStore('usage.do.title'),
      items: [
        $tStore('usage.do.item1'),
        $tStore('usage.do.item2'),
        $tStore('usage.do.item3'),
        $tStore('usage.do.item4'),
      ],
    }}
    dont={{
      title: $tStore('usage.dont.title'),
      items: [
        $tStore('usage.dont.item1'),
        $tStore('usage.dont.item2'),
        $tStore('usage.dont.item3'),
        $tStore('usage.dont.item4'),
      ],
    }}
  />

  <!-- ── Do & Don't ─────────────────────────────────────────────── -->
  <DocsDoDont
    title={$tStore('doDont.title')}
    pairs={[
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair1.do'),
        dontCaption: $tStore('doDont.pair1.dont'),
        doPreview: doPair1,
        dontPreview: dontPair1,
      },
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair2.do'),
        dontCaption: $tStore('doDont.pair2.dont'),
        doPreview: doPair2,
        dontPreview: dontPair2,
      },
    ]}
  />

  {#snippet doPair1()}
    <div class="w-full space-y-2">
      <div class="flex items-center justify-between">
        <Label>Volume</Label>
        <span class="text-sm tabular-nums" aria-live="polite">60%</span>
      </div>
      <Slider value={[60]} min={0} max={100} aria-label="Volume" />
    </div>
  {/snippet}
  {#snippet dontPair1()}
    <div class="w-full space-y-2">
      <Label>Volume</Label>
      <Slider value={[60]} min={0} max={100} aria-label="Volume" />
    </div>
  {/snippet}
  {#snippet doPair2()}
    <div class="w-full">
      <Slider value={[60]} min={0} max={100} aria-label="Volume" />
    </div>
  {/snippet}
  {#snippet dontPair2()}
    <div class="w-full">
      <Slider value={[60]} min={0} max={100} aria-label="Slider" />
    </div>
  {/snippet}

  <!-- ── Importação ─────────────────────────────────────────────── -->
  <DocsImport title={$tStore('import.title')} code={codeImport} />

  <!-- ── Variantes ──────────────────────────────────────────────── -->
  <DocsVariants
    title={$tStore('variants.title')}
    items={[
      { name: $tStore('variants.items.single'),   description: stripHtml($tStore('variants.styles.single')),   code: codeSingle,   preview: variantSingle   },
      { name: $tStore('variants.items.range'),    description: stripHtml($tStore('variants.styles.range')),    code: codeRange,    preview: variantRange    },
      { name: $tStore('variants.items.vertical'), description: stripHtml($tStore('variants.styles.vertical')), code: codeVertical, preview: variantVertical },
    ]}
  />

  {#snippet variantSingle()}
    <div class="w-64">
      <Slider value={[50]} min={0} max={100} aria-label="Volume" />
    </div>
  {/snippet}
  {#snippet variantRange()}
    <div class="w-64">
      <Slider value={[20, 80]} min={0} max={100} aria-label="Faixa" />
    </div>
  {/snippet}
  {#snippet variantVertical()}
    <div class="h-40 flex justify-center">
      <Slider value={[50]} orientation="vertical" min={0} max={100} aria-label="Brilho" />
    </div>
  {/snippet}

  <!-- ── Estados ────────────────────────────────────────────────── -->
  <DocsStates
    title={$tStore('states.title')}
    cols={{
      state: $tStore('states.title'),
      trigger: 'Trigger',
      behavior: $tStore('usage.scenarios.cols.scenario'),
    }}
    items={[
      { label: $tStore('states.items.default'),  trigger: '—',         behavior: stripHtml($tStore('states.descriptions.default'))  },
      { label: $tStore('states.items.hover'),    trigger: 'mouseover', behavior: stripHtml($tStore('states.descriptions.hover'))    },
      { label: $tStore('states.items.focus'),    trigger: 'Tab',       behavior: stripHtml($tStore('states.descriptions.focus'))    },
      { label: $tStore('states.items.active'),   trigger: 'drag',      behavior: stripHtml($tStore('states.descriptions.active'))   },
      { label: $tStore('states.items.disabled'), trigger: 'disabled',  behavior: stripHtml($tStore('states.descriptions.disabled')) },
    ]}
  />

  <!-- ── Propriedades ───────────────────────────────────────────── -->
  <DocsProps
    title={$tStore('props.title')}
    tables={[
      {
        cols: {
          prop: $tStore('props.table.prop'),
          type: $tStore('props.table.type'),
          default: $tStore('props.table.default'),
          required: $tStore('props.table.required'),
          description: $tStore('props.table.description'),
        },
        items: [
          { name: 'value',            type: $tStore('props.table.value.type'),            defaultValue: $tStore('props.table.value.default'),            required: $tStore('props.table.value.required'),            description: $tStore('props.table.value.description') },
          { name: 'defaultValue',     type: $tStore('props.table.defaultValue.type'),     defaultValue: $tStore('props.table.defaultValue.default'),     required: $tStore('props.table.defaultValue.required'),     description: $tStore('props.table.defaultValue.description') },
          { name: 'onValueChange',    type: $tStore('props.table.onValueChange.type'),    defaultValue: $tStore('props.table.onValueChange.default'),    required: $tStore('props.table.onValueChange.required'),    description: $tStore('props.table.onValueChange.description') },
          { name: 'onValueCommit',    type: $tStore('props.table.onValueCommitted.type'), defaultValue: $tStore('props.table.onValueCommitted.default'), required: $tStore('props.table.onValueCommitted.required'), description: $tStore('props.table.onValueCommitted.description') },
          { name: 'min',              type: $tStore('props.table.min.type'),              defaultValue: $tStore('props.table.min.default'),              required: $tStore('props.table.min.required'),              description: $tStore('props.table.min.description') },
          { name: 'max',              type: $tStore('props.table.max.type'),              defaultValue: $tStore('props.table.max.default'),              required: $tStore('props.table.max.required'),              description: $tStore('props.table.max.description') },
          { name: 'step',             type: $tStore('props.table.step.type'),             defaultValue: $tStore('props.table.step.default'),             required: $tStore('props.table.step.required'),             description: $tStore('props.table.step.description') },
          { name: 'orientation',      type: $tStore('props.table.orientation.type'),      defaultValue: $tStore('props.table.orientation.default'),      required: $tStore('props.table.orientation.required'),      description: $tStore('props.table.orientation.description') },
          { name: 'disabled',         type: $tStore('props.table.disabled.type'),         defaultValue: $tStore('props.table.disabled.default'),         required: $tStore('props.table.disabled.required'),         description: $tStore('props.table.disabled.description') },
          { name: 'aria-label',       type: 'string',                                     defaultValue: '—',                                             required: 'Sim',                                            description: 'Obrigatório. Descreve o valor controlado para leitores de tela.' },
        ],
      },
    ]}
    interfaceCode={interfaceCode}
    extensibilityTitle={$tStore('props.extensibilityTitle')}
    extensibilityNotes={$tStore('props.extensibilityCode')}
  />

  <!-- ── Tokens ─────────────────────────────────────────────────── -->
  <DocsTokens
    title={$tStore('tokens.title')}
    cols={{
      token: $tStore('tokens.table.token'),
      value: $tStore('tokens.table.class'),
      description: $tStore('tokens.table.part'),
    }}
    items={[
      { token: '--muted',            value: $tStore('tokens.table.muted.class'),           description: $tStore('tokens.table.muted.part')           },
      { token: '--primary',          value: $tStore('tokens.table.primary.class'),         description: $tStore('tokens.table.primary.part')         },
      { token: '--ring',             value: $tStore('tokens.table.ring.class'),            description: $tStore('tokens.table.ring.part')            },
      { token: '--background',       value: $tStore('tokens.table.background.class'),      description: $tStore('tokens.table.background.part')      },
      { token: '--foreground',       value: $tStore('tokens.table.foreground.class'),      description: $tStore('tokens.table.foreground.part')      },
      { token: '--muted-foreground', value: $tStore('tokens.table.mutedForeground.class'), description: $tStore('tokens.table.mutedForeground.part') },
    ]}
    customizationTitle={$tStore('tokens.customizationTitle')}
    customizationCode={$tStore('tokens.customizationCode')}
  />

  <!-- ── Acessibilidade ─────────────────────────────────────────── -->
  <DocsAccessibility
    title={$tStore('accessibility.title')}
    summary={$tStore('accessibility.summary')}
    items={[
      $tStore('accessibility.items.item1'),
      $tStore('accessibility.items.item2'),
      $tStore('accessibility.items.item3'),
      $tStore('accessibility.items.item4'),
      $tStore('accessibility.items.item5'),
      $tStore('accessibility.items.item6'),
    ]}
    keyboardTitle={$tStore('accessibility.keyboard.title')}
    keyboardItems={[
      { key: 'Tab',        description: $tStore('accessibility.keyboard.tab')        },
      { key: 'ArrowRight', description: stripHtml($tStore('accessibility.keyboard.arrowRight')) },
      { key: 'ArrowLeft',  description: stripHtml($tStore('accessibility.keyboard.arrowLeft'))  },
      { key: 'ArrowUp',    description: stripHtml($tStore('accessibility.keyboard.arrowUp'))    },
      { key: 'ArrowDown',  description: stripHtml($tStore('accessibility.keyboard.arrowDown'))  },
      { key: 'Home',       description: stripHtml($tStore('accessibility.keyboard.home'))       },
      { key: 'End',        description: stripHtml($tStore('accessibility.keyboard.end'))        },
      { key: 'PageUp',     description: $tStore('accessibility.keyboard.pageUp')     },
      { key: 'PageDown',   description: $tStore('accessibility.keyboard.pageDown')   },
    ]}
  />

  <!-- ── Relacionados ───────────────────────────────────────────── -->
  <DocsRelated
    title={$tStore('related.title')}
    items={[
      { name: $tStore('related.items.input.name'),      description: $tStore('related.items.input.description'),      path: '?path=/docs/ui-input--docs'      },
      { name: $tStore('related.items.switch.name'),     description: $tStore('related.items.switch.description'),     path: '?path=/docs/ui-switch--docs'     },
      { name: $tStore('related.items.progress.name'),   description: $tStore('related.items.progress.description'),   path: '?path=/docs/ui-progress--docs'   },
      { name: $tStore('related.items.radioGroup.name'), description: $tStore('related.items.radioGroup.description'), path: '?path=/docs/ui-radiogroup--docs' },
    ]}
  />

  <!-- ── Notas ──────────────────────────────────────────────────── -->
  <DocsNotes
    title={$tStore('notes.title')}
    items={[
      { title: '', content: $tStore('notes.item1') },
      { title: '', content: $tStore('notes.item2') },
      { title: '', content: $tStore('notes.item3') },
      { title: '', content: $tStore('notes.item4') },
    ]}
  />

  <!-- ── Analytics ─────────────────────────────────────────────── -->
  <DocsAnalytics
    title={$tStore('analytics.title')}
    cols={{
      event: $tStore('analytics.table.event'),
      trigger: $tStore('analytics.table.trigger'),
      payload: $tStore('analytics.table.payload'),
    }}
    items={[
      { event: 'slider_change', trigger: $tStore('analytics.table.slider_change.trigger'), payload: $tStore('analytics.table.slider_change.payload') },
    ]}
  />

  <!-- ── Testes ─────────────────────────────────────────────────── -->
  <DocsTestes
    title={$tStore('testes.title')}
    functional={{
      title: $tStore('testes.functional.title'),
      cols: {
        action: $tNavStore('common.userAction'),
        result: $tNavStore('common.expectedResult'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { action: $tStore('testes.functional.item1.action'), result: $tStore('testes.functional.item1.result'), priority: localPriority($tStore('testes.functional.item1.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item2.action'), result: $tStore('testes.functional.item2.result'), priority: localPriority($tStore('testes.functional.item2.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item3.action'), result: $tStore('testes.functional.item3.result'), priority: localPriority($tStore('testes.functional.item3.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item4.action'), result: $tStore('testes.functional.item4.result'), priority: localPriority($tStore('testes.functional.item4.priority'), $tNavStore) },
      ],
    }}
    accessibility={{
      title: $tStore('testes.accessibility.title'),
      cols: {
        criterion: $tNavStore('common.criterion'),
        level: 'WCAG',
        how: $tNavStore('common.howToVerify'),
      },
      items: [
        { criterion: $tStore('testes.accessibility.item1'), level: 'AA',     how: 'axe-core'           },
        { criterion: $tStore('testes.accessibility.item2'), level: '1.4.11', how: 'Contrast checker'   },
        { criterion: $tStore('testes.accessibility.item3'), level: '2.4.7',  how: 'DevTools a11y tree' },
        { criterion: $tStore('testes.accessibility.item4'), level: '4.1.2',  how: 'DevTools a11y tree' },
        { criterion: $tStore('testes.accessibility.item5'), level: '4.1.2',  how: 'DevTools a11y tree' },
      ],
    }}
    visual={{
      title: $tStore('testes.visual.title'),
      cols: {
        story: $tNavStore('common.storyState'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { story: $tStore('testes.visual.item1.story'), priority: localPriority($tStore('testes.visual.item1.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item2.story'), priority: localPriority($tStore('testes.visual.item2.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item3.story'), priority: localPriority($tStore('testes.visual.item3.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item4.story'), priority: localPriority($tStore('testes.visual.item4.priority'), $tNavStore) },
      ],
    }}
  />
</DocsPageLayout>
