// nortear-design-system-svelte/src/components/ui/pagination/pagination-next.svelte
<script lang="ts">
	import { Pagination as PaginationPrimitive } from "bits-ui";
	import { cn } from "@/lib/utils.js";
	import { buttonVariants } from "../button/index.js";
	import ChevronRightIcon from '@lucide/svelte/icons/chevron-right';

	let {
		ref = $bindable(null),
		class: className,
		children,
		text = "Próxima",
		"aria-label": ariaLabel = "Ir para a próxima página",
		...restProps
	}: PaginationPrimitive.NextButtonProps & { text?: string; "aria-label"?: string } = $props();
</script>

<!-- `nds-pagination-next` no lugar de `pr-1.5!`, e `data-slot` próprio — ver a nota em pagination-previous.svelte. -->
<PaginationPrimitive.NextButton
	bind:ref
	aria-label={ariaLabel}
	data-slot="pagination-next"
	class={cn(buttonVariants({ variant: "ghost", size: "default" }), "nds-pagination-next", className)}
	{...restProps}
>
	{#if children}
		{@render children?.()}
	{:else}
		<span class="nds-pagination-label">{text}</span>
		<ChevronRightIcon data-icon="inline-end" />
	{/if}
</PaginationPrimitive.NextButton>

// design-system-react/src/components/ui/pagination.tsx
import * as React from "react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { ChevronLeftIcon, ChevronRightIcon, MoreHorizontalIcon } from "lucide-react"

function Pagination({ className, ...props }: React.ComponentProps<"nav">) {
  return (
    <nav
      role="navigation"
      aria-label="pagination"
      data-slot="pagination"
      className={cn("nds-pagination", className)}
      {...props}
    />
  )
}

function PaginationContent({
  className,
  ...props
}: React.ComponentProps<"ul">) {
  return (
    <ul
      data-slot="pagination-content"
      className={cn("nds-pagination-list", className)}
      {...props}
    />
  )
}

function PaginationItem({ ...props }: React.ComponentProps<"li">) {
  return <li data-slot="pagination-item" {...props} />
}

type PaginationLinkProps = {
  isActive?: boolean
} & Pick<React.ComponentProps<typeof Button>, "size"> &
  React.ComponentProps<"a">

function PaginationLink({
  className,
  isActive,
  size = "icon",
  ...props
}: PaginationLinkProps) {
  return (
    <Button
      variant={isActive ? "outline" : "ghost"}
      size={size}
      className={cn(className)}
      nativeButton={false}
      render={
        <a
          aria-current={isActive ? "page" : undefined}
          data-slot="pagination-link"
          data-active={isActive}
          role="link"
          {...props}
        />
      }
    />
  )
}

function PaginationPrevious({
  className,
  text = "Previous",
  ...props
}: React.ComponentProps<typeof PaginationLink> & { text?: string }) {
  return (
    <PaginationLink
      aria-label="Go to previous page"
      size="default"
      className={cn("nds-pagination-prev", className)}
      {...props}
    >
      <ChevronLeftIcon data-icon="inline-start" />
      <span className="nds-pagination-label">{text}</span>
    </PaginationLink>
  )
}

function PaginationNext({
  className,
  text = "Next",
  ...props
}: React.ComponentProps<typeof PaginationLink> & { text?: string }) {
  return (
    <PaginationLink
      aria-label="Go to next page"
      size="default"
      className={cn("nds-pagination-next", className)}
      {...props}
    >
      <span className="nds-pagination-label">{text}</span>
      <ChevronRightIcon data-icon="inline-end" />
    </PaginationLink>
  )
}

function PaginationEllipsis({
  className,
  ...props
}: React.ComponentProps<"span">) {
  return (
    <span
      aria-hidden
      data-slot="pagination-ellipsis"
      className={cn(
        "nds-pagination-ellipsis",
        className
      )}
      {...props}
    >
      <MoreHorizontalIcon
      />
      <span className="nds-sr-only">More pages</span>
    </span>
  )
}

export {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
}
