// nortear-design-system-vue/src/components/ui/breadcrumb/BreadcrumbList.vue
<script lang="ts" setup>
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <ol
    data-slot="breadcrumb-list"
    :class="cn('nds-breadcrumb-list', props.class)"
  >
    <slot />
  </ol>
</template>

// design-system-svelte/src/components/ui/breadcrumb/breadcrumb-list.svelte
<script lang="ts">
	import type { HTMLOlAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "@/lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLOlAttributes> = $props();
</script>

<ol
	bind:this={ref}
	data-slot="breadcrumb-list"
	class={cn("nds-breadcrumb-list", className)}
	{...restProps}
>
	{@render children?.()}
</ol>
