// nortear-design-system-vue/src/components/ui/sidebar/Sidebar.vue
<script setup lang="ts">
import type { SidebarProps } from './index'
import { cn } from '@/lib/utils'
import { Sheet, SheetContent } from '@/components/ui/sheet'
import SheetDescription from '@/components/ui/sheet/SheetDescription.vue'
import SheetHeader from '@/components/ui/sheet/SheetHeader.vue'
import SheetTitle from '@/components/ui/sheet/SheetTitle.vue'
import { ROTULOS_SIDEBAR_PADRAO } from '@shared/primitives/sidebar-a11y-labels'
import { SIDEBAR_WIDTH_MOBILE, useSidebar } from './utils'

defineOptions({
  inheritAttrs: false,
})

// `mobileTitle` e `mobileDescription` nomeiam a gaveta para quem usa leitor de
// tela — um diálogo sem nome é anunciado como "diálogo" e mais nada. O padrão
// vem do conteúdo compartilhado, em português; são props porque o texto é do
// produto, não do design system.
const props = withDefaults(defineProps<SidebarProps>(), {
  side: 'left',
  variant: 'sidebar',
  collapsible: 'offcanvas',
  mobileTitle: () => ROTULOS_SIDEBAR_PADRAO.tituloMovel,
  mobileDescription: () => ROTULOS_SIDEBAR_PADRAO.descricaoMovel,
})

const { isMobile, state, openMobile, setOpenMobile } = useSidebar()

// A devolução do foco ao gatilho quando a gaveta fecha NÃO é escrita aqui, e
// isso foi medido, não presumido: o primitivo desta stack adota como "gatilho"
// o elemento que estava focado no momento em que o painel monta (desde que não
// seja o `<body>`), então o `SidebarTrigger` — que o diálogo nunca vê, porque a
// gaveta abre pelo estado da sidebar — acaba registrado assim mesmo. Outras
// stacks precisam de código próprio para isto. A story `MobileOverlay` mantém a
// asserção de qualquer forma: o comportamento é contrato, não detalhe da lib.
</script>

<template>
  <div
    v-if="collapsible === 'none'"
    data-slot="sidebar"
    :class="cn('nds-sidebar-static', props.class)"
    v-bind="$attrs"
  >
    <slot />
  </div>

  <!-- A classe e os atributos de quem compõe vão para o PAINEL, não para a raiz
       do Sheet: a raiz não renderiza elemento nenhum, então tudo o que pousasse
       ali sumia em silêncio — a classe do consumidor desaparecia só em tela
       estreita. Na coluna eles pousam em `.nds-sidebar-panel`; aqui, na gaveta,
       que cumpre o mesmo papel. O `v-bind="$attrs"` vem depois do `:style` de
       propósito: assim um estilo de fora sobrescreve a medida móvel em vez de
       ser engolido por ela. -->
  <Sheet
    v-else-if="isMobile"
    :open="openMobile"
    @update:open="setOpenMobile"
  >
    <SheetContent
      data-sidebar="sidebar"
      data-slot="sidebar"
      data-mobile="true"
      :side="side"
      :class="cn('nds-sidebar-mobile', props.class)"
      :style="{
        '--sidebar-width': SIDEBAR_WIDTH_MOBILE,
      }"
      v-bind="$attrs"
    >
      <SheetHeader class="nds-sr-only">
        <SheetTitle>{{ props.mobileTitle }}</SheetTitle>
        <SheetDescription>{{ props.mobileDescription }}</SheetDescription>
      </SheetHeader>
      <div class="nds-sidebar-mobile-inner">
        <slot />
      </div>
    </SheetContent>
  </Sheet>

  <div
    v-else
    class="nds-sidebar-root"
    data-slot="sidebar"
    :data-state="state"
    :data-collapsible="state === 'collapsed' ? collapsible : ''"
    :data-variant="variant"
    :data-side="side"
  >
    <!-- This is what handles the sidebar gap on desktop  -->
    <div
      data-slot="sidebar-gap"
      :class="cn('nds-sidebar-gap-inner')"
    />
    <div
      data-slot="sidebar-container"
      :data-side="side"
      :class="cn('nds-sidebar-panel', props.class)"
      v-bind="$attrs"
    >
      <div
        data-sidebar="sidebar"
        data-slot="sidebar-inner"
        class="nds-sidebar-inner"
      >
        <slot />
      </div>
    </div>
  </div>
</template>

// nortear-design-system-svelte/src/components/ui/sidebar/sidebar.svelte
<script lang="ts">
	import * as Sheet from "@/components/ui/sheet/index.js";
	import { cn, type WithElementRef } from "@/lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";
	import { ROTULOS_SIDEBAR_PADRAO } from "@shared/primitives/sidebar-a11y-labels";
	import { SIDEBAR_WIDTH_MOBILE } from "./constants.js";
	import { useSidebar } from "./context.svelte.js";

	// `mobileTitle` e `mobileDescription` nomeiam a gaveta para quem usa leitor
	// de tela — um diálogo sem nome é anunciado como "diálogo" e mais nada. O
	// padrão vem do conteúdo compartilhado, em português; são props porque o
	// texto é do produto, não do design system.
	let {
		ref = $bindable(null),
		side = "left",
		variant = "sidebar",
		collapsible = "offcanvas",
		mobileTitle = ROTULOS_SIDEBAR_PADRAO.tituloMovel,
		mobileDescription = ROTULOS_SIDEBAR_PADRAO.descricaoMovel,
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		side?: "left" | "right";
		variant?: "sidebar" | "floating" | "inset";
		collapsible?: "offcanvas" | "icon" | "none";
		mobileTitle?: string;
		mobileDescription?: string;
	} = $props();

	const sidebar = useSidebar();
</script>

{#if collapsible === "none"}
	<div
		class={cn("nds-sidebar-static", className)}
		bind:this={ref}
		{...restProps}
	>
		{@render children?.()}
	</div>
{:else if sidebar.isMobile}
	<Sheet.Root
		bind:open={() => sidebar.openMobile, (v) => sidebar.setOpenMobile(v)}
		{...restProps}
	>
		<Sheet.Content
			bind:ref
			data-sidebar="sidebar"
			data-slot="sidebar"
			data-mobile="true"
			class={cn("nds-sidebar-mobile", className)}
			style="--sidebar-width: {SIDEBAR_WIDTH_MOBILE};"
			{side}
		>
			<Sheet.Header class="nds-sr-only">
				<Sheet.Title>{mobileTitle}</Sheet.Title>
				<Sheet.Description>{mobileDescription}</Sheet.Description>
			</Sheet.Header>
			<div class="nds-sidebar-mobile-inner">
				{@render children?.()}
			</div>
		</Sheet.Content>
	</Sheet.Root>
{:else}
	<div
		bind:this={ref}
		class="nds-sidebar-root"
		data-state={sidebar.state}
		data-collapsible={sidebar.state === "collapsed" ? collapsible : ""}
		data-variant={variant}
		data-side={side}
		data-slot="sidebar"
	>
		<!-- This is what handles the sidebar gap on desktop -->
		<div
			data-slot="sidebar-gap"
			class={cn("nds-sidebar-gap-inner")}
		></div>
		<div
			data-slot="sidebar-container"
			class={cn("nds-sidebar-panel", className)}
			{...restProps}
		>
			<div
				data-sidebar="sidebar"
				data-slot="sidebar-inner"
				class="nds-sidebar-inner"
			>
				{@render children?.()}
			</div>
		</div>
	</div>
{/if}
