// nortear-design-system-react/src/components/ui/sonner.tsx
import { useTheme } from "next-themes"
import { Toaster as Sonner, type ToasterProps } from "sonner"
import { CircleCheckIcon, InfoIcon, TriangleAlertIcon, OctagonXIcon, Loader2Icon } from "lucide-react"

const Toaster = ({ ...props }: ToasterProps) => {
  const { theme = "system" } = useTheme()

  return (
    <Sonner
      theme={theme as ToasterProps["theme"]}
      className="toaster"
      icons={{
        success: (
          <CircleCheckIcon className="nds-toast-icon" />
        ),
        info: (
          <InfoIcon className="nds-toast-icon" />
        ),
        warning: (
          <TriangleAlertIcon className="nds-toast-icon" />
        ),
        error: (
          <OctagonXIcon className="nds-toast-icon" />
        ),
        loading: (
          <Loader2Icon className="nds-toast-icon nds-toast-icon-spin" />
        ),
      }}
      style={
        {
          "--normal-bg": "var(--popover)",
          "--normal-text": "var(--popover-foreground)",
          "--normal-border": "var(--border)",
          "--border-radius": "var(--radius)",
        } as React.CSSProperties
      }
      {...props}
    />
  )
}

export { Toaster }

// design-system-vue/src/components/ui/sonner/Sonner.vue
<script lang="ts" setup>
import type { ToasterProps } from 'vue-sonner'

import {
  CircleCheckIcon,
  InfoIcon,
  Loader2Icon,
  OctagonXIcon,
  TriangleAlertIcon,
  XIcon,
} from 'lucide-vue-next'
import { Toaster as Sonner } from 'vue-sonner'
import { cn } from '@/lib/utils'

const props = defineProps<ToasterProps>()
</script>

<template>
  <Sonner
    :class="cn('toaster', props.class)"
    :style="{
      '--normal-bg': 'var(--popover)',
      '--normal-text': 'var(--popover-foreground)',
      '--normal-border': 'var(--border)',
      '--border-radius': 'var(--radius)',
    }"
    v-bind="props"
    :toast-options="props.toastOptions ?? {}"
  >
    <template #success-icon>
      <CircleCheckIcon class="nds-toast-icon" />
    </template>
    <template #info-icon>
      <InfoIcon class="nds-toast-icon" />
    </template>
    <template #warning-icon>
      <TriangleAlertIcon class="nds-toast-icon" />
    </template>
    <template #error-icon>
      <OctagonXIcon class="nds-toast-icon" />
    </template>
    <template #loading-icon>
      <div>
        <Loader2Icon class="nds-toast-icon nds-toast-icon-spin" />
      </div>
    </template>
    <template #close-icon>
      <XIcon class="nds-toast-icon" />
    </template>
  </Sonner>
</template>
