// design-system-svelte/src/components/docs/shared/sections/DocsHeader.svelte
<script lang="ts">
  import { Badge } from '@/components/ui/badge';
  import LanguageSwitcher from '@/components/product/LanguageSwitcher.svelte';

  const { title, description, category, type, installNote }: {
    title: string;
    description: string;
    category: string;
    type: string;
    installNote?: string;
  } = $props();
</script>

<header class="ds-docs nds-stack nds-border-b-soft" data-spacing="md" style="padding-bottom: var(--spacing-6)">
  <div class="nds-cluster" data-spacing="sm">
    <Badge variant="secondary" class="nds-bg-primary-soft nds-text-primary nds-border-primary-soft nds-font-medium">
      {category}
    </Badge>
    <Badge variant="outline" class="nds-text-muted-foreground nds-font-normal">
      {type}
    </Badge>
    <div class="nds-spacer-start">
      <LanguageSwitcher />
    </div>
  </div>
  <div class="nds-stack" data-spacing="sm">
    <h1 class="nds-text-h1 nds-text-foreground">{title}</h1>
    <p class="nds-text-lead nds-text-muted-foreground nds-max-w-prose">{description}</p>
  </div>
  {#if installNote}
    <div class="nds-cluster nds-text-body nds-text-muted-foreground" data-spacing="sm">
      <span class="nds-cluster" data-spacing="xs">
        <code class="nds-code-inline">{installNote}</code>
      </span>
    </div>
  {/if}
</header>

// nortear-design-system-react/src/components/docs/shared/sections/DocsHeader.tsx
import type * as React from 'react';
import { Badge } from '@/components/ui/badge';
import { LanguageSwitcher } from '@/components/product/LanguageSwitcher';

export interface DocsHeaderProps {
  title: string;
  description: string;
  category: string;
  type: string;
  installNote?: string;
  languageSwitcher?: React.ReactNode;
}

export function DocsHeader({ title, description, category, type, installNote, languageSwitcher }: DocsHeaderProps) {
  return (
    <header className="ds-docs nds-stack nds-border-b-soft" data-spacing="md" style={{ paddingBottom: 'var(--spacing-6)' }}>
      <div className="nds-cluster" data-spacing="sm">
        <Badge
          variant="secondary"
          className="nds-bg-primary-soft nds-text-primary nds-border-primary-soft nds-font-medium"
        >
          {category}
        </Badge>
        <Badge variant="outline" className="nds-text-muted-foreground nds-font-normal">
          {type}
        </Badge>
        <div className="nds-spacer-start">{languageSwitcher ?? <LanguageSwitcher />}</div>
      </div>

      <div className="nds-stack" data-spacing="sm">
        <h1 className="nds-text-h1 nds-text-foreground">{title}</h1>
        <p className="nds-text-lead nds-text-muted-foreground nds-max-w-prose">{description}</p>
      </div>

      {installNote && (
        <div className="nds-cluster nds-text-body nds-text-muted-foreground" data-spacing="sm">
          <span className="nds-cluster" data-spacing="xs">
            <code className="nds-code-inline">{installNote}</code>
          </span>
        </div>
      )}
    </header>
  );
}
