// design-system-vue/src/components/ui/carousel/CarouselItem.vue
<script setup lang="ts">
import type { WithClassAsProps } from './interface'
import { cn } from '@/lib/utils'
import { useCarousel } from './useCarousel'

const props = defineProps<WithClassAsProps>()

const { orientation } = useCarousel()
</script>

<template>
  <div
    data-slot="carousel-item"
    role="group"
    aria-roledescription="slide"
    :data-orientation="orientation"
    :class="cn('nds-carousel-slide', props.class)"
  >
    <slot />
  </div>
</template>

// design-system-svelte/src/components/ui/carousel/carousel-item.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { getEmblaContext } from "./context.js";
	import { cn, type WithElementRef } from "@/lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

	const emblaCtx = getEmblaContext("<Carousel.Item/>");
</script>

<div
	bind:this={ref}
	data-slot="carousel-item"
	role="group"
	aria-roledescription="slide"
	class={cn(
		"nds-carousel-slide",
		className
	)}
	data-embla-slide=""
	data-orientation={emblaCtx.orientation}
	{...restProps}
>
	{@render children?.()}
</div>
