// nortear-design-system-vue/src/components/ui/input-group/InputGroupButton.vue
<script setup lang="ts">
import type { InputGroupButtonProps } from './index'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'

/**
 * Botão apertado dentro da moldura. Compõe o `Button` do design system.
 *
 * Correção 1 — `size` é REPASSADO ao `Button`. Antes ele era escrito num
 * `:data-size` e parava ali: nenhuma folha do design system lê `[data-size]`
 * para `.nds-input-group-button`, então a prop prometia uma medida que nunca
 * aplicava. Quem rende `nds-button-xs` e companhia é o `Button`.
 *
 * Correção 2 — `type` é PROP, com padrão `'button'`. Estava cravado no
 * template, e nem quem compõe conseguia sobrepor. O padrão continua sendo
 * `'button'` para o botão do addon não submeter o formulário em volta; declarar
 * `type="submit"` agora funciona, e é o que as outras stacks já permitiam.
 *
 * O `type` chega ao `<button>` por herança de atributos: o `Button` não declara
 * `type` como prop, então o valor escrito aqui vence o `type` que ele calcula
 * internamente. MEDIDO por renderização, não suposto.
 */
const props = withDefaults(defineProps<InputGroupButtonProps>(), {
  size: 'xs',
  variant: 'ghost',
  type: 'button',
})
</script>

<template>
  <Button
    data-slot="input-group-button"
    :type="props.type"
    :variant="props.variant"
    :size="props.size"
    :class="cn('nds-input-group-button', props.class)"
  >
    <slot />
  </Button>
</template>

// nortear-design-system-svelte/src/components/ui/input-group/input-group-button.svelte
<script lang="ts" module>
	/**
	 * Medidas do botão apertado que cabem dentro da moldura.
	 *
	 * Era um `cva` com as quatro medidas mapeando para string VAZIA, e ao lado
	 * dele um `data-size` no elemento. Nenhuma folha do design system lê
	 * `[data-size]` para `.nds-input-group-button` — conferido —, então a opção
	 * prometia uma medida que nunca aplicava. Quem aplica é o `Button`, que rende
	 * `nds-button-xs` e companhia; por isso `size` é REPASSADO a ele.
	 */
	export type InputGroupButtonSize = "xs" | "sm" | "icon-xs" | "icon-sm";
</script>

<script lang="ts">
	import { cn } from "@/lib/utils.js";
	import type { ComponentProps } from "svelte";
	import { Button } from "@/components/ui/button/index.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		type = "button",
		variant = "ghost",
		size = "xs",
		...restProps
	}: Omit<ComponentProps<typeof Button>, "href" | "size"> & {
		size?: InputGroupButtonSize;
	} = $props();
</script>

<!-- `data-slot="input-group-button"` sobrescreve o `data-slot="button"` do
     próprio Button — é por ele que a story e a play acham o que AGE dentro da
     moldura, sem depender do texto nem da posição. A classe daqui só aperta a
     medida; o visual de botão continua vindo de `.nds-button`. -->
<Button
	bind:ref
	{type}
	{variant}
	{size}
	data-slot="input-group-button"
	class={cn("nds-input-group-button", className)}
	{...restProps}
>
	{@render children?.()}
</Button>
