// design-system-vue/src/components/ui/drawer/DrawerContent.vue
<script lang="ts" setup>
import type { DialogContentEmits, DialogContentProps } from 'reka-ui'
import type { HTMLAttributes } from 'vue'
import { useForwardPropsEmits } from 'reka-ui'
import { DrawerContent, DrawerPortal } from 'vaul-vue'
import { cn } from '@/lib/utils'
import DrawerOverlay from './DrawerOverlay.vue'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps<DialogContentProps & { class?: HTMLAttributes['class'] }>()
const emits = defineEmits<DialogContentEmits>()

const forwarded = useForwardPropsEmits(props, emits)
</script>

<template>
  <DrawerPortal>
    <DrawerOverlay />
    <DrawerContent
      data-slot="drawer-content"
      v-bind="{ 'aria-modal': 'true', 'aria-label': $attrs['aria-labelledby'] ? undefined : 'Drawer', ...$attrs, ...forwarded }"
      :class="cn( 'nds-drawer-content', props.class, )"
    >
      <div class="nds-drawer-handle" />
      <slot />
    </DrawerContent>
  </DrawerPortal>
</template>

// design-system-svelte/src/components/ui/drawer/drawer-content.svelte
<script lang="ts">
	import { Drawer as DrawerPrimitive } from "vaul-svelte";
	import DrawerPortal from "./drawer-portal.svelte";
	import DrawerOverlay from "./drawer-overlay.svelte";
	import { cn } from "@/lib/utils.js";
	import type { ComponentProps } from "svelte";
	import type { WithoutChildrenOrChild } from "@/lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		portalProps,
		children,
		...restProps
	}: DrawerPrimitive.ContentProps & {
		portalProps?: WithoutChildrenOrChild<ComponentProps<typeof DrawerPortal>>;
	} = $props();
</script>

<DrawerPortal {...portalProps}>
	<DrawerOverlay />
	<DrawerPrimitive.Content
		bind:ref
		data-slot="drawer-content"
		class={cn("nds-drawer-content", className)}
		{...restProps}
	>
		<div
			class="nds-drawer-handle"
		></div>
		{@render children?.()}
	</DrawerPrimitive.Content>
</DrawerPortal>
