// design-system-react/src/components/product/LanguageSwitcher.tsx
import { Languages } from "lucide-react";
import {
  ToggleGroup,
  ToggleGroupItem,
} from "@/components/ui/toggle-group";
import { useI18nStore } from "@/lib/i18n";
import { track } from "@/lib/analytics";

/**
 * Componente de Produto: Seletor de Idioma
 * Centraliza a lógica de troca de idioma da documentação.
 * Utiliza o ToggleGroup da UI para garantir agrupamento visual e semântica de seleção única.
 * Rastreia trocas de idioma via GA4.
 */
export function LanguageSwitcher() {
  const { locale, setLocale } = useI18nStore();

  return (
    <div className="flex items-center gap-1 nds-bg-muted-30 p-1 rounded-(--radius-input) border nds-border-border-40">
      <ToggleGroup
        type="single"
        value={locale}
        onValueChange={(value: string) => {
          if (!value || value === locale) return;
          track('language_switched', {
            previous_language: locale,
            new_language: value as typeof locale,
          });
          setLocale(value as typeof locale);
        }}
        variant="outline"
        size="sm"
        className="h-(--height-sm)"
      >
        <ToggleGroupItem
          value="pt-BR"
          aria-label="Português"
          className="h-(--height-xs) px-2 nds-text-2xs data-[state=on]:bg-secondary data-[state=on]:text-secondary-foreground"
        >
          PT
        </ToggleGroupItem>
        <ToggleGroupItem
          value="en"
          aria-label="English"
          className="h-(--height-xs) px-2 nds-text-2xs data-[state=on]:bg-secondary data-[state=on]:text-secondary-foreground"
        >
          EN
        </ToggleGroupItem>
        <ToggleGroupItem
          value="es"
          aria-label="Español"
          className="h-(--height-xs) px-2 nds-text-2xs data-[state=on]:bg-secondary data-[state=on]:text-secondary-foreground"
        >
          ES
        </ToggleGroupItem>
      </ToggleGroup>

      <div className="ml-1 border-l nds-border-soft h-3 pl-2 flex items-center">
        <Languages className="h-3 w-3 text-muted-foreground/50" />
      </div>
    </div>
  );
}

// design-system-svelte/src/components/product/LanguageSwitcher.svelte
<script lang="ts">
  import { locale, setLocale, type Locale } from '@/lib/i18n';
  import { track } from '@/lib/analytics';

  const locales: { value: Locale; label: string; ariaLabel: string }[] = [
    { value: 'pt-BR', label: 'PT', ariaLabel: 'Português' },
    { value: 'en',    label: 'EN', ariaLabel: 'English'   },
    { value: 'es',    label: 'ES', ariaLabel: 'Español'   },
  ];

  function handleChange(value: Locale) {
    if (value === $locale) return;
    track('language_switched', {
      previous_language: $locale,
      new_language: value,
    });
    setLocale(value);
  }
</script>

<div class="flex items-center gap-1 nds-bg-muted-30 p-1 rounded-(--radius-input) border nds-border-border-40">
  {#each locales as lang}
    <button
      type="button"
      aria-label={lang.ariaLabel}
      aria-pressed={$locale === lang.value}
      onclick={() => handleChange(lang.value)}
      class={[
        'h-(--height-xs) px-2 text-[10px] font-bold rounded-(--radius-button) transition-all',
        $locale === lang.value
          ? 'bg-secondary text-secondary-foreground'
          : 'text-muted-foreground hover:text-foreground hover:bg-muted/50',
      ].join(' ')}
    >
      {lang.label}
    </button>
  {/each}
</div>
