// design-system-svelte/src/components/docs/InputDocs.svelte
<script lang="ts">
  import { Input } from '@/components/ui/input';
  import { Label } from '@/components/ui/label';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader, DocsDemonstration, DocsAnatomy, DocsWhenToUse, DocsDoDont,
    DocsImport, DocsVariants, DocsStates, DocsProps, DocsTokens,
    DocsAccessibility, DocsRelated, DocsNotes, DocsAnalytics, DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import inputTranslations from '@shared/content/input/translations.json';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(inputTranslations);

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'input',
    });
    track('docs_page_view', {
      component_name: 'input',
      locale: l,
      page_title: `${t('title')} · Design System`,
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────

  let activeSection = $state('demonstracao');

  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')   },
        { id: 'variantes',    label: tNav('nav.variants') },
        { id: 'estados',      label: tNav('nav.states')   },
        { id: 'propriedades', label: tNav('nav.props')    },
        { id: 'tokens',       label: tNav('nav.tokens')   },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  $effect(() => {
    const ids = NAV_GROUPS.flatMap(g => g.sections.map(s => s.id));
    const observer = new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          activeSection = entry.target.id;
          track('docs_section_viewed', { section_id: entry.target.id, component_name: 'input', locale: $locale });
          break;
        }
      }
    }, { rootMargin: '-20% 0px -70% 0px', threshold: 0 });
    for (const id of ids) {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    }
    return () => observer.disconnect();
  });

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  const priorityKeyMap: Record<string, string> = { high: 'common.high', medium: 'common.medium', low: 'common.low' };

  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  // ─── Code strings ────────────────────────────────────────────────────────────

  const codeImportBasic = `import { Input } from "@/components/ui/input";`;

  const codeImportWithLabel = `import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";`;

  const codeDefault = `<div class="flex flex-col gap-1.5">
  <Label for="nome">Nome completo</Label>
  <Input id="nome" type="text" placeholder="ex: João da Silva" />
</div>`;

  const codeEmail = `<div class="flex flex-col gap-1.5">
  <Label for="email">Email</Label>
  <Input id="email" type="email" placeholder="ex: joao@empresa.com" />
</div>`;

  const codePassword = `<div class="flex flex-col gap-1.5">
  <Label for="senha">Senha</Label>
  <Input id="senha" type="password" placeholder="Mínimo 8 caracteres" />
</div>`;

  const codeDisabled = `<div class="flex flex-col gap-1.5">
  <Label for="campo-disabled">Campo desabilitado</Label>
  <Input id="campo-disabled" type="text" disabled placeholder="Não disponível" />
</div>`;

  const codeError = `<div class="flex flex-col gap-1.5">
  <Label for="email-erro">Email</Label>
  <Input id="email-erro" type="email" aria-invalid="true"
    aria-describedby="email-msg"
    placeholder="ex: joao@empresa.com" />
  <p id="email-msg" class="text-sm text-destructive">
    Email inválido. Use o formato nome@dominio.com
  </p>
</div>`;

  const codeFile = `<div class="flex flex-col gap-1.5">
  <Label for="arquivo">Arquivo</Label>
  <Input id="arquivo" type="file" />
</div>`;

  const codeTokenCustomization = `/* Em globals.css */
:root {
  --height-default: 2.25rem; /* altura do campo */
  --radius-input: 0.375rem;  /* border-radius */
}`;

  const interfaceCode = `// Input — estende todos os atributos HTML nativos de <input>
interface InputProps extends HTMLInputAttributes {
  class?: string;
  ref?: HTMLInputElement | null;
}`;
</script>

<DocsPageLayout navGroups={NAV_GROUPS} {activeSection} componentSlug="input">
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
      installNote="npx shadcn-svelte@latest add input"
    />
  {/snippet}

      <!-- ── Demonstração ───────────────────────────────────────────── -->
      <DocsDemonstration title={$tStore('demonstration.title')}>
        {#snippet children()}
          <div class="w-full space-y-4 max-w-sm">
            <div class="flex flex-col gap-1.5">
              <Label for="demo-nome">{$tStore('demonstration.labels.defaultLabel')}</Label>
              <Input id="demo-nome" type="text" placeholder={$tStore('demonstration.labels.defaultPlaceholder')} />
            </div>
            <div class="flex flex-col gap-1.5">
              <Label for="demo-email">{$tStore('demonstration.labels.emailLabel')}</Label>
              <Input id="demo-email" type="email" placeholder={$tStore('demonstration.labels.emailPlaceholder')} />
            </div>
            <div class="flex flex-col gap-1.5">
              <Label for="demo-senha">{$tStore('demonstration.labels.passwordLabel')}</Label>
              <Input id="demo-senha" type="password" placeholder={$tStore('demonstration.labels.passwordPlaceholder')} />
            </div>
            <div class="flex flex-col gap-1.5">
              <Label for="demo-busca">{$tStore('demonstration.labels.searchLabel')}</Label>
              <Input id="demo-busca" type="search" placeholder={$tStore('demonstration.labels.searchPlaceholder')} />
            </div>
            <div class="flex flex-col gap-1.5">
              <Label for="demo-disabled">{$tStore('demonstration.labels.disabledLabel')}</Label>
              <Input id="demo-disabled" type="text" disabled placeholder={$tStore('demonstration.labels.disabledPlaceholder')} />
            </div>
            <div class="flex flex-col gap-1.5">
              <Label for="demo-error">{$tStore('demonstration.labels.errorLabel')}</Label>
              <Input
                id="demo-error"
                type="email"
                aria-invalid="true"
                aria-describedby="demo-error-msg"
                placeholder={$tStore('demonstration.labels.errorPlaceholder')}
              />
              <p id="demo-error-msg" class="text-sm text-destructive">{$tStore('demonstration.labels.errorMessage')}</p>
            </div>
          </div>
        {/snippet}
      </DocsDemonstration>

      <!-- ── Anatomia ───────────────────────────────────────────────── -->
      <DocsAnatomy
        title={$tStore('anatomy.title')}
        items={[
          $tStore('anatomy.item1'),
          $tStore('anatomy.item2'),
          $tStore('anatomy.item3'),
          $tStore('anatomy.item4'),
        ]}
        structureLabel={$tStore('anatomy.structureLabel')}
        structureCode={`<div class="flex flex-col gap-1.5">
  <Label for="email">Email</Label>       <!-- Label obrigatório -->
  <Input
    id="email"
    type="email"                         <!-- type semântico -->
    placeholder="ex: joao@empresa.com"
    aria-describedby="email-hint"
  />
  <p id="email-hint" class="text-sm text-muted-foreground">
    Texto de apoio.
  </p>
</div>`}
      />

      <!-- ── Quando Usar ────────────────────────────────────────────── -->
      <DocsWhenToUse
        title={$tStore('usage.title')}
        guidelines={{
          title: $tStore('usage.guidelines.title'),
          items: [
            $tStore('usage.guidelines.item1'),
            $tStore('usage.guidelines.item2'),
            $tStore('usage.guidelines.item3'),
            $tStore('usage.guidelines.item4'),
            $tStore('usage.guidelines.item5'),
          ],
        }}
        scenarios={{
          title: $tStore('usage.scenarios.title'),
          cols: {
            scenario: $tStore('usage.scenarios.cols.scenario'),
            use: $tStore('usage.scenarios.cols.use'),
            alternative: $tStore('usage.scenarios.cols.alternative'),
          },
          items: [
            { s: $tStore('usage.scenarios.item1.s'), u: $tStore('usage.scenarios.item1.u'), a: $tStore('usage.scenarios.item1.a') },
            { s: $tStore('usage.scenarios.item2.s'), u: $tStore('usage.scenarios.item2.u'), a: $tStore('usage.scenarios.item2.a') },
            { s: $tStore('usage.scenarios.item3.s'), u: $tStore('usage.scenarios.item3.u'), a: $tStore('usage.scenarios.item3.a') },
            { s: $tStore('usage.scenarios.item4.s'), u: $tStore('usage.scenarios.item4.u'), a: $tStore('usage.scenarios.item4.a') },
            { s: $tStore('usage.scenarios.item5.s'), u: $tStore('usage.scenarios.item5.u'), a: $tStore('usage.scenarios.item5.a') },
            { s: $tStore('usage.scenarios.item6.s'), u: $tStore('usage.scenarios.item6.u'), a: $tStore('usage.scenarios.item6.a') },
          ],
        }}
        do={{
          title: $tStore('usage.do.title'),
          items: [
            $tStore('usage.do.item1'),
            $tStore('usage.do.item2'),
            $tStore('usage.do.item3'),
            $tStore('usage.do.item4'),
          ],
        }}
        dont={{
          title: $tStore('usage.dont.title'),
          items: [
            $tStore('usage.dont.item1'),
            $tStore('usage.dont.item2'),
            $tStore('usage.dont.item3'),
          ],
        }}
      />

      <!-- ── Do & Don't ─────────────────────────────────────────────── -->
      <DocsDoDont
        title={$tStore('doDont.title')}
        pairs={[
          {
            doLabel: $tNavStore('common.do'),
            dontLabel: $tNavStore('common.dont'),
            doCaption: $tStore('doDont.pair1.do'),
            dontCaption: $tStore('doDont.pair1.dont'),
            doPreview: doPair1,
            dontPreview: dontPair1,
          },
          {
            doLabel: $tNavStore('common.do'),
            dontLabel: $tNavStore('common.dont'),
            doCaption: $tStore('doDont.pair2.do'),
            dontCaption: $tStore('doDont.pair2.dont'),
            doPreview: doPair2,
            dontPreview: dontPair2,
          },
          {
            doLabel: $tNavStore('common.do'),
            dontLabel: $tNavStore('common.dont'),
            doCaption: $tStore('doDont.pair3.do'),
            dontCaption: $tStore('doDont.pair3.dont'),
            doPreview: doPair3,
            dontPreview: dontPair3,
          },
        ]}
      />

      {#snippet doPair1()}
        <div class="flex flex-col gap-1.5 w-full">
          <Label for="do1-email">Email</Label>
          <Input id="do1-email" type="email" placeholder="ex: joao@empresa.com" />
        </div>
      {/snippet}
      {#snippet dontPair1()}
        <div class="flex flex-col gap-1.5 w-full">
          <Label for="dont1-email">Email</Label>
          <Input id="dont1-email" type="email" placeholder="Digite seu email" />
        </div>
      {/snippet}

      {#snippet doPair2()}
        <div class="flex flex-col gap-1.5 w-full">
          <Label for="do2-email">Email</Label>
          <Input id="do2-email" type="email" placeholder="ex: joao@empresa.com" />
        </div>
      {/snippet}
      {#snippet dontPair2()}
        <div class="flex flex-col gap-1.5 w-full">
          <Label for="dont2-email">Email</Label>
          <Input id="dont2-email" type="text" placeholder="ex: joao@empresa.com" />
        </div>
      {/snippet}

      {#snippet doPair3()}
        <div class="flex flex-col gap-1.5 w-full">
          <Label for="do3-nome">Nome completo</Label>
          <Input id="do3-nome" type="text" placeholder="ex: João da Silva" />
        </div>
      {/snippet}
      {#snippet dontPair3()}
        <div class="flex flex-col gap-1.5 w-full">
          <Input type="text" placeholder="Nome completo" />
        </div>
      {/snippet}

      <!-- ── Importação ─────────────────────────────────────────────── -->
      <DocsImport
        title={$tStore('import.title')}
        description={$tStore('import.basic')}
        code={codeImportBasic}
        secondaryDescription={$tStore('import.withGroup')}
        secondaryCode={codeImportWithLabel}
      />

      <!-- ── Variantes (Tipos) ─────────────────────────────────────── -->
      <DocsVariants
        title={$tStore('variants.title')}
        componentSlug="input"
        items={[
          { name: 'text',     description: $tStore('variants.types.text'),     code: codeDefault,   preview: variantText     },
          { name: 'email',    description: $tStore('variants.types.email'),    code: codeEmail,     preview: variantEmail    },
          { name: 'password', description: $tStore('variants.types.password'), code: codePassword,  preview: variantPassword },
          { name: 'disabled', description: $tStore('states.disabled.behavior'), code: codeDisabled, preview: variantDisabled },
          { name: 'error',    description: $tStore('states.error.behavior'),   code: codeError,     preview: variantError    },
          { name: 'file',     description: $tStore('variants.types.file'),     code: codeFile,      preview: variantFile     },
        ]}
      />

      {#snippet variantText()}
        <div class="flex flex-col gap-1.5 w-64">
          <Label for="v-text">Nome completo</Label>
          <Input id="v-text" type="text" placeholder="ex: João da Silva" />
        </div>
      {/snippet}
      {#snippet variantEmail()}
        <div class="flex flex-col gap-1.5 w-64">
          <Label for="v-email">Email</Label>
          <Input id="v-email" type="email" placeholder="ex: joao@empresa.com" />
        </div>
      {/snippet}
      {#snippet variantPassword()}
        <div class="flex flex-col gap-1.5 w-64">
          <Label for="v-password">Senha</Label>
          <Input id="v-password" type="password" placeholder="Mínimo 8 caracteres" />
        </div>
      {/snippet}
      {#snippet variantDisabled()}
        <div class="flex flex-col gap-1.5 w-64">
          <Label for="v-disabled">Campo desabilitado</Label>
          <Input id="v-disabled" type="text" disabled placeholder="Não disponível" />
        </div>
      {/snippet}
      {#snippet variantError()}
        <div class="flex flex-col gap-1.5 w-64">
          <Label for="v-error">Email</Label>
          <Input id="v-error" type="email" aria-invalid="true" aria-describedby="v-error-msg" placeholder="ex: joao@empresa.com" />
          <p id="v-error-msg" class="text-sm text-destructive">Email inválido. Use o formato nome@dominio.com</p>
        </div>
      {/snippet}
      {#snippet variantFile()}
        <div class="flex flex-col gap-1.5 w-64">
          <Label for="v-file">Arquivo</Label>
          <Input id="v-file" type="file" />
        </div>
      {/snippet}

      <!-- ── Estados ────────────────────────────────────────────────── -->
      <DocsStates
        title={$tStore('states.title')}
        cols={{
          state: $tStore('states.cols.state'),
          trigger: $tStore('states.cols.trigger'),
          behavior: $tStore('states.cols.behavior'),
        }}
        items={[
          { label: $tStore('states.default.label'),  trigger: $tStore('states.default.trigger'),  behavior: $tStore('states.default.behavior')  },
          { label: $tStore('states.focus.label'),    trigger: $tStore('states.focus.trigger'),    behavior: $tStore('states.focus.behavior')    },
          { label: $tStore('states.disabled.label'), trigger: $tStore('states.disabled.trigger'), behavior: $tStore('states.disabled.behavior') },
          { label: $tStore('states.error.label'),    trigger: $tStore('states.error.trigger'),    behavior: $tStore('states.error.behavior')    },
          { label: $tStore('states.file.label'),     trigger: $tStore('states.file.trigger'),     behavior: $tStore('states.file.behavior')     },
        ]}
      />

      <!-- ── Propriedades ───────────────────────────────────────────── -->
      <DocsProps
        title={$tStore('props.title')}
        tables={[
          {
            title: $tStore('props.inputTitle'),
            cols: {
              prop: $tStore('props.table.prop'),
              type: $tStore('props.table.type'),
              default: $tStore('props.table.default'),
              required: $tStore('props.table.required'),
              description: $tStore('props.table.description'),
            },
            items: [
              { name: 'type',          type: 'HTMLInputTypeAttribute',    defaultValue: '"text"', required: 'Não', description: $tStore('props.table.type_prop')    },
              { name: 'placeholder',   type: 'string',                    defaultValue: '—',      required: 'Não', description: $tStore('props.table.placeholder')   },
              { name: 'disabled',      type: 'boolean',                   defaultValue: 'false',  required: 'Não', description: $tStore('props.table.disabled')      },
              { name: 'aria-invalid',  type: '"true" | "false"',          defaultValue: '—',      required: 'Não', description: $tStore('props.table.ariaInvalid')   },
              { name: 'autocomplete',  type: 'string',                    defaultValue: '—',      required: 'Não', description: $tStore('props.table.autoComplete')  },
              { name: 'class',         type: 'string',                    defaultValue: '—',      required: 'Não', description: $tStore('props.table.className')     },
            ],
          },
        ]}
        interfaceCode={interfaceCode}
        extensibilityTitle={$tStore('props.extensibilityTitle')}
        extensibilityNotes={$tStore('props.extensibility')}
      />

      <!-- ── Tokens ─────────────────────────────────────────────────── -->
      <DocsTokens
        title={$tStore('tokens.title')}
        cols={{
          token: $tStore('tokens.table.token'),
          value: $tStore('tokens.table.class'),
          description: $tStore('tokens.table.part'),
        }}
        items={[
          { token: '--height-default',   value: 'h-(--height-default)',               description: $tStore('tokens.table.height')       },
          { token: '--radius-input',     value: 'rounded-(--radius-input)',            description: $tStore('tokens.table.radius')       },
          { token: '--border-input',     value: 'border-input',                        description: $tStore('tokens.table.border')       },
          { token: '--ring',             value: 'focus-visible:border-ring',           description: $tStore('tokens.table.borderFocus')  },
          { token: '--ring / 50%',       value: 'focus-visible:ring-ring/50',          description: $tStore('tokens.table.ring')         },
          { token: '--destructive',      value: 'aria-invalid:border-destructive',     description: $tStore('tokens.table.borderError')  },
          { token: '--destructive / 20%', value: 'aria-invalid:ring-destructive/20',  description: $tStore('tokens.table.ringError')    },
          { token: '--input / 50%',      value: 'disabled:bg-input/50',               description: $tStore('tokens.table.bgDisabled')   },
          { token: '--input / 80%',      value: 'dark:disabled:bg-input/80',          description: $tStore('tokens.table.bgDisabledDark') },
          { token: '--muted-foreground', value: 'placeholder:text-muted-foreground',  description: $tStore('tokens.table.placeholder')  },
          { token: '--input / 30%',      value: 'dark:bg-input/30',                   description: $tStore('tokens.table.bgDark')       },
        ]}
        customizationTitle={$tStore('tokens.customizationTitle')}
        customizationCode={codeTokenCustomization}
      />

      <!-- ── Acessibilidade ─────────────────────────────────────────── -->
      <DocsAccessibility
        title={$tStore('accessibility.title')}
        summary={$tStore('accessibility.summary')}
        items={[
          $tStore('accessibility.item1'),
          $tStore('accessibility.item2'),
          $tStore('accessibility.item3'),
          $tStore('accessibility.item4'),
          $tStore('accessibility.item5'),
        ]}
        keyboardTitle="Navegação por Teclado"
        keyboardItems={[
          { key: 'Tab',        description: $tStore('accessibility.keyboard.tab')      },
          { key: 'Shift+Tab',  description: $tStore('accessibility.keyboard.shiftTab') },
          { key: 'Typing',     description: $tStore('accessibility.keyboard.typing')   },
          { key: 'Escape',     description: $tStore('accessibility.keyboard.escape')   },
        ]}
      />

      <!-- ── Relacionados ───────────────────────────────────────────── -->
      <DocsRelated
        title={$tStore('related.title')}
        items={[
          { name: 'Textarea',  description: $tStore('related.textarea'),  path: '?path=/docs/ui-textarea--docs'  },
          { name: 'InputOTP',  description: $tStore('related.inputOTP'),  path: '?path=/docs/ui-inputotp--docs'  },
          { name: 'Select',    description: $tStore('related.select'),    path: '?path=/docs/ui-select--docs'    },
          { name: 'Form',      description: $tStore('related.form'),      path: '?path=/docs/ui-form--docs'      },
          { name: 'Label',     description: $tStore('related.label'),     path: '?path=/docs/ui-label--docs'     },
        ]}
      />

      <!-- ── Notas ──────────────────────────────────────────────────── -->
      <DocsNotes
        title={$tStore('notes.title')}
        items={[
          { title: '', content: $tStore('notes.tip1') },
          { title: '', content: $tStore('notes.tip2') },
          { title: '', content: $tStore('notes.tip3') },
          { title: '', content: $tStore('notes.tip4') },
          { title: '', content: $tStore('notes.tip5') },
        ]}
      />

      <!-- ── Analytics ─────────────────────────────────────────────── -->
      <DocsAnalytics
        title={$tStore('analytics.title')}
        cols={{
          event: $tStore('analytics.table.event'),
          trigger: $tStore('analytics.table.trigger'),
          payload: $tStore('analytics.table.payload'),
        }}
        items={[
          { event: $tStore('analytics.table.fieldFocus'),    trigger: $tStore('analytics.table.fieldFocusTrigger'),    payload: $tStore('analytics.table.fieldFocusPayload')    },
          { event: $tStore('analytics.table.fieldBlur'),     trigger: $tStore('analytics.table.fieldBlurTrigger'),     payload: $tStore('analytics.table.fieldBlurPayload')     },
          { event: $tStore('analytics.table.fieldError'),    trigger: $tStore('analytics.table.fieldErrorTrigger'),    payload: $tStore('analytics.table.fieldErrorPayload')    },
          { event: $tStore('analytics.table.pageView'),      trigger: $tStore('analytics.table.pageViewTrigger'),      payload: $tStore('analytics.table.pageViewPayload')      },
          { event: $tStore('analytics.table.sectionViewed'), trigger: $tStore('analytics.table.sectionViewedTrigger'), payload: $tStore('analytics.table.sectionViewedPayload') },
          { event: $tStore('analytics.table.langSwitch'),    trigger: $tStore('analytics.table.langSwitchTrigger'),    payload: $tStore('analytics.table.langSwitchPayload')    },
        ]}
      />

      <!-- ── Testes ─────────────────────────────────────────────────── -->
      <DocsTestes
        title={$tStore('testes.title')}
        functional={{
          title: $tStore('testes.functional.title'),
          cols: {
            action: $tNavStore('common.userAction'),
            result: $tNavStore('common.expectedResult'),
            priority: $tNavStore('common.priority'),
          },
          items: [
            { action: $tStore('testes.functional.item1.action'), result: $tStore('testes.functional.item1.result'), priority: localPriority($tStore('testes.functional.item1.priority'), $tNavStore) },
            { action: $tStore('testes.functional.item2.action'), result: $tStore('testes.functional.item2.result'), priority: localPriority($tStore('testes.functional.item2.priority'), $tNavStore) },
            { action: $tStore('testes.functional.item3.action'), result: $tStore('testes.functional.item3.result'), priority: localPriority($tStore('testes.functional.item3.priority'), $tNavStore) },
            { action: $tStore('testes.functional.item4.action'), result: $tStore('testes.functional.item4.result'), priority: localPriority($tStore('testes.functional.item4.priority'), $tNavStore) },
            { action: $tStore('testes.functional.item5.action'), result: $tStore('testes.functional.item5.result'), priority: localPriority($tStore('testes.functional.item5.priority'), $tNavStore) },
            { action: $tStore('testes.functional.item6.action'), result: $tStore('testes.functional.item6.result'), priority: localPriority($tStore('testes.functional.item6.priority'), $tNavStore) },
            { action: $tStore('testes.functional.item7.action'), result: $tStore('testes.functional.item7.result'), priority: localPriority($tStore('testes.functional.item7.priority'), $tNavStore) },
            { action: $tStore('testes.functional.item8.action'), result: $tStore('testes.functional.item8.result'), priority: localPriority($tStore('testes.functional.item8.priority'), $tNavStore) },
          ],
        }}
        accessibility={{
          title: $tStore('testes.accessibility.title'),
          cols: {
            criterion: $tNavStore('common.criterion'),
            level: 'WCAG',
            how: $tNavStore('common.howToVerify'),
          },
          items: [
            { criterion: $tStore('testes.accessibility.item1'), level: 'AA', how: 'axe-core / testing-library' },
            { criterion: $tStore('testes.accessibility.item2'), level: 'AA', how: 'getByLabelText no testing-library' },
            { criterion: $tStore('testes.accessibility.item3'), level: 'AA', how: 'Inspecionar atributo aria-invalid no DOM' },
            { criterion: $tStore('testes.accessibility.item4'), level: 'AA', how: 'Inspecionar aria-describedby no DOM' },
            { criterion: $tStore('testes.accessibility.item5'), level: 'AA', how: 'axe-core / Lighthouse contrast audit' },
          ],
        }}
        visual={{
          title: $tStore('testes.visual.title'),
          cols: {
            story: $tNavStore('common.storyState'),
            priority: $tNavStore('common.priority'),
          },
          items: [
            { story: $tStore('testes.visual.item1.story'), priority: localPriority($tStore('testes.visual.item1.priority'), $tNavStore) },
            { story: $tStore('testes.visual.item2.story'), priority: localPriority($tStore('testes.visual.item2.priority'), $tNavStore) },
            { story: $tStore('testes.visual.item3.story'), priority: localPriority($tStore('testes.visual.item3.priority'), $tNavStore) },
            { story: $tStore('testes.visual.item4.story'), priority: localPriority($tStore('testes.visual.item4.priority'), $tNavStore) },
            { story: $tStore('testes.visual.item5.story'), priority: localPriority($tStore('testes.visual.item5.priority'), $tNavStore) },
          ],
        }}
      />
</DocsPageLayout>

// design-system-vue/src/components/docs/InputDocs.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, watch, ref } from 'vue';
import { useTranslation } from '@/lib/i18n';
import { useSeoEffect } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import DocsPageLayout    from '@/components/docs/shared/sections/DocsPageLayout.vue';
import uiTranslations   from '@/i18n/ui.json';
import inputTranslations from '@shared/content/input/translations.json';

import DocsHeader        from '@/components/docs/shared/sections/DocsHeader.vue';
import DocsDemonstration from '@/components/docs/shared/sections/DocsDemonstration.vue';
import DocsAnatomy       from '@/components/docs/shared/sections/DocsAnatomy.vue';
import DocsWhenToUse     from '@/components/docs/shared/sections/DocsWhenToUse.vue';
import DocsDoDont        from '@/components/docs/shared/sections/DocsDoDont.vue';
import DocsImport        from '@/components/docs/shared/sections/DocsImport.vue';
import DocsVariants      from '@/components/docs/shared/sections/DocsVariants.vue';
import DocsStates        from '@/components/docs/shared/sections/DocsStates.vue';
import DocsProps         from '@/components/docs/shared/sections/DocsProps.vue';
import DocsTokens        from '@/components/docs/shared/sections/DocsTokens.vue';
import DocsAccessibility from '@/components/docs/shared/sections/DocsAccessibility.vue';
import DocsRelated       from '@/components/docs/shared/sections/DocsRelated.vue';
import DocsNotes         from '@/components/docs/shared/sections/DocsNotes.vue';
import DocsAnalytics     from '@/components/docs/shared/sections/DocsAnalytics.vue';
import DocsTestes        from '@/components/docs/shared/sections/DocsTestes.vue';

// ─── i18n ─────────────────────────────────────────────────────────────────────

// IMPORTANTE: locale vem de useTranslation, NUNCA de useLocaleStore ou Pinia
const { t: tNav } = useTranslation(uiTranslations);
const { t: tContent, locale } = useTranslation(inputTranslations);

// ─── Helpers ──────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function localPriority(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

// ─── SEO & GEO ────────────────────────────────────────────────────────────────

useSeoEffect(computed(() => ({
  title: tContent('seo.title'),
  description: tContent('seo.description'),
  locale: locale.value as 'pt-BR' | 'en' | 'es',
  componentSlug: 'input',
})));

// ─── Analytics — page view ────────────────────────────────────────────────────

watch(locale, (newLocale) => {
  track('docs_page_view', {
    component_name: 'input',
    locale: newLocale as 'pt-BR' | 'en' | 'es',
    page_title: tContent('seo.title'),
  });
}, { immediate: true });

// ─── Analytics — section view ─────────────────────────────────────────────────

const activeSection = ref('demonstracao');

function handleSectionChange(id: string) {
  activeSection.value = id;
  track('docs_section_viewed', {
    section_id: id,
    component_name: 'input',
    locale: locale.value as 'pt-BR' | 'en' | 'es',
  });
}

// ─── Navigation groups ────────────────────────────────────────────────────────

const navGroups = computed(() => [
  {
    label: tNav('nav.overview'),
    sections: [
      { id: 'demonstracao', label: tNav('nav.demonstration') },
      { id: 'anatomia',     label: tNav('nav.anatomy')      },
      { id: 'quando-usar',  label: tNav('nav.usage')        },
      { id: 'do-dont',      label: tNav('nav.doDont')       },
    ],
  },
  {
    label: tNav('nav.techRef'),
    sections: [
      { id: 'importacao',   label: tNav('nav.import')   },
      { id: 'variantes',    label: tNav('nav.variants') },
      { id: 'estados',      label: tNav('nav.states')   },
      { id: 'propriedades', label: tNav('nav.props')    },
      { id: 'tokens',       label: tNav('nav.tokens')   },
    ],
  },
  {
    label: tNav('nav.context'),
    sections: [
      { id: 'acessibilidade', label: tNav('nav.accessibility') },
      { id: 'relacionados',   label: tNav('nav.related')       },
      { id: 'notas',          label: tNav('nav.notes')         },
    ],
  },
  {
    label: tNav('nav.quality'),
    sections: [
      { id: 'analytics', label: tNav('nav.analytics') },
      { id: 'testes',    label: tNav('nav.testes')    },
    ],
  },
]);

const allSectionIds = computed(() => navGroups.value.flatMap(g => g.sections.map(s => s.id)));

// ─── IntersectionObserver ─────────────────────────────────────────────────────

let observer: IntersectionObserver | null = null;

onMounted(() => {
  observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) { handleSectionChange(entry.target.id); break; }
      }
    },
    { rootMargin: '-20% 0px -70% 0px', threshold: 0 }
  );
  allSectionIds.value.forEach((id) => {
    const el = document.getElementById(id);
    if (el) observer!.observe(el);
  });
});

onUnmounted(() => {
  observer?.disconnect();
  observer = null;
});

// ─── Code strings ─────────────────────────────────────────────────────────────

const codeImportBasic = `import { Input } from "@/components/ui/input";`;

const codeDefault = `<Input type="text" placeholder="ex: João da Silva" />`;

const codeWithLabel = `<div class="space-y-1.5">
  <Label for="nome">Nome completo</Label>
  <Input id="nome" type="text" placeholder="ex: João da Silva" />
</div>`;

const codeEmail = `<Input type="email" placeholder="ex: joao@empresa.com" />`;

const codePassword = `<Input type="password" placeholder="Mínimo 8 caracteres" />`;

const codeNumber = `<Input type="number" placeholder="0" />`;

const codeDisabled = `<Input type="text" placeholder="Não disponível" disabled />`;

const codeError = `<Input type="email" aria-invalid="true" placeholder="ex: joao@empresa.com" />`;

const codeFile = `<Input type="file" />`;

const codeCustomizationTokens = `/* Em globals.css — sobrescrever tokens de tema */
:root {
  --height-default: 2.5rem;  /* altura do campo */
  --radius-input: 0.375rem;  /* border-radius */
}`;

const interfaceCode = `// Input
interface InputProps {
  type?: string;            // Tipo HTML do input (text, email, password...)
  placeholder?: string;     // Texto de exemplo do formato esperado
  disabled?: boolean;       // Desabilita o campo
  class?: string;           // Classes Tailwind adicionais
  modelValue?: string | number;
  defaultValue?: string | number;
}`;

// ─── Computed data ────────────────────────────────────────────────────────────

const anatomyItems = computed(() => [
  tContent('anatomy.item1'),
  tContent('anatomy.item2'),
  tContent('anatomy.item3'),
  tContent('anatomy.item4'),
]);

const variantItems = computed(() => [
  { name: 'text',     description: tContent('variants.types.text'),     code: codeDefault   },
  { name: 'email',    description: tContent('variants.types.email'),    code: codeEmail     },
  { name: 'password', description: tContent('variants.types.password'), code: codePassword  },
  { name: 'number',   description: tContent('variants.types.number'),   code: codeNumber    },
  { name: 'file',     description: tContent('variants.types.file'),     code: codeFile      },
]);

const stateItems = computed(() => [
  { label: tContent('states.default.label'),  trigger: tContent('states.default.trigger'),  behavior: tContent('states.default.behavior')  },
  { label: tContent('states.focus.label'),    trigger: tContent('states.focus.trigger'),    behavior: tContent('states.focus.behavior')    },
  { label: tContent('states.disabled.label'), trigger: tContent('states.disabled.trigger'), behavior: tContent('states.disabled.behavior') },
  { label: tContent('states.error.label'),    trigger: tContent('states.error.trigger'),    behavior: tContent('states.error.behavior')    },
  { label: tContent('states.file.label'),     trigger: tContent('states.file.trigger'),     behavior: tContent('states.file.behavior')     },
]);

const propCols = computed(() => ({
  prop: tContent('props.table.prop'),
  type: tContent('props.table.type'),
  default: tContent('props.table.default'),
  required: tContent('props.table.required'),
  description: tContent('props.table.description'),
}));

const inputPropItems = computed(() => [
  { name: 'type',        type: 'string',                     defaultValue: '"text"', required: 'Não', description: tContent('props.table.type_prop')   },
  { name: 'placeholder', type: 'string',                     defaultValue: '—',      required: 'Não', description: tContent('props.table.placeholder')  },
  { name: 'disabled',    type: 'boolean',                    defaultValue: 'false',  required: 'Não', description: tContent('props.table.disabled')     },
  { name: 'class',       type: 'string',                     defaultValue: '—',      required: 'Não', description: tContent('props.table.className')    },
  { name: 'aria-invalid', type: '"true" | "false"',          defaultValue: '—',      required: 'Não', description: tContent('props.table.ariaInvalid')  },
  { name: 'autoComplete', type: 'string',                    defaultValue: '—',      required: 'Não', description: tContent('props.table.autoComplete') },
]);

const tokenRows = computed(() => [
  { token: '--height-default', value: 'h-(--height-default)',        description: tContent('tokens.table.height')       },
  { token: '--radius-input',   value: 'rounded-(--radius-input)',    description: tContent('tokens.table.radius')       },
  { token: '--border-input',   value: 'border-input',                description: tContent('tokens.table.border')       },
  { token: '--ring',           value: 'focus-visible:border-ring',   description: tContent('tokens.table.borderFocus')  },
  { token: '--ring',           value: 'focus-visible:ring-ring/50',  description: tContent('tokens.table.ring')         },
  { token: '--destructive',    value: 'aria-invalid:border-destructive', description: tContent('tokens.table.borderError') },
  { token: '--destructive',    value: 'aria-invalid:ring-destructive/20', description: tContent('tokens.table.ringError') },
  { token: '--input',          value: 'disabled:bg-input/50',        description: tContent('tokens.table.bgDisabled')   },
]);

const accessibilityItems = computed(() => [
  tContent('accessibility.item1'),
  tContent('accessibility.item2'),
  tContent('accessibility.item3'),
  tContent('accessibility.item4'),
  tContent('accessibility.item5'),
]);

const keyboardItems = computed(() => [
  { key: 'Tab',        description: tContent('accessibility.keyboard.tab')       },
  { key: 'Shift+Tab',  description: tContent('accessibility.keyboard.shiftTab')  },
  { key: 'Typing',     description: tContent('accessibility.keyboard.typing')    },
  { key: 'Escape',     description: tContent('accessibility.keyboard.escape')    },
]);

const relatedItems = computed(() => [
  { name: 'Textarea',  description: tContent('related.textarea'),  path: '?path=/docs/ui-textarea--docs'  },
  { name: 'InputOTP',  description: tContent('related.inputOTP'),  path: '?path=/docs/ui-inputotp--docs'  },
  { name: 'Select',    description: tContent('related.select'),    path: '?path=/docs/ui-select--docs'    },
  { name: 'Form',      description: tContent('related.form'),      path: '?path=/docs/ui-form--docs'      },
  { name: 'Label',     description: tContent('related.label'),     path: '?path=/docs/ui-label--docs'     },
]);

const noteItems = computed(() => [
  { title: '', content: tContent('notes.tip1') },
  { title: '', content: tContent('notes.tip2') },
  { title: '', content: tContent('notes.tip3') },
  { title: '', content: tContent('notes.tip4') },
  { title: '', content: tContent('notes.tip5') },
]);

const analyticsItems = computed(() => [
  { event: tContent('analytics.table.fieldFocus'),   trigger: tContent('analytics.table.fieldFocusTrigger'),   payload: tContent('analytics.table.fieldFocusPayload')   },
  { event: tContent('analytics.table.fieldBlur'),    trigger: tContent('analytics.table.fieldBlurTrigger'),    payload: tContent('analytics.table.fieldBlurPayload')    },
  { event: tContent('analytics.table.fieldError'),   trigger: tContent('analytics.table.fieldErrorTrigger'),   payload: tContent('analytics.table.fieldErrorPayload')   },
  { event: tContent('analytics.table.pageView'),     trigger: tContent('analytics.table.pageViewTrigger'),     payload: tContent('analytics.table.pageViewPayload')     },
  { event: tContent('analytics.table.sectionViewed'), trigger: tContent('analytics.table.sectionViewedTrigger'), payload: tContent('analytics.table.sectionViewedPayload') },
  { event: tContent('analytics.table.langSwitch'),   trigger: tContent('analytics.table.langSwitchTrigger'),   payload: tContent('analytics.table.langSwitchPayload')   },
]);

const a11yCritCols = computed(() => ({
  criterion: tNav('common.criterion'),
  level: 'WCAG',
  how: tNav('common.howToVerify'),
}));

const functionalTestItems = computed(() => [
  { action: tContent('testes.functional.item1.action'), result: tContent('testes.functional.item1.result'), priority: localPriority(tContent('testes.functional.item1.priority')) },
  { action: tContent('testes.functional.item2.action'), result: tContent('testes.functional.item2.result'), priority: localPriority(tContent('testes.functional.item2.priority')) },
  { action: tContent('testes.functional.item3.action'), result: tContent('testes.functional.item3.result'), priority: localPriority(tContent('testes.functional.item3.priority')) },
  { action: tContent('testes.functional.item4.action'), result: tContent('testes.functional.item4.result'), priority: localPriority(tContent('testes.functional.item4.priority')) },
  { action: tContent('testes.functional.item5.action'), result: tContent('testes.functional.item5.result'), priority: localPriority(tContent('testes.functional.item5.priority')) },
  { action: tContent('testes.functional.item6.action'), result: tContent('testes.functional.item6.result'), priority: localPriority(tContent('testes.functional.item6.priority')) },
  { action: tContent('testes.functional.item7.action'), result: tContent('testes.functional.item7.result'), priority: localPriority(tContent('testes.functional.item7.priority')) },
  { action: tContent('testes.functional.item8.action'), result: tContent('testes.functional.item8.result'), priority: localPriority(tContent('testes.functional.item8.priority')) },
]);

const a11yTestItems = computed(() => [
  { criterion: tContent('testes.accessibility.item1'), level: 'WCAG 2.1 AA', how: 'axe-core' },
  { criterion: tContent('testes.accessibility.item2'), level: 'WCAG 2.1 AA', how: 'getByLabelText' },
  { criterion: tContent('testes.accessibility.item3'), level: 'WCAG 3.3.1',  how: 'aria-invalid' },
  { criterion: tContent('testes.accessibility.item4'), level: 'WCAG 1.3.1',  how: 'aria-describedby' },
  { criterion: tContent('testes.accessibility.item5'), level: 'WCAG 1.4.3',  how: 'Contrast Analyzer' },
]);

const visualTestItems = computed(() => [
  { story: tContent('testes.visual.item1.story'), priority: localPriority(tContent('testes.visual.item1.priority')) },
  { story: tContent('testes.visual.item2.story'), priority: localPriority(tContent('testes.visual.item2.priority')) },
  { story: tContent('testes.visual.item3.story'), priority: localPriority(tContent('testes.visual.item3.priority')) },
  { story: tContent('testes.visual.item4.story'), priority: localPriority(tContent('testes.visual.item4.priority')) },
  { story: tContent('testes.visual.item5.story'), priority: localPriority(tContent('testes.visual.item5.priority')) },
]);
</script>

<template>
  <DocsPageLayout :nav-groups="navGroups" :active-section="activeSection">
    <template #header>
      <DocsHeader
        :title="tContent('title')"
        :description="tContent('description')"
        :category="tContent('category')"
        :type="tContent('type')"
        install-note="npx shadcn-vue@latest add input"
      />
    </template>

    <!-- ── Demonstração ───────────────────────────────────────────── -->
    <DocsDemonstration :title="tContent('demonstration.title')">
      <div class="w-full max-w-sm space-y-4">
        <div class="space-y-1.5">
          <Label for="demo-nome">{{ tContent('demonstration.labels.defaultLabel') }}</Label>
          <Input id="demo-nome" type="text" :placeholder="tContent('demonstration.labels.defaultPlaceholder')" />
        </div>
        <div class="space-y-1.5">
          <Label for="demo-email">{{ tContent('demonstration.labels.emailLabel') }}</Label>
          <Input id="demo-email" type="email" :placeholder="tContent('demonstration.labels.emailPlaceholder')" />
        </div>
        <div class="space-y-1.5">
          <Label for="demo-senha">{{ tContent('demonstration.labels.passwordLabel') }}</Label>
          <Input id="demo-senha" type="password" :placeholder="tContent('demonstration.labels.passwordPlaceholder')" />
        </div>
        <div class="space-y-1.5">
          <Label for="demo-disabled">{{ tContent('demonstration.labels.disabledLabel') }}</Label>
          <Input id="demo-disabled" type="text" :placeholder="tContent('demonstration.labels.disabledPlaceholder')" disabled />
        </div>
        <div class="space-y-1.5">
          <Label for="demo-error">{{ tContent('demonstration.labels.errorLabel') }}</Label>
          <Input id="demo-error" type="email" :placeholder="tContent('demonstration.labels.errorPlaceholder')" aria-invalid="true" />
          <p class="text-sm text-destructive">{{ tContent('demonstration.labels.errorMessage') }}</p>
        </div>
      </div>
    </DocsDemonstration>

    <!-- ── Anatomia ───────────────────────────────────────────────── -->
    <DocsAnatomy
      :title="tContent('anatomy.title')"
      :items="anatomyItems"
      :structure-label="tContent('anatomy.structureLabel')"
      :structure-code="tContent('anatomy.structureCode')"
    />

    <!-- ── Quando Usar ────────────────────────────────────────────── -->
    <DocsWhenToUse
      :title="tContent('usage.title')"
      :guidelines="{
        title: tContent('usage.guidelines.title'),
        items: [
          tContent('usage.guidelines.item1'),
          tContent('usage.guidelines.item2'),
          tContent('usage.guidelines.item3'),
          tContent('usage.guidelines.item4'),
          tContent('usage.guidelines.item5'),
        ],
      }"
      :scenarios="{
        title: tContent('usage.scenarios.title'),
        cols: {
          scenario: tContent('usage.scenarios.cols.scenario'),
          use: tContent('usage.scenarios.cols.use'),
          alternative: tContent('usage.scenarios.cols.alternative'),
        },
        items: [
          { s: tContent('usage.scenarios.item1.s'), u: tContent('usage.scenarios.item1.u'), a: tContent('usage.scenarios.item1.a') },
          { s: tContent('usage.scenarios.item2.s'), u: tContent('usage.scenarios.item2.u'), a: tContent('usage.scenarios.item2.a') },
          { s: tContent('usage.scenarios.item3.s'), u: tContent('usage.scenarios.item3.u'), a: tContent('usage.scenarios.item3.a') },
          { s: tContent('usage.scenarios.item4.s'), u: tContent('usage.scenarios.item4.u'), a: tContent('usage.scenarios.item4.a') },
          { s: tContent('usage.scenarios.item5.s'), u: tContent('usage.scenarios.item5.u'), a: tContent('usage.scenarios.item5.a') },
          { s: tContent('usage.scenarios.item6.s'), u: tContent('usage.scenarios.item6.u'), a: tContent('usage.scenarios.item6.a') },
        ],
      }"
      :do="{ title: tContent('usage.do.title'), items: [tContent('usage.do.item1'), tContent('usage.do.item2'), tContent('usage.do.item3'), tContent('usage.do.item4')] }"
      :dont="{ title: tContent('usage.dont.title'), items: [tContent('usage.dont.item1'), tContent('usage.dont.item2'), tContent('usage.dont.item3')] }"
    />

    <!-- ── Do & Don't ─────────────────────────────────────────────── -->
    <DocsDoDont
      :title="tContent('doDont.title')"
      :pairs="[
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair1.do'), dontCaption: tContent('doDont.pair1.dont') },
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair2.do'), dontCaption: tContent('doDont.pair2.dont') },
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair3.do'), dontCaption: tContent('doDont.pair3.dont') },
      ]"
    >
      <!-- Par 1: placeholder como exemplo vs instrução -->
      <template #do-preview-0>
        <div class="space-y-1.5 w-full max-w-xs">
          <Label for="dodont-do-1">Email</Label>
          <Input id="dodont-do-1" type="email" placeholder="ex: joao@empresa.com" />
        </div>
      </template>
      <template #dont-preview-0>
        <div class="space-y-1.5 w-full max-w-xs">
          <Label for="dodont-dont-1">Email</Label>
          <Input id="dodont-dont-1" type="email" placeholder="Digite seu email" />
        </div>
      </template>

      <!-- Par 2: type=email vs type=text -->
      <template #do-preview-1>
        <div class="space-y-1.5 w-full max-w-xs">
          <Label for="dodont-do-2">Email</Label>
          <Input id="dodont-do-2" type="email" placeholder="ex: joao@empresa.com" />
        </div>
      </template>
      <template #dont-preview-1>
        <div class="space-y-1.5 w-full max-w-xs">
          <Label for="dodont-dont-2">Email</Label>
          <Input id="dodont-dont-2" type="text" placeholder="ex: joao@empresa.com" />
        </div>
      </template>

      <!-- Par 3: com label visível vs sem label -->
      <template #do-preview-2>
        <div class="space-y-1.5 w-full max-w-xs">
          <Label for="dodont-do-3">Nome completo</Label>
          <Input id="dodont-do-3" type="text" placeholder="ex: João da Silva" />
        </div>
      </template>
      <template #dont-preview-2>
        <div class="w-full max-w-xs">
          <Input type="text" placeholder="Nome completo" />
        </div>
      </template>
    </DocsDoDont>

    <!-- ── Importação ─────────────────────────────────────────────── -->
    <DocsImport
      :title="tContent('import.title')"
      :description="tContent('import.basic')"
      :code="codeImportBasic"
      component-slug="input"
    />

    <!-- ── Variantes (Tipos) ──────────────────────────────────────── -->
    <DocsVariants :title="tContent('variants.title')" :items="variantItems" component-slug="input">
      <!-- text -->
      <template #variant-preview-0>
        <div class="w-full max-w-xs">
          <Input type="text" placeholder="ex: João da Silva" />
        </div>
      </template>
      <!-- email -->
      <template #variant-preview-1>
        <div class="w-full max-w-xs">
          <Input type="email" placeholder="ex: joao@empresa.com" />
        </div>
      </template>
      <!-- password -->
      <template #variant-preview-2>
        <div class="w-full max-w-xs">
          <Input type="password" placeholder="Mínimo 8 caracteres" />
        </div>
      </template>
      <!-- number -->
      <template #variant-preview-3>
        <div class="w-full max-w-xs">
          <Input type="number" placeholder="0" />
        </div>
      </template>
      <!-- file -->
      <template #variant-preview-4>
        <div class="w-full max-w-xs">
          <Input type="file" />
        </div>
      </template>
    </DocsVariants>

    <!-- ── Estados ───────────────────────────────────────────────── -->
    <DocsStates
      :title="tContent('states.title')"
      :cols="{
        state: tContent('states.cols.state'),
        trigger: tContent('states.cols.trigger'),
        behavior: tContent('states.cols.behavior'),
      }"
      :items="stateItems"
    />

    <!-- ── Propriedades ───────────────────────────────────────────── -->
    <DocsProps
      :title="tContent('props.title')"
      :tables="[
        { title: tContent('props.inputTitle'), cols: propCols, items: inputPropItems },
      ]"
      :interface-code="interfaceCode"
      :extensibility-title="tContent('props.extensibilityTitle')"
      :extensibility-notes="tContent('props.extensibility')"
    />

    <!-- ── Tokens ─────────────────────────────────────────────────── -->
    <DocsTokens
      :title="tContent('tokens.title')"
      :cols="{
        token: tContent('tokens.table.token'),
        value: tContent('tokens.table.class'),
        description: tContent('tokens.table.part'),
      }"
      :items="tokenRows"
      :customization-title="tContent('tokens.customizationTitle')"
      :customization-code="codeCustomizationTokens"
    />

    <!-- ── Acessibilidade ─────────────────────────────────────────── -->
    <DocsAccessibility
      :title="tContent('accessibility.title')"
      :summary="tContent('accessibility.summary')"
      :items="accessibilityItems"
      :keyboard-title="tNav('nav.accessibility')"
      :keyboard-items="keyboardItems"
    />

    <!-- ── Relacionados ───────────────────────────────────────────── -->
    <DocsRelated
      :title="tContent('related.title')"
      :items="relatedItems"
      component-slug="input"
    />

    <!-- ── Notas ──────────────────────────────────────────────────── -->
    <DocsNotes
      :title="tContent('notes.title')"
      :items="noteItems"
      component-slug="input"
    />

    <!-- ── Analytics ─────────────────────────────────────────────── -->
    <DocsAnalytics
      :title="tContent('analytics.title')"
      :cols="{
        event: tContent('analytics.table.event'),
        trigger: tContent('analytics.table.trigger'),
        payload: tContent('analytics.table.payload'),
      }"
      :items="analyticsItems"
    />

    <!-- ── Testes ─────────────────────────────────────────────────── -->
    <DocsTestes
      :title="tContent('testes.title')"
      :functional="{
        title: tContent('testes.functional.title'),
        cols: {
          action: tNav('common.userAction'),
          result: tNav('common.expectedResult'),
          priority: tNav('common.priority'),
        },
        items: functionalTestItems,
      }"
      :accessibility="{
        title: tContent('testes.accessibility.title'),
        cols: a11yCritCols,
        items: a11yTestItems,
      }"
      :visual="{
        title: tContent('testes.visual.title'),
        cols: { story: tNav('common.storyState'), priority: tNav('common.priority') },
        items: visualTestItems,
      }"
    />
  </DocsPageLayout>
</template>
