// design-system-svelte/src/components/docs/LabelDocs.svelte
<script lang="ts">
  import { Label } from '@/components/ui/label';
  import { Input } from '@/components/ui/input';
  import { Checkbox } from '@/components/ui/checkbox';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import { sanitizeHtml } from '@/lib/sanitize-html';
  import DocsPageLayout    from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader,
    DocsDemonstration,
    DocsAnatomy,
    DocsWhenToUse,
    DocsDoDont,
    DocsImport,
    DocsVariants,
    DocsStates,
    DocsProps,
    DocsTokens,
    DocsAccessibility,
    DocsRelated,
    DocsNotes,
    DocsAnalytics,
    DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import labelTranslations from '@shared/content/label/translations.json';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(labelTranslations);

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'label',
    });
    track('docs_page_view', {
      component_name: 'label',
      locale: l,
      page_title: `${t('title')} · Design System`,
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────

  let activeSection = $state('demonstracao');

  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')   },
        { id: 'variantes',    label: tNav('nav.variants') },
        { id: 'estados',      label: tNav('nav.states')   },
        { id: 'propriedades', label: tNav('nav.props')    },
        { id: 'tokens',       label: tNav('nav.tokens')   },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  $effect(() => {
    const ids = NAV_GROUPS.flatMap(g => g.sections.map(s => s.id));
    const observer = new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          activeSection = entry.target.id;
          track('docs_section_viewed', { section_id: entry.target.id, component_name: 'label', locale: $locale });
          break;
        }
      }
    }, { rootMargin: '-20% 0px -70% 0px', threshold: 0 });
    for (const id of ids) {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    }
    return () => observer.disconnect();
  });

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  function stripHtml(s: string) {
    return s.replace(/<[^>]*>/g, '');
  }

  const priorityKeyMap: Record<string, string> = { high: 'common.high', medium: 'common.medium', low: 'common.low' };
  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  // ─── Code strings ────────────────────────────────────────────────────────────

  const codeImport = `import { Label } from "@/components/ui/label";`;

  const codeDefault = `<Label for="nome">Nome completo</Label>
<Input id="nome" type="text" />`;

  const codeRequired = `<Label for="email">
  Email profissional
  <span class="text-destructive" aria-hidden="true">*</span>
</Label>
<Input id="email" type="email" aria-required="true" />`;

  const codeDisabled = `<!-- Input com peer + disabled dispara peer-disabled no Label -->
<Input id="cpf" disabled class="peer" />
<Label for="cpf">CPF</Label>`;

  const codeCustomization = `<!-- Personalização via class -->
<Label for="field" class="text-muted-foreground">
  Rótulo secundário
</Label>`;

  const interfaceCode = `// Label — Svelte 5
interface LabelProps {
  for?: string;       // associa ao campo com id correspondente
  class?: string;     // classes Tailwind adicionais
  children?: Snippet; // texto do rótulo
  // + todos os atributos HTML nativos de <label>
}`;
</script>

<DocsPageLayout navGroups={NAV_GROUPS} {activeSection} componentSlug="label">
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
      installNote="npx shadcn-svelte@latest add label"
    />
  {/snippet}

  <!-- ── Demonstração ───────────────────────────────────────────── -->
  <DocsDemonstration title={$tStore('demonstration.title')} componentSlug="label">
    {#snippet children()}
      <div class="w-full space-y-6">
        <!-- Padrão -->
        <div class="flex flex-col gap-2">
          <Label for="demo-default">{$tStore('demonstration.labels.default')}</Label>
          <Input id="demo-default" type="text" />
        </div>

        <!-- Required -->
        <div class="flex flex-col gap-2">
          <Label for="demo-required">
            {$tStore('demonstration.labels.required')}
            <span class="text-destructive" aria-hidden="true">{$tStore('demonstration.labels.requiredMarker')}</span>
          </Label>
          <Input id="demo-required" type="email" aria-required="true" />
        </div>

        <!-- Disabled via peer -->
        <div class="flex flex-col gap-2">
          <Input id="demo-disabled" disabled class="peer" />
          <Label for="demo-disabled">{$tStore('demonstration.labels.disabled')}</Label>
        </div>
      </div>
    {/snippet}
  </DocsDemonstration>

  <!-- ── Anatomia ───────────────────────────────────────────────── -->
  <DocsAnatomy
    title={$tStore('anatomy.title')}
    items={[
      $tStore('anatomy.item1'),
      $tStore('anatomy.item2'),
      $tStore('anatomy.item3'),
    ]}
    structureLabel={$tStore('anatomy.structureLabel')}
    structureCode={$tStore('anatomy.structureCode')}
  />

  <!-- ── Quando Usar ────────────────────────────────────────────── -->
  <DocsWhenToUse
    title={$tStore('usage.title')}
    guidelines={{
      title: $tStore('usage.guidelines.title'),
      items: [
        $tStore('usage.guidelines.item1'),
        $tStore('usage.guidelines.item2'),
        $tStore('usage.guidelines.item3'),
        $tStore('usage.guidelines.item4'),
      ],
    }}
    scenarios={{
      title: $tStore('usage.scenarios.title'),
      cols: {
        scenario: $tStore('usage.scenarios.cols.scenario'),
        use: $tStore('usage.scenarios.cols.use'),
        alternative: $tStore('usage.scenarios.cols.alternative'),
      },
      items: [
        { s: $tStore('usage.scenarios.item1.s'), u: $tStore('usage.scenarios.item1.u'), a: $tStore('usage.scenarios.item1.a') },
        { s: $tStore('usage.scenarios.item2.s'), u: $tStore('usage.scenarios.item2.u'), a: $tStore('usage.scenarios.item2.a') },
        { s: $tStore('usage.scenarios.item3.s'), u: $tStore('usage.scenarios.item3.u'), a: $tStore('usage.scenarios.item3.a') },
        { s: $tStore('usage.scenarios.item4.s'), u: $tStore('usage.scenarios.item4.u'), a: $tStore('usage.scenarios.item4.a') },
      ],
    }}
    do={{
      title: $tStore('usage.do.title'),
      items: [
        $tStore('usage.do.item1'),
        $tStore('usage.do.item2'),
        $tStore('usage.do.item3'),
      ],
    }}
    dont={{
      title: $tStore('usage.dont.title'),
      items: [
        $tStore('usage.dont.item1'),
        $tStore('usage.dont.item2'),
        $tStore('usage.dont.item3'),
      ],
    }}
  />

  <!-- ── Do & Don't ─────────────────────────────────────────────── -->
  <DocsDoDont
    title={$tStore('doDont.title')}
    pairs={[
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair1.do'),
        dontCaption: $tStore('doDont.pair1.dont'),
        doPreview: doPair1,
        dontPreview: dontPair1,
      },
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair2.do'),
        dontCaption: $tStore('doDont.pair2.dont'),
        doPreview: doPair2,
        dontPreview: dontPair2,
      },
    ]}
  />

  {#snippet doPair1()}
    <div class="flex flex-col gap-2 w-full">
      <Label for="dodont-do-1">Nome completo</Label>
      <Input id="dodont-do-1" type="text" />
    </div>
  {/snippet}
  {#snippet dontPair1()}
    <div class="flex flex-col gap-2 w-full">
      <Label>Nome completo</Label>
      <Input type="text" />
    </div>
  {/snippet}
  {#snippet doPair2()}
    <div class="flex flex-col gap-2 w-full">
      <Label for="dodont-do-2">Email profissional</Label>
      <Input id="dodont-do-2" type="email" />
    </div>
  {/snippet}
  {#snippet dontPair2()}
    <div class="flex flex-col gap-2 w-full">
      <Input type="email" placeholder="Informe seu email" />
    </div>
  {/snippet}

  <!-- ── Importação ─────────────────────────────────────────────── -->
  <DocsImport
    title={$tStore('import.title')}
    code={codeImport}
    componentSlug="label"
  />

  <!-- ── Variantes ──────────────────────────────────────────────── -->
  <DocsVariants
    title={$tStore('variants.title')}
    componentSlug="label"
    items={[
      {
        name: 'default',
        description: stripHtml($tStore('variants.default.description')),
        code: codeDefault,
        preview: variantDefault,
      },
    ]}
  />

  {#snippet variantDefault()}
    <div class="flex flex-col gap-2 w-full">
      <Label for="variant-default">Nome completo</Label>
      <Input id="variant-default" type="text" />
    </div>
  {/snippet}

  <!-- ── Estados ────────────────────────────────────────────────── -->
  <DocsStates
    title={$tStore('states.title')}
    cols={{
      state: $tStore('states.cols.state'),
      trigger: $tStore('states.cols.trigger'),
      behavior: $tStore('states.cols.behavior'),
    }}
    items={[
      {
        label: $tStore('states.default.label'),
        trigger: stripHtml($tStore('states.default.trigger')),
        behavior: $tStore('states.default.behavior'),
      },
      {
        label: $tStore('states.disabled.label'),
        trigger: stripHtml($tStore('states.disabled.trigger')),
        behavior: stripHtml($tStore('states.disabled.behavior')),
      },
      {
        label: $tStore('states.required.label'),
        trigger: $tStore('states.required.trigger'),
        behavior: stripHtml($tStore('states.required.behavior')),
      },
    ]}
  />

  <!-- ── Propriedades ───────────────────────────────────────────── -->
  <DocsProps
    title={$tStore('props.title')}
    tables={[
      {
        cols: {
          prop: $tStore('props.table.prop'),
          type: $tStore('props.table.type'),
          default: $tStore('props.table.default'),
          required: $tStore('props.table.required'),
          description: $tStore('props.table.description'),
        },
        items: [
          { name: 'for',      type: 'string',  defaultValue: '—', required: 'Não', description: stripHtml($tStore('props.table.htmlFor'))   },
          { name: 'class',    type: 'string',  defaultValue: '—', required: 'Não', description: $tStore('props.table.className')             },
          { name: 'children', type: 'Snippet', defaultValue: '—', required: 'Não', description: $tStore('props.table.children')              },
        ],
      },
    ]}
    interfaceCode={interfaceCode}
    extensibilityNotes={$tStore('props.note')}
  />

  <!-- ── Tokens ─────────────────────────────────────────────────── -->
  <DocsTokens
    title={$tStore('tokens.title')}
    cols={{
      token: $tStore('tokens.table.token'),
      value: $tStore('tokens.table.class'),
      description: $tStore('tokens.table.part'),
    }}
    items={[
      { token: '--foreground',  value: 'text-foreground',  description: $tStore('tokens.table.foreground')       },
      { token: '--muted',       value: 'opacity-50',       description: $tStore('tokens.table.foregroundMuted')  },
      { token: '--font-size-sm', value: 'text-sm',         description: $tStore('tokens.table.fontSize')         },
      { token: '--font-weight',  value: 'font-medium',     description: $tStore('tokens.table.fontWeight')       },
      { token: '--leading-none', value: 'leading-none',    description: $tStore('tokens.table.lineHeight')       },
      { token: '--destructive',  value: 'text-destructive', description: $tStore('tokens.table.destructive')     },
    ]}
    customizationTitle="Personalização"
    customizationCode={codeCustomization}
  />

  <!-- ── Acessibilidade ─────────────────────────────────────────── -->
  <DocsAccessibility
    title={$tStore('accessibility.title')}
    summary={$tStore('accessibility.summary')}
    items={[
      $tStore('accessibility.item1'),
      $tStore('accessibility.item2'),
      $tStore('accessibility.item3'),
      $tStore('accessibility.item4'),
    ]}
    keyboardTitle="Teclado"
    keyboardItems={[
      { key: 'Tab', description: $tStore('accessibility.keyboard.tab') },
      { key: '—',   description: $tStore('accessibility.keyboard.noKeyboard') },
    ]}
  />

  <!-- ── Relacionados ───────────────────────────────────────────── -->
  <DocsRelated
    title={$tStore('related.title')}
    componentSlug="label"
    items={[
      { name: 'Input',      description: $tStore('related.input'),      path: '?path=/docs/ui-input--docs'      },
      { name: 'FormLabel',  description: $tStore('related.formLabel'),  path: '?path=/docs/ui-formlabel--docs'  },
      { name: 'FormField',  description: $tStore('related.formField'),  path: '?path=/docs/ui-formfield--docs'  },
      { name: 'Checkbox',   description: $tStore('related.checkbox'),   path: '?path=/docs/ui-checkbox--docs'   },
    ]}
  />

  <!-- ── Notas ──────────────────────────────────────────────────── -->
  <DocsNotes
    title={$tStore('notes.title')}
    componentSlug="label"
    items={[
      { title: '', content: $tStore('notes.tip1') },
      { title: '', content: $tStore('notes.tip2') },
      { title: '', content: $tStore('notes.tip3') },
    ]}
  />

  <!-- ── Analytics ─────────────────────────────────────────────── -->
  <DocsAnalytics
    title={$tStore('analytics.title')}
    cols={{
      event: $tNavStore('analytics.table.event') ?? 'Evento',
      trigger: $tNavStore('analytics.table.trigger') ?? 'Gatilho',
      payload: $tNavStore('analytics.table.payload') ?? 'Payload',
    }}
    items={[
      {
        event: 'docs_page_view',
        trigger: 'Página carregada',
        payload: 'component_name: "label", locale, page_title',
      },
      {
        event: 'docs_section_viewed',
        trigger: 'Seção entra no viewport',
        payload: 'component_name: "label", section_id, locale',
      },
    ]}
  />

  <!-- ── Testes ─────────────────────────────────────────────────── -->
  <DocsTestes
    title={$tStore('testes.title')}
    functional={{
      title: $tStore('testes.functional.title'),
      cols: {
        action: $tNavStore('common.userAction'),
        result: $tNavStore('common.expectedResult'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { action: $tStore('testes.functional.item1.action'), result: $tStore('testes.functional.item1.result'), priority: localPriority($tStore('testes.functional.item1.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item2.action'), result: $tStore('testes.functional.item2.result'), priority: localPriority($tStore('testes.functional.item2.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item3.action'), result: $tStore('testes.functional.item3.result'), priority: localPriority($tStore('testes.functional.item3.priority'), $tNavStore) },
        { action: $tStore('testes.functional.item4.action'), result: $tStore('testes.functional.item4.result'), priority: localPriority($tStore('testes.functional.item4.priority'), $tNavStore) },
      ],
    }}
    accessibility={{
      title: $tStore('testes.accessibility.title'),
      cols: {
        criterion: $tNavStore('common.criterion'),
        level: 'WCAG',
        how: $tNavStore('common.howToVerify'),
      },
      items: [
        { criterion: $tStore('testes.accessibility.item1'), level: 'AA', how: 'axe-core'             },
        { criterion: $tStore('testes.accessibility.item2'), level: 'AA', how: 'getByLabelText()'     },
        { criterion: $tStore('testes.accessibility.item3'), level: 'AA', how: 'Inspecionar atributos DOM' },
        { criterion: $tStore('testes.accessibility.item4'), level: 'AA', how: 'Ferramenta de contraste' },
      ],
    }}
    visual={{
      title: $tStore('testes.visual.title'),
      cols: {
        story: $tNavStore('common.storyState'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { story: $tStore('testes.visual.item1.story'), priority: localPriority($tStore('testes.visual.item1.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item2.story'), priority: localPriority($tStore('testes.visual.item2.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item3.story'), priority: localPriority($tStore('testes.visual.item3.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item4.story'), priority: localPriority($tStore('testes.visual.item4.priority'), $tNavStore) },
      ],
    }}
  />
</DocsPageLayout>

// design-system-vue/src/components/docs/LabelDocs.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, watch, ref } from 'vue';
import { useTranslation } from '@/lib/i18n';
import { useSeoEffect } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { sanitizeHtml } from '@/lib/sanitize-html';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Badge } from '@/components/ui/badge';
import LanguageSwitcher from '@/components/product/LanguageSwitcher.vue';
import DocsPageLayout    from '@/components/docs/shared/sections/DocsPageLayout.vue';
import uiTranslations from '@/i18n/ui.json';
import labelTranslations from '@shared/content/label/translations.json';

import DocsHeader        from '@/components/docs/shared/sections/DocsHeader.vue';
import DocsDemonstration from '@/components/docs/shared/sections/DocsDemonstration.vue';
import DocsAnatomy       from '@/components/docs/shared/sections/DocsAnatomy.vue';
import DocsWhenToUse     from '@/components/docs/shared/sections/DocsWhenToUse.vue';
import DocsDoDont        from '@/components/docs/shared/sections/DocsDoDont.vue';
import DocsImport        from '@/components/docs/shared/sections/DocsImport.vue';
import DocsVariants      from '@/components/docs/shared/sections/DocsVariants.vue';
import DocsStates        from '@/components/docs/shared/sections/DocsStates.vue';
import DocsProps         from '@/components/docs/shared/sections/DocsProps.vue';
import DocsTokens        from '@/components/docs/shared/sections/DocsTokens.vue';
import DocsAccessibility from '@/components/docs/shared/sections/DocsAccessibility.vue';
import DocsRelated       from '@/components/docs/shared/sections/DocsRelated.vue';
import DocsNotes         from '@/components/docs/shared/sections/DocsNotes.vue';
import DocsAnalytics     from '@/components/docs/shared/sections/DocsAnalytics.vue';
import DocsTestes        from '@/components/docs/shared/sections/DocsTestes.vue';

// ─── i18n ─────────────────────────────────────────────────────────────────────

// locale vem de useTranslation, NUNCA de useLocaleStore ou Pinia
const { t: tNav } = useTranslation(uiTranslations);
const { t: tContent, locale } = useTranslation(labelTranslations);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '');
}

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function localPriority(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

// ─── SEO & GEO ────────────────────────────────────────────────────────────────

useSeoEffect(computed(() => ({
  title: tContent('seo.title'),
  description: tContent('seo.description'),
  locale: locale.value as 'pt-BR' | 'en' | 'es',
  componentSlug: 'label',
})));

// ─── Analytics — page view ────────────────────────────────────────────────────

watch(locale, (newLocale) => {
  track('docs_page_view', {
    component_name: 'label',
    locale: newLocale,
    page_title: `${tContent('title')} · Design System`,
  });
}, { immediate: true });

// ─── Analytics — section view ─────────────────────────────────────────────────

const activeSection = ref('demonstracao');

function handleSectionChange(id: string) {
  activeSection.value = id;
  track('docs_section_viewed', {
    section_id: id,
    component_name: 'label',
    locale: locale.value,
  });
}

// ─── Navigation groups ────────────────────────────────────────────────────────

const navGroups = computed(() => [
  {
    label: tNav('nav.overview'),
    sections: [
      { id: 'demonstracao', label: tNav('nav.demonstration') },
      { id: 'anatomia',     label: tNav('nav.anatomy')      },
      { id: 'quando-usar',  label: tNav('nav.usage')        },
      { id: 'do-dont',      label: tNav('nav.doDont')       },
    ],
  },
  {
    label: tNav('nav.techRef'),
    sections: [
      { id: 'importacao',   label: tNav('nav.import')   },
      { id: 'variantes',    label: tNav('nav.variants') },
      { id: 'estados',      label: tNav('nav.states')   },
      { id: 'propriedades', label: tNav('nav.props')    },
      { id: 'tokens',       label: tNav('nav.tokens')   },
    ],
  },
  {
    label: tNav('nav.context'),
    sections: [
      { id: 'acessibilidade', label: tNav('nav.accessibility') },
      { id: 'relacionados',   label: tNav('nav.related')       },
      { id: 'notas',          label: tNav('nav.notes')         },
    ],
  },
  {
    label: tNav('nav.quality'),
    sections: [
      { id: 'analytics', label: tNav('nav.analytics') },
      { id: 'testes',    label: tNav('nav.testes')    },
    ],
  },
]);

const allSectionIds = computed(() => navGroups.value.flatMap(g => g.sections.map(s => s.id)));

// ─── IntersectionObserver ─────────────────────────────────────────────────────

let observer: IntersectionObserver | null = null;

onMounted(() => {
  observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) { handleSectionChange(entry.target.id); break; }
      }
    },
    { rootMargin: '-20% 0px -70% 0px', threshold: 0 }
  );
  allSectionIds.value.forEach((id) => {
    const el = document.getElementById(id);
    if (el) observer!.observe(el);
  });
});

onUnmounted(() => {
  observer?.disconnect();
  observer = null;
});

// ─── Code strings ─────────────────────────────────────────────────────────────

const codeImportBasic = `import { Label } from "@/components/ui/label";`;

const codeDefault = `<Label for="nome">Nome completo</Label>
<input id="nome" type="text" />`;

const codeRequired = `<Label for="email">
  Email profissional
  <span class="text-destructive" aria-hidden="true">*</span>
</Label>
<input id="email" type="email" aria-required="true" />`;

const codeDisabled = `<!-- peer-disabled: Label e Input devem ser siblings no DOM -->
<Label for="cpf">CPF</Label>
<input id="cpf" type="text" class="peer" disabled />`;

const codeCustomization = `<!-- Personalização via class -->
<Label for="field" class="text-muted-foreground">
  Rótulo secundário
</Label>`;

const interfaceCode = `// Label (Vue)
interface LabelProps {
  for?: string;       // htmlFor no HTML nativo — associa ao campo pelo id
  class?: string;     // Classes Tailwind adicionais
  // Aceita todos os atributos HTML nativos do elemento <label>
}`;

// ─── Computed data ────────────────────────────────────────────────────────────

const anatomyItems = computed(() => [
  tContent('anatomy.item1'),
  tContent('anatomy.item2'),
  tContent('anatomy.item3'),
]);

const variantItems = computed(() => [
  {
    name: tContent('variants.default.label'),
    description: stripHtml(tContent('variants.default.description')),
    code: codeDefault,
  },
]);

const stateItems = computed(() => [
  {
    label: tContent('states.default.label'),
    trigger: tContent('states.default.trigger'),
    behavior: tContent('states.default.behavior'),
  },
  {
    label: tContent('states.disabled.label'),
    trigger: stripHtml(tContent('states.disabled.trigger')),
    behavior: stripHtml(tContent('states.disabled.behavior')),
  },
  {
    label: tContent('states.required.label'),
    trigger: tContent('states.required.trigger'),
    behavior: stripHtml(tContent('states.required.behavior')),
  },
]);

const propCols = computed(() => ({
  prop: tContent('props.table.prop'),
  type: tContent('props.table.type'),
  default: tContent('props.table.default'),
  required: tContent('props.table.required'),
  description: tContent('props.table.description'),
}));

const labelPropItems = computed(() => [
  { name: 'for', type: 'string', defaultValue: '—', required: 'Não', description: stripHtml(tContent('props.table.htmlFor')) },
  { name: 'class', type: 'string', defaultValue: '—', required: 'Não', description: tContent('props.table.className') },
  { name: 'default slot', type: 'VNode', defaultValue: '—', required: 'Sim', description: tContent('props.table.children') },
]);

const tokenRows = computed(() => [
  { token: '--foreground',  value: 'text-foreground',  description: tContent('tokens.table.foreground')      },
  { token: '--foreground',  value: 'opacity-50',        description: tContent('tokens.table.foregroundMuted') },
  { token: '—',             value: 'text-sm',           description: tContent('tokens.table.fontSize')        },
  { token: '—',             value: 'font-medium',       description: tContent('tokens.table.fontWeight')      },
  { token: '—',             value: 'leading-none',      description: tContent('tokens.table.lineHeight')      },
  { token: '--destructive', value: 'text-destructive',  description: tContent('tokens.table.destructive')     },
]);

const accessibilityItems = computed(() => [
  tContent('accessibility.item1'),
  tContent('accessibility.item2'),
  tContent('accessibility.item3'),
  tContent('accessibility.item4'),
]);

const keyboardItems = computed(() => [
  { key: 'Tab',  description: tContent('accessibility.keyboard.tab')        },
  { key: '—',    description: tContent('accessibility.keyboard.noKeyboard') },
]);

const relatedItems = computed(() => [
  { name: 'Input',      description: tContent('related.input'),      path: '?path=/docs/ui-input--docs'      },
  { name: 'FormLabel',  description: tContent('related.formLabel'),  path: '?path=/docs/ui-formlabel--docs'  },
  { name: 'FormField',  description: tContent('related.formField'),  path: '?path=/docs/ui-formfield--docs'  },
  { name: 'Checkbox',   description: tContent('related.checkbox'),   path: '?path=/docs/ui-checkbox--docs'   },
  { name: 'RadioGroup', description: tContent('related.radioGroup'), path: '?path=/docs/ui-radiogroup--docs' },
]);

const noteItems = computed(() => [
  { title: '', content: tContent('notes.tip1') },
  { title: '', content: tContent('notes.tip2') },
  { title: '', content: tContent('notes.tip3') },
]);

const analyticsItems = computed(() => [
  {
    event: 'docs_page_view',
    trigger: 'Carregamento da página / troca de locale',
    payload: 'component_name, locale, page_title',
  },
  {
    event: 'docs_section_viewed',
    trigger: 'Seção entra no viewport (IntersectionObserver)',
    payload: 'section_id, component_name, locale',
  },
]);

const functionalTestItems = computed(() => [
  { action: tContent('testes.functional.item1.action'), result: tContent('testes.functional.item1.result'), priority: localPriority(tContent('testes.functional.item1.priority')) },
  { action: tContent('testes.functional.item2.action'), result: tContent('testes.functional.item2.result'), priority: localPriority(tContent('testes.functional.item2.priority')) },
  { action: tContent('testes.functional.item3.action'), result: tContent('testes.functional.item3.result'), priority: localPriority(tContent('testes.functional.item3.priority')) },
  { action: tContent('testes.functional.item4.action'), result: tContent('testes.functional.item4.result'), priority: localPriority(tContent('testes.functional.item4.priority')) },
]);

const a11yTestItems = computed(() => [
  { criterion: tContent('testes.accessibility.item1'), level: 'WCAG 2.1 AA', how: 'axe-core' },
  { criterion: tContent('testes.accessibility.item2'), level: 'WCAG 2.1 AA', how: 'getByLabelText()' },
  { criterion: tContent('testes.accessibility.item3'), level: 'WCAG 2.1 AA', how: 'DOM inspection' },
  { criterion: tContent('testes.accessibility.item4'), level: 'WCAG 1.4.3',  how: 'Contrast analyser' },
]);

const a11yCritCols = computed(() => ({
  criterion: tNav('common.criterion'),
  level: 'WCAG',
  how: tNav('common.howToVerify'),
}));

const visualTestItems = computed(() => [
  { story: tContent('testes.visual.item1.story'), priority: localPriority(tContent('testes.visual.item1.priority')) },
  { story: tContent('testes.visual.item2.story'), priority: localPriority(tContent('testes.visual.item2.priority')) },
  { story: tContent('testes.visual.item3.story'), priority: localPriority(tContent('testes.visual.item3.priority')) },
  { story: tContent('testes.visual.item4.story'), priority: localPriority(tContent('testes.visual.item4.priority')) },
]);
</script>

<template>
  <DocsPageLayout :nav-groups="navGroups" :active-section="activeSection">
    <template #header>
      <DocsHeader
        :title="tContent('title')"
        :description="tContent('description')"
        :category="tContent('category')"
        :type="tContent('type')"
        install-note="npx shadcn-vue@latest add label"
      />
    </template>

    <!-- ── Demonstração ───────────────────────────────────────────── -->
    <DocsDemonstration :title="tContent('demonstration.title')">
      <div class="flex flex-col gap-6 w-full max-w-sm">
        <!-- Default -->
        <div class="flex flex-col gap-2">
          <Label for="demo-default">{{ tContent('demonstration.labels.default') }}</Label>
          <Input id="demo-default" type="text" :placeholder="tContent('demonstration.labels.default')" />
        </div>

        <!-- Required -->
        <div class="flex flex-col gap-2">
          <Label for="demo-required">
            {{ tContent('demonstration.labels.required') }}
            <span class="text-destructive" aria-hidden="true">{{ tContent('demonstration.labels.requiredMarker') }}</span>
          </Label>
          <Input id="demo-required" type="email" :placeholder="tContent('demonstration.labels.required')" aria-required="true" />
        </div>

        <!-- Disabled -->
        <div class="flex flex-col gap-2">
          <Label for="demo-disabled">{{ tContent('demonstration.labels.disabled') }}</Label>
          <Input id="demo-disabled" type="text" class="peer" :placeholder="tContent('demonstration.labels.disabled')" disabled />
        </div>
      </div>
    </DocsDemonstration>

    <!-- ── Anatomia ───────────────────────────────────────────────── -->
    <DocsAnatomy
      :title="tContent('anatomy.title')"
      :items="anatomyItems"
      :structure-label="tContent('anatomy.structureLabel')"
      :structure-code="tContent('anatomy.structureCode')"
    />

    <!-- ── Quando Usar ────────────────────────────────────────────── -->
    <DocsWhenToUse
      :title="tContent('usage.title')"
      :guidelines="{
        title: tContent('usage.guidelines.title'),
        items: [
          tContent('usage.guidelines.item1'),
          tContent('usage.guidelines.item2'),
          tContent('usage.guidelines.item3'),
          tContent('usage.guidelines.item4'),
        ],
      }"
      :scenarios="{
        title: tContent('usage.scenarios.title'),
        cols: {
          scenario: tContent('usage.scenarios.cols.scenario'),
          use: tContent('usage.scenarios.cols.use'),
          alternative: tContent('usage.scenarios.cols.alternative'),
        },
        items: [
          { s: tContent('usage.scenarios.item1.s'), u: tContent('usage.scenarios.item1.u'), a: tContent('usage.scenarios.item1.a') },
          { s: tContent('usage.scenarios.item2.s'), u: tContent('usage.scenarios.item2.u'), a: tContent('usage.scenarios.item2.a') },
          { s: tContent('usage.scenarios.item3.s'), u: tContent('usage.scenarios.item3.u'), a: tContent('usage.scenarios.item3.a') },
          { s: tContent('usage.scenarios.item4.s'), u: tContent('usage.scenarios.item4.u'), a: tContent('usage.scenarios.item4.a') },
        ],
      }"
      :do="{ title: tContent('usage.do.title'), items: [tContent('usage.do.item1'), tContent('usage.do.item2'), tContent('usage.do.item3')] }"
      :dont="{ title: tContent('usage.dont.title'), items: [tContent('usage.dont.item1'), tContent('usage.dont.item2'), tContent('usage.dont.item3')] }"
    />

    <!-- ── Do & Don't ─────────────────────────────────────────────── -->
    <DocsDoDont
      :title="tContent('doDont.title')"
      :pairs="[
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair1.do'), dontCaption: tContent('doDont.pair1.dont') },
        { doLabel: tNav('common.do'), dontLabel: tNav('common.dont'), doCaption: tContent('doDont.pair2.do'), dontCaption: tContent('doDont.pair2.dont') },
      ]"
    >
      <!-- Par 1 — com htmlFor vs. sem htmlFor -->
      <template #do-preview-0>
        <div class="flex flex-col gap-2 w-full max-w-xs">
          <Label for="do-input-1">Nome completo</Label>
          <Input id="do-input-1" type="text" placeholder="Digite seu nome" />
        </div>
      </template>
      <template #dont-preview-0>
        <div class="flex flex-col gap-2 w-full max-w-xs">
          <Label>Nome completo</Label>
          <Input type="text" placeholder="Digite seu nome" />
        </div>
      </template>

      <!-- Par 2 — texto nominal vs. instrução -->
      <template #do-preview-1>
        <div class="flex flex-col gap-2 w-full max-w-xs">
          <Label for="do-input-2">Email profissional</Label>
          <Input id="do-input-2" type="email" placeholder="voce@empresa.com" />
        </div>
      </template>
      <template #dont-preview-1>
        <div class="flex flex-col gap-2 w-full max-w-xs">
          <Label for="dont-input-2">Informe seu email profissional</Label>
          <Input id="dont-input-2" type="email" placeholder="voce@empresa.com" />
        </div>
      </template>
    </DocsDoDont>

    <!-- ── Importação ─────────────────────────────────────────────── -->
    <DocsImport
      :title="tContent('import.title')"
      :code="codeImportBasic"
    />

    <!-- ── Variantes ──────────────────────────────────────────────── -->
    <DocsVariants :title="tContent('variants.title')" :items="variantItems">
      <template #variant-preview-0>
        <div class="flex flex-col gap-2 w-full max-w-xs">
          <Label for="variant-default">Nome completo</Label>
          <Input id="variant-default" type="text" placeholder="Digite seu nome" />
        </div>
      </template>
    </DocsVariants>

    <!-- ── Estados ───────────────────────────────────────────────── -->
    <DocsStates
      :title="tContent('states.title')"
      :cols="{
        state: tContent('states.cols.state'),
        trigger: tContent('states.cols.trigger'),
        behavior: tContent('states.cols.behavior'),
      }"
      :items="stateItems"
    />

    <!-- ── Propriedades ───────────────────────────────────────────── -->
    <DocsProps
      :title="tContent('props.title')"
      :tables="[
        { title: 'Label', cols: propCols, items: labelPropItems },
      ]"
      :interface-code="interfaceCode"
      :extensibility-notes="tContent('props.note')"
    />

    <!-- ── Tokens ─────────────────────────────────────────────────── -->
    <DocsTokens
      :title="tContent('tokens.title')"
      :cols="{
        token: tContent('tokens.table.token'),
        value: tContent('tokens.table.class'),
        description: tContent('tokens.table.part'),
      }"
      :items="tokenRows"
      customization-title="Personalização"
      :customization-code="codeCustomization"
    />

    <!-- ── Acessibilidade ─────────────────────────────────────────── -->
    <DocsAccessibility
      :title="tContent('accessibility.title')"
      :summary="tContent('accessibility.summary')"
      :items="accessibilityItems"
      :keyboard-items="keyboardItems"
    />

    <!-- ── Relacionados ───────────────────────────────────────────── -->
    <DocsRelated :title="tContent('related.title')" :items="relatedItems" />

    <!-- ── Notas ──────────────────────────────────────────────────── -->
    <DocsNotes :title="tContent('notes.title')" :items="noteItems" />

    <!-- ── Analytics ─────────────────────────────────────────────── -->
    <DocsAnalytics
      :title="tContent('analytics.title')"
      :description="tContent('analytics.description')"
      :cols="{ event: 'Evento', trigger: 'Gatilho', payload: 'Payload' }"
      :items="analyticsItems"
    />

    <!-- ── Testes ─────────────────────────────────────────────────── -->
    <DocsTestes
      :title="tContent('testes.title')"
      :functional="{
        title: tContent('testes.functional.title'),
        cols: { action: tNav('common.userAction'), result: tNav('common.expectedResult'), priority: tNav('common.priority') },
        items: functionalTestItems,
      }"
      :accessibility="{
        title: tContent('testes.accessibility.title'),
        cols: a11yCritCols,
        items: a11yTestItems,
      }"
      :visual="{
        title: tContent('testes.visual.title'),
        cols: { story: tNav('common.storyState'), priority: tNav('common.priority') },
        items: visualTestItems,
      }"
    />
  </DocsPageLayout>
</template>
