// design-system-svelte/src/components/docs/ToggleDocs.svelte
<script lang="ts">
  import { Toggle } from '@/components/ui/toggle';
  import { Bold, Italic, Underline, List, Eye, LayoutGrid } from 'lucide-svelte';
  import { locale, useTranslation } from '@/lib/i18n';
  import { applySeo } from '@/lib/use-seo';
  import { track } from '@/lib/analytics';
  import DocsPageLayout from '@/components/docs/shared/sections/DocsPageLayout.svelte';
  import {
    DocsHeader, DocsDemonstration, DocsAnatomy, DocsWhenToUse, DocsDoDont,
    DocsImport, DocsVariants, DocsStates, DocsProps, DocsTokens,
    DocsAccessibility, DocsRelated, DocsNotes, DocsAnalytics, DocsTestes,
  } from '@/components/docs/shared/sections';
  import uiTranslations from '@/i18n/ui.json';
  import toggleTranslations from '@shared/content/toggle/translations.json';

  const { tStore: tNavStore } = useTranslation(uiTranslations);
  const { tStore } = useTranslation(toggleTranslations);

  // ─── SEO + Analytics ─────────────────────────────────────────────────────────

  $effect(() => {
    const t = $tStore;
    const l = $locale;
    const cleanup = applySeo({
      title: t('seo.title'),
      description: t('seo.description'),
      locale: l,
      componentSlug: 'toggle',
      aiSummary: t('seo.aiSummary'),
      aiEntities: t('seo.aiEntities'),
      aiIntent: t('seo.aiIntent') as 'informational' | 'navigational',
      breadcrumb: [
        { name: 'Components', item: '/components' },
        { name: t('category'), item: '/components/form' },
        { name: t('title') },
      ],
    });
    track('docs_page_view', {
      component_name: 'toggle',
      locale: l,
      page_title: `${t('title')} · Design System`,
    });
    return cleanup;
  });

  // ─── Active section ──────────────────────────────────────────────────────────

  let activeSection = $state('demonstracao');

  const NAV_GROUPS = $derived.by(() => {
    const tNav = $tNavStore;
    return [
      { label: tNav('nav.overview'), sections: [
        { id: 'demonstracao', label: tNav('nav.demonstration') },
        { id: 'anatomia',     label: tNav('nav.anatomy')       },
        { id: 'quando-usar',  label: tNav('nav.usage')         },
        { id: 'do-dont',      label: tNav('nav.doDont')        },
      ]},
      { label: tNav('nav.techRef'), sections: [
        { id: 'importacao',   label: tNav('nav.import')    },
        { id: 'variantes',    label: tNav('nav.variants')  },
        { id: 'estados',      label: tNav('nav.states')    },
        { id: 'propriedades', label: tNav('nav.props')     },
        { id: 'tokens',       label: tNav('nav.tokens')    },
      ]},
      { label: tNav('nav.context'), sections: [
        { id: 'acessibilidade', label: tNav('nav.accessibility') },
        { id: 'relacionados',   label: tNav('nav.related')       },
        { id: 'notas',          label: tNav('nav.notes')         },
      ]},
      { label: tNav('nav.quality'), sections: [
        { id: 'analytics', label: tNav('nav.analytics') },
        { id: 'testes',    label: tNav('nav.testes')    },
      ]},
    ];
  });

  $effect(() => {
    const ids = NAV_GROUPS.flatMap(g => g.sections.map(s => s.id));
    const observer = new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          activeSection = entry.target.id;
          track('docs_section_viewed', { section_id: entry.target.id, component_name: 'toggle', locale: $locale });
          break;
        }
      }
    }, { rootMargin: '-20% 0px -70% 0px', threshold: 0 });
    for (const id of ids) {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    }
    return () => observer.disconnect();
  });

  // ─── Helpers ─────────────────────────────────────────────────────────────────

  function stripHtml(s: string) {
    return s.replace(/<[^>]*>/g, '');
  }

  const priorityKeyMap: Record<string, string> = { high: 'common.high', medium: 'common.medium', low: 'common.low' };

  function localPriority(raw: string, tNav: (k: string) => string): string {
    return tNav(priorityKeyMap[raw] ?? 'common.high');
  }

  // ─── Reactive demo states ────────────────────────────────────────────────────

  let demoBold = $state(true);
  let demoItalic = $state(false);
  let demoUnderline = $state(false);
  let demoShowHidden = $state(false);
  let demoCompact = $state(false);

  // Variants
  let varDefault = $state(false);
  let varOutline = $state(false);
  let varWithLabel = $state(false);

  // Do/Don't
  let dd1DoPressed = $state(false);
  let dd1DontPressed = $state(false);
  let dd2DoPressed = $state(false);
  let dd2DontPressed = $state(false);

  // ─── Code strings ────────────────────────────────────────────────────────────

  const codeImport = `import { Toggle } from "@/components/ui/toggle";`;

  const codeDefault = `<script lang="ts">
  import { Toggle } from "@/components/ui/toggle";
  import { Bold } from "lucide-svelte";
  let pressed = $state(false);
<\/script>

<Toggle bind:pressed aria-label="Negrito">
  <Bold aria-hidden="true" />
</Toggle>`;

  const codeOutline = `<script lang="ts">
  import { Toggle } from "@/components/ui/toggle";
  import { Italic } from "lucide-svelte";
  let pressed = $state(false);
<\/script>

<Toggle bind:pressed variant="outline" aria-label="Itálico">
  <Italic aria-hidden="true" />
</Toggle>`;

  const codeWithLabel = `<script lang="ts">
  import { Toggle } from "@/components/ui/toggle";
  import { Eye } from "lucide-svelte";
  let showHidden = $state(false);
<\/script>

<Toggle bind:pressed={showHidden} variant="outline">
  <Eye aria-hidden="true" />
  Mostrar ocultos
</Toggle>`;

  const interfaceCode = `// Toggle (Svelte 5 — bits-ui)
interface ToggleProps {
  pressed?: boolean;                   // $bindable — estado controlado
  ref?: HTMLElement;                   // $bindable
  disabled?: boolean;
  variant?: "default" | "outline";     // estilo visual
  size?: "default" | "sm" | "lg";      // altura via tokens --height-*
  'aria-label'?: string;               // OBRIGATÓRIO em icon-only
  class?: string;
}`;

  const customizationCode = `/* Cor customizada do estado ativo */
.toggle-brand[data-state="on"] {
  @apply bg-blue-500 text-white;
}

/* Override do tamanho via tokens */
[data-slot="toggle"][data-size="default"] {
  --height-default: 2.5rem;
}`;
</script>

<DocsPageLayout navGroups={NAV_GROUPS} {activeSection} componentSlug="toggle">
  {#snippet header()}
    <DocsHeader
      title={$tStore('title')}
      description={$tStore('description')}
      category={$tStore('category')}
      type={$tStore('type')}
      installNote="npx shadcn-svelte@latest add toggle"
    />
  {/snippet}

  <!-- ── Demonstração ─────────────────────────────────────────────────── -->
  <DocsDemonstration title={$tStore('demonstration.title')} componentSlug="toggle">
    {#snippet children()}
      <div class="flex flex-col gap-6 items-start">
        <!-- Formatting toolbar (icon-only) -->
        <div class="flex items-center gap-1">
          <Toggle
            bind:pressed={demoBold}
            aria-label={$tStore('demonstration.labels.bold')}
            data-track="demo"
            data-track-id="toggle:demo:bold"
            data-track-label={$tStore('demonstration.labels.bold')}
          >
            <Bold aria-hidden="true" />
          </Toggle>
          <Toggle
            bind:pressed={demoItalic}
            aria-label={$tStore('demonstration.labels.italic')}
            data-track="demo"
            data-track-id="toggle:demo:italic"
            data-track-label={$tStore('demonstration.labels.italic')}
          >
            <Italic aria-hidden="true" />
          </Toggle>
          <Toggle
            bind:pressed={demoUnderline}
            aria-label={$tStore('demonstration.labels.underline')}
            data-track="demo"
            data-track-id="toggle:demo:underline"
            data-track-label={$tStore('demonstration.labels.underline')}
          >
            <Underline aria-hidden="true" />
          </Toggle>
        </div>

        <!-- Outline com label visível -->
        <Toggle
          bind:pressed={demoShowHidden}
          variant="outline"
          data-track="demo"
          data-track-id="toggle:demo:showHidden"
          data-track-label={$tStore('demonstration.labels.showHidden')}
        >
          <Eye aria-hidden="true" />
          <span>{$tStore('demonstration.labels.showHidden')}</span>
        </Toggle>

        <!-- Tamanho lg com label visível -->
        <Toggle
          bind:pressed={demoCompact}
          variant="outline"
          size="lg"
          data-track="demo"
          data-track-id="toggle:demo:compactView"
          data-track-label={$tStore('demonstration.labels.compactView')}
        >
          <LayoutGrid aria-hidden="true" />
          <span>{$tStore('demonstration.labels.compactView')}</span>
        </Toggle>
      </div>
    {/snippet}
  </DocsDemonstration>

  <!-- ── Anatomia ──────────────────────────────────────────────────────── -->
  <DocsAnatomy
    title={$tStore('anatomy.title')}
    items={[
      $tStore('anatomy.item1'),
      $tStore('anatomy.item2'),
      $tStore('anatomy.item3'),
    ]}
    structureLabel={$tStore('anatomy.structureLabel')}
    structureCode={$tStore('anatomy.structureCode')}
  />

  <!-- ── Quando Usar ───────────────────────────────────────────────────── -->
  <DocsWhenToUse
    title={$tStore('usage.title')}
    guidelines={{
      title: $tStore('usage.guidelines.title'),
      items: [
        $tStore('usage.guidelines.item1'),
        $tStore('usage.guidelines.item2'),
        $tStore('usage.guidelines.item3'),
        $tStore('usage.guidelines.item4'),
      ],
    }}
    scenarios={{
      title: $tStore('usage.scenarios.title'),
      cols: {
        scenario: $tStore('usage.scenarios.cols.scenario'),
        use: $tStore('usage.scenarios.cols.use'),
        alternative: $tStore('usage.scenarios.cols.alternative'),
      },
      items: [
        { s: $tStore('usage.scenarios.item1.s'), u: $tStore('usage.scenarios.item1.u'), a: $tStore('usage.scenarios.item1.a') },
        { s: $tStore('usage.scenarios.item2.s'), u: $tStore('usage.scenarios.item2.u'), a: $tStore('usage.scenarios.item2.a') },
        { s: $tStore('usage.scenarios.item3.s'), u: $tStore('usage.scenarios.item3.u'), a: $tStore('usage.scenarios.item3.a') },
        { s: $tStore('usage.scenarios.item4.s'), u: $tStore('usage.scenarios.item4.u'), a: $tStore('usage.scenarios.item4.a') },
        { s: $tStore('usage.scenarios.item5.s'), u: $tStore('usage.scenarios.item5.u'), a: $tStore('usage.scenarios.item5.a') },
      ],
    }}
    uxWriting={{
      title: $tStore('usage.uxWriting.title'),
      cols: {
        element: $tStore('usage.uxWriting.table.element'),
        rules: $tStore('usage.uxWriting.table.rules'),
        do: $tStore('usage.uxWriting.table.correct'),
        dont: $tStore('usage.uxWriting.table.avoid'),
      },
      items: [
        {
          element: $tStore('usage.uxWriting.table.ariaLabel.name'),
          rules: $tStore('usage.uxWriting.table.ariaLabel.format'),
          do: $tStore('usage.uxWriting.table.ariaLabel.good'),
          dont: $tStore('usage.uxWriting.table.ariaLabel.bad'),
        },
        {
          element: $tStore('usage.uxWriting.table.label.name'),
          rules: $tStore('usage.uxWriting.table.label.format'),
          do: $tStore('usage.uxWriting.table.label.good'),
          dont: $tStore('usage.uxWriting.table.label.bad'),
        },
        {
          element: $tStore('usage.uxWriting.table.icon.name'),
          rules: $tStore('usage.uxWriting.table.icon.format'),
          do: $tStore('usage.uxWriting.table.icon.good'),
          dont: $tStore('usage.uxWriting.table.icon.bad'),
        },
      ],
    }}
    do={{
      title: $tStore('usage.do.title'),
      items: [
        $tStore('usage.do.item1'),
        $tStore('usage.do.item2'),
        $tStore('usage.do.item3'),
        $tStore('usage.do.item4'),
      ],
    }}
    dont={{
      title: $tStore('usage.dont.title'),
      items: [
        $tStore('usage.dont.item1'),
        $tStore('usage.dont.item2'),
        $tStore('usage.dont.item3'),
        $tStore('usage.dont.item4'),
      ],
    }}
  />

  <!-- ── Do & Don't ───────────────────────────────────────────────────── -->
  <DocsDoDont
    title={$tStore('doDont.title')}
    pairs={[
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair1.do'),
        dontCaption: $tStore('doDont.pair1.dont'),
        doPreview: dd1Do,
        dontPreview: dd1Dont,
      },
      {
        doLabel: $tNavStore('common.do'),
        dontLabel: $tNavStore('common.dont'),
        doCaption: $tStore('doDont.pair2.do'),
        dontCaption: $tStore('doDont.pair2.dont'),
        doPreview: dd2Do,
        dontPreview: dd2Dont,
      },
    ]}
  />

  {#snippet dd1Do()}
    <Toggle bind:pressed={dd1DoPressed} aria-label="Negrito">
      <Bold aria-hidden="true" />
    </Toggle>
  {/snippet}

  {#snippet dd1Dont()}
    <Toggle bind:pressed={dd1DontPressed} aria-label="Botão B">
      <Bold aria-hidden="true" />
    </Toggle>
  {/snippet}

  {#snippet dd2Do()}
    <div class="flex items-center gap-1">
      <Toggle bind:pressed={dd2DoPressed} aria-label="Negrito">
        <Bold aria-hidden="true" />
      </Toggle>
      <Toggle aria-label="Itálico">
        <Italic aria-hidden="true" />
      </Toggle>
      <Toggle aria-label="Sublinhado">
        <Underline aria-hidden="true" />
      </Toggle>
    </div>
  {/snippet}

  {#snippet dd2Dont()}
    <div class="flex items-center gap-3">
      <Toggle bind:pressed={dd2DontPressed} aria-label="Negrito">
        <Bold aria-hidden="true" />
      </Toggle>
      <Toggle aria-label="Itálico">
        <Italic aria-hidden="true" />
      </Toggle>
    </div>
  {/snippet}

  <!-- ── Importação ────────────────────────────────────────────────────── -->
  <DocsImport
    title={$tStore('import.title')}
    code={codeImport}
    componentSlug="toggle"
  />

  <!-- ── Variantes ─────────────────────────────────────────────────────── -->
  <DocsVariants
    title={$tStore('variants.title')}
    componentSlug="toggle"
    items={[
      {
        name: $tStore('variants.items.default'),
        description: stripHtml($tStore('variants.styles.default')),
        code: codeDefault,
        preview: variantDefault,
      },
      {
        name: $tStore('variants.items.outline'),
        description: stripHtml($tStore('variants.styles.outline')),
        code: codeOutline,
        preview: variantOutline,
      },
      {
        name: $tStore('variants.items.withLabel'),
        description: stripHtml($tStore('variants.styles.withLabel')),
        code: codeWithLabel,
        preview: variantWithLabel,
      },
    ]}
  />

  {#snippet variantDefault()}
    <Toggle bind:pressed={varDefault} aria-label="Negrito">
      <Bold aria-hidden="true" />
    </Toggle>
  {/snippet}

  {#snippet variantOutline()}
    <Toggle bind:pressed={varOutline} variant="outline" aria-label="Itálico">
      <Italic aria-hidden="true" />
    </Toggle>
  {/snippet}

  {#snippet variantWithLabel()}
    <Toggle bind:pressed={varWithLabel} variant="outline">
      <Eye aria-hidden="true" />
      <span>Mostrar ocultos</span>
    </Toggle>
  {/snippet}

  <!-- ── Estados ──────────────────────────────────────────────────────── -->
  <DocsStates
    title={$tStore('states.title')}
    cols={{
      state: 'Estado',
      trigger: 'Disparo',
      behavior: 'Comportamento',
    }}
    items={[
      { label: $tStore('states.items.off'),      trigger: 'aria-pressed="false"',  behavior: stripHtml($tStore('states.descriptions.off')) },
      { label: $tStore('states.items.on'),       trigger: 'aria-pressed="true"',   behavior: stripHtml($tStore('states.descriptions.on')) },
      { label: $tStore('states.items.hover'),    trigger: ':hover',                behavior: stripHtml($tStore('states.descriptions.hover')) },
      { label: $tStore('states.items.focus'),    trigger: ':focus-visible',        behavior: stripHtml($tStore('states.descriptions.focus')) },
      { label: $tStore('states.items.disabled'), trigger: 'disabled',              behavior: stripHtml($tStore('states.descriptions.disabled')) },
      { label: $tStore('states.items.invalid'),  trigger: 'aria-invalid="true"',   behavior: stripHtml($tStore('states.descriptions.invalid')) },
    ]}
  />

  <!-- ── Propriedades ─────────────────────────────────────────────────── -->
  <DocsProps
    title={$tStore('props.title')}
    tables={[
      {
        cols: {
          prop: $tStore('props.table.prop'),
          type: $tStore('props.table.type'),
          default: $tStore('props.table.default'),
          required: $tStore('props.table.required'),
          description: $tStore('props.table.description'),
        },
        items: [
          { name: 'pressed',          type: $tStore('props.table.pressed.type'),          defaultValue: $tStore('props.table.pressed.default'),          required: $tStore('props.table.pressed.required'),          description: stripHtml($tStore('props.table.pressed.description')) },
          { name: 'defaultPressed',   type: $tStore('props.table.defaultPressed.type'),   defaultValue: $tStore('props.table.defaultPressed.default'),   required: $tStore('props.table.defaultPressed.required'),   description: stripHtml($tStore('props.table.defaultPressed.description')) },
          { name: 'onPressedChange',  type: $tStore('props.table.onPressedChange.type'),  defaultValue: $tStore('props.table.onPressedChange.default'),  required: $tStore('props.table.onPressedChange.required'),  description: stripHtml($tStore('props.table.onPressedChange.description')) },
          { name: 'disabled',         type: $tStore('props.table.disabled.type'),         defaultValue: $tStore('props.table.disabled.default'),         required: $tStore('props.table.disabled.required'),         description: stripHtml($tStore('props.table.disabled.description')) },
          { name: 'variant',          type: $tStore('props.table.variant.type'),          defaultValue: $tStore('props.table.variant.default'),          required: $tStore('props.table.variant.required'),          description: stripHtml($tStore('props.table.variant.description')) },
          { name: 'size',             type: $tStore('props.table.size.type'),             defaultValue: $tStore('props.table.size.default'),             required: $tStore('props.table.size.required'),             description: stripHtml($tStore('props.table.size.description')) },
          { name: 'class',            type: $tStore('props.table.className.type'),        defaultValue: $tStore('props.table.className.default'),        required: $tStore('props.table.className.required'),        description: stripHtml($tStore('props.table.className.description')) },
        ],
      },
    ]}
    interfaceCode={interfaceCode}
  />

  <!-- ── Tokens ────────────────────────────────────────────────────────── -->
  <DocsTokens
    title={$tStore('tokens.title')}
    cols={{
      token: $tStore('tokens.table.token'),
      value: $tStore('tokens.table.class'),
      description: $tStore('tokens.table.part'),
    }}
    items={[
      { token: '--muted',       value: $tStore('tokens.table.muted.class'),       description: $tStore('tokens.table.muted.part') },
      { token: '--foreground',  value: $tStore('tokens.table.foreground.class'),  description: $tStore('tokens.table.foreground.part') },
      { token: '--input',       value: $tStore('tokens.table.input.class'),       description: $tStore('tokens.table.input.part') },
      { token: '--ring',        value: $tStore('tokens.table.ring.class'),        description: $tStore('tokens.table.ring.part') },
      { token: '--destructive', value: $tStore('tokens.table.destructive.class'), description: $tStore('tokens.table.destructive.part') },
      { token: '--radius-button', value: $tStore('tokens.table.radius.class'),      description: $tStore('tokens.table.radius.part') },
    ]}
    customizationTitle={$tStore('tokens.customizationTitle')}
    customizationCode={customizationCode}
  />

  <!-- ── Acessibilidade ───────────────────────────────────────────────── -->
  <DocsAccessibility
    title={$tStore('accessibility.title')}
    summary={$tStore('accessibility.summary')}
    items={[
      $tStore('accessibility.items.item1'),
      $tStore('accessibility.items.item2'),
      $tStore('accessibility.items.item3'),
      $tStore('accessibility.items.item4'),
      $tStore('accessibility.items.item5'),
      $tStore('accessibility.items.item6'),
    ]}
    keyboardTitle={$tStore('accessibility.keyboard.title')}
    keyboardItems={[
      { key: 'Tab',   description: $tStore('accessibility.keyboard.tab') },
      { key: 'Space', description: $tStore('accessibility.keyboard.space') },
      { key: 'Enter', description: $tStore('accessibility.keyboard.enter') },
    ]}
  />

  <!-- ── Relacionados ──────────────────────────────────────────────────── -->
  <DocsRelated
    title={$tStore('related.title')}
    items={[
      { name: $tStore('related.items.toggleGroup.name'), description: $tStore('related.items.toggleGroup.description'), path: '?path=/docs/ui-togglegroup--docs' },
      { name: $tStore('related.items.switch.name'),      description: $tStore('related.items.switch.description'),      path: '?path=/docs/ui-switch--docs' },
      { name: $tStore('related.items.checkbox.name'),    description: $tStore('related.items.checkbox.description'),    path: '?path=/docs/ui-checkbox--docs' },
      { name: $tStore('related.items.button.name'),      description: $tStore('related.items.button.description'),      path: '?path=/docs/ui-button--docs' },
    ]}
  />

  <!-- ── Notas ─────────────────────────────────────────────────────────── -->
  <DocsNotes
    title={$tStore('notes.title')}
    items={[
      { title: '', content: $tStore('notes.item1') },
      { title: '', content: $tStore('notes.item2') },
      { title: '', content: $tStore('notes.item3') },
      { title: '', content: $tStore('notes.item4') },
    ]}
  />

  <!-- ── Analytics ────────────────────────────────────────────────────── -->
  <DocsAnalytics
    title={$tStore('analytics.title')}
    cols={{
      event: $tStore('analytics.table.event'),
      trigger: $tStore('analytics.table.trigger'),
      payload: $tStore('analytics.table.payload'),
    }}
    items={[
      {
        event: 'field_change',
        trigger: $tStore('analytics.table.field_change.trigger'),
        payload: $tStore('analytics.table.field_change.payload'),
      },
    ]}
  />

  <!-- ── Testes ────────────────────────────────────────────────────────── -->
  <DocsTestes
    title={$tStore('testes.title')}
    functional={{
      title: $tStore('testes.functional.title'),
      cols: {
        action: $tNavStore('common.userAction'),
        result: $tNavStore('common.expectedResult'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { action: stripHtml($tStore('testes.functional.item1.action')), result: stripHtml($tStore('testes.functional.item1.result')), priority: localPriority($tStore('testes.functional.item1.priority'), $tNavStore) },
        { action: stripHtml($tStore('testes.functional.item2.action')), result: stripHtml($tStore('testes.functional.item2.result')), priority: localPriority($tStore('testes.functional.item2.priority'), $tNavStore) },
        { action: stripHtml($tStore('testes.functional.item3.action')), result: stripHtml($tStore('testes.functional.item3.result')), priority: localPriority($tStore('testes.functional.item3.priority'), $tNavStore) },
        { action: stripHtml($tStore('testes.functional.item4.action')), result: stripHtml($tStore('testes.functional.item4.result')), priority: localPriority($tStore('testes.functional.item4.priority'), $tNavStore) },
      ],
    }}
    accessibility={{
      title: $tStore('testes.accessibility.title'),
      cols: {
        criterion: $tNavStore('common.criterion'),
        level: 'WCAG',
        how: $tNavStore('common.howToVerify'),
      },
      items: [
        { criterion: $tStore('testes.accessibility.item1'), level: 'AA',    how: 'axe-core' },
        { criterion: $tStore('testes.accessibility.item2'), level: '1.4.3', how: 'Contrast checker' },
        { criterion: $tStore('testes.accessibility.item3'), level: '2.4.7', how: 'Keyboard test' },
        { criterion: $tStore('testes.accessibility.item4'), level: '4.1.2', how: 'DevTools a11y tree' },
        { criterion: $tStore('testes.accessibility.item5'), level: '4.1.2', how: 'DevTools attribute' },
      ],
    }}
    visual={{
      title: $tStore('testes.visual.title'),
      cols: {
        story: $tNavStore('common.storyState'),
        priority: $tNavStore('common.priority'),
      },
      items: [
        { story: $tStore('testes.visual.item1.story'), priority: localPriority($tStore('testes.visual.item1.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item2.story'), priority: localPriority($tStore('testes.visual.item2.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item3.story'), priority: localPriority($tStore('testes.visual.item3.priority'), $tNavStore) },
        { story: $tStore('testes.visual.item4.story'), priority: localPriority($tStore('testes.visual.item4.priority'), $tNavStore) },
      ],
    }}
  />
</DocsPageLayout>

// design-system-vue/src/components/docs/ToggleDocs.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, watch, ref } from 'vue';
import { useTranslation } from '@/lib/i18n';
import { useSeoEffect } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { Toggle } from '@/components/ui/toggle';
import { Bold, Italic, Underline, List, Eye, LayoutGrid } from 'lucide-vue-next';

import DocsPageLayout    from '@/components/docs/shared/sections/DocsPageLayout.vue';
import DocsHeader        from '@/components/docs/shared/sections/DocsHeader.vue';
import DocsDemonstration from '@/components/docs/shared/sections/DocsDemonstration.vue';
import DocsAnatomy       from '@/components/docs/shared/sections/DocsAnatomy.vue';
import DocsWhenToUse     from '@/components/docs/shared/sections/DocsWhenToUse.vue';
import DocsDoDont        from '@/components/docs/shared/sections/DocsDoDont.vue';
import DocsImport        from '@/components/docs/shared/sections/DocsImport.vue';
import DocsVariants      from '@/components/docs/shared/sections/DocsVariants.vue';
import DocsStates        from '@/components/docs/shared/sections/DocsStates.vue';
import DocsProps         from '@/components/docs/shared/sections/DocsProps.vue';
import DocsTokens        from '@/components/docs/shared/sections/DocsTokens.vue';
import DocsAccessibility from '@/components/docs/shared/sections/DocsAccessibility.vue';
import DocsRelated       from '@/components/docs/shared/sections/DocsRelated.vue';
import DocsNotes         from '@/components/docs/shared/sections/DocsNotes.vue';
import DocsAnalytics     from '@/components/docs/shared/sections/DocsAnalytics.vue';
import DocsTestes        from '@/components/docs/shared/sections/DocsTestes.vue';

import uiTranslations        from '@/i18n/ui.json';
import componentTranslations from '@shared/content/toggle/translations.json';

// ─── i18n ─────────────────────────────────────────────────────────────────────
// IMPORTANT: locale comes from useTranslation — NEVER from useLocaleStore/Pinia
const { t: tNav } = useTranslation(uiTranslations);
const { t: tContent, locale } = useTranslation(componentTranslations);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '');
}

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function localPriority(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

// ─── SEO & GEO ────────────────────────────────────────────────────────────────

useSeoEffect(computed(() => ({
  title: tContent('seo.title'),
  description: tContent('seo.description'),
  locale: locale.value as 'pt-BR' | 'en' | 'es',
  componentSlug: 'toggle',
  aiSummary: tContent('seo.aiSummary'),
  aiEntities: tContent('seo.aiEntities'),
  aiIntent: tContent('seo.aiIntent') as 'informational' | 'navigational',
  breadcrumb: [
    { name: 'Components', item: '/components' },
    { name: tContent('category'), item: '/components/form' },
    { name: tContent('title') },
  ],
})));

// ─── Analytics — page view (reactive to locale) ───────────────────────────────

watch(locale, (newLocale) => {
  track('docs_page_view', {
    component_name: 'toggle',
    locale: newLocale as 'pt-BR' | 'en' | 'es',
    page_title: tContent('seo.title'),
  });
}, { immediate: true });

// ─── Analytics — section view ─────────────────────────────────────────────────

const activeSection = ref('demonstracao');

function handleSectionChange(id: string) {
  activeSection.value = id;
  track('docs_section_viewed', {
    section_id: id,
    component_name: 'toggle',
    locale: locale.value,
  });
}

// ─── Demo state ───────────────────────────────────────────────────────────────

const demoBold = ref(false);
const demoItalic = ref(true);
const demoUnderline = ref(false);
const demoShowHidden = ref(false);
const demoCompact = ref(true);

// ─── Navigation groups ────────────────────────────────────────────────────────

const navGroups = computed(() => [
  {
    label: tNav('nav.overview'),
    sections: [
      { id: 'demonstracao', label: tNav('nav.demonstration') },
      { id: 'anatomia',     label: tNav('nav.anatomy')      },
      { id: 'quando-usar',  label: tNav('nav.usage')        },
      { id: 'do-dont',      label: tNav('nav.doDont')       },
    ],
  },
  {
    label: tNav('nav.techRef'),
    sections: [
      { id: 'importacao',   label: tNav('nav.import')    },
      { id: 'variantes',    label: tNav('nav.variants')  },
      { id: 'estados',      label: tNav('nav.states')    },
      { id: 'propriedades', label: tNav('nav.props')     },
      { id: 'tokens',       label: tNav('nav.tokens')    },
    ],
  },
  {
    label: tNav('nav.context'),
    sections: [
      { id: 'acessibilidade', label: tNav('nav.accessibility') },
      { id: 'relacionados',   label: tNav('nav.related')       },
      { id: 'notas',          label: tNav('nav.notes')         },
    ],
  },
  {
    label: tNav('nav.quality'),
    sections: [
      { id: 'analytics', label: tNav('nav.analytics') },
      { id: 'testes',    label: tNav('nav.testes')    },
    ],
  },
]);

const allSectionIds = computed(() => navGroups.value.flatMap(g => g.sections.map(s => s.id)));

// ─── IntersectionObserver ─────────────────────────────────────────────────────

let observer: IntersectionObserver | null = null;

onMounted(() => {
  observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) { handleSectionChange(entry.target.id); break; }
      }
    },
    { rootMargin: '-20% 0px -70% 0px', threshold: 0 }
  );
  allSectionIds.value.forEach((id) => {
    const el = document.getElementById(id);
    if (el && observer) observer.observe(el);
  });
});

onUnmounted(() => {
  observer?.disconnect();
  observer = null;
});

// ─── Code strings ─────────────────────────────────────────────────────────────

const codeImportBasic = `import { Toggle } from "@/components/ui/toggle";
import { Bold } from "lucide-vue-next";`;

const codeDefault = `<Toggle
  :model-value="isBold"
  @update:model-value="(v) => isBold = v"
  aria-label="Negrito"
>
  <Bold aria-hidden="true" />
</Toggle>`;

const codeOutline = `<Toggle variant="outline" aria-label="Itálico">
  <Italic aria-hidden="true" />
</Toggle>`;

const codeWithLabel = `<Toggle variant="outline">
  <Eye aria-hidden="true" />
  Mostrar ocultos
</Toggle>`;

const codeCustomizationTokens = `/* Override de cor do estado ativo */
.toggle-brand[data-state="on"] {
  @apply bg-blue-500 text-white;
}

/* Override de tamanho via tokens */
[data-slot="toggle"][data-size="default"] {
  --height-default: 2.5rem;
}`;

const interfaceCode = `interface ToggleProps {
  modelValue?: boolean;        // estado controlado (v-model)
  defaultValue?: boolean;      // estado inicial não-controlado
  disabled?: boolean;
  name?: string;
  required?: boolean;
  variant?: 'default' | 'outline';
  size?: 'default' | 'sm' | 'lg';
  class?: string;
  // Emits
  'onUpdate:modelValue'?: (value: boolean) => void;
}`;

// ─── Computed data ────────────────────────────────────────────────────────────

const anatomyItems = computed(() => [
  tContent('anatomy.item1'),
  tContent('anatomy.item2'),
  tContent('anatomy.item3'),
]);

const variantItems = computed(() => [
  { name: stripHtml(tContent('variants.items.default')),   description: stripHtml(tContent('variants.styles.default')),   code: codeDefault   },
  { name: stripHtml(tContent('variants.items.outline')),   description: stripHtml(tContent('variants.styles.outline')),   code: codeOutline   },
  { name: stripHtml(tContent('variants.items.withLabel')), description: stripHtml(tContent('variants.styles.withLabel')), code: codeWithLabel },
]);

const stateItems = computed(() => [
  { label: tContent('states.items.off'),      trigger: '—', behavior: tContent('states.descriptions.off')      },
  { label: tContent('states.items.on'),       trigger: '—', behavior: tContent('states.descriptions.on')       },
  { label: tContent('states.items.hover'),    trigger: '—', behavior: tContent('states.descriptions.hover')    },
  { label: tContent('states.items.focus'),    trigger: '—', behavior: tContent('states.descriptions.focus')    },
  { label: tContent('states.items.disabled'), trigger: '—', behavior: tContent('states.descriptions.disabled') },
  { label: tContent('states.items.invalid'),  trigger: '—', behavior: tContent('states.descriptions.invalid')  },
]);

const propCols = computed(() => ({
  prop: tContent('props.table.prop'),
  type: tContent('props.table.type'),
  default: tContent('props.table.default'),
  required: tContent('props.table.required'),
  description: tContent('props.table.description'),
}));

const togglePropItems = computed(() => [
  { name: 'modelValue',         type: 'boolean',                       defaultValue: '—',         required: tContent('props.table.pressed.required'),        description: stripHtml(tContent('props.table.pressed.description'))        },
  { name: 'defaultValue',       type: 'boolean',                       defaultValue: 'false',     required: tContent('props.table.defaultPressed.required'), description: stripHtml(tContent('props.table.defaultPressed.description')) },
  { name: '@update:modelValue', type: '(value: boolean) => void',      defaultValue: '—',         required: tContent('props.table.onPressedChange.required'), description: stripHtml(tContent('props.table.onPressedChange.description')) },
  { name: 'disabled',           type: 'boolean',                       defaultValue: 'false',     required: tContent('props.table.disabled.required'),       description: stripHtml(tContent('props.table.disabled.description'))       },
  { name: 'variant',            type: '"default" | "outline"',         defaultValue: '"default"', required: tContent('props.table.variant.required'),        description: stripHtml(tContent('props.table.variant.description'))        },
  { name: 'size',               type: '"default" | "sm" | "lg"',       defaultValue: '"default"', required: tContent('props.table.size.required'),           description: stripHtml(tContent('props.table.size.description'))           },
  { name: 'class',              type: 'string',                        defaultValue: '—',         required: tContent('props.table.className.required'),      description: stripHtml(tContent('props.table.className.description'))      },
]);

const tokenRows = computed(() => [
  { token: '--muted',       value: tContent('tokens.table.muted.class'),       description: tContent('tokens.table.muted.part')       },
  { token: '--foreground',  value: tContent('tokens.table.foreground.class'),  description: tContent('tokens.table.foreground.part')  },
  { token: '--input',       value: tContent('tokens.table.input.class'),       description: tContent('tokens.table.input.part')       },
  { token: '--ring',        value: tContent('tokens.table.ring.class'),        description: tContent('tokens.table.ring.part')        },
  { token: '--destructive', value: tContent('tokens.table.destructive.class'), description: tContent('tokens.table.destructive.part') },
  { token: '--radius-button', value: tContent('tokens.table.radius.class'),    description: tContent('tokens.table.radius.part')      },
]);

const accessibilityItems = computed(() => [
  tContent('accessibility.items.item1'),
  tContent('accessibility.items.item2'),
  tContent('accessibility.items.item3'),
  tContent('accessibility.items.item4'),
  tContent('accessibility.items.item5'),
  tContent('accessibility.items.item6'),
]);

const keyboardItems = computed(() => [
  { key: 'Tab',   description: tContent('accessibility.keyboard.tab')   },
  { key: 'Space', description: tContent('accessibility.keyboard.space') },
  { key: 'Enter', description: tContent('accessibility.keyboard.enter') },
]);

const relatedItems = computed(() => [
  { name: 'ToggleGroup', description: tContent('related.items.toggleGroup.description'), path: '?path=/docs/ui-togglegroup--docs' },
  { name: 'Switch',      description: tContent('related.items.switch.description'),      path: '?path=/docs/ui-switch--docs'      },
  { name: 'Checkbox',    description: tContent('related.items.checkbox.description'),    path: '?path=/docs/ui-checkbox--docs'    },
  { name: 'Button',      description: tContent('related.items.button.description'),      path: '?path=/docs/ui-button--docs'      },
]);

const noteItems = computed(() => [
  { title: '', content: tContent('notes.item1') },
  { title: '', content: tContent('notes.item2') },
  { title: '', content: tContent('notes.item3') },
  { title: '', content: tContent('notes.item4') },
]);

const analyticsItems = computed(() => [
  { event: 'field_change', trigger: tContent('analytics.table.field_change.trigger'), payload: tContent('analytics.table.field_change.payload') },
]);

const a11yCritCols = computed(() => ({
  criterion: tNav('common.criterion'),
  level: 'WCAG',
  how: tNav('common.howToVerify'),
}));

const functionalTestItems = computed(() => [
  { action: tContent('testes.functional.item1.action'), result: tContent('testes.functional.item1.result'), priority: localPriority(tContent('testes.functional.item1.priority')) },
  { action: tContent('testes.functional.item2.action'), result: tContent('testes.functional.item2.result'), priority: localPriority(tContent('testes.functional.item2.priority')) },
  { action: tContent('testes.functional.item3.action'), result: tContent('testes.functional.item3.result'), priority: localPriority(tContent('testes.functional.item3.priority')) },
  { action: tContent('testes.functional.item4.action'), result: tContent('testes.functional.item4.result'), priority: localPriority(tContent('testes.functional.item4.priority')) },
]);

const a11yTestItems = computed(() => [
  { criterion: tContent('testes.accessibility.item1'), level: 'WCAG 2.1', how: '—' },
  { criterion: tContent('testes.accessibility.item2'), level: 'WCAG 2.1', how: '—' },
  { criterion: tContent('testes.accessibility.item3'), level: 'WCAG 2.1', how: '—' },
  { criterion: tContent('testes.accessibility.item4'), level: 'WCAG 2.1', how: '—' },
  { criterion: tContent('testes.accessibility.item5'), level: 'WCAG 2.1', how: '—' },
]);

const visualTestItems = computed(() => [
  { story: tContent('testes.visual.item1.story'), priority: localPriority(tContent('testes.visual.item1.priority')) },
  { story: tContent('testes.visual.item2.story'), priority: localPriority(tContent('testes.visual.item2.priority')) },
  { story: tContent('testes.visual.item3.story'), priority: localPriority(tContent('testes.visual.item3.priority')) },
  { story: tContent('testes.visual.item4.story'), priority: localPriority(tContent('testes.visual.item4.priority')) },
]);
</script>

<template>
  <DocsPageLayout :nav-groups="navGroups" :active-section="activeSection" component-slug="toggle">
    <template #header>
      <DocsHeader
        :title="tContent('title')"
        :description="tContent('description')"
        :category="tContent('category')"
        :type="tContent('type')"
        install-note="npx shadcn-vue@latest add toggle"
      />
    </template>

    <!-- ── Demonstração ─────────────────────────────────────────────── -->
    <DocsDemonstration :title="tContent('demonstration.title')">
      <div class="flex flex-col gap-6 w-full max-w-md">
        <!-- Barra de formatação icon-only -->
        <div class="flex items-center gap-1 rounded-md border p-1">
          <Toggle
            :model-value="demoBold"
            @update:model-value="(v: boolean) => demoBold = v"
            :aria-label="tContent('demonstration.labels.bold')"
          >
            <Bold aria-hidden="true" />
          </Toggle>
          <Toggle
            :model-value="demoItalic"
            @update:model-value="(v: boolean) => demoItalic = v"
            :aria-label="tContent('demonstration.labels.italic')"
          >
            <Italic aria-hidden="true" />
          </Toggle>
          <Toggle
            :model-value="demoUnderline"
            @update:model-value="(v: boolean) => demoUnderline = v"
            :aria-label="tContent('demonstration.labels.underline')"
          >
            <Underline aria-hidden="true" />
          </Toggle>
        </div>

        <!-- Toggle com label visível -->
        <div class="flex items-center gap-2">
          <Toggle
            variant="outline"
            :model-value="demoShowHidden"
            @update:model-value="(v: boolean) => demoShowHidden = v"
          >
            <Eye aria-hidden="true" />
            {{ tContent('demonstration.labels.showHidden') }}
          </Toggle>
          <Toggle
            variant="outline"
            :model-value="demoCompact"
            @update:model-value="(v: boolean) => demoCompact = v"
          >
            <LayoutGrid aria-hidden="true" />
            {{ tContent('demonstration.labels.compactView') }}
          </Toggle>
        </div>
      </div>
    </DocsDemonstration>

    <!-- ── Anatomia ─────────────────────────────────────────────────── -->
    <DocsAnatomy
      :title="tContent('anatomy.title')"
      :items="anatomyItems"
      :structure-label="tContent('anatomy.structureLabel')"
      :structure-code="tContent('anatomy.structureCode')"
    />

    <!-- ── Quando Usar ──────────────────────────────────────────────── -->
    <DocsWhenToUse
      :title="tContent('usage.title')"
      :guidelines="{
        title: tContent('usage.guidelines.title'),
        items: [
          tContent('usage.guidelines.item1'),
          tContent('usage.guidelines.item2'),
          tContent('usage.guidelines.item3'),
          tContent('usage.guidelines.item4'),
        ],
      }"
      :scenarios="{
        title: tContent('usage.scenarios.title'),
        cols: {
          scenario: tContent('usage.scenarios.cols.scenario'),
          use: tContent('usage.scenarios.cols.use'),
          alternative: tContent('usage.scenarios.cols.alternative'),
        },
        items: [
          { s: tContent('usage.scenarios.item1.s'), u: tContent('usage.scenarios.item1.u'), a: tContent('usage.scenarios.item1.a') },
          { s: tContent('usage.scenarios.item2.s'), u: tContent('usage.scenarios.item2.u'), a: tContent('usage.scenarios.item2.a') },
          { s: tContent('usage.scenarios.item3.s'), u: tContent('usage.scenarios.item3.u'), a: tContent('usage.scenarios.item3.a') },
          { s: tContent('usage.scenarios.item4.s'), u: tContent('usage.scenarios.item4.u'), a: tContent('usage.scenarios.item4.a') },
          { s: tContent('usage.scenarios.item5.s'), u: tContent('usage.scenarios.item5.u'), a: tContent('usage.scenarios.item5.a') },
        ],
      }"
      :do="{
        title: tContent('usage.do.title'),
        items: [
          tContent('usage.do.item1'),
          tContent('usage.do.item2'),
          tContent('usage.do.item3'),
          tContent('usage.do.item4'),
        ],
      }"
      :dont="{
        title: tContent('usage.dont.title'),
        items: [
          tContent('usage.dont.item1'),
          tContent('usage.dont.item2'),
          tContent('usage.dont.item3'),
          tContent('usage.dont.item4'),
        ],
      }"
      :ux-writing="{
        title: tContent('usage.uxWriting.title'),
        cols: {
          element: tContent('usage.uxWriting.table.element'),
          rules: tContent('usage.uxWriting.table.rules'),
          do: tContent('usage.uxWriting.table.correct'),
          dont: tContent('usage.uxWriting.table.avoid'),
        },
        items: [
          {
            element: tContent('usage.uxWriting.table.ariaLabel.name'),
            rules: tContent('usage.uxWriting.table.ariaLabel.format'),
            do: tContent('usage.uxWriting.table.ariaLabel.good'),
            dont: tContent('usage.uxWriting.table.ariaLabel.bad'),
          },
          {
            element: tContent('usage.uxWriting.table.label.name'),
            rules: tContent('usage.uxWriting.table.label.format'),
            do: tContent('usage.uxWriting.table.label.good'),
            dont: tContent('usage.uxWriting.table.label.bad'),
          },
          {
            element: tContent('usage.uxWriting.table.icon.name'),
            rules: tContent('usage.uxWriting.table.icon.format'),
            do: tContent('usage.uxWriting.table.icon.good'),
            dont: tContent('usage.uxWriting.table.icon.bad'),
          },
        ],
      }"
    />

    <!-- ── Do & Don't ───────────────────────────────────────────────── -->
    <DocsDoDont
      :title="tContent('doDont.title')"
      :pairs="[
        {
          doLabel: tNav('common.do'),
          dontLabel: tNav('common.dont'),
          doCaption: tContent('doDont.pair1.do'),
          dontCaption: tContent('doDont.pair1.dont'),
        },
        {
          doLabel: tNav('common.do'),
          dontLabel: tNav('common.dont'),
          doCaption: tContent('doDont.pair2.do'),
          dontCaption: tContent('doDont.pair2.dont'),
        },
      ]"
    >
      <!-- Pair 1: aria-label descritivo vs genérico -->
      <template #do-preview-0>
        <Toggle aria-label="Negrito">
          <Bold aria-hidden="true" />
        </Toggle>
      </template>
      <template #dont-preview-0>
        <Toggle aria-label="Botão B">
          <Bold aria-hidden="true" />
        </Toggle>
      </template>

      <!-- Pair 2: ToggleGroup vs múltiplos Toggle soltos -->
      <template #do-preview-1>
        <div class="flex items-center gap-1 rounded-md border p-1">
          <Toggle aria-label="Negrito"><Bold aria-hidden="true" /></Toggle>
          <Toggle aria-label="Itálico"><Italic aria-hidden="true" /></Toggle>
          <Toggle aria-label="Sublinhado"><Underline aria-hidden="true" /></Toggle>
        </div>
      </template>
      <template #dont-preview-1>
        <div class="flex items-center gap-3">
          <Toggle aria-label="Negrito"><Bold aria-hidden="true" /></Toggle>
          <Toggle aria-label="Itálico"><Italic aria-hidden="true" /></Toggle>
          <Toggle aria-label="Sublinhado"><Underline aria-hidden="true" /></Toggle>
        </div>
      </template>
    </DocsDoDont>

    <!-- ── Importação ───────────────────────────────────────────────── -->
    <DocsImport
      :title="tContent('import.title')"
      :code="codeImportBasic"
    />

    <!-- ── Variantes ────────────────────────────────────────────────── -->
    <DocsVariants :title="tContent('variants.title')" :items="variantItems" component-slug="toggle">
      <!-- default -->
      <template #variant-preview-0>
        <Toggle aria-label="Negrito">
          <Bold aria-hidden="true" />
        </Toggle>
      </template>

      <!-- outline -->
      <template #variant-preview-1>
        <Toggle variant="outline" aria-label="Itálico">
          <Italic aria-hidden="true" />
        </Toggle>
      </template>

      <!-- withLabel -->
      <template #variant-preview-2>
        <Toggle variant="outline">
          <Eye aria-hidden="true" />
          Mostrar ocultos
        </Toggle>
      </template>
    </DocsVariants>

    <!-- ── Estados ──────────────────────────────────────────────────── -->
    <DocsStates
      :title="tContent('states.title')"
      :cols="{
        state: 'Estado',
        trigger: 'Trigger',
        behavior: 'Comportamento',
      }"
      :items="stateItems"
    />

    <!-- ── Propriedades ─────────────────────────────────────────────── -->
    <DocsProps
      :title="tContent('props.title')"
      :tables="[
        {
          title: 'Toggle',
          cols: propCols,
          items: togglePropItems,
        },
      ]"
      :interface-code="interfaceCode"
    />

    <!-- ── Tokens ────────────────────────────────────────────────────── -->
    <DocsTokens
      :title="tContent('tokens.title')"
      :cols="{
        token: tContent('tokens.table.token'),
        value: tContent('tokens.table.class'),
        description: tContent('tokens.table.part'),
      }"
      :items="tokenRows"
      :customization-title="tContent('tokens.customizationTitle')"
      :customization-code="codeCustomizationTokens"
    />

    <!-- ── Acessibilidade ───────────────────────────────────────────── -->
    <DocsAccessibility
      :title="tContent('accessibility.title')"
      :summary="tContent('accessibility.summary')"
      :items="accessibilityItems"
      :keyboard-items="keyboardItems"
    />

    <!-- ── Relacionados ─────────────────────────────────────────────── -->
    <DocsRelated :title="tContent('related.title')" :items="relatedItems" />

    <!-- ── Notas ────────────────────────────────────────────────────── -->
    <DocsNotes :title="tContent('notes.title')" :items="noteItems" />

    <!-- ── Analytics ────────────────────────────────────────────────── -->
    <DocsAnalytics
      :title="tContent('analytics.title')"
      :cols="{
        event: tContent('analytics.table.event'),
        trigger: tContent('analytics.table.trigger'),
        payload: tContent('analytics.table.payload'),
      }"
      :items="analyticsItems"
    />

    <!-- ── Testes ────────────────────────────────────────────────────── -->
    <DocsTestes
      :title="tContent('testes.title')"
      :functional="{
        title: tContent('testes.functional.title'),
        cols: {
          action: tNav('common.userAction'),
          result: tNav('common.expectedResult'),
          priority: tNav('common.priority'),
        },
        items: functionalTestItems,
      }"
      :accessibility="{
        title: tContent('testes.accessibility.title'),
        cols: a11yCritCols,
        items: a11yTestItems,
      }"
      :visual="{
        title: tContent('testes.visual.title'),
        cols: {
          story: tNav('common.storyState'),
          priority: tNav('common.priority'),
        },
        items: visualTestItems,
      }"
    />
  </DocsPageLayout>
</template>
