// design-system-svelte/src/components/ui/input-otp/input-otp-slot.svelte
<script lang="ts">
	import { PinInput as InputOTPPrimitive } from "bits-ui";
	import { cn } from "@/lib/utils.js";

	let {
		ref = $bindable(null),
		cell,
		class: className,
		...restProps
	}: InputOTPPrimitive.CellProps = $props();
</script>

<InputOTPPrimitive.Cell
	{cell}
	bind:ref
	data-slot="input-otp-slot"
	class={cn(
		"nds-input-otp-slot",
		className
	)}
	{...restProps}
>
	{cell.char}
	{#if cell.hasFakeCaret}
		<div
			class="nds-input-otp-caret-wrap"
		>
			<div class="nds-input-otp-caret"></div>
		</div>
	{/if}
</InputOTPPrimitive.Cell>

// design-system-vue/src/components/ui/input-otp/InputOTPSlot.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { reactiveOmit } from '@vueuse/core'
import { useForwardProps } from 'reka-ui'
import { computed } from 'vue'
import { useVueOTPContext } from 'vue-input-otp'
import { cn } from '@/lib/utils'

const props = defineProps<{ index: number, class?: HTMLAttributes['class'] }>()

const delegatedProps = reactiveOmit(props, 'class')

const forwarded = useForwardProps(delegatedProps)

const context = useVueOTPContext()

const slot = computed(() => context?.value.slots[props.index])
</script>

<template>
  <div
    v-bind="forwarded"
    data-slot="input-otp-slot"
    :data-active="slot?.isActive"
    :class="cn('nds-input-otp-slot', props.class)"
  >
    {{ slot?.char }}
    <div
      v-if="slot?.hasFakeCaret"
      class="nds-input-otp-caret-wrap"
    >
      <div class="nds-input-otp-caret" />
    </div>
  </div>
</template>
