// design-system-react/src/components/docs/shared/DocsSection.tsx
import React from 'react';
import { cn } from '@/lib/utils';

interface DocsSectionProps {
  id?: string;
  title: string;
  description?: string;
  children: React.ReactNode;
  className?: string;
  noSeparator?: boolean;
}

export function DocsSection({ id, title, description, children, className, noSeparator }: DocsSectionProps) {
  return (
    <section id={id} className={cn("space-y-4 scroll-mt-24", className)}>
      {!noSeparator && <hr className="border-border my-12" />}
      <div className="space-y-1">
        <h2 className="text-2xl font-semibold tracking-tight">{title}</h2>
        {description && (
          <p className="text-muted-foreground">{description}</p>
        )}
      </div>
      <div>
        {children}
      </div>
    </section>
  );
}

// design-system-vue/src/components/docs/shared/DocsSection.vue
<script setup lang="ts">
defineProps<{
  id?: string;
  title: string;
  description?: string;
  noSeparator?: boolean;
}>();
</script>

<template>
  <section :id="id" class="space-y-4 scroll-mt-24">
    <hr v-if="!noSeparator" class="border-border my-12" />
    <div class="space-y-1">
      <h2 class="text-2xl font-semibold tracking-tight">{{ title }}</h2>
      <p v-if="description" class="text-muted-foreground">{{ description }}</p>
    </div>
    <div><slot /></div>
  </section>
</template>
