// nortear-design-system-vue/src/components/ui/alert/AlertAction.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <div
    data-slot="alert-action"
    :class="cn('nds-alert-action', props.class)"
  >
    <slot />
  </div>
</template>

// nortear-design-system-svelte/src/components/ui/alert/alert-action.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "@/lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="alert-action"
	class={cn("nds-alert-action", className)}
	{...restProps}
>
	{@render children?.()}
</div>
