// nortear-design-system-svelte/src/components/ui/code-block/code-block.svelte
<script lang="ts">
	/**
	 * A tokenização vem de `@shared/primitives/code-highlight` (TS puro) e devolve
	 * dados, não HTML — cada span vira um nó do template, então não há `{@html}` e
	 * nada a sanitizar. Cores, layout e destaque vivem em `nds/code-block.css`.
	 */
	import type { Snippet } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import Check from "@lucide/svelte/icons/check";
	import Copy from "@lucide/svelte/icons/copy";
	import { cn, type WithElementRef } from "@/lib/utils.js";
	import { Button } from "@/components/ui/button";
	import { copyText } from "@shared/primitives/clipboard";
	import {
		highlightCode,
		parseLineRanges,
		resolveLanguage,
		type LineRangeInput,
	} from "@shared/primitives/code-highlight";

	let {
		ref = $bindable(null),
		code,
		language,
		title,
		showLineNumbers = true,
		highlightLines,
		footer,
		copyLabel = "Copiar código",
		copiedLabel = "Copiado!",
		class: className,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		/** Código a exibir. É exatamente o que o botão copiar coloca no clipboard. */
		code: string;
		/** Linguagem ou extensão (`tsx`, `svelte`, `.css`, `bash`). Desconhecida → sem cor. */
		language?: string;
		/** Rótulo do header, normalmente o nome do arquivo. */
		title?: string;
		/** Numeração de linha. */
		showLineNumbers?: boolean;
		/** Linhas destacadas: `[3, '5-7']` ou `'3, 5-7'`. */
		highlightLines?: LineRangeInput;
		/** Observações abaixo do código. Aceita string ou snippet. */
		footer?: string | Snippet;
		copyLabel?: string;
		copiedLabel?: string;
	} = $props();

	const lines = $derived(highlightCode(code, resolveLanguage(language)));
	const highlighted = $derived(parseLineRanges(highlightLines));

	let copied = $state(false);
	let timer: ReturnType<typeof setTimeout> | undefined;

	// Limpa o timer no unmount: sem isso, desmontar dentro dos 2s escreve num
	// $state de componente já destruído.
	$effect(() => () => clearTimeout(timer));

	async function handleCopy() {
		// copyText já cobre o fallback fora de contexto seguro; false = não copiou,
		// e nesse caso não confirmamos nada. Chamar navigator.clipboard direto
		// deixa o botão inerte em http sem localhost, onde as outras stacks ainda
		// copiam.
		if (!(await copyText(code))) return;
		copied = true;
		clearTimeout(timer);
		timer = setTimeout(() => { copied = false; }, 2000);
	}
</script>

<div
	bind:this={ref}
	data-slot="code-block"
	data-numbered={showLineNumbers ? "true" : "false"}
	class={cn("nds-code-block-root", className)}
	{...restProps}
>
	<div class="nds-code-block-header">
		{#if title}
			<span class="nds-code-block-title">{title}</span>
		{/if}
		<span class="nds-code-block-actions">
			{#if copied}
				<span class="nds-code-block-copy-label" aria-hidden="true">{copiedLabel}</span>
			{/if}
			<Button
				type="button"
				variant="ghost"
				size="icon-sm"
				data-slot="code-block-copy"
				aria-label={copied ? copiedLabel : copyLabel}
				onclick={handleCopy}
			>
				{#if copied}
					<Check class="nds-icon" aria-hidden="true" />
				{:else}
					<Copy class="nds-icon" aria-hidden="true" />
				{/if}
			</Button>
		</span>
	</div>

	<!-- aria-live fora do botão: leitor de tela anuncia a confirmação sem que o
	     rótulo do botão mude no meio da interação. -->
	<span class="nds-sr-only" role="status" aria-live="polite">{copied ? copiedLabel : ""}</span>

	<div class="nds-code-block-scroll" tabindex="0">
		<pre class="nds-code-block-pre"><code class="nds-code-block-code">{#each lines as spans, i (i)}<span
			class="nds-code-block-line"
			data-highlighted={highlighted.has(i + 1) ? "true" : undefined}
		><span class="nds-code-block-gutter" aria-hidden="true">{i + 1}</span><span
			class="nds-code-block-text"
		>{#each spans as span, j (j)}{#if span.token !== "plain"}<span data-token={span.token}>{span.text}</span>{:else}{span.text}{/if}{/each}{#if spans.length === 0}
{/if}</span></span>{/each}</code></pre>
	</div>

	{#if footer}
		<div class="nds-code-block-footer">
			{#if typeof footer === "string"}{footer}{:else}{@render footer()}{/if}
		</div>
	{/if}
</div>

// nortear-design-system-vue/src/components/ui/code-block/CodeBlock.vue
<script setup lang="ts">
/**
 * A tokenização vem de `@shared/primitives/code-highlight` (TS puro) e devolve
 * dados, não HTML — cada span vira um nó do template, então não há `v-html` e
 * nada a sanitizar. Cores, layout e destaque vivem em `nds/code-block.css`.
 */
import type { HTMLAttributes } from 'vue'
import { computed, onBeforeUnmount, ref } from 'vue'
import { Check, Copy } from 'lucide-vue-next'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { copyText } from '@shared/primitives/clipboard'
import {
  highlightCode,
  parseLineRanges,
  resolveLanguage,
  type LineRangeInput,
} from '@shared/primitives/code-highlight'

const props = withDefaults(defineProps<{
  /** Código a exibir. É exatamente o que o botão copiar coloca no clipboard. */
  code: string
  /** Linguagem ou extensão (`tsx`, `vue`, `.css`, `bash`). Desconhecida → sem cor. */
  language?: string
  /** Rótulo do header, normalmente o nome do arquivo. */
  title?: string
  /** Numeração de linha. */
  showLineNumbers?: boolean
  /** Linhas destacadas: `[3, '5-7']` ou `'3, 5-7'`. */
  highlightLines?: LineRangeInput
  /** Observações abaixo do código. Também aceita o slot `footer`. */
  footer?: string
  copyLabel?: string
  copiedLabel?: string
  class?: HTMLAttributes['class']
}>(), {
  showLineNumbers: true,
  copyLabel: 'Copiar código',
  copiedLabel: 'Copiado!',
})

const lines = computed(() => highlightCode(props.code, resolveLanguage(props.language)))
const highlighted = computed(() => parseLineRanges(props.highlightLines))

const copied = ref(false)
let timer: ReturnType<typeof setTimeout> | undefined

// Limpa o timer no unmount: sem isso, desmontar dentro dos 2s mexe num ref de
// componente já destruído.
onBeforeUnmount(() => clearTimeout(timer))

async function handleCopy() {
  // copyText já cobre o fallback fora de contexto seguro; false = não copiou,
  // e nesse caso não confirmamos nada. Chamar navigator.clipboard direto deixa
  // o botão inerte em http sem localhost, onde as outras stacks ainda copiam.
  if (!(await copyText(props.code))) return
  copied.value = true
  clearTimeout(timer)
  timer = setTimeout(() => { copied.value = false }, 2000)
}
</script>

<template>
  <div
    data-slot="code-block"
    :data-numbered="showLineNumbers ? 'true' : 'false'"
    :class="cn('nds-code-block-root', props.class)"
  >
    <div class="nds-code-block-header">
      <span
        v-if="title"
        class="nds-code-block-title"
      >{{ title }}</span>
      <span class="nds-code-block-actions">
        <span
          v-if="copied"
          class="nds-code-block-copy-label"
          aria-hidden="true"
        >{{ copiedLabel }}</span>
        <Button
          type="button"
          variant="ghost"
          size="icon-sm"
          data-slot="code-block-copy"
          :aria-label="copied ? copiedLabel : copyLabel"
          @click="handleCopy"
        >
          <Check
            v-if="copied"
            class="nds-icon"
            aria-hidden="true"
          />
          <Copy
            v-else
            class="nds-icon"
            aria-hidden="true"
          />
        </Button>
      </span>
    </div>

    <!-- aria-live fora do botão: leitor de tela anuncia a confirmação sem que o
         rótulo do botão mude no meio da interação. -->
    <span
      class="nds-sr-only"
      role="status"
      aria-live="polite"
    >{{ copied ? copiedLabel : '' }}</span>

    <div
      class="nds-code-block-scroll"
      tabindex="0"
    >
      <pre class="nds-code-block-pre"><code class="nds-code-block-code"><span
        v-for="(spans, i) in lines"
        :key="i"
        class="nds-code-block-line"
        :data-highlighted="highlighted.has(i + 1) ? 'true' : undefined"
      ><span
        class="nds-code-block-gutter"
        aria-hidden="true"
      >{{ i + 1 }}</span><span class="nds-code-block-text"><template
        v-for="(span, j) in spans"
        :key="j"
      ><span
        v-if="span.token !== 'plain'"
        :data-token="span.token"
      >{{ span.text }}</span><template v-else>{{ span.text }}</template></template><template v-if="spans.length === 0">
</template></span></span></code></pre>
    </div>

    <div
      v-if="footer || $slots.footer"
      class="nds-code-block-footer"
    >
      <slot name="footer">{{ footer }}</slot>
    </div>
  </div>
</template>
