// nortear-design-system-angular/src/components/docs/shared/Swatch.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  OnDestroy,
  signal,
  ViewEncapsulation,
} from '@angular/core';

/**
 * Swatches da página "Cores e Temas" — duas variantes, como nas outras stacks.
 *
 * `div[ndsMiniSwatch]`  — chip com o nome do token abaixo (amostra compacta).
 * `button[ndsSwatch]`   — chip + `--token` + valor HSL, clicável para copiar.
 *
 * Seletor de ATRIBUTO nos dois: o CSS compartilhado (`docs-swatches.css`)
 * estiliza `.nds-swatch` como se ele FOSSE o `<button>` — flex, borda, foco. Um
 * seletor de elemento (`nds-swatch`, tag própria) inseriria um nó extra entre a
 * grade e o botão, e a regra passaria a pintar o invólucro.
 *
 * A cor entra por `--swatch-color`, nunca por style inline de cor: é o mesmo
 * mecanismo do `--ratio` no AspectRatio — custom property carregando um VALOR
 * escolhido no call site, com a forma toda no CSS compartilhado. Assim o chip
 * acompanha tema, modo e marca sem esta página saber qual está ativo.
 */

/** `var(--token)` — o valor que o CSS resolve no escopo onde o chip está. */
function colorReferencia(token: string): string {
  return `var(--${token})`;
}

@Component({
  selector: 'div[ndsMiniSwatch]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: { class: 'nds-miniswatch' },
  template: `
    <span
      class="nds-miniswatch-chip"
      [style.--swatch-color]="tokenColor()"
      aria-hidden="true"
    ></span>
    <span class="nds-miniswatch-name">{{ token() }}</span>
  `,
})
export class NdsMiniSwatch {
  /** Nome do token CSS sem o prefixo `--`. */
  readonly token = input.required<string>();

  protected readonly tokenColor = computed(() => colorReferencia(this.token()));
}

@Component({
  selector: 'button[ndsSwatch]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'nds-swatch',
    type: 'button',
    '[attr.aria-label]': 'accessibleLabel()',
    '(click)': 'copiar()',
  },
  template: `
    <span class="nds-swatch-color" [style.--swatch-color]="tokenColor()" aria-hidden="true"></span>
    <div class="nds-swatch-meta">
      <span class="nds-swatch-token">--{{ token() }}</span>
      <span class="nds-swatch-value">{{ value() || '—' }}</span>
    </div>
    <span class="nds-icon-tile-tooltip" [class.is-visible]="copiado()" aria-hidden="true">{{
      copiado() ? copiedLabel() : copyLabel()
    }}</span>
  `,
})
export class NdsSwatch implements OnDestroy {
  /** Nome do token CSS sem o prefixo `--`. */
  readonly token = input.required<string>();
  /** Valor HSL já resolvido — quem lê o `<html>` é a página, não o swatch. */
  readonly value = input('');
  /** Rótulo do tooltip de cópia. */
  readonly copyLabel = input('');
  /** Rótulo do tooltip depois de copiar. */
  readonly copiedLabel = input('');

  protected readonly copiado = signal(false);
  protected readonly tokenColor = computed(() => colorReferencia(this.token()));
  protected readonly accessibleLabel = computed(
    () => `${this.copyLabel()} --${this.token()}`,
  );

  private relogio: ReturnType<typeof setTimeout> | undefined;

  protected copiar(): void {
    navigator.clipboard
      .writeText(`--${this.token()}`)
      .then(() => {
        this.copiado.set(true);
        clearTimeout(this.relogio);
        this.relogio = setTimeout(() => this.copiado.set(false), 1500);
      })
      .catch(() => {
        // Área de transferência negada (permissão ou contexto inseguro): a
        // página segue navegável, só não confirma a cópia.
      });
  }

  ngOnDestroy(): void {
    clearTimeout(this.relogio);
  }
}

export const NDS_SWATCH = [NdsMiniSwatch, NdsSwatch] as const;

// nortear-design-system-react/src/components/docs/shared/Swatch.tsx
import { useState, useCallback, type CSSProperties } from 'react';

export interface SwatchProps {
  /** Nome do token CSS sem o prefixo `--`. */
  token: string;
  /**
   * `vertical` — chip com o nome do token abaixo (mini-swatch de demonstração).
   * `horizontal` — chip + `--token` + valor HSL, clicável para copiar.
   */
  orientation?: 'vertical' | 'horizontal';
  /** Valor HSL resolvido (apenas `horizontal`). */
  value?: string;
  /** Rótulo do tooltip de cópia (apenas `horizontal`). */
  copyLabel?: string;
  /** Rótulo do tooltip após copiar (apenas `horizontal`). */
  copiedLabel?: string;
}

/**
 * Swatch de cor reutilizável da página "Cores e Temas". Duas variantes:
 * vertical (nome abaixo da cor) e horizontal (variável + código HSL, copiável).
 * Visual 100% via classes .nds-swatch* / .nds-miniswatch* (docs-swatches.css);
 * o único estilo dinâmico é a custom property --swatch-color por token.
 */
export function Swatch({
  token,
  orientation = 'vertical',
  value,
  copyLabel = '',
  copiedLabel = '',
}: SwatchProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard
      .writeText(`--${token}`)
      .then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      })
      .catch(() => {});
  }, [token]);

  const swatchColor = { '--swatch-color': `var(--${token})` } as CSSProperties;

  if (orientation === 'vertical') {
    return (
      <div className="nds-miniswatch">
        <span className="nds-miniswatch-chip" style={swatchColor} aria-hidden="true" />
        <span className="nds-miniswatch-name">{token}</span>
      </div>
    );
  }

  return (
    <button
      type="button"
      onClick={handleCopy}
      aria-label={`${copyLabel} --${token}`}
      className="nds-swatch"
    >
      <span className="nds-swatch-color" style={swatchColor} aria-hidden="true" />
      <div className="nds-swatch-meta">
        <span className="nds-swatch-token">--{token}</span>
        <span className="nds-swatch-value">{value || '—'}</span>
      </div>
      <span
        className="nds-icon-tile-tooltip"
        style={copied ? { opacity: 1 } : undefined}
        aria-hidden="true"
      >
        {copied ? copiedLabel : copyLabel}
      </span>
    </button>
  );
}
