// nortear-design-system-vue/src/components/docs/TypographyDocs.vue
<script setup lang="ts">
import FoundationsRenderer from '@/components/docs/shared/FoundationsRenderer.vue';
import translations from '@shared/content/foundations/tipografia/translations.json';
import { useTranslation } from '@/lib/i18n';
import DOMPurify from 'dompurify';

const { t } = useTranslation(translations);
</script>

<!--
  Specimens visuais usando os elementos HTML padrão — as regras `.nds-type-specimen` (typography.css) aplicam o type scale ativo.
  Textos vêm de translations.json (specimens.*); nds-m-0 zera as margens
  NATIVAS dos elementos base dentro do nds-stack.
-->
<template>
  <FoundationsRenderer
    component-slug="foundations/tipografia"
    :translations="translations"
  >
    <template #extra>
      <section
        class="nds-stack nds-docs-section-divider"
        data-spacing="md"
      >
        <div
          class="nds-stack"
          data-spacing="xs"
        >
          <h2 class="nds-text-h2 nds-text-foreground">{{ t('specimens.title') }}</h2>
          <p class="nds-text-body">{{ t('specimens.subtitle') }}</p>
        </div>

        <div
          class="nds-type-specimen nds-stack nds-rounded-lg nds-border-default nds-p-6 nds-bg-card"
          data-spacing="md"
        >
          <h1 class="nds-m-0">{{ t('specimens.h1') }}</h1>
          <h2 class="nds-m-0">{{ t('specimens.h2') }}</h2>
          <h3 class="nds-m-0">{{ t('specimens.h3') }}</h3>
          <h4 class="nds-m-0">{{ t('specimens.h4') }}</h4>
          <p
            class="nds-m-0 nds-text-foreground"
            v-html="DOMPurify.sanitize(t('specimens.body'))"
          />
          <label class="nds-block nds-text-foreground">{{ t('specimens.label') }}</label>
        </div>
      </section>
    </template>
  </FoundationsRenderer>
</template>

// design-system-react/src/components/docs/TypographyDocs.tsx
import { FoundationPage } from './shared/FoundationPage';
import translations from '@shared/content/foundations/tipografia/translations.json';

// Specimens visuais usando os elementos HTML padrão — `@layer base` em
// globals.css aplica os tokens `--text-*`, `--font-weight-*` e `--line-height-*`
// automaticamente. Não precisamos repetir classes utilitárias aqui.
function TypographySpecimens() {
  return (
    <section className="nds-stack nds-docs-section-divider" data-spacing="lg">
      <div className="nds-stack" data-spacing="xs">
        <h2 className="nds-text-h2 nds-text-foreground">Specimens</h2>
        <p className="nds-text-body">
          Hierarquia renderizada com os elementos HTML padrão do tema ativo.
        </p>
      </div>

      <div className="nds-stack nds-rounded-lg nds-border-default nds-p-6 nds-bg-card" data-spacing="md">
        <h1 className="nds-m-0">Heading 1 — título de página</h1>
        <h2 className="nds-m-0">Heading 2 — seção principal</h2>
        <h3 className="nds-m-0">Heading 3 — subseção</h3>
        <h4 className="nds-m-0">Heading 4 — agrupamento menor</h4>
        <p className="nds-m-0 nds-text-foreground">
          Parágrafo de corpo. The quick brown fox jumps over the lazy dog. Texto
          corrido usa <code>--text-p</code> (14px) com <code>--line-height-normal</code>
          (1.5) — base WCAG 1.4.12.
        </p>
        <label className="nds-block nds-text-foreground">
          Label — rótulo de formulário
        </label>
      </div>
    </section>
  );
}

export function TypographyDocs() {
  return (
    <FoundationPage
      slug="tipografia"
      translations={translations}
      extraSection={<TypographySpecimens />}
    />
  );
}
