// nortear-design-system-vue/src/components/ui/combobox/ComboboxItemIndicator.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { CheckIcon } from 'lucide-vue-next'
import { ComboboxItemIndicator } from 'reka-ui'
import { cn } from '@/lib/utils'

const props = defineProps<{ class?: HTMLAttributes['class'] }>()

/*
 * O invólucro está sempre no DOM e a marca só aparece na opção escolhida: é ele
 * que reserva a largura, para a linha não pular de tamanho a cada escolha.
 */
</script>

<template>
  <span
    data-slot="combobox-item-indicator"
    :class="cn('nds-combobox-item-indicator', props.class)"
  >
    <ComboboxItemIndicator>
      <slot>
        <CheckIcon />
      </slot>
    </ComboboxItemIndicator>
  </span>
</template>

// nortear-design-system-svelte/src/components/ui/combobox/combobox-item-indicator.svelte
<script lang="ts">
	import CheckIcon from '@lucide/svelte/icons/check';
	import { cn } from '@/lib/utils.js';

	// Sempre no fluxo, escondida por `visibility` quando a opção não está
	// escolhida: tirar o nó faria o rótulo dançar para o lado a cada escolha.

	let { class: className }: { class?: string } = $props();
</script>

<span class={cn('nds-combobox-item-indicator', className)} data-slot="combobox-item-indicator">
	<CheckIcon aria-hidden="true" />
</span>
