// design-system-vue/src/components/ui/combobox/ComboboxGroup.vue
<script setup lang="ts">
import type { ComboboxGroupProps } from 'reka-ui'
import type { HTMLAttributes } from 'vue'
import { reactiveOmit } from '@vueuse/core'
import { ComboboxGroup, ComboboxLabel } from 'reka-ui'
import { cn } from '@/lib/utils'

const props = defineProps<ComboboxGroupProps & {
  class?: HTMLAttributes['class']
  heading?: string
}>()

const delegatedProps = reactiveOmit(props, 'class')
</script>

<template>
  <ComboboxGroup
    data-slot="combobox-group"
    v-bind="delegatedProps"
    :class="cn('nds-command-group', props.class)"
  >
    <ComboboxLabel
      v-if="heading"
      class="nds-command-group-heading"
    >
      {{ heading }}
    </ComboboxLabel>
    <slot />
  </ComboboxGroup>
</template>

// nortear-design-system-svelte/src/components/ui/combobox/combobox-group.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { Combobox as ComboboxPrimitive } from 'bits-ui';
	import { cn } from '@/lib/utils.js';

	let {
		class: className,
		children,
		...restProps
	}: { class?: string; children?: Snippet } & Record<string, unknown> = $props();
</script>

<ComboboxPrimitive.Group
	class={cn('nds-combobox-group', className)}
	data-slot="combobox-group"
	{...restProps}
>
	{@render children?.()}
</ComboboxPrimitive.Group>
