// nortear-design-system-react/src/components/docs/ChatThreadDocs.tsx
import { Fragment, useCallback, useEffect, useMemo } from "react";
import { ChatThread } from "@/components/ui/chat-thread";
import { Separator } from "@/components/ui/separator";
import { paraMensagens, useChatLabels } from "@/components/ui/chat-thread.fixtures";
import { useTranslation } from "@/lib/i18n";
import { useSeoEffect } from "@/lib/use-seo";
import { track } from "@/lib/analytics";
import { useActiveSection } from "@/lib/use-active-section";
import uiTranslations from "@/i18n/ui.json";
import chatTranslations from "@shared/content/chat-thread/translations.json";
import {
  CHAT_COM_FERRAMENTAS,
  CHAT_CONVERSA,
  CHAT_EM_STREAMING,
  CHAT_FERRAMENTA_FALHOU,
  type ChatExampleMessage,
} from "@shared/primitives/chat-examples";

import { DocsHeader }        from "@/components/docs/shared/sections/DocsHeader";
import { DocsPageLayout }    from "@/components/docs/shared/sections/DocsPageLayout";
import { DocsDemonstration } from "@/components/docs/shared/sections/DocsDemonstration";
import { DocsAnatomy }       from "@/components/docs/shared/sections/DocsAnatomy";
import { DocsWhenToUse }     from "@/components/docs/shared/sections/DocsWhenToUse";
import { DocsDoDont }        from "@/components/docs/shared/sections/DocsDoDont";
import { DocsImport }        from "@/components/docs/shared/sections/DocsImport";
import { DocsVariants }      from "@/components/docs/shared/sections/DocsVariants";
import { DocsStates }        from "@/components/docs/shared/sections/DocsStates";
import { DocsProps }         from "@/components/docs/shared/sections/DocsProps";
import { DocsTokens }        from "@/components/docs/shared/sections/DocsTokens";
import { DocsAccessibility } from "@/components/docs/shared/sections/DocsAccessibility";
import { DocsRelated }       from "@/components/docs/shared/sections/DocsRelated";
import { DocsNotes }         from "@/components/docs/shared/sections/DocsNotes";
import { DocsAnalytics }     from "@/components/docs/shared/sections/DocsAnalytics";
import { DocsTestes }        from "@/components/docs/shared/sections/DocsTestes";
import { toPlainText } from "@/lib/strip-html";

// ─── Helpers ─────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: "common.high",
  medium: "common.medium",
  low: "common.low",
};

// ─── Nav ─────────────────────────────────────────────────────────────────────

const getNavGroups = (t: (key: string) => string) => [
  {
    label: t("nav.overview"),
    sections: [
      { id: "demonstracao", label: t("nav.demonstration") },
      { id: "anatomia",     label: t("nav.anatomy") },
      { id: "quando-usar",  label: t("nav.usage") },
      { id: "do-dont",      label: t("nav.doDont") },
    ],
  },
  {
    label: t("nav.techRef"),
    sections: [
      { id: "importacao",   label: t("nav.import") },
      { id: "variantes",    label: t("nav.variants") },
      { id: "estados",      label: t("nav.states") },
      { id: "propriedades", label: t("nav.props") },
      { id: "tokens",       label: t("nav.tokens") },
    ],
  },
  {
    label: t("nav.context"),
    sections: [
      { id: "acessibilidade", label: t("nav.accessibility") },
      { id: "relacionados",   label: t("nav.related") },
      { id: "notas",          label: t("nav.notes") },
    ],
  },
  {
    label: t("nav.quality"),
    sections: [
      { id: "analytics", label: t("nav.analytics") },
      { id: "testes",    label: t("nav.testes") },
    ],
  },
];

const INTERFACE_CODE = `interface ChatThreadProps extends Omit<React.ComponentProps<"div">, "children"> {
  messages: ChatMessage[];
  labels: ChatThreadLabels;
  error?: string;
  size?: "xs" | "sm" | "md" | "lg" | "xl";
}

// A LISTA é a API: quem faz streaming troca o array.
//   mensagem nova   — acrescenta ao fim, e é por ela que a rolagem decide
//   mesmo \`id\`      — onde o streaming pousa, sem remontar a mensagem
//   \`error\`         — a falha da execução, fora da conversa`;

// ─── Componente principal ─────────────────────────────────────────────────────

export function ChatThreadDocs() {
  const { t: tNav } = useTranslation(uiTranslations);
  // A ÚNICA linha sobrescrita é o TIPO de `actions`, e por um motivo de API: o
  // conteúdo compartilhado descreve o tipo na API do Vanilla, onde os botões do
  // turno chegam como lista de elementos. Aqui eles chegam como nó, e o que se
  // passa é qualquer coisa que o renderizador saiba desenhar. O nome da prop é
  // o mesmo nas duas, então só o tipo diverge.
  const { t: tContent, locale } = useTranslation(chatTranslations, {
    "*": { "props.table.actions.type": "ReactNode" },
  });
  const labels = useChatLabels();

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria.
  // O `title` fica de fora: ele é o cabeçalho da lista, não um item dela.
  const screenReaderItems = useMemo(
    () =>
      Object.entries(
        (chatTranslations as unknown as Record<
          string,
          { accessibility?: { screenReader?: Record<string, string> } }
        >)[locale]?.accessibility?.screenReader ?? {},
      )
        .filter(([key]) => key !== "title")
        .map(([, value]) => value),
    [locale],
  );

  const navGroups = useMemo(() => getNavGroups(tNav), [tNav]);
  const allIds = useMemo(
    () => navGroups.flatMap((g) => g.sections.map((s) => s.id)),
    [navGroups],
  );

  useSeoEffect({
    title: tContent("seo.title"),
    description: tContent("seo.description"),
    locale,
    componentSlug: "chat-thread",
  });

  useEffect(() => {
    track("docs_page_view", {
      component_name: "chat-thread",
      locale,
      page_title: `${tContent("title")} · Design System`,
    });
  }, [locale, tContent]);

  const handleSectionChange = useCallback(
    (id: string) => {
      track("docs_section_viewed", {
        section_id: id,
        component_name: "chat-thread",
        locale,
      });
    },
    [locale],
  );

  const activeId = useActiveSection(allIds, handleSectionChange);

  const priorityLabel = (raw: string) => tNav(priorityKeyMap[raw] ?? "common.high");

  /**
   * Uma conversa rotulada.
   *
   * A legenda diz QUAL exemplo está desenhado — sem ela, quatro conversas
   * empilhadas viram uma só, e o assunto da demonstração é justamente a
   * diferença entre elas.
   */
  const example = (labelKey: string, messages: ChatExampleMessage[], streaming = false) => {
    const list = paraMensagens(messages);
    if (streaming) list[list.length - 1].streaming = true;
    return (
      <div className="nds-stack nds-w-full" data-spacing="xs">
        <p className="nds-text-caption nds-text-muted-foreground">{tContent(labelKey)}</p>
        <ChatThread messages={list} labels={labels} size="md" />
      </div>
    );
  };

  // Separador ENTRE os exemplos, e não em volta de cada um.
  //
  // A thread não tem moldura própria — em uso real ela mora dentro de um painel
  // que dá o quadro. Empilhadas na demonstração, quatro delas viram uma sopa: o
  // rótulo de uma encosta no último turno da anterior, e não dá para dizer onde
  // uma acaba. O separador é decorativo de propósito: quem dá a estrutura para
  // quem ouve é a legenda de cada exemplo, não a linha.
  const exemplos = [
    example("demonstration.labels.conversation", CHAT_CONVERSA),
    example("demonstration.labels.tools", CHAT_COM_FERRAMENTAS),
    example("demonstration.labels.streaming", CHAT_EM_STREAMING, true),
    example("demonstration.labels.failed", CHAT_FERRAMENTA_FALHOU),
  ];

  return (
    <DocsPageLayout
      navGroups={navGroups}
      activeSection={activeId}
      header={
        <DocsHeader
          title={tContent("title")}
          description={tContent("description")}
          category={tContent("category")}
          type={tContent("type")}
        />
      }
    >
      {/* ── Demonstração ──────────────────────────────────────────── */}
      <DocsDemonstration componentSlug="chat-thread">
        <div className="nds-stack nds-w-full" data-spacing="lg">
          {exemplos.map((el, i) => (
            <Fragment key={i}>
              {i > 0 && <Separator />}
              {el}
            </Fragment>
          ))}
        </div>
      </DocsDemonstration>

      {/* ── Anatomia ──────────────────────────────────────────────── */}
      <DocsAnatomy
        items={[1, 2, 3, 4, 5].map((i) => tContent(`anatomy.item${i}`))}
        structureLabel={tContent("anatomy.structureLabel")}
        structureCode={tContent("anatomy.structureCode")}
        language="html"
      />

      {/* ── Quando Usar ───────────────────────────────────────────── */}
      <DocsWhenToUse
        guidelines={{
          title: tContent("usage.guidelines.title"),
          items: [1, 2, 3, 4, 5].map((i) => tContent(`usage.guidelines.item${i}`)),
        }}
        scenarios={{
          title: tContent("usage.scenarios.title"),
          cols: {
            scenario: tContent("usage.scenarios.cols.scenario"),
            use: tContent("usage.scenarios.cols.use"),
            alternative: tContent("usage.scenarios.cols.alternative"),
          },
          items: [1, 2, 3, 4, 5].map((i) => ({
            s: tContent(`usage.scenarios.item${i}.s`),
            u: tContent(`usage.scenarios.item${i}.u`),
            a: toPlainText(tContent(`usage.scenarios.item${i}.a`)),
          })),
        }}
        uxWriting={{
          title: tContent("usage.uxWriting.title"),
          cols: {
            element: tContent("usage.uxWriting.table.element"),
            rules: tContent("usage.uxWriting.table.rules"),
            do: tContent("usage.uxWriting.table.correct"),
            dont: tContent("usage.uxWriting.table.avoid"),
          },
          items: ["author", "toolName", "toolState", "system"].map((k) => ({
            element: tContent(`usage.uxWriting.table.${k}.name`),
            rules: tContent(`usage.uxWriting.table.${k}.format`),
            do: tContent(`usage.uxWriting.table.${k}.good`),
            dont: tContent(`usage.uxWriting.table.${k}.bad`),
          })),
        }}
        do={{
          title: tContent("usage.do.title"),
          items: [1, 2, 3, 4].map((i) => tContent(`usage.do.item${i}`)),
        }}
        dont={{
          title: tContent("usage.dont.title"),
          items: [1, 2, 3, 4].map((i) => tContent(`usage.dont.item${i}`)),
        }}
      />

      {/* ── Do & Don't ────────────────────────────────────────────── */}
      <DocsDoDont
        pairs={[
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doCaption: toPlainText(tContent("doDont.pair1.do")),
            dontCaption: toPlainText(tContent("doDont.pair1.dont")),
            // O par é a MESMA conversa: o que muda é para onde a rolagem vai
            // quando a mensagem chega.
            doPreview: (
              <ChatThread messages={paraMensagens(CHAT_CONVERSA)} labels={labels} size="sm" />
            ),
            dontPreview: (
              <ChatThread messages={paraMensagens(CHAT_CONVERSA)} labels={labels} size="sm" />
            ),
          },
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doCaption: toPlainText(tContent("doDont.pair2.do")),
            dontCaption: toPlainText(tContent("doDont.pair2.dont")),
            doPreview: (
              <ChatThread
                messages={paraMensagens(CHAT_FERRAMENTA_FALHOU)}
                labels={labels}
                size="sm"
              />
            ),
            dontPreview: (
              <ChatThread
                messages={paraMensagens(CHAT_FERRAMENTA_FALHOU)}
                // O contraexemplo: o estado sem palavra, só o ícone colorido.
                labels={{
                  ...labels,
                  toolState: { pending: "", running: "", done: "", failed: "" },
                }}
                size="sm"
              />
            ),
          },
        ]}
      />

      {/* ── Importação ────────────────────────────────────────────── */}
      <DocsImport
        description={tContent("import.basic")}
        code={tContent("import.basicCode")}
        secondaryDescription={tContent("import.withStreaming")}
        secondaryCode={tContent("import.withStreamingCode")}
      />

      {/* ── Variantes ─────────────────────────────────────────────── */}
      <DocsVariants
        note={tContent("variants.note")}
        componentSlug="chat-thread"
        items={(["user", "assistant", "system"] as const).map((role) => ({
          name: role,
          description: tContent(`variants.items.${role}.description`),
          code: `<ChatThread\n  messages={[{ role: "${role}", content: texto }]}\n  labels={labels}\n/>`,
          preview: (
            <ChatThread
              messages={paraMensagens(CHAT_CONVERSA.filter((m) => m.role === role))}
              labels={labels}
              size="xs"
            />
          ),
        }))}
      />

      {/* ── Estados ───────────────────────────────────────────────── */}
      <DocsStates
        cols={{
          state: tContent("states.cols.state"),
          trigger: tContent("states.cols.trigger"),
          behavior: tContent("states.cols.behavior"),
        }}
        items={["atEnd", "away", "streaming", "toolPending", "toolFailed", "error"].map((k) => ({
          label: tContent(`states.${k}.label`),
          trigger: toPlainText(tContent(`states.${k}.trigger`)),
          behavior: toPlainText(tContent(`states.${k}.behavior`)),
        }))}
      />

      {/* ── Propriedades ──────────────────────────────────────────── */}
      <DocsProps
        tables={[
          {
            title: "ChatThread",
            cols: {
              prop: tContent("props.table.prop"),
              type: tContent("props.table.type"),
              default: tContent("props.table.default"),
              required: tContent("props.table.required"),
              description: tContent("props.table.description"),
            },
            items: [
              "messages", "labels", "id", "role", "streaming",
              "toolCalls", "sources", "actions", "error", "regionLabel", "class",
            ].map((k) => ({
              name: tContent(`props.table.${k}.name`),
              type: tContent(`props.table.${k}.type`),
              defaultValue: tContent(`props.table.${k}.default`),
              required: tContent(`props.table.${k}.required`),
              description: toPlainText(tContent(`props.table.${k}.description`)),
            })),
          },
        ]}
        interfaceCode={INTERFACE_CODE}
        extensibilityTitle={tContent("props.extensibilityTitle")}
        extensibilityNotes={tContent("props.extensibility")}
        extensibilityCode={tContent("props.extensibilityCode")}
      />

      {/* ── Tokens ────────────────────────────────────────────────── */}
      <DocsTokens
        cols={{
          token: tContent("tokens.table.token"),
          value: tContent("tokens.table.value"),
          description: tContent("tokens.table.description"),
        }}
        items={["bubble", "header", "body", "disclosure", "failed", "ring"].map((k) => ({
          token: tContent(`tokens.table.${k}.token`),
          value: tContent(`tokens.table.${k}.value`),
          description: toPlainText(tContent(`tokens.table.${k}.description`)),
        }))}
        customizationTitle={tContent("tokens.customizationTitle")}
        customizationCode={tContent("tokens.customizationCode")}
        language="css"
      />

      {/* ── Acessibilidade ────────────────────────────────────────── */}
      <DocsAccessibility
        summary={tContent("accessibility.summary")}
        items={[1, 2, 3, 4, 5].map((i) => tContent(`accessibility.items.item${i}`))}
        keyboardTitle={tContent("accessibility.keyboard.title")}
        keyboardItems={[
          { key: "Tab",   description: tContent("accessibility.keyboard.tab") },
          { key: "Enter", description: tContent("accessibility.keyboard.enter") },
          { key: "↑ ↓",   description: tContent("accessibility.keyboard.arrows") },
        ]}
        screenReaderTitle={tContent("accessibility.screenReader.title")}
        screenReaderItems={screenReaderItems}
      />

      {/* ── Relacionados ──────────────────────────────────────────── */}
      <DocsRelated
        items={[
          { name: tContent("related.items.markdown.name"), description: toPlainText(tContent("related.items.markdown.description")), path: "?path=/docs/components-conversational-markdown--docs" },
          { name: tContent("related.items.avatar.name"),   description: toPlainText(tContent("related.items.avatar.description")),   path: "?path=/docs/components-display-avatar--docs" },
          { name: tContent("related.items.button.name"),   description: toPlainText(tContent("related.items.button.description")),   path: "?path=/docs/components-form-button--docs" },
          { name: tContent("related.items.skeleton.name"), description: toPlainText(tContent("related.items.skeleton.description")), path: "?path=/docs/components-feedback-skeleton--docs" },
        ]}
      />

      {/* ── Notas ─────────────────────────────────────────────────── */}
      <DocsNotes
        componentSlug="chat-thread"
        items={[1, 2, 3, 4, 5].map((i) => ({ title: "", content: tContent(`notes.item${i}`) }))}
      />

      {/* ── Analytics ─────────────────────────────────────────────── */}
      <DocsAnalytics
        cols={{
          event: tContent("analytics.table.event"),
          trigger: tContent("analytics.table.trigger"),
          payload: tContent("analytics.table.payload"),
        }}
        items={["pageView", "sectionViewed", "demoClick"].map((k) => ({
          event: tContent(`analytics.table.${k}`),
          trigger: toPlainText(tContent(`analytics.table.${k}Trigger`)),
          payload: tContent(`analytics.table.${k}Payload`),
        }))}
      />

      {/* ── Testes ────────────────────────────────────────────────── */}
      <DocsTestes
        functional={{
          title: tContent("testes.functional.title"),
          description: tContent("testes.functional.description"),
          cols: {
            action: tNav("common.userAction"),
            result: tNav("common.expectedResult"),
            priority: tNav("common.priority"),
          },
          items: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((i) => ({
            action: toPlainText(tContent(`testes.functional.item${i}.action`)),
            result: toPlainText(tContent(`testes.functional.item${i}.result`)),
            priority: priorityLabel(tContent(`testes.functional.item${i}.priority`)),
          })),
        }}
        accessibility={{
          title: tContent("testes.accessibility.title"),
          description: tContent("testes.accessibility.description"),
          cols: {
            criterion: tNav("common.criterion"),
            level: "WCAG",
            how: tNav("common.howToVerify"),
          },
          // A lista é PLANA: cada item é um critério, e o "como verificar" é o
          // próprio addon-a11y rodando em toda story.
          items: [1, 2, 3, 4, 5, 6].map((i) => ({
            criterion: toPlainText(tContent(`testes.accessibility.item${i}`)),
            level: "AA",
            how: "—",
          })),
        }}
        visual={{
          title: tContent("testes.visual.title"),
          description: tContent("testes.visual.description"),
          cols: {
            story: tNav("common.storyState"),
            priority: tNav("common.priority"),
          },
          items: [1, 2, 3, 4, 5, 6, 7].map((i) => ({
            story: toPlainText(tContent(`testes.visual.item${i}.story`)),
            priority: priorityLabel(tContent(`testes.visual.item${i}.priority`)),
          })),
        }}
      />
    </DocsPageLayout>
  );
}

// nortear-design-system-angular/src/components/docs/ChatThreadDocs.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  OnDestroy,
  signal,
  TemplateRef,
  ViewEncapsulation,
  viewChild,
} from '@angular/core';
import { applySeo } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { useTranslation, getLocale } from '@/lib/i18n';
import { createActiveSectionObserver } from '@/lib/use-active-section';
import { toPlainText } from '@/lib/strip-html';
import { NdsChatThread, type ChatMessage, type ChatThreadLabels } from '@/components/ui/chat-thread';
import { chatLabels, toMessages } from '@/components/ui/chat-thread.fixtures';
import { NdsSeparator } from '@/components/ui/separator';
import uiTranslations from '@/i18n/ui.json';
import chatTranslations from '@shared/content/chat-thread/translations.json';
import {
  CHAT_COM_FERRAMENTAS,
  CHAT_CONVERSA,
  CHAT_EM_STREAMING,
  CHAT_FERRAMENTA_FALHOU,
} from '@shared/primitives/chat-examples';

import {
  NdsDocsPageLayout,
  NdsDocsHeader,
  NdsDocsDemonstration,
  NdsDocsAnatomy,
  NdsDocsWhenToUse,
  NdsDocsDoDont,
  NdsDocsImport,
  NdsDocsVariants,
  NdsDocsStates,
  NdsDocsProps,
  NdsDocsTokens,
  NdsDocsAccessibility,
  NdsDocsRelated,
  NdsDocsNotes,
  NdsDocsAnalytics,
  NdsDocsTestes,
} from '@/components/docs/shared/sections';

const { t: tNav } = useTranslation(uiTranslations as Record<string, unknown>);

// As ações do turno e os controles de autorização são `TemplateRef` nesta
// stack, não nó de interface como no React. Divergência de API entre frameworks
// não se "alinha": cada stack usa a sua, e o conteúdo compartilhado descreve o
// CONCEITO. A linha da tabela nomeia o que se escreve AQUI, senão quem copia
// procura por um tipo que não existe.
const { t, dict } = useTranslation(chatTranslations as Record<string, unknown>, {
  '*': { 'props.table.actions.type': 'TemplateRef<unknown>' },
  'pt-BR': {
    'props.table.class.description':
      'Atributo nativo do elemento, não input: o Angular mescla com a classe base. É por aqui que a página define a altura e a medida de leitura.',
  },
  en: {
    'props.table.class.description':
      'Native element attribute, not an input: Angular merges it with the base class. This is where the page sets the height and the reading measure.',
  },
  es: {
    'props.table.class.description':
      'Atributo nativo del elemento, no input: Angular lo combina con la clase base. Aquí es donde la página define la altura y la medida de lectura.',
  },
});

const SECTION_IDS = [
  'demonstracao', 'anatomia', 'quando-usar', 'do-dont',
  'importacao', 'variantes', 'estados', 'propriedades', 'tokens',
  'acessibilidade', 'relacionados', 'notas', 'analytics', 'testes',
] as const;

const NAV_GROUPS: { labelKey: string; sections: { id: string; labelKey: string }[] }[] = [
  { labelKey: 'nav.overview', sections: [
    { id: 'demonstracao', labelKey: 'nav.demonstration' },
    { id: 'anatomia',     labelKey: 'nav.anatomy'       },
    { id: 'quando-usar',  labelKey: 'nav.usage'         },
    { id: 'do-dont',      labelKey: 'nav.doDont'        },
  ]},
  { labelKey: 'nav.techRef', sections: [
    { id: 'importacao',   labelKey: 'nav.import'   },
    { id: 'variantes',    labelKey: 'nav.variants' },
    { id: 'estados',      labelKey: 'nav.states'   },
    { id: 'propriedades', labelKey: 'nav.props'    },
    { id: 'tokens',       labelKey: 'nav.tokens'   },
  ]},
  { labelKey: 'nav.context', sections: [
    { id: 'acessibilidade', labelKey: 'nav.accessibility' },
    { id: 'relacionados',   labelKey: 'nav.related'       },
    { id: 'notas',          labelKey: 'nav.notes'         },
  ]},
  { labelKey: 'nav.quality', sections: [
    { id: 'analytics', labelKey: 'nav.analytics' },
    { id: 'testes',    labelKey: 'nav.testes'    },
  ]},
];

const INTERFACE_CODE = `// <nds-chat-thread> — componente
@Component({ selector: 'nds-chat-thread', … })
export class NdsChatThread {
  readonly messages = input.required<ChatMessage[]>();
  readonly labels = input.required<ChatThreadLabels>();
  readonly error = input<string | undefined>(undefined);
  readonly size = input<ChatThreadSize | undefined>(undefined);
}

// A LISTA é a API: quem faz streaming troca o array.
//   mensagem nova   — acrescenta ao fim, e é por ela que a rolagem decide
//   mesmo \`id\`      — onde o streaming pousa; é o \`track\` que remenda a
//                     mensagem que cresce, em vez de remontá-la
//   \`error\`         — a falha da execução, fora da conversa`;

const CODE_USER = `<nds-chat-thread
  [messages]="[{ role: 'user', content: text }]"
  [labels]="labels"
/>`;
const CODE_ASSISTANT = `<nds-chat-thread
  [messages]="[{ role: 'assistant', content: text }]"
  [labels]="labels"
/>`;
const CODE_SYSTEM = `<nds-chat-thread
  [messages]="[{ role: 'system', content: text }]"
  [labels]="labels"
/>`;

/** Os rótulos sem a palavra do estado — o contraexemplo do segundo par. */
const EMPTY_TOOL_STATE = { pending: '', running: '', done: '', failed: '' };

@Component({
  selector: 'nds-chat-thread-docs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [
    NdsChatThread, NdsSeparator,
    NdsDocsPageLayout, NdsDocsHeader, NdsDocsDemonstration, NdsDocsAnatomy,
    NdsDocsWhenToUse, NdsDocsDoDont, NdsDocsImport, NdsDocsVariants,
    NdsDocsStates, NdsDocsProps, NdsDocsTokens, NdsDocsAccessibility,
    NdsDocsRelated, NdsDocsNotes, NdsDocsAnalytics, NdsDocsTestes,
  ],
  template: `
    <!-- O par do Do & Don't é a MESMA conversa: o que muda é para onde a
         rolagem vai quando a mensagem chega. -->
    <ng-template #tplDoDont1Do>
      <nds-chat-thread [messages]="conversation" [labels]="labels()" size="sm" />
    </ng-template>
    <ng-template #tplDoDont1Dont>
      <nds-chat-thread [messages]="conversation" [labels]="labels()" size="sm" />
    </ng-template>
    <ng-template #tplDoDont2Do>
      <nds-chat-thread [messages]="toolFailed" [labels]="labels()" size="sm" />
    </ng-template>
    <ng-template #tplDoDont2Dont>
      <!-- O contraexemplo: o estado sem palavra, só o ícone colorido. -->
      <nds-chat-thread [messages]="toolFailed" [labels]="mutedToolState()" size="sm" />
    </ng-template>

    <ng-template #tplVarUser>
      <nds-chat-thread [messages]="userTurn" [labels]="labels()" size="xs" />
    </ng-template>
    <ng-template #tplVarAssistant>
      <nds-chat-thread [messages]="assistantTurn" [labels]="labels()" size="xs" />
    </ng-template>
    <ng-template #tplVarSystem>
      <nds-chat-thread [messages]="systemTurn" [labels]="labels()" size="xs" />
    </ng-template>

    <nds-docs-page-layout
      [navGroups]="navGroups()"
      [activeSection]="activeSection()"
      componentSlug="chat-thread"
    >
      <div docsHeader>
        <nds-docs-header
          [title]="t('title')"
          [description]="t('description')"
          [category]="t('category')"
          [type]="t('type')"
        />
      </div>

      <ng-container docsMain>
        <nds-docs-demonstration componentSlug="chat-thread">
          <div class="nds-stack nds-w-full" data-spacing="lg">
            <!-- A legenda diz QUAL exemplo está desenhado — sem ela, quatro
                 conversas empilhadas viram uma só, e o assunto da demonstração é
                 justamente a diferença entre elas.

                 O separador é decorativo de propósito: quem dá a estrutura para
                 quem ouve é a legenda de cada exemplo, não a linha. -->
            @for (example of examples(); track example.key) {
              @if (!$first) {
                <div ndsSeparator></div>
              }
              <div class="nds-stack nds-w-full" data-spacing="xs">
                <p class="nds-text-caption nds-text-muted-foreground">{{ example.label }}</p>
                <nds-chat-thread
                  [messages]="example.messages"
                  [labels]="labels()"
                  size="md"
                />
              </div>
            }
          </div>
        </nds-docs-demonstration>

        <nds-docs-anatomy
          [items]="anatomyItems()"
          [structureLabel]="t('anatomy.structureLabel')"
          [structureCode]="t('anatomy.structureCode')"
          language="html"
        />

        <nds-docs-when-to-use
          [guidelines]="guidelines()"
          [scenarios]="scenarios()"
          [uxWriting]="uxWriting()"
          [do]="usageDo()"
          [dont]="usageDont()"
        />

        <nds-docs-do-dont [pairs]="doDontPairs()" />

        <nds-docs-import
          [description]="t('import.basic')"
          [code]="t('import.basicCode')"
          [secondaryDescription]="t('import.withStreaming')"
          [secondaryCode]="t('import.withStreamingCode')"
          componentSlug="chat-thread"
          language="html"
        />

        <nds-docs-variants
          [note]="t('variants.note')"
          [items]="variantItems()"
          componentSlug="chat-thread"
          id="variantes"
          language="html"
        />

        <nds-docs-states
          [cols]="statesCols()"
          [items]="stateItems()"
        />

        <nds-docs-props
          [tables]="propTables()"
          [interfaceCode]="interfaceCode"
          [extensibilityTitle]="t('props.extensibilityTitle')"
          [extensibilityNotes]="t('props.extensibility')"
          [extensibilityCode]="t('props.extensibilityCode')"
        />

        <nds-docs-tokens
          [cols]="tokensCols()"
          [items]="tokenItems()"
          [customizationTitle]="t('tokens.customizationTitle')"
          [customizationCode]="t('tokens.customizationCode')"
          language="css"
        />

        <nds-docs-accessibility
          [summary]="t('accessibility.summary')"
          [items]="a11yItems()"
          [keyboardTitle]="t('accessibility.keyboard.title')"
          [keyboardItems]="keyboardItems()"
          [screenReaderTitle]="t('accessibility.screenReader.title')"
          [screenReaderItems]="screenReaderItems()"
        />

        <nds-docs-related
          [items]="relatedItems()"
          componentSlug="chat-thread"
        />

        <nds-docs-notes
          [items]="noteItems()"
          componentSlug="chat-thread"
        />

        <nds-docs-analytics
          [cols]="analyticsCols()"
          [items]="analyticsItems()"
        />

        <nds-docs-testes
          [functional]="testesFunctional()"
          [accessibility]="testesAccessibility()"
          [visual]="testesVisual()"
        />
      </ng-container>
    </nds-docs-page-layout>
  `,
})
export class NdsChatThreadDocs implements AfterViewInit, OnDestroy {
  protected readonly t = t;
  protected readonly tNav = tNav;
  protected readonly interfaceCode = INTERFACE_CODE;

  // As conversas não dependem de idioma: o que a `translations.json` carrega são
  // os RÓTULOS da interface, não a fala.
  protected readonly conversation = toMessages(CHAT_CONVERSA);
  protected readonly toolFailed = toMessages(CHAT_FERRAMENTA_FALHOU);
  protected readonly userTurn = toMessages(CHAT_CONVERSA.filter((m) => m.role === 'user'));
  protected readonly assistantTurn = toMessages(
    CHAT_CONVERSA.filter((m) => m.role === 'assistant'),
  );
  protected readonly systemTurn = toMessages(CHAT_CONVERSA.filter((m) => m.role === 'system'));

  /** Os rótulos são texto de interface, então acompanham a troca de idioma. */
  protected readonly labels = computed<ChatThreadLabels>(() => {
    dict();
    return chatLabels();
  });

  protected readonly mutedToolState = computed<ChatThreadLabels>(() => ({
    ...this.labels(),
    toolState: EMPTY_TOOL_STATE,
  }));

  protected readonly activeSection = signal<string | undefined>(undefined);
  private observer: { disconnect: () => void } | undefined;

  private readonly tplDoDont1Do = viewChild.required<TemplateRef<unknown>>('tplDoDont1Do');
  private readonly tplDoDont1Dont = viewChild.required<TemplateRef<unknown>>('tplDoDont1Dont');
  private readonly tplDoDont2Do = viewChild.required<TemplateRef<unknown>>('tplDoDont2Do');
  private readonly tplDoDont2Dont = viewChild.required<TemplateRef<unknown>>('tplDoDont2Dont');
  private readonly tplVarUser = viewChild.required<TemplateRef<unknown>>('tplVarUser');
  private readonly tplVarAssistant = viewChild.required<TemplateRef<unknown>>('tplVarAssistant');
  private readonly tplVarSystem = viewChild.required<TemplateRef<unknown>>('tplVarSystem');

  // Rótulo resolvido aqui, não concatenado no template: chave montada em runtime
  // é invisível para o auditor de i18n, que passa a acusar a chave parcial — e
  // um erro de digitação nela só apareceria na tela.
  protected readonly examples = computed<
    { key: string; label: string; messages: ChatMessage[] }[]
  >(() => {
    dict();
    const streaming = toMessages(CHAT_EM_STREAMING);
    streaming[streaming.length - 1].streaming = true;
    return [
      {
        key: 'conversation',
        label: t('demonstration.labels.conversation'),
        messages: toMessages(CHAT_CONVERSA),
      },
      {
        key: 'tools',
        label: t('demonstration.labels.tools'),
        messages: toMessages(CHAT_COM_FERRAMENTAS),
      },
      { key: 'streaming', label: t('demonstration.labels.streaming'), messages: streaming },
      {
        key: 'failed',
        label: t('demonstration.labels.failed'),
        messages: toMessages(CHAT_FERRAMENTA_FALHOU),
      },
    ];
  });

  protected readonly navGroups = computed(() => {
    dict();
    return NAV_GROUPS.map((g) => ({
      label: tNav(g.labelKey),
      sections: g.sections.map((s) => ({ id: s.id, label: tNav(s.labelKey) })),
    }));
  });

  protected readonly anatomyItems = computed(() => {
    dict();
    return [1, 2, 3, 4, 5].map((i) => t(`anatomy.item${i}`));
  });

  protected readonly guidelines = computed(() => {
    dict();
    return {
      title: t('usage.guidelines.title'),
      items: [1, 2, 3, 4, 5].map((i) => t(`usage.guidelines.item${i}`)),
    };
  });

  protected readonly scenarios = computed(() => {
    dict();
    return {
      title: t('usage.scenarios.title'),
      cols: {
        scenario: t('usage.scenarios.cols.scenario'),
        use: t('usage.scenarios.cols.use'),
        alternative: t('usage.scenarios.cols.alternative'),
      },
      items: [1, 2, 3, 4, 5].map((i) => ({
        s: t(`usage.scenarios.item${i}.s`),
        u: t(`usage.scenarios.item${i}.u`),
        a: toPlainText(t(`usage.scenarios.item${i}.a`)),
      })),
    };
  });

  protected readonly uxWriting = computed(() => {
    dict();
    return {
      title: t('usage.uxWriting.title'),
      cols: {
        element: t('usage.uxWriting.table.element'),
        rules: t('usage.uxWriting.table.rules'),
        do: t('usage.uxWriting.table.correct'),
        dont: t('usage.uxWriting.table.avoid'),
      },
      items: ['author', 'toolName', 'toolState', 'system'].map((key) => ({
        element: t(`usage.uxWriting.table.${key}.name`),
        rules: t(`usage.uxWriting.table.${key}.format`),
        do: t(`usage.uxWriting.table.${key}.good`),
        dont: t(`usage.uxWriting.table.${key}.bad`),
      })),
    };
  });

  protected readonly usageDo = computed(() => {
    dict();
    return { title: t('usage.do.title'), items: [1, 2, 3, 4].map((i) => t(`usage.do.item${i}`)) };
  });

  protected readonly usageDont = computed(() => {
    dict();
    return {
      title: t('usage.dont.title'),
      items: [1, 2, 3, 4].map((i) => t(`usage.dont.item${i}`)),
    };
  });

  protected readonly doDontPairs = computed(() => {
    dict();
    return [
      {
        doLabel: tNav('common.do'),
        dontLabel: tNav('common.dont'),
        doCaption: toPlainText(t('doDont.pair1.do')),
        dontCaption: toPlainText(t('doDont.pair1.dont')),
        doPreview: this.tplDoDont1Do(),
        dontPreview: this.tplDoDont1Dont(),
      },
      {
        doLabel: tNav('common.do'),
        dontLabel: tNav('common.dont'),
        doCaption: toPlainText(t('doDont.pair2.do')),
        dontCaption: toPlainText(t('doDont.pair2.dont')),
        doPreview: this.tplDoDont2Do(),
        dontPreview: this.tplDoDont2Dont(),
      },
    ];
  });

  protected readonly variantItems = computed(() => {
    dict();
    return [
      { key: 'user',      code: CODE_USER,      tpl: this.tplVarUser()      },
      { key: 'assistant', code: CODE_ASSISTANT, tpl: this.tplVarAssistant() },
      { key: 'system',    code: CODE_SYSTEM,    tpl: this.tplVarSystem()    },
    ].map(({ key, code, tpl }) => ({
      name: key,
      description: t(`variants.items.${key}.description`),
      code,
      trackId: key,
      preview: tpl,
    }));
  });

  protected readonly statesCols = computed(() => {
    dict();
    return {
      state: t('states.cols.state'),
      trigger: t('states.cols.trigger'),
      behavior: t('states.cols.behavior'),
    };
  });

  protected readonly stateItems = computed(() => {
    dict();
    // Os estados deste componente são NOMEADOS, não numerados: o que os
    // distingue é o assunto, e `item3` não diria qual é.
    return ['atEnd', 'away', 'streaming', 'toolPending', 'toolFailed', 'error'].map((k) => ({
      label: t(`states.${k}.label`),
      trigger: toPlainText(t(`states.${k}.trigger`)),
      behavior: toPlainText(t(`states.${k}.behavior`)),
    }));
  });

  protected readonly propTables = computed(() => {
    dict();
    const cols = {
      prop: t('props.table.prop'),
      type: t('props.table.type'),
      default: t('props.table.default'),
      required: t('props.table.required'),
      description: t('props.table.description'),
    };
    return [
      {
        title: 'NdsChatThread',
        cols,
        items: [
          'messages', 'labels', 'id', 'role', 'streaming',
          'toolCalls', 'sources', 'actions', 'error', 'regionLabel', 'class',
        ].map((k) => ({
          name: t(`props.table.${k}.name`),
          type: t(`props.table.${k}.type`),
          defaultValue: t(`props.table.${k}.default`),
          required: t(`props.table.${k}.required`),
          description: toPlainText(t(`props.table.${k}.description`)),
        })),
      },
    ];
  });

  protected readonly tokensCols = computed(() => {
    dict();
    return {
      token: t('tokens.table.token'),
      value: t('tokens.table.value'),
      description: t('tokens.table.description'),
    };
  });

  protected readonly tokenItems = computed(() => {
    dict();
    return ['bubble', 'header', 'body', 'disclosure', 'failed', 'ring'].map((k) => ({
      token: t(`tokens.table.${k}.token`),
      value: t(`tokens.table.${k}.value`),
      description: toPlainText(t(`tokens.table.${k}.description`)),
    }));
  });

  protected readonly a11yItems = computed(() => {
    dict();
    return [1, 2, 3, 4, 5].map((i) => t(`accessibility.items.item${i}`));
  });

  protected readonly keyboardItems = computed(() => {
    dict();
    return [
      { key: 'Tab',   description: toPlainText(t('accessibility.keyboard.tab')) },
      { key: 'Enter', description: toPlainText(t('accessibility.keyboard.enter')) },
      { key: '↑ ↓',   description: toPlainText(t('accessibility.keyboard.arrows')) },
    ];
  });

  protected readonly screenReaderItems = computed(() => {
    dict();
    return ['turns', 'answer', 'tool', 'jump'].map((k) =>
      t(`accessibility.screenReader.${k}`),
    );
  });

  protected readonly relatedItems = computed(() => {
    dict();
    return [
      { key: 'markdown', path: '?path=/docs/components-conversational-markdown--docs' },
      { key: 'avatar',   path: '?path=/docs/components-display-avatar--docs'   },
      { key: 'button',   path: '?path=/docs/components-form-button--docs'   },
      { key: 'skeleton', path: '?path=/docs/components-feedback-skeleton--docs' },
    ].map(({ key, path }) => ({
      name: t(`related.items.${key}.name`),
      description: toPlainText(t(`related.items.${key}.description`)),
      path,
    }));
  });

  protected readonly noteItems = computed(() => {
    dict();
    return [1, 2, 3, 4, 5].map((i) => ({ title: '', content: t(`notes.item${i}`) }));
  });

  protected readonly analyticsCols = computed(() => {
    dict();
    return {
      event: t('analytics.table.event'),
      trigger: t('analytics.table.trigger'),
      payload: t('analytics.table.payload'),
    };
  });

  protected readonly analyticsItems = computed(() => {
    dict();
    return ['pageView', 'sectionViewed', 'demoClick'].map((k) => ({
      event: t(`analytics.table.${k}`),
      trigger: toPlainText(t(`analytics.table.${k}Trigger`)),
      payload: t(`analytics.table.${k}Payload`),
    }));
  });

  protected readonly testesFunctional = computed(() => {
    dict();
    return {
      title: t('testes.functional.title'),
      description: t('testes.functional.description'),
      cols: {
        action: tNav('common.userAction'),
        result: tNav('common.expectedResult'),
        priority: tNav('common.priority'),
      },
      items: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((i) => ({
        action: toPlainText(t(`testes.functional.item${i}.action`)),
        result: toPlainText(t(`testes.functional.item${i}.result`)),
        priority: priorityLabel(t(`testes.functional.item${i}.priority`)),
      })),
    };
  });

  protected readonly testesAccessibility = computed(() => {
    dict();
    // A lista é PLANA: cada item é um critério, e o "como verificar" é o próprio
    // addon-a11y rodando em toda story.
    return {
      title: t('testes.accessibility.title'),
      description: t('testes.accessibility.description'),
      cols: {
        criterion: tNav('common.criterion'),
        level: 'WCAG',
        how: tNav('common.howToVerify'),
      },
      items: [1, 2, 3, 4, 5, 6].map((i) => ({
        criterion: toPlainText(t(`testes.accessibility.item${i}`)),
        level: 'AA',
        how: '—',
      })),
    };
  });

  protected readonly testesVisual = computed(() => {
    dict();
    return {
      title: t('testes.visual.title'),
      description: t('testes.visual.description'),
      cols: {
        story: tNav('common.storyState'),
        priority: tNav('common.priority'),
      },
      items: [1, 2, 3, 4, 5, 6, 7].map((i) => ({
        story: toPlainText(t(`testes.visual.item${i}.story`)),
        priority: priorityLabel(t(`testes.visual.item${i}.priority`)),
      })),
    };
  });

  constructor() {
    effect((onCleanup) => {
      dict();
      const locale = getLocale();
      const cleanup = applySeo({
        title: t('seo.title'),
        description: t('seo.description'),
        locale,
        componentSlug: 'chat-thread',
      });
      track('docs_page_view', {
        component_name: 'chat-thread',
        locale,
        page_title: `${t('title')} · Design System`,
      });
      onCleanup(cleanup);
    });
  }

  ngAfterViewInit(): void {
    this.observer = createActiveSectionObserver(
      [...SECTION_IDS],
      (id) => document.getElementById(id),
      (id) => this.activeSection.set(id),
      (id) =>
        track('docs_section_viewed', {
          component_name: 'chat-thread',
          section_id: id,
          locale: getLocale(),
        }),
    );
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }
}

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function priorityLabel(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}
