// design-system-vue/src/components/docs/CheckboxDocs.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, watch, ref } from 'vue';
import { useTranslation } from '@/lib/i18n';
import { useSeoEffect } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { Checkbox } from '@/components/ui/checkbox';

import DocsPageLayout    from '@/components/docs/shared/sections/DocsPageLayout.vue';
import DocsHeader        from '@/components/docs/shared/sections/DocsHeader.vue';
import DocsDemonstration from '@/components/docs/shared/sections/DocsDemonstration.vue';
import DocsAnatomy       from '@/components/docs/shared/sections/DocsAnatomy.vue';
import DocsWhenToUse     from '@/components/docs/shared/sections/DocsWhenToUse.vue';
import DocsDoDont        from '@/components/docs/shared/sections/DocsDoDont.vue';
import DocsImport        from '@/components/docs/shared/sections/DocsImport.vue';
import DocsVariants      from '@/components/docs/shared/sections/DocsVariants.vue';
import DocsStates        from '@/components/docs/shared/sections/DocsStates.vue';
import DocsProps         from '@/components/docs/shared/sections/DocsProps.vue';
import DocsTokens        from '@/components/docs/shared/sections/DocsTokens.vue';
import DocsAccessibility from '@/components/docs/shared/sections/DocsAccessibility.vue';
import DocsRelated       from '@/components/docs/shared/sections/DocsRelated.vue';
import DocsNotes         from '@/components/docs/shared/sections/DocsNotes.vue';
import DocsAnalytics     from '@/components/docs/shared/sections/DocsAnalytics.vue';
import DocsTestes        from '@/components/docs/shared/sections/DocsTestes.vue';

import uiTranslations       from '@/i18n/ui.json';
import checkboxTranslations from '@shared/content/checkbox/translations.json';

// ─── i18n ─────────────────────────────────────────────────────────────────────
// IMPORTANT: locale comes from useTranslation — NEVER from useLocaleStore/Pinia
const { t: tNav } = useTranslation(uiTranslations);
const { t: tContent, locale } = useTranslation(checkboxTranslations);

// ─── Helpers ──────────────────────────────────────────────────────────────────

function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, '');
}

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function localPriority(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

// ─── SEO & GEO ────────────────────────────────────────────────────────────────

useSeoEffect(computed(() => ({
  title: tContent('seo.title'),
  description: tContent('seo.description'),
  locale: locale.value as 'pt-BR' | 'en' | 'es',
  componentSlug: 'checkbox',
})));

// ─── Analytics — page view ────────────────────────────────────────────────────

watch(locale, (newLocale) => {
  track('docs_page_view', {
    component_name: 'checkbox',
    locale: newLocale,
    page_title: `${tContent('title')} · Design System`,
  });
}, { immediate: true });

// ─── Analytics — section view ─────────────────────────────────────────────────

const activeSection = ref('demonstracao');

function handleSectionChange(id: string) {
  activeSection.value = id;
  track('docs_section_viewed', {
    section_id: id,
    component_name: 'checkbox',
    locale: locale.value,
  });
}

// ─── Navigation groups ────────────────────────────────────────────────────────

const navGroups = computed(() => [
  {
    label: tNav('nav.overview'),
    sections: [
      { id: 'demonstracao', label: tNav('nav.demonstration') },
      { id: 'anatomia',     label: tNav('nav.anatomy')      },
      { id: 'quando-usar',  label: tNav('nav.usage')        },
      { id: 'do-dont',      label: tNav('nav.doDont')       },
    ],
  },
  {
    label: tNav('nav.techRef'),
    sections: [
      { id: 'importacao',   label: tNav('nav.import')    },
      { id: 'variantes',    label: tNav('nav.variants')  },
      { id: 'estados',      label: tNav('nav.states')    },
      { id: 'propriedades', label: tNav('nav.props')     },
      { id: 'tokens',       label: tNav('nav.tokens')    },
    ],
  },
  {
    label: tNav('nav.context'),
    sections: [
      { id: 'acessibilidade', label: tNav('nav.accessibility') },
      { id: 'relacionados',   label: tNav('nav.related')       },
      { id: 'notas',          label: tNav('nav.notes')         },
    ],
  },
  {
    label: tNav('nav.quality'),
    sections: [
      { id: 'analytics', label: tNav('nav.analytics') },
      { id: 'testes',    label: tNav('nav.testes')    },
    ],
  },
]);

const allSectionIds = computed(() => navGroups.value.flatMap(g => g.sections.map(s => s.id)));

// ─── IntersectionObserver ─────────────────────────────────────────────────────

let observer: IntersectionObserver | null = null;

onMounted(() => {
  observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) { handleSectionChange(entry.target.id); break; }
      }
    },
    { rootMargin: '-20% 0px -70% 0px', threshold: 0 }
  );
  allSectionIds.value.forEach((id) => {
    const el = document.getElementById(id);
    if (el && observer) observer.observe(el);
  });
});

onUnmounted(() => {
  observer?.disconnect();
  observer = null;
});

// ─── Code strings ─────────────────────────────────────────────────────────────

const codeImportBasic = `import { Checkbox } from "@/components/ui/checkbox";`;
const codeImportWithLabel = `import { Checkbox } from "@/components/ui/checkbox";
// Label é um elemento HTML nativo ou componente Label de @/components/ui/label`;

const codeDefault = `<div class="flex items-center gap-2">
  <Checkbox id="terms" />
  <label for="terms" class="text-sm font-medium leading-none">
    Aceito os termos e condições
  </label>
</div>`;

const codeChecked = `<div class="flex items-center gap-2">
  <Checkbox id="terms" :checked="true" />
  <label for="terms" class="text-sm font-medium leading-none">
    Aceito os termos e condições
  </label>
</div>`;

const codeWithLabel = `<div class="flex items-center gap-2">
  <Checkbox id="newsletter" />
  <label
    for="newsletter"
    class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
  >
    Receber novidades por email
  </label>
</div>`;

const codeWithDescription = `<div class="flex items-start gap-2">
  <Checkbox id="newsletter" class="mt-0.5" aria-describedby="newsletter-desc" />
  <div class="space-y-1">
    <label for="newsletter" class="text-sm font-medium leading-none">
      Receber novidades por email
    </label>
    <p id="newsletter-desc" class="text-sm text-muted-foreground">
      Enviaremos atualizações mensais sobre o produto.
    </p>
  </div>
</div>`;

const codeCustomizationTokens = `/* Em globals.css — sobrescrever tokens de cor */
:root {
  --primary: 221 83% 53%;
  --primary-foreground: 0 0% 100%;
  --input: 214.3 31.8% 91.4%;
  --ring: 221 83% 53%;
}

.dark {
  --primary: 217 91% 60%;
  --input: 217.2 32.6% 17.5%;
}`;

const interfaceCode = `interface CheckboxProps {
  checked?: boolean | 'indeterminate';
  defaultChecked?: boolean;
  disabled?: boolean;
  required?: boolean;
  name?: string;
  value?: string;
  class?: string;
  // Emits
  'onUpdate:checked'?: (value: boolean | 'indeterminate') => void;
}`;

// ─── Computed data ────────────────────────────────────────────────────────────

const anatomyItems = computed(() => [
  tContent('anatomy.item1'),
  tContent('anatomy.item2'),
  tContent('anatomy.item3'),
  tContent('anatomy.item4'),
]);

const variantItems = computed(() => [
  { name: 'default',         description: stripHtml(tContent('variants.items.default')),         code: codeDefault         },
  { name: 'checked',         description: stripHtml(tContent('variants.items.checked')),         code: codeChecked         },
  { name: 'withLabel',       description: stripHtml(tContent('variants.items.withLabel')),       code: codeWithLabel       },
  { name: 'withDescription', description: stripHtml(tContent('variants.items.withDescription')), code: codeWithDescription },
]);

const stateItems = computed(() => [
  { label: tContent('states.unchecked.label'),     trigger: tContent('states.unchecked.trigger'),     behavior: tContent('states.unchecked.behavior')     },
  { label: tContent('states.checked.label'),       trigger: tContent('states.checked.trigger'),       behavior: tContent('states.checked.behavior')       },
  { label: tContent('states.disabled.label'),      trigger: tContent('states.disabled.trigger'),      behavior: tContent('states.disabled.behavior')      },
  { label: tContent('states.error.label'),         trigger: tContent('states.error.trigger'),         behavior: tContent('states.error.behavior')         },
  { label: tContent('states.indeterminate.label'), trigger: tContent('states.indeterminate.trigger'), behavior: tContent('states.indeterminate.behavior') },
]);

const propCols = computed(() => ({
  prop: tContent('props.table.prop'),
  type: tContent('props.table.type'),
  default: tContent('props.table.default'),
  required: tContent('props.table.required'),
  description: tContent('props.table.description'),
}));

const checkboxPropItems = computed(() => [
  { name: 'checked',             type: 'boolean | "indeterminate"',    defaultValue: '—',         required: 'Não', description: stripHtml(tContent('props.items.checked'))            },
  { name: 'defaultChecked',      type: 'boolean',                      defaultValue: '—',         required: 'Não', description: stripHtml(tContent('props.items.defaultChecked'))     },
  { name: '@update:checked',     type: '(value: boolean | "indeterminate") => void', defaultValue: '—', required: 'Não', description: stripHtml(tContent('props.items.onCheckedChange')) },
  { name: 'disabled',            type: 'boolean',                      defaultValue: 'false',     required: 'Não', description: stripHtml(tContent('props.items.disabled'))           },
  { name: 'required',            type: 'boolean',                      defaultValue: 'false',     required: 'Não', description: stripHtml(tContent('props.items.required'))           },
  { name: 'name',                type: 'string',                       defaultValue: '—',         required: 'Não', description: stripHtml(tContent('props.items.name'))               },
  { name: 'value',               type: 'string',                       defaultValue: '"on"',      required: 'Não', description: stripHtml(tContent('props.items.value'))              },
  { name: 'class',               type: 'string',                       defaultValue: '—',         required: 'Não', description: stripHtml(tContent('props.items.className'))          },
]);

const tokenRows = computed(() => [
  { token: '--primary',            value: 'bg-primary',                 description: tContent('tokens.table.primary')            },
  { token: '--primary-foreground', value: 'text-primary-foreground',    description: tContent('tokens.table.primaryForeground')  },
  { token: '--input',              value: 'border-input',               description: tContent('tokens.table.input')              },
  { token: '--ring',               value: 'focus-visible:ring-ring/50', description: tContent('tokens.table.ring')               },
  { token: '--destructive',        value: 'aria-invalid:border-destructive', description: tContent('tokens.table.destructive')   },
  { token: '--border',             value: 'border',                     description: tContent('tokens.table.border')             },
]);

const accessibilityItems = computed(() => [
  tContent('accessibility.item1'),
  tContent('accessibility.item2'),
  tContent('accessibility.item3'),
  tContent('accessibility.item4'),
  tContent('accessibility.item5'),
]);

const keyboardItems = computed(() => [
  { key: 'Tab',       description: tContent('accessibility.keyboard.tab')      },
  { key: 'Space',     description: tContent('accessibility.keyboard.space')    },
  { key: 'Shift+Tab', description: tContent('accessibility.keyboard.shiftTab') },
]);

const relatedItems = computed(() => [
  { name: 'Switch',     description: tContent('related.switch'),     path: '?path=/docs/ui-switch--docs'      },
  { name: 'RadioGroup', description: tContent('related.radioGroup'), path: '?path=/docs/ui-radiogroup--docs'  },
  { name: 'Form',       description: tContent('related.form'),       path: '?path=/docs/ui-form--docs'        },
  { name: 'Select',     description: tContent('related.select'),     path: '?path=/docs/ui-select--docs'      },
]);

const noteItems = computed(() => [
  { title: '', content: tContent('notes.tip1') },
  { title: '', content: tContent('notes.tip2') },
  { title: '', content: tContent('notes.tip3') },
  { title: '', content: tContent('notes.tip4') },
]);

const analyticsItems = computed(() => [
  { event: tContent('analytics.table.fieldChange'),    trigger: tContent('analytics.table.fieldChangeTrigger'),    payload: tContent('analytics.table.fieldChangePayload')    },
  { event: tContent('analytics.table.pageView'),       trigger: tContent('analytics.table.pageViewTrigger'),       payload: tContent('analytics.table.pageViewPayload')       },
  { event: tContent('analytics.table.sectionViewed'),  trigger: tContent('analytics.table.sectionViewedTrigger'),  payload: tContent('analytics.table.sectionViewedPayload')  },
  { event: tContent('analytics.table.langSwitch'),     trigger: tContent('analytics.table.langSwitchTrigger'),     payload: tContent('analytics.table.langSwitchPayload')     },
]);

const a11yCritCols = computed(() => ({
  criterion: tNav('common.criterion'),
  level: 'WCAG',
  how: tNav('common.howToVerify'),
}));

const functionalTestItems = computed(() => [
  { action: tContent('testes.functional.item1.action'), result: tContent('testes.functional.item1.result'), priority: localPriority(tContent('testes.functional.item1.priority')) },
  { action: tContent('testes.functional.item2.action'), result: tContent('testes.functional.item2.result'), priority: localPriority(tContent('testes.functional.item2.priority')) },
  { action: tContent('testes.functional.item3.action'), result: tContent('testes.functional.item3.result'), priority: localPriority(tContent('testes.functional.item3.priority')) },
  { action: tContent('testes.functional.item4.action'), result: tContent('testes.functional.item4.result'), priority: localPriority(tContent('testes.functional.item4.priority')) },
  { action: tContent('testes.functional.item5.action'), result: tContent('testes.functional.item5.result'), priority: localPriority(tContent('testes.functional.item5.priority')) },
  { action: tContent('testes.functional.item6.action'), result: tContent('testes.functional.item6.result'), priority: localPriority(tContent('testes.functional.item6.priority')) },
]);

const a11yTestItems = computed(() => [
  { criterion: tContent('testes.accessibility.item1.criterion'), level: tContent('testes.accessibility.item1.level'), how: tContent('testes.accessibility.item1.how') },
  { criterion: tContent('testes.accessibility.item2.criterion'), level: tContent('testes.accessibility.item2.level'), how: tContent('testes.accessibility.item2.how') },
  { criterion: tContent('testes.accessibility.item3.criterion'), level: tContent('testes.accessibility.item3.level'), how: tContent('testes.accessibility.item3.how') },
  { criterion: tContent('testes.accessibility.item4.criterion'), level: tContent('testes.accessibility.item4.level'), how: tContent('testes.accessibility.item4.how') },
  { criterion: tContent('testes.accessibility.item5.criterion'), level: tContent('testes.accessibility.item5.level'), how: tContent('testes.accessibility.item5.how') },
]);

const visualTestItems = computed(() => [
  { story: tContent('testes.visual.item1.story'), priority: localPriority(tContent('testes.visual.item1.priority')) },
  { story: tContent('testes.visual.item2.story'), priority: localPriority(tContent('testes.visual.item2.priority')) },
  { story: tContent('testes.visual.item3.story'), priority: localPriority(tContent('testes.visual.item3.priority')) },
  { story: tContent('testes.visual.item4.story'), priority: localPriority(tContent('testes.visual.item4.priority')) },
  { story: tContent('testes.visual.item5.story'), priority: localPriority(tContent('testes.visual.item5.priority')) },
]);
</script>

<template>
  <DocsPageLayout :nav-groups="navGroups" :active-section="activeSection" component-slug="checkbox">
    <template #header>
      <DocsHeader
        :title="tContent('title')"
        :description="tContent('description')"
        :category="tContent('category')"
        :type="tContent('type')"
        install-note="npx shadcn-vue@latest add checkbox"
      />
    </template>

    <!-- ── Demonstração ─────────────────────────────────────────────── -->
    <DocsDemonstration :title="tContent('demonstration.title')">
      <div class="flex flex-wrap gap-6">
        <div class="flex items-center gap-2">
          <Checkbox id="demo-terms" />
          <label for="demo-terms" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            {{ tContent('demonstration.labels.acceptTerms') }}
          </label>
        </div>
        <div class="flex items-center gap-2">
          <Checkbox id="demo-newsletter" :checked="true" />
          <label for="demo-newsletter" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            {{ tContent('demonstration.labels.newsletter') }}
          </label>
        </div>
        <div class="flex items-center gap-2">
          <Checkbox id="demo-session" :disabled="true" />
          <label for="demo-session" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            {{ tContent('demonstration.labels.rememberMe') }}
          </label>
        </div>
        <div class="flex items-start gap-2">
          <Checkbox id="demo-notif" class="mt-0.5" />
          <div class="space-y-1">
            <label for="demo-notif" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              {{ tContent('demonstration.labels.notifications') }}
            </label>
            <p class="text-xs text-muted-foreground">
              Enviaremos atualizações mensais.
            </p>
          </div>
        </div>
      </div>
    </DocsDemonstration>

    <!-- ── Anatomia ─────────────────────────────────────────────────── -->
    <DocsAnatomy
      :title="tContent('anatomy.title')"
      :items="anatomyItems"
      :structure-label="tContent('anatomy.structureLabel')"
      :structure-code="tContent('anatomy.structureCode')"
    />

    <!-- ── Quando Usar ──────────────────────────────────────────────── -->
    <DocsWhenToUse
      :title="tContent('usage.title')"
      :guidelines="{
        title: tContent('usage.guidelines.title'),
        items: [
          tContent('usage.guidelines.item1'),
          tContent('usage.guidelines.item2'),
          tContent('usage.guidelines.item3'),
          tContent('usage.guidelines.item4'),
        ],
      }"
      :scenarios="{
        title: tContent('usage.scenarios.title'),
        cols: {
          scenario: tContent('usage.scenarios.cols.scenario'),
          use: tContent('usage.scenarios.cols.use'),
          alternative: tContent('usage.scenarios.cols.alternative'),
        },
        items: [
          { s: tContent('usage.scenarios.item1.s'), u: tContent('usage.scenarios.item1.u'), a: tContent('usage.scenarios.item1.a') },
          { s: tContent('usage.scenarios.item2.s'), u: tContent('usage.scenarios.item2.u'), a: tContent('usage.scenarios.item2.a') },
          { s: tContent('usage.scenarios.item3.s'), u: tContent('usage.scenarios.item3.u'), a: tContent('usage.scenarios.item3.a') },
          { s: tContent('usage.scenarios.item4.s'), u: tContent('usage.scenarios.item4.u'), a: tContent('usage.scenarios.item4.a') },
          { s: tContent('usage.scenarios.item5.s'), u: tContent('usage.scenarios.item5.u'), a: tContent('usage.scenarios.item5.a') },
        ],
      }"
      :do="{
        title: tContent('usage.do.title'),
        items: [
          tContent('usage.do.item1'),
          tContent('usage.do.item2'),
          tContent('usage.do.item3'),
          tContent('usage.do.item4'),
        ],
      }"
      :dont="{
        title: tContent('usage.dont.title'),
        items: [
          tContent('usage.dont.item1'),
          tContent('usage.dont.item2'),
          tContent('usage.dont.item3'),
          tContent('usage.dont.item4'),
        ],
      }"
    />

    <!-- ── Do & Don't ───────────────────────────────────────────────── -->
    <DocsDoDont
      :title="tContent('doDont.title')"
      :pairs="[
        {
          doLabel: tNav('common.do'),
          dontLabel: tNav('common.dont'),
          doCaption: tContent('doDont.pair1.do'),
          dontCaption: tContent('doDont.pair1.dont'),
        },
        {
          doLabel: tNav('common.do'),
          dontLabel: tNav('common.dont'),
          doCaption: tContent('doDont.pair2.do'),
          dontCaption: tContent('doDont.pair2.dont'),
        },
      ]"
    >
      <!-- Pair 1: label semântica vs label genérica -->
      <template #do-preview-0>
        <div class="flex items-center gap-2">
          <Checkbox id="dodont-do-1" />
          <label for="dodont-do-1" class="text-sm font-medium leading-none">
            Receber notificações por email
          </label>
        </div>
      </template>
      <template #dont-preview-0>
        <div class="flex items-center gap-2">
          <Checkbox id="dodont-dont-1" />
          <label for="dodont-dont-1" class="text-sm font-medium leading-none">
            Email
          </label>
        </div>
      </template>

      <!-- Pair 2: fieldset vs checkboxes soltos -->
      <template #do-preview-1>
        <fieldset class="space-y-2 border rounded-md p-3 w-full">
          <legend class="text-xs font-semibold px-1">Notificações</legend>
          <div class="flex items-center gap-2">
            <Checkbox id="dodont-do-2a" />
            <label for="dodont-do-2a" class="text-sm font-medium leading-none">Email</label>
          </div>
          <div class="flex items-center gap-2">
            <Checkbox id="dodont-do-2b" />
            <label for="dodont-do-2b" class="text-sm font-medium leading-none">Push</label>
          </div>
        </fieldset>
      </template>
      <template #dont-preview-1>
        <div class="space-y-2">
          <div class="flex items-center gap-2">
            <Checkbox id="dodont-dont-2a" />
            <label for="dodont-dont-2a" class="text-sm font-medium leading-none">Email</label>
          </div>
          <div class="flex items-center gap-2">
            <Checkbox id="dodont-dont-2b" />
            <label for="dodont-dont-2b" class="text-sm font-medium leading-none">Push</label>
          </div>
        </div>
      </template>
    </DocsDoDont>

    <!-- ── Importação ───────────────────────────────────────────────── -->
    <DocsImport
      :title="tContent('import.title')"
      :description="tContent('import.vue')"
      :code="codeImportBasic"
      :secondary-description="tContent('import.svelte')"
      :secondary-code="`import { Checkbox } from '@/components/ui/checkbox';`"
    />

    <!-- ── Variantes ────────────────────────────────────────────────── -->
    <DocsVariants :title="tContent('variants.title')" :items="variantItems" component-slug="checkbox">
      <!-- default: unchecked -->
      <template #variant-preview-0>
        <div class="flex items-center gap-2">
          <Checkbox id="variant-default" />
          <label for="variant-default" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            Aceito os termos e condições
          </label>
        </div>
      </template>

      <!-- checked -->
      <template #variant-preview-1>
        <div class="flex items-center gap-2">
          <Checkbox id="variant-checked" :checked="true" />
          <label for="variant-checked" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            Aceito os termos e condições
          </label>
        </div>
      </template>

      <!-- withLabel -->
      <template #variant-preview-2>
        <div class="flex items-center gap-2">
          <Checkbox id="variant-with-label" />
          <label for="variant-with-label" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
            Receber novidades por email
          </label>
        </div>
      </template>

      <!-- withDescription -->
      <template #variant-preview-3>
        <div class="flex items-start gap-2">
          <Checkbox id="variant-with-desc" class="mt-0.5" />
          <div class="space-y-1">
            <label for="variant-with-desc" class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
              Receber novidades por email
            </label>
            <p class="text-sm text-muted-foreground">
              Enviaremos atualizações mensais sobre o produto.
            </p>
          </div>
        </div>
      </template>
    </DocsVariants>

    <!-- ── Estados ──────────────────────────────────────────────────── -->
    <DocsStates
      :title="tContent('states.title')"
      :cols="{
        state: tContent('states.cols.state'),
        trigger: tContent('states.cols.trigger'),
        behavior: tContent('states.cols.behavior'),
      }"
      :items="stateItems"
    />

    <!-- ── Propriedades ─────────────────────────────────────────────── -->
    <DocsProps
      :title="tContent('props.title')"
      :tables="[
        {
          title: tContent('props.vueTitle'),
          cols: propCols,
          items: checkboxPropItems,
        },
      ]"
      :interface-code="interfaceCode"
    />

    <!-- ── Tokens ────────────────────────────────────────────────────── -->
    <DocsTokens
      :title="tContent('tokens.title')"
      :cols="{
        token: tContent('tokens.table.token'),
        value: tContent('tokens.table.class'),
        description: tContent('tokens.table.part'),
      }"
      :items="tokenRows"
      :customization-title="tContent('tokens.customizationTitle')"
      :customization-code="codeCustomizationTokens"
    />

    <!-- ── Acessibilidade ───────────────────────────────────────────── -->
    <DocsAccessibility
      :title="tContent('accessibility.title')"
      :summary="tContent('accessibility.summary')"
      :items="accessibilityItems"
      :keyboard-items="keyboardItems"
    />

    <!-- ── Relacionados ─────────────────────────────────────────────── -->
    <DocsRelated :title="tContent('related.title')" :items="relatedItems" />

    <!-- ── Notas ────────────────────────────────────────────────────── -->
    <DocsNotes :title="tContent('notes.title')" :items="noteItems" />

    <!-- ── Analytics ────────────────────────────────────────────────── -->
    <DocsAnalytics
      :title="tContent('analytics.title')"
      :cols="{
        event: tContent('analytics.table.event'),
        trigger: tContent('analytics.table.trigger'),
        payload: tContent('analytics.table.payload'),
      }"
      :items="analyticsItems"
    />

    <!-- ── Testes ────────────────────────────────────────────────────── -->
    <DocsTestes
      :title="tContent('testes.title')"
      :functional="{
        title: tContent('testes.functional.title'),
        cols: {
          action: tNav('common.userAction'),
          result: tNav('common.expectedResult'),
          priority: tNav('common.priority'),
        },
        items: functionalTestItems,
      }"
      :accessibility="{
        title: tContent('testes.accessibility.title'),
        cols: a11yCritCols,
        items: a11yTestItems,
      }"
      :visual="{
        title: tContent('testes.visual.title'),
        cols: {
          story: tNav('common.storyState'),
          priority: tNav('common.priority'),
        },
        items: visualTestItems,
      }"
    />
  </DocsPageLayout>
</template>

// nortear-design-system-angular/src/components/docs/CheckboxDocs.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  OnDestroy,
  viewChild,
  TemplateRef,
  signal,
  ViewEncapsulation,
} from '@angular/core';
import { applySeo } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { useTranslation, getLocale } from '@/lib/i18n';
import { createActiveSectionObserver } from '@/lib/use-active-section';
import { stripHtml, toPlainText } from '@/lib/strip-html';
import { NdsCheckbox } from '@/components/ui/checkbox';
import { NdsLabel } from '@/components/ui/label';
import uiTranslations from '@/i18n/ui.json';
import checkboxTranslations from '@shared/content/checkbox/translations.json';

import {
  NdsDocsPageLayout,
  NdsDocsHeader,
  NdsDocsDemonstration,
  NdsDocsAnatomy,
  NdsDocsWhenToUse,
  NdsDocsDoDont,
  NdsDocsImport,
  NdsDocsVariants,
  NdsDocsCompositions,
  NdsDocsStates,
  NdsDocsProps,
  NdsDocsTokens,
  NdsDocsAccessibility,
  NdsDocsRelated,
  NdsDocsNotes,
  NdsDocsAnalytics,
  NdsDocsTestes,
} from '@/components/docs/shared/sections';

const { t: tNav } = useTranslation(uiTranslations as Record<string, unknown>);
const { t, dict } = useTranslation(checkboxTranslations as Record<string, unknown>);

const SECTION_IDS = [
  'demonstracao', 'anatomia', 'quando-usar', 'do-dont',
  'importacao', 'variantes', 'composicoes', 'estados', 'propriedades', 'tokens',
  'acessibilidade', 'relacionados', 'notas', 'analytics', 'testes',
] as const;

const NAV_GROUPS: { labelKey: string; sections: { id: string; labelKey: string }[] }[] = [
  { labelKey: 'nav.overview', sections: [
    { id: 'demonstracao', labelKey: 'nav.demonstration' },
    { id: 'anatomia',     labelKey: 'nav.anatomy'       },
    { id: 'quando-usar',  labelKey: 'nav.usage'         },
    { id: 'do-dont',      labelKey: 'nav.doDont'        },
  ]},
  { labelKey: 'nav.techRef', sections: [
    { id: 'importacao',   labelKey: 'nav.import'       },
    { id: 'variantes',    labelKey: 'nav.variants'     },
    { id: 'composicoes',  labelKey: 'nav.compositions' },
    { id: 'estados',      labelKey: 'nav.states'       },
    { id: 'propriedades', labelKey: 'nav.props'        },
    { id: 'tokens',       labelKey: 'nav.tokens'       },
  ]},
  { labelKey: 'nav.context', sections: [
    { id: 'acessibilidade', labelKey: 'nav.accessibility' },
    { id: 'relacionados',   labelKey: 'nav.related'       },
    { id: 'notas',          labelKey: 'nav.notes'         },
  ]},
  { labelKey: 'nav.quality', sections: [
    { id: 'analytics', labelKey: 'nav.analytics' },
    { id: 'testes',    labelKey: 'nav.testes'    },
  ]},
];

const INTERFACE_CODE = `// <button ndsCheckbox> — compõe os primitivos do Radix NG
@Component({
  selector: 'button[ndsCheckbox]',
  hostDirectives: [
    { directive: RdxCheckboxRootDirective,
      inputs: ['checked', 'indeterminate', 'disabled', 'required', 'name', 'value'],
      outputs: ['checkedChange', 'indeterminateChange'] },
    RdxCheckboxButtonDirective,
  ],
})
export class NdsCheckbox {}

// Uso com Reactive Forms:
// <button ndsCheckbox formControlName="termos" id="termos"></button>`;

const ANATOMY_CODE = `<div class="nds-cluster" data-spacing="sm">
  <button ndsCheckbox id="termos" [(checked)]="aceito"></button>
  <label ndsLabel for="termos">Aceito os termos</label>
</div>`;

@Component({
  selector: 'nds-checkbox-docs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [
    NdsCheckbox, NdsLabel,
    NdsDocsPageLayout, NdsDocsHeader, NdsDocsDemonstration, NdsDocsAnatomy,
    NdsDocsWhenToUse, NdsDocsDoDont, NdsDocsImport, NdsDocsVariants,
    NdsDocsCompositions, NdsDocsStates, NdsDocsProps, NdsDocsTokens,
    NdsDocsAccessibility, NdsDocsRelated, NdsDocsNotes, NdsDocsAnalytics,
    NdsDocsTestes,
  ],
  template: `
    <ng-template #tplDoDont1Do>
      <div class="nds-cluster nds-w-full" data-spacing="sm">
        <button ndsCheckbox id="dd1-do"></button>
        <label ndsLabel for="dd1-do">{{ t('demonstration.labels.acceptTerms') }}</label>
      </div>
    </ng-template>
    <ng-template #tplDoDont1Dont>
      <div class="nds-cluster nds-w-full" data-spacing="sm">
        <button ndsCheckbox [attr.aria-label]="t('demonstration.labels.acceptTerms')"></button>
        <span class="nds-text-body">{{ t('demonstration.labels.acceptTerms') }}</span>
      </div>
    </ng-template>
    <ng-template #tplDoDont2Do>
      <div class="nds-stack nds-w-full" data-spacing="md">
        <div class="nds-cluster" data-spacing="sm">
          <button ndsCheckbox id="dd2-do-a"></button>
          <label ndsLabel for="dd2-do-a">{{ t('demonstration.labels.newsletter') }}</label>
        </div>
        <div class="nds-cluster" data-spacing="sm">
          <button ndsCheckbox id="dd2-do-b"></button>
          <label ndsLabel for="dd2-do-b">{{ t('demonstration.labels.notifications') }}</label>
        </div>
      </div>
    </ng-template>
    <ng-template #tplDoDont2Dont>
      <div class="nds-cluster nds-w-full" data-spacing="sm">
        <button ndsCheckbox id="dd2-dont"></button>
        <label ndsLabel for="dd2-dont">
          {{ t('demonstration.labels.newsletter') }} e {{ t('demonstration.labels.notifications') }}
        </label>
      </div>
    </ng-template>

    <ng-template #tplVarDefault>
      <button ndsCheckbox [attr.aria-label]="t('demonstration.labels.rememberMe')"></button>
    </ng-template>
    <ng-template #tplVarWithLabel>
      <div class="nds-cluster" data-spacing="sm">
        <button ndsCheckbox id="var-label"></button>
        <label ndsLabel for="var-label">{{ t('demonstration.labels.rememberMe') }}</label>
      </div>
    </ng-template>
    <ng-template #tplVarWithDescription>
      <div class="nds-cluster" data-spacing="sm" data-align="start">
        <button ndsCheckbox id="var-desc" aria-describedby="var-desc-texto"></button>
        <div class="nds-stack" data-spacing="xs">
          <label ndsLabel for="var-desc">{{ t('demonstration.labels.newsletter') }}</label>
          <p id="var-desc-texto" class="nds-text-caption nds-text-muted-foreground">
            {{ t('demonstration.labels.notifications') }}
          </p>
        </div>
      </div>
    </ng-template>

    <ng-template #tplCompFieldset>
      <fieldset class="nds-stack" data-spacing="md">
        <legend class="nds-text-body nds-font-medium">
          {{ t('demonstration.labels.notifications') }}
        </legend>
        <div class="nds-cluster" data-spacing="sm">
          <button ndsCheckbox id="comp-fs-a"></button>
          <label ndsLabel for="comp-fs-a">{{ t('demonstration.labels.newsletter') }}</label>
        </div>
        <div class="nds-cluster" data-spacing="sm">
          <button ndsCheckbox id="comp-fs-b"></button>
          <label ndsLabel for="comp-fs-b">{{ t('demonstration.labels.rememberMe') }}</label>
        </div>
      </fieldset>
    </ng-template>
    <ng-template #tplCompSelectAll>
      <div class="nds-stack" data-spacing="md">
        <div class="nds-cluster" data-spacing="sm">
          <button ndsCheckbox id="comp-all" [indeterminate]="true"></button>
          <label ndsLabel for="comp-all">{{ t('demonstration.labels.selectAll') }}</label>
        </div>
        <div class="nds-stack nds-checkbox-sublist" data-spacing="md">
          <div class="nds-cluster" data-spacing="sm">
            <button ndsCheckbox id="comp-all-a" [checked]="true"></button>
            <label ndsLabel for="comp-all-a">{{ t('demonstration.labels.newsletter') }}</label>
          </div>
          <div class="nds-cluster" data-spacing="sm">
            <button ndsCheckbox id="comp-all-b"></button>
            <label ndsLabel for="comp-all-b">{{ t('demonstration.labels.rememberMe') }}</label>
          </div>
        </div>
      </div>
    </ng-template>
    <ng-template #tplCompInList>
      <div class="nds-stack" data-spacing="md">
        <div class="nds-cluster" data-spacing="sm">
          <button ndsCheckbox id="comp-list-a" [checked]="true"></button>
          <label ndsLabel for="comp-list-a">{{ t('demonstration.labels.acceptTerms') }}</label>
        </div>
        <div class="nds-cluster" data-spacing="sm">
          <button ndsCheckbox id="comp-list-b"></button>
          <label ndsLabel for="comp-list-b">{{ t('demonstration.labels.newsletter') }}</label>
        </div>
      </div>
    </ng-template>

    <nds-docs-page-layout
      [navGroups]="navGroups()"
      [activeSection]="activeSection()"
      componentSlug="checkbox"
    >
      <div docsHeader>
        <nds-docs-header
          [title]="t('title')"
          [description]="t('description')"
          [category]="t('category')"
          [type]="t('type')"
        />
      </div>

      <ng-container docsMain>
        <nds-docs-demonstration [title]="t('demonstration.title')">
          <div class="nds-stack nds-w-full" data-spacing="md">
            <div class="nds-cluster" data-spacing="sm">
              <button ndsCheckbox id="demo-terms" [checked]="true"></button>
              <label ndsLabel for="demo-terms">{{ t('demonstration.labels.acceptTerms') }}</label>
            </div>
            <div class="nds-cluster" data-spacing="sm">
              <button ndsCheckbox id="demo-news"></button>
              <label ndsLabel for="demo-news">{{ t('demonstration.labels.newsletter') }}</label>
            </div>
            <div class="nds-cluster" data-spacing="sm">
              <button ndsCheckbox id="demo-mixed" [indeterminate]="true"></button>
              <label ndsLabel for="demo-mixed">{{ t('demonstration.labels.selectAll') }}</label>
            </div>
            <div class="nds-cluster" data-spacing="sm" data-disabled="true">
              <button ndsCheckbox id="demo-disabled" [disabled]="true"></button>
              <label ndsLabel for="demo-disabled">{{ t('demonstration.labels.rememberMe') }}</label>
            </div>
          </div>
        </nds-docs-demonstration>

        <nds-docs-anatomy
          [title]="t('anatomy.title')"
          [items]="anatomyItems()"
          [structureCode]="anatomyCode"
          language="html"
        />

        <nds-docs-when-to-use
          [title]="t('usage.title')"
          [guidelines]="guidelines()"
          [scenarios]="scenarios()"
          [do]="usageDo()"
          [dont]="usageDont()"
        />

        <nds-docs-do-dont [title]="t('doDont.title')" [pairs]="doDontPairs()" />

        <nds-docs-import
          [title]="tNav('nav.import')"
          [code]="importCode"
          componentSlug="checkbox"
          language="ts"
        />

        <nds-docs-variants
          [title]="t('variants.title')"
          [note]="t('variants.note')"
          [items]="variantItems()"
          componentSlug="checkbox"
          id="variantes"
          language="html"
        />

        <nds-docs-compositions
          [title]="t('variants.compositionsTitle')"
          [items]="compositionItems()"
          [useWhenLabel]="tNav('common.useWhen')"
          componentSlug="checkbox"
        />

        <nds-docs-states
          [title]="t('states.title')"
          [cols]="statesCols()"
          [items]="stateItems()"
        />

        <nds-docs-props
          [title]="t('props.title')"
          [tables]="propTables()"
          [interfaceCode]="interfaceCode"
        />

        <nds-docs-tokens
          [title]="t('tokens.title')"
          [cols]="tokensCols()"
          [items]="tokenItems()"
        />

        <nds-docs-accessibility
          [title]="t('accessibility.title')"
          [summary]="t('accessibility.summary')"
          [items]="a11yItems()"
          [keyboardTitle]="tNav('common.keyboardNav')"
          [keyboardItems]="keyboardItems()"
          [screenReaderTitle]="tNav('common.screenReader')"
          [screenReaderItems]="screenReaderItems()"
        />

        <nds-docs-related
          [title]="t('related.title')"
          [items]="relatedItems()"
          componentSlug="checkbox"
        />

        <nds-docs-notes [title]="t('notes.title')" [items]="noteItems()" componentSlug="checkbox" />

        <nds-docs-analytics
          [title]="t('analytics.title')"
          [cols]="analyticsCols()"
          [items]="analyticsItems()"
        />

        <nds-docs-testes
          [title]="t('testes.title')"
          [functional]="testesFunctional()"
          [accessibility]="testesAccessibility()"
          [visual]="testesVisual()"
        />
      </ng-container>
    </nds-docs-page-layout>
  `,
})
export class NdsCheckboxDocs implements AfterViewInit, OnDestroy {
  protected readonly t = t;
  protected readonly tNav = tNav;
  protected readonly interfaceCode = INTERFACE_CODE;
  protected readonly anatomyCode = ANATOMY_CODE;
  protected readonly importCode = `import { NdsCheckbox } from '@/components/ui/checkbox';`;

  protected readonly activeSection = signal<string | undefined>(undefined);

  private readonly tplDoDont1Do = viewChild.required<TemplateRef<unknown>>('tplDoDont1Do');
  private readonly tplDoDont1Dont = viewChild.required<TemplateRef<unknown>>('tplDoDont1Dont');
  private readonly tplDoDont2Do = viewChild.required<TemplateRef<unknown>>('tplDoDont2Do');
  private readonly tplDoDont2Dont = viewChild.required<TemplateRef<unknown>>('tplDoDont2Dont');
  private readonly tplVarDefault = viewChild.required<TemplateRef<unknown>>('tplVarDefault');
  private readonly tplVarWithLabel = viewChild.required<TemplateRef<unknown>>('tplVarWithLabel');
  private readonly tplVarWithDescription = viewChild.required<TemplateRef<unknown>>('tplVarWithDescription');
  private readonly tplCompFieldset = viewChild.required<TemplateRef<unknown>>('tplCompFieldset');
  private readonly tplCompSelectAll = viewChild.required<TemplateRef<unknown>>('tplCompSelectAll');
  private readonly tplCompInList = viewChild.required<TemplateRef<unknown>>('tplCompInList');

  protected readonly navGroups = computed(() => {
    dict();
    return NAV_GROUPS.map((g) => ({
      label: t(g.labelKey),
      sections: g.sections.map((s) => ({ id: s.id, label: t(s.labelKey) })),
    }));
  });

  protected readonly anatomyItems = computed(() => {
    const d = dict();
    // Este componente não numera a anatomia por item1..N — o conteúdo usa o
    // bloco `anatomy` livre. Percorre o que existir, sem inventar linha.
    return Object.keys(d)
      .filter((k) => /^anatomy\.item\d+$/.test(k))
      .sort()
      .map((k) => d[k]);
  });

  protected readonly guidelines = computed(() => {
    const d = dict();
    return {
      title: d['usage.guidelines.title'] ?? '',
      items: Object.keys(d).filter((k) => /^usage\.guidelines\.item\d+$/.test(k)).sort().map((k) => d[k]),
    };
  });

  protected readonly scenarios = computed(() => {
    const d = dict();
    return {
      title: d['usage.scenarios.title'] ?? '',
      cols: {
        scenario: d['usage.scenarios.cols.scenario'] ?? '',
        use: d['usage.scenarios.cols.use'] ?? '',
        alternative: d['usage.scenarios.cols.alternative'] ?? '',
      },
      items: itemsFromDict(d, 'usage.scenarios', ['s', 'u', 'a']),
    };
  });

  protected readonly usageDo = computed(() => {
    dict();
    return { title: t('usage.do.title'), items: [1, 2, 3, 4].map((i) => t(`usage.do.item${i}`)) };
  });

  protected readonly usageDont = computed(() => {
    dict();
    return { title: t('usage.dont.title'), items: [1, 2, 3, 4].map((i) => t(`usage.dont.item${i}`)) };
  });

  protected readonly doDontPairs = computed(() => {
    dict();
    const pairs: [TemplateRef<unknown>, TemplateRef<unknown>][] = [
      [this.tplDoDont1Do(), this.tplDoDont1Dont()],
      [this.tplDoDont2Do(), this.tplDoDont2Dont()],
    ];
    return pairs.map(([doTpl, dontTpl], i) => ({
      doLabel: tNav('common.do'),
      dontLabel: tNav('common.dont'),
      doCaption: toPlainText(t(`doDont.pair${i + 1}.do`)),
      dontCaption: toPlainText(t(`doDont.pair${i + 1}.dont`)),
      doPreview: doTpl,
      dontPreview: dontTpl,
    }));
  });

  protected readonly variantItems = computed(() => {
    dict();
    return [
      { name: t('variants.items.default'),         description: t('variants.items.default'),         trackId: 'default',          preview: this.tplVarDefault()         },
      { name: t('variants.items.withLabel'),       description: t('variants.items.withLabel'),       trackId: 'with-label',       preview: this.tplVarWithLabel()       },
      { name: t('variants.items.withDescription'), description: t('variants.items.withDescription'), trackId: 'with-description', preview: this.tplVarWithDescription() },
    ];
  });

  protected readonly compositionItems = computed(() => {
    dict();
    const mapa: { key: string; tpl: TemplateRef<unknown> }[] = [
      { key: 'fieldset',  tpl: this.tplCompFieldset()  },
      { key: 'selectAll', tpl: this.tplCompSelectAll() },
      { key: 'inList',    tpl: this.tplCompInList()    },
    ];
    return mapa.map(({ key, tpl }) => ({
      name: t(`variants.compositions.${key}.name`),
      description: t(`variants.compositions.${key}.description`),
      useWhen: t(`variants.compositions.${key}.use`),
      trackId: key,
      preview: tpl,
    }));
  });

  protected readonly statesCols = computed(() => {
    dict();
    return {
      state: t('states.cols.state'),
      trigger: t('states.cols.trigger'),
      behavior: t('states.cols.behavior'),
    };
  });

  protected readonly stateItems = computed(() => {
    dict();
    return ['unchecked', 'checked', 'indeterminate', 'disabled', 'error'].map((k) => ({
      label: t(`states.${k}.label`),
      trigger: toPlainText(t(`states.${k}.trigger`)),
      behavior: toPlainText(t(`states.${k}.behavior`)),
    }));
  });

  protected readonly propTables = computed(() => {
    dict();
    const cols = {
      prop: t('props.table.prop'),
      type: t('props.table.type'),
      default: t('props.table.default'),
      required: t('props.table.required'),
      description: t('props.table.description'),
    };
    const not = tNav('common.no');
    // As props vêm do RdxCheckboxRoot via hostDirectives — `checked` e
    // `indeterminate` são `model()`, então `[(checked)]` funciona. O conteúdo
    // compartilhado descreve as mesmas chaves para as outras stacks.
    return [
      {
        title: 'NdsCheckbox',
        cols,
        items: [
          { name: 'checked',        type: 'model<boolean>',   defaultValue: 'false', required: not, description: toPlainText(t('props.items.checked')) },
          { name: 'indeterminate',  type: 'model<boolean>',   defaultValue: 'false', required: not, description: toPlainText(t('props.items.indeterminate')) },
          { name: 'checkedChange',  type: 'output<boolean>',  defaultValue: '—',     required: not, description: toPlainText(t('props.items.onCheckedChange')) },
          { name: 'disabled',       type: 'boolean',          defaultValue: 'false', required: not, description: toPlainText(t('props.items.disabled')) },
          { name: 'required',       type: 'boolean',          defaultValue: 'false', required: not, description: toPlainText(t('props.items.required')) },
          { name: 'name',           type: 'string',           defaultValue: '—',     required: not, description: toPlainText(t('props.items.name')) },
          { name: 'value',          type: 'string',           defaultValue: '—',     required: not, description: toPlainText(t('props.items.value')) },
          { name: 'class',          type: 'string',           defaultValue: '—',     required: not, description: toPlainText(t('props.items.className')) },
        ],
      },
    ];
  });

  protected readonly tokensCols = computed(() => {
    dict();
    return {
      token: t('tokens.table.token'),
      value: t('tokens.table.class'),
      description: t('tokens.table.part'),
    };
  });

  protected readonly tokenItems = computed(() => {
    dict();
    // Seletor real lido de docs/shared/styles/nds/checkbox.css — cada token
    // pinta uma regra diferente, não `.nds-checkbox` para todas as seis.
    return [
      { token: '--primary',            value: '.nds-checkbox[data-state="checked"]', k: 'primary'           },
      { token: '--primary-foreground', value: '.nds-checkbox-indicator',             k: 'primaryForeground' },
      { token: '--input',              value: '.nds-checkbox',                       k: 'input'             },
      { token: '--ring',               value: '.nds-checkbox:focus-visible',         k: 'ring'              },
      { token: '--destructive',        value: '.nds-checkbox[aria-invalid="true"]',  k: 'destructive'       },
      { token: '--border',             value: '.nds-checkbox',                       k: 'border'            },
    ].map(({ token, value, k }) => ({
      token,
      value,
      description: toPlainText(t(`tokens.table.${k}`)),
    }));
  });

  protected readonly a11yItems = computed(() => {
    dict();
    return [1, 2, 3, 4, 5].map((i) => t(`accessibility.item${i}`));
  });

  protected readonly keyboardItems = computed(() => {
    dict();
    return [
      { key: 'Tab',       description: toPlainText(t('accessibility.keyboard.tab')) },
      { key: 'Space',     description: toPlainText(t('accessibility.keyboard.space')) },
      { key: 'Shift+Tab', description: toPlainText(t('accessibility.keyboard.shiftTab')) },
      { key: '—',         description: toPlainText(t('accessibility.keyboard.disabled')) },
    ];
  });

  protected readonly screenReaderItems = computed(() => {
    dict();
    const locale = getLocale();
    const byLocale = checkboxTranslations as unknown as Record<
      string,
      { accessibility?: { screenReader?: Record<string, string> } }
    >;
    return Object.values(byLocale[locale]?.accessibility?.screenReader ?? {});
  });

  protected readonly relatedItems = computed(() => {
    dict();
    return [
      { key: 'switch',     name: 'Switch',      path: '?path=/docs/ui-switch--docs'      },
      { key: 'radioGroup', name: 'Radio Group', path: '?path=/docs/ui-radiogroup--docs'  },
      { key: 'form',       name: 'Form',        path: '?path=/docs/ui-form--docs'        },
      { key: 'select',     name: 'Select',      path: '?path=/docs/ui-select--docs'      },
    ].map(({ key, name, path }) => ({
      name: name,
      description: t(`related.${key}`),
      path,
    }));
  });

  protected readonly noteItems = computed(() => {
    dict();
    return [1, 2, 3, 4].map((i) => ({ title: '', content: t(`notes.tip${i}`) }));
  });

  protected readonly analyticsCols = computed(() => {
    dict();
    return {
      event: t('analytics.table.event'),
      trigger: t('analytics.table.trigger'),
      payload: t('analytics.table.payload'),
    };
  });

  protected readonly analyticsItems = computed(() => {
    dict();
    return ['fieldChange', 'pageView', 'sectionViewed', 'langSwitch'].map((k) => ({
      event: t(`analytics.table.${k}`),
      trigger: toPlainText(t(`analytics.table.${k}Trigger`)),
      payload: toPlainText(t(`analytics.table.${k}Payload`)),
    }));
  });

  protected readonly testesFunctional = computed(() => {
    const d = dict();
    return {
      title: t('testes.functional.title'),
      description: t('testes.functional.description'),
      cols: {
        action: tNav('common.userAction'),
        result: tNav('common.expectedResult'),
        priority: tNav('common.priority'),
      },
      items: itemsFromDict(d, 'testes.functional', ['action', 'result', 'priority']).map((r) => ({
        action: toPlainText(r.action),
        result: stripHtml(toPlainText(r.result)),
        priority: priorityLabel(r.priority),
      })),
    };
  });

  protected readonly testesAccessibility = computed(() => {
    const d = dict();
    return {
      title: t('testes.accessibility.title'),
      description: t('testes.accessibility.description'),
      cols: { criterion: tNav('common.criterion'), level: 'WCAG', how: tNav('common.howToVerify') },
      items: itemsFromDict(d, 'testes.accessibility', ['criterion', 'level', 'how']).map((r) => ({
        criterion: toPlainText(r.criterion),
        level: r.level,
        how: toPlainText(r.how),
      })),
    };
  });

  protected readonly testesVisual = computed(() => {
    const d = dict();
    return {
      title: t('testes.visual.title'),
      description: t('testes.visual.description'),
      cols: { story: tNav('common.storyState'), priority: tNav('common.priority') },
      items: itemsFromDict(d, 'testes.visual', ['story', 'priority']).map((r) => ({
        story: toPlainText(r.story),
        priority: priorityLabel(r.priority),
      })),
    };
  });

  private observer: { disconnect: () => void } | undefined;

  constructor() {
    effect((onCleanup) => {
      dict();
      const locale = getLocale();
      const cleanup = applySeo({
        title: t('seo.title'),
        description: t('seo.description'),
        locale,
        componentSlug: 'checkbox',
      });
      track('docs_page_view', {
        component_name: 'checkbox',
        locale,
        page_title: `${t('title')} · Design System`,
      });
      onCleanup(cleanup);
    });
  }

  ngAfterViewInit(): void {
    this.observer = createActiveSectionObserver(
      [...SECTION_IDS],
      (id) => document.getElementById(id),
      (id) => this.activeSection.set(id),
      (id) =>
        track('docs_section_viewed', {
          component_name: 'checkbox',
          section_id: id,
          locale: getLocale(),
        }),
    );
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }
}

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function priorityLabel(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}

function itemsFromDict<K extends string>(
  d: Record<string, string>,
  base: string,
  fields: readonly K[],
): Record<K, string>[] {
  const rows: Record<K, string>[] = [];
  for (let i = 1; ; i++) {
    if (d[`${base}.item${i}.${fields[0]}`] === undefined) break;
    const row = {} as Record<K, string>;
    for (const f of fields) row[f] = d[`${base}.item${i}.${f}`] ?? '';
    rows.push(row);
  }
  return rows;
}
