// nortear-design-system-react/src/components/docs/InlineCitationDocs.tsx
import { Fragment, useCallback, useEffect, useMemo, type ReactNode } from "react";
import { InlineCitation } from "@/components/ui/inline-citation";
import { Separator } from "@/components/ui/separator";
import {
  citationOf,
  sentenceCitations,
  sentenceParts,
  useInlineCitationLabels,
  type InlineCitationCase,
} from "@/components/ui/inline-citation.fixtures";
import { useTranslation } from "@/lib/i18n";
import { useSeoEffect } from "@/lib/use-seo";
import { track } from "@/lib/analytics";
import { useActiveSection } from "@/lib/use-active-section";
import uiTranslations from "@/i18n/ui.json";
import inlineCitationTranslations from "@shared/content/inline-citation/translations.json";

import { DocsHeader }        from "@/components/docs/shared/sections/DocsHeader";
import { DocsPageLayout }    from "@/components/docs/shared/sections/DocsPageLayout";
import { DocsDemonstration } from "@/components/docs/shared/sections/DocsDemonstration";
import { DocsAnatomy }       from "@/components/docs/shared/sections/DocsAnatomy";
import { DocsWhenToUse }     from "@/components/docs/shared/sections/DocsWhenToUse";
import { DocsDoDont }        from "@/components/docs/shared/sections/DocsDoDont";
import { DocsImport }        from "@/components/docs/shared/sections/DocsImport";
import { DocsStates }        from "@/components/docs/shared/sections/DocsStates";
import { DocsProps }         from "@/components/docs/shared/sections/DocsProps";
import { DocsTokens }        from "@/components/docs/shared/sections/DocsTokens";
import { DocsAccessibility } from "@/components/docs/shared/sections/DocsAccessibility";
import { DocsRelated }       from "@/components/docs/shared/sections/DocsRelated";
import { DocsNotes }         from "@/components/docs/shared/sections/DocsNotes";
import { DocsAnalytics }     from "@/components/docs/shared/sections/DocsAnalytics";
import { DocsTestes }        from "@/components/docs/shared/sections/DocsTestes";
import { stripHtml, toPlainText } from "@/lib/strip-html";

// ─── Helpers ─────────────────────────────────────────────────────────────────

const priorityKeyMap: Record<string, string> = {
  high: "common.high",
  medium: "common.medium",
  low: "common.low",
};

// ─── Nav ─────────────────────────────────────────────────────────────────────

const getNavGroups = (t: (key: string) => string) => [
  {
    label: t("nav.overview"),
    sections: [
      { id: "demonstracao", label: t("nav.demonstration") },
      { id: "anatomia",     label: t("nav.anatomy") },
      { id: "quando-usar",  label: t("nav.usage") },
      { id: "do-dont",      label: t("nav.doDont") },
    ],
  },
  {
    label: t("nav.techRef"),
    sections: [
      { id: "importacao",   label: t("nav.import") },
      { id: "estados",      label: t("nav.states") },
      { id: "propriedades", label: t("nav.props") },
      { id: "tokens",       label: t("nav.tokens") },
    ],
  },
  {
    label: t("nav.context"),
    sections: [
      { id: "acessibilidade", label: t("nav.accessibility") },
      { id: "relacionados",   label: t("nav.related") },
      { id: "notas",          label: t("nav.notes") },
    ],
  },
  {
    label: t("nav.quality"),
    sections: [
      { id: "analytics", label: t("nav.analytics") },
      { id: "testes",    label: t("nav.testes") },
    ],
  },
];

const INTERFACE_CODE = `export interface InlineCitationProps {
  citation: Citation;                    // a fonte, o trecho e onde dentro dela
  index: number;                         // o número que a marca mostra
  defaultOpen?: boolean;                 // nasce com a prévia aberta
  onOpenChange?: (open: boolean) => void;
  labels: InlineCitationLabels;
}

// O VOCABULÁRIO NÃO É DAQUI. \`Citation\` e \`ChatSource\` vêm de
// \`@shared/primitives/chat-protocol\`, e é lá que está escrito por que o trecho
// mora na CITAÇÃO e não na fonte: a mesma fonte apoia afirmações diferentes.
export interface Citation {
  source: ChatSource;         // o documento
  excerpt?: string;           // o texto citado, como saiu da fonte
  anchor?: string;            // onde dentro dele — página, âncora, linhas
}

export interface InlineCitationLabels {
  marker: string;             // o nome acessível, já escrito, com o número dentro
  unsafeSource: string;       // o que se diz no lugar de um endereço recusado
}

// A MARCA É CONTROLÁVEL POR COMANDO, e o comando é o que resolve a exclusão
// mútua entre duas prévias — a peça não conhece as vizinhas, e não conhecê-las
// é o que permite que duas marcas da mesma frase venham de lugares diferentes.
export type InlineCitationHandle = {
  open: () => void;
  close: () => void;
  toggle: () => void;
  isOpen: () => boolean;
};`;

// ─── Exemplos ────────────────────────────────────────────────────────────────

/**
 * Uma frase com uma marca, que é a única forma em que esta peça existe.
 *
 * A frase é montada AQUI, e não pelo componente: é a demonstração do contrato —
 * quem escreve a frase decide onde a afirmação precisa de apoio. Nenhum pedaço
 * termina em espaço, e é isso que mantém a marca colada à palavra na quebra de
 * linha.
 */
function CitationSentence({ name, open = false }: { name: InlineCitationCase; open?: boolean }) {
  const labelsOf = useInlineCitationLabels();
  const parts = sentenceParts();
  const citation = citationOf(name);

  return (
    <p>
      {parts[0]}
      <InlineCitation
        citation={citation}
        index={1}
        defaultOpen={open}
        labels={labelsOf(1, citation)}
      />
      {parts[1] + parts[2]}
    </p>
  );
}

/** A frase com as DUAS marcas, cada uma com a própria numeração. */
function SentenceWithTwo() {
  const labelsOf = useInlineCitationLabels();
  const parts = sentenceParts();
  const citations = sentenceCitations();

  return (
    <p>
      {parts[0]}
      {citations.map((citation, i) => (
        <Fragment key={i}>
          <InlineCitation
            citation={citation}
            index={i + 1}
            labels={labelsOf(i + 1, citation)}
          />
          {parts[i + 1]}
        </Fragment>
      ))}
    </p>
  );
}

/**
 * O contraexemplo: o nome acessível é o número.
 *
 * Quem vê não nota diferença nenhuma, e é esse o ponto — "1" não descreve fonte
 * nenhuma para quem ouve.
 */
function NumberNamedSentence({ unsafeSource }: { unsafeSource: string }) {
  const parts = sentenceParts();
  const citation = citationOf("full");

  return (
    <p>
      {parts[0]}
      <InlineCitation
        citation={citation}
        index={1}
        labels={{ marker: "1", unsafeSource }}
      />
      {parts[1] + parts[2]}
    </p>
  );
}

/**
 * O contraexemplo: um traço no lugar do trecho que não veio.
 *
 * A prévia passa a afirmar que existe um trecho vazio, que é pior do que não
 * dizer nada.
 */
function DashedSentence() {
  const labelsOf = useInlineCitationLabels();
  const parts = sentenceParts();
  const plain = citationOf("minimal");

  return (
    <p>
      {parts[0]}
      <InlineCitation
        citation={{ source: plain.source, excerpt: "—", anchor: "—" }}
        index={1}
        defaultOpen
        labels={labelsOf(1, plain)}
      />
      {parts[1] + parts[2]}
    </p>
  );
}

// ─── Componente principal ─────────────────────────────────────────────────────

export function InlineCitationDocs() {
  const { t: tNav } = useTranslation(uiTranslations);
  const { t: tContent, locale } = useTranslation(inlineCitationTranslations);

  // As chaves de `accessibility.screenReader` variam por componente, então só os
  // valores chegam ao container — o `t()` exige nome de chave e não serviria.
  // O `title` fica de fora: ele é o cabeçalho da lista, não um item dela.
  const screenReaderItems = useMemo(
    () =>
      Object.entries(
        (inlineCitationTranslations as unknown as Record<
          string,
          { accessibility?: { screenReader?: Record<string, string> } }
        >)[locale]?.accessibility?.screenReader ?? {},
      )
        .filter(([key]) => key !== "title")
        .map(([, value]) => value),
    [locale],
  );

  const navGroups = useMemo(() => getNavGroups(tNav), [tNav]);
  const allIds = useMemo(
    () => navGroups.flatMap((g) => g.sections.map((s) => s.id)),
    [navGroups],
  );

  useSeoEffect({
    title: tContent("seo.title"),
    description: tContent("seo.description"),
    locale,
    componentSlug: "inline-citation",
  });

  useEffect(() => {
    track("docs_page_view", {
      component_name: "inline-citation",
      locale,
      page_title: `${tContent("title")} · Design System`,
    });
  }, [locale, tContent]);

  const handleSectionChange = useCallback(
    (id: string) => {
      track("docs_section_viewed", {
        section_id: id,
        component_name: "inline-citation",
        locale,
      });
    },
    [locale],
  );

  const activeId = useActiveSection(allIds, handleSectionChange);

  const priorityLabel = (raw: string) => tNav(priorityKeyMap[raw] ?? "common.high");

  /**
   * Uma frase, rotulada.
   *
   * A legenda diz QUAL exemplo está desenhado — sem ela, quatro frases quase
   * iguais viram uma só, e o assunto da demonstração é justamente a diferença
   * entre elas.
   *
   * `reserve` dá altura ao exemplo cuja prévia nasce aberta: a caixa é
   * posicionada fora do fluxo, então sem folga ela cobriria a legenda do
   * exemplo seguinte.
   */
  const example = (labelKey: string, node: ReactNode, reserve = false) => (
    <div className="nds-stack nds-w-full" data-spacing="xs">
      <p className="nds-text-caption nds-text-muted-foreground">
        {stripHtml(tContent(labelKey))}
      </p>
      <div className={reserve ? "nds-min-h-50" : undefined}>{node}</div>
    </div>
  );

  const examples = [
    // O primeiro é o único fechado, e é ele que mostra a peça como ela vive:
    // duas marcas dentro de uma frase, à espera de quem lê.
    example("demonstration.labels.inSentence", <SentenceWithTwo />),
    example("demonstration.labels.open", <CitationSentence name="full" open />, true),
    example("demonstration.labels.minimal", <CitationSentence name="minimal" open />, true),
    example("demonstration.labels.unsafe", <CitationSentence name="unsafe" open />, true),
  ];

  const propsCols = {
    prop: tContent("props.table.prop"),
    type: tContent("props.table.type"),
    default: tContent("props.table.default"),
    required: tContent("props.table.required"),
    description: tContent("props.table.description"),
  };

  const propsRows = (keys: string[]) =>
    keys.map((k) => ({
      name: tContent(`props.table.${k}.name`),
      type: tContent(`props.table.${k}.type`),
      defaultValue: tContent(`props.table.${k}.default`),
      required: tContent(`props.table.${k}.required`),
      description: toPlainText(tContent(`props.table.${k}.description`)),
    }));

  return (
    <DocsPageLayout
      navGroups={navGroups}
      activeSection={activeId}
      header={
        <DocsHeader
          title={tContent("title")}
          description={tContent("description")}
          category={tContent("category")}
          type={tContent("type")}
        />
      }
    >
      {/* ── Demonstração ──────────────────────────────────────────── */}
      <DocsDemonstration
        title={tContent("demonstration.title")}
        componentSlug="inline-citation"
      >
        <div className="nds-stack nds-w-full" data-spacing="lg">
          {examples.map((el, i) => (
            <Fragment key={i}>
              {i > 0 && <Separator />}
              {el}
            </Fragment>
          ))}
        </div>
      </DocsDemonstration>

      {/* ── Anatomia ──────────────────────────────────────────────── */}
      <DocsAnatomy
        title={tContent("anatomy.title")}
        items={[1, 2, 3, 4, 5].map((i) => tContent(`anatomy.item${i}`))}
        structureLabel={tContent("anatomy.structureLabel")}
        structureCode={tContent("anatomy.structureCode")}
        language="html"
      />

      {/* ── Quando Usar ───────────────────────────────────────────── */}
      <DocsWhenToUse
        title={tContent("usage.title")}
        guidelines={{
          title: tContent("usage.guidelines.title"),
          items: [1, 2, 3, 4, 5, 6].map((i) => tContent(`usage.guidelines.item${i}`)),
        }}
        scenarios={{
          title: tContent("usage.scenarios.title"),
          cols: {
            scenario: tContent("usage.scenarios.cols.scenario"),
            use: tContent("usage.scenarios.cols.use"),
            alternative: tContent("usage.scenarios.cols.alternative"),
          },
          items: [1, 2, 3, 4, 5].map((i) => ({
            s: tContent(`usage.scenarios.item${i}.s`),
            u: tContent(`usage.scenarios.item${i}.u`),
            a: toPlainText(tContent(`usage.scenarios.item${i}.a`)),
          })),
        }}
        uxWriting={{
          title: tContent("usage.uxWriting.title"),
          cols: {
            element: tContent("usage.uxWriting.table.element"),
            rules: tContent("usage.uxWriting.table.rules"),
            do: tContent("usage.uxWriting.table.correct"),
            dont: tContent("usage.uxWriting.table.avoid"),
          },
          items: ["marker", "unsafeSource", "sourceTitle", "anchor"].map((k) => ({
            element: tContent(`usage.uxWriting.table.${k}.name`),
            rules: tContent(`usage.uxWriting.table.${k}.format`),
            do: tContent(`usage.uxWriting.table.${k}.good`),
            dont: tContent(`usage.uxWriting.table.${k}.bad`),
          })),
        }}
        do={{
          title: tContent("usage.do.title"),
          items: [1, 2, 3, 4].map((i) => tContent(`usage.do.item${i}`)),
        }}
        dont={{
          title: tContent("usage.dont.title"),
          items: [1, 2, 3, 4].map((i) => tContent(`usage.dont.item${i}`)),
        }}
      />

      {/* ── Do & Don't ────────────────────────────────────────────── */}
      <DocsDoDont
        title={tContent("doDont.title")}
        pairs={[
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doCaption: toPlainText(tContent("doDont.pair1.do")),
            dontCaption: toPlainText(tContent("doDont.pair1.dont")),
            // A MESMA citação nos dois lados: o que muda é o nome acessível.
            doPreview: <CitationSentence name="full" />,
            dontPreview: (
              <NumberNamedSentence unsafeSource={tContent("labels.unsafeSource")} />
            ),
          },
          {
            doLabel: tNav("common.do"),
            dontLabel: tNav("common.dont"),
            doCaption: toPlainText(tContent("doDont.pair2.do")),
            dontCaption: toPlainText(tContent("doDont.pair2.dont")),
            doPreview: <CitationSentence name="minimal" open />,
            dontPreview: <DashedSentence />,
          },
        ]}
      />

      {/* ── Importação ────────────────────────────────────────────── */}
      <DocsImport
        title={tContent("import.title")}
        description={tContent("import.basic")}
        code={tContent("import.basicCode")}
        secondaryDescription={tContent("import.withLabels")}
        secondaryCode={tContent("import.withLabelsCode")}
      />

      {/* ── Estados ───────────────────────────────────────────────── */}
      <DocsStates
        title={tContent("states.title")}
        cols={{
          state: tContent("states.cols.state"),
          trigger: tContent("states.cols.trigger"),
          behavior: tContent("states.cols.behavior"),
        }}
        // Só os dois primeiros são estados que a peça guarda — recolhida e
        // expandida. Os outros dois são o que a mesma prévia faz conforme o que
        // a citação trouxe.
        items={["closed", "open", "minimal", "unsafe"].map((k) => ({
          label: tContent(`states.${k}.label`),
          trigger: toPlainText(tContent(`states.${k}.trigger`)),
          behavior: toPlainText(tContent(`states.${k}.behavior`)),
        }))}
      />

      {/* ── Propriedades ──────────────────────────────────────────── */}
      <DocsProps
        title={tContent("props.title")}
        tables={[
          {
            title: "InlineCitation",
            cols: propsCols,
            items: propsRows(["citation", "index", "defaultOpen", "onOpenChange", "labels"]),
          },
          {
            title: "Citation",
            cols: propsCols,
            items: propsRows(["citationSource", "citationExcerpt", "citationAnchor"]),
          },
          {
            title: "ChatSource",
            cols: propsCols,
            items: propsRows(["sourceTitle", "sourceUrl"]),
          },
          {
            title: "InlineCitationLabels",
            cols: propsCols,
            items: propsRows(["labelsMarker", "labelsUnsafeSource"]),
          },
        ]}
        interfaceCode={INTERFACE_CODE}
        extensibilityTitle={tContent("props.extensibilityTitle")}
        extensibilityNotes={stripHtml(tContent("props.extensibility"))}
        extensibilityCode={tContent("props.extensibilityCode")}
      />

      {/* ── Tokens ────────────────────────────────────────────────── */}
      <DocsTokens
        title={tContent("tokens.title")}
        cols={{
          token: tContent("tokens.table.token"),
          value: tContent("tokens.table.value"),
          description: tContent("tokens.table.description"),
        }}
        items={[
          "muted", "foreground", "primary", "primaryForeground", "ring",
          "sizeXs", "radiusSm", "textLabel",
          "textControlSm", "spacing2", "mutedForeground", "border",
        ].map((k) => ({
          token: tContent(`tokens.table.${k}.token`),
          value: tContent(`tokens.table.${k}.value`),
          description: toPlainText(tContent(`tokens.table.${k}.description`)),
        }))}
        customizationTitle={tContent("tokens.customizationTitle")}
        customizationCode={tContent("tokens.customizationCode")}
        language="css"
      />

      {/* ── Acessibilidade ────────────────────────────────────────── */}
      <DocsAccessibility
        title={tContent("accessibility.title")}
        summary={tContent("accessibility.summary")}
        items={[1, 2, 3, 4, 5, 6, 7, 8].map((i) => tContent(`accessibility.items.item${i}`))}
        keyboardTitle={tContent("accessibility.keyboard.title")}
        keyboardItems={[
          { key: "Tab",            description: tContent("accessibility.keyboard.tab") },
          { key: "Enter / Space",  description: tContent("accessibility.keyboard.enter") },
          { key: "Escape",         description: tContent("accessibility.keyboard.escape") },
        ]}
        screenReaderTitle={tContent("accessibility.screenReader.title")}
        screenReaderItems={screenReaderItems}
      />

      {/* ── Relacionados ──────────────────────────────────────────── */}
      <DocsRelated
        title={tContent("related.title")}
        items={[
          { name: tContent("related.items.chatThread.name"), description: toPlainText(tContent("related.items.chatThread.description")), path: "?path=/docs/primitives-conversational-chatthread--docs" },
          { name: tContent("related.items.hoverCard.name"),  description: toPlainText(tContent("related.items.hoverCard.description")),  path: "?path=/docs/primitives-overlay-hovercard--docs"        },
          { name: tContent("related.items.popover.name"),    description: toPlainText(tContent("related.items.popover.description")),    path: "?path=/docs/primitives-overlay-popover--docs"          },
          { name: tContent("related.items.tooltip.name"),    description: toPlainText(tContent("related.items.tooltip.description")),    path: "?path=/docs/primitives-overlay-tooltip--docs"          },
        ]}
      />

      {/* ── Notas ─────────────────────────────────────────────────── */}
      <DocsNotes
        title={tContent("notes.title")}
        componentSlug="inline-citation"
        items={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((i) => ({
          title: "",
          content: tContent(`notes.item${i}`),
        }))}
      />

      {/* ── Analytics ─────────────────────────────────────────────── */}
      <DocsAnalytics
        title={tContent("analytics.title")}
        cols={{
          event: tContent("analytics.table.event"),
          trigger: tContent("analytics.table.trigger"),
          payload: tContent("analytics.table.payload"),
        }}
        items={["pageView", "sectionViewed", "demoClick"].map((k) => ({
          event: tContent(`analytics.table.${k}`),
          trigger: toPlainText(tContent(`analytics.table.${k}Trigger`)),
          payload: tContent(`analytics.table.${k}Payload`),
        }))}
      />

      {/* ── Testes ────────────────────────────────────────────────── */}
      <DocsTestes
        title={tContent("testes.title")}
        functional={{
          title: tContent("testes.functional.title"),
          description: tContent("testes.functional.description"),
          cols: {
            action: tNav("common.userAction"),
            result: tNav("common.expectedResult"),
            priority: tNav("common.priority"),
          },
          items: [1, 2, 3, 4, 5, 6, 7, 8].map((i) => ({
            action: toPlainText(tContent(`testes.functional.item${i}.action`)),
            result: toPlainText(tContent(`testes.functional.item${i}.result`)),
            priority: priorityLabel(tContent(`testes.functional.item${i}.priority`)),
          })),
        }}
        accessibility={{
          title: tContent("testes.accessibility.title"),
          description: tContent("testes.accessibility.description"),
          cols: {
            criterion: tNav("common.criterion"),
            level: "WCAG",
            how: tNav("common.howToVerify"),
          },
          // A lista é PLANA: cada item é um critério, e o "como verificar" é o
          // próprio addon-a11y rodando em toda story.
          items: [1, 2, 3, 4, 5, 6, 7, 8].map((i) => ({
            criterion: toPlainText(tContent(`testes.accessibility.item${i}`)),
            level: "AA",
            how: "—",
          })),
        }}
        visual={{
          title: tContent("testes.visual.title"),
          description: tContent("testes.visual.description"),
          cols: {
            story: tNav("common.storyState"),
            priority: tNav("common.priority"),
          },
          items: [1, 2, 3, 4, 5, 6].map((i) => ({
            story: toPlainText(tContent(`testes.visual.item${i}.story`)),
            priority: priorityLabel(tContent(`testes.visual.item${i}.priority`)),
          })),
        }}
      />
    </DocsPageLayout>
  );
}

// nortear-design-system-angular/src/components/docs/InlineCitationDocs.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  OnDestroy,
  TemplateRef,
  ViewEncapsulation,
  computed,
  effect,
  signal,
  viewChild,
} from '@angular/core';
import { applySeo } from '@/lib/use-seo';
import { track } from '@/lib/analytics';
import { useTranslation, getLocale } from '@/lib/i18n';
import { createActiveSectionObserver } from '@/lib/use-active-section';
import { toPlainText } from '@/lib/strip-html';
import { NdsInlineCitation, type InlineCitationLabels } from '@/components/ui/inline-citation';
import {
  citationOf,
  inlineCitationLabels,
  sentenceParts,
  sentenceSlots,
  type InlineCitationSlot,
} from '@/components/ui/inline-citation.fixtures';
import { NdsSeparator } from '@/components/ui/separator';
import type { Citation } from '@shared/primitives/chat-protocol';
import uiTranslations from '@/i18n/ui.json';
import inlineCitationTranslations from '@shared/content/inline-citation/translations.json';

import {
  NdsDocsPageLayout,
  NdsDocsHeader,
  NdsDocsDemonstration,
  NdsDocsAnatomy,
  NdsDocsWhenToUse,
  NdsDocsDoDont,
  NdsDocsImport,
  NdsDocsStates,
  NdsDocsProps,
  NdsDocsTokens,
  NdsDocsAccessibility,
  NdsDocsRelated,
  NdsDocsNotes,
  NdsDocsAnalytics,
  NdsDocsTestes,
} from '@/components/docs/shared/sections';

const { t: tNav } = useTranslation(uiTranslations as Record<string, unknown>);

// O OVERRIDE TROCA O NOME, E O TIPO — NUNCA A DESCRIÇÃO.
//
// O conteúdo compartilhado documenta a saída como `onOpenChange`, que é o nome
// da propriedade nas stacks em que ela é uma função passada por argumento. Aqui
// ela é um `output`, e o prefixo `on` é do LISTENER: `(openChange)="…"`. Um
// output chamado `onOpenChange` viraria `(onOpenChange)` no ponto de uso, que é
// o mesmo defeito que a linha do estado da execução já registrou com `action`.
//
// A DESCRIÇÃO fica intocada: ela é neutra de API e continua verdadeira — a peça
// devolve cada abertura e cada fechamento, e é por aí que a página fecha a
// prévia irmã. E nada de snippet `*Code` aqui: ele ficaria preso a esta stack e
// invisível para o conteúdo compartilhado.
const { t, dict } = useTranslation(inlineCitationTranslations as Record<string, unknown>, {
  '*': {
    'props.table.onOpenChange.name': 'openChange',
    'props.table.onOpenChange.type': 'OutputEmitterRef<boolean>',
  },
});

// Esta peça não tem eixo de forma, e o conteúdo compartilhado não traz seção de
// variantes: ela não existe nem na navegação nem na página.
const SECTION_IDS = [
  'demonstracao', 'anatomia', 'quando-usar', 'do-dont',
  'importacao', 'estados', 'propriedades', 'tokens',
  'acessibilidade', 'relacionados', 'notas', 'analytics', 'testes',
] as const;

const NAV_GROUPS: { labelKey: string; sections: { id: string; labelKey: string }[] }[] = [
  { labelKey: 'nav.overview', sections: [
    { id: 'demonstracao', labelKey: 'nav.demonstration' },
    { id: 'anatomia',     labelKey: 'nav.anatomy'       },
    { id: 'quando-usar',  labelKey: 'nav.usage'         },
    { id: 'do-dont',      labelKey: 'nav.doDont'        },
  ]},
  { labelKey: 'nav.techRef', sections: [
    { id: 'importacao',   labelKey: 'nav.import'   },
    { id: 'estados',      labelKey: 'nav.states'   },
    { id: 'propriedades', labelKey: 'nav.props'    },
    { id: 'tokens',       labelKey: 'nav.tokens'   },
  ]},
  { labelKey: 'nav.context', sections: [
    { id: 'acessibilidade', labelKey: 'nav.accessibility' },
    { id: 'relacionados',   labelKey: 'nav.related'       },
    { id: 'notas',          labelKey: 'nav.notes'         },
  ]},
  { labelKey: 'nav.quality', sections: [
    { id: 'analytics', labelKey: 'nav.analytics' },
    { id: 'testes',    labelKey: 'nav.testes'    },
  ]},
];

const INTERFACE_CODE = `// As quatro entradas da peça, no <span ndsInlineCitation>
export class NdsInlineCitation {
  readonly citation = input.required<Citation>();     // a fonte, o trecho e onde dentro dela
  readonly index = input.required<number>();          // o número que a marca mostra
  readonly labels = input.required<InlineCitationLabels>();
  readonly defaultOpen = input(false);                // nasce com a prévia aberta

  // Cada abertura e cada fechamento. O prefixo "on" é do LISTENER nesta stack —
  // no ponto de uso isto se escreve (openChange)="fecharAsOutras($event)".
  readonly openChange = output<boolean>();

  // O COMANDO. É a forma que esta stack tem de ser controlada: quem controla
  // alcança a peça por viewChild/viewChildren e chama o método. É esse par —
  // evento de volta, comando de ida — que resolve a exclusão mútua entre marcas,
  // que a peça não resolve sozinha porque não conhece as vizinhas.
  open(): void;
  close(): void;
  toggle(): void;
  isOpen(): boolean;
}

// O VOCABULÁRIO NÃO É DAQUI. Citation e ChatSource vêm de
// @shared/primitives/chat-protocol, e é lá que está escrito por que o trecho
// mora na CITAÇÃO e não na fonte: a mesma fonte apoia afirmações diferentes.
export interface Citation {
  source: ChatSource;         // o documento
  excerpt?: string;           // o texto citado, como saiu da fonte
  anchor?: string;            // onde dentro dele — página, âncora, linhas
}

export interface InlineCitationLabels {
  marker: string;             // o nome acessível, já escrito, com o número dentro
  unsafeSource: string;       // o que se diz no lugar de um endereço recusado
}`;

@Component({
  selector: 'nds-inline-citation-docs',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  imports: [
    NdsInlineCitation, NdsSeparator,
    NdsDocsPageLayout, NdsDocsHeader, NdsDocsDemonstration, NdsDocsAnatomy,
    NdsDocsWhenToUse, NdsDocsDoDont, NdsDocsImport, NdsDocsStates, NdsDocsProps,
    NdsDocsTokens, NdsDocsAccessibility, NdsDocsRelated, NdsDocsNotes,
    NdsDocsAnalytics, NdsDocsTestes,
  ],
  // A FRASE É MONTADA AQUI, e não pelo componente: é a demonstração do contrato
  // — quem escreve a frase decide onde a afirmação precisa de apoio. Nenhum
  // pedaço termina em espaço, e as emendas do template encostam de propósito: é
  // assim que a marca não se separa da palavra que a antecede na quebra de linha.
  template: `
    <!-- O primeiro par é o do NOME ACESSÍVEL: a mesma citação dos dois lados, e
         o que muda é só o que quem ouve recebe. Quem vê não nota diferença
         nenhuma, e é esse o ponto. -->
    <ng-template #tplDoDont1Do>
      <p>{{ antes }}<span
          ndsInlineCitation
          [citation]="full"
          [index]="1"
          [labels]="fullLabels()"
        ></span>{{ depois }}</p>
    </ng-template>
    <ng-template #tplDoDont1Dont>
      <p>{{ antes }}<span
          ndsInlineCitation
          [citation]="full"
          [index]="1"
          [labels]="numberOnlyLabels()"
        ></span>{{ depois }}</p>
    </ng-template>

    <!-- O segundo par é o do que NÃO veio: a citação mínima desenhada como ela
         é, e a mesma com um traço no lugar do trecho e do lugar. O traço afirma
         que existe um trecho vazio, que é pior do que não dizer nada. -->
    <ng-template #tplDoDont2Do>
      <p>{{ antes }}<span
          ndsInlineCitation
          [citation]="minimal"
          [index]="1"
          [labels]="minimalLabels()"
          [defaultOpen]="true"
        ></span>{{ depois }}</p>
    </ng-template>
    <ng-template #tplDoDont2Dont>
      <p>{{ antes }}<span
          ndsInlineCitation
          [citation]="dashed"
          [index]="1"
          [labels]="minimalLabels()"
          [defaultOpen]="true"
        ></span>{{ depois }}</p>
    </ng-template>

    <nds-docs-page-layout
      [navGroups]="navGroups()"
      [activeSection]="activeSection()"
      componentSlug="inline-citation"
    >
      <div docsHeader>
        <nds-docs-header
          [title]="t('title')"
          [description]="t('description')"
          [category]="t('category')"
          [type]="t('type')"
        />
      </div>

      <ng-container docsMain>
        <nds-docs-demonstration
          [title]="t('demonstration.title')"
          componentSlug="inline-citation"
        >
          <div class="nds-stack nds-w-full" data-spacing="lg">
            <!-- A legenda diz QUAL exemplo está desenhado — sem ela, quatro
                 frases quase iguais viram uma só, e o assunto da demonstração é
                 justamente a diferença entre elas.

                 O primeiro é o único fechado, e é ele que mostra a peça como ela
                 vive: duas marcas dentro de uma frase, à espera de quem lê. -->
            <div class="nds-stack nds-w-full" data-spacing="xs">
              <p class="nds-text-caption nds-text-muted-foreground">{{ t('demonstration.labels.inSentence') }}</p>
              <div>
                <p>{{ antes }}@for (slot of slots; track slot.index) {<span
                      ndsInlineCitation
                      [citation]="slot.citation"
                      [index]="slot.index"
                      [labels]="slot.labels"
                    ></span>{{ slot.tail }}}</p>
              </div>
            </div>

            <div ndsSeparator></div>

            <!-- Os três seguintes nascem abertos, e por isso ganham folga: a
                 caixa é posicionada FORA do fluxo, então sem altura reservada
                 ela cobriria a legenda do exemplo seguinte. -->
            <div class="nds-stack nds-w-full" data-spacing="xs">
              <p class="nds-text-caption nds-text-muted-foreground">{{ t('demonstration.labels.open') }}</p>
              <div class="nds-min-h-50">
                <p>{{ antes }}<span
                    ndsInlineCitation
                    [citation]="full"
                    [index]="1"
                    [labels]="fullLabels()"
                    [defaultOpen]="true"
                  ></span>{{ depois }}</p>
              </div>
            </div>

            <div ndsSeparator></div>

            <div class="nds-stack nds-w-full" data-spacing="xs">
              <p class="nds-text-caption nds-text-muted-foreground">{{ t('demonstration.labels.minimal') }}</p>
              <div class="nds-min-h-50">
                <p>{{ antes }}<span
                    ndsInlineCitation
                    [citation]="minimal"
                    [index]="1"
                    [labels]="minimalLabels()"
                    [defaultOpen]="true"
                  ></span>{{ depois }}</p>
              </div>
            </div>

            <div ndsSeparator></div>

            <div class="nds-stack nds-w-full" data-spacing="xs">
              <p class="nds-text-caption nds-text-muted-foreground">{{ t('demonstration.labels.unsafe') }}</p>
              <div class="nds-min-h-50">
                <p>{{ antes }}<span
                    ndsInlineCitation
                    [citation]="unsafe"
                    [index]="1"
                    [labels]="unsafeLabels()"
                    [defaultOpen]="true"
                  ></span>{{ depois }}</p>
              </div>
            </div>
          </div>
        </nds-docs-demonstration>

        <nds-docs-anatomy
          [title]="t('anatomy.title')"
          [items]="anatomyItems()"
          [structureLabel]="t('anatomy.structureLabel')"
          [structureCode]="t('anatomy.structureCode')"
          language="html"
        />

        <nds-docs-when-to-use
          [title]="t('usage.title')"
          [guidelines]="guidelines()"
          [scenarios]="scenarios()"
          [uxWriting]="uxWriting()"
          [do]="usageDo()"
          [dont]="usageDont()"
        />

        <nds-docs-do-dont [title]="t('doDont.title')" [pairs]="doDontPairs()" />

        <nds-docs-import
          [title]="t('import.title')"
          [description]="t('import.basic')"
          [code]="t('import.basicCode')"
          [secondaryDescription]="t('import.withLabels')"
          [secondaryCode]="t('import.withLabelsCode')"
          componentSlug="inline-citation"
        />

        <nds-docs-states
          [title]="t('states.title')"
          [cols]="statesCols()"
          [items]="stateItems()"
        />

        <nds-docs-props
          [title]="t('props.title')"
          [tables]="propTables()"
          [interfaceCode]="interfaceCode"
          [extensibilityTitle]="t('props.extensibilityTitle')"
          [extensibilityNotes]="t('props.extensibility')"
          [extensibilityCode]="t('props.extensibilityCode')"
          language="ts"
        />

        <nds-docs-tokens
          [title]="t('tokens.title')"
          [cols]="tokensCols()"
          [items]="tokenItems()"
          [customizationTitle]="t('tokens.customizationTitle')"
          [customizationCode]="t('tokens.customizationCode')"
          language="css"
        />

        <nds-docs-accessibility
          [title]="t('accessibility.title')"
          [summary]="t('accessibility.summary')"
          [items]="a11yItems()"
          [keyboardTitle]="t('accessibility.keyboard.title')"
          [keyboardItems]="keyboardItems()"
          [screenReaderTitle]="t('accessibility.screenReader.title')"
          [screenReaderItems]="screenReaderItems()"
        />

        <nds-docs-related
          [title]="t('related.title')"
          [items]="relatedItems()"
          componentSlug="inline-citation"
        />

        <nds-docs-notes
          [title]="t('notes.title')"
          [items]="noteItems()"
          componentSlug="inline-citation"
        />

        <nds-docs-analytics
          [title]="t('analytics.title')"
          [cols]="analyticsCols()"
          [items]="analyticsItems()"
        />

        <nds-docs-testes
          [title]="t('testes.title')"
          [functional]="testesFunctional()"
          [accessibility]="testesAccessibility()"
          [visual]="testesVisual()"
        />
      </ng-container>
    </nds-docs-page-layout>
  `,
})
export class NdsInlineCitationDocs implements AfterViewInit, OnDestroy {
  protected readonly t = t;
  protected readonly tNav = tNav;
  protected readonly interfaceCode = INTERFACE_CODE;

  /**
   * A frase das fotos, partida onde as marcas entram.
   *
   * Dado, e por isso a mesma nos três idiomas: a frase é a fala da demonstração,
   * e é ela que garante que as cinco stacks fotografem o mesmo parágrafo.
   */
  protected readonly antes = sentenceParts()[0]!;
  protected readonly depois = sentenceParts()[1]! + sentenceParts()[2]!;

  /** As três citações que a peça desenha diferente. */
  protected readonly full = citationOf('full');
  protected readonly minimal = citationOf('minimal');
  protected readonly unsafe = citationOf('unsafe');

  /**
   * O contraexemplo do segundo par: um traço no lugar do que não veio.
   *
   * A prévia passa a AFIRMAR que existe um trecho vazio, e afirmar isso é pior
   * do que não dizer nada. A citação é montada aqui porque não há entrada que
   * produza o defeito — a peça simplesmente não monta o que não recebeu.
   */
  protected readonly dashed: Citation = {
    source: this.minimal.source,
    excerpt: '—',
    anchor: '—',
  };

  /** As duas marcas da frase da demonstração, já numeradas. */
  protected readonly slots: InlineCitationSlot[] = sentenceSlots();

  // Os rótulos são texto de interface, então acompanham a troca de idioma.
  protected readonly fullLabels = computed<InlineCitationLabels>(() => {
    dict();
    return inlineCitationLabels(1, this.full);
  });

  protected readonly minimalLabels = computed<InlineCitationLabels>(() => {
    dict();
    return inlineCitationLabels(1, this.minimal);
  });

  protected readonly unsafeLabels = computed<InlineCitationLabels>(() => {
    dict();
    return inlineCitationLabels(1, this.unsafe);
  });

  /**
   * O contraexemplo do primeiro par: o nome acessível é o número.
   *
   * "1" não descreve fonte nenhuma, e quem vê não nota diferença alguma em
   * relação ao exemplo certo — é exatamente esse o assunto do par.
   */
  protected readonly numberOnlyLabels = computed<InlineCitationLabels>(() => {
    dict();
    return { marker: '1', unsafeSource: t('labels.unsafeSource') };
  });

  protected readonly activeSection = signal<string | undefined>(undefined);
  private observer: { disconnect: () => void } | undefined;

  private readonly tplDoDont1Do = viewChild.required<TemplateRef<unknown>>('tplDoDont1Do');
  private readonly tplDoDont1Dont = viewChild.required<TemplateRef<unknown>>('tplDoDont1Dont');
  private readonly tplDoDont2Do = viewChild.required<TemplateRef<unknown>>('tplDoDont2Do');
  private readonly tplDoDont2Dont = viewChild.required<TemplateRef<unknown>>('tplDoDont2Dont');

  protected readonly navGroups = computed(() => {
    dict();
    return NAV_GROUPS.map((g) => ({
      label: tNav(g.labelKey),
      sections: g.sections.map((s) => ({ id: s.id, label: tNav(s.labelKey) })),
    }));
  });

  protected readonly anatomyItems = computed(() => {
    dict();
    return [1, 2, 3, 4, 5].map((i) => t(`anatomy.item${i}`));
  });

  protected readonly guidelines = computed(() => {
    dict();
    return {
      title: t('usage.guidelines.title'),
      items: [1, 2, 3, 4, 5, 6].map((i) => t(`usage.guidelines.item${i}`)),
    };
  });

  protected readonly scenarios = computed(() => {
    dict();
    return {
      title: t('usage.scenarios.title'),
      cols: {
        scenario: t('usage.scenarios.cols.scenario'),
        use: t('usage.scenarios.cols.use'),
        alternative: t('usage.scenarios.cols.alternative'),
      },
      items: [1, 2, 3, 4, 5].map((i) => ({
        s: t(`usage.scenarios.item${i}.s`),
        u: t(`usage.scenarios.item${i}.u`),
        a: toPlainText(t(`usage.scenarios.item${i}.a`)),
      })),
    };
  });

  protected readonly uxWriting = computed(() => {
    dict();
    return {
      title: t('usage.uxWriting.title'),
      cols: {
        element: t('usage.uxWriting.table.element'),
        rules: t('usage.uxWriting.table.rules'),
        do: t('usage.uxWriting.table.correct'),
        dont: t('usage.uxWriting.table.avoid'),
      },
      items: ['marker', 'unsafeSource', 'sourceTitle', 'anchor'].map((key) => ({
        element: t(`usage.uxWriting.table.${key}.name`),
        rules: t(`usage.uxWriting.table.${key}.format`),
        do: t(`usage.uxWriting.table.${key}.good`),
        dont: t(`usage.uxWriting.table.${key}.bad`),
      })),
    };
  });

  protected readonly usageDo = computed(() => {
    dict();
    return { title: t('usage.do.title'), items: [1, 2, 3, 4].map((i) => t(`usage.do.item${i}`)) };
  });

  protected readonly usageDont = computed(() => {
    dict();
    return {
      title: t('usage.dont.title'),
      items: [1, 2, 3, 4].map((i) => t(`usage.dont.item${i}`)),
    };
  });

  protected readonly doDontPairs = computed(() => {
    dict();
    return [
      {
        doLabel: tNav('common.do'),
        dontLabel: tNav('common.dont'),
        doCaption: toPlainText(t('doDont.pair1.do')),
        dontCaption: toPlainText(t('doDont.pair1.dont')),
        doPreview: this.tplDoDont1Do(),
        dontPreview: this.tplDoDont1Dont(),
      },
      {
        doLabel: tNav('common.do'),
        dontLabel: tNav('common.dont'),
        doCaption: toPlainText(t('doDont.pair2.do')),
        dontCaption: toPlainText(t('doDont.pair2.dont')),
        doPreview: this.tplDoDont2Do(),
        dontPreview: this.tplDoDont2Dont(),
      },
    ];
  });

  protected readonly statesCols = computed(() => {
    dict();
    return {
      state: t('states.cols.state'),
      trigger: t('states.cols.trigger'),
      behavior: t('states.cols.behavior'),
    };
  });

  protected readonly stateItems = computed(() => {
    dict();
    // Só os dois primeiros são estados que a peça guarda — recolhida e
    // expandida. Os outros dois são o que a MESMA prévia faz conforme o que a
    // citação trouxe.
    return ['closed', 'open', 'minimal', 'unsafe'].map((k) => ({
      label: t(`states.${k}.label`),
      trigger: toPlainText(t(`states.${k}.trigger`)),
      behavior: toPlainText(t(`states.${k}.behavior`)),
    }));
  });

  protected readonly propTables = computed(() => {
    dict();
    const cols = {
      prop: t('props.table.prop'),
      type: t('props.table.type'),
      default: t('props.table.default'),
      required: t('props.table.required'),
      description: t('props.table.description'),
    };
    const rowsOf = (keys: string[]) =>
      keys.map((k) => ({
        name: t(`props.table.${k}.name`),
        type: t(`props.table.${k}.type`),
        defaultValue: t(`props.table.${k}.default`),
        required: t(`props.table.${k}.required`),
        description: toPlainText(t(`props.table.${k}.description`)),
      }));
    return [
      {
        title: 'NdsInlineCitation',
        cols,
        items: rowsOf(['citation', 'index', 'defaultOpen', 'onOpenChange', 'labels']),
      },
      {
        title: 'Citation',
        cols,
        items: rowsOf(['citationSource', 'citationExcerpt', 'citationAnchor']),
      },
      { title: 'ChatSource', cols, items: rowsOf(['sourceTitle', 'sourceUrl']) },
      {
        title: 'InlineCitationLabels',
        cols,
        items: rowsOf(['labelsMarker', 'labelsUnsafeSource']),
      },
    ];
  });

  protected readonly tokensCols = computed(() => {
    dict();
    return {
      token: t('tokens.table.token'),
      value: t('tokens.table.value'),
      description: t('tokens.table.description'),
    };
  });

  protected readonly tokenItems = computed(() => {
    dict();
    return [
      'muted', 'foreground', 'primary', 'primaryForeground', 'ring',
      'sizeXs', 'radiusSm', 'textLabel',
      'textControlSm', 'spacing2', 'mutedForeground', 'border',
    ].map((k) => ({
      token: t(`tokens.table.${k}.token`),
      value: t(`tokens.table.${k}.value`),
      description: toPlainText(t(`tokens.table.${k}.description`)),
    }));
  });

  protected readonly a11yItems = computed(() => {
    dict();
    return [1, 2, 3, 4, 5, 6, 7, 8].map((i) => t(`accessibility.items.item${i}`));
  });

  protected readonly keyboardItems = computed(() => {
    dict();
    return [
      { key: 'Tab',            description: toPlainText(t('accessibility.keyboard.tab'))    },
      { key: 'Enter / Space',  description: toPlainText(t('accessibility.keyboard.enter'))  },
      { key: 'Escape',         description: toPlainText(t('accessibility.keyboard.escape')) },
    ];
  });

  protected readonly screenReaderItems = computed(() => {
    dict();
    return [1, 2, 3].map((i) => t(`accessibility.screenReader.item${i}`));
  });

  protected readonly relatedItems = computed(() => {
    dict();
    return [
      { key: 'chatThread', path: '?path=/docs/components-conversational-chatthread--docs' },
      { key: 'hoverCard',  path: '?path=/docs/components-overlay-hovercard--docs'         },
      { key: 'popover',    path: '?path=/docs/components-overlay-popover--docs'           },
      { key: 'tooltip',    path: '?path=/docs/components-overlay-tooltip--docs'           },
    ].map(({ key, path }) => ({
      name: t(`related.items.${key}.name`),
      description: toPlainText(t(`related.items.${key}.description`)),
      path,
    }));
  });

  protected readonly noteItems = computed(() => {
    dict();
    return [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((i) => ({
      title: '',
      content: t(`notes.item${i}`),
    }));
  });

  protected readonly analyticsCols = computed(() => {
    dict();
    return {
      event: t('analytics.table.event'),
      trigger: t('analytics.table.trigger'),
      payload: t('analytics.table.payload'),
    };
  });

  protected readonly analyticsItems = computed(() => {
    dict();
    return ['pageView', 'sectionViewed', 'demoClick'].map((k) => ({
      event: t(`analytics.table.${k}`),
      trigger: toPlainText(t(`analytics.table.${k}Trigger`)),
      payload: t(`analytics.table.${k}Payload`),
    }));
  });

  protected readonly testesFunctional = computed(() => {
    dict();
    return {
      title: t('testes.functional.title'),
      description: t('testes.functional.description'),
      cols: {
        action: tNav('common.userAction'),
        result: tNav('common.expectedResult'),
        priority: tNav('common.priority'),
      },
      items: [1, 2, 3, 4, 5, 6, 7, 8].map((i) => ({
        action: toPlainText(t(`testes.functional.item${i}.action`)),
        result: toPlainText(t(`testes.functional.item${i}.result`)),
        priority: priorityLabel(t(`testes.functional.item${i}.priority`)),
      })),
    };
  });

  protected readonly testesAccessibility = computed(() => {
    dict();
    // A lista é PLANA: cada item é um critério, e o "como verificar" é o próprio
    // addon-a11y rodando em toda story.
    return {
      title: t('testes.accessibility.title'),
      description: t('testes.accessibility.description'),
      cols: {
        criterion: tNav('common.criterion'),
        level: 'WCAG',
        how: tNav('common.howToVerify'),
      },
      items: [1, 2, 3, 4, 5, 6, 7, 8].map((i) => ({
        criterion: toPlainText(t(`testes.accessibility.item${i}`)),
        level: 'AA',
        how: '—',
      })),
    };
  });

  protected readonly testesVisual = computed(() => {
    dict();
    return {
      title: t('testes.visual.title'),
      description: t('testes.visual.description'),
      cols: {
        story: tNav('common.storyState'),
        priority: tNav('common.priority'),
      },
      items: [1, 2, 3, 4, 5, 6].map((i) => ({
        story: toPlainText(t(`testes.visual.item${i}.story`)),
        priority: priorityLabel(t(`testes.visual.item${i}.priority`)),
      })),
    };
  });

  constructor() {
    effect((onCleanup) => {
      dict();
      const locale = getLocale();
      const cleanup = applySeo({
        title: t('seo.title'),
        description: t('seo.description'),
        locale,
        componentSlug: 'inline-citation',
      });
      track('docs_page_view', {
        component_name: 'inline-citation',
        locale,
        page_title: `${t('title')} · Design System`,
      });
      onCleanup(cleanup);
    });
  }

  ngAfterViewInit(): void {
    this.observer = createActiveSectionObserver(
      [...SECTION_IDS],
      (id) => document.getElementById(id),
      (id) => this.activeSection.set(id),
      (id) =>
        track('docs_section_viewed', {
          component_name: 'inline-citation',
          section_id: id,
          locale: getLocale(),
        }),
    );
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }
}

const priorityKeyMap: Record<string, string> = {
  high: 'common.high',
  medium: 'common.medium',
  low: 'common.low',
};

function priorityLabel(raw: string): string {
  return tNav(priorityKeyMap[raw] ?? 'common.high');
}
