// nortear-design-system-vue/src/components/ui/sidebar/SidebarInput.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'
import { Input } from '@/components/ui/input'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <Input
    data-slot="sidebar-input"
    data-sidebar="input"
    :class="cn('nds-sidebar-input', props.class)"
  >
    <slot />
  </Input>
</template>

// design-system-svelte/src/components/ui/sidebar/sidebar-input.svelte
<script lang="ts">
	import type { ComponentProps } from "svelte";
	import { Input } from "@/components/ui/input/index.js";
	import { cn } from "@/lib/utils.js";

	let {
		ref = $bindable(null),
		value = $bindable(""),
		class: className,
		...restProps
	}: ComponentProps<typeof Input> = $props();
</script>

<Input
	bind:ref
	bind:value
	data-slot="sidebar-input"
	data-sidebar="input"
	class={cn("nds-sidebar-input", className)}
	{...restProps}
/>
