// design-system-vue/src/components/ui/sidebar/SidebarMenuSubItem.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <li
    data-slot="sidebar-menu-sub-item"
    data-sidebar="menu-sub-item"
    :class="cn('nds-sidebar-menu-sub-item', props.class)"
  >
    <slot />
  </li>
</template>

// design-system-svelte/src/components/ui/sidebar/sidebar-menu-sub-item.svelte
<script lang="ts">
	import { cn, type WithElementRef } from "@/lib/utils.js";
	import type { HTMLAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		children,
		class: className,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLLIElement>> = $props();
</script>

<li
	bind:this={ref}
	data-slot="sidebar-menu-sub-item"
	data-sidebar="menu-sub-item"
	class={cn("nds-sidebar-menu-sub-item", className)}
	{...restProps}
>
	{@render children?.()}
</li>
