// nortear-design-system-svelte/src/components/ui/composer/composer-context.svelte
<script lang="ts" module>
  // ─── ComposerContext ───────────────────────────────────────────────────────
  //
  // As etiquetas do que vai junto com a pergunta sem ser carga.
  //
  // Desenho em `nds/composer.css`, no bloco de contexto, que também guarda as
  // cinco decisões de acessibilidade. O vocabulário — `ContextItem`,
  // `ContextKind`, `isContextRemovable` — vem de
  // `@shared/primitives/chat-protocol`.
  //
  // A DECISÃO QUE GOVERNA A PEÇA: contexto não é anexo, ainda que a geometria
  // seja quase a mesma. O anexo é CARGA — sobe, tem bytes, tem progresso e pode
  // falhar no meio, e por isso a fila de anexos desenha estado e barra. O
  // contexto é REFERÊNCIA: aponta para o que já está lá, não sobe nada e não
  // tem o que esperar. É por isso que aqui não há `state` nem `progress`: não
  // existe espera para comunicar, e uma barra parada seria uma barra mentindo.
  //
  // O QUE O COMPONENTE NÃO FAZ: decidir o que entra na pergunta, o quanto um
  // item abrange, ou tirar coisa alguma. Ele desenha a lista que recebe e avisa
  // que alguém pediu para tirar um item. Quem consome monta a pergunta e
  // decide — mesma divisão de `approval` no `chat-thread`.
  import type { ContextKind } from '@shared/primitives/chat-protocol';

  /**
   * O vocabulário da lista.
   *
   * Tudo aqui é TEXTO de interface, e por isso tem três idiomas: a espécie que
   * chega a quem ouve, a marca do que entrou sozinho e o nome do botão que
   * tira um item.
   */
  export interface ComposerContextLabels {
    /** Nome acessível da lista. */
    list: string;
    /** Nome do botão de remover. `{label}` vira o nome do item. */
    remove: string;
    /** A palavra de cada espécie. É ela que o leitor de tela recebe. */
    kind: Record<ContextKind, string>;
    /** A marca do que entrou sem ninguém pedir. É texto, e não só a cor. */
    automatic: string;
  }
</script>

<script lang="ts">
  import AppWindow from '@lucide/svelte/icons/app-window';
  import File from '@lucide/svelte/icons/file';
  import Folder from '@lucide/svelte/icons/folder';
  import FolderGit2 from '@lucide/svelte/icons/folder-git-2';
  import SquareDashedText from '@lucide/svelte/icons/square-dashed-text';
  import { isContextRemovable, type ContextItem } from '@shared/primitives/chat-protocol';
  import { Button } from '@/components/ui/button';

  const {
    items,
    labels,
    onRemove,
  }: {
    items: ContextItem[];
    labels: ComposerContextLabels;
    /** Alguém pediu para tirar. Tirar de verdade é de quem monta a pergunta. */
    onRemove?: (item: ContextItem) => void;
  } = $props();

  /**
   * O ícone de cada espécie.
   *
   * Ele é DECORATIVO, e a espécie viaja em texto dentro do item (decisão 2 da
   * folha): o ícone é a única pista visual de que aquilo é um trecho e não o
   * arquivo inteiro, e pista que só existe em desenho não chega a quem ouve
   * (WCAG 1.1.1).
   *
   * O mapa é `Record<ContextKind, …>` de propósito: espécie nova no vocabulário
   * compartilhado reprova a compilação aqui, em vez de cair num ícone genérico
   * que ninguém repara que está errado.
   */
  const KIND_ICONS: Record<ContextKind, typeof File> = {
    selection: SquareDashedText,
    file: File,
    directory: Folder,
    page: AppWindow,
    repository: FolderGit2,
  };

  /**
   * O nome acessível leva o NOME DO ITEM.
   *
   * Uma lista de botões chamados "Remover" é um botão só para quem navega por
   * audição (decisão 4 da folha).
   */
  function removeLabel(item: ContextItem): string {
    return labels.remove.replace('{label}', item.label);
  }
</script>

<!--
  `<ul>`: é o que faz o leitor de tela dizer QUANTOS itens a pergunta leva antes
  de percorrê-los, e aqui a contagem é a informação — saber que são sete
  arquivos muda o que se pergunta. Uma pilha de `div` não anuncia nada.
-->
<ul data-slot="composer-context" class="nds-composer-context" aria-label={labels.list}>
  {#each items as item, index (item.id ?? index)}
    {@const Icon = KIND_ICONS[item.kind]}
    <li
      class="nds-composer-context-item"
      data-slot="composer-context-item"
      data-kind={item.kind}
      data-context-id={item.id}
      data-automatic={item.automatic ? 'true' : undefined}
    >
      <!-- O ícone é DESENHO, e sai do que é lido em voz. -->
      <Icon class="nds-composer-context-icon" aria-hidden="true" />

      <!--
        A espécie em TEXTO, dentro do item (decisão 2 da folha). Ela não vai num
        `aria-label` do `<li>`: rótulo em item de lista SUBSTITUI o conteúdo no
        anúncio, e o recorte — que é o que separa um pedaço do todo — sairia
        junto. Escondida do olho, presente para o ouvido, e na frente do nome
        porque é assim que a frase se lê: "Trecho relatorio.ts, linhas 12–48".
      -->
      <span class="nds-sr-only">{labels.kind[item.kind]}</span>

      <span class="nds-composer-context-label">{item.label}</span>

      <!--
        O recorte, quando o item é um PEDAÇO. Sem ele, um trecho seria o nome de
        um arquivo repetido.
      -->
      {#if item.detail}
        <span class="nds-composer-context-detail">{item.detail}</span>
      {/if}

      <!--
        A decisão 3 da folha, e a máquina dela mora no protocolo: contexto
        automático não ganha botão de remover — ele voltaria na próxima
        pergunta, e botão que desfaz o que se refaz sozinho é armadilha. A marca
        ocupa o lugar do botão, e é TEXTO: a moldura tracejada sozinha não
        descreve estado (WCAG 1.4.1).
      -->
      {#if isContextRemovable(item)}
        <Button
          data-slot="composer-context-remove"
          variant="ghost"
          size="icon-sm"
          aria-label={removeLabel(item)}
          onclick={() => onRemove?.(item)}
        >
          ×
        </Button>
      {:else}
        <span
          class="nds-composer-context-detail"
          data-slot="composer-context-automatic">{labels.automatic}</span
        >
      {/if}
    </li>
  {/each}
</ul>

// nortear-design-system-react/src/components/ui/composer-context.tsx
import {
  AppWindow,
  File,
  Folder,
  FolderGit2,
  SquareDashedText,
  type LucideIcon,
} from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  isContextRemovable,
  type ContextItem,
  type ContextKind,
} from "@shared/primitives/chat-protocol"

/**
 * As etiquetas do que vai junto com a pergunta sem ser carga.
 *
 * Desenho em `nds/composer.css`, no bloco de contexto, que também guarda as
 * cinco decisões de acessibilidade. O vocabulário — `ContextItem`,
 * `ContextKind`, `isContextRemovable` — vem de
 * `@shared/primitives/chat-protocol`.
 *
 * A DECISÃO QUE GOVERNA A PEÇA: contexto não é anexo, ainda que a geometria
 * seja quase a mesma. O anexo é CARGA — sobe, tem bytes, tem progresso e pode
 * falhar no meio, e por isso a fila de anexos desenha estado e barra. O
 * contexto é REFERÊNCIA: aponta para o que já está lá, não sobe nada e não tem
 * o que esperar. É por isso que aqui não há `state` nem `progress`: não existe
 * espera para comunicar, e uma barra parada seria uma barra mentindo.
 *
 * O QUE O COMPONENTE NÃO FAZ: decidir o que entra na pergunta, o quanto um
 * item abrange, ou tirar coisa alguma. Ele desenha a lista que recebe e avisa
 * que alguém pediu para tirar um item. Quem consome monta a pergunta e decide —
 * mesma divisão de `approval` no `chat-thread`.
 *
 * A API NÃO DIVERGE do resto do sistema: os três nomes são os mesmos em todas
 * as stacks, porque aqui não há estado imperativo para traduzir. A lista é dado
 * que entra e desenho que sai. O que muda é só o portador do ícone — aqui um
 * componente, e não a lista `[tag, atributos]` do pacote agnóstico.
 */

/**
 * O ícone de cada espécie.
 *
 * Ele é DECORATIVO, e a espécie viaja em texto no nome acessível do item
 * (decisão 2 da folha): o ícone é a única pista visual de que aquilo é um
 * trecho e não o arquivo inteiro, e pista que só existe em desenho não chega a
 * quem ouve (WCAG 1.1.1).
 *
 * O mapa é `Record<ContextKind, …>` de propósito: espécie nova no vocabulário
 * compartilhado reprova a compilação aqui, em vez de cair num ícone genérico
 * que ninguém repara que está errado.
 */
const KIND_ICONS: Record<ContextKind, LucideIcon> = {
  selection: SquareDashedText,
  file: File,
  directory: Folder,
  page: AppWindow,
  repository: FolderGit2,
}

export interface ComposerContextLabels {
  /** Nome acessível da lista. */
  list: string
  /** Nome do botão de remover. `{label}` vira o nome do item. */
  remove: string
  /** A palavra de cada espécie. É ela que o leitor de tela recebe. */
  kind: Record<ContextKind, string>
  /** A marca do que entrou sem ninguém pedir. É texto, e não só a cor. */
  automatic: string
}

export interface ComposerContextProps {
  items: ContextItem[]
  labels: ComposerContextLabels
  /** Alguém pediu para tirar. Tirar de verdade é de quem monta a pergunta. */
  onRemove?: (item: ContextItem) => void
}

function ComposerContext({ items, labels, onRemove }: ComposerContextProps) {
  return (
    // `<ul>`: é o que faz o leitor de tela dizer QUANTOS itens a pergunta leva
    // antes de percorrê-los, e aqui a contagem é a informação — saber que são
    // sete arquivos muda o que se pergunta. Uma pilha de `div` não anuncia nada.
    <ul
      data-slot="composer-context"
      className="nds-composer-context"
      aria-label={labels.list}
    >
      {items.map((item, index) => {
        const Icon = KIND_ICONS[item.kind]

        return (
          <li
            key={item.id ?? `${item.label}-${index}`}
            className="nds-composer-context-item"
            data-slot="composer-context-item"
            data-kind={item.kind}
            data-context-id={item.id}
            data-automatic={item.automatic ? "true" : undefined}
          >
            {/* O ícone é DESENHO, e sai do que é lido em voz. */}
            <Icon className="nds-composer-context-icon" aria-hidden="true" />

            {/* A espécie em TEXTO, dentro do item (decisão 2 da folha). Ela
                não vai num `aria-label` do `<li>`: rótulo em item de lista
                SUBSTITUI o conteúdo no anúncio, e o recorte — que é o que
                separa um pedaço do todo — sairia junto. Escondida do olho,
                presente para o ouvido, e na frente do nome porque é assim que a
                frase se lê: "Trecho relatorio.ts, linhas 12–48". */}
            <span className="nds-sr-only">{labels.kind[item.kind]}</span>

            <span className="nds-composer-context-label">{item.label}</span>

            {/* O recorte, quando o item é um PEDAÇO. Sem ele, um trecho seria o
                nome de um arquivo repetido. */}
            {item.detail ? (
              <span className="nds-composer-context-detail">{item.detail}</span>
            ) : null}

            {/* A decisão 3 da folha, e a máquina dela mora no protocolo:
                contexto automático não ganha botão de remover — ele voltaria na
                próxima pergunta, e botão que desfaz o que se refaz sozinho é
                armadilha. A marca ocupa o lugar do botão, e é TEXTO: a moldura
                tracejada sozinha não descreve estado (WCAG 1.4.1). */}
            {isContextRemovable(item) ? (
              // O nome acessível leva o NOME DO ITEM: uma lista de botões
              // chamados "Remover" é um botão só para quem navega por audição
              // (decisão 4).
              <Button
                data-slot="composer-context-remove"
                type="button"
                variant="ghost"
                size="icon-sm"
                aria-label={labels.remove.replace("{label}", item.label)}
                onClick={() => onRemove?.(item)}
              >
                ×
              </Button>
            ) : (
              <span
                className="nds-composer-context-detail"
                data-slot="composer-context-automatic"
              >
                {labels.automatic}
              </span>
            )}
          </li>
        )
      })}
    </ul>
  )
}

export { ComposerContext }
