// nortear-design-system-angular/src/components/ui/popover.source.ts
/**
 * Transform do painel Code do Popover.
 *
 * Exportado de um módulo próprio para ser CHAMADO pela guarda
 * `source-snippets.test.ts`, que varre `*.source.ts` por glob e lê o texto que
 * sai. Construtor inline não é alcançável por ela — e exportar do
 * `.stories.ts` viraria story fantasma na barra lateral.
 *
 * O snippet ensina o painel com cabeçalho nomeado (`ndsPopoverTitle` e
 * `ndsPopoverDescription`, que é de onde sai o nome acessível) e os DOIS
 * caminhos de fechar, que não são intercambiáveis: o "Cancelar" é a peça de
 * fechar (`button[ndsPopoverClose]`), e o "Salvar" fecha por CÓDIGO depois de
 * salvar. A diferença chega ao relatório como `close-button` × `api`, que é o
 * que separa quem desistiu de quem concluiu — ver `popover-close-reason.ts`.
 *
 * O segundo construtor é o do painel com FORMULÁRIO, e ele existe porque ali a
 * mesma regra muda de lugar: o fechamento por código não pode morar no clique
 * de "Atualizar" — mora no `(submit)`. Ver o bloco sobre `popoverFormSource`.
 *
 * Os quatro últimos servem as cinco stories de ESTADO, que até 2026-09-13
 * publicavam o template cru — com a interpolação de `SIMPLE_PANEL` no meio, com
 * o gancho `data-testid` da play e com o `[(open)]` amarrado a uma propriedade
 * solta que não existe fora do renderer do Storybook.
 *
 * O que é ANDAIME naquelas stories, e por isso não entra em snippet nenhum:
 *
 *  · `data-testid="area-externa"` e o parágrafo que o carrega, em Controlled.
 *    É alvo inerte para a play clicar FORA do painel — não faz parte do que o
 *    modo controlado ensina.
 *  · `[defaultOpen]="true"` em Modal, que abre o painel para o axe varrer e o
 *    Chromatic fotografar. Um popover modal que já nasce aberto prende o foco
 *    de quem acabou de chegar na página, e ensiná-lo seria ensinar a foto.
 *
 * O que NÃO é andaime, e por isso fica: em Modal, a AUSÊNCIA de peça de fechar
 * e os dois checkboxes rotulados. Os dois são o assunto — ver o comentário da
 * story e o bloco sobre `popoverModalSource`.
 *
 * Os SEIS últimos fecham, em 2026-09-13, a dívida que estava declarada em
 * `SEM_CONSTRUTOR` no teste: as duas stories de variante (`Default`,
 * `WithTitle`) e as quatro de composição (`TableFilter`, `ColorPicker`,
 * `QuickSettings`, `SideTop`) publicavam o template cru. A lista deixou de
 * existir junto com eles — lista de exclusão vazia é pior que exclusão nenhuma,
 * porque continua parecendo que alguém a relê.
 *
 * O andaime que some nesses seis, e o motivo:
 *
 *  · o irmão `[data-slot="side-top-headroom"]` e o embrulho que o segura, em
 *    SideTop. Ele existe para o auto-flip NÃO acontecer no primeiro passo da
 *    play; é arranjo do quadro da story, e não do componente. A premissa é
 *    cobrada em `popover.source.test.ts`.
 *  · o prefixo de id das stories (`pc-`, `pv-`), que existe só para dois
 *    exemplos não colidirem no mesmo documento da docs page.
 */
import type { PopoverAlign, PopoverSide } from './popover';
export type PopoverArgs = {
  side: PopoverSide;
  align: PopoverAlign;
  sideOffset: number;
  defaultOpen: boolean;
  triggerLabel: string;
  onOpenChange: (open: boolean) => void;
};

/**
 * Ver a nota em separator.stories.ts: o painel Code imprime o `template` da
 * story literalmente, com os bindings ligados aos args e o `(openChange)` do
 * espião. O `transform` devolve o uso real, com os valores atuais dos controls.
 */
export function popoverPlaygroundSource(
  _gerado?: string,
  ctx: { args?: Partial<PopoverArgs> } = {},
): string {
  const {
    side = 'bottom',
    align = 'center',
    sideOffset = 4,
    defaultOpen = false,
    triggerLabel = 'Abrir popover',
  } = ctx.args ?? {};

  // Só o que difere do padrão entra no snippet — documentação que repete valor
  // padrão ensina ruído.
  const options = [
    side !== 'bottom' ? `side="${side}"` : '',
    align !== 'center' ? `align="${align}"` : '',
    sideOffset !== 4 ? `[sideOffset]="${sideOffset}"` : '',
  ].filter(Boolean).join(' ');
  // A raiz é sempre CONTROLADA: é o `[(open)]` que permite ao "Salvar" fechar
  // por código. O control `defaultOpen` entra no valor inicial do sinal, que é
  // onde o estado inicial mora num painel controlado.
  return `import { signal } from '@angular/core';
import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';

@Component({
  imports: [...NDS_POPOVER, NdsButton],
  template: \`
    <div ndsPopover [(open)]="aberto">
      <button ndsPopoverTrigger ndsButton variant="outline">${triggerLabel}</button>

      <ng-template ndsPopoverContent${options ? ` ${options}` : ''}>
        <div ndsPopoverHeader>
          <h2 ndsPopoverTitle>Configurações de exibição</h2>
          <p ndsPopoverDescription>Ajuste a aparência do conteúdo da página.</p>
        </div>

        <div class="nds-cluster" data-justify="end" data-spacing="sm">
          <!-- Desistiu: a peça de fechar, que reporta close-button -->
          <button ndsPopoverClose ndsButton variant="ghost" size="sm">Cancelar</button>
          <!-- Concluiu: salva e fecha por código, que reporta api -->
          <button ndsButton size="sm" (click)="salvar()">Salvar</button>
        </div>
      </ng-template>
    </div>
  \`,
})
export class Exemplo {
  readonly aberto = signal(${defaultOpen ? 'true' : 'false'});

  salvar(): void {
    // …persistir…
    this.aberto.set(false);
  }
}`;
}

/**
 * Painel com FORMULÁRIO embutido — a terceira forma documentada do popover.
 *
 * A regra do rodapé é a mesma do construtor acima, e a diferença é só ONDE o
 * fechamento por código mora: aqui a ação que confirma é o `type="submit"` do
 * formulário, então fechar tem de acontecer no `(submit)`, depois do
 * `preventDefault()`. Fechar no `(click)` do botão desmontaria o formulário
 * antes de ele enviar — e deixaria de fora o ENTER num campo, que é como
 * metade das pessoas envia formulário e nunca passa pelo clique.
 *
 * O "Cancelar" continua sendo a peça de fechar (`ndsPopoverClose`, motivo
 * `close-button`, desistiu); o submit fecha por código (motivo `api`,
 * concluiu).
 */
export function popoverFormSource(
  _gerado?: string,
  ctx: { args?: Partial<PopoverArgs> } = {},
): string {
  const { triggerLabel = 'Editar perfil' } = ctx.args ?? {};

  return `import { signal } from '@angular/core';
import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';
import { NdsInput } from '@/components/ui/input';
import { NdsLabel } from '@/components/ui/label';

@Component({
  imports: [...NDS_POPOVER, NdsButton, NdsInput, NdsLabel],
  template: \`
    <div ndsPopover [(open)]="aberto">
      <button ndsPopoverTrigger ndsButton variant="outline">${triggerLabel}</button>

      <ng-template ndsPopoverContent align="start">
        <div ndsPopoverHeader>
          <h2 ndsPopoverTitle>Editar perfil</h2>
          <p ndsPopoverDescription>Altere o nome e o email da conta.</p>
        </div>

        <!-- Fechar mora no (submit), e não no clique de "Atualizar": fechar no
             clique desmontaria o formulário antes de ele enviar, e só o caminho
             do submit cobre também o Enter num campo. -->
        <form class="nds-stack" data-spacing="md" (submit)="atualizar($event)">
          <div class="nds-stack" data-spacing="xs">
            <label ndsLabel for="perfil-nome">Nome</label>
            <input ndsInput id="perfil-nome" value="Ana Ribeiro" />
          </div>

          <div class="nds-stack" data-spacing="xs">
            <label ndsLabel for="perfil-email">Email</label>
            <input ndsInput id="perfil-email" type="email" value="ana@nortear.com.br" />
          </div>

          <div class="nds-cluster" data-justify="end" data-spacing="sm">
            <!-- Desistiu: a peça de fechar, que reporta close-button -->
            <button ndsPopoverClose ndsButton variant="ghost" size="sm">Cancelar</button>
            <!-- Concluiu: o submit grava e fecha por código, que reporta api -->
            <button ndsButton type="submit" size="sm">Atualizar</button>
          </div>
        </form>
      </ng-template>
    </div>
  \`,
})
export class Exemplo {
  readonly aberto = signal(false);

  atualizar(evento: Event): void {
    evento.preventDefault();
    // …gravar o perfil…
    this.aberto.set(false);
  }
}`;
}

// ─── As cinco stories de ESTADO ───────────────────────────────────────────────

/**
 * O painel simples — o MESMO das stories de estado, que o interpolam de uma
 * constante em vez de o repetirem quatro vezes.
 *
 * Escrito sem recuo de base: `indented()` o encaixa no nível de cada exemplo,
 * que muda quando a raiz ganha um embrulho (é o caso de Controlled).
 */
const SIMPLE_PANEL = `<ng-template ndsPopoverContent>
  <div ndsPopoverHeader>
    <h2 ndsPopoverTitle>Configurações de exibição</h2>
    <p ndsPopoverDescription>Ajuste a aparência do conteúdo da página.</p>
  </div>

  <div class="nds-cluster" data-justify="end" data-spacing="sm">
    <!-- Desistiu: a peça de fechar, que reporta close-button -->
    <button ndsPopoverClose ndsButton variant="ghost" size="sm">Cancelar</button>
    <!-- Concluiu: salva e fecha por código, que reporta api -->
    <button ndsButton size="sm" (click)="salvar()">Salvar</button>
  </div>
</ng-template>`;

/** O bloco recuado ao nível em que ele aparece no exemplo. */
function indented(block: string, pad: string): string {
  return block
    .split('\n')
    .map((line) => (line ? pad + line : line))
    .join('\n');
}

/**
 * A raiz controlada com o painel simples — o corpo de `Closed`, `Open` e
 * `Focus`, que só diferem no valor que SEMEIA o sinal.
 *
 * Não é exportada: o `transform` do Storybook chama o construtor com
 * `(código, contexto)`, então quem entra na tabela de transforms tem de ter
 * essa assinatura. Aqui os parâmetros são o estado inicial e o rótulo do
 * gatilho, e os construtores exportados logo abaixo é que os fixam.
 *
 * O rótulo é parâmetro por causa de `Variants/WithTitle`, que renderiza este
 * mesmo painel sob um gatilho próprio ("Configurações de exibição"). Um
 * construtor por story, com o corpo aqui: a alternativa seria um construtor
 * servindo duas stories que NÃO renderizam o mesmo markup, e a premissa da
 * exceção reprovaria — corretamente.
 */
function simpleStateExample(initialOpen: boolean, triggerLabel = 'Abrir popover'): string {
  return `import { signal } from '@angular/core';
import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';

@Component({
  imports: [...NDS_POPOVER, NdsButton],
  template: \`
    <div ndsPopover [(open)]="aberto">
      <button ndsPopoverTrigger ndsButton variant="outline">${triggerLabel}</button>

${indented(SIMPLE_PANEL, '      ')}
    </div>
  \`,
})
export class Exemplo {
  readonly aberto = signal(${initialOpen ? 'true' : 'false'});

  salvar(): void {
    // …persistir…
    this.aberto.set(false);
  }
}`;
}

/**
 * States/Closed e States/Focus — o popover padrão, fechado em repouso.
 *
 * Serve DUAS stories, e a exceção está declarada em `popover.source.test.ts`
 * com a premissa cobrada caso a caso: as duas renderizam o mesmo template e
 * semeiam o mesmo estado inicial. O que as separa é INTERAÇÃO — uma não abre o
 * painel, a outra abre e caminha com Tab entre os controles —, e interação não
 * aparece em snippet. Dois construtores idênticos seriam a cópia que envelhece
 * sozinha.
 *
 * É também o que diferencia `Focus` de `Modal`: aqui o foco ENTRA no painel ao
 * abrir e não fica preso, porque a raiz não declara `modal`. A ausência do
 * input é o que o snippet ensina.
 */
export function popoverBasicSource(): string {
  return simpleStateExample(false);
}

/**
 * States/Open — o painel que NASCE aberto, que é o que a story afirma.
 *
 * Mesmo markup do construtor acima, e a diferença inteira está no sinal:
 * `signal(true)`. Num painel CONTROLADO é ali que o estado inicial mora — o
 * `defaultOpen` ao lado do `[(open)]` seriam duas fontes para a mesma pergunta.
 */
export function popoverOpenSource(): string {
  return simpleStateExample(true);
}

/**
 * States/Controlled — o par `[open]`/`(openChange)` escrito por extenso.
 *
 * É o assunto da story, e por isso o snippet não usa o açúcar `[(open)]` das
 * outras: quem precisa abrir o painel a partir de um comando de fora tem de ver
 * as duas pontas separadas. Ligar só `open` é o defeito clássico — o painel
 * fecha sozinho no Escape e no clique fora, e o estado de fora continua dizendo
 * que está aberto.
 *
 * O parágrafo `data-testid="area-externa"` da story não vem: é alvo inerte para
 * a play clicar fora do painel, e não faz parte do que o modo controlado ensina.
 */
export function popoverControlledSource(): string {
  return `import { signal } from '@angular/core';
import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';

@Component({
  imports: [...NDS_POPOVER, NdsButton],
  template: \`
    <div class="nds-cluster" data-spacing="md">
      <div ndsPopover [open]="aberto()" (openChange)="aberto.set($event)">
        <button ndsPopoverTrigger ndsButton variant="outline">Abrir popover</button>

${indented(SIMPLE_PANEL, '        ')}
      </div>

      <button ndsButton variant="ghost" (click)="aberto.set(!aberto())">
        Alternar por fora
      </button>
    </div>
  \`,
})
export class Exemplo {
  readonly aberto = signal(false);

  salvar(): void {
    // …persistir…
    this.aberto.set(false);
  }
}`;
}

/**
 * States/Modal — `[modal]="true"`, que prende o foco, trava a rolagem e anuncia
 * `aria-modal`, os três juntos.
 *
 * O painel NÃO traz peça de fechar, e a ausência é o assunto: com um
 * `ndsPopoverClose` registrado quem prende o foco passa a ser a lib
 * (`hasPopupClose()`), e o laço de tabulação que o `NdsPopover` escreve — que é
 * o que esta stack de fato entrega — deixaria de ser exercido. São DOIS
 * focáveis pelo mesmo motivo: com um só, "o Tab do último volta ao primeiro"
 * seria verdade sem laço nenhum.
 *
 * E são CHECKBOX com rótulo amarrado por `for`/`id`, não um par
 * Cancelar/Confirmar: sem a peça de fechar, um "Cancelar" não cancelaria nada.
 * Checkbox é o controle que se BASTA — marcar já é o efeito.
 *
 * O `[defaultOpen]="true"` da story fica de fora: ele abre o painel para o axe
 * varrer e o Chromatic fotografar, e um popover modal que nasce aberto prende o
 * foco de quem acabou de chegar na página.
 */
export function popoverModalSource(): string {
  return `import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';
import { NdsCheckbox } from '@/components/ui/checkbox';
import { NdsLabel } from '@/components/ui/label';

@Component({
  imports: [...NDS_POPOVER, NdsButton, NdsCheckbox, NdsLabel],
  template: \`
    <div ndsPopover [modal]="true">
      <button ndsPopoverTrigger ndsButton variant="outline">Abrir modal</button>

      <ng-template ndsPopoverContent>
        <div ndsPopoverHeader>
          <h2 ndsPopoverTitle>Popover modal</h2>
          <p ndsPopoverDescription>O foco fica preso no painel enquanto ele está aberto.</p>
        </div>

        <div class="nds-stack" data-spacing="sm">
          <div class="nds-cluster" data-spacing="sm">
            <button ndsCheckbox id="popover-modal-remember"></button>
            <label ndsLabel for="popover-modal-remember">Lembrar minha escolha</label>
          </div>

          <div class="nds-cluster" data-spacing="sm">
            <button ndsCheckbox id="popover-modal-email"></button>
            <label ndsLabel for="popover-modal-email">Receber aviso por e-mail</label>
          </div>
        </div>
      </ng-template>
    </div>
  \`,
})
export class Exemplo {}`;
}

// ─── As duas VARIANTES que faltavam ──────────────────────────────────────────

/**
 * Variants/Default — o painel de conteúdo LIVRE, e o único sem título.
 *
 * A ausência do título é o assunto, e ela tem consequência de nome acessível:
 * `role="dialog"` sem nome reprova em `aria-dialog-name`, e o painel não herda o
 * nome do gatilho — herdar anunciaria o botão no lugar do painel. Sem
 * `ndsPopoverTitle`, então, o nome se DECLARA por `ariaLabel` no próprio
 * `ndsPopoverContent`. É a contrapartida exata da regra do painel com título,
 * onde `aria-label` junto seriam dois contratos de nome no mesmo painel.
 *
 * Raiz NÃO controlada: sem rodapé de ações, não há nada que precise fechar por
 * código, e um `[(open)]` aqui seria estado sem quem o leia.
 */
export function popoverPlainSource(): string {
  return `import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';

@Component({
  imports: [...NDS_POPOVER, NdsButton],
  template: \`
    <div ndsPopover>
      <button ndsPopoverTrigger ndsButton variant="outline">Ver atalhos</button>

      <!-- Sem título visível, o nome do painel se DECLARA: dialog sem nome
           reprova em aria-dialog-name, e herdar o do gatilho anunciaria o
           botão. -->
      <ng-template ndsPopoverContent ariaLabel="Informações adicionais">
        <p>
          Use <kbd class="nds-kbd">Ctrl</kbd> + <kbd class="nds-kbd">K</kbd> para abrir a
          busca em qualquer tela.
        </p>
      </ng-template>
    </div>
  \`,
})
export class Exemplo {}`;
}

/**
 * Variants/WithTitle — o cabeçalho com título e descrição.
 *
 * Mesmo painel das stories de estado, sob o gatilho próprio da story. O que ele
 * ensina, e o `popoverPlainSource` acima não pode ensinar, é o par
 * `ndsPopoverTitle` + `ndsPopoverDescription`: o primeiro vira `aria-labelledby`
 * e o segundo `aria-describedby`, os dois escritos pela diretiva a partir do
 * markup — por isso não há `aria-label` nenhum aqui.
 */
export function popoverTitledSource(): string {
  return simpleStateExample(false, 'Configurações de exibição');
}

// ─── As quatro COMPOSIÇÕES que faltavam ──────────────────────────────────────

/**
 * Compositions/TableFilter — filtro de listagem, e o contraste entre as duas
 * ações do rodapé.
 *
 * Aqui a diferença de fechamento aparece numa terceira forma, que é o que esta
 * composição tem de próprio: "Aplicar" fecha por CÓDIGO (motivo `api`, quem
 * concluiu) e "Limpar" NÃO FECHA — desmarcar é o efeito inteiro dele, e fechar
 * obrigaria a reabrir o painel para continuar filtrando. Nenhum dos dois é
 * `ndsPopoverClose`: o rodapé do filtro não tem o caminho de quem desistiu, que
 * ali é o Escape e o clique fora.
 *
 * O `limpar()` existe no snippet e não na story: lá os checkboxes são estado do
 * próprio controle e não há o que limpar, aqui quem copia precisa ver que a ação
 * age sem fechar. O que a story renderiza e o snippet ensina é a mesma FORMA de
 * rodapé; o corpo do método é o que a story não tinha como ter.
 */
export function popoverTableFilterSource(): string {
  return `import { signal } from '@angular/core';
import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';
import { NdsCheckbox } from '@/components/ui/checkbox';
import { NdsLabel } from '@/components/ui/label';

@Component({
  imports: [...NDS_POPOVER, NdsButton, NdsCheckbox, NdsLabel],
  template: \`
    <div ndsPopover [(open)]="aberto">
      <button ndsPopoverTrigger ndsButton variant="outline">Filtros</button>

      <ng-template ndsPopoverContent>
        <div ndsPopoverHeader>
          <h2 ndsPopoverTitle>Filtrar por status</h2>
          <p ndsPopoverDescription>Combine quantos status quiser na listagem.</p>
        </div>

        <div class="nds-stack" data-spacing="sm">
          <div class="nds-cluster" data-spacing="sm">
            <button ndsCheckbox id="filtro-ativo"></button>
            <label ndsLabel for="filtro-ativo">Ativo</label>
          </div>

          <div class="nds-cluster" data-spacing="sm">
            <button ndsCheckbox id="filtro-pendente"></button>
            <label ndsLabel for="filtro-pendente">Pendente</label>
          </div>

          <div class="nds-cluster" data-spacing="sm">
            <button ndsCheckbox id="filtro-arquivado"></button>
            <label ndsLabel for="filtro-arquivado">Arquivado</label>
          </div>
        </div>

        <div class="nds-cluster" data-justify="end" data-spacing="sm">
          <!-- Limpar age e NÃO fecha: filtro é escolha múltipla, e fechar aqui
               obrigaria a reabrir o painel para continuar filtrando. -->
          <button ndsButton variant="ghost" size="sm" (click)="limpar()">Limpar</button>
          <!-- Concluiu: aplica e fecha por código, que reporta api -->
          <button ndsButton size="sm" (click)="aplicar()">Aplicar</button>
        </div>
      </ng-template>
    </div>
  \`,
})
export class Exemplo {
  readonly aberto = signal(false);

  limpar(): void {
    // …desmarcar os status; o painel segue aberto…
  }

  aplicar(): void {
    // …aplicar o filtro à listagem…
    this.aberto.set(false);
  }
}`;
}

/**
 * Compositions/ColorPicker — a grade de amostras.
 *
 * Duas regras moram aqui, e as duas são do design system, não do popover.
 *
 * A COR vem de token do tema (`nds-bg-primary`, `nds-bg-success`, …) e nunca de
 * hexadecimal: amostra escrita em hex sai do tema na primeira troca de marca, e
 * um `style="background:#…"` ainda venceria a folha. É por isso que a grade é
 * escrita amostra a amostra, e não por laço com classe interpolada — classe
 * montada em runtime não é alcançável por quem lê o snippet nem pelo portão.
 *
 * O NOME de cada amostra é declarado: um botão que só tem cor chega ao leitor de
 * tela sem nome nenhum, e quem não distingue a cor não tem outra informação. O
 * `aria-label` é o nome, e a cor é a decoração.
 */
export function popoverColorPickerSource(): string {
  return `import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';

@Component({
  imports: [...NDS_POPOVER, NdsButton],
  template: \`
    <div ndsPopover>
      <button ndsPopoverTrigger ndsButton variant="outline">Escolher cor da etiqueta</button>

      <ng-template ndsPopoverContent>
        <div ndsPopoverHeader>
          <h2 ndsPopoverTitle>Cor da etiqueta</h2>
          <p ndsPopoverDescription>Escolha uma cor da paleta do tema.</p>
        </div>

        <!-- A cor sai de TOKEN do tema: hexadecimal aqui sairia do tema na
             primeira troca de marca. E cada amostra declara o nome — cor
             sozinha chega ao leitor de tela como botão sem nome. -->
        <div class="nds-cluster" data-spacing="sm">
          <button
            type="button"
            class="nds-size-8 nds-rounded-full nds-bg-primary nds-border-soft nds-focus-ring"
            aria-label="Primária"
          ></button>
          <button
            type="button"
            class="nds-size-8 nds-rounded-full nds-bg-secondary nds-border-soft nds-focus-ring"
            aria-label="Secundária"
          ></button>
          <button
            type="button"
            class="nds-size-8 nds-rounded-full nds-bg-success nds-border-soft nds-focus-ring"
            aria-label="Sucesso"
          ></button>
          <button
            type="button"
            class="nds-size-8 nds-rounded-full nds-bg-warning nds-border-soft nds-focus-ring"
            aria-label="Atenção"
          ></button>
          <button
            type="button"
            class="nds-size-8 nds-rounded-full nds-bg-info nds-border-soft nds-focus-ring"
            aria-label="Informação"
          ></button>
          <button
            type="button"
            class="nds-size-8 nds-rounded-full nds-bg-destructive nds-border-soft nds-focus-ring"
            aria-label="Destrutiva"
          ></button>
        </div>
      </ng-template>
    </div>
  \`,
})
export class Exemplo {}`;
}

/**
 * Compositions/QuickSettings — os alternadores.
 *
 * O que esta composição tem de próprio é a INDEPENDÊNCIA: cada linha vale por
 * si, marcar uma não mexe nas outras, e por isso não há rodapé de confirmação —
 * marcar já é o efeito. Um par Cancelar/Salvar aqui prometeria uma transação que
 * não existe.
 *
 * Rótulo à esquerda e controle à direita (`data-justify="between"`), amarrados
 * por `for`/`id`: é o que faz o clique no texto alternar a preferência, e o que
 * dá nome ao controle.
 */
export function popoverQuickSettingsSource(): string {
  return `import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';
import { NdsCheckbox } from '@/components/ui/checkbox';
import { NdsLabel } from '@/components/ui/label';

@Component({
  imports: [...NDS_POPOVER, NdsButton, NdsCheckbox, NdsLabel],
  template: \`
    <div ndsPopover>
      <button ndsPopoverTrigger ndsButton variant="outline">Configurações rápidas</button>

      <ng-template ndsPopoverContent>
        <div ndsPopoverHeader>
          <h2 ndsPopoverTitle>Preferências</h2>
          <p ndsPopoverDescription>Cada linha vale por si — nada aqui depende do resto.</p>
        </div>

        <!-- Sem rodapé de confirmação: marcar já é o efeito, e um par
             Cancelar/Salvar prometeria uma transação que não existe. -->
        <div class="nds-stack" data-spacing="sm">
          <div class="nds-cluster" data-justify="between">
            <label ndsLabel for="preferencia-notificacoes">Notificações</label>
            <button ndsCheckbox id="preferencia-notificacoes" [checked]="true"></button>
          </div>

          <div class="nds-cluster" data-justify="between">
            <label ndsLabel for="preferencia-escuro">Modo escuro</label>
            <button ndsCheckbox id="preferencia-escuro"></button>
          </div>

          <div class="nds-cluster" data-justify="between">
            <label ndsLabel for="preferencia-compacto">Modo compacto</label>
            <button ndsCheckbox id="preferencia-compacto"></button>
          </div>
        </div>
      </ng-template>
    </div>
  \`,
})
export class Exemplo {}`;
}

/**
 * Compositions/SideTop — o lado de abertura pedido por atributo.
 *
 * O assunto é o par `side="top"` + `[sideOffset]="12"`: a posição é união de
 * strings e vai como atributo, a distância é número e vai como binding —
 * escrita `sideOffset="12"` ela chegaria à diretiva como a STRING "12".
 *
 * O irmão que cria o espaço acima do gatilho NÃO entra, nem o embrulho que o
 * segura. Ele existe para que o auto-flip não aconteça enquanto a play mede o
 * lado pedido: é arranjo do QUADRO da story, e ensiná-lo faria quem copia achar
 * que o popover precisa de um espaçador para abrir acima. Precisa de espaço —
 * e, se não houver, vira sozinho, que é o contrato C9.
 */
export function popoverSideTopSource(): string {
  return `import { NDS_POPOVER } from '@/components/ui/popover';
import { NdsButton } from '@/components/ui/button';

@Component({
  imports: [...NDS_POPOVER, NdsButton],
  template: \`
    <div ndsPopover>
      <button ndsPopoverTrigger ndsButton variant="outline">Abrir acima</button>

      <!-- A posição é atributo e a distância é binding: escrita
           sideOffset="12" ela chegaria à diretiva como a string "12". -->
      <ng-template ndsPopoverContent side="top" [sideOffset]="12">
        <div ndsPopoverHeader>
          <h2 ndsPopoverTitle>Ancorado acima</h2>
          <p ndsPopoverDescription>
            Sem espaço acima, o painel vira para baixo sozinho.
          </p>
        </div>
      </ng-template>
    </div>
  \`,
})
export class Exemplo {}`;
}

// nortear-design-system-react/src/components/ui/popover.source.ts
/**
 * Transforms do painel Code do Popover.
 *
 * Módulo de TS puro — o `.tsx` só entra por `import type`, que o compilador
 * apaga. É o que deixa as funções rodarem no projeto `unit` do vitest, a única
 * guarda que elas têm: a saída do painel não chega ao DOM durante a `play`.
 *
 * O que as stories montam em volta — `contain: layout`, `minHeight`,
 * `position: relative`, o parágrafo "Área externa", a chave de remontagem — é
 * andaime: o painel é portalizado e precisa de um quadro contra o que se
 * posicionar dentro do Storybook, e a dispensa por clique fora precisa de um
 * alvo inerte para não depender da geometria da página. Nada disso é do
 * componente, e por isso nada disso entra no snippet.
 *
 * O gatilho entra sempre com `asChild` sobre um `<Button>`: o gatilho não é um
 * invólucro, é o botão que JÁ existe na interface recebendo as props de
 * abertura. É isso que mantém um só elemento focável e um só nome acessível.
 */
import {
  attrs,
  attrsMultilinha,
  jsxSnippet,
  propBool,
  propNumber,
  propOption,
  type SourceTransform,
} from '@/lib/story-source';

export type PopoverArgs = {
  side: 'top' | 'right' | 'bottom' | 'left';
  align: 'start' | 'center' | 'end';
  sideOffset: number;
  defaultOpen: boolean;
  modal: boolean;
};

const LADOS = ['top', 'right', 'bottom', 'left'] as const;
const ALINHAMENTOS = ['start', 'center', 'end'] as const;

/** Distância padrão entre gatilho e painel, em px. */
const DISTANCIA_DEFAULT = 4;

const IMPORT_BUTTON = 'import { Button } from "@/components/ui/button";';

const IMPORT_CHECKBOX = 'import { Checkbox } from "@/components/ui/checkbox";';

/**
 * O import do estado. Sai daqui e não de cada construtor porque agora são
 * CINCO os snippets que fecham por código, e um `useState` sem import chega a
 * quem copiou como `useState is not defined` — o mesmo defeito do nome elidido,
 * uma linha acima.
 */
const IMPORT_USE_STATE = 'import { useState } from "react";';

/** Bloco de import do componente, em ordem alfabética das peças usadas. */
function importingPopover(...parts: string[]): string {
  const list = [...parts].sort();
  return `import {\n${list
    .map((part) => `  ${part},`)
    .join('\n')}\n} from "@/components/ui/popover";`;
}

/** Gatilho: o botão de verdade da interface, com as props emprestadas. */
function trigger(label: string): string {
  return `  <PopoverTrigger asChild>
    <Button variant="outline">${label}</Button>
  </PopoverTrigger>`;
}

/**
 * Cabeçalho nomeado. Com `PopoverTitle` a lib monta o `aria-labelledby`
 * sozinha — e `role="dialog"` sem nome reprova na regra `aria-dialog-name`.
 */
function header(title: string, descricao?: string): string {
  const lineDescription = descricao
    ? `\n      <PopoverDescription>\n        ${descricao}\n      </PopoverDescription>`
    : '';
  return `    <PopoverHeader>
      <PopoverTitle>${title}</PopoverTitle>${lineDescription}
    </PopoverHeader>`;
}

/** A composição inteira: raiz, gatilho e painel. */
function popover(root: string, gatilhoRotulo: string, panel: string, content: string): string {
  return `<Popover${root}>
${trigger(gatilhoRotulo)}
  <PopoverContent${panel}>
${content}
  </PopoverContent>
</Popover>`;
}

/**
 * Par de ações do rodapé do painel, encostado à direita.
 *
 * As duas FECHAM, e por CAMINHOS diferentes — é o snippet que ensina isso, e
 * por isso ele carrega o `onClick` em vez de dois `PopoverClose`:
 *
 *   Cancelar → `PopoverClose`, motivo `close-button` — desistiu
 *   Salvar   → código, depois de salvar, motivo `api` — concluiu
 *
 * Um "Cancelar" que não fecha é botão que promete saída e não entrega — foi o
 * defeito que a dona viu na tela em 2026-09-12. Um "Salvar" que fecha COMO
 * peça de fechar é o defeito seguinte, e mais silencioso: o painel some do
 * mesmo jeito, e os dois desfechos chegam ao relatório com o mesmo motivo.
 */
const ACTIONS_DEFAULT = `    <div className="nds-cluster" data-justify="end" data-spacing="sm">
      <PopoverClose asChild>
        <Button variant="ghost" size="sm">Cancelar</Button>
      </PopoverClose>
      <Button size="sm" onClick={() => { salvar(); setOpen(false); }}>Salvar</Button>
    </div>`;

/**
 * Abertura do `<form>` do painel, com o fechamento já no lugar certo.
 *
 * O fechamento vai no `onSubmit`, DEPOIS do `preventDefault`, e nunca no
 * `onClick` do botão que confirma. Dois motivos, e os dois são do formulário:
 *
 *   1. fechar no clique DESMONTA o formulário antes de ele submeter — o
 *      "salvar" nunca acontece;
 *   2. só o caminho do `submit` cobre também o Enter num campo, que é como
 *      metade das pessoas envia formulário.
 *
 * E fecha por CÓDIGO, motivo `api`: envolver o confirmar num `PopoverClose`
 * faria "concluiu" chegar ao relatório como "apertou o botão de fechar".
 */
const FORM_ABERTURA = `    <form
      className="nds-stack"
      data-spacing="sm"
      onSubmit={(e) => {
        // Fechar no \`onClick\` do botão desmontaria o formulário antes do
        // submit, e deixaria de fora o Enter num campo.
        e.preventDefault();
        salvar();
        setOpen(false);
      }}
    >`;

/**
 * Estado do painel e o nome da ação que ele conclui.
 *
 * A base-ui não tem fechamento imperativo: quem fecha por código é o estado de
 * quem compõe, então TODO painel cuja ação primária fecha é CONTROLADO — a
 * mesma forma do Playground desta stack.
 *
 * Até 2026-09-13 só os dois snippets de formulário liam isso; os outros três
 * imprimiam `<Popover>` cru e um rodapé que chamava `setOpen(false)`, ou seja
 * ensinavam exatamente o Salvar inerte que esta campanha existiu para
 * consertar. Um construtor por vez é como o defeito volta: o par mora aqui.
 *
 * E a ação entra DECLARADA porque o snippet é para copiar: manipulador em
 * linha não tem passe na varredura de snippets, e um nome elidido chega a quem
 * copiou como `salvar is not defined` na primeira renderização.
 */
function controlledPreamble(action: string, note: string, initiallyOpen = false): string {
  return `const [open, setOpen] = useState(${initiallyOpen});

function ${action}() {
  // …${note}…
}`;
}

const FORM_PREAMBULO = controlledPreamble('salvar', 'grave o formulário');

/** Raiz controlada — o par que deixa o \`setOpen\` do submit ter efeito. */
const RAIZ_CONTROLADA = ' open={open} onOpenChange={setOpen}';

/**
 * Transform do `meta` — vale para todas as stories do arquivo. Lê os controls do
 * Playground; nas stories sem args cai no painel fechado, que é o padrão do
 * componente e o uso canônico. Só o que difere do padrão entra no snippet.
 *
 * O espião de `onOpenChange` NÃO é interpolado: o Storybook o entrega como
 * função, e o corpo do mock apareceria no painel como se fosse código do design
 * system. O `onOpenChange` que o snippet imprime é o do ESTADO — `setOpen` —, e
 * é sempre esse, venha o control como vier.
 *
 * `defaultOpen` do control vira o valor INICIAL do estado, e não prop da raiz.
 * A raiz é controlada porque o Salvar do rodapé fecha por código, e numa raiz
 * controlada `defaultOpen` é prop morta — a lib lê `open`. Imprimir os dois
 * juntos ensinaria um controle que não controla nada. É a mesma decisão da
 * story ao lado, que faz `useState(Boolean(defaultOpen))`.
 */
export const popoverSource: SourceTransform<PopoverArgs> = (_gerado, ctx) => {
  const args = ctx?.args ?? {};
  const root = RAIZ_CONTROLADA + attrs(propBool('modal', args.modal));
  const panel = attrsMultilinha([
    propOption('side', args.side, LADOS, 'bottom'),
    propOption('align', args.align, ALINHAMENTOS, 'center'),
    typeof args.sideOffset === 'number' && args.sideOffset !== DISTANCIA_DEFAULT
      ? propNumber('sideOffset', args.sideOffset)
      : undefined,
  ]);

  return jsxSnippet(
    `${IMPORT_USE_STATE}
${importingPopover(
  'Popover',
  'PopoverClose',
  'PopoverContent',
  'PopoverDescription',
  'PopoverHeader',
  'PopoverTitle',
  'PopoverTrigger',
)}
${IMPORT_BUTTON}

${controlledPreamble('salvar', 'grave o que o painel ajustou', args.defaultOpen === true)}`,
    popover(
      root,
      'Abrir popover',
      panel,
      `${header('Configurações de exibição', 'Ajuste a aparência do conteúdo da página.')}
${ACTIONS_DEFAULT}`,
    ),
  );
};

/**
 * O controle de fechar por dentro do painel.
 *
 * `PopoverClose` e não `onClick={() => setAberto(false)}`: o que separa os dois
 * é o MOTIVO que chega ao `onOpenChange` — a peça fecha com `close-press`, que o
 * design system lê como `close-button`, e o estado escrito à mão fecha por
 * código, que é `api`. Trocar um pelo outro apaga do relatório a diferença
 * entre desistiu e concluiu.
 *
 * O painel da story mostra o motivo num parágrafo ao lado; aquilo é andaime de
 * demonstração e não entra aqui, pela mesma razão do resto do quadro.
 *
 * A raiz é CONTROLADA e nasce aberta pelo estado inicial, e não por
 * `defaultOpen`: o Salvar deste rodapé é justamente o ramo que fecha por
 * código, e sem o par `open`/`onOpenChange` ele seria um botão inerte — que é o
 * defeito que a story ao lado existe para separar do outro ramo.
 */
export function popoverCloseSource(): string {
  return jsxSnippet(
    `${IMPORT_USE_STATE}
${importingPopover(
  'Popover',
  'PopoverClose',
  'PopoverContent',
  'PopoverDescription',
  'PopoverHeader',
  'PopoverTitle',
  'PopoverTrigger',
)}
${IMPORT_BUTTON}

${controlledPreamble('salvar', 'grave o que o painel ajustou', true)}`,
    popover(
      RAIZ_CONTROLADA,
      'Abrir popover',
      '',
      `${header('Configurações de exibição', 'Ajuste a aparência do conteúdo da página.')}
${ACTIONS_DEFAULT}`,
    ),
  );
}

/**
 * Conteúdo livre — a ausência de título é o assunto, e o `aria-label` é a
 * resposta: sem `PopoverTitle` o nome do painel se DECLARA, em vez de cair na
 * herança do rótulo do gatilho. Um `role="dialog"` anônimo reprovaria no axe, e
 * um nomeado pelo botão anuncia a porta em vez do que há atrás dela.
 */
export function popoverContentLivreSource(): string {
  return jsxSnippet(
    `${importingPopover('Popover', 'PopoverContent', 'PopoverTrigger')}
${IMPORT_BUTTON}`,
    popover(
      '',
      'Ver atalhos',
      ' aria-label="Informações adicionais"',
      `    <p>
      Use Ctrl+K para abrir a busca em qualquer tela.
    </p>`,
    ),
  );
}

/**
 * Formulário curto dentro do painel. É o que separa popover de tooltip: o
 * conteúdo é interativo, então o foco entra nele ao abrir e o Tab caminha pelos
 * campos sem sair do painel.
 *
 * O fechamento vive no `onSubmit`, depois do `preventDefault` — nunca no
 * `onClick` do botão: ver `FORM_ABERTURA`.
 */
export function popoverFormSource(): string {
  return jsxSnippet(
    `${IMPORT_USE_STATE}
${importingPopover(
  'Popover',
  'PopoverContent',
  'PopoverHeader',
  'PopoverTitle',
  'PopoverTrigger',
)}
${IMPORT_BUTTON}
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

${FORM_PREAMBULO}`,
    popover(
      RAIZ_CONTROLADA,
      'Editar perfil',
      '',
      `${header('Editar perfil')}
${FORM_ABERTURA}
      <Label htmlFor="perfil-nome" className="nds-text-caption">Nome</Label>
      <Input id="perfil-nome" defaultValue="Joana" />
      <Label htmlFor="perfil-email" className="nds-text-caption">Email</Label>
      <Input id="perfil-email" type="email" defaultValue="joana@example.com" />
      <Button type="submit" size="sm" className="nds-mt-1">Atualizar</Button>
    </form>`,
    ),
  );
}

/**
 * Aberto por estado inicial. Enquanto aberto, o gatilho aponta para o painel por
 * `aria-controls` — e o painel só existe no DOM nesse intervalo, o que é
 * justamente o estado que a regressão visual precisa alcançar.
 */
export function popoverOpenSource(): string {
  return jsxSnippet(
    `${importingPopover(
      'Popover',
      'PopoverContent',
      'PopoverDescription',
      'PopoverHeader',
      'PopoverTitle',
      'PopoverTrigger',
    )}
${IMPORT_BUTTON}`,
    popover(
      ' defaultOpen',
      'Abrir popover',
      '',
      header('Configurações de exibição', 'Ajuste a aparência do conteúdo da página.'),
    ),
  );
}

/**
 * Controlado de fora. Dois botões, e não um que alterna: o `pointerdown` do
 * clique fora dispensa o painel ANTES do `click`, então um alternador leria o
 * estado já invertido pela lib e reabriria o que acabou de fechar.
 */
export function popoverControlledSource(): string {
  return jsxSnippet(
    `${IMPORT_USE_STATE}
${importingPopover(
  'Popover',
  'PopoverContent',
  'PopoverDescription',
  'PopoverHeader',
  'PopoverTitle',
  'PopoverTrigger',
)}
${IMPORT_BUTTON}

const [aberto, setAberto] = useState(false);`,
    `<div className="nds-stack" data-spacing="sm">
  <div className="nds-cluster" data-spacing="md">
    <Button onClick={() => setAberto(true)}>Abrir externamente</Button>
    <Button variant="outline" onClick={() => setAberto(false)}>
      Fechar externamente
    </Button>
  </div>

  <Popover open={aberto} onOpenChange={setAberto}>
    <PopoverTrigger asChild>
      <Button variant="outline">Preferências</Button>
    </PopoverTrigger>
    <PopoverContent>
      <PopoverHeader>
        <PopoverTitle>Estado controlado</PopoverTitle>
        <PopoverDescription>
          A abertura vive fora do componente.
        </PopoverDescription>
      </PopoverHeader>
    </PopoverContent>
  </Popover>
</div>`,
  );
}

/**
 * Modal: prende o foco no painel, trava a rolagem da página e anuncia
 * `aria-modal`. Os três juntos — anunciar que o resto da página está inerte sem
 * prender o foco engana quem navega por leitor de tela.
 *
 * A prisão é NOSSA e não da lib. O gerenciador de foco do Base UI só trapeia com
 * `modal !== false && hasClosePart`, e `hasClosePart` conta os `Popover.Close`
 * registrados dentro do painel; da lib vem a trava de rolagem, que cai de
 * `modal === true` sozinho. O laço de tabulação está no `PopoverContent` de
 * `popover.tsx`, na mesma forma do Vanilla, que é a referência.
 *
 * Por isso este é o ÚNICO painel sem `PopoverClose` — e a ausência é o assunto:
 * é ela que deixa o painel modal depender do nosso laço, que é o caso que o
 * contrato precisa cobrir. Com um controle de fechar aqui, quem trapearia seria
 * a lib, e a story mediria a lib.
 *
 * E por isso o conteúdo é uma LISTA DE OPÇÕES, não um rodapé de ações. Até
 * 2026-09-13 este snippet imprimia um par Cancelar/OK que existia só para haver
 * dois focáveis — nenhum dos dois podia fechar, porque um controle de fechar
 * registrado entregaria a prisão de foco à lib. Botão que promete ação e não
 * entrega é defeito, e um exemplo publicado o ensina. A caixa de marcação se
 * basta: marcar JÁ é o efeito, e ela continua sendo o segundo focável que prova
 * o laço — com um só, "o Tab do último volta ao primeiro" seria verdade sem laço
 * nenhum, porque primeiro e último seriam o mesmo elemento.
 */
export function popoverModalSource(): string {
  const option = (id: string, label: string) => `      <div className="nds-cluster" data-spacing="sm">
        <Checkbox id="${id}" />
        <label htmlFor="${id}" className="nds-label">
          ${label}
        </label>
      </div>`;

  return jsxSnippet(
    `${importingPopover(
      'Popover',
      'PopoverContent',
      'PopoverDescription',
      'PopoverHeader',
      'PopoverTitle',
      'PopoverTrigger',
    )}
${IMPORT_BUTTON}
${IMPORT_CHECKBOX}`,
    popover(
      ' defaultOpen modal',
      'Abrir modal',
      '',
      `${header('Popover modal', 'O foco fica preso no painel enquanto ele está aberto.')}
    <div className="nds-stack nds-pt-1" data-spacing="sm">
${option('lembrar-escolha', 'Lembrar minha escolha')}
${option('aviso-email', 'Receber aviso por e-mail')}
    </div>`,
    ),
  );
}

/**
 * Edição rápida sem trocar de tela. O gatilho nomeia a ação E o objeto —
 * "Editar perfil", nunca "Mais" ou "Clique aqui" —, porque é o nome do gatilho
 * que a pessoa ouve antes de decidir abrir.
 *
 * Só "Cancelar" é `PopoverClose`. "Atualizar" é o submit DO formulário: fora do
 * `<form>` ele ficaria inerte e o Enter num campo não dispararia nada — que é o
 * gesto de quem acabou de digitar. Fechar por dentro sem salvar é papel do
 * descarte.
 *
 * E quem fecha ao salvar é o `onSubmit`, não o clique do "Atualizar" — o motivo
 * está em `FORM_ABERTURA`.
 */
export function popoverEditarPerfilSource(): string {
  return jsxSnippet(
    `${IMPORT_USE_STATE}
${importingPopover(
  'Popover',
  'PopoverClose',
  'PopoverContent',
  'PopoverDescription',
  'PopoverHeader',
  'PopoverTitle',
  'PopoverTrigger',
)}
${IMPORT_BUTTON}
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

${FORM_PREAMBULO}`,
    popover(
      RAIZ_CONTROLADA,
      'Editar perfil',
      '',
      `${header('Editar perfil', 'Altere o nome e o email da conta.')}
${FORM_ABERTURA}
      <Label htmlFor="conta-nome" className="nds-text-caption">Nome</Label>
      <Input id="conta-nome" defaultValue="Ana Ribeiro" />
      <Label htmlFor="conta-email" className="nds-text-caption">Email</Label>
      <Input id="conta-email" type="email" defaultValue="ana@nortear.com.br" />
      <div className="nds-cluster" data-justify="end" data-spacing="sm">
        <PopoverClose asChild>
          <Button variant="ghost" size="sm">Cancelar</Button>
        </PopoverClose>
        <Button type="submit" size="sm">Atualizar</Button>
      </div>
    </form>`,
    ),
  );
}

/**
 * Filtros combináveis. Escolha múltipla não fecha no primeiro clique — fechar
 * obrigaria a reabrir o painel para cada critério —, e o par Limpar / Aplicar
 * fica no fim, na ordem em que a decisão acontece.
 *
 * Só "Aplicar" fecha, e fecha por CÓDIGO: aplicar É a decisão, e depois dela o
 * painel não tem mais o que oferecer. "Limpar" desmarca e devolve a escolha a
 * quem está decidindo — fechar ali seria tirar o painel de quem acabou de pedir
 * para recomeçar.
 *
 * Era `PopoverClose` até 2026-09-13, e por isso este snippet não importa mais a
 * peça: aplicar é "concluiu", e a peça de fechar reporta "desistiu".
 *
 * Trocada a peça por código, a raiz TEM de ser controlada — foi o degrau que
 * ficou para trás na mesma rodada, e por meio dia este snippet ensinou um
 * Aplicar que não fechava nada.
 */
export function popoverFilterSource(): string {
  const opcao = (label: string, marcada = false) => `      <label className="nds-cluster" data-spacing="sm">
        <input type="checkbox" className="nds-size-4"${marcada ? ' defaultChecked' : ''} />
        <span>${label}</span>
      </label>`;

  return jsxSnippet(
    `${IMPORT_USE_STATE}
${importingPopover(
  'Popover',
  'PopoverContent',
  'PopoverDescription',
  'PopoverHeader',
  'PopoverTitle',
  'PopoverTrigger',
)}
${IMPORT_BUTTON}

${controlledPreamble('aplicar', 'aplique os filtros à listagem')}`,
    popover(
      RAIZ_CONTROLADA,
      'Filtros',
      '',
      `${header('Filtrar por status', 'Combine quantos status quiser na listagem.')}
    <div className="nds-stack nds-text-body" data-spacing="xs">
${opcao('Ativo', true)}
${opcao('Pendente')}
${opcao('Arquivado')}
    </div>
    <div className="nds-cluster" data-justify="end" data-spacing="sm">
      <Button variant="ghost" size="sm">Limpar</Button>
      <Button size="sm" onClick={() => { aplicar(); setOpen(false); }}>Aplicar</Button>
    </div>`,
    ),
  );
}

/**
 * Paleta restrita. A cor NÃO é o nome: cada amostra carrega o próprio
 * `aria-label`, porque quem não distingue a cor precisa do rótulo — e um botão
 * sem texto nenhum reprova no axe por `button-name`.
 */
export function popoverPaletteSource(): string {
  const amostra = (token: string, label: string) =>
    `      <button type="button" className={\`\${AMOSTRA} nds-bg-${token}\`} aria-label="${label}" />`;

  return jsxSnippet(
    `${importingPopover(
      'Popover',
      'PopoverContent',
      'PopoverDescription',
      'PopoverHeader',
      'PopoverTitle',
      'PopoverTrigger',
    )}
${IMPORT_BUTTON}

const AMOSTRA = "nds-size-8 nds-rounded-full nds-border-soft nds-focus-ring";`,
    popover(
      '',
      'Escolher cor da etiqueta',
      '',
      `${header('Cor da etiqueta', 'Escolha uma cor da paleta do tema.')}
    <div className="nds-cluster" data-spacing="sm">
${amostra('primary', 'Primária')}
${amostra('secondary', 'Secundária')}
${amostra('success', 'Sucesso')}
${amostra('warning', 'Atenção')}
${amostra('info', 'Informação')}
${amostra('destructive', 'Destrutiva')}
    </div>`,
    ),
  );
}

/**
 * Preferências booleanas independentes — alternativa leve ao diálogo para
 * ajustes rápidos. Cada linha vale por si: marcar uma não mexe nas outras, e é
 * por isso que são caixas de marcação e não um grupo de escolha única.
 */
export function popoverPreferenciasSource(): string {
  const preferencia = (label: string, ligada = false) => `      <label
        className="nds-cluster"
        data-align="center"
        data-justify="between"
      >
        <span>${label}</span>
        <input type="checkbox" className="nds-size-4"${ligada ? ' defaultChecked' : ''} />
      </label>`;

  return jsxSnippet(
    `${importingPopover(
      'Popover',
      'PopoverContent',
      'PopoverDescription',
      'PopoverHeader',
      'PopoverTitle',
      'PopoverTrigger',
    )}
${IMPORT_BUTTON}`,
    popover(
      '',
      'Configurações rápidas',
      '',
      `${header('Preferências', 'Cada linha vale por si — nada aqui depende do resto.')}
    <div className="nds-stack nds-text-body" data-spacing="sm">
${preferencia('Notificações', true)}
${preferencia('Modo escuro')}
${preferencia('Modo compacto')}
    </div>`,
    ),
  );
}

/**
 * Ancorado acima. `side` é preferência, não garantia: sem espaço acima o painel
 * vira para baixo sozinho — a troca é sempre de LADO no mesmo eixo, nunca de
 * eixo. `sideOffset` é a distância entre o gatilho e o painel.
 */
export function popoverAboveSource(): string {
  return jsxSnippet(
    `${importingPopover(
      'Popover',
      'PopoverContent',
      'PopoverDescription',
      'PopoverHeader',
      'PopoverTitle',
      'PopoverTrigger',
    )}
${IMPORT_BUTTON}`,
    popover(
      '',
      'Abrir acima',
      ' side="top" sideOffset={12}',
      header('Ancorado acima', 'Sem espaço acima, o painel vira para baixo sozinho.'),
    ),
  );
}
