// nortear-design-system-angular/src/components/ui/sheet.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  Directive,
  TemplateRef,
  ViewEncapsulation,
  computed,
  contentChild,
  effect,
  inject,
  input,
  isDevMode,
  untracked,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import {
  RdxDialogRoot,
  RdxDialogTrigger,
  RdxDialogPortal,
  RdxDialogBackdrop,
  RdxDialogPopup,
  RdxDialogTitle,
  RdxDialogDescription,
  RdxDialogClose,
} from '@radix-ng/primitives/dialog';
import { NdsButton, NdsButtonIcon } from '@/components/ui/button';
import { cn } from '@/lib/utils';

// ─── Sheet ────────────────────────────────────────────────────────────────────
//
// Visual: classes .nds-sheet-* (docs/shared/styles/nds/sheet.css), o mesmo
// conjunto que o Vanilla — referência de markup — escreve à mão.
//
// Decisão de acessibilidade do Sheet — bloco canônico no sheet.ts do Vanilla.
// Em resumo: painel modal que entra pela borda, com role="dialog",
// aria-modal="true", foco preso, foco devolvido ao gatilho no fecho, Escape e
// clique no véu fechando, rolagem da página travada, corpo rolável com papel e
// nome, e NENHUMA região viva.
//
// O mecanismo desta stack, medido em node_modules: o RdxDialogPopup liga
// [attr.aria-modal] a modal() === true e aria-labelledby/aria-describedby aos
// ids que as diretivas de título e descrição registram; a dispensa é escapeKey
// sempre ligado mais outsidePress restrito ao diálogo mais profundo; o
// gerenciador de foco é dono do alvo de retorno e sobrevive à animação de
// saída. É a lista logo abaixo, item por item.
//
// COM os primitivos de Dialog do Radix NG, porque o Sheet É um Dialog com
// posicionamento lateral e a parte difícil dele não é o CSS. O que o primitivo
// entrega, e que se escreve errado à mão:
//
//   · `role="dialog"` + `aria-modal="true"` no painel;
//   · `aria-labelledby` / `aria-describedby` ligados aos ids REAIS do título e
//     da descrição — as diretivas de título/descrição registram o próprio id no
//     contexto da raiz, então o painel nunca aponta para um id que não existe;
//   · foco preso enquanto aberto e devolvido ao gatilho ao fechar (o gerenciador
//     sobrevive à animação de saída, senão o foco voltaria antes da hora);
//   · Escape e clique fora fecham, com o dialog mais profundo primeiro;
//   · trava de rolagem da página e `inert` nos irmãos enquanto modal;
//   · portal para o `document.body` com desmontagem só depois da transição de
//     saída — é o que dá o que animar no fechamento;
//   · `data-starting-style` / `data-ending-style`, exatamente os ganchos que o
//     CSS compartilhado usa para animar entrada e saída.
//
// O que o primitivo NÃO entrega é `data-state="open|closed"`: o Radix NG segue a
// convenção do Base UI (`data-open` / `data-closed`). Emitimos os dois — o par
// do primitivo, que o CSS lê, e o `data-state`, que o conteúdo compartilhado
// documenta na tabela de estados e que Vue e Svelte também emitem.
//
// ─── Forma da API ─────────────────────────────────────────────────────────────
//
// O painel é renderizado por PORTAL, fora da posição em que quem consome o
// escreveu. Em Angular isso obriga o conteúdo a viver num `<ng-template>`: o
// `rdxDialogPortal` é diretiva estrutural e o portal precisa de dois nós raiz
// (backdrop + painel). Daí a forma:
//
//   <nds-sheet>
//     <button ndsSheetTrigger ndsButton variant="outline">Abrir</button>
//     <ng-template ndsSheetContent side="right">…</ng-template>
//   </nds-sheet>
//
// O gatilho fica onde foi escrito (uma `<ng-content />` só, sem ramo de `@if` —
// duas destinações de projeção não entregariam conteúdo a nenhuma das duas), e o
// conteúdo do painel entra pelo `ngTemplateOutlet` dentro do portal.

/** Borda de onde o painel desliza. */
export type SheetSide = 'top' | 'right' | 'bottom' | 'left';

// A tradução do motivo mora em `./sheet-close-reason`, e é reexportada aqui para
// quem compõe continuar importando tudo de um lugar só. O arquivo é separado
// porque a função é PURA e precisa ser testável em node: um teste unitário que
// importasse ESTE módulo carregaria `@Component`/`@Directive` fora do compilador
// do Angular, e era por isso que esta stack era a única das cinco sem teste do
// mapeador. Mesma forma do `dialog-close-reason.ts`.
export { sheetCloseReason, type SheetCloseReason } from './sheet-close-reason';

/**
 * Conteúdo do painel.
 *
 * `<ng-template>` e não elemento: o painel é criado dentro do portal, e é o
 * único jeito de o conteúdo escrito por quem consome atravessar para lá sem
 * perder o contexto de binding do componente que o declarou.
 *
 * `side` mora aqui, e não na raiz, porque é isso que o conteúdo compartilhado
 * documenta ("a prop side fica no Content") e o que as outras quatro stacks
 * fazem.
 *
 * `panelClass` é a única exceção à regra "nunca criar input de classe" neste
 * stack, e a exceção tem causa: a regra existe porque o Angular já mescla a
 * classe que quem consome escreve NO ELEMENTO. Aqui não há elemento — o painel
 * é construído por este componente, dentro do portal, e quem consome não tem
 * onde escrever. O conteúdo compartilhado documenta essa mesma escotilha nas
 * outras stacks como `className`.
 *
 * O que ela NÃO faz é ajustar a largura, e vale dizer porque o contrário já
 * esteve escrito aqui: as regras de lado são (0,2,0) e qualquer utilitária de
 * largura é (0,1,0), então `nds-max-w-lg` no painel é inerte. A largura sai de
 * `--sheet-width` / `--sheet-max-width`, como a tabela de props do conteúdo
 * compartilhado registra e o snippet de customização ensina.
 */
@Directive({
  selector: 'ng-template[ndsSheetContent]',
  standalone: true,
})
export class NdsSheetContent {
  /** O próprio template — instanciado pelo `ngTemplateOutlet` dentro do portal. */
  readonly tpl = inject<TemplateRef<unknown>>(TemplateRef);

  readonly side = input<SheetSide>('right');

  /** Botão X embutido no canto do painel. */
  readonly showCloseButton = input(true);

  /**
   * Nome acessível do botão X. O default é o mesmo das outras quatro stacks —
   * que até 2026-08-30 tinham a palavra cravada no markup, sem entrada nenhuma
   * para trocá-la. Numa aplicação traduzida, passe o rótulo.
   */
  readonly closeLabel = input('Fechar');

  /** Classes .nds-* extras no painel — ver a nota de largura no docblock acima. */
  readonly panelClass = input('');
}

// ─── Um painel por vez ────────────────────────────────────────────────────────
//
// O Sheet é MODAL: dois painéis na tela ao mesmo tempo escondem o de baixo atrás
// do véu e criam duas armadilhas de foco. A lib empilha diálogos (ela sabe
// aninhar, que é outro caso); quem recolhe o anterior é este registro, como na
// referência — o vanilla fecha o painel aberto ao abrir outro desde
// `sheet.ts:231-237`, e tem story própria para isso.
//
// O painel que sai da TELA sai também do analytics: o recolhimento passa pelo
// `close()` público, que relata `imperative-action` e vira `api` na tradução.
// Nenhum gesto da pessoa o fechou — foi decisão de dentro do componente —, e sem
// isso a série de abre/fecha da docs page não fecha a conta.
const openPanels = new Set<NdsSheet>();

function closeOthers(current: NdsSheet): void {
  // Cópia da lista antes de percorrer: cada `close()` mexe no próprio registro.
  for (const other of [...openPanels]) {
    if (other !== current) other.close();
  }
}

/**
 * Raiz do Sheet.
 *
 * `open` é model do primitivo, então `[(open)]` funciona; `defaultOpen` cobre o
 * modo não-controlado. `modal` fica exposto porque decide três coisas de uma vez
 * (foco preso, rolagem travada, ponteiro bloqueado fora) e há painel lateral que
 * quer conviver com a página.
 *
 * `triggerId` / `defaultTriggerId` / `handle` do primitivo ficam FORA da lista:
 * servem ao caso de gatilho destacado, que este design system não documenta.
 */
@Component({
  selector: 'nds-sheet',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  // O visual inteiro vem de @shared/styles/nds/sheet.css, que é global.
  encapsulation: ViewEncapsulation.None,
  imports: [
    NgTemplateOutlet,
    RdxDialogPortal,
    RdxDialogBackdrop,
    RdxDialogPopup,
    RdxDialogClose,
    NdsButton,
    NdsButtonIcon,
  ],
  hostDirectives: [
    {
      directive: RdxDialogRoot,
      inputs: ['open', 'defaultOpen', 'modal', 'disablePointerDismissal'],
      outputs: ['openChange', 'onOpenChange', 'onOpenChangeComplete'],
    },
  ],
  host: {
    '[attr.data-slot]': '"sheet"',
  },
  template: `
    <ng-content />

    @if (content(); as c) {
      <ng-template rdxDialogPortal>
        <div
          rdxDialogBackdrop
          class="nds-sheet-overlay"
          data-slot="sheet-overlay"
          [attr.data-state]="state()"
        ></div>

        <div
          rdxDialogPopup
          [class]="classeDoPainel()"
          data-slot="sheet-content"
          [attr.data-side]="c.side()"
          [attr.data-state]="state()"
        >
          <ng-container [ngTemplateOutlet]="c.tpl" />

          @if (c.showCloseButton()) {
            <!-- Botão do design system, não um <button> cru: assim o X herda
                 anel de foco, hover e área de toque do sistema. O CSS
                 compartilhado tem .nds-sheet-close-position justamente para
                 esta composição — só posicionamento, nenhum visual próprio. -->
            <button
              rdxDialogClose
              ndsButton
              variant="ghost"
              size="icon-sm"
              class="nds-sheet-close-position"
              data-slot="sheet-close"
            >
              <svg ndsButtonIcon kind="x"></svg>
              <span class="nds-sr-only">{{ c.closeLabel() }}</span>
            </button>
          }
        </div>
      </ng-template>
    }
  `,
})
export class NdsSheet {
  /**
   * A raiz do Dialog aplicada como host directive. Injetável daqui porque host
   * directive vive no injector de elemento do próprio componente.
   */
  private readonly root = inject(RdxDialogRoot);

  private readonly destroyRef = inject(DestroyRef);

  protected readonly content = contentChild(NdsSheetContent, { descendants: true });

  /**
   * `data-state` para as outras stacks e para a tabela de estados do conteúdo
   * compartilhado. O par `data-open` / `data-closed` que o CSS lê continua vindo
   * do primitivo — este atributo é adição, não substituição.
   */
  protected readonly state = computed(() => (this.root.open() ? 'open' : 'closed'));

  protected readonly classeDoPainel = computed(() =>
    cn('nds-sheet-content', this.content()?.panelClass()),
  );

  /**
   * Fecha o painel por DECISÃO DE DENTRO.
   *
   * É o verbo que a referência expõe (`close()` da fábrica do vanilla), e o que
   * dá à ação primária do rodapé um caminho de saída que não se confunde com o
   * X: `imperative-action` traduz para `api`, e é ele que separa no GA4 o painel
   * aplicado do painel dispensado. Quem fecha por gesto — Escape, véu, X,
   * Cancelar — continua passando pela lib, com o motivo dela.
   */
  close(): void {
    this.root.close('imperative-action');
  }

  constructor() {
    // Um painel por vez. O registro é alimentado pelo estado, e não pelo clique
    // no gatilho: painel aberto por `[open]`, por `defaultOpen` ou por código
    // recolhe o anterior do mesmo jeito.
    effect(() => {
      const isOpen = this.root.open();
      untracked(() => {
        if (!isOpen) {
          openPanels.delete(this);
          return;
        }
        openPanels.add(this);
        closeOthers(this);
      });
    });

    // Sair da página não é fechar, e não relata motivo nenhum: quem desmonta com
    // o painel aberto (troca de idioma numa docs page, story que termina) só
    // precisa deixar o registro limpo para o próximo painel não recolher um
    // fantasma.
    this.destroyRef.onDestroy(() => openPanels.delete(this));

    // Painel modal sem nome acessível é o defeito silencioso deste componente:
    // o leitor de tela anuncia "diálogo" e nada mais, e nenhum teste de render
    // percebe. O primitivo só escreve `aria-labelledby` quando existe um
    // `ndsSheetTitle` registrado — sem título visível, use um com .nds-sr-only.
    effect(() => {
      if (!isDevMode()) return;
      if (!this.root.open()) return;
      // A checagem é adiada de propósito. O `ndsSheetTitle` registra o próprio
      // id no construtor, e o construtor só roda quando o portal cria a view do
      // painel — um passo DEPOIS de `open` virar true. Avaliar aqui dentro
      // acusaria todo painel correto no instante da abertura.
      setTimeout(() => {
        if (untracked(this.root.open) && !untracked(this.root.titleId)) {
          console.warn(
            '[nds-sheet] painel aberto sem ndsSheetTitle: o diálogo fica sem nome ' +
              'acessível. Se o título não deve aparecer, mantenha o elemento e ' +
              'aplique a classe nds-sr-only.',
          );
        }
      });
    });
  }
}

/**
 * Botão que abre o painel.
 *
 * `disabled` do `RdxDialogTrigger` fica FORA da lista de inputs: quando o
 * gatilho também é `ndsButton`, os dois ligariam `attr.disabled` no mesmo
 * elemento e o último a rodar venceria. Desabilitar pelo botão dá as três coisas
 * de uma vez — sem clique, sem foco, aparência e anúncio nativos.
 *
 * `handle` também fica de fora: serve ao gatilho destacado, fora da raiz, que
 * este design system não documenta.
 */
@Directive({
  selector: 'button[ndsSheetTrigger]',
  standalone: true,
  hostDirectives: [
    {
      directive: RdxDialogTrigger,
      inputs: ['id', 'payload'],
    },
  ],
  host: {
    '[attr.data-slot]': '"sheet-trigger"',
  },
})
export class NdsSheetTrigger {}

/**
 * Cabeçalho do painel — título e descrição.
 *
 * Diretiva, não componente: só acrescenta classe e `data-slot` a um `<div>` que
 * quem consome já escreveu.
 */
@Directive({
  selector: 'div[ndsSheetHeader]',
  standalone: true,
  host: {
    class: 'nds-sheet-header',
    '[attr.data-slot]': '"sheet-header"',
  },
})
export class NdsSheetHeader {}

/**
 * Título acessível.
 *
 * O primitivo publica o id deste elemento no contexto da raiz, e é dele que sai
 * o `aria-labelledby` do painel. Seletor restrito a cabeçalho porque o título de
 * um diálogo é cabeçalho de verdade — o nível certo depende do que existe na
 * página em volta.
 */
@Directive({
  selector: 'h1[ndsSheetTitle], h2[ndsSheetTitle], h3[ndsSheetTitle], h4[ndsSheetTitle], h5[ndsSheetTitle], h6[ndsSheetTitle]',
  standalone: true,
  hostDirectives: [RdxDialogTitle],
  host: {
    class: 'nds-sheet-title',
    '[attr.data-slot]': '"sheet-title"',
  },
})
export class NdsSheetTitle {}

/**
 * Descrição acessível — vira o `aria-describedby` do painel pelo mesmo caminho
 * do título.
 */
@Directive({
  selector: 'p[ndsSheetDescription]',
  standalone: true,
  hostDirectives: [RdxDialogDescription],
  host: {
    class: 'nds-sheet-description',
    '[attr.data-slot]': '"sheet-description"',
  },
})
export class NdsSheetDescription {}

/**
 * Corpo rolável do painel.
 *
 * `tabindex="0"` estático, como no Vanilla: quando o conteúdo excede a altura do
 * painel, a região rolável precisa ser alcançável por teclado (WCAG 2.1.1 —
 * é a regra `scrollable-region-focusable` do axe). O `flex: 1 1 auto` do CSS
 * compartilhado é o que mantém o rodapé no lugar enquanto o corpo rola — e é
 * `1 1 auto`, não o atalho `flex: 1`, que zera a base e derruba a altura do
 * painel nos lados `top` e `bottom`. O motivo inteiro está em sheet.css.
 */
@Directive({
  selector: 'div[ndsSheetBody]',
  standalone: true,
  host: {
    class: 'nds-sheet-body',
    tabindex: '0',
    '[attr.data-slot]': '"sheet-body"',
    '[attr.role]': 'ariaLabel() ? "group" : null',
    '[attr.aria-label]': 'ariaLabel() || null',
  },
})
export class NdsSheetBody {
  /**
   * Nome acessível da região que rola. Sem padrão, de propósito.
   *
   * O conteúdo é o que quem monta pôs lá dentro, e só ali se sabe o que é;
   * padrão genérico anunciaria sem informar. Sem nome NÃO emitimos papel
   * nenhum — nome em elemento sem papel é atributo proibido, e o axe acusa
   * `aria-prohibited-attr`.
   *
   * Divergência de API de framework, registrada e não "alinhada": aqui é
   * `input` com apelido, para que o markup escrito continue idêntico ao das
   * outras stacks.
   */
  readonly ariaLabel = input<string>('', { alias: 'aria-label' });
}

/** Rodapé de ações — cancelar à esquerda, ação primária à direita. */
@Directive({
  selector: 'div[ndsSheetFooter]',
  standalone: true,
  host: {
    class: 'nds-sheet-footer',
    '[attr.data-slot]': '"sheet-footer"',
  },
})
export class NdsSheetFooter {}

/**
 * Botão que fecha o painel.
 *
 * Vale para o "Cancelar" do rodapé e para qualquer outro caminho de saída. O X
 * do canto já vem embutido no `ndsSheetContent`.
 */
@Directive({
  selector: 'button[ndsSheetClose]',
  standalone: true,
  hostDirectives: [RdxDialogClose],
  host: {
    '[attr.data-slot]': '"sheet-close"',
  },
})
export class NdsSheetClose {}

/** As peças todas — conveniência para o `imports` de quem compõe. */
export const NDS_SHEET = [
  NdsSheet,
  NdsSheetTrigger,
  NdsSheetContent,
  NdsSheetHeader,
  NdsSheetTitle,
  NdsSheetDescription,
  NdsSheetBody,
  NdsSheetFooter,
  NdsSheetClose,
] as const;

// nortear-design-system-react/src/components/ui/sheet.tsx
import * as React from "react"
import { Dialog as SheetPrimitive } from "@base-ui/react/dialog"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { XIcon } from "lucide-react"

// Decisão de acessibilidade do Sheet — bloco canônico no sheet.ts do Vanilla.
// Em resumo: painel modal que entra pela borda, com role="dialog",
// aria-modal="true", foco preso, foco devolvido ao gatilho no fecho, Escape e
// clique no véu fechando, rolagem da página travada, corpo rolável com papel e
// nome, e NENHUMA região viva.
//
// O mecanismo desta stack, medido em node_modules: o foco é preso pelo
// FloatingFocusManager do DialogPopup, com modal !== false, que também devolve
// o foco ao gatilho (returnFocus); a dispensa sai do useDismiss da raiz
// (escapeKey só no diálogo do topo, outsidePress restrito ao backdrop do
// próprio diálogo); a trava de rolagem cai de useScrollLock(open && modal ===
// true), e portanto só do modal de verdade.
//
// O primitivo isola o resto do documento com `inert`/`aria-hidden` e NÃO emite
// `aria-modal` (conferido em node_modules). Quem cumpre o contrato de markup do
// design system é este wrapper, e para isso o Content precisa saber se a raiz é
// modal. `'trap-focus'` prende o foco mas deixa a página interativa: não é modal
// para o leitor de tela, e por isso não recebe o atributo.
const SheetModalContext = React.createContext<boolean | "trap-focus">(true)

/**
 * Painéis abertos. O Sheet é MODAL: um de cada vez, e o mais novo manda.
 *
 * A lib EMPILHA diálogos — abrir o segundo deixava o primeiro vivo atrás do véu,
 * inalcançável pelo ponteiro e fora da armadilha de foco do painel de cima. A
 * referência da casa (vanilla, `sheet.ts:231-237`) recolhe o anterior na
 * ABERTURA, e é essa a guarda determinística: não depende de quando a remoção do
 * nó é notificada, e descreve o estado que o componente promete.
 *
 * Quem tira o painel da tela é o `close()` imperativo da própria lib
 * (`actionsRef`), e não um estado paralelo mantido aqui: ele passa pelo mesmo
 * `setOpen` de todos os outros caminhos, então o consumidor RECEBE o
 * `onOpenChange` com `reason: 'imperative-action'` — que o `dialogCloseReason`
 * traduz para `api`. É a palavra certa entre as quatro do vocabulário da
 * família: ninguém dispensou o painel de baixo (Escape, véu e botão são os três
 * gestos da pessoa, e nenhum aconteceu), foi uma decisão tomada DENTRO do
 * sistema. Sem isso o painel que sumia da tela sumia também do analytics.
 */
const openPanels = new Set<{ close: () => void }>()

function closeOtherPanels(current: { close: () => void }): void {
  for (const entry of [...openPanels]) {
    if (entry !== current) entry.close()
  }
}

function Sheet({
  open,
  defaultOpen,
  onOpenChange,
  actionsRef,
  ...props
}: SheetPrimitive.Root.Props) {
  // O `actionsRef` de quem compõe tem precedência: o handle é dele, e o painel
  // só pega carona no mesmo objeto para poder se recolher.
  const ownActions = React.useRef<SheetPrimitive.Root.Actions | null>(null)
  const actions = actionsRef ?? ownActions

  // "Está aberto?" só para saber QUANDO entrar e sair da pilha — quem abre e
  // fecha continua sendo a lib. O valor é DERIVADO, nunca sincronizado por
  // efeito: no modo controlado quem manda é a prop, e copiá-la com um
  // `setState` dentro de um efeito renderizaria de novo para chegar ao valor
  // que já estava aqui (`react-hooks/set-state-in-effect`).
  const [uncontrolledOpen, setUncontrolledOpen] = React.useState(defaultOpen ?? false)
  const isOpen = open ?? uncontrolledOpen

  const entry = React.useMemo(
    () => ({ close: () => actions.current?.close() }),
    [actions],
  )

  React.useEffect(() => {
    if (!isOpen) return
    // Antes de pôr mais um painel na tela, tire da tela o que já estava lá.
    closeOtherPanels(entry)
    openPanels.add(entry)
    return () => {
      openPanels.delete(entry)
    }
  }, [isOpen, entry])

  return (
    <SheetModalContext.Provider value={props.modal ?? true}>
      <SheetPrimitive.Root
        data-slot="sheet"
        open={open}
        defaultOpen={defaultOpen}
        actionsRef={actions}
        onOpenChange={(next, details) => {
          setUncontrolledOpen(next)
          onOpenChange?.(next, details)
        }}
        {...props}
      />
    </SheetModalContext.Provider>
  )
}

function SheetTrigger({ ...props }: SheetPrimitive.Trigger.Props) {
  return <SheetPrimitive.Trigger data-slot="sheet-trigger" {...props} />
}

function SheetClose({ ...props }: SheetPrimitive.Close.Props) {
  return <SheetPrimitive.Close data-slot="sheet-close" {...props} />
}

function SheetPortal({ ...props }: SheetPrimitive.Portal.Props) {
  return <SheetPrimitive.Portal data-slot="sheet-portal" {...props} />
}

function SheetOverlay({ className, ...props }: SheetPrimitive.Backdrop.Props) {
  return (
    <SheetPrimitive.Backdrop
      data-slot="sheet-overlay"
      className={cn(
        "nds-sheet-overlay",
        className
      )}
      {...props}
    />
  )
}

function SheetContent({
  className,
  children,
  side = "right",
  showCloseButton = true,
  closeLabel = "Fechar",
  ...props
}: SheetPrimitive.Popup.Props & {
  side?: "top" | "right" | "bottom" | "left"
  showCloseButton?: boolean
  /**
   * Nome acessível do botão X. Era a palavra "Fechar" escrita direto no JSX, e
   * essa era a única string de interface do Sheet presa a um idioma: numa
   * página em inglês ou espanhol o leitor de tela ouvia português, sem que
   * nada na chamada pudesse mudar isso.
   */
  closeLabel?: string
}) {
  const modal = React.useContext(SheetModalContext)
  return (
    <SheetPortal>
      <SheetOverlay />
      <SheetPrimitive.Popup
        data-slot="sheet-content"
        data-side={side}
        className={cn(
          "nds-sheet-content",
          className
        )}
        aria-modal={modal === true ? "true" : undefined}
        {...props}
      >
        {children}
        {showCloseButton && (
          <SheetPrimitive.Close
            data-slot="sheet-close"
            render={
              <Button
                variant="ghost"
                className="nds-sheet-close-position"
                size="icon-sm"
              />
            }
          >
            <XIcon
            />
            <span className="nds-sr-only">{closeLabel}</span>
          </SheetPrimitive.Close>
        )}
      </SheetPrimitive.Popup>
    </SheetPortal>
  )
}

function SheetHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sheet-header"
      className={cn("nds-sheet-header", className)}
      {...props}
    />
  )
}

/**
 * Corpo rolável do painel.
 *
 * `tabIndex={0}`, como no Vanilla: quando o conteúdo passa da altura do painel,
 * a região rolável precisa ser alcançável por teclado (WCAG 2.1.1 — é a regra
 * `scrollable-region-focusable` do axe). O `flex` do CSS compartilhado é o que
 * mantém o rodapé no lugar enquanto o corpo rola.
 */
function SheetBody({
  className,
  "aria-label": ariaLabel,
  ...props
}: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sheet-body"
      tabIndex={0}
      role={ariaLabel ? "group" : undefined}
      aria-label={ariaLabel}
      className={cn("nds-sheet-body", className)}
      {...props}
    />
  )
}

function SheetFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sheet-footer"
      className={cn("nds-sheet-footer", className)}
      {...props}
    />
  )
}

function SheetTitle({ className, ...props }: SheetPrimitive.Title.Props) {
  return (
    <SheetPrimitive.Title
      data-slot="sheet-title"
      className={cn(
        "nds-sheet-title",
        className
      )}
      {...props}
    />
  )
}

function SheetDescription({
  className,
  ...props
}: SheetPrimitive.Description.Props) {
  return (
    <SheetPrimitive.Description
      data-slot="sheet-description"
      className={cn("nds-sheet-description", className)}
      {...props}
    />
  )
}

export {
  Sheet,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetBody,
  SheetFooter,
  SheetTitle,
  SheetDescription,
}
