// nortear-design-system-angular/src/components/ui/sidebar.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  Directive,
  ElementRef,
  Injectable,
  InjectionToken,
  ViewEncapsulation,
  computed,
  effect,
  inject,
  input,
  model,
  signal,
  untracked,
  type OnInit,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { LABELS_SIDEBAR_DEFAULT } from '@shared/primitives/sidebar-a11y-labels';
import {
  NdsSheet,
  NdsSheetContent,
  NdsSheetHeader,
  NdsSheetTitle,
  NdsSheetDescription,
} from './sheet';

// ─── Sidebar ──────────────────────────────────────────────────────────────────
//
// Visual: classes .nds-sidebar-* (docs/shared/styles/nds/sidebar.css).
//
// SEM primitivo do Radix NG: não existe `@radix-ng/primitives/sidebar`. A peça é
// do design system, não da lib headless — as outras quatro stacks também a
// escrevem à mão.
//
// O estado (aberto/recolhido, móvel, atalho de teclado) mora num serviço de
// signals fornecido pelo Provider, e não em input espalhado pelas peças: o
// gatilho fica longe do painel na árvore, e passar `open` de mão em mão faria
// quem compõe costurar o que o componente já sabe fazer.
//
// Nenhuma medida vem daqui. `--sidebar-width` e `--sidebar-width-icon` já são
// declaradas em `.nds-sidebar-wrapper` no CSS compartilhado — o React as repete
// em `style` inline sem precisar.

const SHORTCUT = 'b';
const COOKIE = 'sidebar_state';
const COOKIE_MAX_AGE = 60 * 60 * 24 * 7; // uma semana
/** Abaixo disto a sidebar vira gaveta sobreposta em vez de coluna. */
const WIDTH_MOVEL = '(max-width: 767px)';

/**
 * A media query que decide se a barra é coluna ou gaveta.
 *
 * Injetável porque o ponto de virada é do produto, não do design system: uma
 * aplicação com sidebar mais estreita vira mais tarde. Também é o que permite
 * exercitar o caminho móvel sem redimensionar o navegador.
 */
export const NDS_SIDEBAR_MOBILE_QUERY = new InjectionToken<string>(
  'nds-sidebar-mobile-query',
  { providedIn: 'root', factory: () => WIDTH_MOVEL },
);

export type SidebarState = 'expanded' | 'collapsed';
export type SidebarSide = 'left' | 'right';
export type SidebarVariant = 'sidebar' | 'floating' | 'inset';
export type SidebarCollapsible = 'offcanvas' | 'icon' | 'none';
export type SidebarMenuButtonVariant = 'default' | 'outline';
export type SidebarMenuButtonSize = 'default' | 'sm' | 'lg';

/**
 * Estado compartilhado por toda a árvore da sidebar.
 *
 * Fornecido pelo `NdsSidebarProvider`, nunca em `root`: duas sidebars na mesma
 * página — o que a docs page faz, com um exemplo por variante — precisam de
 * estados independentes.
 */
@Injectable()
export class NdsSidebarStore {
  private readonly _open = signal(true);
  private readonly _openMobile = signal(false);
  private readonly _isMobile = signal(false);

  readonly open = this._open.asReadonly();
  readonly openMobile = this._openMobile.asReadonly();
  readonly isMobile = this._isMobile.asReadonly();

  /** O que o CSS lê em `data-state`. */
  readonly state = computed<SidebarState>(() => (this._open() ? 'expanded' : 'collapsed'));

  /** Avisa quem controla de fora; o Provider liga isto ao próprio model. */
  onChange: ((aberto: boolean) => void) | undefined;

  constructor() {
    const destroyRef = inject(DestroyRef);

    // Ctrl/Cmd+B. No `document` e não no elemento: o atalho vale de qualquer
    // lugar da página, inclusive com o foco no conteúdo principal.
    const aoTeclar = (e: KeyboardEvent) => {
      if (e.key === SHORTCUT && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        this.alternar();
      }
    };
    document.addEventListener('keydown', aoTeclar);

    const consulta = window.matchMedia(inject(NDS_SIDEBAR_MOBILE_QUERY));
    const onChangeWidth = () => this._isMobile.set(consulta.matches);
    onChangeWidth();
    consulta.addEventListener('change', onChangeWidth);

    destroyRef.onDestroy(() => {
      document.removeEventListener('keydown', aoTeclar);
      consulta.removeEventListener('change', onChangeWidth);
    });
  }

  definir(aberto: boolean): void {
    this._open.set(aberto);
    this.onChange?.(aberto);
    // Persistência entre visitas. Falha em silêncio onde cookie não é gravável
    // (iframe de terceiro, modo restrito) — é preferência, não dado.
    try {
      document.cookie = `${COOKIE}=${aberto}; path=/; max-age=${COOKIE_MAX_AGE}; SameSite=Lax`;
    } catch {
      /* preferência perdida, sidebar funcionando */
    }
  }

  definirMovel(aberto: boolean): void {
    this._openMobile.set(aberto);
  }

  alternar(): void {
    if (this._isMobile()) this.definirMovel(!this._openMobile());
    else this.definir(!this._open());
  }
}

/**
 * Raiz. Envolve a sidebar e o conteúdo principal, e é quem fornece o estado.
 *
 * Também é onde o CSS declara `--sidebar-width` e `--sidebar-width-icon`, então
 * nenhuma peça abaixo precisa saber medida.
 */
@Component({
  selector: 'div[ndsSidebarProvider]',
  standalone: true,
  template: '<ng-content />',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [NdsSidebarStore],
  host: {
    class: 'nds-sidebar-wrapper',
    '[attr.data-slot]': '"sidebar-wrapper"',
  },
})
export class NdsSidebarProvider implements OnInit {
  /** Estado inicial quando ninguém controla de fora. */
  readonly defaultOpen = input<boolean>(true);

  /** Controle de fora. É um `model`, então `[(open)]` funciona. */
  readonly open = model<boolean | undefined>(undefined);

  private readonly store = inject(NdsSidebarStore);

  ngOnInit(): void {
    // No `ngOnInit` e NÃO no construtor: no construtor um `input()` ainda
    // devolve o valor declarado no componente, não o que quem consome ligou.
    // Ler `defaultOpen()` lá dá `true` sempre, e a sidebar nasce aberta mesmo
    // com `[defaultOpen]="false"` — sem erro, só com o estado errado.
    this.store.definir(this.open() ?? this.defaultOpen());

    // O store avisa quem controla; sem isto um `[(open)]` nunca receberia de
    // volta o efeito do atalho de teclado nem do clique no gatilho.
    this.store.onChange = (aberto) => this.open.set(aberto);
  }

  constructor() {
    effect(() => {
      const ofOutside = this.open();
      // A leitura de comparação vai em `untracked`: como dependência, ela
      // faria o effect acordar da própria escrita do `onChange` acima.
      if (ofOutside !== undefined && ofOutside !== untracked(this.store.open)) this.store.definir(ofOutside);
    });
  }
}

/** O painel em si. */
@Component({
  selector: 'div[ndsSidebar]',
  standalone: true,
  imports: [NgTemplateOutlet, NdsSheet, NdsSheetContent, NdsSheetHeader, NdsSheetTitle, NdsSheetDescription],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'classeDoHost()',
    '[attr.data-slot]': '"sidebar"',
    '[attr.data-state]': 'store.state()',
    '[attr.data-side]': 'side()',
    '[attr.data-variant]': 'variant()',
    '[attr.data-collapsible]': 'colapsavelAtivo()',
    '[attr.data-mobile]': 'store.isMobile() ? "true" : null',
  },
  template: `
    <!-- UMA <ng-content> só, guardada aqui e instanciada onde faz falta.
         Duas <ng-content> em ramos exclusivos de @if não funcionam: o Angular
         resolve a projeção em tempo de compilação, e com dois destinos padrão o
         conteúdo não chega a NENHUM dos dois. O sintoma é a sidebar renderizar
         vazia, sem erro. O <ng-container> não deixa elemento no DOM. -->
    <ng-template #conteudo><ng-content /></ng-template>

    @if (store.isMobile() && collapsible() !== 'none') {
      <!-- Em tela estreita a barra deixa de ser coluna e vira gaveta sobreposta.
           Não é escolha estética: 16rem numa tela de 360px não deixa conteúdo.
           O Sheet traz foco preso, Escape, devolução de foco e trava de rolagem,
           que uma gaveta modal precisa ter e ninguém escreve certo à mão.

           O X embutido fica desligado porque o CSS compartilhado já o esconde
           dentro de .nds-sidebar-mobile — o gatilho continua sendo a saída. -->
      <nds-sheet
        [open]="store.openMobile()"
        (openChange)="store.definirMovel($event)"
      >
        <ng-template
          ndsSheetContent
          [side]="side()"
          panelClass="nds-sidebar-mobile"
          [showCloseButton]="false"
        >
          <!-- Título só para leitor de tela: um diálogo sem nome é anunciado
               como "diálogo" e mais nada. O mesmo par que o React escreve. -->
          <div ndsSheetHeader class="nds-sr-only">
            <h2 ndsSheetTitle>{{ mobileTitle() }}</h2>
            <p ndsSheetDescription>{{ mobileDescription() }}</p>
          </div>
          <div class="nds-sidebar-mobile-inner">
            <ng-container [ngTemplateOutlet]="conteudo" />
          </div>
        </ng-template>
      </nds-sheet>
    } @else if (collapsible() === 'none') {
      <!-- Sem recolhimento não há vão a reservar nem painel flutuante: o
           conteúdo é a própria coluna. -->
      <ng-container [ngTemplateOutlet]="conteudo" />
    } @else {
      <!-- O vão reserva a largura no fluxo enquanto o painel fica fixo por
           cima. Sem ele o conteúdo principal pularia a cada recolhimento. -->
      <div class="nds-sidebar-gap" [attr.data-state]="store.state()" data-slot="sidebar-gap">
        <div class="nds-sidebar-gap-inner"></div>
      </div>
      <div class="nds-sidebar-panel" data-slot="sidebar-container">
        <div class="nds-sidebar-inner" data-sidebar="sidebar" data-slot="sidebar-inner">
          <ng-container [ngTemplateOutlet]="conteudo" />
        </div>
      </div>
    }
  `,
})
export class NdsSidebar {
  readonly side = input<SidebarSide>('left');
  readonly variant = input<SidebarVariant>('sidebar');
  readonly collapsible = input<SidebarCollapsible>('offcanvas');

  /**
   * Nome e descrição do painel na versão móvel, só para leitor de tela.
   *
   * O padrão vem do conteúdo compartilhado, em português, e é o mesmo nas cinco
   * stacks: era o inglês cravado no componente que fazia a gaveta ser anunciada
   * como "Sidebar / Displays the mobile sidebar." num produto em português.
   */
  readonly mobileTitle = input(LABELS_SIDEBAR_DEFAULT.tituloMovel);
  readonly mobileDescription = input(LABELS_SIDEBAR_DEFAULT.descricaoMovel);

  protected readonly store = inject(NdsSidebarStore);

  protected readonly classeDoHost = computed(() =>
    this.collapsible() === 'none' ? 'nds-sidebar-static' : 'nds-sidebar-root',
  );

  /** Quem tinha o foco quando a gaveta móvel abriu. */
  private gavetaFocusBefore: HTMLElement | null = null;

  constructor() {
    // Devolver o foco é trabalho de quem abriu.
    //
    // O Sheet restaura sozinho quando o gatilho é um `ndsSheetTrigger` — aqui
    // não é: a gaveta abre pelo store, a partir do `ndsSidebarTrigger`, que o
    // primitivo nunca vê. Sem isto o Escape fecha o painel e o foco cai no
    // <body>: quem navega por teclado volta ao começo da página.
    effect(() => {
      const aberta = this.store.openMobile();
      if (aberta) {
        this.gavetaFocusBefore = document.activeElement as HTMLElement | null;
        return;
      }
      const alvo = this.gavetaFocusBefore;
      this.gavetaFocusBefore = null;
      // Adiado de propósito: o painel ainda está saindo, e o gerenciador de
      // foco do primitivo mexe no foco durante a animação de saída.
      if (alvo?.isConnected) setTimeout(() => alvo.focus());
    });
  }

  /**
   * `data-collapsible` só existe enquanto a sidebar está recolhida.
   *
   * É assim que as outras stacks emitem, e o CSS depende disso: as regras de
   * `[data-collapsible="icon"]` encolhem o painel e escondem rótulos — se o
   * atributo ficasse fixo, a sidebar nasceria encolhida.
   */
  protected readonly colapsavelAtivo = computed(() =>
    this.store.state() === 'collapsed' && this.collapsible() !== 'none' ? this.collapsible() : null,
  );
}

/**
 * Botão que alterna a sidebar.
 *
 * O nome acessível tem padrão em português, vindo do conteúdo compartilhado: um
 * gatilho só de ícone sem nome é anunciado pelo que houver dentro dele — e nas
 * outras quatro stacks esse texto era "Toggle Sidebar", cravado.
 *
 * O input é APELIDADO como `aria-label`, e não exposto como `label`: assim o
 * `aria-label="Abrir navegação"` que quem compõe já escrevia continua sendo a
 * forma de trocá-lo, em vez de virar um atributo que a ligação de host
 * sobrescreveria em silêncio.
 */
@Directive({
  selector: 'button[ndsSidebarTrigger]',
  standalone: true,
  host: {
    type: 'button',
    'data-sidebar': 'trigger',
    '[attr.data-slot]': '"sidebar-trigger"',
    '[attr.aria-expanded]': 'store.open()',
    '[attr.aria-label]': 'ariaLabel()',
    '(click)': 'store.alternar()',
  },
})
export class NdsSidebarTrigger {
  readonly ariaLabel = input(LABELS_SIDEBAR_DEFAULT.alternar, { alias: 'aria-label' });

  protected readonly store = inject(NdsSidebarStore);
}

/**
 * Faixa clicável na borda do painel.
 *
 * `tabindex="-1"` de propósito: ela faz o mesmo que o gatilho, que já está na
 * ordem de tabulação. Duas paradas de teclado para uma ação só é ruído para
 * quem navega sem mouse — e o `aria-hidden` completa, tirando a duplicata
 * também do leitor de tela.
 *
 * O `title` é a dica de ponteiro, para quem a faixa existe: sem ela, a faixa é
 * uma tira de 1rem que reage ao clique e não se explica. As outras quatro
 * stacks já a emitiam; esta era a única sem — divergência de markup, e o Vanilla
 * é a referência. O texto é o mesmo do gatilho, porque a ação é a mesma.
 */
@Directive({
  selector: 'button[ndsSidebarRail]',
  standalone: true,
  host: {
    class: 'nds-sidebar-rail',
    type: 'button',
    tabindex: '-1',
    'aria-hidden': 'true',
    'data-sidebar': 'rail',
    '[attr.data-slot]': '"sidebar-rail"',
    '[attr.title]': 'title()',
    '(click)': 'store.alternar()',
  },
})
export class NdsSidebarRail {
  readonly title = input(LABELS_SIDEBAR_DEFAULT.alternar);

  protected readonly store = inject(NdsSidebarStore);
}

/** Conteúdo principal ao lado da sidebar. `<main>` porque é o marco da página. */
@Directive({
  selector: 'main[ndsSidebarInset]',
  standalone: true,
  host: { class: 'nds-sidebar-inset', '[attr.data-slot]': '"sidebar-inset"' },
})
export class NdsSidebarInset {}

@Directive({
  selector: 'input[ndsSidebarInput]',
  standalone: true,
  host: {
    class: 'nds-sidebar-input',
    'data-sidebar': 'input',
    '[attr.data-slot]': '"sidebar-input"',
  },
})
export class NdsSidebarInput {}

@Directive({
  selector: 'div[ndsSidebarHeader]',
  standalone: true,
  host: { class: 'nds-sidebar-header', 'data-sidebar': 'header', '[attr.data-slot]': '"sidebar-header"' },
})
export class NdsSidebarHeader {}

@Directive({
  selector: 'div[ndsSidebarFooter]',
  standalone: true,
  host: { class: 'nds-sidebar-footer', 'data-sidebar': 'footer', '[attr.data-slot]': '"sidebar-footer"' },
})
export class NdsSidebarFooter {}

@Directive({
  selector: 'div[ndsSidebarContent]',
  standalone: true,
  host: { class: 'nds-sidebar-content', 'data-sidebar': 'content', '[attr.data-slot]': '"sidebar-content"' },
})
export class NdsSidebarContent {}

@Directive({
  selector: 'div[ndsSidebarSeparator]',
  standalone: true,
  host: {
    class: 'nds-sidebar-separator',
    role: 'separator',
    'aria-orientation': 'horizontal',
    'data-sidebar': 'separator',
    '[attr.data-slot]': '"sidebar-separator"',
  },
})
export class NdsSidebarSeparator {}

@Directive({
  selector: 'div[ndsSidebarGroup]',
  standalone: true,
  host: { class: 'nds-sidebar-group', 'data-sidebar': 'group', '[attr.data-slot]': '"sidebar-group"' },
})
export class NdsSidebarGroup {}

/**
 * Rótulo do grupo.
 *
 * Some da tela quando a sidebar recolhe para ícones (o CSS zera a opacidade),
 * mas continua no DOM — é ele que dá nome ao grupo para quem usa leitor de
 * tela, e recolher a coluna não deveria apagar essa informação.
 */
@Directive({
  selector: 'div[ndsSidebarGroupLabel]',
  standalone: true,
  host: {
    class: 'nds-sidebar-group-label',
    'data-sidebar': 'group-label',
    '[attr.data-slot]': '"sidebar-group-label"',
  },
})
export class NdsSidebarGroupLabel {}

@Directive({
  selector: 'button[ndsSidebarGroupAction]',
  standalone: true,
  host: {
    class: 'nds-sidebar-group-action',
    type: 'button',
    'data-sidebar': 'group-action',
    '[attr.data-slot]': '"sidebar-group-action"',
  },
})
export class NdsSidebarGroupAction {}

@Directive({
  selector: 'div[ndsSidebarGroupContent]',
  standalone: true,
  host: {
    class: 'nds-sidebar-group-content',
    'data-sidebar': 'group-content',
    '[attr.data-slot]': '"sidebar-group-content"',
  },
})
export class NdsSidebarGroupContent {}

@Directive({
  selector: 'ul[ndsSidebarMenu]',
  standalone: true,
  host: { class: 'nds-sidebar-menu', 'data-sidebar': 'menu', '[attr.data-slot]': '"sidebar-menu"' },
})
export class NdsSidebarMenu {}

@Directive({
  selector: 'li[ndsSidebarMenuItem]',
  standalone: true,
  host: {
    class: 'nds-sidebar-menu-item',
    'data-sidebar': 'menu-item',
    '[attr.data-slot]': '"sidebar-menu-item"',
  },
})
export class NdsSidebarMenuItem {}

/**
 * O item de navegação.
 *
 * Serve tanto `<button>` quanto `<a href>` — quem navega para outra rota merece
 * um link de verdade, que abre em nova aba e aparece no histórico.
 *
 * `aria-current="page"` além do `data-active`: o data-attribute é para o CSS,
 * o ARIA é o que o leitor de tela anuncia como "página atual". As outras stacks
 * emitem os dois.
 */
@Directive({
  selector: 'button[ndsSidebarMenuButton], a[ndsSidebarMenuButton]',
  standalone: true,
  host: {
    '[class]': 'classeDoHost()',
    'data-sidebar': 'menu-button',
    '[attr.data-slot]': '"sidebar-menu-button"',
    '[attr.data-active]': 'active() ? "true" : null',
    '[attr.data-size]': 'size() === "default" ? null : size()',
    '[attr.aria-current]': 'active() && ehLink ? "page" : null',
  },
})
export class NdsSidebarMenuButton {
  readonly variant = input<SidebarMenuButtonVariant>('default');
  readonly size = input<SidebarMenuButtonSize>('default');
  readonly active = input<boolean>(false);

  private readonly hostRef = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly ehLink = this.hostRef.nativeElement.tagName === 'A';

  // A variante `outline` tem classe própria em vez de `data-variant`, que é
  // como o CSS compartilhado a escreve. Só as classes deste componente entram
  // aqui: o `class` que quem consome escrever no elemento o Angular já mescla.
  protected readonly classeDoHost = computed(() =>
    this.variant() === 'outline'
      ? 'nds-sidebar-menu-button nds-sidebar-menu-button-outline'
      : 'nds-sidebar-menu-button',
  );
}

@Directive({
  selector: 'button[ndsSidebarMenuAction]',
  standalone: true,
  host: {
    class: 'nds-sidebar-menu-action',
    type: 'button',
    'data-sidebar': 'menu-action',
    '[attr.data-slot]': '"sidebar-menu-action"',
  },
})
export class NdsSidebarMenuAction {}

/**
 * Contador ao lado do item.
 *
 * `aria-hidden` porque o número sozinho não diz nada: quem compõe põe a
 * contagem no nome acessível do item ("Notificações, 3 não lidas"), e sem isto
 * o leitor leria um "3" solto depois do rótulo.
 */
@Directive({
  selector: 'span[ndsSidebarMenuBadge]',
  standalone: true,
  host: {
    class: 'nds-sidebar-menu-badge',
    'aria-hidden': 'true',
    'data-sidebar': 'menu-badge',
    '[attr.data-slot]': '"sidebar-menu-badge"',
  },
})
export class NdsSidebarMenuBadge {}

@Directive({
  selector: 'ul[ndsSidebarMenuSub]',
  standalone: true,
  host: {
    class: 'nds-sidebar-menu-sub',
    'data-sidebar': 'menu-sub',
    '[attr.data-slot]': '"sidebar-menu-sub"',
  },
})
export class NdsSidebarMenuSub {}

@Directive({
  selector: 'li[ndsSidebarMenuSubItem]',
  standalone: true,
  host: {
    class: 'nds-sidebar-menu-sub-item',
    'data-sidebar': 'menu-sub-item',
    '[attr.data-slot]': '"sidebar-menu-sub-item"',
  },
})
export class NdsSidebarMenuSubItem {}

@Directive({
  selector: 'a[ndsSidebarMenuSubButton], button[ndsSidebarMenuSubButton]',
  standalone: true,
  host: {
    class: 'nds-sidebar-menu-sub-button',
    'data-sidebar': 'menu-sub-button',
    '[attr.data-slot]': '"sidebar-menu-sub-button"',
    '[attr.data-active]': 'active() ? "true" : null',
    '[attr.data-size]': 'size() === "default" ? null : size()',
    '[attr.aria-current]': 'active() && ehLink ? "page" : null',
  },
})
export class NdsSidebarMenuSubButton {
  readonly size = input<SidebarMenuButtonSize>('default');
  readonly active = input<boolean>(false);

  private readonly hostRef = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly ehLink = this.hostRef.nativeElement.tagName === 'A';
}

/**
 * Espaço reservado enquanto o menu carrega.
 *
 * `role="status"` com `aria-label`: um bloco cinza pulsando não diz nada para
 * quem não o vê, e um `aria-label` num elemento sem papel seria atributo
 * proibido (axe aria-prohibited-attr).
 */
@Component({
  selector: 'div[ndsSidebarMenuSkeleton]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'nds-sidebar-menu-skeleton',
    role: 'status',
    'data-sidebar': 'menu-skeleton',
    '[attr.data-slot]': '"sidebar-menu-skeleton"',
    '[attr.aria-label]': 'loadingLabel()',
  },
  template: `
    @if (showIcon()) {
      <div class="nds-sidebar-menu-skeleton-icon" data-sidebar="menu-skeleton-icon"></div>
    }
    <div class="nds-sidebar-menu-skeleton-text" data-sidebar="menu-skeleton-text"></div>
  `,
})
export class NdsSidebarMenuSkeleton {
  readonly showIcon = input<boolean>(false);
  readonly loadingLabel = input<string>('Carregando menu');
}

/** A família inteira — conveniência para o `imports` de quem compõe. */
export const NDS_SIDEBAR = [
  NdsSidebarProvider, NdsSidebar, NdsSidebarTrigger, NdsSidebarRail, NdsSidebarInset,
  NdsSidebarInput, NdsSidebarHeader, NdsSidebarFooter, NdsSidebarContent, NdsSidebarSeparator,
  NdsSidebarGroup, NdsSidebarGroupLabel, NdsSidebarGroupAction, NdsSidebarGroupContent,
  NdsSidebarMenu, NdsSidebarMenuItem, NdsSidebarMenuButton, NdsSidebarMenuAction,
  NdsSidebarMenuBadge, NdsSidebarMenuSub, NdsSidebarMenuSubItem, NdsSidebarMenuSubButton,
  NdsSidebarMenuSkeleton,
] as const;

// nortear-design-system-react/src/components/ui/sidebar.tsx
"use client"

import * as React from "react"
import { mergeProps } from "@base-ui/react/merge-props"
import { useRender } from "@base-ui/react/use-render"
import { cva, type VariantProps } from "class-variance-authority"

import { SIDEBAR_MOBILE_QUERY, useIsMobile } from "@/hooks/use-mobile"
import { LABELS_SIDEBAR_DEFAULT } from "@shared/primitives/sidebar-a11y-labels"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Separator } from "@/components/ui/separator"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet"
import { Skeleton } from "@/components/ui/skeleton"
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { PanelLeftIcon } from "lucide-react"

const SIDEBAR_COOKIE_NAME = "sidebar_state"
const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7
const SIDEBAR_WIDTH = "16rem"
const SIDEBAR_WIDTH_MOBILE = "18rem"
const SIDEBAR_WIDTH_ICON = "3rem"
const SIDEBAR_KEYBOARD_SHORTCUT = "b"

type SidebarContextProps = {
  state: "expanded" | "collapsed"
  open: boolean
  setOpen: (open: boolean) => void
  openMobile: boolean
  setOpenMobile: (open: boolean) => void
  isMobile: boolean
  toggleSidebar: () => void
}

const SidebarContext = React.createContext<SidebarContextProps | null>(null)

function useSidebar() {
  const context = React.useContext(SidebarContext)
  if (!context) {
    throw new Error("useSidebar must be used within a SidebarProvider.")
  }

  return context
}

function SidebarProvider({
  defaultOpen = true,
  open: openProp,
  onOpenChange: setOpenProp,
  mobileQuery = SIDEBAR_MOBILE_QUERY,
  className,
  style,
  children,
  ...props
}: React.ComponentProps<"div"> & {
  defaultOpen?: boolean
  open?: boolean
  onOpenChange?: (open: boolean) => void
  /**
   * A consulta de mídia que decide se a barra vira gaveta sobreposta.
   *
   * Existe como prop, e não só como constante, porque o ponto de virada é do
   * produto e não do design system — uma aplicação com sidebar mais estreita
   * vira mais tarde. É também o que permite exercitar o caminho móvel sem
   * redimensionar o navegador: uma consulta sempre verdadeira força a gaveta de
   * forma determinística, inclusive no runner headless.
   *
   * Fica DESESTRUTURADA de propósito: se caísse no `...props` viraria atributo
   * desconhecido no `<div>` e o React reclamaria no console.
   */
  mobileQuery?: string
}) {
  const isMobile = useIsMobile(mobileQuery)
  const [openMobile, setOpenMobile] = React.useState(false)

  // This is the internal state of the sidebar.
  // We use openProp and setOpenProp for control from outside the component.
  const [_open, _setOpen] = React.useState(defaultOpen)
  const open = openProp ?? _open
  const setOpen = React.useCallback(
    (value: boolean | ((value: boolean) => boolean)) => {
      const openState = typeof value === "function" ? value(open) : value
      if (setOpenProp) {
        setOpenProp(openState)
      } else {
        _setOpen(openState)
      }

      // This sets the cookie to keep the sidebar state.
      document.cookie = `${SIDEBAR_COOKIE_NAME}=${openState}; path=/; max-age=${SIDEBAR_COOKIE_MAX_AGE}`
    },
    [setOpenProp, open]
  )

  // Helper to toggle the sidebar.
  const toggleSidebar = React.useCallback(() => {
    return isMobile ? setOpenMobile((open) => !open) : setOpen((open) => !open)
  }, [isMobile, setOpen, setOpenMobile])

  // Adds a keyboard shortcut to toggle the sidebar.
  React.useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (
        event.key === SIDEBAR_KEYBOARD_SHORTCUT &&
        (event.metaKey || event.ctrlKey)
      ) {
        event.preventDefault()
        toggleSidebar()
      }
    }

    window.addEventListener("keydown", handleKeyDown)
    return () => window.removeEventListener("keydown", handleKeyDown)
  }, [toggleSidebar])

  // We add a state so that we can do data-state="expanded" or "collapsed".
  // This makes it easier to style the sidebar with CSS (.nds-* / data-attrs).
  const state = open ? "expanded" : "collapsed"

  const contextValue = React.useMemo<SidebarContextProps>(
    () => ({
      state,
      open,
      setOpen,
      isMobile,
      openMobile,
      setOpenMobile,
      toggleSidebar,
    }),
    [state, open, setOpen, isMobile, openMobile, setOpenMobile, toggleSidebar]
  )

  return (
    <SidebarContext.Provider value={contextValue}>
      <div
        data-slot="sidebar-wrapper"
        style={
          {
            "--sidebar-width": SIDEBAR_WIDTH,
            "--sidebar-width-icon": SIDEBAR_WIDTH_ICON,
            ...style,
          } as React.CSSProperties
        }
        className={cn(
          "nds-sidebar-wrapper",
          className
        )}
        {...props}
      >
        {children}
      </div>
    </SidebarContext.Provider>
  )
}

function Sidebar({
  side = "left",
  variant = "sidebar",
  collapsible = "offcanvas",
  mobileTitle = LABELS_SIDEBAR_DEFAULT.tituloMovel,
  mobileDescription = LABELS_SIDEBAR_DEFAULT.descricaoMovel,
  className,
  children,
  dir,
  ...props
}: React.ComponentProps<"div"> & {
  side?: "left" | "right"
  variant?: "sidebar" | "floating" | "inset"
  collapsible?: "offcanvas" | "icon" | "none"
  /**
   * Nome e descrição da gaveta sobreposta, só para leitor de tela.
   *
   * O padrão vem do conteúdo compartilhado, em português. São props e não
   * literais porque o texto pertence ao produto: uma aplicação em outro idioma
   * — ou que chame a barra de outra coisa — precisa poder trocá-lo sem editar o
   * componente. Ficam DESESTRUTURADOS de propósito: no `...props` virariam
   * atributos desconhecidos no elemento.
   */
  mobileTitle?: string
  mobileDescription?: string
}) {
  const { isMobile, state, openMobile, setOpenMobile } = useSidebar()

  if (collapsible === "none") {
    return (
      <div
        data-slot="sidebar"
        className={cn(
          "nds-sidebar-static",
          className
        )}
        {...props}
      >
        {children}
      </div>
    )
  }

  if (isMobile) {
    // `className` e o resto das props vão para o PAINEL, não para a raiz do
    // Sheet: a raiz não renderiza elemento nenhum, então tudo o que caísse ali
    // sumiria em silêncio — a classe de quem compõe desaparecia só em tela
    // estreita. Na coluna elas pousam em `.nds-sidebar-panel`; aqui, na gaveta,
    // que é o mesmo papel. O `style` de fora entra depois da medida móvel para
    // poder sobrescrevê-la.
    const { style: estiloDeFora, ...restante } = props
    return (
      <Sheet open={openMobile} onOpenChange={setOpenMobile}>
        <SheetContent
          dir={dir}
          data-sidebar="sidebar"
          data-slot="sidebar"
          data-mobile="true"
          className={cn("nds-sidebar-mobile", className)}
          style={
            {
              "--sidebar-width": SIDEBAR_WIDTH_MOBILE,
              ...estiloDeFora,
            } as React.CSSProperties
          }
          side={side}
          {...restante}
        >
          <SheetHeader className="nds-sr-only">
            <SheetTitle>{mobileTitle}</SheetTitle>
            <SheetDescription>{mobileDescription}</SheetDescription>
          </SheetHeader>
          <div className="nds-sidebar-mobile-inner">{children}</div>
        </SheetContent>
      </Sheet>
    )
  }

  return (
    <div
      className="nds-sidebar-root"
      data-state={state}
      data-collapsible={state === "collapsed" ? collapsible : ""}
      data-variant={variant}
      data-side={side}
      data-slot="sidebar"
    >
      {/* This is what handles the sidebar gap on desktop */}
      <div data-slot="sidebar-gap" className="nds-sidebar-gap-inner" />
      <div
        data-slot="sidebar-container"
        data-side={side}
        className={cn("nds-sidebar-panel", className)}
        {...props}
      >
        <div
          data-sidebar="sidebar"
          data-slot="sidebar-inner"
          className="nds-sidebar-inner"
        >
          {children}
        </div>
      </div>
    </div>
  )
}

/**
 * Botão que alterna a barra.
 *
 * `label` é o nome acessível: o botão carrega só um ícone, e o ícone é
 * `aria-hidden`. O padrão vem do conteúdo compartilhado, em português — quem
 * ouve o controle principal do componente ouvia "Toggle Sidebar" até aqui.
 * Continua trocável para o caso em que o rótulo depende do contexto ("Abrir
 * navegação do produto").
 */
function SidebarTrigger({
  className,
  onClick,
  label = LABELS_SIDEBAR_DEFAULT.alternar,
  ...props
}: React.ComponentProps<typeof Button> & { label?: string }) {
  const { toggleSidebar } = useSidebar()

  return (
    <Button
      data-sidebar="trigger"
      data-slot="sidebar-trigger"
      variant="ghost"
      size="icon-sm"
      className={cn(className)}
      onClick={(event) => {
        onClick?.(event)
        toggleSidebar()
      }}
      {...props}
    >
      <PanelLeftIcon />
      <span className="nds-sr-only">{label}</span>
    </Button>
  )
}

/**
 * Faixa clicável na borda do painel.
 *
 * `tabIndex={-1}` de propósito: ela faz o mesmo que o gatilho, que já está na
 * ordem de tabulação — duas paradas de teclado para uma ação só é ruído para
 * quem navega sem mouse. `aria-hidden` completa o par: sem ele, o leitor de
 * tela lista dois botões com o mesmo nome para a mesma ação, e um deles nem
 * recebe foco. O `title` fica: é a dica de ponteiro, para quem a faixa existe —
 * e vem do conteúdo compartilhado, em português, com o mesmo texto do gatilho,
 * porque a ação é a mesma. Vai ANTES do spread: um `title` de quem compõe ainda
 * ganha.
 */
function SidebarRail({ className, ...props }: React.ComponentProps<"button">) {
  const { toggleSidebar } = useSidebar()

  return (
    <button
      data-sidebar="rail"
      data-slot="sidebar-rail"
      aria-hidden="true"
      tabIndex={-1}
      onClick={toggleSidebar}
      title={LABELS_SIDEBAR_DEFAULT.alternar}
      className={cn("nds-sidebar-rail", className)}
      {...props}
    />
  )
}

function SidebarInset({ className, ...props }: React.ComponentProps<"main">) {
  return (
    <main
      data-slot="sidebar-inset"
      className={cn("nds-sidebar-inset", className)}
      {...props}
    />
  )
}

function SidebarInput({
  className,
  ...props
}: React.ComponentProps<typeof Input>) {
  return (
    <Input
      data-slot="sidebar-input"
      data-sidebar="input"
      className={cn("nds-sidebar-input", className)}
      {...props}
    />
  )
}

function SidebarHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sidebar-header"
      data-sidebar="header"
      className={cn("nds-sidebar-header", className)}
      {...props}
    />
  )
}

function SidebarFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sidebar-footer"
      data-sidebar="footer"
      className={cn("nds-sidebar-footer", className)}
      {...props}
    />
  )
}

function SidebarSeparator({
  className,
  ...props
}: React.ComponentProps<typeof Separator>) {
  return (
    <Separator
      data-slot="sidebar-separator"
      data-sidebar="separator"
      className={cn("nds-sidebar-separator", className)}
      {...props}
    />
  )
}

function SidebarContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sidebar-content"
      data-sidebar="content"
      className={cn("nds-sidebar-content", className)}
      {...props}
    />
  )
}

function SidebarGroup({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sidebar-group"
      data-sidebar="group"
      className={cn("nds-sidebar-group", className)}
      {...props}
    />
  )
}

function SidebarGroupLabel({
  className,
  render,
  ...props
}: useRender.ComponentProps<"div"> & React.ComponentProps<"div">) {
  return useRender({
    defaultTagName: "div",
    props: mergeProps<"div">(
      {
        className: cn("nds-sidebar-group-label", className),
      },
      props
    ),
    render,
    state: {
      slot: "sidebar-group-label",
      sidebar: "group-label",
    },
  })
}

function SidebarGroupAction({
  className,
  render,
  ...props
}: useRender.ComponentProps<"button"> & React.ComponentProps<"button">) {
  return useRender({
    defaultTagName: "button",
    props: mergeProps<"button">(
      {
        className: cn("nds-sidebar-group-action", className),
      },
      props
    ),
    render,
    state: {
      slot: "sidebar-group-action",
      sidebar: "group-action",
    },
  })
}

function SidebarGroupContent({
  className,
  ...props
}: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sidebar-group-content"
      data-sidebar="group-content"
      className={cn("nds-sidebar-group-content", className)}
      {...props}
    />
  )
}

function SidebarMenu({ className, ...props }: React.ComponentProps<"ul">) {
  return (
    <ul
      data-slot="sidebar-menu"
      data-sidebar="menu"
      className={cn("nds-sidebar-menu", className)}
      {...props}
    />
  )
}

function SidebarMenuItem({ className, ...props }: React.ComponentProps<"li">) {
  return (
    <li
      data-slot="sidebar-menu-item"
      data-sidebar="menu-item"
      className={cn("nds-sidebar-menu-item", className)}
      {...props}
    />
  )
}

const sidebarMenuButtonVariants = cva("nds-sidebar-menu-button", {
  variants: {
    variant: {
      default: "",
      outline: "nds-sidebar-menu-button-outline",
    },
    size: {
      default: "",
      sm: "",
      lg: "",
    },
  },
  defaultVariants: {
    variant: "default",
    size: "default",
  },
})

/**
 * Serialização de `active` como `data-active="true"`.
 *
 * A conversão automática de estado em atributo trata flag booleana como
 * atributo presente e vazio (`data-active=""`). A folha compartilhada do design
 * system casa `[data-active="true"]`, que é o que as demais implementações
 * emitem — com o atributo vazio, a regra de item ativo não pintava nada aqui.
 * O mapeamento devolve o valor textual e omite o atributo quando inativo, igual
 * às outras: presença do atributo é o próprio estado.
 */
const stateActiveAsText = {
  active: (active: boolean) => (active ? { "data-active": "true" } : null),
}

function SidebarMenuButton({
  render,
  isActive = false,
  variant = "default",
  size = "default",
  tooltip,
  className,
  ...props
}: useRender.ComponentProps<"button"> &
  React.ComponentProps<"button"> & {
    isActive?: boolean
    tooltip?: string | React.ComponentProps<typeof TooltipContent>
  } & VariantProps<typeof sidebarMenuButtonVariants>) {
  const { isMobile, state } = useSidebar()
  const comp = useRender({
    defaultTagName: "button",
    props: mergeProps<"button">(
      {
        className: cn(sidebarMenuButtonVariants({ variant, size }), className),
      },
      props
    ),
    render: !tooltip ? render : <TooltipTrigger render={render} />,
    state: {
      slot: "sidebar-menu-button",
      sidebar: "menu-button",
      size,
      active: isActive,
    },
    stateAttributesMapping: stateActiveAsText,
  })

  if (!tooltip) {
    return comp
  }

  if (typeof tooltip === "string") {
    tooltip = {
      children: tooltip,
    }
  }

  return (
    /**
     * O balão só faz sentido com a barra recolhida em ícones: é ali que o
     * rótulo do item some. Antes ele era montado sempre e apenas ESCONDIDO por
     * `hidden` — e um balão escondido continua sendo um flutuante ABERTO. Ele
     * abria ao foco e engolia o Escape (a lib fecha o flutuante mais interno e
     * interrompe a propagação): dentro da gaveta móvel, quem navega por teclado
     * precisava apertar Escape DUAS vezes para fechá-la, e a primeira não
     * fechava nada visível. `disabled` impede a abertura em vez de tapar o
     * resultado — e mantém a árvore estável, porque desmontar o `Tooltip` aqui
     * remontaria o próprio botão e derrubaria o foco a cada recolhimento.
     */
    <Tooltip disabled={state !== "collapsed" || isMobile}>
      {comp}
      <TooltipContent side="right" align="center" {...tooltip} />
    </Tooltip>
  )
}

function SidebarMenuAction({
  className,
  render,
  showOnHover = false,
  ...props
}: useRender.ComponentProps<"button"> &
  React.ComponentProps<"button"> & {
    showOnHover?: boolean
  }) {
  return useRender({
    defaultTagName: "button",
    props: mergeProps<"button">(
      {
        className: cn(
          "nds-sidebar-menu-action",
          showOnHover && "nds-sidebar-menu-action-hover",
          className
        ),
      },
      props
    ),
    render,
    state: {
      slot: "sidebar-menu-action",
      sidebar: "menu-action",
    },
  })
}

function SidebarMenuBadge({
  className,
  ...props
}: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sidebar-menu-badge"
      data-sidebar="menu-badge"
      className={cn("nds-sidebar-menu-badge", className)}
      {...props}
    />
  )
}

function SidebarMenuSkeleton({
  className,
  showIcon = false,
  ...props
}: React.ComponentProps<"div"> & {
  showIcon?: boolean
}) {
  // Random width between 50 to 90%.
  const [width] = React.useState(() => {
    return `${Math.floor(Math.random() * 40) + 50}%`
  })

  return (
    <div
      data-slot="sidebar-menu-skeleton"
      data-sidebar="menu-skeleton"
      className={cn("nds-sidebar-menu-skeleton", className)}
      {...props}
    >
      {showIcon && (
        <Skeleton
          className="nds-sidebar-menu-skeleton-icon"
          data-sidebar="menu-skeleton-icon"
        />
      )}
      <Skeleton
        className="nds-sidebar-menu-skeleton-text"
        data-sidebar="menu-skeleton-text"
        style={
          {
            "--skeleton-width": width,
          } as React.CSSProperties
        }
      />
    </div>
  )
}

function SidebarMenuSub({ className, ...props }: React.ComponentProps<"ul">) {
  return (
    <ul
      data-slot="sidebar-menu-sub"
      data-sidebar="menu-sub"
      className={cn("nds-sidebar-menu-sub", className)}
      {...props}
    />
  )
}

function SidebarMenuSubItem({
  className,
  ...props
}: React.ComponentProps<"li">) {
  return (
    <li
      data-slot="sidebar-menu-sub-item"
      data-sidebar="menu-sub-item"
      className={cn("nds-sidebar-menu-sub-item", className)}
      {...props}
    />
  )
}

function SidebarMenuSubButton({
  render,
  size = "md",
  isActive = false,
  className,
  ...props
}: useRender.ComponentProps<"a"> &
  React.ComponentProps<"a"> & {
    size?: "sm" | "md"
    isActive?: boolean
  }) {
  return useRender({
    defaultTagName: "a",
    props: mergeProps<"a">(
      {
        className: cn("nds-sidebar-menu-sub-button", className),
      },
      props
    ),
    render,
    state: {
      slot: "sidebar-menu-sub-button",
      sidebar: "menu-sub-button",
      size,
      active: isActive,
    },
    stateAttributesMapping: stateActiveAsText,
  })
}

export {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupAction,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInput,
  SidebarInset,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSkeleton,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  SidebarProvider,
  SidebarRail,
  SidebarSeparator,
  SidebarTrigger,
  useSidebar,
}
