// nortear-design-system-angular/src/components/ui/skeleton.ts
import { Directive, input } from '@angular/core';

// ─── Skeleton ─────────────────────────────────────────────────────────────────
//
// Visual: classe .nds-skeleton (docs/shared/styles/nds/skeleton.css), que já
// traz o pulso e o respeito a `prefers-reduced-motion`.
//
// Sem dimensão própria e sem inputs de tamanho: a caixa vem de `data-shape`,
// `data-width` e `data-size`, e a folha continua dona de todas as medidas —
// dimensão fixa no componente daria sempre o retângulo errado, e valor de design
// em `style` deixaria tema, densidade e escala de texto para trás.
//
// `aria-hidden` fixo, não configurável: o esqueleto é ruído para leitor de tela.
// Quem anuncia o carregamento é a REGIÃO que espera o conteúdo — e ela é peça
// desta casa, o `NdsSkeletonRegion` abaixo.

@Directive({
  selector: 'div[ndsSkeleton]',
  standalone: true,
  host: {
    class: 'nds-skeleton',
    '[attr.data-slot]': '"skeleton"',
    '[attr.aria-hidden]': '"true"',
  },
})
export class NdsSkeleton {}

// ─── NdsSkeletonRegion ────────────────────────────────────────────────────────
//
// A região que ESPERA o conteúdo, e que é quem fala: o esqueleto sai
// `aria-hidden`, então sem ela o carregamento não é anunciado a ninguém.
//
// Existe como peça porque o trio é indivisível e vinha sendo remontado à mão em
// cada superfície — cinco stacks, cinco formas diferentes do mesmo contêiner:
//
// - `role="status"`, porque `aria-busy` sozinho num `div` sem papel não é
//   anunciado;
// - `aria-busy="true"`, que é o estado;
// - nome acessível por `aria-label`, porque nome em elemento sem papel é
//   atributo proibido — o leitor de tela o descarta e o axe acusa
//   `aria-prohibited-attr`.
//
// `aria-busy` é FIXO em "true" e a peça não o alterna: quando o conteúdo chega,
// a região SAI do template e o conteúdo real entra no lugar dela (decisão da
// dona, 2026-09-14). Por isso não há input de estado.
//
// Papel e estado não são sobrescrevíveis, e aqui isso sai do próprio mecanismo:
// a diretiva não expõe input de `role` nem de `aria-busy`, e host binding APAGA
// o atributo estático que quem usa escrever no template — `role="region"` ao
// lado de `ndsSkeletonRegion` renderiza `status`.
//
// `label` é obrigatório de propósito: região sem nome é o defeito que esta peça
// existe para impedir, e um default genérico o esconderia.
//
// Sem CSS própria: quem compõe põe `nds-stack`/`nds-grid` no próprio elemento,
// porque o arranjo é do bloco que carrega, não da região. E é diretiva, não
// componente — não há markup a montar nem conteúdo a projetar além do que já
// está no template de quem usa.
//
// UMA região por BLOCO, nunca por peça: cinco itens de três esqueletos cada
// viriam a ser quinze avisos repetindo a mesma frase.

@Directive({
  selector: 'div[ndsSkeletonRegion]',
  standalone: true,
  host: {
    '[attr.data-slot]': '"skeleton-region"',
    '[attr.role]': '"status"',
    '[attr.aria-busy]': '"true"',
    '[attr.aria-label]': 'label()',
  },
})
export class NdsSkeletonRegion {
  /** O que está carregando, por extenso — vira o nome acessível da região. */
  readonly label = input.required<string>();
}

/** A família inteira — conveniência para o `imports` de quem compõe. */
export const NDS_SKELETON = [NdsSkeleton, NdsSkeletonRegion] as const;

// nortear-design-system-react/src/components/ui/skeleton.tsx
import { cn } from "@/lib/utils"

// A caixa do esqueleto vem de `data-shape` / `data-width` (ver
// docs/shared/styles/nds/skeleton.css), nunca de altura cravada: altura é
// resultado de padding + tipografia, para o bloco crescer junto quando a
// pessoa aumenta a fonte do navegador (guideline 12, WCAG 1.4.4).
//
// `aria-hidden` sai marcado de fábrica e NÃO é sobrescrevível — o placeholder é
// ruído para leitor de tela, e quem anuncia o carregamento é a região que o
// contém. Por isso os atributos fixos vêm DEPOIS do espalhamento: em JSX quem
// escreve por último vence.
function Skeleton({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      {...props}
      data-slot="skeleton"
      aria-hidden="true"
      className={cn("nds-skeleton", className)}
    />
  )
}

/**
 * A região que ESPERA o conteúdo — e que é quem anuncia a espera.
 *
 * Peça do design system desde 2026-09-13, por decisão da dona: as cinco docs
 * pages montavam este contêiner à mão e tinham divergido em cinco formas (uma
 * delas sem `role="status"`). Regra que cada consumidor executa por conta é
 * regra que se perde no quinto consumidor.
 *
 * Os três atributos andam juntos, e cada um tem motivo próprio:
 * - `role="status"` — `aria-busy` sozinho num `div` sem papel não é anunciado, e
 *   nome acessível sem papel é atributo proibido;
 * - `aria-busy="true"` — é o estado, e é FIXO: a região não alterna para
 *   `false`. Quando o conteúdo chega, ela SAI e o conteúdo entra no lugar dela
 *   (decisão da dona, 2026-09-14). Região vazia deixada para trás continuaria
 *   dizendo que algo carrega;
 * - `label` obrigatório — uma região `status` sem nome não é alcançável pela
 *   lista de regiões, e "carregando" sem dizer o quê não orienta.
 *
 * Papel, estado e nome NÃO são sobrescrevíveis: saem do tipo das props e são
 * escritos depois do espalhamento, então nem um `role`/`aria-busy` passado por
 * cast chega ao DOM.
 *
 * `status` já é região viva por definição, então NÃO se acrescenta `aria-live`
 * aqui, e nem uma segunda região dentro desta: uma região por BLOCO, nunca por
 * peça — cinco linhas de esqueleto numa lista são uma espera só.
 *
 * Não tem CSS próprio de propósito: o layout é de quem compõe, por `className`
 * (`nds-stack`, `nds-grid`, `nds-cluster`).
 */
type SkeletonRegionProps = Omit<
  React.ComponentProps<"div">,
  "role" | "aria-busy" | "aria-label"
> & { label: string }

function SkeletonRegion({ label, className, children, ...props }: SkeletonRegionProps) {
  return (
    <div
      {...props}
      data-slot="skeleton-region"
      role="status"
      aria-busy="true"
      aria-label={label}
      className={className}
    >
      {children}
    </div>
  )
}

export { Skeleton, SkeletonRegion }
export type { SkeletonRegionProps }
