// nortear-design-system-angular/src/components/ui/table.ts
import {
  booleanAttribute,
  computed,
  Directive,
  ElementRef,
  inject,
  input,
} from '@angular/core';

// ─── Table ────────────────────────────────────────────────────────────────────
//
// Visual: classes .nds-table-wrapper e .nds-table (docs/shared/styles/nds/table.css).
//
// SEM primitivo do `@radix-ng/primitives`: o pacote não publica subcaminho
// `table` — e não haveria o que compor. Tabela de dados é markup semântico
// nativo: `<table>` / `<thead>` / `<tbody>` / `<tfoot>` / `<tr>` / `<th>` /
// `<td>` / `<caption>` já entregam papel, relação linha-coluna e leitura em
// ordem. O que um leitor de tela precisa a mais são dois atributos (`scope` no
// cabeçalho, `aria-sort` na coluna ordenada) e uma legenda — nada de estado,
// foco gerenciado ou navegação por teclado própria.
//
// Por isso a família inteira é de DIRETIVA de atributo, nunca `@Component`:
// nenhum subcomponente tem markup próprio nem projeta conteúdo (o conteúdo da
// célula é filho do `<td>` que a pessoa escreveu, no template dela). Um
// `@Component` com `template: '<ng-content />'` criaria view e ciclo de
// detecção para reemitir o que já estava lá — e, pior, um `<ng-content>` dentro
// de `<tr>` arriscaria o parser de HTML mover o conteúdo para fora da tabela.
//
// O DOM resultante é idêntico ao do Vanilla, que é a referência cross-stack.
//
// ─── Por que o wrapper é explícito aqui ───────────────────────────────────────
//
// React e Vanilla envolvem o `<table>` num `<div class="nds-table-wrapper">`
// por dentro do componente. Uma diretiva de atributo NÃO pode fazer isso: o
// host dela É o `<table>`, e não existe como criar um pai. Então o wrapper é um
// elemento que quem usa escreve, com `ndsTableWrapper` — é o que o snippet
// `anatomy.structureCode.angular` do conteúdo compartilhado já contrata.
//
// Divergência de API de framework, não de markup: o HTML final é o mesmo nas
// cinco stacks.

/**
 * Container rolável da tabela — `<div ndsTableWrapper>`.
 *
 * `.nds-table-wrapper` é `overflow-x: auto`, e região rolável precisa ser
 * alcançável por teclado: quem navega sem mouse não tem outro jeito de chegar
 * às colunas que ficaram fora da caixa (WCAG 2.1.1, regra `scrollable-region-focusable`
 * do axe). O `tabindex` é fixo, e não input, pelo mesmo motivo do Vanilla, onde
 * a factory o crava: torná-lo configurável só criaria a opção de desligar a
 * única coisa que faz a rolagem existir para o teclado.
 */
@Directive({
  selector: 'div[ndsTableWrapper]',
  standalone: true,
  host: {
    class: 'nds-table-wrapper',
    '[attr.data-slot]': '"table-container"',
    '[attr.tabindex]': '"0"',
    '[attr.role]': 'regionLabel() ? "group" : null',
    '[attr.aria-label]': 'regionLabel() || null',
  },
})
export class NdsTableWrapper {
  /**
   * Nome acessível do container que rola. Sem padrão, de propósito.
   *
   * O container é o WRAPPER, e não a `<table>`: cada um tem o seu nome, e um
   * nome escrito na tabela nomeia a TABELA — comportamento certo, que não se
   * quer roubar. Por isso a entrada tem nome próprio e não é `aria-label`.
   *
   * O nome é do CONTEÚDO ("Faturas de 2026"), e o design system não tem como
   * sabê-lo; padrão genérico ("Tabela") anunciaria sem informar. Sem nome NÃO
   * emitimos papel nenhum — o axe acusa `aria-prohibited-attr`.
   *
   * `group` e não `region`: uma tela de relatório empilha várias tabelas, e
   * seriam vários marcos onde não há várias seções.
   */
  readonly regionLabel = input<string>('');
}

/** A tabela em si — `<table ndsTable>`. Só ela carrega classe; o CSS alcança as
 * seções por descendência (`.nds-table thead tr`, `.nds-table td`…). */
@Directive({
  selector: 'table[ndsTable]',
  standalone: true,
  host: {
    class: 'nds-table',
    '[attr.data-slot]': '"table"',
  },
})
export class NdsTable {}

/** Cabeçalho da tabela — `<thead ndsTableHeader>`. */
@Directive({
  selector: 'thead[ndsTableHeader]',
  standalone: true,
  host: { '[attr.data-slot]': '"table-header"' },
})
export class NdsTableHeader {}

/** Corpo da tabela — `<tbody ndsTableBody>`. */
@Directive({
  selector: 'tbody[ndsTableBody]',
  standalone: true,
  host: { '[attr.data-slot]': '"table-body"' },
})
export class NdsTableBody {}

/**
 * Rodapé da tabela — `<tfoot ndsTableFooter>`.
 *
 * É onde total e sumário vivem. Uma linha de `<tbody>` faria o mesmo desenho e
 * seria lida como mais um registro; o `tfoot` é anunciado como rodapé.
 */
@Directive({
  selector: 'tfoot[ndsTableFooter]',
  standalone: true,
  host: { '[attr.data-slot]': '"table-footer"' },
})
export class NdsTableFooter {}

/**
 * Linha — `<tr ndsTableRow>`.
 *
 * `selected` liga o `data-state="selected"` que o CSS compartilhado pinta. O
 * atributo escrito à mão (`<tr ndsTableRow data-state="selected">`, como as
 * outras stacks fazem nas fixtures) continua valendo: sem essa leitura o host
 * binding devolveria `null` e APAGARIA em silêncio o estado que a pessoa
 * escreveu — binding roda depois de atributo estático.
 *
 * Ler o atributo no construtor é seguro; ler um `input()` ali não seria (o
 * binding de quem consome ainda não foi aplicado — armadilha 9 do CLAUDE.md).
 */
@Directive({
  selector: 'tr[ndsTableRow]',
  standalone: true,
  host: {
    '[attr.data-slot]': '"table-row"',
    '[attr.data-state]': 'state()',
  },
})
export class NdsTableRow {
  /**
   * Marca a linha como selecionada. `booleanAttribute` para aceitar a forma
   * curta `<tr ndsTableRow selected>`, como o HTML faz com `disabled`.
   */
  readonly selected = input(false, { transform: booleanAttribute });

  private readonly estadoEscrito = inject<ElementRef<HTMLTableRowElement>>(
    ElementRef,
  ).nativeElement.getAttribute('data-state');

  protected readonly state = computed(() =>
    this.selected() ? 'selected' : this.estadoEscrito,
  );
}

/** Direção da ordenação exposta em `aria-sort`. */
export type TableSortDirection = 'ascending' | 'descending' | 'none';

/**
 * Célula de cabeçalho — `<th ndsTableHead>`.
 *
 * `scope` nasce em `"col"` porque é o caso de longe mais comum e porque uma
 * tabela sem `scope` é uma grade muda: o leitor de tela lê os valores sem dizer
 * de que coluna vieram (WCAG 1.3.1). Quem tem cabeçalho de linha escreve
 * `scope="row"` — o Angular aplica o atributo estático ao input de mesmo nome,
 * então a forma nativa continua sendo a forma certa de escrever.
 *
 * `sort` só emite `aria-sort` quando a coluna é de fato ordenável. Emitir
 * `aria-sort="none"` em coluna que não ordena anuncia uma capacidade que não
 * existe; por isso o default é `undefined`, e não `'none'`.
 */
@Directive({
  selector: 'th[ndsTableHead]',
  standalone: true,
  host: {
    '[attr.data-slot]': '"table-head"',
    '[attr.scope]': 'scope()',
    '[attr.aria-sort]': 'sort() ?? null',
  },
})
export class NdsTableHead {
  readonly scope = input<'col' | 'row' | 'colgroup' | 'rowgroup'>('col');
  readonly sort = input<TableSortDirection | undefined>(undefined);
}

/** Célula de dados — `<td ndsTableCell>`. `colspan`/`rowspan` são atributos
 * nativos e não viram input: quem escreve o HTML já os tem. */
@Directive({
  selector: 'td[ndsTableCell]',
  standalone: true,
  host: { '[attr.data-slot]': '"table-cell"' },
})
export class NdsTableCell {}

/**
 * Legenda — `<caption ndsTableCaption>`.
 *
 * O leitor de tela a anuncia antes das células, então ela é o que dá contexto à
 * grade. Quando o título já está visível na página, some visualmente com
 * `class="nds-sr-only"` em vez de removê-la: o `.nds-table` é `caption-side: bottom`,
 * e uma tabela sem caption chega ao leitor sem nome nenhum.
 */
@Directive({
  selector: 'caption[ndsTableCaption]',
  standalone: true,
  host: { '[attr.data-slot]': '"table-caption"' },
})
export class NdsTableCaption {}

// nortear-design-system-react/src/components/ui/table.tsx
import type * as React from "react"

import { cn } from "@/lib/utils"

/**
 * Nome acessível do container que rola. SEM PADRÃO, de propósito.
 *
 * O container é o WRAPPER, e não a `<table>`: são elementos diferentes e cada um
 * tem o seu nome. Por isso a prop tem nome próprio e não é `aria-label` — um
 * `aria-label` escrito aqui nomeia a TABELA, que é o comportamento certo e que
 * não se quer roubar. O wrapper é o que quem monta não alcança, e é ele que entra
 * na ordem de tabulação.
 *
 * O nome é do CONTEÚDO ("Faturas de 2026"), e o design system não tem como
 * sabê-lo. Padrão genérico ("Tabela") anunciaria sem informar: quem chegou por Tab
 * já sabe que rola, o que não sabe é o que rola. Sem nome NÃO emitimos papel
 * nenhum — `aria-label` em elemento sem papel é atributo proibido, e o axe acusa
 * `aria-prohibited-attr`.
 *
 * `group` e não `region`: `region` com nome vira marco de página, e uma tela de
 * relatório empilha várias tabelas — seriam vários marcos onde não há várias
 * seções. Quem quiser marco envolve a tabela num `<section>` nomeado.
 */
type TableProps = React.ComponentProps<"table"> & { regionLabel?: string }

function Table({ className, regionLabel, ...props }: TableProps) {
  return (
    <div
      data-slot="table-container"
      className="nds-table-wrapper"
      // .nds-table-wrapper tem overflow-x: auto — região rolável precisa ser
      // alcançável por teclado (WCAG 2.1.1 / axe scrollable-region-focusable)
      // E precisa de papel e nome, que é a outra metade da regra: foco sozinho
      // faz uma parada que o leitor de tela não sabe anunciar.
      tabIndex={0}
      role={regionLabel ? "group" : undefined}
      aria-label={regionLabel}
    >
      <table
        data-slot="table"
        className={cn("nds-table", className)}
        {...props}
      />
    </div>
  )
}

function TableHeader({ className, ...props }: React.ComponentProps<"thead">) {
  return (
    <thead
      data-slot="table-header"
      className={cn(className)}
      {...props}
    />
  )
}

function TableBody({ className, ...props }: React.ComponentProps<"tbody">) {
  return (
    <tbody
      data-slot="table-body"
      className={cn(className)}
      {...props}
    />
  )
}

function TableFooter({ className, ...props }: React.ComponentProps<"tfoot">) {
  return (
    <tfoot
      data-slot="table-footer"
      className={cn(className)}
      {...props}
    />
  )
}

function TableRow({ className, ...props }: React.ComponentProps<"tr">) {
  return (
    <tr
      data-slot="table-row"
      className={cn(className)}
      {...props}
    />
  )
}

// `scope` nasce em "col" porque é o caso de longe mais comum e porque uma tabela
// sem `scope` é uma grade muda: o leitor de tela lê os valores sem dizer de que
// coluna vieram (WCAG 1.3.1). Quem tem cabeçalho de linha passa `scope="row"` e
// sobrescreve — a forma nativa continua sendo a forma certa de escrever.
function TableHead({ className, scope = "col", ...props }: React.ComponentProps<"th">) {
  return (
    <th
      data-slot="table-head"
      scope={scope}
      className={cn(className)}
      {...props}
    />
  )
}

function TableCell({ className, ...props }: React.ComponentProps<"td">) {
  return (
    <td
      data-slot="table-cell"
      className={cn(className)}
      {...props}
    />
  )
}

function TableCaption({
  className,
  ...props
}: React.ComponentProps<"caption">) {
  return (
    <caption
      data-slot="table-caption"
      className={cn(className)}
      {...props}
    />
  )
}

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
}
