// design-system-svelte/src/components/ui/textarea/textarea.svelte
<script lang="ts">
	import { cn, type WithElementRef, type WithoutChildren } from "@/lib/utils.js";
	import type { HTMLTextareaAttributes } from "svelte/elements";

	let {
		ref = $bindable(null),
		value = $bindable(),
		class: className,
		"data-slot": dataSlot = "textarea",
		...restProps
	}: WithoutChildren<WithElementRef<HTMLTextareaAttributes>> = $props();
</script>

<textarea
	bind:this={ref}
	data-slot={dataSlot}
	class={cn(
		"nds-textarea",
		className
	)}
	bind:value
	{...restProps}
></textarea>

// nortear-design-system-react/src/components/ui/textarea.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

// Estilo via .nds-textarea (docs/shared/styles/nds/textarea.css).
function Textarea({ className, ...props }: React.ComponentProps<"textarea">) {
  return (
    <textarea
      data-slot="textarea"
      className={cn("nds-textarea", className)}
      {...props}
    />
  )
}

export { Textarea }
