// nortear-design-system-svelte/src/components/ui/toggle/toggle.svelte
<script lang="ts" module>
	import { cva, type VariantProps } from "class-variance-authority";

	export const toggleVariants = cva("nds-toggle", {
		
		variants: {
			variant: {
				default: "",
				outline: "",
			},
			size: {
				default: "",
				sm: "",
				lg: "",
			},
		},
		defaultVariants: {
			variant: "default",
			size: "default",
		},
	});

	export type ToggleVariant = VariantProps<typeof toggleVariants>["variant"];
	export type ToggleSize = VariantProps<typeof toggleVariants>["size"];
	export type ToggleVariants = VariantProps<typeof toggleVariants>;
</script>

<script lang="ts">
	import { Toggle as TogglePrimitive } from "bits-ui";
	import { cn } from "@/lib/utils.js";

	let {
		ref = $bindable(null),
		pressed = $bindable(false),
		class: className,
		size = "default",
		variant = "default",
		...restProps
	}: TogglePrimitive.RootProps & {
		variant?: ToggleVariant;
		size?: ToggleSize;
	} = $props();
</script>

<TogglePrimitive.Root
	bind:ref
	bind:pressed
	data-slot="toggle"
	data-variant={variant === "default" ? undefined : variant}
	data-size={size === "default" ? undefined : size}
	class={cn(toggleVariants({ variant, size }), className)}
	{...restProps}
/>

// nortear-design-system-react/src/components/ui/toggle.tsx
import { Toggle as TogglePrimitive } from "@base-ui/react/toggle"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

// Estilo via .nds-toggle (docs/shared/styles/nds/toggle.css). Variante e
// tamanho são selecionados por data-variant/data-size no CSS — o cva mantém
// apenas a TIPAGEM das variantes (valores vazios de propósito).
const toggleVariants = cva("nds-toggle", {
  variants: {
    variant: {
      default: "",
      outline: "",
    },
    size: {
      default: "",
      sm: "",
      lg: "",
    },
  },
  defaultVariants: {
    variant: "default",
    size: "default",
  },
})

function Toggle({
  className,
  variant = "default",
  size = "default",
  ...props
}: TogglePrimitive.Props & VariantProps<typeof toggleVariants>) {
  return (
    <TogglePrimitive
      data-slot="toggle"
      data-variant={variant}
      data-size={size}
      className={cn(toggleVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Toggle, toggleVariants }
