// design-system-vue/src/components/docs/shared/sections/DocsStates.vue
<script setup lang="ts">
interface DocsStateItem { label: string; trigger: string; behavior: string }

defineProps<{
  title: string;
  cols: { state: string; trigger: string; behavior: string };
  items: DocsStateItem[];
}>();
</script>

<template>
  <section id="estados">
    <h2 class="text-xl font-semibold mb-4">{{ title }}</h2>
    <div class="rounded-lg border border-border p-4 shadow-sm overflow-x-auto">
      <table class="w-full text-sm">
        <thead>
          <tr class="border-b border-border bg-muted/50 text-left">
            <th class="p-3 border-r border-border font-semibold">{{ cols.state }}</th>
            <th class="p-3 border-r border-border font-semibold">{{ cols.trigger }}</th>
            <th class="p-3 font-semibold">{{ cols.behavior }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(item, i) in items" :key="i" class="border-b border-border last:border-0 hover:bg-muted/5">
            <td class="p-3 border-r border-border font-medium">{{ item.label }}</td>
            <td class="p-3 border-r border-border text-muted-foreground">{{ item.trigger }}</td>
            <td class="p-3 text-muted-foreground">{{ item.behavior }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</template>

// design-system-react/src/components/docs/shared/sections/DocsStates.tsx
import React from 'react';

export interface DocsStateItem {
  label: string;
  trigger: string;
  behavior: string;
}

export interface DocsStatesProps {
  title: string;
  cols: { state: string; trigger: string; behavior: string };
  items: DocsStateItem[];
}

export function DocsStates({ title, cols, items }: DocsStatesProps) {
  return (
    <section id="estados">
      <h2 className="text-xl font-semibold mb-4">{title}</h2>
      <div className="rounded-lg border border-border p-4 shadow-sm overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border bg-muted/50 text-left">
              <th className="p-3 border-r border-border font-semibold">{cols.state}</th>
              <th className="p-3 border-r border-border font-semibold">{cols.trigger}</th>
              <th className="p-3 font-semibold">{cols.behavior}</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item, i) => (
              <tr key={i} className="border-b border-border last:border-0 hover:bg-muted/5">
                <td className="p-3 border-r border-border font-medium">{item.label}</td>
                <td className="p-3 border-r border-border text-muted-foreground">{item.trigger}</td>
                <td className="p-3 text-muted-foreground">{item.behavior}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}
